pom.xml

chore: remove extra profile (#11819)

---

flow-data/src/main/java/com/vaadin/flow/data/binder/SimpleResult.java
flow-data/src/test/java/com/vaadin/flow/data/binder/SimpleResultTest.java

fix: add equals and hashCode to SimpleResult

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePackageJson.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java

Flag update of vaadin version as an addition
also and only write the package.json if
thee was an actual change in content.
Fixes #11259

fix: Only write package.json if something actually changed

---

flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java

fix: make IPhone version above 14.7 browsers allowed for Vaadin (#11821)

---

flow-tests/pom.xml
flow-tests/test-fusion-csrf-context/.gitignore
flow-tests/test-fusion-csrf-context/pom.xml
flow-tests/test-fusion-csrf-context/src/main/java/com/vaadin/fusion/csrftest/MyServlet.java
flow-tests/test-fusion-csrf-context/src/test/java/com/vaadin/fusion/csrftest/CsrfCookieWithTrailingSlashAndCustomContextIT.java
flow-tests/test-fusion-csrf/frontend/index.html
flow-tests/test-fusion-csrf/frontend/index.ts
flow-tests/test-fusion-csrf/frontend/views/helloworld/hello-world-view.ts
flow-tests/test-fusion-csrf/pom.xml
flow-tests/test-fusion-csrf/src/main/java/com/vaadin/fusion/csrftest/MyServlet.java
flow-tests/test-fusion-csrf/src/test/java/com/vaadin/fusion/csrftest/CsrfCookieWithTrailingSlashIT.java
fusion-endpoint/src/main/java/com/vaadin/fusion/auth/CsrfIndexHtmlRequestListener.java

Fixes https://github.com/vaadin/fusion/issues/105

fix: add fusion csrf cookie to correct path

---

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataProvider.java
flow-data/src/main/java/com/vaadin/flow/data/provider/DataChangeEvent.java
flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataProviderTest.java

fix: allow listener removal via DataChangeEvent

---

fusion-endpoint/src/main/java/com/vaadin/fusion/FusionController.java

Fixes https://github.com/vaadin/spring/issues/904

chore: upgrade fusion package version

---

README.md

chore: update flow branch info in readme [skip ci]

---

flow-server/src/main/java/com/vaadin/flow/component/Component.java
flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java

feat: use proper getTranslation

---

flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java

feat: add bindReadOnly methods

---

flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java

Related-to https://github.com/vaadin/flow/issues/11928

test: Ignore component theme live reload test

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java

fix: upgrade to lit 2.0.0 (#11898)

---

flow-data/src/test/java/com/vaadin/flow/data/binder/BinderConverterValidatorTest.java

test: avoid CurrentInstances leaking into the test

---

flow-html-components/src/main/java/com/vaadin/flow/component/html/HtmlObject.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/Param.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlObjectTest.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/ParamTest.java
flow-server/src/main/java/com/vaadin/flow/component/Tag.java

feat: add Object Component to html components module

---

flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java

fix: remove detach listeners from listenOn components on detach owner

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/resources/webpack.generated.js

fix: make webpack respect path aliases in tsconfig

---

flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/test/java/com/vaadin/experimental/FeatureFlagsTest.java

Use correct ApplicationConfiguration with
FeatureFlags configuration.
Fixes #12195

fix: Use correct configuration in FeatureFlags

---

flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/FeatureView.java
flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/FeatureIT.java

Add a test that enables a feature through
the gizmo features tab.

test: Add feature test to validate enabling feature.

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendWebComponentGenerator.java
flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriter.java
flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriterTest.java

chore: simplify web components generation avoiding reflective call

---

flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java

fix: Only log RouteNotFoundError if debugging is enabled

---

flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java

chore: Close input stream after using it

---

pom.xml

chore: update testbench version

---

pom.xml

This reverts commit 20db22cc
Reverted to see whether the TestBench upgrade is the reason of random failures in IT tests.

Revert "chore: update testbench version (#12257)"

---

flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.properties

chore: upgrade gradle 7.3

---

flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java

feat: Enable serving Brotli resources by default

---

flow-server/src/main/resources/vite.generated.ts

fix: Use correct URL for generated/vaadin.ts

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTsTest.java
fusion-endpoint/src/main/java/com/vaadin/fusion/generator/GenerationOutputDirectory.java
fusion-endpoint/src/test/java/com/vaadin/fusion/frontend/NodeTasksEndpointTest.java

fix: Write generated index.ts to frontend/generated

---

flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java

fix: Update supported browser versions to those that support globalThis

---

flow-server/src/main/resources/vite.generated.ts
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java

fix: Make Vite serve the index page only when using the exact URL of it

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateSettingsFile.java
flow-server/src/main/resources/vite.generated.ts
flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/FileAccessIT.java

fix: Restrict which files Vite publishes

---

flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BasicsIT.java
flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/FileAccessIT.java
flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ThemeReloadIT.java
flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ViteDevModeIT.java

Wait for an element on the main page to load before
commencing tests.

chore: stabilize vite dev-mode ITs

---

flow-dnd/pom.xml
flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java

Bumps the version and fixes the mitch-match of polyfill version.
Related to #12315
Fixes #8014

fix: fix the mobile-dnd polyfill versions

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/ExtraNodeTestComponents.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ClassFinderTest.java

fix: Make ClassFinder deterministic

---

flow-dnd/pom.xml
flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java

Bumps the version and fixes the mitch-match of polyfill version.
Related to #12315
Fixes #8014

fix: fix the mobile-dnd polyfill versions (#12438) (CP: 8.0)

---

flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java

feat: Make it easier to see the relevant part of InternalServerError

---

flow-client/src/main/java/com/vaadin/client/flow/StateTree.java
flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
flow-client/src/main/java/com/vaadin/client/flow/dom/DomNode.java
flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java
flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBusUtil.java
flow-server/src/main/java/com/vaadin/flow/dom/DomEvent.java
flow-server/src/main/java/com/vaadin/flow/dom/DomListenerRegistration.java
flow-server/src/main/java/com/vaadin/flow/shared/JsonConstants.java
flow-server/src/test/java/com/vaadin/flow/component/ComponentEventBusTest.java
flow-server/src/test/java/com/vaadin/flow/component/MappedDomEventWithComponentData.java
flow-server/src/test/java/com/vaadin/flow/component/MappedDomEventWithRouterLinkData.java
flow-server/src/test/java/com/vaadin/flow/component/MappedToDomEventWithElementData.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementListenersTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/AbstractEventDataView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ComponentEventDataView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/EventTargetView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AbstractEventDataIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ComponentEventDataIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/EventTargetIT.java

CP: Element and Component as event data support for 2.8

---

.github/workflows/validation.yml
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PushLongPollingUpdateDivIT.java

Related to https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

chore: add option to run manually validation action

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/RepeatedAnnotationVisitor.java

fix: Updated ASM8 to ASM9 (#12487)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

Related to https://github.com/advisories/GHSA-896r-f27r-55mw

chore: Upgrade workbox

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/test/java/com/vaadin/flow/component/UITest.java

fix: Do not throw NPE for UI.access called when session has expired

---

flow-plugins/flow-gradle-plugin/pom.xml

It seems that causes problems in Bender. Let's revert it until fixed

Revert "chore: replace exec-maven-plugin with gradle-maven-plugin (#12501)

---

flow-plugins/flow-gradle-plugin/pom.xml

This reverts commit 193d65b61bff8350470d5248320ba2ff27fba9ad.

Revert "chore: replace exec-maven-plugin with gradle-maven-plugin (#12501) (#12545)"

---

flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java

feat: Only send index.html when the browser requests a HTML page

---

flow-migration/src/test/java/com/vaadin/flow/migration/RewriteLegacyAnnotationsStepTest.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java

chore: close streams (#12491)

---

flow-client/src/main/frontend/Flow.ts
flow-client/src/main/frontend/FlowBootstrap.js
flow-client/src/main/frontend/VaadinDevmodeGizmo.ts

Fixes: https://github.com/vaadin/flow/issues/12539

chore: Fix linting warnings

---

flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/utils/LookupImpl.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendWebComponentGenerator.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriter.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullScannerPwaTest.java
flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriterTest.java

Do not squash!
This reverts commit 51837be and 7b9666765a2ed67341a73a83492211d8fabdedcf due to Maven plugin classloader throwing ClassNotFoundException for Spring classes during class scanning.

Revert use maven plugin classloader as parent

---

flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java

Checkign the logs for errors will
wait for vaadin to be ready also.

test: Wait for vaadin to be ready

---

fusion-endpoint/src/main/java/com/vaadin/fusion/FusionController.java

Upgrade `@vaadin/fusion-frontend` and `@vaadin/form` to 0.0.16.
See https://github.com/vaadin/fusion/releases/tag/0.0.16

feat: upgrade Fusion npm packages to 0.0.16

---

.github/workflows/sonar.yml
pom.xml

This is a draft on top of @Artur- 's branch bringing java 11 to master

chore: introduce sonar cloud validation

---

flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java

fix: Proper handling of href when the anchor is disabled/enabled (#12616)

---

flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java
flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
flow-server/src/test/java/com/vaadin/flow/server/StreamResourceTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/StreamResourceHandlerTest.java

Fixes #5471
(cherry picked from commit 508c0c414a610c52df76ab7cd0a2cf37f465b769)

feat: add possibility to set header values for StreamResource (#11860) (CP: 2.8)

---

flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java
flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
flow-server/src/test/java/com/vaadin/flow/server/StreamResourceTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/StreamResourceHandlerTest.java

Fixes #5471
(cherry picked from commit 508c0c414a610c52df76ab7cd0a2cf37f465b769)

feat: add possibility to set header values for StreamResource (#11860) (CP: 2.7)

---

flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBuild.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java

These options are not really useful for anything and just makes the code more complex

chore!: remove webpackTemplate and webpackGeneratedTemplate options

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java

fix: check if --openssl-legacy-provider required for Node

---

flow-server/src/main/java/com/vaadin/flow/internal/UsageStatistics.java
flow-server/src/test/java/com/vaadin/experimental/FeatureFlagsTest.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java

Fixes for UsageStatistics to keep the methods same in 9.0 and 10.0
Rebase.

UsageStatistics fixes from master

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
flow-server/src/test/java/com/vaadin/tests/server/SerializationTest.java

fix: Fix serialization of a recently deserialized session

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

This reverts commit 45387fbaa3652021184f9b159641a27104809ddd.

Revert "fix: Force an older babel version (#12781) (#12792)"

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

This reverts commit 0208c4a4d94c6af067c5e8ce44d6d63e7a6a2a3d.

Revert "fix: Force an older babel version (#12781)"

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

This reverts commit 64126cc91d9e429d20bb4db5af8a5157f3f35ba9.

Revert "fix: Force an older babel version (#12781) (#12790)"

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java

fix: install all packages from versions.json also when using pnpm

---

flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
flow-tests/test-root-context/pom.xml
pom.xml

with Selenium 4
update imports for changes classes
add osgi.annotation dependency in test module

feat!: Update to Testbench 8

---

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java

Fixes a deserialization problem https://bender.vaadin.com/viewLog.html?buildId=283152&buildTypeId=FlowComponents_Snapshot

fix: do not store UI reference in DataCommunicator

---

flow-client/package.json

fix: update node-fetch to 2.6.7

---

flow-client/package.json

fix: update node-fetch to 2.6.7 (#12844)

---

flow-plugins/flow-gradle-plugin/build.gradle
flow-tests/test-npm-only-features/test-npm-performance-regression/pom.xml

Remove overrding junit in test.
Update gradle junit version

chore: update junit versions

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-tests/test-frontend/test-npm/package-lock.json
flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml

Update css-loader to get a
newer version of postcss

fix: update css-loader

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-tests/test-frontend/pom.xml
flow-tests/test-frontend/test-npm/package-lock.json
flow-tests/test-frontend/test-npm/pom-production.xml
flow-tests/test-frontend/test-npm/pom.xml
flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml
flow-tests/test-frontend/test-pnpm/pom-production.xml
flow-tests/test-frontend/test-pnpm/pom.xml
pom.xml

Update webpack-cli and webpack-dev-server
to get newer dependencies.
Fixes dependabot alert

fix: update webpack versions

---

flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java

fix: Use service already assigned (#12808) (#12835)

---

vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevServerOutputTracker.java

fix: Do not print frontend build error when stopping the server

---

flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java

Ignore test until fixed.
See #11928

test: ignore broken test

---

fusion-endpoint/src/main/java/com/vaadin/fusion/FusionController.java

Upgrade Fusion npm package version, which has the following fixes:
* Clears the JWT cookie on logout https://github.com/vaadin/hilla/issues/49
* Support empty Size validator without arguments https://github.com/vaadin/hilla/pull/154
* Handle Spring CSRF as string undefined in meta tags https://github.com/vaadin/hilla/pull/187

fix: upgrade fusion npm pkg version to fix bugs

---

flow-tests/vaadin-spring-tests/pom.xml
flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
pom.xml

Update jaxb-runtime to a version
compatible with jdk17
Fixes vaadin/spring#981

fix: Update jaxb-runtime

---

flow-tests/vaadin-spring-tests/test-spring-common/pom.xml

Remove the polymer webjar dependency.

test: Remove polymer webjar

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/test/java/com/vaadin/flow/component/UITest.java

Add methods to check if there is a
modal component set and to add
component to current modal component.
Fixes #12992

feat: Add modality helpers

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-tests/test-frontend/test-npm/package-lock.json

dependabot alert re transitive dependency
follow-redirect

chore: update webpack-dev-server

---

flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-tests/test-frontend/test-npm/package-lock.json

Picks to 23 from master

---

flow-server/src/main/java/com/vaadin/flow/server/Platform.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ServerInfo.java

No squash.  Store platform in `nodes_modules` and comment fix commit.

Cherry picks from master to 23.0

---

flow-server/src/main/resources/webpack.generated.js

fix: Fix usage of deprecated webpack API

---

flow-server/src/main/resources/vite.generated.ts

Fixes the duplicate that is a result of an inaccurate rebase performed in #12941.

fix: remove the duplicate of optimizeDeps.entries

---

flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementListenerMap.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementListenersTest.java

Manual cherry pick of https://github.com/vaadin/flow/pull/13021

fix: Get boolean only if eventData has the key

---

flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/FeatureIT.java

test: do not leave server in Vite state

---

fusion-endpoint/src/main/java/dev/hilla/EndpointController.java
fusion-endpoint/src/main/java/dev/hilla/EndpointControllerConfiguration.java
fusion-endpoint/src/main/java/dev/hilla/EndpointInvoker.java
fusion-endpoint/src/test/java/dev/hilla/EndpointControllerConfigurationTest.java
fusion-endpoint/src/test/java/dev/hilla/EndpointControllerMockBuilder.java
fusion-endpoint/src/test/java/dev/hilla/EndpointControllerTest.java
vaadin-spring/src/test/java/com/vaadin/flow/spring/AbstractDevModeBrowserLauncherTest.java
vaadin-spring/src/test/java/com/vaadin/flow/spring/security/RequestUtilTest.java
vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinDefaultRequestCacheTest.java

The EndpointInvoker still has knowledge of an HTTP request at this point.
It should be refactored out later.

refactor: Split method invocation part out to EndpointInvoker

---

flow-server/src/main/java/com/vaadin/flow/component/Key.java

fix: Alter handling of cases where key value is not present

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinDefaultRequestCache.java
vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinDefaultRequestCacheTest.java

Never save /error as the navigation target after login

---

flow-tests/test-frontend/vite-context-path/src/test/java/com/vaadin/viteapp/BundlesIT.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ActivatePushView.java
flow-tests/vaadin-spring-tests/test-spring-security-flow-urlmapping/src/main/java/com/vaadin/flow/spring/flowsecurityurlmapping/Application.java
flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/UserInfoEndpoint.java
flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/src/main/java/com/vaadin/flow/spring/fusionsecurityurlmapping/Application.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java

Using find . -type f -name "*.java"|xargs java -jar google-java-format-1.14.0-all-deps.jar --fix-imports-only --skip-sorting-imports  -r

chore: Remove unused imports

---

.github/workflows/validation.yml
flow-tests/vaadin-spring-tests/pom.xml
flow-tests/vaadin-spring-tests/test-endpoints-latest-java/frontend/index.html
flow-tests/vaadin-spring-tests/test-endpoints-latest-java/frontend/index.ts
flow-tests/vaadin-spring-tests/test-endpoints-latest-java/frontend/test-component.ts
flow-tests/vaadin-spring-tests/test-endpoints-latest-java/pom.xml
flow-tests/vaadin-spring-tests/test-endpoints-latest-java/src/main/java/com/vaadin/flow/connect/AppEndpoint.java
flow-tests/vaadin-spring-tests/test-endpoints-latest-java/src/main/java/com/vaadin/flow/connect/Application.java
flow-tests/vaadin-spring-tests/test-endpoints-latest-java/src/main/resources/application.properties
flow-tests/vaadin-spring-tests/test-endpoints-latest-java/src/test/java/com/vaadin/flow/connect/AppViewIT.java
fusion-endpoint/src/main/java/dev/hilla/generator/OpenAPIObjectGenerator.java

Fixes https://github.com/vaadin/hilla/issues/216

fix: Allow all Java features when parsing endpoint code

---

flow-data/src/test/java/com/vaadin/flow/data/binder/BeanBinderTest.java
flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/TestSelectComponent.java

Added back to the Flow BeanBinderTest missing tests for select components
Closes #2263

test: Restored BeanBinderTest with tests for select components

---

flow-server/src/main/java/com/vaadin/flow/server/Constants.java
pom.xml

fix: Upgrade to new Atmosphere

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java

Same as #12571 but for V14 bootstrapping mode.
Fixes #10965 for V14 bootstrapping mode.

feat: Only send index.html when the browser requests a HTML page (#13242) (CP: 23.0)

---

flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js

Fixes #13319
<!-- PLEASE READ A

Only import the needed parts of lumo-styles

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java

chore: fix javadoc

---

vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/StatisticsStorage.java

Be more graceful with exceptions when reading usage stats

---

flow-server/src/main/java/com/vaadin/flow/server/Constants.java
pom.xml

chore: Upgrade to Atmosphere 2.7.3

---

flow-tests/test-redeployment/pom.xml
flow-tests/vaadin-spring-tests/pom.xml
flow-tests/vaadin-spring-tests/test-endpoints-latest-java/pom.xml
flow-tests/vaadin-spring-tests/test-mvc-without-endpoints/pom.xml
flow-tests/vaadin-spring-tests/test-spring-boot-contextpath/pom.xml
flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/pom.xml
flow-tests/vaadin-spring-tests/test-spring-boot-scan/pom.xml
flow-tests/vaadin-spring-tests/test-spring-boot-undertow/pom.xml
flow-tests/vaadin-spring-tests/test-spring-boot/pom.xml
flow-tests/vaadin-spring-tests/test-spring-security-flow-contextpath/pom.xml
flow-tests/vaadin-spring-tests/test-spring-security-flow-urlmapping/pom.xml
flow-tests/vaadin-spring-tests/test-spring-security-flow/pom.xml
flow-tests/vaadin-spring-tests/test-spring-security-fusion-contextpath/pom.xml
flow-tests/vaadin-spring-tests/test-spring-security-fusion-jwt/pom.xml
flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/pom.xml
flow-tests/vaadin-spring-tests/test-spring-security-fusion/pom.xml
flow-tests/vaadin-spring-tests/test-spring-white-list/pom.xml
flow-tests/vaadin-spring-tests/test-ts-services-custom-client/pom.xml
flow-tests/vaadin-spring-tests/test-ts-services/pom.xml
fusion-endpoint/pom.xml
pom.xml
vaadin-spring/pom.xml

bump spring-related versions to latest

chore:update spring related version

---

drivers.xml
flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/template/AbstractAttachExistingElementByIdIT.java
flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/template/BundledTemplateInTemplateWithIdIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/EmptyListsIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/imports/LazyWidgetIT.java
flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/template/ThemedTemplateIT.java
flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/MyThemeIT.java
pom.xml

update getting from shadowroot

test: remove shadow root helpers

---

flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java

fix: Fix determining edge from userAgent (#13446)

---

flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/pnpm-lock.yaml
flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/ScopesIT.java

Hopefully makes the test more reliable

test: Add lock file to speed up pnpm install and wait for dev server

---

flow-tests/vaadin-spring-tests/test-spring-security-fusion/src/test/java/com/vaadin/flow/spring/fusionsecurity/SecurityIT.java

test: Wait for page reload so it does not happen unexpectedly

---

flow-server/src/main/resources/com/vaadin/flow/server/webcomponent/webcomponent-script-template.js
flow-tests/test-embedding/embedding-test-assets/src/main/java/com/vaadin/flow/webcomponent/servlets/AbstractPlainServlet.java
flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/EmbeddedWebComponentIT.java

fix: Do not append a nonsense slot to exported web components

---

flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/MapSyncRpcHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/MapSyncRpcHandlerTest.java

(cherry picked from commit ba2c87a48ff883d52926459a522bed7ad545f97e)

test: add tests for log level change in MapSyncRpcHandler (#13517)

---

flow-tests/test-frontend/test-npm/package-lock.json
flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml
flow-tests/test-frontend/vite-basics/package.json
flow-tests/test-frontend/vite-context-path/package.json
flow-tests/test-frontend/vite-production/package.json
flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/TestVersion.java
fusion-endpoint/pom.xml

This reverts commit 96a5267f324e2ef77f1942b226116658194a10ed.

Revert "chore(deps): bump swagger-codegen from 3.0.20 to 3.0.34 (#13532)"

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-tests/test-frontend/test-npm/package-lock.json
flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml
flow-tests/test-frontend/vite-basics/package.json
flow-tests/test-frontend/vite-context-path/package.json
flow-tests/test-frontend/vite-production/package.json

force async version 3.2.2 to get fix for
Prototype Pollution in async

fix: Force async version 3.2.2

---

fusion-endpoint/src/main/java/dev/hilla/ConditionalOnFeatureFlag.java
fusion-endpoint/src/main/java/dev/hilla/FeatureFlagCondition.java
fusion-endpoint/src/main/java/dev/hilla/push/EngineIoCleanup.java
fusion-endpoint/src/main/java/dev/hilla/push/EngineIoHandler.java
fusion-endpoint/src/main/java/dev/hilla/push/PushMessageHandler.java
fusion-endpoint/src/main/java/dev/hilla/push/SocketIoConfigurer.java
fusion-endpoint/src/main/java/dev/hilla/push/SocketIoHandler.java
fusion-endpoint/src/main/java/dev/hilla/push/SocketIoWebsocketConfigurer.java

fix: Register push related beans only when the feature flag is enabled

---

flow-plugins/flow-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml

Reverts vaadin/flow#13302
Fixes #13619

Revert "fix: Do not run any Maven goals automatically in Eclipse / VS Code"

---

flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java
flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
flow-server/src/test/java/com/vaadin/flow/component/ComponentUtilTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandlerTest.java

Manual CP to 23.0 branch to exclude
the breaking changes of #13604

fix: ignore server-modality for poll RPC invocations (CP: #13604)

---

fusion-endpoint/src/main/java/dev/hilla/ByteArrayModule.java
fusion-endpoint/src/main/java/dev/hilla/EndpointInvoker.java
fusion-endpoint/src/test/java/dev/hilla/rest/EndpointWithRestControllerTest.java
fusion-endpoint/src/test/java/dev/hilla/rest/TestEndpoints.java

Fix https://github.com/vaadin/hilla/issues/396.

fix: Serialize byte[] as Array<number>

---

fusion-endpoint/src/main/java/dev/hilla/ByteArrayModule.java
fusion-endpoint/src/main/java/dev/hilla/EndpointController.java
fusion-endpoint/src/test/java/dev/hilla/rest/EndpointWithRestControllerTest.java
fusion-endpoint/src/test/java/dev/hilla/rest/TestEndpoints.java

* Serialize byte[] as Array<number>
* Remove unused imports
* Add test
* Fix test
* Make inner classes static
* Format
(cherry picked from commit 53511dff3a6d580c8b7e0cee6c1d7fba7885c31b)

fix: Serialize byte[] as Array<number> (#13656) (CP: 23.0)

---

pom.xml

Bumps `spring.boot.version` from 2.6.6 to 2.6.7.
Updates `spring-boot-autoconfigure` from 2.6.6 to 2.6.7
- [Release notes](https://github.com/spring-projects/spring-boot/releases)
- [Commits](https://github.com/spring-projects/spring-boot/compare/v2.6.6...v2.6.7)
Updates `spring-boot-test-autoconfigure` from 2.6.6 to 2.6.7
- [Release notes](https://github.com/spring-projects/spring-boot/releases)
- [Commits](https://github.com/spring-projects/spring-boot/compare/v2.6.6...v2.6.7)
Updates `spring-boot-dependencies` from 2.6.6 to 2.6.7
- [Release notes](https://github.com/spring-projects/spring-boot/releases)
- [Commits](https://github.com/spring-projects/spring-boot/compare/v2.6.6...v2.6.7)
---
updated-dependencies:
- dependency-name: org.springframework.boot:spring-boot-autoconfigure …

chore(deps): bump spring.boot.version from 2.6.6 to 2.6.7

---

flow-server/src/main/java/com/vaadin/flow/server/SystemMessages.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutWithNotificationIT.java

fix: clean default system error messages (#12951)

---

fusion-endpoint/src/main/java/dev/hilla/EndpointUtil.java
fusion-endpoint/src/test/java/dev/hilla/EndpointUtilTest.java

Fixes https://github.com/vaadin/hilla/issues/370

fix: Workaround Spring Boot UnsupportedOperationException for error page requests

---

flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
flow-server/src/main/java/com/vaadin/flow/internal/UrlUtil.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/ViewTestServlet.java
flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/CompressionIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VaadinPushScriptIT.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinMVCWebAppInitializer.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java

fix!: Always load static files from context root

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinMVCWebAppInitializer.java
vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationRootMappedTest.java
vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationUrlMappedTest.java

fix: Pass url mapping to Atmosphere

---

flow-tests/test-application-theme/pom.xml
flow-tests/test-application-theme/test-reusable-as-parent-vite/src/test/java/com/vaadin/flow/uitest/ui/theme/ParentThemeIT.java
scripts/computeMatrix.js

The PR fixes some omissions related to tests from #13862: 
- Added the test module to the list of modules that participate in computing the matrix.
- Added the test module to its parent's modules list.
A follow-up to #13862

test: Compute matrix taking into account the recently added tests

---

flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
pom.xml

* chore: Update TestBench version
* fix package name
(cherry picked from commit 5ff1f5deb3b291dc94ae6f09e494efdefbf66898)

chore: Update TestBench version (#13894) (CP: 23.1)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-tests/test-frontend/vite-basics/package.json
flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/PostinstallIT.java

fix: Run postinstall for the project itself when there is a script defined

---

flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
flow-client/src/main/java/com/vaadin/client/communication/RequestResponseTracker.java
flow-client/src/test-gwt/java/com/vaadin/client/flow/dom/GwtDomApiTest.java
flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorDataTest.java
flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
flow-server/src/main/java/com/vaadin/flow/server/SessionRouteRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
flow-server/src/test/java/com/vaadin/flow/server/SessionRouteRegistryTest.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterIT.java

Cherry-pick recent missed bugfix into 2.7

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/PwaIcon.java
flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/PwaRegistryTest.java
flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java

 fix: Add missing media-queries and resources for PWA splash screen (#13923)

---

flow-client/package.json
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-tests/test-frontend/test-npm/package-lock.json
flow-tests/test-frontend/test-npm/package.json
flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml

Update webpack-cli to v4.10.0, since 4.9.2 incompatible with @webpack-cli/serve 1.7.0.
Part-of: https://github.com/vaadin/flow/issues/13952

fix: Update webpack-cli to a latest version

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

chore: Upgrade to latest esbuild-loader

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringServlet.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinMVCWebAppInitializer.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationRootMappedTest.java
vaadin-spring/src/test/java/com/vaadin/flow/spring/service/SpringServletTest.java

Fixes https://github.com/vaadin/spring/issues/789

fix: Do not expose /vaadinServlet/* publicly

---

flow-server/src/main/resources/vite.generated.ts

fix: Set preventAssignment to true to avoid warnings

---

flow-server/src/main/resources/vite.generated.ts

fix: Make SW generation work with Vite 3

---

pom.xml

chore: Bump Spring Boot to 2.7.1 (#14054)

---

flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java

Tests are added for changes done in PR
#14014

test: add tests for handling separate versions in NodeUpdater

---

flow-plugins/flow-gradle-plugin/build.gradle
flow-plugins/flow-gradle-plugin/pom.xml

chore: Simplify Gradle build so no dependency copying is needed (#14005)(CP: 23)

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts

fix: Support Vite 3 ping URL

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java

https://github.com/nodejs/node/releases/tag/v16.16.0

chore: Upgrade Node to 16.16

---

flow-client/src/test/java/com/vaadin/client/DomApiAbstractionUsageTest.java
flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/MultipleAnchorsIT.java

Fixes issues that have been encountered during local build of master branch on MacOS M1 (arm) using OpenJDK 11.

test: fix minor issues related to macos m1 tests failing

---

flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
flow-server/src/test/java/com/vaadin/flow/server/PwaRegistryTest.java
flow-tests/test-frontend/vite-pwa-production/src/test/java/com/vaadin/viteapp/MainIT.java

fix: Fix ServiceWorker path requests in dev mode

---

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java

Let DataCommunicator#flush keep track of which StateTree is supposed to execute its flushRequest (https://github.com/vaadin/flow/pull/14068)
* DataCommunicator#flush can be stuck when moving between UI instances, for instance when the @PreserveOnRefresh annotation is present.
Co-authored-by: Marco Collovati mcollovati@gmail.com
(cherry picked from commit c55bdcc6dd9dac75be42291b5752d1d86d5a9997)

fix: Let DataCommunicator#flush keep track of its StateTree (CP: 2.8)

---

flow-server/src/main/resources/vite.generated.ts
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java

Prevents restart of application during startup.
Fixes #13123
Fixes #14022

fix: build the service worker without writing it to FS

---

flow-server/src/main/resources/vite.generated.ts
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java

Prevents restart of application during startup.
Fixes #13123
Fixes #14022
Fixes #14146
Co-authored-by: Sergey Vinogradov <mr.vursen@gmail.com>
(cherry picked from commit d39102937dc62e9f292b56e02ddaa635e2cef2e9)

fix: build the service worker without writing it to FS (#14182) (CP: 23.1)

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java

Changed Fusion to Hilla so IDE code hints make more sense.

chore: Change Fusion to Hilla

---

flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandlerTest.java

Fixes https://github.com/vaadin/flow/issues/14136

fix: Not show warning if no poll listener

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java

Fix removal of node_modules so that
symlink and Windows junction directory
contents are not deleted also.
Fixes #14138
Closes #11177

fix: Fix removal of windows junctions (#14259)

---

flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksHillaTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksViteTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksWebpackTest.java

feat: add feature flag for Hilla multi-module engine

---

flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java

Update npm version used and
use the .vaadin version for npm

test: Update npm version for test

---

flow-server/src/main/java/com/vaadin/flow/component/Component.java
flow-server/src/main/java/com/vaadin/flow/i18n/I18NProvider.java

feat: Support Object type keys in Component#getTranslation (#14287) (CP 2.8)

---

flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java

Removes the map feature flag, as the component becomes stable with 23.2

chore: remove map feature flag

---

flow-server/src/main/java/com/vaadin/flow/component/Component.java
flow-server/src/main/java/com/vaadin/flow/i18n/I18NProvider.java
flow-server/src/test/java/com/vaadin/flow/server/TestProvider.java

feat: Support Object type keys in Component#getTranslation

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java

Rename the parameter logoutUrl to logoutSuccessUrl

---

flow-server/src/main/resources/vite.generated.ts
flow-tests/test-frontend/vite-basics/frontend/testscopemaploader.js
flow-tests/test-frontend/vite-basics/package.json
flow-tests/test-frontend/vite-basics/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BundlesIT.java
flow-tests/test-frontend/vite-context-path/package.json
flow-tests/test-frontend/vite-context-path/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
flow-tests/test-frontend/vite-production/package.json
flow-tests/test-frontend/vite-production/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
flow-tests/test-frontend/vite-test-assets/packages/@testscope/all/all.js
flow-tests/test-frontend/vite-test-assets/packages/@testscope/map/package.json
flow-tests/test-frontend/vite-test-assets/packages/@testscope/map/src/lib.js
flow-tests/test-frontend/vite-test-assets/packages/@testscope/map/src/testscope-map.js
flow-tests/test-frontend/vite-test-assets/packages/@testscope/map/testscope-map.js
flow-tests/test-frontend/vite-test-assets/packages/@vaadin/bundles-old/vaadin-bundle.json
flow-tests/test-frontend/vite-test-assets/packages/@vaadin/bundles/vaadin-bundle.json
flow-tests/test-frontend/vite-test-assets/packages/@vaadin/bundles/vaadin.js

fix(Vite): handle default exports from Vaadin bundle

---

flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksHillaTest.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTest.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTestBase.java

fix: run TaskGenerateHilla after npm install

---

flow-server/src/main/java/com/vaadin/flow/router/PreserveOnRefresh.java

chore: Update PreserveOnRefresh's javadoc

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java

Chore. Update of `VaadinWebSecurityConfigurerAdapter` javadoc comment.

chore: VaadinWebSecurityConfigurerAdapter javadoc update

---

vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java

fix: Never cache the "waiting for frontend build" page

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts

fix: Do not handle Vite special URLs in the service worker

---

flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
pom.xml

manual cherry-pick of (#14424)
The following vulnerabilities are fixed with an upgrade:
https://snyk.io/vuln/SNYK-JAVA-ORGJSOUP-2989728

fix!: Security upgrade org.jsoup:jsoup to 1.15.3

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
flow-tests/test-frontend/vite-basics/frontend/cssimport-textfield.css
flow-tests/test-frontend/vite-basics/package.json
flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BasicsIT.java

Add ?inline for CSSimports so they do not end up in the document

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/webpack/package.json
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java

This should allow tools to create automated PRs for dependency updates
Fixes #13640

chore: Read default dependencies from a package.json

---

flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java

feat: Allow rerouting to an external URL

---

flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java
flow-server/src/test/java/com/vaadin/flow/server/auth/ViewAccessCheckerTest.java

fix: Redirect to login page without showing the 404 page

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

this is a Cherry pick of https://github.com/vaadin/flow/pull/12863
Update css-loader to get a newer version of postcss

fix: update css-loader(#12863)(CP:2.8)

---

flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
flow-client/src/main/java/com/vaadin/client/communication/RequestResponseTracker.java
flow-client/src/test-gwt/java/com/vaadin/client/flow/dom/GwtDomApiTest.java
flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
flow-server/src/main/java/com/vaadin/flow/server/SessionRouteRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
flow-server/src/test/java/com/vaadin/flow/server/SessionRouteRegistryTest.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterIT.java

this is a cherry pick #13945 
DO NOT SQUASH

cherry pick #13945, DO NOT SQUASH (CP: 2.8)

---

flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java
flow-server/src/test/java/com/vaadin/flow/server/auth/ViewAccessCheckerTest.java
flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/LoginView.java
flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSavedRequestAwareAuthenticationSuccessHandler.java

fix: Redirect to the correct server view also when coming from a non-root URL

---

flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java

chore: log initialization time for PWARegistry

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

this is a cherry-pick based on #12424. 
as instructed by https://github.com/vaadin/flow/pull/12424#issuecomment-986768811

fix: Make linking to packages in the file system work (CP: 2.8)

---

flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFilesTest.java

Fix TaskCopyTemplateFilesTest for windows
Fixes #14667

test: fix TaskCopyTemplateFilesTest for windows (#14667)

---

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java

fix: Cancel previous flush request if new one is forced (#14647) (CP: 2.8)

---

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java

Cancels flush request if it presents in the queue and a new request is forcibly registered. No unit tests added, because this case is quite hard to simulate.
Regression IT test vaadin/flow-components#3804.
Fixes #14435

fix: Cancel previous flush request if new one is forced (#14647) (#14705) (CP: 2.7)

---

flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java

test: fix BootstrapHandlerTest on Windows (#14715) (CP 9.0) 

---

flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java

test: fix BootstrapHandlerTest on Windows (#14715) (CP 23.1)

---

flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java

test: fix BootstrapHandlerTest on Windows (#14715) (CP 2.7)

---

flow-tests/test-frontend/vite-basics/package.json

update test component versions

test: update test component versions

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java

chore: upgrade to Node 18.11.0

---

flow-client/pom.xml
flow-server/pom.xml

Throw a meaningful exception if deployed into a Servlet 3 container

---

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataProvider.java

Replace lambda with anonymous inner class in AbstractDataProvider to fix serialization issue(s).
Test will be added to flow-components project since the issue only seems to happen when the data provider is used with a grid.
Fixes #14654

fix: AbstractDataProvider serialization issue (#14654)

---

flow-client/.eslintrc.js
flow-client/src/main/resources/META-INF/frontend/VaadinDevmodeGizmo.ts
flow-client/src/main/resources/META-INF/frontend/copy-to-clipboard.js
flow-client/src/test/frontend/VaadinDevmodeGizmoTests.js
flow-server/pom.xml
flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReload.java
flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadAccess.java
flow-server/src/main/java/com/vaadin/flow/internal/DebugWindowConnection.java
flow-server/src/main/java/com/vaadin/flow/internal/DebugWindowData.java
flow-server/src/main/java/com/vaadin/flow/internal/DebugWindowMessage.java
flow-server/src/main/java/com/vaadin/flow/internal/ServerInfo.java
flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
flow-server/src/test/java/com/vaadin/flow/internal/BrowserLiveReloadAccessTest.java
flow-server/src/test/java/com/vaadin/flow/internal/DebugWindowConnectionTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

Show version info in debug window and allow copying it to clipboard.
(cherry picked from commit 5cb22904929ba33133c12a8dc2f55488af986e56)
Needed for https://github.com/vaadin/flow/pull/14871
Part-of https://github.com/vaadin/flow/issues/14633

feat: Show version info in debug window (#12000)(CP: 2.8)

---

flow-client/src/main/resources/META-INF/frontend/License.ts
flow-client/src/main/resources/META-INF/frontend/VaadinDevmodeGizmo.ts
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-server/src/main/java/com/vaadin/flow/internal/DebugWindowConnection.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/CvdlProducts.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java

feat: Backport offline license checking (CP: 2.8)

---

flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
pom.xml

Spring Boot 3 RC1 and newer depend on SLF4J 2

chore!: Upgrade to SLF4J 2.0

---

flow-client/src/main/resources/META-INF/frontend/License.ts
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java

Related-to https://github.com/vaadin/flow/issues/14633

feat: Move new license checker feature behind config parameter

---

flow-plugins/flow-gradle-plugin/build.gradle
flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
flow-plugins/flow-gradle-plugin/gradlew
flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/AbstractGradleTest.kt
flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/TestUtils.kt
flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt

* test: extract slf4j version to a variable
* Use Gradle 7.5.1
* Fix Spring Boot test for newer Spring Boot

test: Enable Gradle tests with Gradle 7.5.1 and correct Spring Boot version (#14937) (CP: 23.3)

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java

Remove use of attribute to remove
the need to lock.
Fixes #14950

fix. remove locking and attribute usage

---

flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java

Removes the spreadsheet feature flag, as the component becomes stable with 23.3

chore: remove spreadsheet feature flag

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java

Remove use of attribute to remove the need to lock.
Fixes #14950

fix. remove locking and attribute usage (#14965)

---

pom.xml

chore: bump testbench to 9.0.0.alpha3

---

flow-tests/servlet-containers/felix-jetty/pom.xml

Add flow-server as direct dependency
so that the dependencies are used in
copy-dependencies.

test: update felix versions

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
flow-server/src/main/resources/vite.generated.ts

chore: Make @vaadin/flow-frontend jar-resources change backwards compatible

---

pom.xml

Dependency update to testbench 9.0.0.alpha4

chore: bump testbench to 9.0.0.alpha4

---

flow-polymer2lit/README.md

- Added a "Supported transformations" section.
- Added a "Motivation" section.
- Improved the "Limitations" section.
Part of #14957

doc: Enhance polymer2lit documentation

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateSettingsFile.java
flow-server/src/main/resources/vite.generated.ts

Moves folder logic into the same place

refactor: Write stats output folder from Java

---

flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/ClasspathFilter.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt

feat: port dependency filtering from v14 gradle plugin

---

flow-polymer2lit/README.md

The PR contains some minor improvements to the Polymer to Lit converter's  `README.md`.
A follow-up to #14957

doc: Add minor improvements to README.md

---

flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/ClasspathFilter.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt

Bring in dependency filtering from the vaadin 14 gradle plugin.
Fixes #14994

feat: port dependency filtering from v14 gradle plugin (#15186)

---

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
flow-server/src/main/resources/plugins/stats-plugin/package.json
flow-server/src/main/resources/plugins/stats-plugin/stats-plugin.js

fixes cleanup of stats.json contents
so that the needed templates are
not dropped.

fix: fix faulty cleanup of stats.json

---

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java

fix: Added MAXIMUM_ALLOWED_ITEMS_LOWER_LIMIT for small pageSizes

---

.github/workflows/validation.yml

Include them in the result zip instead

chore: Do not delete test results from the build

---

flow-tests/vaadin-spring-tests/pom.xml
pom.xml

Also updated hibernate.validator, jackson and jackson.databind

chore: Upgrade to Spring Boot 2.7.6 (#15268) (CP: 23.2)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig-osgi.json

Fixes https://github.com/vaadin/flow/issues/15269

fix: Add a template of old tsconfig.json used in OSGi

---

flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java

Add debug logging for incrementing
server id to be able to see what is
calling it during runtime.
Targets #14797

chore: add call thread debug logging

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
flow-server/src/test/java/com/vaadin/flow/component/UITest.java

Avoids conflicts with the application
Fixes #15263

fix: Prefix web component client app with wc-

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
flow-server/src/test/java/com/vaadin/flow/function/DeploymentConfigurationTest.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java

Related-to https://github.com/vaadin/flow/pull/14902

test: Add tests for new license checker config parameter

---

flow-plugins/flow-maven-plugin/pom.xml

test: Delete unused dependency (#15369) (CP: 23.3)

---

flow-server/src/main/resources/vite.generated.ts
flow-server/src/main/resources/webpack.generated.js

Fix collecting versions for npm
modules in windows environment.

fix: npm version collection on windows

---

flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java

Check #13871 for details
Fixes #13871

fix: added HasDynamicTitle checking in parent layouts

---

.github/workflows/validation.yml
scripts/computeMatrix.js

- #15435
- #15231
- #15428
- #15230
- #15224 
- #15226

chore: align with master (#15435, #15231, #15428, #15151, #15230, #15224, #15226) (CP: 23.3)

---

pom.xml

chore: Upgrade to Jetty 10.0.13 (#15440) (CP: 23.2)

---

flow-client/src/main/frontend/Flow.ts
flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
flow-server/src/main/java/com/vaadin/flow/router/Location.java
flow-server/src/main/java/com/vaadin/flow/router/LocationUtil.java
flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/HelloWorldView.java
flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/SpecialCharactersView.java
flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java
flow-tests/test-ccdm/frontend/index.html
flow-tests/test-ccdm/frontend/index.js
flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/FaultyLocationIT.java

fix: Correctly handle URL encoding in routes

---

flow-server/src/main/java/com/vaadin/flow/component/dependency/JsModule.java

chore: Add note about restriction regarding LitTemplate

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json

chore: Upgrade plugin-replace to latest (5.0.1)

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/BasicPushIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/BasicPushWebsocketIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/BasicPushWebsocketXhrIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/EnableDisablePushIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/IdlePushChannelWebsocketIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/MakeComponentVisibleWithPushIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/PushConfigurationWebSocketIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/PushErrorHandlingIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/PushLargeDataWebsocketIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/PushToggleComponentVisibilityIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/PushWithRequireJSIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/ReconnectWebsocketIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/SendMultibyteCharactersWebSocketIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/TogglePushIT.java

Follow-up for https://github.com/vaadin/flow/pull/15509

test: Ignore recently added PUSH + WebSockets tests for OSGi env

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/GenerateMainImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
flow-server/src/main/resources/vite.generated.ts
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

Validate frontenfiles in the bundle
to what generated-flow-imports.js contains
for the project.
Fixes #15553

feat: Validate bundle frontend files

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json

Fixes https://github.com/vaadin/hilla/issues/696

chore: Upgrade Vite to 3.2.5

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/GenerateMainImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java

The in-memory generated-flow-imports needs
to take into account the possible theme used.
part of #15376

fix: Memory generated should use theme

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTsTest.java

feat: support for index.tsx

---

vaadin-spring/pom.xml
vaadin-spring/src/main/java/com/vaadin/flow/spring/AtmosphereHintsRegistrar.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinBeanFactoryInitializationAotProcessor.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinHintsRegistrar.java
vaadin-spring/src/main/resources/META-INF/spring/aot.factories
vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java

Registers project @Routes, component classes and more

feat: Improve Spring Native support

---

flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PageView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PageIT.java

This reverts commit 077191109098cecc4ec8c8637a438bd870d89d04.

Revert "feat: add API to fetch page direction (#15598) (#15608)"

---

flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PageView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PageIT.java

This reverts commit 4ed2db3601285dd4f5cda840c72696b023088be7.

Revert "feat: add API to fetch page direction (#15598) (#15609)"

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinBeanFactoryInitializationAotProcessor.java

It is not needed, and causes a null pointer exception. See https://github.com/spring-projects/spring-framework/issues/29774

fix: Do not register anonymous classes with Spring aot

---

flow-tests/test-frontend/vite-pwa-production/frontend/themes/my-theme/styles.css
flow-tests/test-frontend/vite-pwa-production/src/test/java/com/vaadin/viteapp/MainIT.java
flow-tests/test-frontend/vite-pwa/frontend/themes/my-theme/styles.css
flow-tests/test-frontend/vite-pwa/src/test/java/com/vaadin/viteapp/MainIT.java

instead of testing some JS variable

test: Test that the theme was loaded

---

flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
flow-server/src/test/java/com/vaadin/flow/ComponentTrackerTest.java

Enables updating the location from code later on if needed

fix: Do not use stack trace elements in public API

---

flow-server/src/main/java/com/vaadin/flow/internal/MessageDigestUtil.java
flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
flow-server/src/main/resources/vite.generated.ts
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
flow-tests/test-express-build/test-dev-bundle-java-add-on/pom.xml
flow-tests/test-express-build/test-dev-bundle-java-add-on/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/AddOnIT.java

When having jar-resources validate contents
through hash.
Closes #15668

feat: validate frontend file hash

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java

test: fix faulty tests

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java

fix: avoid infinite recursion on imported directories (#15596) (CP: 23.3)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java

fix: avoid infinite recursion on imported directories (#15596) (CP: 9.0)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java

fix: avoid infinite recursion on imported directories (#15596) (CP: 2.8)

---

flow-server/src/main/java/com/vaadin/flow/internal/NetworkUtil.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringDevToolsPortHandler.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
vaadin-spring/src/main/resources/META-INF/spring.factories
vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java

fix: Use a random port for Spring Boot livereload if the default is taken

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java

Add tracking of express mode usage when
dev-bundle  is checked.

feat: add usage tracking for when expressMode

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java

fix: avoid infinite recursion on imported directories (#15596) (CP: 23.2)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java

Update package.json contents in memory
when checking for bundle build as platform
version might have changed for instance.
Fixes #15727

feat: Always in-memory update package.json

---

flow-client/eclipse/GWT tests.launch
flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateViteDevMode.java
flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
flow-server/src/test/java/com/vaadin/flow/server/PropertyDeploymentConfigurationTest.java
flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerViteTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerManagerImpl.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/MockDeploymentConfiguration.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/AbstractDevModeTest.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
vaadin-spring/src/test/java/com/vaadin/flow/spring/VaadinServletContextInitializerTest.java

Rename enableDevServer to
frontendHotdeploy as devServer
can at the moment mean too many things.
Part of #15743

feat!: rename enableDevServer

---

flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java

Add the possibility to enable
frontend hotdeploy using plugin
configuration.
Closes #15765

feat: add hotdeploy option

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinBeanFactoryInitializationAotProcessor.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java

Caused by resource or classes not always being available

fix: Fix problems in Hilla native compilation

---

flow-server/pom.xml

feat: Throw a meaningful exception if deployed into a Servlet 5 container (#14842)(CP: 2.8)

---

flow-server/pom.xml

feat: Throw a meaningful exception if deployed into a Servlet 5 container (#14842)(CP: 9.0)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
flow-server/src/main/resources/vite.generated.ts
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java

Require rebundling for changes in
frontend/index.ts file.
Fixes #15883

feat: bundle should take into account index.ts

---

vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts

fix: Only show development tools code tab when Flow is used

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java

package.json in-memory generation
should take into account versions files
Fixes #15907

fix: package generation

---

vaadin-dev-server/README.md
vaadin-dev-server/package.json
vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/component-picker.ts
vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts

Adds the prettier code formatter to the dev tools, and reformats existing files.

chore: add prettier to dev tools and reformat code

---

flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ThemeModifier.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/ThemeModifierTest.java

Moved Theme Editor behind feature flag.
Minor updates: cleaned up debug messages handling, updates tests to use feature flags

refactor: feature flag for theme editor

---

flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileUploadBase.java
flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/pub/FileCountLimitExceededException.java

commit f86a96d96ef4ce9507f91ea02ea243c12b6eb02c
Author: Mark Thomas <markt@apache.org>
Date:   Mon Feb 20 17:08:55 2023 +0000
Note new limit is not enabled by default

fix: Update to latest file upload master

---

flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java

chore: add javadoc notes on nested property binding (#15948) (CP: 2.8)

---

vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts

Fixes https://github.com/vaadin/hilla/issues/789

fix: Restore the Hilla exception for the code tab

---

flow-tests/vaadin-spring-tests/pom.xml

pick the change from https://github.com/vaadin/flow/pull/16023

test: remove unnecessary depedendencies (CP: 24.0)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java

Modifies bundle detection logic, so that Flow doesn't check for JS/TS modules in frontend dir that are deleted or added. If a module is added or deleted, then other modules/files would add/remove an import line, so re-bundling happens anyway upon file content change. Adding or deleting of index.ts file is an exclusion and handled separately.
Fixes https://github.com/vaadin/flow/issues/16069

fix: Deleting or adding a file without importing it shouldn't cause re-bundling

---

pom.xml

Upgrades Spring to 6.0.6 and Spring Security to 6.0.2

chore: Upgrade to Spring Boot 3.0.4

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinBeanFactoryInitializationAotProcessor.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java

Do not double register views and include router templates

fix: Fixes for Spring native compile

---

flow-client/package-lock.json
flow-client/package.json

test: Run with playwright that installs browsers on demand (CP:9.0)

---

vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/api.ts
vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/history.test.ts
vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/history.ts
vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/icons.ts

Integrates the server-side undo history with the theme editor frontend.

refactor: integrate theme editor history with frontend

---

vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/range-property-editor.test.ts
vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/range-property-editor.ts
vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/shared.ts
vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/text-property-editor.test.ts
vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/text-property-editor.ts
vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.test.ts
vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.ts

Show a modification indicator in property editors if a property has been modified by the theme editor.

refactor: show modified properties in theme editor

---

flow-tests/test-frontend/vite-embedded-webcomponent-resync/pom.xml
vaadin-dev-server/pom.xml

Fixes https://github.com/vaadin/platform/issues/3898

fix: Add missing provided scope

---

vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/LoadRulesHandler.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/RulesHandler.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/LoadRulesResponse.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/RulesResponse.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandlerTest.java

Added class names (if present) to set rules and load rules responses.

refactor: added classname to set and load rules responses

---

vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-avatar.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-number-field.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-progress-bar.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-text-area.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-text-field.ts

Added simple metadata for vaadin-number-field, vaadin-text-area, vaadin-progress-bar, vaadin-avatar and added sliders&color pickers to vaadin-text-field.

refactor: Theme Editor: additional metadata for components

---

vaadin-dev-server/frontend/theme-editor/components/editors/range-property-editor.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-checkbox.ts
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifier.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifierTest.java

Updates after demo:
- unique classname rename
- added vaadin-checkbox metadata
- made input next to slider smaller to hide horizontal scrollbar

refactor: Theme Editor updates after demo

---

flow-tests/test-lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java
flow-tests/test-lumo/src/main/resources/META-INF/resources/frontend/lumo-includes.ts
flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/TestVersion.java

Syncs with https://github.com/vaadin/flow-components/pull/4808

test: Update test Lumo to reflect latest version

---

flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java

Sets the theme variant in the index page so it is applied in all modes
Fixes #16256

fix: Always set theme variant

---

vaadin-dev-server/src/main/java/com/vaadin/base/devserver/editor/Editor.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifier.java
vaadin-dev-server/src/test/resources/java/org/vaadin/example/TestView_messed.java
vaadin-dev-server/src/test/resources/java/org/vaadin/example/TestView_messedExpected.java

Updated Editor to use javaparser API instead of String operations, minor polishing.

refactor: drop String operations in favor of javaparser API, polishing

---

flow-server/src/main/resources/vite.generated.ts

fix: Do not build Brotli files for the dev bundle

---

flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js

These changes break typography import

Revert lumo changes from 24.0

---

vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifier.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandler.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeModifier.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/LocalClassNameHandler.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifierTest.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeModifierTest.java

Adds updating CSS rules while changing local classname.

refactor: css rules classname replace

---

flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java

fix: Decode project folder when using classpath

---

vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java

fix: Decode project folder when using classpath (#16399) (CP: 23.3)

---

vaadin-dev-server/src/main/java/com/vaadin/base/devserver/editor/Editor.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifierTest.java

Fixes empty lines that were present after removing classname.

refactor: fix empty line after removing component

---

vaadin-dev-server/frontend/theme-editor/metadata/components/defaults.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-big-decimal-field.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-email-field.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-integer-field.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-number-field.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-password-field.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-text-area.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-text-field.ts

Add / improve metadata for text-field based components:
- BigDecimalField
- EmailField
- IntegerField
- NumberField
- TextArea
- TextField

refactor: add basic text fields metadata to theme editor

---

flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/themes/app-theme/styles.css
flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
flow-tests/test-frontend/vite-basics/frontend/themes/vite-basics/styles.css
flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ThemeIT.java
flow-tests/test-themes/frontend/themes/app-theme/styles.css
flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java

* Check the external font is loaded
* Check the sub css is used

test: Check end result instead of implementation details

---

vaadin-dev-server/src/main/java/com/vaadin/base/devserver/editor/Editor.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifierTest.java

Removes empty line after changing local classname.

refactor: remove empty lines on classname update

---

vaadin-dev-server/src/main/java/com/vaadin/base/devserver/editor/Editor.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifier.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/LocalClassNameVisitor.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/AbstractThemeEditorTest.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifierTest.java

Adds support for setting addClassName in constructors of given component (like layouts).

refactor: add support for addClassName inside constructor block

---

vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java

This can happen if Vite sends a lot of messages during a short period of time

fix: Assemble partial websocket messages from Vite

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/index.ts

Fix: Fix invalid link in comment

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/index.ts
flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/index.ts
flow-tests/test-themes/frontend/index.ts

Thank you for the original fix @Artur-! 🙇 I saw some stale/old links in some other places, 
so I thought why not fix them.
Fixes https://github.com/vaadin/flow/issues/16209

fix: some old/stale links fixes.

---

flow-client/package-lock.json
flow-client/package.json
flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json

chore: Upgrade common-frontend

---

flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
flow-tests/vaadin-spring-tests/test-spring-security-flow/pom.xml
flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/SpringBootUnitTest.java

fix: Do not require extensive setup for @SpringBootTest

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfigTest.java

fix: Do not downgrade es-version

---

flow-server/src/main/resources/vite.generated.ts

fix: Make material styles work in hotdeploy dev mode (#16470) (CP: 23.3)

---

flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
flow-tests/vaadin-spring-tests/pom.xml

This seems to have gotten lost in some merge

fix: Import global typography and color styles

---

flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java

fix: Fix importCss being imported twice (#16402) (CP: 24.0)

---

vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-avatar.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-button.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-menu-bar.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-progress-bar.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-select.ts

Use predefined properties for all component metadata. Also adds some additional properties to Button and Avatar metadata.

refactor: polish existing theme editor metadata

---

vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-combo-box.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-time-picker.ts

Adds ComboBox and TimePicker metadata to the theme editor.

refactor: add ComboBox, TimePicker metadata

---

flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FileIOUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FileIOUtilsTest.java

fix: Form a correct path for the project folder when on Windows

---

flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FileIOUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FileIOUtilsTest.java

fix: Form a correct path for the project folder when on Windows (#16611) (CP: 24.0)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FileIOUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FileIOUtilsTest.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java

fix: Form a correct path for the project folder when on Windows (#16611) (CP: 23.3)

---

flow-server/src/main/java/com/vaadin/flow/dom/ElementUtil.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-tests/test-express-build/test-theme-dev-bundle/frontend/themes/my-theme/styles.css
flow-tests/test-express-build/test-theme-dev-bundle/src/test/java/com/vaadin/flow/devbuild/DevBundleThemeIT.java

fix: Do not encode special characters in CSS

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeValidationUtil.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java

Move bundle verification methods
to utility class.
closes #16617

refactor: move util methods to util class

---

vaadin-dev-server/src/main/resources/com/vaadin/base/devserver/dev-mode-not-ready.html

This should fix problems with the dev mode not ready page showing forever on startup

fix: Try polling again on connection refused

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java

Reverts FullDependenciesScanner changes from #16568
Fixes #16639

fix: Include only one theme again

---

pom.xml

so I can prevent local tests execution to freeze my laptop.

test: allow runtime configuration of failsafe parallel execution setting

---

flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java

Adds a feature flag for the SideNav component that is currently in development
Part of https://github.com/vaadin/flow-components/issues/4981

feat: add feature flag for the SideNav component

---

flow-server/src/test/java/com/vaadin/flow/server/communication/AtmospherePushConnectionTest.java

Fix tests flakiness by adjusting operations timings.

test: fix push disconnection tests timings

---

vaadin-dev-server/src/main/java/com/vaadin/base/devserver/MavenUtils.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/ProjectHelpers.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/MavenUtilsTest.java
vaadin-dev-server/src/test/resources/com/vaadin/base/devserver/maven/pom-standalone.xml
vaadin-dev-server/src/test/resources/com/vaadin/base/devserver/maven/pom-with-parent.xml

Fixes group id parsing when pom has a parent

refactor: Extract Maven utils to a separate class

---

flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFiles.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFilesTest.java
flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/TodoIT.java
flow-tests/test-frontend/test-npm/src/test/java/com/vaadin/flow/mixedtest/ui/NpmUsedIT.java
flow-tests/test-frontend/test-pnpm/src/test/java/com/vaadin/flow/mixedtest/ui/PnpmUsedIT.java

When automatically generating
a new frontend bundle clean any
frontend files generated specifically
for bundle generation.
fixes #16783

feat: task to clean generated frontend files

---

flow-server/src/main/java/com/vaadin/flow/internal/springcsrf/SpringCsrfTokenUtil.java

fix: compatibility with CookieCsrfTokenRepository in Spring Security

---

flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/StreamResourceHandlerTest.java

If an exception is thrown, and then another exception is thrown when trying to close() the stream, the exception that gets propagated to the outside world is the bogus/meaningless close() exception, not the actual root cause exception. This makes debugging much harder because the root cause exception is being completely lost.

fix: propagate exception raised during stream write (#16776) (CP: 23.3)

---

flow-tests/vaadin-spring-tests/pom.xml
flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
flow-tests/vaadin-spring-tests/test-spring-helpers/pom.xml
pom.xml

For relevant changes in Spring Boot 3.1, see https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.1-Release-Notes

chore: Upgrade to Spring Boot 3.1.0

---

flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
flow-server/src/main/java/com/vaadin/flow/dom/Element.java
flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
flow-server/src/test/java/com/vaadin/flow/component/JavaScriptInvocationTest.java
flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java

Adding owner to JavaScriptInvocation class.

chore: add owner to JavaScriptInvocation class.

---

flow-server/src/main/java/com/vaadin/flow/internal/springcsrf/SpringCsrfTokenUtil.java

fix: JS syntax error in login form CSRF provider script

---

pom.xml

chore: upgrade jackson.version to 2.15.2 (CP: 24.1)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java

fix: Scan method annotations

---

flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandler.java

Log error messages and throw more
generic exceptions.

fix: log error messages (#16935) (CP: 2.9)

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java

A shorthand to pass RouteParam array directly to navigate method

---

flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
flow-server/src/test/java/com/vaadin/flow/router/QueryParametersTest.java

feat: Added shorthands for QueryParameters class

---

flow-server/src/main/java/com/vaadin/flow/router/RouteParam.java

feat: Overloaded RouteParam constructor with Integer and Long

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java

fix: auto-update @vitejs/plugin-react devDependency (24.0)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java

fix: Only import theme files from the active theme

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java

fix: auto-update @vitejs/plugin-react devDependency

---

flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java

Fixes https://github.com/vaadin/flow/issues/16990

chore: Add doc links to FeatureFlags for SideNav and ThemeEditor

---

flow-server/src/main/java/com/vaadin/flow/component/page/WebStorage.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/WebStorageView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/WebStorageIT.java

Add server side API for web storage (window.localStorage && window.sessionStorage).
Fixes  #13524

feat: Add API for Web Storage

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/CssBundler.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/CssBundlerTest.java

Correctly handles $ and \
Fixes #17039

fix: Quote result in CSS bundler

---

flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/internal/StringUtilTest.java

fix: Strip ?inline from import before finding file

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitionsTest.java

If the content for types.d.ts
has updated update the file
contents even if it already exists.

fix: Update types.d.ts if needed

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitionsTest.java

Reverts vaadin/flow#17081
Created problems with custom types.d.ts that got overwritten.

Revert "fix: Update types.d.ts if needed"

---

flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
flow-tests/test-themes/frontend/index.html

fix: Load theme after other styles in production mode

---

flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadAccessor.java
flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/BrowserLiveReloadAccessorImpl.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/BrowserLiveReloadAccessorImplTest.java

fix: Do not create a LiveReload instance in production mode

---

flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
vaadin-dev-server/frontend/vaadin-dev-tools.ts
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeModifier.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/AbstractThemeEditorTest.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeModifierTest.java

chore: remove theme editor feature flag

---

.github/workflows/validation.yml
flow-tests/pom.xml
flow-tests/test-webpush/frontend/sw.ts
flow-tests/test-webpush/pom.xml
flow-tests/test-webpush/src/main/java/com/vaadin/flow/webpush/Configurator.java
flow-tests/test-webpush/src/main/java/com/vaadin/flow/webpush/WebPushView.java
flow-tests/test-webpush/src/main/resources/vaadin-featureflags.properties
flow-tests/test-webpush/src/test/java/com/vaadin/flow/webpush/WebPushIT.java
scripts/computeMatrix.js

test: Add web push it test

---

vaadin-dev-server/src/main/java/com/vaadin/base/devserver/FileWatcher.java

fix: Report exception if filewatcher fails to start

---

flow-test-util/pom.xml
flow-tests/test-frontend/vite-embedded-webcomponent-resync/pom.xml
flow-tests/test-npm-only-features/test-npm-performance-regression/pom.xml
pom.xml
vaadin-dev-server/pom.xml

Cleaned up the above dependencies version handling (guava and jakarta web socket).

chore: cleaned up guava and jakarta.websocket dependencies to handle the version in one place.

---

flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
flow-server/src/test/java/com/vaadin/flow/router/QueryParametersTest.java

Add methods proposed by Leif
Fixes https://github.com/vaadin/flow/issues/14565

feat: Allow modifying QueryParameters 

---

flow-tests/vaadin-spring-tests/pom.xml
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-accordion-heading.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-accordion-panel.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-date-picker.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-date-time-picker.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-details-summary.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-list-box.ts

Improving Theme Editor components coverage
Part of #17042

added meta-data file for vaadin-date-picker

---

vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-message-input.ts

Message Input doesn't have any issues or blockers.

Add meta data for message input

---

vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-multi-select-combo-box.ts

Metadata for Theme Editor Multi-Select Combo Box

feat: Theme Editor Multi-Select Combo Box metadata

---

vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-icon.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-rich-text-editor.ts

Support for additional components vaadin-icon and vaadin-rich-text-editor
Related to https://github.com/vaadin/web-components/issues/6248

Feat/theme editor vaadin-icon and vaadin-rich-text-editor

---

flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java

Replaces deprecate API usage in Spring Security configurations.

test: replace deprecated Spring Security API usage

---

vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-button.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-custom-field.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-upload.ts

feat: support for vaadin-custom-field, vaadin-upload

---

flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java

Filtering JS invocations for visible owner may be expensive when the UI has a deep component tree, since the visibility check will visit all component ancestors.
This change partitions the pending invocation list by the owner visibility, so the UI tree is visited only once per component.
References #17286

chore: filter pending JS invocation by visible owner only once

---

flow-bom/pom.xml
flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java

Update bad error handler message

fix: add webpush to flow-bom

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java

Cherry pick for https://github.com/vaadin/flow/pull/17359/files

chore: Upgrade pnpm to latest (CP: 24.0)

---

flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java

Cherry pick from main.
Related-to https://github.com/vaadin/flow/pull/17359

chore: Upgrade pnpm to 7 and supported Node version to 14 (CP: 2.10)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java

Cherry pick from main.
Related-to https://github.com/vaadin/flow/pull/17359

chore: Upgrade pnpm to 7 and update supported Node version(CP: 9.1)

---

vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-grid-pro.ts
vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-grid.ts

Theme Editor metadata for Grid Pro

feat: grid-pro metadata, minor grid metadata update

---

flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java
flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
pom.xml

picked this commit https://github.com/vaadin/flow/pull/16665

chore: update TB to 9.0.7 (CP: 24.0)

---

flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/BundleLitParser.java
flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/BundleLitParserTest.java

For lit template render, accept
code before the html` template.
Part of #17455

fix: Accept statements before html render

---

vaadin-dev-server/frontend/theme-editor/editor.test.ts
vaadin-dev-server/frontend/theme-editor/editor.ts

fix: updated missing theme notice

---

flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/NPEHandlerIT.java
pom.xml

Update atmosphere version
to next release.
Closes #17326

fix: update atmosphere version

---

flow-server/src/main/java/com/vaadin/flow/server/Constants.java
pom.xml

Update atmosphere version
to next release.
Closes #17326

fix: update atmosphere version (#17517)

---

pom.xml

resolve vulnerability https://github.com/advisories/GHSA-crqf-q9fp-hwjw

chore : use latest springboot 3.0.10 in flow 24.0

---

flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java
flow-server/src/main/java/com/vaadin/flow/component/DomEvent.java
flow-server/src/main/java/com/vaadin/flow/dom/DomListenerRegistration.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DomEventStopPropagationAndPreventDefaultView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DomEventStopPropagationAndPreventDefaultIT.java

feat: Added methods to prevent default and stopping propagation

---

flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
flow-tests/test-no-root-context/pom.xml
flow-tests/test-no-theme/pom.xml
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/StreamResourceView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateInTemplateIT.java
pom.xml

Update 2.10 to have all changes from 2.9

Merge 2.9 to 2.10

---

flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java
flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java

Related-to https://github.com/vaadin/flow/pull/15885

test: Add missing tests for invisible nodes

---

flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java

Forward to should run even
when targeting same target
but with another URL
Fixes #15876

fix: forward to should update url

---

flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java

Check that resolvedPath is
not null.

Fix: check for null resolvedPath

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java

CP of https://github.com/vaadin/flow/pull/15532

fix!: Use servlet context path as the default logout url

---

flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
vaadin-spring/src/test/java/com/vaadin/flow/spring/VaadinServletContextInitializerTest.java

The message does not really offer much benefit. It is not logged with a logger for some reason and in some cases it is wrong. In most cases the browser will automatically be opened with the correct URL anyway.
With Hilla apps, it is also logged and just looks strange

chore: Remove sysout message

---

flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java

Reroute should not check for url
change.
fixes #17597

fix: reroute doens't change url.

---

flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/AbstractThemeEditorIT.java
flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/ThemeEditorIT.java
flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/testbench/DevToolsCheckboxPropertyEditorElement.java
flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/testbench/DevToolsThemeClassNameEditorElement.java
flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/testbench/DevToolsThemeColorPropertyEditorElement.java
flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/testbench/DevToolsThemeRangePropertyEditorElement.java
flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/testbench/DevToolsThemeTextInputElement.java

Improve theme editor tests to interact with the editor and check if the CSS file is updated correctly.
- [ x ] Feature
- [ X ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ X ] I have added a description following the guideline.
- [ X ] New and existing tests are passing locally with my change.
- [ X ] I have performed self-review and corrected misspellings.

Improve the theme-editor test to check the rules in the created CSS file

---

flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java

Java 17.0.3+ and 11.0.9+ return text/javascript for URLConnection.getFileNameMap().getContentTypeFor(foo.js) Older versions return null
(back-port of 4567381f)

test: make PWA test compatible with Java 11 an 17

---

flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java

Reduces time it takes to populate a lot of  registered routes in `AbstractRouteRegistry` by avoiding checking same path multiple times to figure out route aliases. One path can be mapped to only one `RouteTarget` based on `ConfiguredRoutes#routeMap`.

perf: improve route registration performance

---

flow-plugins/flow-maven-plugin/pom.xml
flow-server/pom.xml

chore: bump commons-compress to resolve vulnerability (CP 23.3)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java

Release notes https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#20.7.0

chore: Update Node.js to latest 20.7.0

---

flow-client/src/main/frontend/Flow.ts
flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PostponeUpdateView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PostponeUpdateIT.java

Fixes issue with update timing
when postponing a router-link
as the navigation goes through
the vaadin-router.
Fixes #17528

fix: router-link postpone navigation

---

flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/ThemeEditorIT.java

Related-to https://github.com/vaadin/flow/issues/17678

test: Ignore failed test for Theme Editor

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/ReloadCache.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java

Cache all classes of interest scanned from JARs, not limiting to classes from vaadin packages.

feat: Cache all classes from JARs

---

flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java

fix: Be less verbose when Vite is not running

---

flow-tests/test-theme-editor/pom.xml
flow-tests/test-theme-editor/src/main/java/com/vaadin/flow/uitest/ui/ThemeEditorView.java
flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/ThemeEditorIT.java
flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/testbench/DevToolsComponentPickerElement.java
flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/testbench/DevToolsThemeEditorElement.java

Adds a test for vaadin-dialog element
Done some refactoring to make it easier to create tests for elements that need some custom operations.
- [ X ] Feature
- [ X ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ X ] I have added a description following the guideline.
- [ X ] I have added tests to ensure my change is effective and works as intended.
- [ X ] New and existing tests are passing locally with my change.
- [ X ] I have performed self-review and corrected misspellings.

Theme editor: adds a test for vaadin-dialog element

---

flow-client/src/main/java/com/vaadin/client/Console.java
flow-tests/test-misc/frontend/consoleLoggingProxy.js
flow-tests/test-misc/frontend/exception-logging.js
flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/ExceptionLoggingView.java
flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/ExceptionLoggingIT.java

Fixes https://github.com/vaadin/flow/issues/2963

Log JS exceptions in production mode

---

flow-server/src/test/java/com/vaadin/flow/i18n/DefaultInstantiatorI18NTest.java
flow-server/src/test/java/com/vaadin/flow/server/I18NProviderTest.java

Instantiator test is not thread safe as after cleans static field
Fixes #17856

test: fix test to not be run threaded

---

flow-html-components/src/main/java/com/vaadin/flow/component/html/Div.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/DivTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/AbstractEventDataView.java

feat: add Div constructor that accept text content

---

flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java

fix: exit disconnect if disconnection already happened

---

vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevToolsInterface.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevToolsMessageHandler.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DebugWindowConnectionTest.java

Add the possibility for plugins to
be notified when the devTools
is disconnected from the client.

feat: add handleDisconnect method to plugin

---

vaadin-dev-server/frontend/vaadin-dev-tools-info.ts
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ServerInfo.java
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/DevModeUsageStatistics.java
vaadin-dev-server/src/test/java/com/vaadin/base/devserver/ServerInfoTest.java

Fixes https://github.com/vaadin/hilla/issues/1581

fix: Show Hilla version when Hilla is available

---

flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/CleanFrontendMojoTest.java

Fixes https://github.com/vaadin/flow/issues/17873

Remove .pnpmfile.cjs on clean-frontend

---

flow-server/src/main/java/com/vaadin/flow/dom/ElementConstants.java
flow-server/src/main/java/com/vaadin/flow/dom/Style.java
flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/AbstractLiveReloadView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/BasicComponentView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/BasicElementView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DnDAttachDetachView.java
flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PublicView.java

feat: add more properties with the typed API in Style

---

flow-webpush/pom.xml
flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java

if flow build is green, let us take this method instead of #17940

fix!: replace outdated webpush dependency

---

flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java

When using the default production bundle, the chunk for a specific Flow component subclass may not be present (e.g. MyChart < Chart). However, the required imports are in the bundle, associated with the chunk id of the parent class.
This change forces the load of potential chunks for all parent classes in the component hierarchy.
Fixes #17694

fix: load chunks for component parents

---

pom.xml

use latest jetty version to resolve CVE-2023-36479

chore: upgrade jetty version

---

flow-tests/test-frontend/test-npm/pom.xml

test: clean frontend stuff for npm dev mode test module

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json

chore: Upgrade @vitejs/plugin-react to 4.1.1

---

flow-tests/test-frontend/pom.xml
flow-tests/test-frontend/test-npm/pom-production.xml
scripts/computeMatrix.js

test: run production mode first for npm and pnpm test modules

---

flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPrepareFrontendTask.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinUtils.kt

Does not fix any particular issue. Contains a couple of cleanups of the Vaadin Gradle Plugin.

Chore: Gradle plugin cleanup

---

flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
vaadin-dev-server/frontend/vaadin-dev-tools-info.ts
vaadin-dev-server/frontend/vaadin-dev-tools.test.ts
vaadin-dev-server/frontend/vaadin-dev-tools.ts

This will allow initializing the dev tools element elsewhere in the future

refactor: Write dev tools config as a global

---

flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinUtils.kt

Just a minor refactoring which removes calls to deprecated methods and adds a bit of kdoc cleanup. Fixes no particular issue.

refactoring: replace calls to deprecated methods; kdoc cleanup

---

flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java

Add feature flag for using
the react router.

chore: add react feature flag.

---

flow-server/src/main/java/com/vaadin/flow/server/Constants.java
pom.xml

* fix: update atmosphere to 2.7.3.slf4jvaadin6
* update constants

fix: update atmosphere to 2.7.3.slf4jvaadin6 (#18047) (CP:2.9)

---

flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/ComponentProperty.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/ComponentTest.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/RangeInputTest.java

Implement a component for `<input type="range">`.
Fixes #3483

feat: Implement RangeInput component

---

flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/RangeInputElement.java
flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/RangeInputElementIT.java
flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/RangeInputView.java

Implement TestBench `RangeInputElement` to test the newly created `RangeInput`.
Unfortunately the tests do not run at the moment, so I can not run them and verify that they pass. Blocked by #18094 ? Or maybe we can pull this one in, and the tests will all be fixed in one sweep as a part of fixing #18094 ?
Fixes #18093

feat: implement RangeInputElement

---

flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckDecision.java
flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckDecisionResolver.java
flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckResult.java
flow-server/src/main/java/com/vaadin/flow/server/auth/DefaultAccessCheckDecisionResolver.java
flow-server/src/main/java/com/vaadin/flow/server/auth/DefaultNavigationCheckDecisionResolver.java
flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessChecker.java
flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java
flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationContext.java
flow-server/src/test/java/com/vaadin/flow/server/auth/AccessCheckResultTest.java
flow-server/src/test/java/com/vaadin/flow/server/auth/AnnotatedViewAccessCheckerTest.java
flow-server/src/test/java/com/vaadin/flow/server/auth/NavigationAccessControlTest.java
flow-server/src/test/java/com/vaadin/flow/server/auth/RoutePathAccessCheckerTest.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/security/NavigationAccessControlConfigurer.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/security/RequestUtil.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/security/SpringNavigationAccessControl.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSavedRequestAwareAuthenticationSuccessHandler.java
vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringSecurityAutoConfigurationTest.java
vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringViewAccessCheckerTest.java
vaadin-spring/src/test/java/com/vaadin/flow/spring/security/NavigationAccessControlConfigurerTest.java
vaadin-spring/src/test/java/com/vaadin/flow/spring/security/RequestUtilTest.java
vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinSavedRequestAwareAuthenticationSuccessHandlerTest.java

Extracts NavigationAccessChecker inner classes to top level
Adds factory method to AccessCheckResult
Improves javadoc

refactor: refactor navigation access control API

---

flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java

Fixes the WebPush documentation link

chore: fix WebPush FeatureFlag moreInfoLink

---

flow-server/src/main/java/com/vaadin/flow/dom/ElementConstants.java
flow-server/src/main/java/com/vaadin/flow/dom/Style.java

added a style method for the transform-origin property

feat: added a style method for the transform-origin property

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx

Add anchor handling so we do
not loose all data for flow navigation.

feat: anchor handling for react-router

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java

When user code calls the deprecated VaadinWebSecurity.getViewAccessChecker(), instead of throwing an exception returns a stub ViewAccessChecker that delegates calls to the relative methods on NavigationAccessControl.

refactor: don't throw when VaadinWeSecurity.getViewAccessChecker is called

---

flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java

Revert "fix: support accept property in StreamReceiverHandler (#18022) (CP: 2.9)"

---

flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java

Revert "fix: support accept property in StreamReceiverHandler (#18022) (CP: 23.3)"

---

flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java

Revert "fix: support accept property in StreamReceiverHandler (#18022) (CP: 23.4)"

---

flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java

Revert "fix: support accept property in StreamReceiverHandler (#18022) (CP: 9.1)"

---

flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java

Revert "fix: support accept property in StreamReceiverHandler (#18022) (CP: 1.0)"

---

flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java

Revert "fix: support accept property in StreamReceiverHandler (#18022) (CP: 2.10)"

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
flow-server/src/main/resources/com/vaadin/flow/server/frontend/App.tsx
flow-server/src/main/resources/com/vaadin/flow/server/frontend/index-react.ts

Generate the App.tsx and
routes.tsx to Frontend and
correct the import in index.ts
Fixes #18239

fix: Generate files to Frontend

---

vaadin-dev-server/frontend/connection.ts
vaadin-dev-server/frontend/live-reload-connection.ts
vaadin-dev-server/frontend/theme-editor/api.ts
vaadin-dev-server/frontend/theme-editor/editor.ts
vaadin-dev-server/frontend/vaadin-dev-tools-info.ts
vaadin-dev-server/frontend/vaadin-dev-tools.ts
vaadin-dev-server/frontend/websocket-connection.ts

Live reload is a standard websocket connection that supports two commands: `hello` and `reload`
The debug window connection should use Atmosphere and supports a lot of other commands

refactor: Split out live reload connection

---

flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
vaadin-dev-server/frontend/vaadin-dev-tools.ts
vaadin-dev-server/frontend/websocket-connection.ts

This should add support for large messages, reconnect and all other features that Atmosphere comes with

fix: Use Atmosphere for debug window connection

---

pom.xml

chore: update license-checker to 1.12.4 (CP: 9.2)

---

vaadin-dev-server/frontend/vaadin-dev-tools.ts

Fixes #18351 
Should not be merged before https://github.com/vaadin/docs/pull/3104

Show link to Docs when devmode host not allowed

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json

https://github.com/advisories/GHSA-c24v-8rfc-w8vw

chore: Upgrade to Vite 3.2.8

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
flow-tests/vaadin-spring-tests/pom.xml
flow-tests/vaadin-spring-tests/test-spring-boot-jar/pom.xml
flow-tests/vaadin-spring-tests/test-spring-boot-jar/src/main/java/com/vaadin/flow/spring/test/TestServletInitializer.java
flow-tests/vaadin-spring-tests/test-spring-boot-jar/src/main/resources/application.properties
flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
flow-tests/vaadin-spring-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/test/ShutdownHook.java
flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/SmokeTestIT.java
scripts/computeMatrix.js

Adds a new module to run ITs for executable jar build for Spring boot with Jetty.
Related-to: #18410

test: test executable jar with Jetty

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java

If a project package.json contains references to local npm pacakges instead of parsable version, the bundle validation fails. This change update the version check in bundle validation to accept also local packages.
For those packages, a bundle re-creation is triggered only if the reference in package.json does not match the one in the stats.
Fixes #18106

fix: consider local npm packages in bundle validation

---

flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java

Newlines cannot be removed from JavaScript as they work as ;

fix: Uncaught SyntaxError: Unexpected identifier 'RefreshRuntime'

---

flow-tests/test-eager-bootstrap/src/test/java/com/vaadin/flow/eagerbootstrap/ParameterIT.java
flow-tests/test-eager-bootstrap/src/test/java/com/vaadin/flow/servlet/BasicViewsIT.java

Fix test execution by waiting for
the dev server to be ready.

test: wait for dev server

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx

Add method to create and
load the WebComponent using
one method if nothing
specific wanted or needed
for createElement.
Part of #18401

feat: create and load WebComponent

---

flow-tests/test-redeployment-no-cache/src/main/java/com/vaadin/flow/uitest/ui/DevModeNoClassCacheView.java
flow-tests/test-redeployment-no-cache/src/test/java/com/vaadin/flow/uitest/ui/DevModeNoClassCacheIT.java
flow-tests/test-redeployment/src/main/java/com/vaadin/flow/uitest/ui/DevModeClassCacheView.java
flow-tests/test-redeployment/src/test/java/com/vaadin/flow/uitest/ui/DevModeClassCacheIT.java
flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/main/java/com/vaadin/flow/spring/test/Application.java
flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/main/java/com/vaadin/flow/spring/test/DummyService.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/ReloadCache.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java

Fixes https://github.com/vaadin/flow/issues/18565

Remove caching of AppShellConfigurator classes to fix injection

---

flow-server/src/main/resources/com/vaadin/flow/server/browser-too-old.html

Fixes #18614  (issue)
I didn't create a test for this case, since there is nothing existing about this page.

fix: Add a lang attribute to the html tag of the browser-too-old.htnl

---

flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java

null means automatic mode.
Fixes: #18578

chore: change hotdeploy property to null by default

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json

https://github.com/advisories/GHSA-c24v-8rfc-w8vw

fixes: upgrade vite version to 3.2.8 (23.3)

---

flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
flow-server/src/main/java/com/vaadin/flow/dom/Element.java
flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExecJavaScriptView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExecJavaScriptIT.java

Wondering if anything else would change for users but await would just magically start to work 🤔 Let's see what the test say...
Quick prototype for #18693, not at all tested...
Fixes #18693

feat: Wrap the JS snippet in async function

---

flow-plugins/flow-gradle-plugin/build.gradle

this will let the sonar build run with java 17.

chore: upgrade dokka version

---

flow-server/src/main/java/com/vaadin/flow/server/Platform.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java

chore: fix unwanted imports

---

flow-server/src/main/java/com/vaadin/flow/component/ClickNotifier.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ImageClickView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ImageClickIT.java

Backport https://github.com/vaadin/flow/pull/16644

feat: Added single and double click event listeners registration methods

---

flow-server/src/main/java/com/vaadin/flow/server/Platform.java
flow-server/src/test/java/com/vaadin/flow/server/PlatformTest.java

Fixes https://github.com/vaadin/platform/issues/5014

fix: Read Hilla version from correct file

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx

Fixes https://github.com/vaadin/flow/issues/18736

fix: fire location-changed on popstateevent

---

flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java

Test for BundlevValidationUtil with vaadin-*versions.json exclusions.
Related-to: #18817

test: add bundle validation test

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json

Related-to https://github.com/vaadin/hilla/issues/2147

chore: Upgrade react deps to latest

---

flow-webpush/pom.xml

resolve https://github.com/advisories/GHSA-6qvw-249j-h44c

chore: upgrade jose4j to 0.9.5

---

flow-tests/test-redeployment/src/test/java/com/vaadin/flow/uitest/ui/DevModeClassCacheIT.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/ReloadEvent.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java

* fix: also scan changed files for routes
* fix test method name

fix: scan changed files for routes (cp:24.2)

---

flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java

fix: locking on FeatureFlags instead of VaadinContext

---

flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinUtils.kt

Pick of #17992 and  #18695  to 24.3
**DO NOT SQUASH**

chore: cherry pick of gradle fixes to 24.3

---

flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/server/scanner/ReflectionsClassFinderTest.java

Prevents a warning message to be printed when the class finder scanner is not able to handle an URL, for example because it points to a not existing directory.
A message is anyway printed at debug level.
Fixes #18855

fix: do not log error for not existing folder during resource scan

---

pom.xml

chore: upgrade testbench to 9.2.4

---

flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojo.java
flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java

Prepare frontend should set
the reactEnabled correctly.
Fixes #18920

fix: reactEnabled should be set correctly for prepare-frontend

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePackageJson.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java

If package json type is missing
or not set to module when upgrading
and modifying package.json
add/update type to module.
Fixes #18924

fix: add or update package.json type

---

flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentProviderTest.java
flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
pom.xml

Bumps commons-io from 2.11.0 to 2.12.0.
---
updated-dependencies:
- dependency-name: commons-io:commons-io dependency-type: direct:production update-type: version-update:semver-minor ...

chore(deps): bump commons-io from 2.11.0 to 2.12.0 (#16816) (CP: 23.5)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java

fix: Update pattern to accept multiple values

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx

Fixed navigation via anchor to Flow views not rendering content. Removed unnecessary if-block from Flow.tsx that stopped rendering the view.
Fixes: #18896

fix: fix anchor navigation with react router

---

pom.xml

chore: upgrade license-checker to 1.12.9

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
flow-tests/test-react-router/src/test/java/com/vaadin/flow/NavigationIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PopStateHandlerIT.java

fix: preserve last navigation path with react

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java

Fixes https://github.com/vaadin/flow/issues/19022

docs: update docs link

---

vaadin-dev-server/src/main/frontend/websocket-connection.ts

Atmosphere will fail if you send a message before the open event

fix: Do not send try to send debug window messages before the connection is up

---

flow-server/src/main/java/com/vaadin/flow/server/Constants.java
pom.xml

chore: Upgrade to Atmosphere 3.0.5.slf4jvaadin1

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx

Make server route validation
not use path but element instead.

fix: more robust Server route check

---

flow-tests/test-react-router/src/test/java/com/vaadin/flow/NavigationIT.java

Check that after navigation to
react view flow components are
not left on screen.

test: add test to check that flow cleared

---

flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java

Fixes https://github.com/vaadin/flow/issues/19023

fix: restore hasBeenAttached on resync (#19023)

---

flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicationController.java
flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java

Fixes #19006 
[PR for test](https://github.com/vaadin/flow-components/pull/6164) - should be reviewed together

fix: do not deactivate expanded item keys (#19006)

---

flow-tests/vaadin-spring-tests/pom.xml
flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
flow-tests/vaadin-spring-tests/test-spring-security-flow/pom.xml

Update component version for tests

chore: update component version

---

flow-server/src/main/java/com/vaadin/flow/di/DefaultInstantiator.java
flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
flow-server/src/test/java/com/vaadin/flow/i18n/DefaultInstantiatorI18NTest.java
flow-server/src/test/java/com/vaadin/flow/i18n/I18NUtilTest.java
flow-server/src/test/java/com/vaadin/flow/i18n/TranslationFileRequestHandlerTest.java
flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/TranslationView.java
flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/TranslationIT.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/i18n/DefaultI18NProviderFactory.java

Fixes getting translation bundle
when executing from thread.
Fixes #18977

fix: i18n default translation from thread

---

flow-server/src/main/java/com/vaadin/flow/di/DefaultInstantiator.java
flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
flow-server/src/test/java/com/vaadin/flow/i18n/DefaultInstantiatorI18NTest.java
flow-server/src/test/java/com/vaadin/flow/i18n/I18NUtilTest.java
flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/TranslationView.java
flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/TranslationIT.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/i18n/DefaultI18NProviderFactory.java

Fixes getting translation bundle
when executing from thread.
Fixes #18977

fix: i18n default translation from thread (#19136)

---

flow-tests/test-ccdm-flow-navigation/pom-production.xml
flow-tests/test-ccdm-flow-navigation/pom.xml
flow-tests/test-frontend/vite-pwa-custom-offline-path/pom-production.xml
flow-tests/test-frontend/vite-pwa-custom-offline-path/pom.xml
flow-tests/test-frontend/vite-pwa-disabled-offline/pom-production.xml
flow-tests/test-frontend/vite-pwa-disabled-offline/pom.xml
flow-tests/test-frontend/vite-pwa-production/pom.xml
flow-tests/test-frontend/vite-pwa/pom.xml
flow-tests/test-pwa/pom-production.xml
flow-tests/test-router-custom-context/pom.xml

test: make webpush tests work with chrome 120

---

vaadin-dev-server/frontend/vaadin-dev-tools-info.ts
vaadin-dev-server/frontend/vaadin-dev-tools.ts

Fixes https://github.com/vaadin/flow/issues/19062

fix: show java livereload status with shared ws

---

vaadin-dev-server/src/main/frontend/vaadin-dev-tools-info.ts
vaadin-dev-server/src/main/frontend/vaadin-dev-tools.ts

fix: show java livereload status with shared ws (cp: main)

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx

Make the sample code return
the correct type of RouteObject[]
instead of only RouteObject
Fixes #19178

fix: correct sample in file

---

vaadin-dev-server/frontend/vaadin-dev-tools.ts

Related to https://github.com/vaadin/flow/issues/19062

fix: set correct debug status blip color (24.3)

---

vaadin-dev-server/src/main/frontend/vaadin-dev-tools.ts

Related to https://github.com/vaadin/flow/issues/19062

fix: set correct debug status blip color

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java

Fixes https://github.com/vaadin/flow/issues/19181

fix: Use less strict regexp for export validation

---

vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketProxy.java

Was unintentionally removed in #19340

chore: Reintroduce message debug logging

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleUtilsTest.java

The package-lock.json provided by the pre-compiled dev-bundle contains no Hilla dependencies, slowing down the first frontend build. This change attempts to extract a package-lock.json file specific to the hybrid application from the bundle, possibly falling back on the standard one.
Fixes #19298

fix: provide specific package-lock.json for hybrid applications

---

flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java

Add a feature flag for the new I18n plugin for Copilot.

chore: add feature flag for Copilot I18n plugin

---

flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java

chore: add feature flag for Full-stack Signals

---

flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java

Fixes https://github.com/vaadin/flow/issues/19386

fix: do not set lastHandledNavigation on refresh

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java

fix: add reflection hints for VaadinRolePrefixHolder

---

flow-react/src/main/resources/com/vaadin/flow/server/frontend/ReactAdapter.template
flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerViteTest.java

Part of https://github.com/vaadin/platform/issues/6430

feat: Add MAU tracking for routing

---

pom.xml

Related to https://github.com/vaadin/platform/issues/5251

chore: Upgrade to Spring-Boot 3.3.0

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFiles.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFilesTest.java

fix: prevent prepare-frontend to remove Hilla generated files

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinBeanFactoryInitializationAotProcessor.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java

Adds reflection hints to fix:
*  missing `ImageIO` class at runtime
* JSON serialization of LoginI18n.Header class
Fixes #19405

fix: add missing hints to fix native compilation

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java

Configures additional reflection hints required by `flow-component`s for native image.
Fixes #19405

fix: add missing reflection hints for flow-components

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
flow-tests/test-react-router/src/main/java/com/vaadin/flow/NavigationView.java
flow-tests/test-react-router/src/test/java/com/vaadin/flow/NavigationIT.java

Add event for informing when navigation is done.
Fixes #19530

fix: add vaadin-navigated event

---

flow-server/src/main/java/com/vaadin/flow/component/page/History.java
flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
flow-server/src/test/java/com/vaadin/flow/component/page/HistoryTest.java

when using vaadin-router
vaadin-navigated event should
be sent instead of vaadin-navigate

Fix: send vaadin-navigated event

---

flow-server/src/main/java/com/vaadin/flow/component/page/History.java
flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
flow-server/src/test/java/com/vaadin/flow/component/page/HistoryTest.java

when using vaadin-router
vaadin-navigated event should
be sent instead of vaadin-navigate

Fix: send vaadin-navigated event (#19537)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java

fix: Bun is bun on Windows

---

flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java

Only require AbstractConfiguration
in the MenuRegistry as that has
the required information.

fix: require the minimum interface needed

---

README.md

Remove link to Discord, add link to Forum.

Change Discord -> Forum

---

flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
flow-server/src/test/java/com/vaadin/flow/server/AbstractConfigurationTest.java

fix: detect project folder for gradle kotlin projects

---

flow-tests/vaadin-spring-tests/pom.xml

Bumps `component.version` from 24.4.2 to 24.4.3.

chore(deps): bump component.version from 24.4.2 to 24.4.3 (#19599)

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/index-react.tsx

fix: Make index.tsx HMR compatible

---

pom.xml

chore: upgrade to TB 9.3.2

---

flow-tests/vaadin-spring-tests/pom.xml

Bumps `component.version` from 24.4.3 to 24.4.4.

chore(deps): bump component.version from 24.4.3 to 24.4.4 (#19634)

---

flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendInputProperties.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinUtils.kt
flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java

Gets or computes an application identifier during production build and stores it into flow-build-info.json

feat: add application identifier to build info

---

flow-server/src/main/java/com/vaadin/flow/component/page/PendingJavaScriptResult.java
flow-server/src/main/java/com/vaadin/flow/component/page/WebStorage.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/WebStorageView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/WebStorageIT.java

Adds CompletableFuture methods for `WebStorage.getItem`.
Fixes #19743

feat: Add CompletableFuture WebStorage API

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FrontendDataProvider.java

Minor change for Drop Bower Support

Fix for dropping support for bower mode

---

flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java

Fixes https://github.com/vaadin/flow/issues/19772

fix: HierarchicalDataCommunicator doesn't support estimates

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java

Add the react classes
as found for optimized bundle.

fix: Add react classes in optimized mode

---

flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java

Add validation that Layout
annotated classes are on
classes that extend RouterLayout.

fix: Validate Layout annotation

---

pom.xml

chore: upgrade  TB to 9.3.4

---

flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java

Adds `premiumFeatures.enable` token to production build info.
Will not compile until license checker is updated.

chore: add premiumFeatures.enable token to build info

---

flow-server/pom.xml

chore: upgrade commons-compress to 1.26.1 

---

flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java

Check Layout annotations
for duplicate values.
If found throw exception.
Fixes #19872

fix: Validate layout values

---

flow-tests/servlet-containers/felix-jetty/pom.xml
flow-tests/servlet-containers/pom.xml
flow-tests/servlet-containers/tomcat85/pom.xml
flow-tests/servlet-containers/tomcat9/pom.xml
flow-tests/test-root-context/pom.xml

Restores production of test-jar and classes artifact for test-root-context module and fixes dependencies artifactId in servlet container test modules

test: fix servlet containers test modules (2.11)

---

flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
flow-server/src/main/java/com/vaadin/flow/router/internal/DefaultRouteResolver.java
flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
flow-server/src/test/java/com/vaadin/flow/router/DefaultRouteResolverTest.java
flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java

Fixes issue where client view with
server side layout is not rendered.
Better error messages.
Fixes vaadin/start#3169
fixes #19895

fix: client navigation for server layout

---

flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java

fix: Do not throw if re-setting the login view

---

flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java
flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java

Make log more detailed for
ignored invocation handle.

chore: More detailed logging for ignored handling (#20007)

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
flow-tests/test-react-router/src/main/java/com/vaadin/flow/BackNavFirstView.java
flow-tests/test-react-router/src/main/java/com/vaadin/flow/BackNavSecondView.java
flow-tests/test-react-router/src/main/java/com/vaadin/flow/ForwardTargetView.java
flow-tests/test-react-router/src/main/java/com/vaadin/flow/ForwardingToParametersView.java
flow-tests/test-react-router/src/main/java/com/vaadin/flow/ForwardingView.java
flow-tests/test-react-router/src/test/java/com/vaadin/flow/BackNavIT.java

fix: queued navigate with React Router (#19985)

---

pom.xml
vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
vaadin-spring/src/test/java/com/vaadin/flow/spring/security/stateless/JwtStatelessAuthenticationTest.java

this is a test PR. so let us dont merge it until a decision has been made from flow team

[test PR]chore: test Spring boot 3.4

---

flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/TestVersion.java
flow-tests/vaadin-spring-tests/pom.xml

close https://github.com/vaadin/flow/pull/20100

chore: upgrade component version to 24.4.13

---

flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java

fix: change blank icon to null in MenuData

---

flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationStateRenderer.java
flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
flow-server/src/main/java/com/vaadin/flow/server/auth/AnnotatedViewAccessChecker.java
flow-server/src/test/java/com/vaadin/flow/router/internal/RouteUtilTest.java
flow-server/src/test/java/com/vaadin/flow/server/auth/AccessControlTestClasses.java
flow-server/src/test/java/com/vaadin/flow/server/auth/AnnotatedViewAccessCheckerTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryMenuAccessTest.java

Make Flow (a)Layout linking dynamic.
Add access checking for route Layout.
Part of #20097

fix: Accesscontrolled layout

---

flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java

fix: add usage stats for automatic menu

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java

Fixes https://github.com/vaadin/flow/issues/19994

feat: enable easier override for SpringServlet

---

flow-server/src/main/resources/vite.generated.ts

When updating `tsconfig.json` to include `*.ts` there are build errors on `vite.generated.ts` file.
This PR fixes some of them, although there are a few others more that would need investigation.
For example `AssetInfo`, `ChunkInfo` and `OutputOptions` types are not exported by `vite`:
```
Module '"vite"' has no exported member 'AssetInfo'.ts(2305)
Module '"vite"' has no exported member 'ChunkInfo'.ts(2305)
Module '"vite"' has no exported member 'OutputOptions'.ts(2305)
```
Also TS complains about missing type definitions for files in `./target/plugins` as they are `.js`.
- Internal change

fix: add types to fix some TS warnings in vite.generated.ts

---

flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java

Fix assertion error after removing a class name (#19489) (CP: 23.5)

---

flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java

Fix assertion error after removing a class name (#19489) (CP: 24.3)

---

flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/TestVersion.java
flow-tests/vaadin-spring-tests/pom.xml

Co-authored-by: Marco Collovati <marco@vaadin.com>
Co-authored-by: Zhe Sun <31067185+ZheSun88@users.noreply.github.com>

chore: update component version to 24.5.3 (#20403)

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java

fix: add missing reflection hints for menu

---

flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java

This PR adds the feature flag for the new [Dashboard component](https://github.com/vaadin/platform/issues/6626).
[Related issue](https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=87587771)

feat: add dashboard component feature flag

---

flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java

Also use file extensions
with production build.

fix: Production also with file extensions

---

flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java

Make the javadoc more
descriptive and correct
for extra extensions.

chore: update javadoc explanation

---

.github/workflows/validation.yml

Update branches that should run github build

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts

fix: Disable workbox developer logs by default

---

flow-plugins/flow-plugin-base/pom.xml
pom.xml
vaadin-spring/pom.xml

chore: pin javassist version in flow plugin base

---

flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java

chore: Updated link at Copilot experimental feature flag

---

flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java

Depends on https://github.com/vaadin/flow-components/pull/6979

feat: add feature flag for Card

---

flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java

Define a constant instead of duplicating literal.
Use string block.
Remove non-thrown throws.
pr 20771 sonar issues

chore: sonar fixes

---

flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java

Add parsing for byte spider and duck duck bot user agents.
Fixes #20784

fix: parse bot user agents

---

flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java

Revert "fix: Store the exception and not an array with the exception for uncaught promise exceptions"

---

flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/CleanFrontendUtil.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFiles.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-test-util/src/main/java/com/vaadin/flow/testutil/FileTestUtil.java
flow-tests/test-frontend/test-bun/src/test/java/com/vaadin/flow/mixedtest/ui/BunUsedIT.java

Fixes https://github.com/vaadin/flow/issues/20896

fix: support bun 1.2 lock file

---

flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java

Retries JS execution several times to prevent test failures cause by aborted navigation on the browser.

test: fix redirect after logout test

---

flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java

Close resources more eagerly and clean up the StreamHandlerFactory after use.

chore: Fix flow-server tests to work on Windows

---

flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java

Adds a feature flag for enabling layout improvements in `HorizontalLayout` and `VerticalLayout`.
Part of https://github.com/vaadin/flow-components/issues/6998
- Feature

feat: add feature flag for layout improvements

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java

With HashSet contains is O(1) with ArrayList it is O(n)

chore: Improve performance by using HashSet

---

pom.xml

Co-authored-by: Zhe Sun <zhe@vaadin.com>
(cherry picked from commit 6c9e04d1fac63b6d64ef42130ca5453b2ab1f157)

chore: upgrade license-checker to 1.13.4 (#20964)(CP: 24.5)

---

pom.xml

Co-authored-by: Zhe Sun <zhe@vaadin.com>
(cherry picked from commit 6c9e04d1fac63b6d64ef42130ca5453b2ab1f157)

chore: upgrade license-checker to 1.13.4 (#20964)(CP: 23.5)

---

pom.xml

Co-authored-by: Zhe Sun <zhe@vaadin.com>
(cherry picked from commit 6c9e04d1fac63b6d64ef42130ca5453b2ab1f157)

chore: upgrade license-checker to 1.13.4 (#20964)(CP: 2.11)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

Write package.json as
formatted instead of single line.

fix: Format package.json

---

pom.xml

This reverts commit a5929bd1a6776a362bc0c74418cf0f05601f2773.
Until we figure out a workaround for https://github.com/spring-projects/spring-framework/issues/34423 or can upgrade to 3.4.4.

Revert "chore: update spring-boot to 3.4.3 (#21023) (#21027)"

---

flow-tests/test-express-build/test-dev-bundle/src/main/resources/vaadin-featureflags.properties
flow-tests/test-root-context/src/main/resources/vaadin-featureflags.properties
flow-tests/test-webpush/src/main/resources/vaadin-featureflags.properties

Removes settings for removed feature flags.

chore: remove unused feature flags files

---

flow-plugins/flow-maven-plugin/pom.xml

Fixes https://github.com/vaadin/flow/issues/20359

chore: remove elemental dep from maven plugin

---

flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/TestUtils.java
flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/CleanFrontendMojoTest.java
flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojoTest.java
flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/CleanFrontendUtil.java
flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java

Update plugins to use
jackson for json handling.
part of #20741

feat: plugins to use jackson

---

flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendInputProperties.kt
flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojo.java
flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/ConvertPolymerCommand.java
flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsSettings.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/JarContentsManagerTest.java

Fixes https://github.com/vaadin/flow/issues/21049

feat: add ignore version check to plugin params

---

flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponent.java
flow-server/src/main/java/com/vaadin/flow/i18n/TranslationFileRequestHandler.java
flow-server/src/main/java/com/vaadin/flow/internal/UsageStatisticsExporter.java
flow-server/src/main/java/com/vaadin/flow/internal/change/MapPutChange.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementAttributeMap.java
flow-server/src/main/java/com/vaadin/flow/internal/springcsrf/SpringCsrfTokenUtil.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/CvdlProducts.java
flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentTest.java
flow-server/src/test/java/com/vaadin/flow/internal/JacksonUtilsTest.java

Change internal functions to
use jackson.
part of #20741

feat: Internals to jackson

---

flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java
flow-server/src/test/java/com/vaadin/flow/server/auth/NavigationAccessControlTest.java

Fixes #21082
Co-authored-by: David Sosa (@sosa-vaadin)

fix: fix equality check in NavigationAccessControl

---

flow-polymer-template/src/test/java/com/vaadin/flow/templatemodel/TemplateModelTest.java
flow-server/src/main/java/com/vaadin/flow/internal/ConstantPool.java
flow-server/src/main/java/com/vaadin/flow/internal/ConstantPoolKey.java
flow-server/src/main/java/com/vaadin/flow/internal/JacksonUtils.java
flow-server/src/main/java/com/vaadin/flow/internal/change/MapPutChange.java
flow-server/src/main/java/com/vaadin/flow/internal/change/NodeChange.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementListenerMap.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/PolymerEventListenerMap.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
flow-server/src/main/java/com/vaadin/flow/server/communication/MetadataWriter.java
flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
flow-server/src/test/java/com/vaadin/flow/component/DomEventTest.java
flow-server/src/test/java/com/vaadin/flow/internal/ConstantPoolTest.java
flow-server/src/test/java/com/vaadin/flow/internal/JacksonUtilsTest.java
flow-server/src/test/java/com/vaadin/flow/internal/change/ListChangeTest.java
flow-server/src/test/java/com/vaadin/flow/internal/change/MapPutChangeTest.java
flow-server/src/test/java/com/vaadin/flow/internal/change/MapRemoveChangeTest.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/PolymerServerEventHandlersTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/MetadataWriterTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java

Use jackson in constant pool
UidlWriter to handle response
in jackson.
Part of #20741

fix: constant pool to jackson

---

flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java

Use add method if not
replacing an old value.

fix: use add if not replacing

---

flow-server/src/main/java/com/vaadin/flow/component/EventData.java
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/router/ErrorNavigationEvent.java
flow-server/src/main/java/com/vaadin/flow/router/NavigationEvent.java
flow-server/src/main/java/com/vaadin/flow/router/Router.java
flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java

Use jackson for router
and navigation.

feat: Router parts to jackson

---

flow-react/src/main/java/com/vaadin/flow/component/react/ReactAdapterComponent.java
flow-react/src/main/java/com/vaadin/flow/component/react/ReactRouterOutlet.java
flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java
flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java
flow-server/src/main/java/com/vaadin/flow/component/ScrollOptions.java
flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java
flow-server/src/main/java/com/vaadin/flow/dom/Element.java
flow-server/src/main/java/com/vaadin/flow/internal/JacksonUtils.java
flow-server/src/main/java/com/vaadin/flow/internal/JavaScriptSemantics.java
flow-server/src/main/java/com/vaadin/flow/internal/change/MapPutChange.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/AbstractPropertyMap.java
flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/DefaultRpcDecoder.java
flow-server/src/test/java/com/vaadin/flow/component/AbstractSinglePropertyFieldTest.java
flow-server/src/test/java/com/vaadin/flow/dom/ElementJacksonTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandlerTest.java

Have ReactAdapter and elemnt
use jackson.
AbstractSinglePropertyField to support
jackson type.
part of #20741

feat: ReactAdapter and element to support jackson

---

flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFiles.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFilesTest.java

fix: Clean file-routes if hilla not in use

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java
flow-server/src/main/java/com/vaadin/flow/router/Router.java
flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java

Fix navigation getting blocked
after initial navigation to
same route when using postpone
Fixes #16984

fix: Renavigation to same url (#21170)

---

flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/Fragment.java

Deprecate because it's not used.

chore: Deprecate Fragment

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java

fix: add native hint for feature flags file

---

flow-server/src/main/java/com/vaadin/flow/server/PwaIcon.java
flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java

This commit is a backport of #16994 (limited to PWA icon handling)
Fixes #21253

feat: backport of PWA icon image lazy generation (23.5)

---

flow-server/src/main/java/com/vaadin/flow/server/PwaIcon.java
flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java

This commit is a backport of #16994 (limited to PWA icon handling) and #14607
Fixes #21253

feat: backport of PWA icon image lazy generation (2.11)

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/PwaConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/PwaIcon.java
flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePWAIcons.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGeneratePWAIconsTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeClassFinderTest.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

Backport #20516 to Flow 2.11
Fixes #21254

feat: backport of PWA icons generation at build time (2.11)

---

.github/workflows/validation.yml

* chore: Use Ubuntu 24.04
* update image for all jobs

chore: Use Ubuntu 24.04 (#21269) (CP: 24.7)

---

flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
flow-server/src/main/java/com/vaadin/flow/server/ElementRequestHandler.java
flow-server/src/main/java/com/vaadin/flow/server/StreamResourceRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
flow-server/src/test/java/com/vaadin/flow/server/StreamResourceRegistryTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/StreamRequestHandlerTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/StreamResourceView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java

Fixes https://github.com/vaadin/flow/issues/21164

feat: add ElementRequestHandler

---

.github/workflows/validation.yml

chore: add 23.6 branch to GHA branch collection

---

flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/router/PreserveOnRefresh.java
flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/partial/MainLayout.java
flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/partial/MainView.java
flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/partial/RootLayout.java
flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/partial/SecondView.java
flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/PartialMatchRefreshIT.java
flow-tests/vaadin-spring-tests/pom.xml
flow-tests/vaadin-spring-tests/test-spring-boot/pom.xml
flow-tests/vaadin-spring-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/test/partial/MainLayout.java
flow-tests/vaadin-spring-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/test/partial/MainView.java
flow-tests/vaadin-spring-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/test/partial/RootLayout.java
flow-tests/vaadin-spring-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/test/partial/SecondView.java
flow-tests/vaadin-spring-tests/test-spring-boot/src/test/java/com/vaadin/flow/spring/test/partial/PartialMatchRefreshIT.java
flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/views/LoginView.java
flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PublicView.java
flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/LoginView.java
flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PublicView.java
flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/UIAccessContextIT.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringViewAccessChecker.java

Cherry pick of https://github.com/vaadin/flow/pull/21189.

feat: Enable preserving partial view chain (CP: 23.6)

---

flow-server/src/main/java/com/vaadin/flow/router/ParameterDeserializer.java
flow-server/src/test/java/com/vaadin/flow/router/ParameterDeserializerTest.java

fix: detect parameter type from parameterized interface

---

flow-server/src/main/java/com/vaadin/flow/server/DownloadHandler.java
flow-server/src/main/java/com/vaadin/flow/server/DownloadRequest.java

Add getUI() method.
part of #21166

fix: make DownloadRequest a record

---

.github/workflows/validation.yml

Based on the OpenSSF scorecard report, there are potential `Dangerous-Workflow` in our flow repo workflow. 
After this change, score goes from 0/10 to 10/10
reference knowledge can be found from [here](https://securitylab.github.com/resources/github-actions-untrusted-input/)
```
Starting [Dangerous-Workflow]
Finished [Dangerous-Workflow]
RESULTS
-------
Aggregate score: 10.0 / 10
Check scores:
|---------|--------------------|--------------------------------|-------------------------------------------------------------------------------------------------------------------|---------------------------|
|  SCORE  |        NAME        |             REASON             |                                                      DETAILS                                                      | …
```

chore: update the GHA workflow 

---

flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/HtmlObject.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/IFrame.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/Image.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlObjectTest.java

feat: add download handler to html components

---

flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/StreamRequestHandlerTest.java

Fixes https://github.com/vaadin/flow/issues/21337

fix: elementrequesthandler node state handling

---

flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressAwareHandler.java

addTransferProgressListener is redundant because we already expose shortcut fluent methods and factory methods where the listener is present.
if needed, custom handlers extending the abstract class can use this method in constructors or make it public.

fix: Make addTransferProgressListener protected

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinResponse.java
flow-server/src/main/java/com/vaadin/flow/server/streams/FileDownloadHandler.java
flow-server/src/test/java/com/vaadin/flow/server/streams/FileDownloadHandlerTest.java

Add the setContentLengthLong method
to VaadinResponse.

feat!: add setContentLengthLong to VaadinResponse

---

flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadHandler.java
flow-server/src/main/java/com/vaadin/flow/server/streams/UploadHandler.java

Update overload JavaDoc to have
description of difference in
the first sentence.

fix: Update JavaDoc to be more descriptive

---

flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
flow-server/src/main/java/com/vaadin/flow/server/streams/ElementRequestHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/StreamRequestHandlerTest.java

Rename allowInert to isAllowInert

fix: rename allowInert for ElementRequestHandler

---

flow-server/src/main/java/com/vaadin/flow/server/streams/UploadEvent.java
flow-server/src/main/java/com/vaadin/flow/server/streams/UploadHandler.java
flow-server/src/main/java/com/vaadin/flow/server/streams/UploadMetadata.java

remove sendUploadResponse as ResponseHandled
is used and should be the one to
override for custom responses.

fix: Remove faulty method

---

flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadEvent.java
flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadResponse.java
flow-server/src/test/java/com/vaadin/flow/server/streams/DownloadEventTest.java

fix: Do not set Content-Disposition for null file name

---

flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java

fix: set download attribute for Anchor DownloadHandlers

---

flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadEvent.java
flow-server/src/main/java/com/vaadin/flow/server/streams/InMemoryUploadHandler.java
flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressAwareHandler.java
flow-server/src/main/java/com/vaadin/flow/server/streams/UploadEvent.java

Cleanup code usage,
remove unused imports and fix typos

chore: Clean up streams

---

flow-tests/test-dev-mode/src/main/frontend/vite-communication.ts
flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/ViteCommunicationView.java
flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/ViteCommunicationIT.java
flow-tests/test-dev-mode/vite.config.ts
vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java

fix: Make Vite messages from browser to server work

---

flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
flow-server/src/test/java/com/vaadin/flow/router/internal/RouteUtilTest.java

fix: prevent route collision check before dev server is started

---

flow-server/pom.xml
flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/StreamReceiverHandlerTest.java

chore: replace commons-fileupload2-jakarta with commons-fileupload2-jakarta-servlet6 (#21711) (CP:24.7)

---

flow-server/pom.xml
flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/StreamReceiverHandlerTest.java

chore: replace commons-fileupload2-jakarta with commons-fileupload2-jakarta-servlet6 (#21711) (CP:24.6)

---

flow-data/src/main/java/com/vaadin/flow/data/provider/Query.java
flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java

Make getPageSize check that it
matches the offset.
Update javadocs for Query to
explain that getPage updates
the pageSize to match offset.
fixes #21481

fix: Update Query getPageSize to check for offset

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java

This reverts commit b60e2fa63b4c294ef3159c05f645473a468e51c6.

Revert "fix: fix AuthenticationContext bean duplicated definition (#21845) (#21846)" (24.9)

---

vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java
vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java

This reverts commit 7b18957eff14583f8fa2fb7d56b6272080036106.

Revert "fix: fix AuthenticationContext bean duplicated definition (#21845)"

---

flow-server/src/main/java/com/vaadin/flow/server/SynchronizedRequestHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java

Fix: move blocking calls outside session lock

---

flow-server/src/main/java/com/vaadin/flow/server/SynchronizedRequestHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
flow-tests/vaadin-spring-tests/pom.xml

Move blocking calls outside session lock (#19938)

Fix: move blocking calls outside session lock (#19938) (#20475)

---

pom.xml

part of https://github.com/vaadin/platform/issues/7882

chore: bump spring-boot to 3.5.4

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx

This fixes cases where the server sends multiple navigate() calls in the same response. There is currently no IT that would fail but this might very well resolve some edge/timing cases without ITs.
This is needed also for React 19 where timing is slightly different and the current solution does not work.
If https://github.com/remix-run/react-router/issues/14158 is ever implemented, it might replace this hacky solution

fix: Run only one queued navigate() at a time

---

flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
flow-server/src/main/java/com/vaadin/flow/component/dependency/NpmPackage.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyNpmAssetsFiles.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/AbstractDependenciesScanner.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyNpmAssetsFilesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerTestComponents.java
flow-tests/test-themes/pom-devbundle.xml
flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/AppShell.java
flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
flow-tests/vaadin-spring-tests/pom.xml

feat: Assets using NpmPackage

---

flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/AbstractTemplate.java
flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java
flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateInitializer.java
flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementData.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/VirtualChildrenList.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementDataTest.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/VirtualChildrenListTest.java

feat!: ElementData to Jackson

---

flow-data/src/main/java/com/vaadin/flow/data/provider/ArrayUpdater.java
flow-data/src/main/java/com/vaadin/flow/data/provider/BeanDataGenerator.java
flow-data/src/main/java/com/vaadin/flow/data/provider/CompositeDataGenerator.java
flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
flow-data/src/main/java/com/vaadin/flow/data/provider/DataGenerator.java
flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataGeneratorTest.java
flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java
flow-data/src/test/java/com/vaadin/flow/data/provider/CompositeDataGeneratorTest.java
flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorAsyncTest.java
flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/AbstractHierarchicalDataCommunicatorTest.java
flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorBasicTest.java
flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorDataRefreshTest.java
flow-server/src/main/java/com/vaadin/flow/component/JsonSerializable.java
flow-server/src/main/java/com/vaadin/flow/internal/JacksonSerializer.java
flow-server/src/test/java/com/vaadin/flow/internal/JacksonSerializerTest.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

feat!: Use Jackson in flow-data package

---

flow-server/src/main/java/com/vaadin/flow/internal/change/MapPutChange.java

Transform ArrayNode to JsonArray  correctly

fix: Mapping of ArrayNode

---

signals/src/main/java/com/vaadin/signals/AbstractSignal.java
signals/src/main/java/com/vaadin/signals/Signal.java
signals/src/test/java/com/vaadin/signals/impl/ComputedSignalTest.java

Move map from AbstractSignal to Signal

---

flow-server/src/main/java/com/vaadin/flow/component/ComponentEffect.java
flow-server/src/test/java/com/vaadin/flow/component/ComponentEffectTest.java

Remove ComponentEffect.format

---

README.md

24.7 is not maintained anymore

Update README.md: remove 24.7

---

flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/AbstractHierarchicalDataCommunicatorTest.java
flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorBasicTest.java
flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorDataGenerationTest.java
flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorDataRefreshTest.java
flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorKeyGenerationTest.java

Part of https://github.com/vaadin/flow-components/issues/8040

test: Clean up data communicator tests

---

CLAUDE.md

With some minor additional custom instructions

chore: Claude instructions generated using /init

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java

Update old platform version
override when a dependency
is added for the override.
Fixes #22415

fix: Update old override (#22429)
