vaadin/flow

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Fixes a security alert related to "workbox-build@6.4.1 requires json-schema@^0.3.0 via @apideck/better-ajv-errors@0.2.7" when using Vite
> chore: Upgrade workbox-build to 6.4.2

- flow-maven-plugin/pom.xml
Set all org.apache.maven artifacts to
provided scope.
Fixes #12499
> fix: add scope to dependencies (#12500) (#12527)

- flow-server/src/main/resources/vite.generated.ts
Added `vaadin:` prefix to all the Vaadin internal Vite plugins defined in `vite.generated.ts` to prevent their possible interference with the user's custom plugins.
A follow-up to https://github.com/vaadin/flow/pull/12857#discussion_r794499392.
> refactor: add `vaadin:` prefix to internal Vite plugins

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
TaskUpdatePackage was still using FileUtils.
Fixes #12810
> fix: use FrontendUtils::deleteNodeModules

- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
Add error log for when a class
visitor fails with an exception for
easier debugging.
Fixes #12759
> Add extra log information for failing visitor

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Leave package-lock even if platform version has updated.
Fixes #12796
> Fix: do not remove package-lock on platform update

- flow-server/src/main/java/com/vaadin/flow/router/LocationUtil.java
- flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
- flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java
- flow-server/src/test/java/com/vaadin/flow/router/QueryParametersTest.java
Fix 1: Don't double-decode query parameters.
Fix 2: URI.getQuery is broken, making it impossible to distinguish `&` separating 
parameters from literal ampersands:
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8214423'
Fix 3: Return a properly encoded query string from
QueryParamaters.getQueryString instead of justing joining the decoded
strings in the map. This is a potentially breaking change.
Fixes #12887
> fix!: no double decode query parameters

- flow-server/src/main/java/com/vaadin/flow/component/UI.java
Allow setting server side modality to
component also when they are not direct
children of the UI.
> fix: Allow server side modality for components UI tree

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Even if we have a vaadin_versions.json
we should also take into account versions
defined in package.json to be locked
for transitive dependencies.
fixes #12662
> fix: also consider package.json for lock versions

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Even if we have a vaadin_versions.json
we should also take into account versions
defined in package.json to be locked
for transitive dependencies.
fixes #12662
> fix: also consider package.json for lock versions (#12915)

- flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
- flow-tests/test-embedding/test-embedding-reusable-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Searching for vaadin-text-field children in shadow DOM by id sometimes fails because the internal index not always reflects the position of parent container, meaning that an element with id 'vaadin-text-field-input-0' could be a child of any  themed-component elements. Searching the element by part attribute makes the test reliable.
Fixes #10331
> test: Find elements by part attribute instead of id (#10331)

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
- flow-tests/test-frontend/vite-basics/package.json
- flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/FileAccessIT.java
Never serve the index.html page for URLs inside /VAADIN/
> fix: Return 404 for /VAADIN/ urls which do not map to a file

- flow-server/src/main/java/com/vaadin/flow/server/SystemMessages.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutWithNotificationIT.java
> fix: clean default system error messages

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
We really have no idea if those versions work and claiming this only harm users
> chore: Delete misleading 'should work' information

- flow-server/bnd.bnd
currently, if you use map component and OSGi, it will fail as the experimental package has not been exported. 
https://bender.vaadin.com/viewLog.html?buildId=287615&buildTypeId=VaadinPlatform_TestReleasePlatformSnapshotToMavenVaadinPrerelease&tab=buildLog
> Fix: export experimental package for OSGi

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
When passing `enablePnpm` flag to `TaskUpdateImports` it must be negated since flag is the oposite in this class.
> chore: fix how disabledPnpm flag was set for TaskUpdateImports

- flow-tests/test-application-theme/test-theme-switch-live-reload/pom.xml
jetty-maven-plugins is configured to scan changes in source directory,
but this is not necessary to trigger automatic reload becuase the test
compiles the source code into `target/classes`, that is already watched
by the plugin.
> chore: remove unecessary jetty-maven-plugin scan configuration

- flow-server/src/main/resources/webpack.generated.js
URLs in CSS may contain a query string or fragment, that prevents a
correct resolution of resource real path and, consequently,
its inclusion in the output bundle.  An example of this kind of url
are SVG Fragment Identifiers, such ones in fontawesome css:
`url("../webfonts/fa-solid-900.svg#fontawesome")`
When this URL is present on CSS file, the svg file will not be available
at runtime.
With this change, incoming URLs are cleaned up by removing potential
query string and fragment before resolving the real path against filesystem.
> fix: cleanup url before resolving resource path in css-loader

- flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Used a try-with-resources statement to ensure that log file gets closed
after iterating over its contents.
> test: Ensure file is closed after reading lines

- pom.xml
Upgrade jetty to 9.4.43 to fix some random test failure
due to jetty PathWacher ConcurrentModificationException
> chore: bump jetty.version

- .github/ISSUE_TEMPLATE/bug_report.yaml
Bug report template references hilla (not fusion)
> chore: link to Hilla repository

- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementListenerMap.java
- flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementListenersTest.java
Fixes: https://github.com/vaadin/flow/issues/12198
> fix: Get boolean only if eventData has the key

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/FrontendStubs.java
Due to requirement of npm 8.3+ the supported
node version is updated to 16.14 and
the autoinstalled node is set to the current lts v16.14.0.
Also autoinstall an use .vaadin if node version is less than
the supported version 8.3
Fixes #12995
> fix!: Supported node is updated to 16.14

- flow-server/src/main/java/com/vaadin/flow/server/Constants.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
Just log an additional warning when package-lock.json is missing.
Fixes #12825.
> fix: Slow npm warning when no package-lock

- flow-server/src/main/resources/vite.generated.ts
- flow-tests/test-frontend/pom.xml
This PR fixes the Vite config so that it would respect the `offline` property of the `PWA` annotation and disable the service worker build when `offline == false`.
Seems like these changes have got lost after a rebase in the original PR introducing the `offline` property.
A follow-up to #13019
> fix: respect PWA offline property in the Vite config

- flow-test-util/pom.xml
Remove exclusion for guava since https://github.com/bonigarcia/webdrivermanager/issues/779 has been fixed and released.
> chore: update webdrivermanager version

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
Currently, when the user wants to have a custom service worker in the `frontend` folder that looks like:
```ts
/// <reference lib="webworker" />
declare var self: ServiceWorkerGlobalScope;
// ...
```
...running the `tsc` utility will report conflicts in the standard TS library due to having a reference to the `webworker` lib.
```bash
node_modules/.pnpm/typescript@4.5.5/node_modules/typescript/lib/lib.dom.d.ts:25:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: ImportExportKind, TableKind, ValueType, ExportValue, Exports, ImportValue, Imports, ModuleImports, name, AlgorithmIdentifier, BigInteger, BinaryData, BlobPart, BodyInit, BufferSource, CanvasImageSource, DOMHighResTimeStamp, DOMTimeStamp, EventListenerOrEventListenerObject, Float32List, …
```
> fix: enable skipDefaultLibCheck in the default TS config

- flow-server/src/main/java/com/vaadin/flow/server/Platform.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ServerInfo.java
To decide whether additional cleanup is needed, store the 
platform version in `node_modules/.vaadin/vaadin.json`, then 
compare with the platform published version. Was previously 
checking `vaadin-shrinkwrap` in `package.json`, but this 
package is removed in V23.
Part of #13008
> fix: save platform version in node_modules

- flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
- flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
- flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/DefaultMappingServlet.java
- flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/NestedMappingServlet.java
- flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerOnNestedMappingIT.java
In production mode service worker content is loaded from `META-INF/VAADIN/webapp/sw.js` classpath resource. When running on a "non root" servlet mapping, sw.js was not served at all because servlet path was prepended to file name when getting resource from classpath.
This change handles the special case of "sw.js" in `StaticFileServer.getRequestFilename`, in order to ignore servlet path on the returned file name.
Fixes #13073
> fix: handle service worker content in production mode when running on non root servlet mapping (#13073)

- flow-server/src/main/resources/vite.generated.ts
Adds Vaadin entry points to `optimizeDeps.entries` in the Vite config in order to let Vite discover and pre-bundle dependencies already during the server startup, not waiting for their first request.
> fix: add Vaadin entry points to `optimizeDeps.entries`

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/ComponentFlagsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
This PR brings in the parts of 204d2cfddb8f438fbd48b0d0fcbea5fe55408f5b
that set a DOM flag to enable theme initialization in `generated-flow-imports.js`.
It is only activated in V14 legacy bootstrap mode.
Fixes #13041
> fix: apply theme in V14 legacy mode

- flow-server/src/main/resources/vite.generated.ts
Fixes formatting issues for `vite.generated.ts` by running it through Prettier.
A follow-up to #13039, #12928.
> refactor: format `vite.generated.ts` with Prettier

- flow-server/src/main/resources/vite.generated.ts
- flow-tests/test-frontend/vite-basics/frontend/testscopebuttonloader.js
- flow-tests/test-frontend/vite-basics/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
- flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BundlesIT.java
- flow-tests/test-frontend/vite-basics/vite.config.ts
- flow-tests/test-frontend/vite-context-path/package.json
- flow-tests/test-frontend/vite-context-path/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
- flow-tests/test-frontend/vite-context-path/src/test/java/com/vaadin/viteapp/BundlesIT.java
- flow-tests/test-frontend/vite-context-path/vite.config.ts
- flow-tests/test-frontend/vite-production/package.json
- flow-tests/test-frontend/vite-production/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
- flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/BundlesIT.java
- flow-tests/test-frontend/vite-production/vite.config.ts
- flow-tests/test-frontend/vite-test-assets/.gitignore
- flow-tests/test-frontend/vite-test-assets/packages/@testscope/all/all.js
- flow-tests/test-frontend/vite-test-assets/packages/@testscope/all/package.json
- flow-tests/test-frontend/vite-test-assets/packages/@testscope/button/package.json
- flow-tests/test-frontend/vite-test-assets/packages/@testscope/button/src/testscope-button.js
- flow-tests/test-frontend/vite-test-assets/packages/@testscope/button/testscope-button.js
- flow-tests/test-frontend/vite-test-assets/packages/@vaadin/bundles-old/package.json
- flow-tests/test-frontend/vite-test-assets/packages/@vaadin/bundles-old/vaadin-bundle.json
- flow-tests/test-frontend/vite-test-assets/packages/@vaadin/bundles-old/vaadin.js
- flow-tests/test-frontend/vite-test-assets/packages/@vaadin/bundles/package.json
- flow-tests/test-frontend/vite-test-assets/packages/@vaadin/bundles/vaadin-bundle.json
- flow-tests/test-frontend/vite-test-assets/packages/@vaadin/bundles/vaadin.js
Enables using use pre-bundled modules from @vaadin/bundles in Vite development mode, if available
Disables bundle usage if different package versions are installed
Fixes #12941
> feat: use Vaadin component container bundles in Vite dev mode (#13039) (CP: 23.0)

- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
For no apparent reason, a Flow project on `23.0.0.beta3` sometimes generates the warning in the logs:
```
A VaadinSession instance not associated to any service is getting unbound. Session destroy events will not be fired and UIs in the session will not get detached. This might happen if a session is deserialized but never used before it expires.
```
According to the omniscient @Artur- , this might be happening when a user
1. Start server
2. Open in a tab
3. Close tab
4. Restart server
5. Wait for timeout
In any case, it doesn't seem to be actionable enough to warrant a `warn` level.
> Change log level when a VaadinSession is getting unbound

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
In it's current place, the warning about the missing package-lock.json (and the associated delay) can be missed as a number of other log messages appear during the log process before npm installation is started. This PR shifts the warning message so it appears right before `npm install` is actually run.
> Show patience notice right before npm install starts

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
Overrides should also automatically
be cleaned from the package.json
if there is no dependency that the
override would be targeting.
> fix: clean overrides for removed dependencies

- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/AbstractGradleTest.kt
- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
Files left by previous node+npm installation caused
corrupted installation when unpacking on top of an
existing installation. Fixed by removing 
~/.vaadin/node/node_modules prior to
installation of newer version.
> fix: remove home node_modules before install

- flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ActivatePushView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VaadinPushScriptIT.java
vaadinPush script url doesn't took into account potential servlet path and was always relative to context path; this can cause the script not to be served by Vaadin StaticFileHandler, but directly by container or non Vaadin handlers (for example in Spring applications).
This change makes the script URL relative to servlet path, so it is forced to be served by Vaadin StaticFileHandler.
Fixes #13153
> fix: let vaadinPush.js script always be served by Vaadin

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
If a devDependency reference has
been manually added to override
do not clean those.
> fix: do not clean manual dev references

- flow-tests/vaadin-spring-tests/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-boot/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-security-flow-contextpath/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-security-flow-urlmapping/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-security-flow/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-security-fusion-contextpath/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-security-fusion-jwt/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-security-fusion/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-white-list/pom.xml
To ensure that version locking works properly we must depend on the whole vaadin and not on individual Flow components. This also simplifies the setup
> test: Properly lock component versions in tests

- flow-tests/vaadin-spring-tests/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-boot/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-security-flow-contextpath/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-security-flow-urlmapping/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-security-flow/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-security-fusion-contextpath/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-security-fusion-jwt/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-security-fusion/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-white-list/pom.xml
To ensure that version locking works properly we must depend on the whole vaadin and not on individual Flow components. This also simplifies the setup
> test: Properly lock component versions in tests (#13218) (CP: 23.0)

- flow-bom/pom.xml
This is needed so that when overriding the Flow version in a project you will get the correct vaadin-spring version also
> fix: Include vaadin-spring in flow-bom

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-tests/test-frontend/test-npm/package-lock.json
chokidar 2 has known security issues that will show up when auditing.
These issues are probably impossible to exploit as dev tools do not
get input from a user but we should still fix them.
This is 1:1 with the pnpm locking in pnpmfile.js
Fixes #13222
> fix: Always lock chokidar version to avoid chokidar 2

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsLocator.java
In some cases, npm -v can prefix the version by something like this printed to stderr
(node: 1124) [LRU_CACHE_OPTION_maxAge] DeprecationWarning: The maxAge option is deprecated. please use options.ttl instead
This should not be interpreted like npm does not work.
Fixes #13195
> fix: Do not assume a tool is broken if it outputs to stderr

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
Check that there is a postinstall
script available before executing
it to not receive error in the logs.
Fixes #12861
> fix: check postinstall before run

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
If a postinstall script contains e.g. "node install.js" like esbuild then it will use "node" from PATH to run the script.
In this case, the Vaadin installed node must come first, before any other node versions mentioned in the PATH
> fix: Do not accidentally invoke a global node through postinstall scripts

- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
Fix a regression where identical ids were
generated for distinct `@CssImport`s
Fixes #13211
> fix: distinct dom-module ids

- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
Fix the jar test for jetty 10.
Do not delete package-lock for clean.
Closes #13257
> test: fix test for jetty10

- flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
- flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ModalDialogIT.java
If the UI is overlaid by a modal component, shortcut
events to UI are ignored; so send them from the active
modal component instead.
Fixes #13205
> fix: shortcut event to modal component instead of UI

- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ReturnChannelMap.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/ReturnChannelHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/ReturnChannelHandlerTest.java
Allow return calls for server-side
registered return channel on targeted
node.
Fixes #13208
> fix: allow server registered return calls

- flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
- flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ModalDialogView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ModalDialogIT.java
The previous fix for #13205 (PR #13263) moved all shortcut
registration event sources from UI to the modal component 
if one was active; this caused shortcuts owned by components
not under the modal tree to also be moved if they were registered
when a modal component was active, and hence they stopped
working when the modal component tree was removed. This
modifies the previous fix to only change the event source if the 
shortcut owner is under the an active modal tree.
> fix: set shortcut listener to modal only if owner is child

- flow-server/src/main/java/com/vaadin/flow/component/Component.java
- flow-server/src/main/java/com/vaadin/flow/dom/Element.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/scroll/ScrollableView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/ScrollableViewIT.java
This change adds back a scrollIntoView method that we had in past framework versions.
The implementation is a trivial shorthand to the similarly named DOM method, and very handy in UI development.
It has been requested by multiple SoF and forum users, but apparently nobody wants to write this trivial enhancement issues as I couldn't find an existing issue for this.
The implementation leaves door open for overloading the method with a version with additional parameters, but already this method should solve most use cases.
> feat: Add scrollIntoView method to Component

- flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
- flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java
Safari 13 does not support the EventTarget constructor,
used in @vaadin/components-base:
https://caniuse.com/?search=EventTarget()
Fixes #13271
> fix: require Safari 14 minimum

- pom.xml
the older parent version generate invalid url for projects.
> chore: update parent project to 2.0.5 (#13290)

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullScannerPwaTest.java
If encountering multiple NpmPackage
annotations with different versions log
a warning and inform of choice taken.
Fixes #13285
> fix: Warn for duplicate npm classes

- flow-plugins/flow-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
It seems like especially VS Code can start running `prepare-frontend` over and over again in some cases which will interfere with an externally running `mvn spring-boot:run` process that will continuously restart because of an updated `target/classes/META-INF/VAADIN/config/flow-build-info.json`
There should be no need nowadays to run `prepare-frontend` from Eclipse at all as it is run through the dev server if needed.
> fix: Do not run any Maven goals automatically in Eclipse / VS Code

- flow-migration/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
If encountering multiple NpmPackage
annotations with different versions log
a warning and inform of choice taken.
Fixes #13285
> fix: Warn for duplicate npm classes (#13291)

- flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/NavigationRpcHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/NavigationRpcHandlerTest.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InertComponentIT.java
Server-side modality feature attempted to block navigation when a modal component is active. This blocks some legitimate use cases when one wants to use RouterLinks inside a modal component. With the current router implementation, it is not practically possible to separate between RouterLinks that are inside a modal from those that are outside (inert). Moreover, navigation cannot be fully controlled on the server side anyway. Therefore, the development team decided to reverse the decision to block RouterLinks when the UI is inert. This PR allows navigation via RouterLinks even when the UI is inert.
Fixes #13270
> feat: Allow navigation with RouterLinks when inert

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrap.java
Test assert checks for `\n`, but
test creation used system line
separator which is not always `\n`
Explicitly use `\n` in string.
This fixes the test execution on
windows where the separator is `\r\n`
> test: fix join to explicitly use \n

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Allow usage of pnpm 6 by
then generating `.pnpmfile.cjs`
instead of `pnpmfile.js`
Closes #12953
> feat: Enable usage of pnpm >5

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderInstanceFieldTest.java
If custom binding is added or completed after the call to Binder.bindInstanceFields
the field is bound twice and this may lead to potential multiple application
of converters, producing wrong representation and value for the field.
This change ignores incomplete bindings during `bindInstanceFields()`
process and overwrites existing bindings when `Binding.bind()` is
invoked after `bindInstanceFields()`.
Fixes #13314
> fix!: Avoid duplicated field bindings

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
Change the build-frontend goal
defaultPhase from prepare-package
to process-classes.
This will make it so that if defined
the build task will also be executed
for server run.
Fixes #13349
> fix: change build-frontend goal phase

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Always when creating a FrontendTools
validate node and npm so that if the
global node is too old and we should
use the installed one we do not use
the global npm even if it was new enough.
Fixes #13364
> fix: validate node and npm on creation

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> fix: Upgrade to v2.9.0-beta.10

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Always when creating a FrontendTools
validate node and npm so that if the
global node is too old and we should
use the installed one we do not use
the global npm even if it was new enough.
Fixes #13364
> fix: validate node and npm on creation (#13374)

- flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java
Add test that chrome and firefox
version 100 doesn't break version
recognition.
Closes #13387
> test: test chrome and firefox version 100 useragents

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPluginsTest.java
Plugins are used as full path
and not through node_modules.
Do not add plugins to package.json
and clean away any existing plugins
Fixes #13247
> fix: clean and do not add plugins

- flow-server/bnd.bnd
The modified atmosphere-runtime:2.7.3.slf4jvaadin3 exports packages
with version 2.7.3 (i.e., not 2.7.3.slf4jvaadin3). Depend on bundle version
instead of the package version.
http://docs.osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.module.importpackage
> fix: use bundle-version instead of package version (#12785)

- fusion-endpoint/src/main/java/dev/hilla/EndpointController.java
This allows the controller to return 404 when no endpoints are registered instead of letting the index html handler return an HTML page
Fixes https://github.com/vaadin/hilla/issues/359
> fix: Always register EndpointController

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/main/java/com/vaadin/flow/data/converter/ConverterFactory.java
- flow-data/src/main/java/com/vaadin/flow/data/converter/DefaultConverterFactory.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BeanBinderTest.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderInstanceFieldTest.java
- flow-data/src/test/java/com/vaadin/flow/data/converter/DefaultConverterFactoryTest.java
- flow-data/src/test/java/com/vaadin/flow/tests/data/bean/ConvertibleValues.java
- flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java
- flow-server/src/test/java/com/vaadin/flow/internal/ReflectToolsTest.java
When binding a field and a property which do not have the same value type
an exception is thrown. With this change, an attempt is made to
automatically pick a suitable converter from the ones provided by the framework.
Closes #12881
> feat: Automatically use available converters in Binder 

- flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
When running maven test on modules together with flow-client, client side
classes are detected by ClassesSerializableTest, but they cannot be
loaded because of missing dependencies.
Client classes can be ignored from test, since they are not available at
runtime.
Fixes #13164
> test: Exclude client classes from serialization test.

- drivers.xml
- flow-client/intern.json
Chrome has update outside of the 97 version support.
> chore: update chrome driver version.

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Updates the Map component feature flag link to point to the docs
Addresses: https://github.com/vaadin/platform/issues/2611#issuecomment-1086147917
> chore: update map feature flag link

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> chore: Upgrade Vite to 2.9.1

- flow-server/pom.xml
- fusion-endpoint/pom.xml
- pom.xml
Seemingly this does not (always) follow jackson versioning. 2.13.2.1 of jackson-databind contains a security (DoS) fix
> chore: Upgrade jackson-databind

- flow-server/pom.xml
Affected versions of this package are vulnerable to Information Exposure
> chore: Override commons-codec version to a safe one

- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ReconnectDialogConfigurationMap.java
The reconnecting message defaults on the server-side do not match the [defaults used on the client-side](https://github.com/vaadin/flow-hilla-common/blob/main/frontend/packages/common-frontend/src/ConnectionIndicator.ts) (which is what the user actually sees). This PR makes the two sets of messages match each other.
> fix: Change reconnecting message defaults to match client-side defaults

- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
When using `@CssImport("some.css")` we need an import for `unsafeCSS`
> fix: Import unsafeCSS when using Vite and @CssImport

- flow-plugins/flow-maven-plugin/pom.xml
- flow-server/pom.xml
- fusion-endpoint/pom.xml
- pom.xml
Seemingly this does not (always) follow jackson versioning. 2.13.2.1 of jackson-databind contains a security (DoS) fix
> chore: Upgrade jackson-databind (#13430) (CP: 9.0)

- flow-client/.gitignore
- flow-client/pom.xml
- flow-client/src/test/npm/intern.json
- flow-test-util/pom.xml
- pom.xml
Chromedriver version for flow-client tests is hard-coded in intern.json file
and should be manually updated when browser gets updated.
With this change, a feasible chromedriver version is automatically detected
using webdrivermanager, as already done for testbench test, and intern.json
is created by replacing a placeholder in a template file.
> test: Automatically setup chromedriver version for flow-client tests

- flow-server/src/main/resources/vite.generated.ts
- flow-server/src/main/resources/webpack.generated.js
It may happen that the watchdog client started by webpack
fails to connect for some reason, for example when server
socket is bound to ipv4 only and client resolve localhost
with its ipv6 address (e.g. with node 17).
This change adds the detail of the connection error to the
log message, so that debugging this kind of situation may
be simpler.
> chore: log watchdog client connection error

- flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/MapSyncRpcHandler.java
Do not log a waning if getting a
property change for a disabled
component when that property has
not been set for the component.
Fixes vaadin/flow-components#2490
> fix: do not warn for unset disabled property change

- flow-server/pom.xml
this current dependency setting failed in platform 
[link](https://bender.vaadin.com/viewLog.html?buildId=299463&buildTypeId=VaadinPlatform_TestReleasePlatformSnapshotToMavenVaadinPrerelease&tab=buildLog)
let us exclude this version properly. 
```
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce) @ vaadin ---
[08:59:47]	[INFO] artifact org.webjars.npm:mobile-drag-drop: checking for updates from central
[08:59:47]	[INFO] artifact org.webjars.npm:mobile-drag-drop: checking for updates from vaadin-prereleases
[08:59:47]	[WARNING] 
[08:59:47]	Dependency convergence error for commons-codec:commons-codec:1.11 paths to dependency are:
[08:59:47]	+-com.vaadin:vaadin:14.8-SNAPSHOT
[08:59:47]	  +-com.vaadin:vaadin-core:14.8-SNAPSHOT
[08:59:47]	    +-com.vaadin:flow-server:2.7-SNAPSHOT …
```
> chore: exclude commons-codec from httpClient

- vaadin-dev-server/src/main/resources/com/vaadin/base/devserver/dev-mode-not-ready.html
If the server is restarting, fetch can result in Uncaught (in promise) TypeError: Failed to fetch
> fix: Keep polling for dev mode server if an exception occurs

- flow-server/src/main/resources/vite.generated.ts
- flow-server/src/main/resources/webpack.generated.js
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/AbstractDevServerRunnerTest.java
Dev server monitors watchdog port on localhost to be sure that Java process
is running, otherwise it kills itself.
It could happend that Java and Node processes resolve localhost ip
address differently (ipv4 vs ipv6), for example when using Node 17 and
setting Java system property `-Djava.net.preferIPv4Stack=true`.
This change resolves the ip address in Java process and provides it to
the node process so it will bind to the correct address.
> chore: pass watchdog ip address to dev server process

- .github/workflows/validation.yml
It makes no sense that the build is sometimes killed when it is storing the results of the build and has about 10 seconds remaining
> chore: Give more time to build steps

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Fixes bug that caused Grid with multi select mode to select not only the item that was clicked on, but also every item below
Fixes:
https://github.com/vaadin-component-factory/selection-grid-flow/issues/34
https://github.com/vaadin-component-factory/selection-grid-flow/issues/16#issuecomment-809987669
Co-authored-by: @s76527
> fix: Not fetch entire page if number of requested items is less

- flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptNavigationStateRenderer.java
- flow-server/src/main/java/com/vaadin/flow/router/HasErrorParameter.java
- flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
- flow-server/src/main/java/com/vaadin/flow/router/LocationChangeEvent.java
- flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
- flow-server/src/main/java/com/vaadin/flow/router/Router.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/main/java/com/vaadin/flow/server/HttpStatusCode.java
- flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/FaviconHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/HeartbeatHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
- flow-server/src/test/java/com/vaadin/flow/server/HttpStatusCodeTest.java
- flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/StreamReceiverHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/StreamResourceHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentProviderTest.java
- flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/UnauthenticatedExceptionHandler.java
- flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomNotFoundView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/routing/PushRouteNotFoundView.java
- flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java
- flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ErrorTarget.java
- flow-tests/vaadin-spring-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/test/NPEHandler.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
Introduction of a custom HTTP status code enumeration aims to minimize the use of javax.servlet APIs, in order to simplify migration to `jakarta.servlet` package.
Fixes #13595
> refactor: introduce http status code enumeration

- flow-server/src/main/java/com/vaadin/flow/server/SessionRouteRegistry.java
- flow-server/src/test/java/com/vaadin/flow/server/SessionRouteRegistryTest.java
Check if parent registry contains a better match
than the session registry.
Fixes #13348
> fix: do not select from session if parent has a better match

- flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandler.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/AbstractDevModeTest.java
Move a couple of common methods from AbstractDevServerRunner to DevModeHandler: get port and wait for dev server. It allows to avoid casts to AbstractDevServerRunner and get rid of dev server dependency only for these tho methods.
> !refactor: Extend DevModeHandler API

- flow-server/src/main/java/com/vaadin/flow/di/OneTimeInitializerPredicate.java
- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinRequest.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinResponse.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/main/java/com/vaadin/flow/server/WrappedSession.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationConfiguration.java
Some flow component imports servlet classes only to link them on javadocs.
To simplify migration to jakarta package, import has been removed and
replace in javadoc link tag with fully qualified class name.
Fixes #13596
> refactor: remove servlet imports used only for javadocs

- flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/ReturnChannelHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandler.java
- flow-server/src/test/java/com/vaadin/flow/component/ComponentUtilTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandlerTest.java
The inert status of the UI as the result of
server-modality should be ignored for
some RPC calls such as polling events. 
Fixes #13337
> fix: ignore server-modality for poll RPC invocations

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
This is useful optimization for the case where you have e.g. validator that checks that input is not in the database, hence avoiding duplicate DB query.
> fix: Optimize Binder#doWriteIfValid to avoid duplicate field level validations

- flow-client/src/main/frontend/License.ts
- flow-client/src/main/frontend/VaadinDevmodeGizmo.ts
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-server/pom.xml
- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
- flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReload.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/CvdlProducts.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
- flow-server/src/main/resources/vite.generated.ts
- flow-server/src/main/resources/webpack.generated.js
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ProductAndMessage.java
For development mode:
- Checks the license from the Java side to avoid cookies
- Replaces commercial components with a login/validation link if the subscription could not be validated
For production mode:
- Requires a license during a production build for commercial components
- Removes commercial components from the fallback bundle if there is no license
- Speeds up production build for free users as charts/maps/... are not compiled in the fallback bundle
Fixes https://github.com/vaadin/platform/issues/2938
> feat: License checker in Java instead of browser

- flow-client/pom.xml
- pom.xml
Since Java 11 is the minimum required version for Flow, specific settings are
applied to the main sections and java11 profile is removed.
> chore: Remove java11 profile

- flow-server/pom.xml
- fusion-endpoint/pom.xml
- pom.xml
Seemingly this does not (always) follow jackson versioning. 2.13.2.1 of jackson-databind contains a security (DoS) fix
> chore: Upgrade jackson-databind (#13430)

- flow-server/src/main/resources/npmrc
> fix: Disable strict peer dependencies to make pnpm 7 work

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
The checker is invoked in three places:
1. After production build with the plugin
2. For fallback chunk in production build
3. Development time through dev mode gizmo
With this addition, all the three places are guarded by the feature flag
> fix: Only run new license checker when flag is enabled

- .github/workflows/validation.yml
Validations triggered from users with `read-only` permissions will fail sooner, then project owners can re-run the build once they verify that changes in the PR are not dangerous for the organisation.
Fixes https://github.com/vaadin/releases-team-tasks/issues/75
> chore: use pull_request_target event and check-user-permissions to allow validations from external contributions

- flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
Filter out AppShellConfigurator interface as Open Liberty includes the implementation itself.
Fixes #13608
> fix: Do not include AppShellConfigurator interface as an implementation #13608

- vaadin-spring/pom.xml
The javadoc and source plugins are already specified in the parent pom
> chore: Remove duplicated build parts

- vaadin-spring/pom.xml
The javadoc and source plugins are already specified in the parent pom
> chore: Remove duplicated build parts (#13682)

- flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Java 17.0.3+ return "text/javascript" for URLConnection.getFileNameMap().getContentTypeFor("foo.js")
Older versions return null
> test: Fix test for Java 17.0.3+

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
This is to add a feature-flag for Collaboration Engine backend support (aka clustering support).
> feat: add flag for CE backend support

- flow-client/.gitignore
- flow-client/pom.xml
- flow-client/src/test/npm/intern.json
- flow-test-util/pom.xml
- pom.xml
Chromedriver version for flow-client tests is hard-coded in intern.json file
and should be manually updated when browser gets updated.
With this change, a feasible chromedriver version is automatically detected
using webdrivermanager, as already done for testbench test, and intern.json
is created by replacing a placeholder in a template file.
(cherry picked from commit 64bbcf737c1f36f7ec64a03f381bbb70068008d9)
> test: Automatically setup chromedriver version for flow-client tests (#13484) (CP: 23.0)

- flow-client/.gitignore
- flow-client/pom.xml
- flow-client/src/test/npm/intern.json
- flow-test-util/pom.xml
- pom.xml
Chromedriver version for flow-client tests is hard-coded in intern.json file
and should be manually updated when browser gets updated.
With this change, a feasible chromedriver version is automatically detected
using webdrivermanager, as already done for testbench test, and intern.json
is created by replacing a placeholder in a template file.
(cherry picked from commit e5d7b796654eedba2c83af45a9bed99c701ce766)
> test: Automatically setup chromedriver version for flow-client tests (#13710) (CP 9.0)

- flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java
- flow-server/src/test/java/com/vaadin/flow/server/auth/ViewAccessCheckerTest.java
Makes it possible to fetch the principal and roles from other sources than the HTTP request
> refactor: Make ViewAccessControl more extensible

- vaadin-dev-server/src/main/resources/com/vaadin/base/devserver/dev-mode-not-ready.html
Simplify the message. Avoid "please", just state what is happening.
Avoid the ellipsis character as it might imply truncated text. The spinner indicates ongoing progress.
Center the message within the viewport. Adapt to light and dark OS theme automatically.
Before:
Light | Dark
---|---
After:
Light | Dark
---|---
> Improve dev mode startup message and styling

- flow-client/src/main/frontend/License.ts
The PR modifies `License.ts` to make it use the `cvdlName` getter for retrieving the product name instead of relying on tag names. The getter has been recently added to the Vaadin web components (see vaadin/web-components#3832).
> refactor: use the cvdlName getter for retrieving the product name

- flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
- flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FrontendDanceMojo.java
Move clean-frontend to pre-clean as if
mvn clean is executed before clean-frontend
clean will remove the target folder making
removal of node_modules fail on windows
if there is a symlink to target/flow-frontend
touches #13760
> fix: Move the clean-frontend phase to be before clean (#13763)

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/AbstractDevServerRunnerTest.java
This happens when the dev server startup fails, i.e. DevModeInitializer.runNodeTasks throws an exception,
then "action" in the constructor throws an exception and devServerStartFuture completes with an exception.
After this when the browser reloads, it needs to go to AbstractDevModeHandler.handleRequest which checks
if an exception happened and sets isDevServerFailedToStart accordingly.
However before getting to AbstractDevModeHandler.handleRequest the static file server checks if the requested
path is a static resource by calling AbstractDevModeHandler.serveDevModeRequest. This throws an exception
because it only checks that the dev server is not still starting and then it tries to access it using port 0.
Fixes #13772
> fix: Do not serve static resources from dev server if dev server startup failed

- vaadin-spring/src/main/java/com/vaadin/flow/spring/DevModeBrowserLauncher.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/RootMappedCondition.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringUtil.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinMVCWebAppInitializer.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/DevModeBrowserLauncherVaadinAndServletMappingTest.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/RootMappedConditionTest.java
The properties in application.properties use a relaxed mapping strategy in
Spring Boot so all variants of "url-mapping","urlmapping","urlMapping" are
mapped to the same value in VaadinConfigurationProperties.
Fixes https://github.com/vaadin/spring/issues/478
> fix: Always get url mapping using helpers when using Spring Boot

- flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicationController.java
The performance of calling Set#removeAll(List) is dependent on the relative sizes of the Set and List parameter. Replace Set#removeAll with List#forEach(Set::remove) to avoid this.
Fixes #13745
> fix: Avoid potential slow Set#removeAll call in HierarchicalCommunicator

- fusion-endpoint/src/main/java/dev/hilla/EndpointController.java
- fusion-endpoint/src/main/java/dev/hilla/push/EngineIoHandler.java
- fusion-endpoint/src/main/java/dev/hilla/push/SocketIoWebsocketConfigurer.java
This avoids conflict with the VaadinServlet when it is bound to /VAADIN/*
Related to https://github.com/vaadin/hilla/pull/424
> Fix: Use /HILLA/push as the Hilla push endpoint

- flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTest.java
Should reduce log output by 3000 rows or so
> test: Start chromedriver with --silent

- fusion-endpoint/src/main/java/dev/hilla/push/PushMessageHandler.java
- fusion-endpoint/src/main/java/dev/hilla/push/SocketIoHandler.java
- fusion-endpoint/src/test/java/dev/hilla/push/PushMessageHandlerTest.java
When the browser disconnects, we need to close all subscriptions. With socket.io, the browser will not reuse the same socket when it reconnects so on reconnect there will be new subscriptions created
Test based on #13728
> fix: Clean up flux subscription on browser disconnect

- fusion-endpoint/src/main/java/dev/hilla/EndpointSubscription.java
- fusion-endpoint/src/main/java/dev/hilla/generator/GeneratorType.java
- fusion-endpoint/src/main/java/dev/hilla/generator/SchemaResolver.java
- fusion-endpoint/src/main/java/dev/hilla/push/PushMessageHandler.java
- fusion-endpoint/src/test/java/dev/hilla/push/PushMessageHandlerTest.java
Adds support for EndpointSubscription as an endpoint return value
An endpoint subscription is the same as a Flux but in addition supports an unsubscribe event handler, triggered when the client closes the subscription (not when the flux completes or errors)
Fixes https://github.com/vaadin/hilla/issues/403
> feat: Support listening to browser unsubscribe in endpoint methods

- flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
Add a `/VAADIN/*` servlet mapping for OSGi test servlet, since it's mandatory for non-root mappings.
Part-of https://github.com/vaadin/flow/issues/13769
> test: Add VAADIN mapping to OSGi servlet registrations

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
- flow-server/src/main/resources/webpack.generated.js
- flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
- flow-server/src/test/resources/META-INF/VAADIN/webapp/web-component.html
This reverts commit 878e94e7
Recent WebComponentBootstrapHandler changes https://github.com/vaadin/flow/pull/13165 prevents Vaadin Portlet from rendering portlet's content. See more details in the pull request comments.
> Revert "refactor: make Webpack use web-component.html (#13165)"

- flow-plugins/flow-plugin-base/pom.xml
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-server/pom.xml
- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
- pom.xml
- vaadin-dev-server/pom.xml
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
This makes it clearer that Flow (flow-server) does not depend on the license checker nor is it needed in production
> Move license checker dependency to vaadin-dev-server and plugin

- flow-plugins/flow-plugin-base/pom.xml
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-server/pom.xml
- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
- pom.xml
- vaadin-dev-server/pom.xml
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
This makes it clearer that Flow (flow-server) does not depend on the license checker nor is it needed in production
> chore: Move license checker dependency to vaadin-dev-server and plugin (#13859) (CP: 23.1)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
The defaults come into effect when
the user clears out or deletes the
package.json, and it is being generated
from scratch.
> fix: upgrade lit default version from 2.2.1 to 2.2.3

- .github/workflows/validation.yml
with current setting, it uses node 16.0.0 to build the project
> chore: let action to pick the latest node 16.

- flow-server/src/main/java/com/vaadin/flow/router/OptionalParameter.java
To make it clear that `OptionalParameter` can be null (with the benefit of providing better hints from IDEs and code analyzers).
> Annotate OptionalParameter with @Nullable

- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/IdentifierProviderChangeEvent.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Components like `Grid` or `MultiSelectComboBox` are supposed to reuse the identifier provider of the Flow data classes to identify items, for example to manage a selection state. However retrieving the identifier provider from a component is problematic at the moment as developers can set an identifier provider on any data view, and there is no way to react to that apart from extending individual implementations of data view classes to implement a custom notification mechanism that the `setIdentifierProvider` method was called.
This change introduces a `IdentifierProviderChangeEvent` that is fired when the developer sets an identifier provider on a data view. Components like `Grid` or `MultiSelectComboBox` can listen for this event, and retrieve the new identifier provider from it.
> feat: notify component about identifier provider changes

- flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterIT.java
When navigating to a non-existent route in dev mode, an error page is displayed with the list of the available routes. However, as noted by [@dmitrilc](https://github.com/dmitrilc), this list doesn't include routes defined via the `@RouteAlias` annotation. 
This PR fixes this.
> fix: Include RouteAliases in RouteNotFoundError message

- flow-server/src/main/java/com/vaadin/flow/router/OptionalParameter.java
This change causes various issues for Flow OSGi integration, and it's not clear after a quick analysis what goes wrong with routing function in OSGi with nullable annotation.
Temporal solution for https://github.com/vaadin/flow/issues/13933.
> Revert "feat: Annotate OptionalParameter with @Nullable (#13903)"

- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
The removes the need to manually specify dev.hilla in the whitelist, something that should be considered an internal detail
> fix: Scan Hilla packages by default

- flow-client/package.json
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-tests/test-frontend/test-npm/package-lock.json
- flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml
Update webpack-cli to v4.10.0, since 4.9.2 incompatible with @webpack-cli/serve 1.7.0.
Part-of: https://github.com/vaadin/flow/issues/13952
(cherry picked from commit 791e8d79d505e37fb187e69c088809c0ea3dedac)
> fix: Update webpack-cli to a latest version (#13954)(CP: 9.0)

- flow-client/package.json
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-tests/test-frontend/test-npm/package-lock.json
- flow-tests/test-frontend/test-npm/package.json
- flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml
Update webpack-cli to v4.10.0, since 4.9.2 incompatible with @webpack-cli/serve 1.7.0.
Part-of: https://github.com/vaadin/flow/issues/13952
(cherry picked from commit 791e8d79d505e37fb187e69c088809c0ea3dedac)
> fix: Update webpack-cli to a latest version (#13954)(CP: 23.1)

- .github/workflows/validation.yml
When the number of tests grows the timeout 
also needed to be increased. This is not a 
permanent solution, the #13972 is created to 
investigate this.
> chore: update timeout to 20 minutes

- .github/workflows/validation.yml
Complement to https://github.com/vaadin/flow/pull/13973 to also increase timeout for unit tests.
> chore: update unit tests timeout to 20 minutes

- vaadin-dev-server/pom.xml
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeEndpointTest.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/TestEndpointGeneratorTaskFactory.java
Connected to: vaadin/hilla#208
Removes dependency on `EnpointGeneratorTaskLibraryImpl` in `vaadin-dev-server` tests.
> refactor: make vaadin-dev-server not depend on fusion-endpoint

- flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java
- flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
When building a navigation menu component which is not based on RouterLink, there is the same need as RouterLink has: to create links to certain views. That requires a Router reference.
> feat: Make the Router lookup method available for others to use

- flow-server/src/main/java/com/vaadin/flow/component/Component.java
- flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Add a helper method to seek the parent component of given type from the component tree. 
Fixes #13984
> feat: Find a parent component with a given type

- flow-server/src/main/java/com/vaadin/flow/server/Constants.java
- flow-server/src/main/java/com/vaadin/flow/server/Platform.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesNpmVersionLockingTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
Previously, the vaadin_versions.json contained
both core and commercial components listed
which led to including them all in package.json
even if the user only used vaadin-core. Now
platform generates vaadin-core-version.json in
vaadin-core and vaadin-version.json to include
commercial components in vaadin artifact.
This commit will adopt having separate files
while generating package.json and pinning the
platform dependencies.
Fixes: #13749
> fix: separate core and commercial components version files

- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java
In IndexHtmlRequestHandler the customElements.define function is
redefined to apply a custom feature after invoking the original
function. The reference to the the original function is stored in a
`define` constant and unfortunately this conflicts with require.js.
This change renames the constant in order to avoid the conflict.
In addition, it fixes an NPE in ApplicationRunnerServlet, when getting
DeploymentConfiguration in a debug window websocket request.
Fixes #14057
> fix: rename global js constant conflicting with require.js

- flow-server/src/main/resources/vite.generated.ts
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
Use 127.0.0.1 both for the Vite server and when connecting to it to ensure it works
Fixes #14021
> fix: Fix ip binding problem with Vite 3

- flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
- flow-tests/pom.xml
- flow-tests/test-eager-bootstrap/pom.xml
- flow-tests/test-eager-bootstrap/src/main/java/com/vaadin/flow/eagerbootstrap/HelloView.java
- flow-tests/test-eager-bootstrap/src/main/java/com/vaadin/flow/eagerbootstrap/RootView.java
- flow-tests/test-eager-bootstrap/src/test/java/com/vaadin/flow/servlet/BasicViewsIT.java
- flow-tests/test-eager-bootstrap/src/test/java/com/vaadin/flow/servlet/LowLevelFetchIT.java
Returns 404 for non-existant views
Helps with #13421
> fix: Use correct view when using eagerServerLoad

- flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
- flow-tests/pom.xml
- flow-tests/test-eager-bootstrap/pom.xml
- flow-tests/test-eager-bootstrap/src/main/java/com/vaadin/flow/eagerbootstrap/HelloView.java
- flow-tests/test-eager-bootstrap/src/main/java/com/vaadin/flow/eagerbootstrap/RootView.java
- flow-tests/test-eager-bootstrap/src/test/java/com/vaadin/flow/servlet/BasicViewsIT.java
- flow-tests/test-eager-bootstrap/src/test/java/com/vaadin/flow/servlet/LowLevelFetchIT.java
* fix: Use correct view when using eagerServerLoad
Returns 404 for non-existent views
Helps with #13421
(cherry picked from commit 87c220a753fc281204847b768d64bb583a1d0276)
> fix: Use correct view when using eagerServerLoad (#14036) (CP: 9.0)

- flow-server/src/main/java/com/vaadin/flow/server/Platform.java
after https://github.com/vaadin/flow/pull/14014 fix, one log message needs to be updated.
> chore: update log message after versions.json separation

- flow-plugins/flow-gradle-plugin/build.gradle
- flow-plugins/flow-gradle-plugin/pom.xml
> chore: Simplify Gradle build so no dependency copying is needed (#14005) (CP: 9.0)

- flow-server/src/main/resources/vite.generated.ts
This is needed in Vite 3 to avoid an initial attempt to connect Vite's websocket channel to localhost:8080 which logs a browser warning
> fix: Set Vite hot reload port to match the server port

- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
- flow-tests/test-frontend/vite-basics/frontend/themes/vite-basics/styles.css
- flow-tests/test-frontend/vite-basics/package.json
- flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ThemeIT.java
CSS url directive allows the url to be enclosed in single or double quotes.
Currently, webpack processors removes quotes before the theme-generator is used,
but this does not happen with Vite, so URLs are set on the link elements by
createLinkReferences function with quotes and this leads to an HTTP 404 error
because the browser adds the base url to the contents of the directive.
This change modifies the regular expression that matches urls, so that
the quotes are not part of the capturing group used to get the url.
> fix: ignore quotes in CSS url directive

- flow-data/src/main/java/com/vaadin/flow/data/binder/HasValidator.java
The error in javadoc example is fixed
so the getDefaultValidator represent
the correct implementation.
Fixes #14049
> chore: fix HasValidator javadoc

- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
- flow-tests/test-frontend/vite-basics/frontend/themes/vite-basics/styles.css
- flow-tests/test-frontend/vite-basics/package.json
- flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ThemeIT.java
CSS url directive allows the url to be enclosed in single or double quotes.
Currently, webpack processors removes quotes before the theme-generator is used,
but this does not happen with Vite, so URLs are set on the link elements by
createLinkReferences function with quotes and this leads to an HTTP 404 error
because the browser adds the base url to the contents of the directive.
This change modifies the regular expression that matches urls, so that
the quotes are not part of the capturing group used to get the url.
> fix: ignore quotes in CSS url directive (#14103) (CP 23.1)

- flow-server/src/main/java/com/vaadin/flow/server/Constants.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
This is a manual cherry-pick to collect
all changes that are done in #14014,
#14079, and #14083.
Related to #14092
>  fix: separate core and commercial components version files (#14014) (CP: 9.0)

- flow-server/src/main/java/com/vaadin/flow/server/Constants.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
This is a manual cherry-pick to collect
all changes that are done in #14014,
#14079, and #14083.
Fixes #14092
>  fix: separate core and commercial components version files (#14014) (CP: 2.7)

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderValidationStatusChangeListenerTest.java
Listener removal was missing when unbinding
was happening. Follow up for #13940.
Fixes #14110
> feat: remove validation status change listener upon unbind

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlags.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlagsTest.java
Adding a workaround as recommended by [TypeScript docs](https://www.typescriptlang.org/tsconfig#non-module-files).
Fixes #14184
- Bugfix
> fix: add empty export to vaadin-featureflags.ts

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
fix: Let DataCommunicator#flush keep track of which StateTree is supposed to execute its flushRequest (#14068)
* DataCommunicator#flush can be stuck when moving between UI instances, for instance when the @PreserveOnRefresh annotation is present.
Co-authored-by: Marco Collovati <mcollovati@gmail.com>
(cherry picked from commit c55bdcc6dd9dac75be42291b5752d1d86d5a9997)
> fix: Let DataCommunicator#flush keep track of its StateTree (CP: 9.0)

- flow-tests/test-frontend/vite-pwa-custom-offline-path/pom-production.xml
- flow-tests/test-frontend/vite-pwa-custom-offline-path/pom.xml
- flow-tests/test-frontend/vite-pwa-production/pom.xml
- flow-tests/test-frontend/vite-pwa/pom.xml
Test using dev tools are not working with internal selenium grid
because it is not up to date. Adding dependency to support chrome 100
> test: workaround for internal selenium grid

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderValidationStatusChangeListenerTest.java
Add binder-level flag to allow disabling of 
validation status change listener registration 
for HasValidator fields.
Related to https://github.com/vaadin/flow/pull/13940#issuecomment-1174668400 and https://github.com/vaadin/flow/pull/13940#issuecomment-1174668400
> feat: allow disabling validation status change listener registration on binder

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
fix: Let DataCommunicator#flush keep track of which StateTree is supposed to execute its flushRequest (#14068)
* DataCommunicator#flush can be stuck when moving between UI instances, for instance when the @PreserveOnRefresh annotation is present.
Co-authored-by: Marco Collovati mcollovati@gmail.com
(cherry picked from commit c55bdcc6dd9dac75be42291b5752d1d86d5a9997)
> fix: Let DataCommunicator#flush keep track of its StateTree (CP: 2.7)

- flow-data/src/main/java/com/vaadin/flow/data/binder/ValidationResult.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/ValidationResultTest.java
Improve developer experience by providing proper `equals`, `hashCode` and `toString` methods for `ValidationResult`. 
Allows developer to use it inside tests without unwrapping it.
```java
assertThat(validator.apply("valid", valueContext))
.isEqualTo(ValidationResult.ok());
assertThat(validator.apply("not valid", valueContext))
.isEqualTo(ValidationResult.error("Not valid input provided."));
assertThat(validator.apply("not valid", valueContext))
.isEqualTo(ValidationResult.create("Not the best input provided.", ErrorLevel.INFO));
```
> feat: Improving DX ValidationResult

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderValidationStatusChangeListenerTest.java
Add binder-level flag to allow disabling of
validation status change listener registration
for HasValidator fields.
Related to https://github.com/vaadin/flow/pull/13940#issuecomment-1174668400 and https://github.com/vaadin/flow-components/pull/3406#discussion_r908427652
(cherry picked from commit 420498c6f9ab113a4a91d23f19cb7d464be3f6f9)
> feat: allow disabling validation status change listener registration on binder (CP: 2.7)

- flow-server/src/main/java/com/vaadin/flow/dom/Node.java
Added Collection based appendChild / appendVirtualChild / insertChild / removeChild / removeVirtualChild methods for `com.vaadin.flow.dom.Node`
Fixes #13599
> feat: provides collection based append/remove methods for Node

- flow-server/src/main/resources/vite.generated.ts
devMode flag was hard-coded to false in theme options, preventing the theme generator
plugin to work correctly when styles.css does not exist
Fixes #14228
> fix: provide correct devMode flag to theme-generator with Vite

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateHilla.java
Adds a method to `TaskGenerateHilla` that allows implementations to get some configuration, notably the path of the current Maven project.
Closes #14218
> feat: add configuration to `TaskGenerateHilla`

- flow-server/src/main/java/com/vaadin/flow/component/HasComponents.java
Added Collection based add / remove methods for `com.vaadin.flow.component.HasComponents`
Fixes #13598
> feat: provides collection based methods for HasComponents

- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
With Vite it may happend that '@import url(...)' in CSS are rewritten
as '@import ...', that is a valid CSS statement.
Currently the theme generator does not handle the case and this prevents
the resource to be added to the head section. A warning is also
logged on browser console, stating import rules not allowed when
creating stylesheets.
This change updates the importMatcher regex to handle @import without url
In addition it also handles media query declared in import statements.
> fix: support import without url keyword in theme generator

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
Duplicated root entry in manifest happens when running application
in development mode but after a frontend build.
This change removes the entry potentially added by flow
if compile-time manifest already added it
> fix: handle duplicated root entries in manifest

- flow-server/src/main/java/com/vaadin/flow/component/Component.java
- flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Changes return type to be compatible with classic components package API. Not a breaking change since this method was added recently for 23.2.
Related-to https://github.com/vaadin/classic-components-internal/pull/164
> fix: Make findAncestor return Object for backward compatibility

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
When checking for new NPM package versions, let's skip all versions that we do not understand.
Closes #14217
> feat: swallow exceptions on unparseable NPM package versions

- flow-tests/test-frontend/vite-pwa-custom-offline-path/pom-production.xml
- flow-tests/test-frontend/vite-pwa-custom-offline-path/pom.xml
- flow-tests/test-frontend/vite-pwa-production/pom.xml
- flow-tests/test-frontend/vite-pwa/pom.xml
Selenium grid now has chrome 103
This reverts commit 7f6155a19e39ee7fce06d4be4c6580253ae74912.
> Revert "test: workaround for internal selenium grid (#14174)"

- .github/workflows/validation.yml
based on a [recent change](https://github.blog/changelog/2022-07-19-differentiating-triggering-actor-from-executing-actor/) the addon that we have used cannot return the user info for GHA rerun any more. 
i have patch-fix the addon, so let us use it for now and updated it later when they have fixed the issue.
**after merging this, please rebase the PRs from external contributors.**
> chore: use a patch user permission checking

- flow-server/src/main/resources/vite.generated.ts
Flow theme plugin for Vite processes themes only on changes on files
in active theme directory.
This prevents regeneration with java live reload when changing value of
Theme annotation.
This change also triggers theme processing for updates on theme.js file.
> fix: let Vite process theme also on theme.js changes

- flow-server/src/main/resources/vite.generated.ts
Vite 'handleHotUpdate' hook is invoked only for file changes, not for creation nor deletion.
This change adds a watcher as well for those events and triggers theme regeneration
when theme file are added or deleted
Fixes #12154
> fix: handle theme files creation and deletion with Vite

- vaadin-dev-server/pom.xml
URL.setURLStreamHandlerFactory() can be invoked only once per JVM,
otherwise it throws an exception.
To support more tests in the same module using that method, URL.factory
private field should be nullified with reflection, but this fails with
Java 17 with java.lang.reflect.InaccessibleObjectException exception.
To make reflection work, this change add '--add-opens' flag to maven
surefire plugin configuration.
> test: open java.net module to allow reset of URL URLStreamHandlerFactory

- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/stats/ProjectHelpersTest.java
ProjectHelpersTest tests sets user.home system property
to a custom value, but they do not reset it after execution,
causing other tests to potentially fail or behave incorrectly.
This change resets user.home at original value after each test
> test: restore user.home system property after test

- flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
Allow window resize events when
modal component is set.
Fixes #14265
> Fix: Allow windowResize during modality

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Fix removal of node_modules so that
symlink and Windows junction directory
contents are not deleted also.
Fixes #14138
Closes #11177
> fix: Fix removal of windows junctions

- flow-tests/test-ccdm-flow-navigation/pom.xml
- flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/ReconnectIntervalConfigurer.java
- flow-tests/test-ccdm-flow-navigation/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
- flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
- pom.xml
Decreases heartbeat interval to make test more stable
Uses system property to detect development mode, since getting 'Vaadin.developmentMode' from browser returns wrong value in Bender validation job
> test: reduce flakyness of ccdm flow navigation tests

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
This PR adds a feature flag for the new field validation behavior. The flag will be used by Flow field components. For more information about the new behavior, please refer to https://github.com/vaadin/platform/issues/3066.
Part of https://github.com/vaadin/platform/issues/3066
> feat: add a feature flag for new field validation behavior

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/resources/vite.generated.ts
- flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
- flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Fixes #14142
Added `rollup-plugin-postcss-lit` and configured it to handle all CSS files except those under theme folder.
Note the extra entry with `?` is necessary until https://github.com/umbopepato/rollup-plugin-postcss-lit/issues/49 fixed.
Another entry added to `excludes` to workaround https://github.com/umbopepato/rollup-plugin-postcss-lit/issues/52
- Bugfix
> fix: use rollup-plugin-postcss-lit with Vite

- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/WebpackHandlerTest.java
In test, we stop HTTP server with 0 delay, so when performing
subsequent request, server may not yet be stopped.
In this case, we will have a SocketException with 'Connection reset' message.
Expecting a SocketException will also cover ConnectException case
> test: expect SocketException after stopping webpack handler

- flow-server/src/main/resources/vite.generated.ts
It may happen that when Vite analyses imports for theme.js file,
they are not yet generated of filesystem and this make compilation
fail.
This change checks for theme.js imports existence, and if not present
forces theme generation process
Should fix ThemeSwitchLiveReloadIT flakiness
> fix: regenerate theme files if not existing during Vite resolution

- flow-tests/test-frontend/vite-basics/pom.xml
`BasicsIT::debugWindowShown` is flaky: dev tool popup is not shown at all in CI, probably because the app is running in prod mode erroneously.
> test: Explicitly set dev mode for Vite basic tests

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
- flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/NpmOnlyIndexIT.java
- flow-tests/test-embedding/test-embedding-reusable-theme/pom.xml
The document that is generated by 
WebComponentBootstrapHandler was 
missing the needed CSS to be added 
to the shadow dom while using Vite. 
Fixes #14256
> fix: Add missing general styles to webcomponents shadow dom

- flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/pom.xml
When running in development mode we need to add Vite --host flag
so Vite client websocket connection will work when tests are
executed on a remote browser
> test: set --host Vite flag in development mode

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
- pom.xml
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
The new license checker is triggered also for production builds and requires an offline license for development in an offline environment. It no longer relies on third party cookies to resolve all browser compatibility issues.
Fixes https://github.com/vaadin/platform/issues/2984
> feat!: Fully enable new license checker

- flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
- flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java
Fixes User Agent in Chrome for iOS when the
Request Desktop Site feature is enabled.
At this time the version only consists of the major version.
part of #13921
> fix: Request Desktop Site feature with only MajorVersion

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
- flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/NpmOnlyIndexIT.java
- flow-tests/test-embedding/test-embedding-reusable-theme/pom.xml
The document that is generated by
WebComponentBootstrapHandler was
missing the needed CSS to be added
to the shadow dom while using Vite.
Fixes: #14256
(cherry picked from commit 16959a935433dc024ccc585d0003e7b6bc319d21)
> fix: Add missing general styles to webcomponents shadow dom (#14316)(CP: 23.1)

- flow-server/src/main/java/com/vaadin/flow/theme/NoTheme.java
Clarify that `@NoTheme` should be added to a class implementing `AppShellConfigurator`.
> chore: update @NoTheme Javadoc

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/NpmOnlyIndexIT.java
- flow-tests/test-embedding/test-embedding-reusable-theme/pom.xml
The document that is generated by
WebComponentBootstrapHandler was
missing the needed CSS to be added
to the shadow dom while using Vite.
Fixes: #14256
(manually cherry picked from commit 16959a935433dc024ccc585d0003e7b6bc319d21
and updates were made to FrontendUtils and
BootstrapHandler to make it compatible)
> fix: Add missing general styles to webcomponents shadow dom (#14316) (CP: 23.0)

- flow-client/src/main/frontend/Flow.ts
- flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
It sometimes happens that when window online listener is invoked, http
request to sw.js fails anyway with net::ERR_INTERNET_DISCONNECTED error,
even if navigator.onLine flag is true.
To reduce the possibility of a network failure in the online event listener,
the request is postponed by a little number of milliseconds.
Fixes #14364
> fix: postpone http request on online listener

- flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
When an application with PUSH enabled tries to re-establish the push connection
after a server restart, it may happen that the dev mode handler responds
to the push request with HTML contents (dev-mode-not-ready.html).
In this situation, an error is shown on the browser page, a manual page reload
is required to make the application work again.
This changes the request handlers order so that the PushRequestHandler is
executed before DevModeHandler
> fix: execute PushRequestHandler before DevModeHandler

- flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/PwaHandlerTest.java
PwaHandler has an isInitialized flag that is checked on handleRequest method,
but never initialized, causing init method to be invoked on every request.
This change sets the flag within init method.
> fix: initialize PwaHandler only once

- flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
Fixes the hashed segment removal logic:
if no segment with hash is present in the location,
while navigating between Flow and legacy views/components,
the update of the browser history is not needed.
Fixes https://github.com/vaadin/multiplatform-runtime/issues/115
> fix: Not modify browser history if location has no hash

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Makes ViewAccessChecker be accessible in the VaadinWebSecurity subclasses,
for example, to be able to override the security configuration for SSO.
> feat: Give an access to ViewAccessChecker in subclasses

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
- flow-server/src/test/java/com/vaadin/experimental/FeatureFlagsTest.java
Accepts a value for a feature flag passed through a system property and overrides existing value.
Closes #14407
> feat: allow to set a feature flag using a system property

- flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
- flow-server/src/main/java/com/vaadin/flow/internal/UrlUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
- flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerOnNestedMappingIT.java
- flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/ViewTestServlet.java
- flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/main/java/com/vaadin/flow/uitest/ui/servlets/ServletWithPath.java
- flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/test-webpack/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
- flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
- flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/CompressionIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VaadinPushScriptIT.java
- flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeEndpointTest.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/AbstractDevModeTest.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinMVCWebAppInitializer.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationRootMappedTest.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationUrlMappedTest.java
Changes static files loading so that:
1. The overall behavior is reverted to that in 23.0, i.e. static files are loaded from /context/servlet/VAADIN instead of /context/VAADIN
2. When using Vite in dev mode, uses the first deployed `VaadinServlet` to serve static resources. If you have both a `/foo/*` and a `/bar/*`mapped servlet, then if `/foo` is the servlet deployed first, also `/bar/` requests will use `/foo/VAADIN` for static resources.
This reverts commit af975389 
Fixes https://github.com/vaadin/flow/issues/14239
Fixes #13190
> fix!: Revert always load static files from context root (#13795)

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
I'm amending #14408 here. I realized that it is way more common to use dots than dashes as separator in system property names.
While there is no change in functionality, I'd prefer to follow the standards.
I'm sorry for that :)
> fix: hange prefix to `vaadin.` for feature flag system properties

- flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
Follow-up for https://github.com/vaadin/flow/pull/14357, revert unnecessary `/VAADIN/*` mapping, since the functionality for serving resources from context root has been reverted.
This reverts commit b9d07ebb
> Revert "test: Add VAADIN mapping to OSGi servlet registrations (#13855)"

- flow-server/src/main/java/com/vaadin/flow/dom/Element.java
- flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
when invoking setText(sometext) on an Element, using the same text as before, this still triggers some dom changes being sent to browser, even though nothing changes. This causes unnecessary network traffic and browser code to run.
The same situation is handled correctly for setProperty(prop,value) etc., so it should work the same way also for setText().
Fixes #14388
> fix: No client updates when Element::setText does nothing

- flow-server/src/main/java/com/vaadin/flow/dom/Element.java
- flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
This reverts commit 77a64eb8b0b1e0a5924226fed0fdd3d3b30428a5.
The fix made in https://github.com/vaadin/flow/pull/14389 breaks the case when the child nodes are added on the client side, see failing test `ClearNodeChildrenIT.addTextNode_setTextToContainerWithClientSideNodes_allNodesAreRemoved`.
To be reconsidered.
> Revert "fix: No client updates when Element::setText does nothing (#14389)

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/main/java/com/vaadin/flow/data/converter/ConverterFactory.java
- flow-data/src/main/java/com/vaadin/flow/data/converter/DefaultConverterFactory.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BeanBinderTest.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderInstanceFieldTest.java
- flow-data/src/test/java/com/vaadin/flow/data/converter/DefaultConverterFactoryTest.java
- flow-data/src/test/java/com/vaadin/flow/tests/data/bean/ConvertibleValues.java
- flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java
- flow-server/src/test/java/com/vaadin/flow/internal/ReflectToolsTest.java
Backporting #13373 
When binding a field and a property which do not have the same value type
an exception is thrown. With this change, an attempt is made to
automatically pick a suitable converter from the ones provided by the framework.
> feat: Automatically use available converters in Binder (CP: 2.8)

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
- flow-server/src/main/resources/tsconfig.json
> fix: Skip checking library code for TypeScript errors

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
Fall back to the OSGi bundle-version attribute if there is no implementation version
> chore: Mainly use Implementation-version

- flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
- pom.xml
manual cherry-pick of (#14424)
Fixes https://github.com/vaadin/platform/issues/3187
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-JAVA-ORGJSOUP-2989728
> fix!: Security upgrade of org.jsoup:jsoup to 1.15.3

- flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
- pom.xml
manual cherry-pick of (#14424)
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-JAVA-ORGJSOUP-2989728
> fix!: Security upgrade org.jsoup:jsoup to 1.15.3

- flow-server/src/main/resources/vite.generated.ts
There is an extra brotli plugin instance that I forgot to remove while working on https://github.com/vaadin/flow/pull/14370. It is not used anywhere.
> refactor: remove unused code

- flow-server/src/main/resources/vite.generated.ts
- flow-tests/test-frontend/vite-production/frontend/lit-invalid-imports.ts
- flow-tests/test-frontend/vite-production/package.json
- flow-tests/test-frontend/vite-production/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
The import rewrites must only match one row and not a similar import on the following row
Fixes https://github.com/vaadin/component-starter-flow/issues/369
> Make Lit import rewrites lazy

- flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java
When using Vite, DevModeInitializer blocks dev-server startup until a VaadinServlet is deployed because it needs to get the servlet path to use. If the container lazily loads servlets, Vite will not start until the first HTTP request for the Vaadin servlet is received.
This change sets load-on-startup feature for automatically deployed Vaadin servlet, to ensure that the servlet and Vite are loaded on the startup of the Web application
Part of #14479
> fix: set load-on-startup for automatically registered Vaadin servlet

- flow-client/package.json
@types/express-serve-static-core requires typescript version >= 4.1, see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51262
> chore: Align TS version in flow-client with flow-server

- flow-server/src/main/java/com/vaadin/flow/component/Html.java
- flow-server/src/test/java/com/vaadin/flow/component/HTMLTest.java
When using Html component as replacement for Vaadin 8's Label /w html content allowed, it is quite common use case to alter the content programmatically.
> feat: Allow setting content of the Html component

- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Moved item presence check to dataProvider to prevent fetching all items
Fixes #14170
> fix: Remove presence check on item refresh

- flow-server/src/main/java/com/vaadin/flow/component/dependency/NpmPackage.java
Updated javadocs to align it with current handling of duplicated versions. Build process does not fail, but it prints a warning
Ref #14381
> chore: update NpmPackage.version javadocs

- flow-server/src/main/java/com/vaadin/flow/component/page/ExtendedClientDetails.java
- flow-server/src/test/java/com/vaadin/flow/component/page/ExtendedClientDetailsTest.java
For iPad with iOS 15, navigator platform does not start with iPad anymore but is MacIntel.
This change assumes the device is an iPad when platform is MacIntel, and it is a touch device
Fixes #14517
> fix: adapt iPad detection for iOS 15

- flow-plugins/flow-maven-plugin/pom.xml
Having this dependency here brings an old and vulnerable version of `commons-codec`
> chore: remove not needed dependency since it comes from flow-server

- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
ClassFinder used for frontend build is missing build resources directory. This change adds it to the list of elements to scan during build.
Fixes #14420
> fix: add build resource dir to classpath element to scan

- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
ClassFinder used for frontend build is missing build resources directory. This change adds it to the list of elements to scan during build.
Fixes #14420
> fix: add build resource dir to classpath element to scan (#14536) (CP: 9.0)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractTaskClientGenerator.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractTaskClientGeneratorTest.java
Overwriting the files will cause the frontend tooling to recompile when there is no need to do that
Fixes #14490
> fix: Do not overwrite generated files with the same content

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Allows to use OpenSSL legacy provider, which is needed to build `flow-client` with Node 18 on the Linux used in Flow's CI.
See https://github.com/nodejs/node/releases/tag/v16.16.0.
> chore: Update automatically installed Node version to 16.17

- flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
- pom.xml
Reverted because 2.0 is not fully supported by Spring and might cause a breaking changes rather than package names.
> chore: Revert "chore(deps)!: bump slf4j.version from 1.7.36 to 2.0.0 (#14409)"

- flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorDataTest.java
* fix: Use KeyMapper by default for unique keys
* fix: Use KeyMapper by default to generate unique keys
Delegates to regular KeyMapper whenever the unique key provider is not present and a unique key is needed for a row.
Part-of: https://github.com/vaadin/flow-components/issues/3156
(cherry picked from commit 570244d9afadfd185689f9ec0d3ef40e985c02d2)
> fix: Use KeyMapper by default to generate unique keys (#13883) (CP:2.8)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
TaskUpdatePackage was still using FileUtils.
Fixes #12810
> fix: use FrontendUtils::deleteNodeModules (#12905) (CP:2.8)

- flow-server/src/main/java/com/vaadin/flow/internal/change/AbstractListChange.java
- flow-server/src/main/java/com/vaadin/flow/internal/change/ListAddChange.java
- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java
- flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java
Makes memory consumption optimisation for collecting state tree changes on the server-side: change list is checked and re-indexed (if needed) on each change, making removed objects be eligible for garbage collecting.
Fixes: #13851
(cherry picked from commit 317be63b69fa1cec4a48fd49a98c1e0989945764)
> fix: Be more sensible when adding changes to list of pending changes (#14478) (CP: 2.8)

- flow-plugins/pom.xml
Upper bound '17]' does not match correctly JDK 17. Quote from Maven docs:
> Note: an upper bound such as ,1.5] is likely not to include most releases of
> 1.5, since they will have an additional 'patch' release such as _05 that is
> not taken into consideration in the above range.'
Updating range to catch every version lower than 18
> chore: fix gradle profile activation

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/server/scanner/ReflectionsClassFinderTest.java
Class scan in production build may differ from development mode because DefaultClassFinder and ReflectionsClassFinder may provide classes in different order. As a result, when there are multiple NpmPackage annotations for the same package with different version, the final version used in package.json may be different in dev mode and production build.
This change makes ReflectionsClassFinder sort classes by name, as DefaultClassFinder does in its constructor.
Ref #14381
> fix: sort classes by name in ReflectionsClassFinder

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
If setLoginView is provided with a path to a Java Flow view, not accessible by anonymous users, when navigating to the login page the browser start reloading the page infinitely.
This change updates javadoc to remind that the java class must be annotated with AnonymousAllowed.
Refs #14582
> chore: remind Flow view must grant anonymous access if using setLoginView with path

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
If setLoginView is provided with a path to a Java Flow view, not accessible by anonymous users, when navigating to the login page the browser start reloading the page infinitely.
This change updates javadoc to remind that the java class must be annotated with AnonymousAllowed.
Refs #14582
> chore: remind Flow view must grant anonymous access if using setLoginView with path (#14588) (CP: 23.1)

- flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java
- flow-server/src/test/java/com/vaadin/flow/server/auth/AccessAnnotationCheckerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/auth/ViewAccessCheckerTest.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSavedRequestAwareAuthenticationSuccessHandler.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinSavedRequestAwareAuthenticationSuccessHandlerTest.java
This is to fix the problem of navigating to a secured view
from a public view before login in while using the OAuth2 external
login page. Prior to this, it was needed to set "router-ignore" 
attribute on the links from public pages to skip vaadin-router and 
let the spring-security forward the user to the external login page. 
Fixes #14253
> fix: Fix navigation to secured view with oauth2 without router-ignore

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
- flow-server/src/main/resources/tsconfig.json
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfigTest.java
> fix: Use es2020 for Vite, es2019 for webpack

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/FrontendStubs.java
Fix installation of node for unix systems.
NodeJS 18 is more strict about where
the contents are located than old versions.
Fixes #14636
> fix: linux node installation

- vaadin-spring/src/main/resources/META-INF/spring.factories
- vaadin-spring/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Spring Boot introduced a new location for auto configuration entries in spring boot 2.7.0. The new location is `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`. This has until spring boot 3.0.0-M5 worked in parallel with the spring.factories configuration.
The spring.factories support was removed in spring boot 3.0.0-M5 so this move has to be done now in order for the auto configuration to be picked up.
Fixes #14628
> feat: Adapt to a new auto configuration in Spring Boot

- flow-tests/vaadin-spring-tests/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/test/CustomWebSocket.java
- flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/CustomWebSocketIT.java
- flow-tests/vaadin-spring-tests/test-spring-war/pom.xml
- vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinMVCWebAppInitializer.java
(cherry picked from commit f4c7497e260c42940c049d8f82c383bbfacc9b78)
> fix: Only map websockets to servlet path and not any sub paths (#14638) (CP 23.2)

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
When configuring global method security the `GlobalMethodSecurityConfiguration` picks up the wrong `SecurityContextHolderStrategy` because it gets the `SecurityContextHolderStrategy` from the `SecurityContextHolder` befor the vaadin security configuration has overridden it. If the `GlobalMethodSecurityConfiguration` finds a `SecurityContextHolderStrategy` bean it will use that as the strategy instead of the default picked up from the `SecurityContextHolder`.
Fixes #14585
> feat: Register VaadinSecurityContextHolderStrategy as a bean

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
- flow-server/src/test/java/com/vaadin/experimental/FeatureFlagsTest.java
Enable or disable a feature flag by providing a system property is not working when feature flags file is loaded by a ResourceProvider. This change makes system properties always take precedence over stored values
Fixes #14679
> fix: make system property feature flag value always override stored one

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsSettings.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksViteTest.java
As the default download root might be
different depending on the used system
we should not use a hardcoded default if
user has not given a download root.
Fixes #13837
> fix: Do not use a fixed download root

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsSettings.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
As the default download root might be
different depending on the used system
we should not use a hardcoded default if
user has not given a download root.
Fixes #13837
> fix: Do not use a fixed download root (#14632)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesNpmVersionLockingTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
The earlier logic was like
1. Read package.json
2. Modify package.json in memory
3. Generate version.json based on package.json file
4. Write modified package.json to file
Where step 3 ignored what was done in step 2
> fix: Write version.json from the currently constructed package.json

- flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Added Windows check assumption to make TeamCity branches green again.
> test: fix BootstrapHandlerTest on Windows

- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Added Windows check assumption for FrontendUtilsTest.deleteNodeModules_canDeleteSymlinksAndNotFollowThem 
Fixes #14716
> test: Added Windows check assumption for FrontendUtilsTest.deleteNodeModules_canDeleteSymlinksAndNotFollowThem #14716

- flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
> test: fix BootstrapHandlerTest on Windows (#14715) (CP 2.8)

- flow-client/src/main/java/com/vaadin/client/flow/StateTree.java
- flow-client/src/main/java/com/vaadin/client/flow/TreeChangeProcessor.java
- flow-client/src/test/java/com/vaadin/client/flow/TreeChangeProcessorTest.java
Ignore changes for nodes that are not
available in the tree when a resync is underway.
This will get the page to a working
condition after a resync as all changes for
existing nodes are executed.
Fixes #14232
Fixes #14470
> fix: ignore nonexistent nodes during resync

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
Binder addValueChangeListener JavaDoc was not clear, updated to make sure it's obvious that failing validations will not block.
Fixes #9099
- [x ] Bugfix
- [ x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x ] I have added a description following the guideline.
- [x ] The issue is created in the corresponding repository and I have referenced it.
- [ n/a] I have added tests to ensure my change is effective and works as intended.
- [ n/a] New and existing tests are passing locally with my change.
- [x ] I have performed self-review and corrected misspellings.
> chore: update Binder ValueChangeListener javadocs

- flow-client/src/main/java/com/vaadin/client/flow/StateTree.java
- flow-client/src/main/java/com/vaadin/client/flow/TreeChangeProcessor.java
- flow-client/src/test/java/com/vaadin/client/flow/TreeChangeProcessorTest.java
Ignore changes for nodes that are not
available in the tree when a resync is underway.
This will get the page to a working
condition after a resync as all changes for
existing nodes are executed.
Fixes #14232
Fixes #14470
> fix: ignore nonexistent nodes during resync (#14749)

- flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
> fix: Redirect if refresh token is in push response also

- flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
> fix: Redirect if refresh token is in push response also (#14777)

- flow-client/src/main/java/com/vaadin/client/PopStateHandler.java
- flow-tests/test-v14-bootstrap/src/main/java/com/vaadin/flow/navigation/ui/FirstView.java
- flow-tests/test-v14-bootstrap/src/main/java/com/vaadin/flow/navigation/ui/SecondView.java
- flow-tests/test-v14-bootstrap/src/test/java/com/vaadin/flow/navigation/ui/BrowserNavigationServerRoundTripIT.java
Track of location and query string after response from server happens too early when handling server side navigation, because history.pushState is executed within a setTimeout. This change defers the tracking to the next event loop cycle in order to get the correct values.
Fixes #14323
> fix: defer location and query tracking

- flow-tests/pom.xml
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
This is only meant for debugging the dev server itself and the connection to it
> feat: Allow specifying vaadin.devServerPort to connect to an already running dev server

- flow-client/src/main/java/com/vaadin/client/PopStateHandler.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/navigation/FirstView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/navigation/SecondView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/navigation/BrowserNavigationServerRoundTripIT.java
Track of location and query string after response from server happens too early when handling server side navigation, because history.pushState is executed within a setTimeout. This change defers the tracking to the next event loop cycle in order to get the correct values.
Fixes #14323
> fix: defer location and query tracking (#14742) (CP: 2.8)

- flow-tests/pom.xml
- flow-tests/vaadin-spring-tests/pom.xml
- pom.xml
This should fix this [issue with nexus-staging-maven-plugin](https://stackoverflow.com/questions/70153962/nexus-staging-maven-plugin-maven-deploy-failed-an-api-incompatibility-was-enco)
> chore: Update nexus-staging-maven-plugin version

- flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
Fixes rendering issue of the example code in the Javadoc for the `AppShellConfigurator` class.
See [Javadoc.io](https://javadoc.io/doc/com.vaadin/flow-server/latest/com/vaadin/flow/component/page/AppShellConfigurator.html) and note how the example code in the class header comment is rendered as one long line.
Fixes #14794.
> Fix Javadoc rendering in AppShellConfigurator

- pom.xml
> chore: update vaadin-parent to 2.1.0 (24.0)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Log out used tool path before checking
version to be able to debug faulty version
exceptions.
> chore: Log used tool before check

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
npm should log also before validate and
not only check
> chore: validate tool after debug log

- pom.xml
Reapplies the old commit which was reverted as part of the Servlet 5 upgrade
Bumps jaxb-impl from 4.0.0 to 4.0.1.
---
updated-dependencies:
- dependency-name: com.sun.xml.bind:jaxb-impl dependency-type: direct:development update-type: version-update:semver-patch ...
> chore(deps-dev): bump jaxb-impl from 4.0.0 to 4.0.1 (#14600)

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
When configuring global method security the GlobalMethodSecurityConfiguration picks up the wrong SecurityContextHolderStrategy because it gets the SecurityContextHolderStrategy from the SecurityContextHolder befor the vaadin security configuration has overridden it. If the GlobalMethodSecurityConfiguration finds a SecurityContextHolderStrategy bean it will use that as the strategy instead of the default picked up from the SecurityContextHolder.
Fixes #14585
> feat: Register VaadinSecurityContextHolderStrategy as a bean (#14631)

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinServletContext.java
> Potential solutions (I did not really think these through):
> 
> Lock on vaadin context in getCachedIndexHtmlDocument to avoid locking in another order. Seems quite fragile and there might be other similar cases here and there.
> Use the same object for locking in all cases. Can't see why we really need to synchronize on different ones for these operations
Only lock on FeatureFlags when checking for wrapper and initializing
Fixes #13962
> fix: locking on FeatureFlags instead of VaadinContext (#13962)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Fix so that if we have a usable old
node installation we check the correc
path for npm script.
Fixes #14839
> fix: old node installation

- flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
Synchronize pwa handler on the
requestHandlerMap instead of
locking the session.
Locking and unlocking session may
fire a push event that might make the
server client sync faulty.
touches #14797
> fix: synchronize pwa handler on map

- flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
Synchronize pwa handler on the
requestHandlerMap instead of
locking the session.
Locking and unlocking session may
fire a push event that might make the
server client sync faulty.
touches #14797
> fix: synchronize pwa handler on map (#14838)

- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
Use access so that we do not
block with the lock
Fixes vaadin/multiplatform-runtime#101
> fix: use access and not lock

- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
Use access so that we do not
deadlock.
Fixes vaadin/multiplatform-runtime#101
> fix: use access and not lock (#14827)

- flow-server/src/main/java/com/vaadin/flow/router/ParameterDeserializer.java
- flow-server/src/main/java/com/vaadin/flow/router/RouteParameterRegex.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
HasUrlParameter<Long> now accepts all valid
long values and throws in the case where
value is out of Long range.
Fixes #14747
> fix: long parameter regex

- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
This requires all applications to also change any usage of authorizeRequests to authorizeHttpRequests
> chore!: Use authorizeHttpRequests instead of deprecated authorizeRequests

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
This PR forces Spring to use the deprecated CSRF handler to make Hilla auth work. This is only a temporary solution until Hilla is updated to work with the modern CSRF handler [`XorServerCsrfTokenRequestAttributeHandler`](https://github.com/spring-projects/spring-security/issues?q=gh-4001+) which is more secure.
Related to https://github.com/vaadin/hilla/pull/616
> fix: enforce the deprecated CSRF handler temporarily

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
If application folder changes we should
execute npm install to get any folder
references updated.
Fixes #14908
> fix: run npm install if folder changes

- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
Spring Security uses an mvc matcher automatically and that does not match paths the same way
> test: Explicitly use AntPathRequestMatcher to avoid problems

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSavedRequestAwareAuthenticationSuccessHandler.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/stateless/VaadinStatelessSecurityConfigurer.java
This is needed when the login response is an xhr and does not cause a page reload. The csrf token is needed immediately after the login request e.g. to be able to query the user info from an endpoint in Hilla
In earlier Spring Security versions, the new csrf was automatically generated and sent in [CsrfAuthenticationStrategy](https://github.com/spring-projects/spring-security/blob/aed7a869dfbba4f545ecd59174a83e19728227a9/web/src/main/java/org/springframework/security/web/csrf/CsrfAuthenticationStrategy.java#L59-L60) when authentication succeeded but this was removed in Spring Security 6.0 RC1
> fix: Send new csrf cookie in login response

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
If application folder changes we should
execute npm install to get any folder
references updated.
Fixes #14908
> fix: run npm install if folder changes (#14909)

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Remove any comment blocks in CSS
before creating link references.
Fixes #14770
> fix: clean commented css before handling

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
Remove any comment blocks in CSS
before creating link references.
Fixes #14770
> fix: clean commented css before handling (#14924)

- .github/workflows/validation.yml
referenece https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> chore: update github/action file to get rid of the warnings

- flow-tests/test-application-theme/test-reusable-as-parent-vite/src/main/java/com/vaadin/flow/uitest/ui/theme/MyPolymerField.java
- flow-tests/test-application-theme/test-reusable-as-parent/src/main/java/com/vaadin/flow/uitest/ui/theme/MyPolymerField.java
- flow-tests/test-application-theme/test-theme-reusable-vite/src/main/java/com/vaadin/flow/uitest/ui/theme/MyComponent.java
- flow-tests/test-application-theme/test-theme-reusable/src/main/java/com/vaadin/flow/uitest/ui/theme/MyComponent.java
- flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/main/java/com/vaadin/flow/uitest/ui/theme/MyComponent.java
- flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/MyComponent.java
- flow-tests/test-embedding/test-embedding-reusable-theme/src/main/java/com/vaadin/flow/webcomponent/MyComponent.java
- flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/ThemableTextField.java
- flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/MyComponent.java
Fixed the package name to get rid of the warning and make it possible to bump `TestVersion.VAADIN` to V24:
```
[main] WARN com.vaadin.testbench.AbstractBrowserTestBase - This message in browser log console may be a potential error: '[2022-11-08T10:30:18.892Z] [WARNING] webpack-internal:///../node_modules/.pnpm/@vaadin+vaadin-text-field@23.3.0-alpha2/node_modules/@vaadin/vaadin-text-field/src/vaadin-text-field.js 19:8 "WARNING: Since Vaadin 23.2, \"@vaadin/vaadin-text-field\" is deprecated. Use \"@vaadin/text-field\" instead."'
```
- Tests
> test: use non-prefixed version of text-field

- flow-server/src/main/java/com/vaadin/flow/server/Constants.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
This makes Flow keep its installed Node version up to date. Manually installed node versions are not affected
> chore!: Enable auto update of installed Node by default

- flow-plugins/flow-gradle-plugin/README.md
Described an alternative way of making your project use the local Gradle plugin for testing purposes. The Composite Build approach doesn't work when you need to test some changes in `flow-plugin-base` rather than directly in `flow-gradle-plugin`.
> doc: Explain how to use Gradle plugin from the local Maven repo

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
The blacklisted versions are older then the supported version and should thus have no effect ever
> chore: Remove blacklisted npm versions which are out of date

- flow-server/src/main/resources/vite.generated.ts
The generated jar-resources are now inside the frontend folder so no special case should be needed
> chore: Remove special jar resources allow

- flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
> fix: Do not log null if servlet deployer is disabled

- .github/workflows/validation.yml
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/FrontendStubs.java
Node 18 is the latest LTS version and what everbody should at least have going forward
> chore!: Require Node 18 (npm 8.6)

- vaadin-spring/pom.xml
Without this you get
The type org.springframework.security.oauth2.client.web.OAuth2LoginAuthenticationFilter cannot be resolved. It is indirectly referenced from required type org.springframework.security.config.annotation.web.configurers.oauth2.client.OAuth2LoginConfigurer
> chore: Add dependency needed to properly compile VaadinWebSecurity

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinConvertPolymerTask.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPlugin.kt
- flow-polymer2lit/README.md
The PR adds a `./gradlew vaadinConvertPolymer` Gradle task that converts Polymer-based sources to Lit.
**The following parameters are supported:**
- **`-Dvaadin.useLit1`** forces the converter to use `lit-element` rather than `lit` imports.
- **`-Dvaadin.disableOptionalChaining`** disables the usage of the optional chaining operator which can be helpful for projects still based on Webpack.
- **`-Dvaadin.path=/path/to/directory/or/file`** allows specifying the path to a file or directory that needs to be converted. By default, the converter scans all `**/*.js` and `**/*.java` files in the project.
A follow-up to #14972
> feat: Add Gradle support for polymer2lit

- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
The new gretty version required jdk11 and is thus not compatible.
3.0.1 is again found online so there must have been an outage somewhere previously.
> Revert "test: update gretty version (#15024) (#15028)"

- flow-server/src/main/java/com/vaadin/flow/server/communication/JSR356WebsocketInitializer.java
Fixes #14889
The fix is similar to what is already there for `WsocServlet`, and is far from optimal. This should be revisited when considering #15086.
> Skip IBMRestServlet when checking for VaadinServlet

- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/ConvertPolymerMojo.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/ConvertPolymerCommand.java
- flow-polymer2lit/README.md
- flow-polymer2lit/src/main/java/com/vaadin/flow/polymer2lit/FrontendConverter.java
- flow-polymer2lit/src/main/java/com/vaadin/flow/polymer2lit/ServerConverter.java
Corrects `convert into Lit` to `convert to Lit` in the context of `source files` in JSDoc and README.
> doc: Use more appropriate prepositions

- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/ConvertPolymerCommandTest.java
This is a leftover from some refactoring in #14972 during development.
> test: Rename ConvertPolymerExecutorTest to ConvertPolymerCommandTest

- flow-polymer2lit/convert.ts
- flow-polymer2lit/src/test/java/com/vaadin/flow/polymer2lit/FrontendConverterTest.java
- flow-polymer2lit/src/test/resources/frontend/expected/dom-repeat-disabled-optional-chaining.js
- flow-polymer2lit/src/test/resources/frontend/expected/dom-repeat.js
- flow-polymer2lit/src/test/resources/frontend/expected/nested-dom-repeat-disabled-optional-chaining.js
- flow-polymer2lit/src/test/resources/frontend/expected/nested-dom-repeat.js
This PR prevents adding an extra dot to expressions that consist of only one variable that is assumed to never be null. This could occur before when running the converter with the enabled optional chaining operator.
```diff
${this.items.map(
(item, index) => html`
-    <div>${index.}</div>
+    <div>${index}</div>
`
)}
```
A follow-up #14972
> fix: Prevent adding an extra dot to expressions consisting of one non-null variable

- flow-polymer2lit/convert.ts
- flow-polymer2lit/src/test/resources/frontend/expected/dom-repeat.js
- flow-polymer2lit/src/test/resources/frontend/expected/inline-styles.js
- flow-polymer2lit/src/test/resources/frontend/expected/multiple-bindings.js
- flow-polymer2lit/src/test/resources/frontend/expected/nested-dom-repeat.js
- flow-polymer2lit/src/test/resources/frontend/expected/order-card-from-bakery.js
The PR makes the converter add a default value to expressions that are built with the optional chaining operator. Before, the converter used to add a default value only in the case optional chaining was disabled.
```diff
<div>
- ${account?.info?.friends.map((name) => name)}
+ ${(account?.info?.friends || []).map((name) => name)}
</div>
```
A follow-up to #14972
> fix: Add a default value to expressions when optional chaining is enabled

- flow-commons-upload/pom.xml
- flow-lit-template/pom.xml
- flow-plugins/flow-plugin-base/pom.xml
- flow-polymer-template/pom.xml
- flow-server/src/test/java/com/vaadin/flow/server/MockServletContext.java
- flow-tests/test-memory-leaks/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-boot/pom.xml
- pom.xml
As Spring Boot now uses Tomcat 10.1, we cannot mix Jetty 11 (servlet 5) and Tomcat 10.1 (servlet 6) in the same test modules so they are all run with Jetty 11 for now.
> chore: Upgrade to Spring Boot 3 RC2

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/FrontendStubs.java
Fix installation of node for unix systems.
NodeJS 18 is more strict about where
the contents are located than old versions.
Fixes #14636
> fix: linux node installation (#14657) (#14825)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Makes debugging easier when you know e.g. why npm --version exited with code 254
> chore: Show command output when it fails

- flow-polymer2lit/package.json
- flow-polymer2lit/pom.xml
The PR creates an individual npm script for compiling `convert.ts` instead of running it on `postinstall` which may happen to be disabled by `ignore-scripts=true` in `.npmrc`.
> fix: Create an individual npm script for compiling convert.ts

- flow-server/src/main/resources/plugins/stats-plugin/stats-plugin.js
https://github.com/vaadin/flow/pull/6919 added optimization of stats.json
However due https://github.com/vaadin/flow/pull/8519 there is regression as chunks are not filtered in similar fashion and stats.json is overgrown again.
> fix: Filter chunks to minimize stats.json

- flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/StreamReceiverHandlerTest.java
Do not call the error handler for upload
io exceptions. Only inform as streaming
failed.
Fixes #13736
> fix: suppress error handler for upload

- flow-server/src/main/resources/tsconfig.json
Related to Vite 3.2 issue: https://github.com/vitejs/vite/issues/10296 
- Bugfix
> fix: set useDefineForClassFields to false in tsconfig.json

- flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
- flow-server/src/main/resources/webpack.generated.js
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
This is compatible with Webpack 5
> chore: Use env instead of custom parameter to webpack (#9934) (CP: 2.8)

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/ConvertPolymerCommand.java
The PR enhances `ConvertPolymerCommand` to make it show some statistics about how many files have been processed and their conversion status.
A follow-up to #14956
> chore: Show statistics after Polymer to Lit conversion

- flow-tests/vaadin-spring-tests/pom.xml
The PR updates `jakarta.websocket` from `2.0.0` (Jakarta 9) to `2.1.0` (Jakarta 10) for `vaadin-spring-tests`. This seems to be a leftover from the recent Spring Boot RC2 upgrade.
> test: Update jakarta.websocket to 2.1.0

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
Follow-up to #15165. Looks like I missed to update the other `tsconfig.json` so the build still fails:
- Bugfix
> fix: set useDefineForClassFields in generated tsconfig.json

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Update npm version to match the node
16.18.1 default npm.
> chore: update the expected default npm version

- pom.xml
> chore: Upgrade license checker to 1.11.2

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
The package.json hash is now again a hash of the contents and can be used by other tools to check if the content (installed packages) has changed
Fixes #14908 in a different way
> refactor: Record project folder inside node_modules instead

- flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
- flow-tests/test-embedding/test-embedding-reusable-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Now compatible with both Vite 3 and 4
> test: Care less about the exact format Vite/rollup use to names files

- flow-server/src/main/java/com/vaadin/flow/internal/ServerInfo.java
Use vaadin-core-versions instead of
vaadin-versions as core-versions is also available when using the full vaadin dependency
Fixes #15236
> fix: Get vaadin version from core

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
This is needed to allow built in tasks to extend other built-in tasks
> chore: Return an exact match before checking inheritance

- flow-server/src/main/resources/plugins/stats-plugin/package.json
- flow-server/src/main/resources/plugins/stats-plugin/stats-plugin.js
In development mode the local
frontend stat files got left out
from the cleaned stats that
webpack served
> fix: stats in development mode

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/DevModeUsageStatistics.java
initDevModeHandler is called when Spring dev tools restart so this message is logged once per restart for no good reason
> chore: Remove warning about stats init

- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
- flow-server/src/test/java/com/vaadin/tests/server/SerializationTest.java
Do not serialize the streamResourceRegistry
if UIs are not serialized.
Fixes #14893
> fix: no stream serialization without uis

- flow-html-components/src/main/java/com/vaadin/flow/component/html/Image.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/ImageTest.java
Giving the alternate text in the constructor
should generate a property to the image.
Fixes #14880
> fix: Empty alt in costructor should add property

- flow-server/src/main/java/com/vaadin/flow/component/Component.java
- flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Reduces coupling between UI components (and/or ugly code)
> feat: Added a shorthand to remove a component from its parent

- flow-html-components/src/main/java/com/vaadin/flow/component/html/Image.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/ImageTest.java
Giving the alternate text in the constructor
should generate a property to the image.
Fixes #14880
> fix: Empty alt in costructor should add property (#15292) (2.8)

- flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicationController.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorDataTest.java
For hierarchical data, even when the child components are filtered out, the `clear` method on `ArrayUpdater.Update` in `HierarchicalCommunicationController` is never called. This is caused by an if check, in which the start index of `previousActive` is compared to the newly calculated `assumedSize`. Since there might be items to clear, the newly calculated size should have no effect on whether we clear the items or not. This check is not present in the `DataCommunicator` counterpart within the method `collectChangesToSend`.
This PR removes the aforementioned clear condition. Add test to ensure that the expanded children are cleared properly when filtered out.
Fixes #[4132](https://github.com/vaadin/flow-components/issues/4132)
> fix: remove clear condition for hierarchical data

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig-v23.3.0.json
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
- flow-server/src/main/resources/tsconfig.json
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfigTest.java
- flow-server/src/test/resources/tsconfig-latest-version.json
- flow-server/src/test/resources/tsconfig-reference.json
Summary of changes:
- Added a good default for `jsx` setting
- Relaxed file extensions for TypeScript, so that `.tsx` and such are considered
This should not interfere with existing TypeScript / Lit-based code.
> feat(hilla): make tsconfig.json React compatible

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
* Revert "fix: run npm install if folder changes (#14909)"
This reverts commit abc08f863924001b16be838cfb16f0cd8d922e5d.
The earlier patch is not needed as target/flow-frontend is no longer used. Additionally using a hash that is dependent on the project folder makes the hash unusable for other purposes, such as determining if the package.json contents has changed.
The package.json hash is now again a hash of the contents and can be used by other tools to check if the content (installed packages) has changed
Fixes #14908 in a different way
> refactor: Record project folder inside node_modules instead (#15216) (CP: 23.2)

- flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
- flow-client/src/main/java/com/vaadin/client/communication/PushConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/component/PushConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/internal/BootstrapHandlerHelper.java
- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/PushConfigurationMap.java
- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/Constants.java
- flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
- flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/AbstractDeploymentConfigurationTest.java
- flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
- flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
- flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
- flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/MockDeploymentConfiguration.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinMVCWebAppInitializer.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationRootMappedTest.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationUrlMappedTest.java
Removes pushUrl configuration option, and instead maps push always to a dedicated path (/VAADIN/push).
Related-to #14641
> fix!: Use dedicated mapping for Vaadin push endpoint

- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/LoadingIndicatorConfigurationMap.java
The current initial delay to show loading indicator seems quite short. If one deploys an app to another continent, even no op visits can make the indicator "flash". This may kind of just increases the feeling of "broken app". Especially as the indicator in latest versions is bold visually.
Still, at least mine app feels perfectly usable and don't even realise there is a server visit. I don't have the skills to me the indication look less bolder, so I'd just propose to increase the delay a bit. With this level (450ms) all seems to work fine for my app, but maybe it could be even bit longer still 🤷‍♂️
> Increase initial delay to show loading indicator

- flow-server/src/main/java/com/vaadin/flow/router/AfterNavigationEvent.java
- flow-server/src/main/java/com/vaadin/flow/router/BeforeEnterEvent.java
- flow-server/src/main/java/com/vaadin/flow/router/NavigationTrigger.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
Add the isRefreshEvent to BeforeEnterEvent
and AfterNavigationEvent to be make it possible
to diustinguish if the event is for a refresh of
a preserve on refresh view.
Fixes #14999
> feat: add refresh flag to navigation event

- flow-client/pom.xml
Makes the build work even when you are using --ignore-scripts
> test: Always run postinstall for esbuild in flow-client

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Vite 4 final is targeted for December so it fits the Vaadin 24 release plan
> chore: Upgrade to Vite v4.0.0-alpha.6

- flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
Fallback to a root mapping for push in case if not servlet registration is available (OSGi runtime).
> fix: Use root servlet mapping for push url in OSGi case

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorDataTest.java
With a `TreeGrid`, the expanded state of a root item gets lost when scrolled enough to request a new range. The cause for this is the updated key of the returned item. The expanded state for the items except the root items do not get lost. 
This PR makes sure that the key-value pair for a root item persists in the `KeyMapper` if the item is expanded. This change only affects hierarchical data. A test is added to ensure that the fix solves the issue.
While this refactoring is less than ideal in terms of clean code, I think that the alternative requires a much larger refactoring. The logic in the regular and hierarchical data communicators are mostly both coupled and duplicated with private methods at this time. Therefore, this PR is as atomic as possible.
Fixes …
> fix: do not remove expanded items from key mapper

- flow-server/src/main/java/com/vaadin/flow/component/Component.java
- flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Component locale should return a locale
even when UI and i18nProvider are not
available.
Fixes #15313
> fix: Component locale works without UI and i18n

- flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
- flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
ComponentTest.getComponentLocale_noCurrentUI_returnsDefaultLocale assumes that I18nProvider is null but it may have been initialized by another test. This change makes the Instantiator instance a mockito spy so that it can be instructed by the tests to return a null I18nProvider instance.
> test: ensure ComponentTest preconditions

- flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
- flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
ComponentTest.getComponentLocale_noCurrentUI_returnsDefaultLocale assumes that I18nProvider is null but it may have been initialized by another test. This change makes the Instantiator instance a mockito spy so that it can be instructed by the tests to return a null I18nProvider instance.
> test: ensure ComponentTest preconditions (CP: 23.3)

- flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
- flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
ComponentTest.getComponentLocale_noCurrentUI_returnsDefaultLocale assumes that I18nProvider is null but it may have been initialized by another test. This change makes the Instantiator instance a mockito spy so that it can be instructed by the tests to return a null I18nProvider instance.
> test: ensure ComponentTest preconditions (CP: 2.8)

- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityUtils.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/service/BankService.java
- vaadin-spring/pom.xml
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/UidlRedirectStrategy.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/security/AuthenticationContextTest.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/security/UidlRedirectStrategyTest.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinWebSecurityTest.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/security/stateless/JwtSecurityContextRepositoryTest.java
AuthenticationContext bean provides an API for getting authenticated user details and logout capabilities.
Fixes https://github.com/vaadin/flow/issues/14958
> feat: Add the authentication context API to the Vaadin Web Security

- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
Stack trace to debug sync id increment is verbose. Log it at trace level.
Fixes #15396
> chore: log server sync id stack at trace level

- flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
In dev mode, the index.html in the project was not used but instead the Vite index.html was served
> fix: Do not serve Vite index.html for /index.html

- flow-server/src/main/resources/vite.generated.ts
- flow-tests/test-frontend/vite-basics/package-outside-npm/index.js
- flow-tests/test-frontend/vite-basics/package.json
- flow-tests/test-frontend/vite-basics/package2-outside-npm/index.js
- flow-tests/test-frontend/vite-production/package.json
- flow-tests/test-frontend/vite-production/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
- flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/ExternalPackageIT.java
- flow-tests/test-frontend/vite-test-assets/packages/package-outside-npm/.gitignore
- flow-tests/test-frontend/vite-test-assets/packages/package-outside-npm/index.js
- flow-tests/test-frontend/vite-test-assets/packages/package-outside-npm/node_modules/package-transitive
- flow-tests/test-frontend/vite-test-assets/packages/package-outside-npm/package.json
- flow-tests/test-frontend/vite-test-assets/packages/package-transitive/index.js
- flow-tests/test-frontend/vite-test-assets/packages/package-transitive/package.json
- flow-tests/test-frontend/vite-test-assets/packages/package2-outside-npm/.gitignore
- flow-tests/test-frontend/vite-test-assets/packages/package2-outside-npm/index.js
- flow-tests/test-frontend/vite-test-assets/packages/package2-outside-npm/node_modules/package-transitive
- flow-tests/test-frontend/vite-test-assets/packages/package2-outside-npm/package.json
Fixes #15395
Modifies the Vite stats.json plugin so that only direct dependencies are considered in `npmModules`, assuming that transitive dependency versions are not relevant.
In addition, includes integration testing setup up with a transitive dependency for Vite, in both development and production modes.
> fix: Vite production build errors with transitive dependencies

- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Checks the navigation targets including parent layouts and takes the page title from the one implementing HasDynamicTitle.
Fixes: #13871
> fix: added HasDynamicTitle checking in parent layouts (#15355) (CP 2.8)

- .github/workflows/validation.yml
This PR reverts partially https://github.com/vaadin/flow/pull/15261 because it still does not prevent outside collaborators running the workflow as it's demonstrated in the PR https://github.com/vaadin/flow/pull/15433 that was able to run all the workflow steps in the action https://github.com/vaadin/flow/actions/runs/3670083099
The problem is that the 'Require approval for outside collaborators' flag in the github 'settings -> actions' section only 
applies for `pull_request` event, but we still need to configure our projects to use `pull_request_target` one, since we need that the secret for the TB license is available for running ITs in the contribution branch.
As a bonus, this PR removes the need of using a forked version of the  `ZheSun88/check-user-permission` action in `ZheSun88`
> chore: re-enable the check for outside collaborators

- .github/workflows/validation.yml
Only first attempt can take advantage of flow compilation in `build` job, because uploaded artefact is discarded after that, so for successive attempts we need to recompile flow as is performed with this PR.
> chore: allow re-running failed jobs in GH actions

- flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
New license checker warning should be printed only on development mode
Fixes #15407
> fix: don't warn about new license checker in production mode

- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
When adding license checker script a global constant name originalCustomElementDefineFn is declared. This produces browser errors in portlet addon, because the script may be added multiple times on the same page.
This patch stores the originalCustomElementDefineFn reference under window.Vaadin container and adds a guard to set it only if not already present.
> fix: avoid duplicate JS const declaration on license checker script

- .github/workflows/validation.yml
The `actions/upload-artifact` action is quite time demanding when dealing with a long list of files.
This change uploads only one compressed-file with all tests per job.
This reduces the size of the saved artifact from 30MB to 2MB, and the overall build process in 6 minutes.
The only cons is that the developer has to download the `zip` artifact, uncompress it, and then uncompress a second time the file containing the test she is interested on, but still it should be easier to locate the test since they are distributed in files with the job name.
> chore: reduce upload/download artifact times

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
Uses `lib` for specifying the version to not break the older browsers support (preserve old JS target ).
> fix: Use es2019 for TS compiler

- flow-server/src/main/resources/vite.generated.ts
Vite gives modules list as `C:/Users/`
where as the nodeModulesFolder is `C:\Users\`
Unify path separator for both when executing.
> fix: vite module path for windows

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/security/AuthenticationContextTest.java
Principal name usually refers to a user identifier that can be used to retrieve additional details.
Fixes #15484
> feat: added method to get authenticate principal name

- flow-client/src/main/frontend/vaadin-dev-tools.ts
Feature flags toggle "preview" and "deprecated" features, not necessarily just experimental features. Align the naming with documentation and other marketing material.
Remove introduction paragraph. That information is available from the "Learn more" link of each feature, and the text in the dev tools wasn't completely accurate anymore.
> chore: rename "Experimental Features" to "Feature Flags"

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java
The AuthenticationContext component is Serializable because the idea was to potentially inject it into Vaadin views, but this may cause several issues:
* a single instance of that class per application is expected, but if deserializating views we may end up with many of them
* logoutSuccessHandler and logoutHandler are transient, but they are not Spring beans, and we do not provide a simple way to inject them upon deserialization
* for the above reasons, AuthenticationContext may not work correctly with Kubernetes Kit
This change removes the implementation of Serializable interface and updates javadocs.
> fix: remove Serializable interface from AuthenticationContext

- flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
When UidlWriter collects changes to send to the client, it may happen that UI is still dirty because features may enqueue additional changes. As a side effect, if UI is still dirty after UIDL response is written, a useless PUSH action is performed.
This change performs changes collection until the UI is no more dirty.
Fixes #14887
> fix: collect changes until UI is not dirty (#15517) (CP: 23.3)

- flow-client/README.md
Adds a note to remove dev-bundle in the sub-folders after recompiling the flow-client.
> doc: Add a note about removing dev-bundle

- flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
When UidlWriter collects changes to send to the client, it may happen that UI is still dirty because features may enqueue additional changes. As a side effect, if UI is still dirty after UIDL response is written, a useless PUSH action is performed.
This change performs changes collection until the UI is no more dirty.
Fixes #14887
> fix: collect changes until UI is not dirty (#15517) (#15521) (CP: 2.8)

- flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
When UidlWriter collects changes to send to the client, it may happen that UI is still dirty because features may enqueue additional changes. As a side effect, if UI is still dirty after UIDL response is written, a useless PUSH action is performed.
This change performs changes collection until the UI is no more dirty.
Fixes #14887
> fix: collect changes until UI is not dirty (#15517) (#15521) (CP: 9.0)

- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Spring Security requires logout url to start with `/`, otherwise throws
with `defaultTarget must start with '/' or with 'http(s)'`.
Our default value is using servlet context path, which could be empty. This
change adds the `/` prefix for the serlvet context path when using it for
logout url.
> fix: ensure default logout url starts with '/'

- flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/AbstractDevModeTest.java
When you launch a Spring Boot Application class directly from the IDE, there is no PROJECT_BASEDIR info available
> fix: Use current folder when prepare-frontend has not run

- flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PageView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PageIT.java
Add API to fetch the document.dir from browser
and pass it to the provided callback.
Fixes #15597
> feat: add API to fetch page direction

- vaadin-dev-server/tsconfig.json
Experimental decorators are off by default for tsc
> fix: Add tsconfig to vaadin-dev-server to avoid IDE errors

- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerManagerImpl.java
Does not add a link tag for theme styles and does not watch the theme folder if no theme is used in the project.
> fix: Not start watching theme if no theme is used

- flow-server/src/main/java/com/vaadin/flow/server/frontend/GenerateMainImports.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
- flow-tests/test-express-build/test-dev-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NoAppBundleIT.java
Stats.json records some handled files as `Frontend/...` where as the requested file may be in the format `./...`
Use each `Frontend/` always as `./`
> fix: replace any 'Frontend/' with './'

- flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/FindComponentView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FindComponentIT.java
An appId only identifies a servlet and does not identify which UI instance connected to that servlet to use. A UI id uniquely identifies the UI and app id is not needed at all
> fix: Use uiId instead of appId to find an element

- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
If Theme annotation specifies a variant but not theme name or class, the production build applies the default Lumo theme but without the variant. This change makes the variant work even when theme name or class are not specified.
Fixes #15638
> fix: apply variant when using default theme

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateViteDevMode.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-tests/test-express-build/test-dev-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NoAppBundleIT.java
If running application using devBundle
do not generate frontend files like,
package.json, vite.*.ts etc.
Closes #15640
> fix: Don't generate frontend files with devBundle

- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
If Theme annotation specifies a variant but not theme name or class, the production build applies the default Lumo theme but without the variant. This change makes the variant work even when theme name or class are not specified.
Fixes #15638
> fix: apply variant when using default theme (#15641) (CP: 2.8)

- flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationConfiguration.java
Corrects a small spelling mistake in the message for an exception in `ApplicationConfiguration::get`.
> chore: Correct spelling mistake in `ApplicationConfiguration` exception message

- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
Close #15595
The check of whether the file has already been visited should be done after converting a directory to `directory/index.js` by `getImportedFrontendFile` (#15023). Otherwise, `directory` would never be found in `visitedPath`, and it will enter infinite recursion.
https://github.com/vaadin/flow/blob/444befa9c3ad393ed80174c5ccc3c13c5bfb8591/flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java#L631-L639
> fix: avoid infinite recursion on imported directories

- flow-server/src/main/java/com/vaadin/flow/server/frontend/GenerateMainImports.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
As we skip generated-flow-imports
we should also skip generated-flow-imports-fallback.
Fixes debBundle execution after a production mode build has been run.
> fix: do not take fallback js into account

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
Dev bundle should be used if possible
even after `clean-frontend` goal has been
executed.
Fixes #15707
> fix: DevBundle used after clean-frontend goal

- flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
- flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtPropertyElementBinderTest.java
DOM events related to property synchronization must not flush changes
to avoid wrong execution order of events on server side.
For example, an 'has-input-value-changed' event may occur before the
actual value of a field has been changed and a flush will trigger
listeners with an old value.
Fixes #15615
> fix: prevent flush changes when synchronizing properties

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Now has only one websocket connection to Vite instead of two
> chore: Upgrade to vite plugin checker 0.5.4

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
If you have multiple versions installed, e.g. community and ultimate, the protocol might open the wrong one
> fix: Remove special Idea case for Mac

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Now has only one websocket connection to Vite instead of two
> chore: Upgrade to vite plugin checker 0.5.4 (#15730) (CP: 23.3)

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketProxy.java
Prevents deadlocks in Quarkus environments.
Fixes #15744
> fix: forward messages asynchronously in Vite websocket proxy

- flow-html-components-testbench/pom.xml
Use the same dependency as flow-components
> fix: Do not bring junit4 into all TestBench projects

- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/AbstractGradleTest.kt
- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/TestUtils.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPlugin.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPrepareFrontendTask.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinUtils.kt
When a sourceset other than `main` is used for holding classes using Vaadin components, or for providing a resolution scope for Vaadin dependencies, the `prepareVaadinFrontend` task does not correctly extract the correct Node libraries required by those classes, and the `buildVaadinFrontend` task subsequently fails to complete due to Vite requiring those Node dependencies to have been extracted into the project so failing to find all of its front-end dependencies.
The `VaadinFlowPluginExtension` is being altered to include a `sourceSetName` field, that defaults to `main` for backwards compatibility but allows users to specify a custom sourceset to use for the prepare and build tasks. As the use of a custom sourceset generally implies that different Gradle tasks will be executed for …
> fix: Allow Gradle builds to use custom sourcesets (#15739) (CP: 9.0)

- flow-html-components/src/main/java/com/vaadin/flow/component/html/Image.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/ImageTest.java
> fix: Always set image alt text the same way

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
This option, added in #15334, should no longer be necessary as Vite 4 is now stable.
> chore: remove the --legacy-peer-deps option

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFiles.java
When comparing file names, the
used file separator should be the
same on all OS:es
> fix: file separator used should be the same

- flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
- pom.xml
in selenium 4.8.0. `Chrome DevTools support is now: v107, v108, and v109` 
[selenium 4.8.0 release blog](https://www.selenium.dev/blog/2023/selenium-4-8-0-released/)
> chore: update TB to 9.0.0.alpha7

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/stateless/VaadinStatelessSecurityConfigurer.java
The shared objects need to be available when other configurers are run and because of https://github.com/spring-projects/spring-security/issues/12579 a workaround is needed to actually apply the correct SecurityContextRepository
Fixes https://github.com/vaadin/hilla/issues/681
> fix: Use correct SecurityContextRepository for stateless authentication

- flow-server/src/main/java/com/vaadin/flow/component/Component.java
All components are capable of having class names yet you must remember to implement `HasStyle` every time you create a new component or the class API is missing. The only known exception is a text node which cannot have classes. It is fine if this edge case, which is almost never used, throws an exception from the API
> feat: Allow every component to have styles

- flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/AtmospherePushConnectionTest.java
Disconnecting an AtmospherePushConnection while it is sending a message may result in a NullPointerException if AtmosphereResource is nullified before the message is sent.
This change synchronizes operations, so that disconnect will wait until current push finishes, or push waits for disconnect to complete so that the isConnected() method reflects correctly current state.
Fixes #15571
> fix: prevent concurrent disconnect and push operations

- flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/AtmospherePushConnectionTest.java
Disconnecting an AtmospherePushConnection while it is sending a message may result in a NullPointerException if AtmosphereResource is nullified before the message is sent.
This change synchronizes operations, so that disconnect will wait until current push finishes, or push waits for disconnect to complete so that the isConnected() method reflects correctly current state.
Fixes #15571
> fix: prevent concurrent disconnect and push operations (#15767) (CP: 2.8)

- flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
Set pwa character set to utf-8
instead of the default iso encoding
Fixes #15834
> fix: pwa charset

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
- flow-server/src/main/resources/vite.generated.ts
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
package dependencies have
new name and vite handled
dependencies go to npmModules
Closes #15871
> fix: rename stats dependencies

- flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/LongPollingCacheFilter.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/LongPollingCacheFilterTest.java
Atmosphere caches messages when the client is disconnected, but unfortunately, it may happen that a message does not reach the client because of network disconnection during async response write operation. In this case, the message is not cached and will be completely lost, causing a UI resynchronization request. This change preserves messages in broadcaster cache until the client confirms that they have been processed, by sending the last seen server sync identifier on reconnection. This should prevent the need for a UI resynchronization. It may happen in some cases, e.g. back to online after being offline, that messages already seen will be sent to the client, but Flow will discard them.
Part of #15281
Fixes #15205
Co-authored-by: Teppo Kurki <teppo.kurki@vaadin.com>
> fix: preserve push messages in cache until they are seen by client (#15764) (CP: 9.0)

- flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
- flow-server/src/main/resources/plugins/application-theme-plugin/package.json
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
Since https://github.com/vaadin/flow/pull/15535 the `application-theme-plugin` package should be marked to include ES modules
Bugfix
> fix: make application-theme-plugin type module

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
- flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
- flow-tests/test-express-build/test-embedding-express-build/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
- flow-tests/test-express-build/test-theme-dev-bundle/src/test/java/com/vaadin/flow/devbuild/DevBundleThemeIT.java
Theme files in Express Build mode should be served with a pattern /VAADIN/themes/ like for the hot deploy mode with Vite.
Fixes https://github.com/vaadin/flow/issues/15915
> fix: Add reserved /VAADIN segment to the theme pattern

- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
When closing inactive VaadinSession the framework prints a log message stating that it is 'Closing inactive session  <SID>', but this message can be misunderstood, as it seems that the HTTP session will be closed. This change updates the log message to make it explicit that the framework is closing the Vaadin session.
Related to #15476
> chore: clarify inactive session closing log messages

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
Ignores the dependencies provided by older Vaadin versions and not present anymore in a target Vaadin version. Examples: polymer iron-list or deprecated Vaadin web components with "vaadin-" prefix.
Fixes https://github.com/vaadin/flow/issues/15910
> fix: Ignore old Vaadin provided dependencies for bundle resolution

- vaadin-dev-server/README.md
- vaadin-dev-server/package.json
- vaadin-dev-server/patch-application.js
- vaadin-dev-server/web-dev-server.config.mjs
Adds a frontend dev setup to the `vaadin-dev-tools` module in order to be able to work iteratively on the dev tools UI.
The setup includes a dev server that hosts the Typescript files for the dev tool UI, and provides hot module replacement functionality so that changes to the dev tool don't require a page reload. In order to use the local dev tool files in a Flow app, the setup includes a script that patches a Flow app to load the dev tool from the dev server instead of from the classpath.
Due to how the dev tool Lit component is constructed, changes to tab contents currently don't work correctly, but changes to the outer HTML or CSS should be visible. If this is merged I'll open a separate PR to refactor the component to make this work as well.
> chore: add frontend dev setup to vaadin-dev-tools

- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Refactor dev tool tabs so that they can be updated during hot module replacement (HMR). The problem was that tabs stored references to methods. Since HMR patches methods on Lit elements, these references get stale, and the new/patched methods can only be picked up when referenced through `this`.
- Refactoring
> refactor: make dev tool tabs content updatable

- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Some of the CSS template literals don't contain valid CSS, which at least IntelliJ complains about:
Apart from that the construct of putting HSL color values in a template literal is kind of weird. Let's put them into the CSS right away, and use CSS custom properties to reference them instead.
- Refactoring
> refactor: replace invalid CSS template literals in dev tool

- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/component-picker.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Refactor the dev tools component picker to decouple it from the code tab and make it reusable by the theme editor. There is still one global picker, however the picker now has a method for opening the it, where you need to provide options, such as which callback to call when a component is picked, and which template to display in the info panel. For the theme editor the idea is to pass it a reference or provider for the component picker, so that the editor can access / open the picker on demand.
- Refactoring
> refactor: make dev tools component picker reusable

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorAsyncTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
DataCommunicator internally uses a Stream.Builder to collect paginated data. but it fails it the DataProvider returns a parallel stream. This change consumes parallel streams before adding items to the builder.
Fixes #15881
> fix: consume parallel streams when fetching paginated data

- vaadin-dev-server/pom.xml
Excludes frontend test files from the vaadin-dev-tools JAR file.
> chore: exclude frontend tests from dev tools package

- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Show a notice in the theme editor in case a theme has not been set up yet. The notice includes a link to the documentation that explains how to set up a theme.
> refactor: show notice for missing theme in theme editor

- flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
During theme processing, a file detected as existing may be delete before it gets copied, causing a ENOENT (No such file or directory) error. After such failure, dev server live reload stops working. This change catches errors in file copy operations, ignoring ENOENT and propagating other failures.
Fixes #13885
> fix: ignore missing files in theme processing (#15896) (CP: 2.8)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
Frontend resources checking ignores ?inline suffixes in the stylesheet path when comparing file names.
> fix: Ignore ?inline suffix for imported stylesheets

- vaadin-dev-server/package.json
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/detector.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/detector.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/events.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/components/vaadin-button.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/components/vaadin-text-field.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/model.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/property-editor.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/property-list.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/style-detector.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
- vaadin-dev-server/web-test-runner.config.mjs
Added:
- base theme detection for the selected component and use it for filling property editors
- allow editing of properties and store them in an edited theme
- live preview of the edited theme
- save or discard the edited theme, where saving sends the pending changes to the dev server
For now the theme preview will always have higher priority over other stylesheets. When saving, it is expected that the page reloads, and there is no logic yet to either prevent the reload, or restore UI state after a reload.
> refactor: basic editing of properties in theme editor

- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.ts
Adds a `Theme` data structure and state for keeping all previously saved component theme modifictions in the theme editor. The theme instance contains all modifications to all components since the last reload. This allows to keep the modifications in the theme preview when picking a different component, and also to restore the modified values in the property editors when picking the same component again.
> refactor: keep modified component themes in theme editor

- vaadin-dev-server/pom.xml
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/detector.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/detector.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/events.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/components/vaadin-button.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/components/vaadin-text-field.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/model.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/property-editor.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/property-list.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/tests/utils.ts
- Extends component metadata to include host properties
- Show editors for host properties in theme editor
- Update button metadata to use host properties, as proposed by Jouni
- Update tests to use a test element / metadata in order to reduce changes when iterating on Vaadin component metadata in the future
> refactor: editable host properties in theme editor

- flow-server/src/main/java/com/vaadin/flow/component/HasAriaLabel.java
- flow-server/src/main/java/com/vaadin/flow/dom/ElementConstants.java
- flow-server/src/test/java/com/vaadin/flow/component/HasAriaLabelTest.java
Add API to set `aria-labelledby` attribute to the `HasAriaLabel` interface.
Part of https://github.com/vaadin/platform/issues/3803
> feat: add aria-labelledby API to HasAriaLabel

- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Changes the theme editor to push individual property changes immediately to the dev server to store them in the theme editor CSS file.
Does not yet include undo history, or parsing the initial theme editor stylesheet.
> refactor: save theme editor changes immediately

- flow-server/src/main/java/com/vaadin/flow/component/HasAriaLabel.java
This is a follow-up of https://github.com/vaadin/flow/pull/16081, where a bug on `HasAriaLabel#setAriaLabel` was found. It turns out that the current implementation uses `getElement().setProperty()` to set the aria-label to the component, but since the value of `ElementConstants.ARIA_LABEL_PROPERTY_NAME` is in the Kebab Case format (`aria-label`) instead of the Camel Case one (`ariaLabel`), it doesn't correctly set the property.
> fix: use setAttribute in setAriaLabel method

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
Parent theme key in theme.json is skipped when theme.json content is analysed, because having a parent theme shouldn't trigger a re-bundle per se.
Follow-up for https://github.com/vaadin/flow/issues/16004
> fix: Parent theme should not trigger a re-bundle

- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
Should make it easier to see if errors is caused by a partially downloaded file
> chore: Log downloaded node archive size

- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/api.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/api.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Add an API client to the theme editor that wraps the websocket connection, can send messages and correlate responses to the original request. Each request returns a `Promise` that resolves when a successful response is received, and rejects when an error response is received.
Only covers sending rule updates, we can cover component metadata when adding a related feature.
> refactor: implement theme editor API client

- flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
context.getSessionHandler().getSession is no more in Jetty 12
> test: Avoid using Jetty API that is going away

- pom.xml
Upgrades Spring Security to 5.7.7 and byte buddy to 1.12.23.
Also upgrades Jackson to 2.14.2 which is newer than what Spring Boot uses
> chore: Upgrade to Spring Boot 2.7.9

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
@vaadin/flow-frontend package was used in previous Vaadin versions to alias .target/flow-frontend folder. Since it is present only under "dependencies" object, Flow cannot decide was it added by user or not. Now Flow ignores this legacy package to not re-bundle erroneously.
> fix: Skip checking @vaadin/flow-frontend package (CP: 24.0)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/GenerateMainImports.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/CssAnnotationVisitor.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/CssData.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
- flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/java/com/vaadin/flow/frontend/DevBundleCssImportView.java
- flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/java/com/vaadin/flow/frontend/MyComponent.java
- flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/resources/META-INF/resources/frontend/addons-styles/add-on-styles.css
- flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/frontend/DevBundleCssImportIT.java
When the stylesheet is imported by `AtCssImport` from `src/main/resources/META-INF/resources/frontend`, the Flow copies the stylesheets to `frontend/generated/jar-resources` in Vite dev server mode, and only then checks that the needed files are present.
For the dev bundle mode, these kind of files are checked even before any of the tasks run (when Flow check if re-bundling is needed), so before these files are copied. 
The fix is to make `GenerateMainImports` ignore missing files, because this class only runs for checking dev bundle and the absence of files is expected.
Related-to https://github.com/vaadin/flow/issues/16109
> fix: Not throw for not yet copied CSS when checking for re-bundling (CP: 24.0)

- .github/workflows/validation.yml
Should make it easier to see what goes wrong in the builds that cause them to take longer
> test: Increase build timeout to 30min

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandler.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeModifier.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/LoadPreviewRequest.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/LoadPreviewResponse.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/LoadRulesRequest.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/LoadRulesResponse.java
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/api.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/tests/utils.ts
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandlerTest.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeModifierTest.java
Adds an API for loading existing rules for a component. After picking a component in the editor, loads all rules for the picked component, so that property edtiors initialize with the previously modified value. For the future this API could also be used to load rules for different component scopes (global or instances with a specific CSS class name).
Also adds an API for loading the current content of the theme editor CSS file in order to update the theme preview. This allows to remove the double-bookkeeping of modifications since the last reload on the client. Whenever a property is modified we just save the change on the server, and then retrieve the current CSS again. This creates more traffic than the previous approach, but it is how the Flow live reload is going to work as well when …
> refactor: initialize component theme in theme editor

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/ConvertPolymerCommand.java
Use `Files.walkFileTree` instead of `Files.walk` in the Polymer to Lit converter to prevent it from visiting the `node_modules` folder.
> refactor: skip the node_modules folder completely

- flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
context.getSessionHandler().getSession is no more in Jetty 12
> test: Avoid using Jetty API that is going away (#16129) (CP: 23.3)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/GenerateMainImports.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/CssAnnotationVisitor.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/CssData.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
- flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/java/com/vaadin/flow/frontend/DevBundleCssImportView.java
- flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/java/com/vaadin/flow/frontend/MyComponent.java
- flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/resources/META-INF/resources/frontend/addons-styles/add-on-styles.css
- flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/frontend/DevBundleCssImportIT.java
When the stylesheet is imported by `AtCssImport` from `src/main/resources/META-INF/resources/frontend`, the Flow copies the stylesheets to `frontend/generated/jar-resources` in Vite dev server mode, and only then checks that the needed files are present.
For the dev bundle mode, these kind of files are checked even before any of the tasks run (when Flow check if re-bundling is needed), so before these files are copied. 
The fix is to make `GenerateMainImports` ignore missing files, because this class only runs for checking dev bundle and the absence of files is expected.
Related-to https://github.com/vaadin/flow/issues/16109
> fix: Not throw for not yet copied CSS when checking for re-bundling

- .github/workflows/validation.yml
This avoids long queues in the project when pushing multiple changes to the same PR
> chore: cancel previous builds if there are new changes in the branch

- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.ts
Make theme preview initialize its stylesheet lazily to avoid errors in Safari and guarantee that it is added after stylesheets loaded by the application.
> refactor: initialize theme preview lazily

- vaadin-dev-server/package.json
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/base-property-editor.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/color-picker.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/color-picker.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/color-property-editor.test.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/color-property-editor.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/range-property-editor.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/components/presets.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/components/vaadin-button.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/model.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/property-list.ts
- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vendor/@vaadin/overlay/src/vaadin-overlay-position-mixin.js
Adds a custom editor for CSS properties that represent colors. The component is structured into two parts:
- A more general color picker component, which is mostly a wrapper for putting a vanilla-colorful picker into an overlay. 
- The actual color property editor that uses the same layout as the other property editors and contains a color-picker as well as an input for displaying and entering color values.
> refactor: implement color property editor in theme editor

- vaadin-dev-server/frontend/component-picker.ts
- vaadin-dev-server/frontend/connection.ts
- vaadin-dev-server/frontend/styles.ts
- vaadin-dev-server/frontend/theme-editor/api.ts
- vaadin-dev-server/frontend/theme-editor/editor.ts
- vaadin-dev-server/frontend/vaadin-dev-tools.ts
There are currently circular dependencies between TS modules in the dev tools:
- `vaadin-dev-tools.ts` -> `await import('./component-picker.js');`
- `component-picker.ts` -> `import { popupStyles } from './vaadin-dev-tools.js';`
- `vaadin-dev-tools.ts` -> `import './theme-editor/editor';`
- `editor.ts` -> `import { Connection } from '../vaadin-dev-tools.ts';`
- `editor.ts` -> `await import('./component-picker.js');`
- `component-picker.ts` -> `import { popupStyles } from './vaadin-dev-tools.js';`
In general these should be avoided, as they can work, but also can result in random errors which are hard to debug. I just ran into one where the lazy import of the component picker from the dev tools module loaded the dev tools module again (with several other side effects), due to some …
> refactor: remove circular dependencies in dev tools

- flow-server/src/main/java/com/vaadin/flow/component/UI.java
- flow-server/src/test/java/com/vaadin/flow/component/UITest.java
A variant that support both RouteParameters and QueryParameters that was missing for some reason. Requested by community members in Discord.
> Added a missing navigate method

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
The PR cherry-picks the feature flag removal to `24.0`:
- https://github.com/vaadin/flow/pull/16248
> chore: remove the enforceFieldValidation feature flag (#16248) (CP: 24.0)

- flow-data/pom.xml
- flow-html-components/pom.xml
- flow-lit-template/pom.xml
- flow-polymer-template/pom.xml
- flow-server/pom.xml
- flow-tests/test-frontend/vite-embedded-webcomponent-resync/pom.xml
- pom.xml
- vaadin-dev-server/pom.xml
Jakarta EE APIs should be in provided scope.
Related to https://github.com/vaadin/platform/issues/3898
> fix: Use correct scope for ee api's

- vaadin-dev-server/frontend/theme-editor/editor.test.ts
- vaadin-dev-server/frontend/theme-editor/editor.ts
After merging the scope changing, the base theme detection used for showing default values in the property editor does not work correctly anymore. For example in the following case:
- Change background color globally
- Switch to local scope
- Property editor shows initial background color, because the base theme has not been updated with the modified global background color
A similar problem exists with undo/redo, which can also affect properties outside of the current scope.
This fix updates the base theme whenever the scope is changed, or undo / redo is performed.
> refactor: fix base theme detection in theme editor

- vaadin-dev-server/frontend/component-picker.ts
- vaadin-dev-server/frontend/theme-editor/editor.test.ts
- vaadin-dev-server/frontend/theme-editor/editor.ts
Adds an outline to the selected component in the theme editor. The outline gets removed when the component picker is opened again, or when the editor is removed from the DOM.
> refactor: highlight selected component in theme editor

- flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
There were some problems in testbench, and to prevent any further problems in any other service, I am just making this part more general, to accept every Key implementation not just HashableKey (although right now it is only called in real-life app with HashableKeys).
> chore: optimize getModifierKey method, to handle more implementations of Key interface:

- vaadin-dev-server/frontend/theme-editor/components/editors/range-property-editor.ts
Remove fixed width from range slider and make it use the remaining space instead. Also restores the initial custom value input width.
> refactor: fix range editor sizing issues

- vaadin-dev-server/frontend/component-picker.ts
Follow up from: https://github.com/vaadin/flow/pull/16270
Make the component picker use an overlay when hovering over elements, which makes it more obvious that something is happening, and also avoids the outline being cut off if the element is at the bounds of the client area.
https://user-images.githubusercontent.com/357820/225763596-3b9e2f4c-ea37-425a-8d1f-c38182877c21.mp4
> refactor: use overlay for component picker hover styles

- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloader.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
Makes it easier to understand that download of Node failed instead of that the archive was corrupt
> chore: Throw an exception when a download fails

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Resolves the correct project folder when running a Vaadin project inside a multi module project
Fixes #16265
> fix: Try determining the project folder from the classpath (#16266) (CP: 23.3)

- vaadin-dev-server/pom.xml
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/editor/Editor.java
Align `javaparser` version with the one transitively used by Spreadsheet.
> fix: align javaparser version with the one used by Spreadsheet

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
This should no longer be needed
> chore: Remove dev mode detector version force

- vaadin-dev-server/frontend/theme-editor/editor.test.ts
- vaadin-dev-server/frontend/theme-editor/editor.ts
- vaadin-dev-server/frontend/vaadin-dev-tools.ts
Removes / restores the selected element highlight when closing / opening the dev tools.
Addresses feedback from DX tests that highlight is still visible after closing dev tools.
https://user-images.githubusercontent.com/357820/226929991-68a54d70-f252-4872-8bea-c2782448963f.mp4
> refactor: hide selection highlight when closing theme editor

- flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Added more covering tests to ComponentTest.java for covering the getLocale() method. 
It was needed because another external contributor PR is tackling a refactor/optimization of this method (as well), and this change, it will ensure the functionality, and execution branches are the same:
Fixes # (issue):
- https://github.com/vaadin/flow/pull/16160
> chore: added more covering tests to ComponentTest.java for covering getLocale() method

- flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
- flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
- flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Allow accessing the error page in security tests so that the 404 is sent to the browser
Fixes #16371
> fix: Allow access to /favicon even when the vaadin mapping is /something

- vaadin-dev-server/frontend/theme-editor/api.test.ts
- vaadin-dev-server/frontend/theme-editor/api.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/base-property-editor.test.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/base-property-editor.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/color-property-editor.test.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/range-property-editor.test.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/text-property-editor.test.ts
- vaadin-dev-server/frontend/theme-editor/components/property-list.ts
- vaadin-dev-server/frontend/theme-editor/detector.test.ts
- vaadin-dev-server/frontend/theme-editor/detector.ts
- vaadin-dev-server/frontend/theme-editor/editor.test.ts
- vaadin-dev-server/frontend/theme-editor/editor.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-avatar.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-button.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-checkbox.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-number-field.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-progress-bar.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-text-area.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-text-field.ts
- vaadin-dev-server/frontend/theme-editor/metadata/model.ts
- vaadin-dev-server/frontend/theme-editor/metadata/registry.test.ts
- vaadin-dev-server/frontend/theme-editor/model.test.ts
- vaadin-dev-server/frontend/theme-editor/model.ts
- vaadin-dev-server/frontend/theme-editor/tests/utils.ts
- Updates component metadata model to contain a list of elements, each element having a selector and a list of properties. The host itself is now also just an element.
- Update API calls to pass/receive selectors when loading / setting rules
- Update theme model to work with selectors, add logic for generating local and global scoped selectors
- Update theme detector to work with selectors
- Set local class name before sending rules
> refactor: use selectors in theme editor component metadata

- vaadin-dev-server/frontend/theme-editor/components/editors/base-property-editor.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/checkbox-property-editor.test.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/checkbox-property-editor.ts
- vaadin-dev-server/frontend/theme-editor/components/property-list.ts
- vaadin-dev-server/frontend/theme-editor/detector.test.ts
- vaadin-dev-server/frontend/theme-editor/detector.ts
- vaadin-dev-server/frontend/theme-editor/editor.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/presets.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-menu-bar.ts
- vaadin-dev-server/frontend/theme-editor/metadata/model.ts
- vaadin-dev-server/frontend/theme-editor/model.test.ts
- vaadin-dev-server/frontend/theme-editor/model.ts
- vaadin-dev-server/frontend/theme-editor/tests/utils.ts
Adds metadata for the MenuBar component. 
Also:
- Improves theme detection to work with more complex components. To detect styles for components that have children or overlays we need an instance that has all of these set up. Relying on the selected element seems brittle, as that might not have all of the elements we want to measure, and its custom styles would lead to incorrect results for detecting styles for the global scope. It gets even more difficult for data-driven components like ComboBox. Having a generic setup for all types of components seems impossible, so for now, for each complex component the metadata defines functions on how to properly set up or clean up an instance from which styles can be detected.
- Adds a property editor with a checkbox to allow toggling bold / italic …
> refactor: add menubar metadata to theme editor

- vaadin-dev-server/frontend/theme-editor/detector.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-select.ts
Adds metadata for the Select component. Also updates the theme detector to be able to detect pseudo element styles.
We could think about reusing some of the property definitions somehow, but let's maybe add some more components first to see what patterns come up.
> refactor: add select metadata to theme editor

- vaadin-dev-server/frontend/theme-editor/metadata/components/defaults.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/generic.ts
- vaadin-dev-server/frontend/theme-editor/metadata/registry.test.ts
- vaadin-dev-server/frontend/theme-editor/metadata/registry.ts
Allows styling non-Vaadin components, such as `H1`, `Div`, `Span`, etc., using a generic set of metadata. The generic metadata is used whenever a component's tag name does not start with `vaadin-`. For Vaadin components we should attempt to cover them with specific metadata, so the generic metadata is not used as fallback for Vaadin components that don't have their own metadata yet.
~~Based on the changes from https://github.com/vaadin/flow/pull/16413 and is currently set to merge against it.~~
> refactor: allow theming non-Vaadin components

- vaadin-dev-server/frontend/vaadin-dev-tools.ts
The theme editor only works with Flow apps and should not be visible in a Hilla app.
> refactor: show theme editor only in Flow apps

- vaadin-dev-server/frontend/vaadin-dev-tools.ts
- vaadin-dev-server/vite.config.js
The theme editor injects global styles using constructable stylesheets right when its JS modules are loaded. While we use a polyfill for constructable stylesheets for Safari, the current loading order does not guarantee that the polyfill is loaded before the theme editor modules. Adding an explicit import to the polyfill in the dev tools should fix that.
> refactor: import constructable stylesheets polyfill from dev tools

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
- vaadin-dev-server/frontend/vaadin-dev-tools.ts
Theme editor is going to be a commercial feature. While it is going to stay behind a feature flag for now and will be freely accessible, it has been decided that it should already indicate that it is not going to be accessible without a subscription in a future stable release. Added a "Free Preview" to the feature flag name, and the dev tools tab title.
> refactor: indicate that theme editor is going to be a commercial feature on stable release

- vaadin-dev-server/frontend/theme-editor/components/class-name-editor.test.ts
- vaadin-dev-server/frontend/theme-editor/components/class-name-editor.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/base-property-editor.test.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/base-property-editor.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/checkbox-property-editor.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/color-property-editor.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/range-property-editor.ts
- vaadin-dev-server/frontend/theme-editor/editor.test.ts
- vaadin-dev-server/frontend/theme-editor/editor.ts
- vaadin-dev-server/frontend/theme-editor/history.test.ts
- vaadin-dev-server/frontend/theme-editor/history.ts
- vaadin-dev-server/frontend/theme-editor/preview.test.ts
- vaadin-dev-server/frontend/theme-editor/preview.ts
- vaadin-dev-server/frontend/theme-editor/styles.ts
Allows editing a component's local class name in the theme editor:
- If component does not have a class name yet, the custom class name is only applied when actually changing a property
- If a component already has a class name, it is changed immediately
- Only valid class names are accepted, otherwise an error message is shown
- Enhanced undo / redo to update the local class name for elements that are not selected anymore
- Extracted styles from property editor rows to be reused for class name editor row
> refactor: allow editing local class name in theme editor

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeEditorCommand.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandler.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeModifier.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/OpenCssHandler.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/OpenCssRequest.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandlerTest.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeModifierTest.java
Adds support for opening theme-editor.css on line where rule with given selector is defined. If there is no such rule creates new empty rule and opens line where it has been defined.
disclaimer: not to add & clear empty rules each time files is opened and saved,  empty rules are preserved. To be discussed later.
`{ uid: int, requestId: string, selector: string }`
> refactor: add support for themeEditorOpenCss command

- flow-tests/test-ccdm-flow-navigation/pom-production.xml
- flow-tests/test-ccdm/pom-production.xml
- flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/pom-generatedTsDir.xml
- flow-tests/test-frontend/test-npm/pom-production.xml
- flow-tests/test-frontend/test-pnpm/pom-production.xml
- flow-tests/test-frontend/vite-context-path/pom-production.xml
- flow-tests/test-frontend/vite-embedded/pom-production.xml
- flow-tests/test-frontend/vite-pwa-custom-offline-path/pom-production.xml
- flow-tests/test-frontend/vite-pwa-disabled-offline/pom-production.xml
- flow-tests/test-npm-only-features/test-npm-bytecode-scanning/pom-devmode.xml
- flow-tests/test-npm-only-features/test-npm-bytecode-scanning/pom-prod-fallback.xml
- flow-tests/test-npm-only-features/test-npm-bytecode-scanning/pom-production.xml
- flow-tests/test-pwa-disabled-offline/pom-production.xml
- flow-tests/test-pwa/pom-production.xml
- flow-tests/test-themes/pom-devbundle.xml
- flow-tests/test-themes/pom-production.xml
Configured maven to add a suffix for test reports in modules that have multiple pom files, to prevent results to be overwritten during test-results validation job.
> test: added suffix for test reports

- vaadin-dev-server/frontend/theme-editor/components/class-name-editor.test.ts
- vaadin-dev-server/frontend/theme-editor/components/class-name-editor.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/base-property-editor.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/color-property-editor.test.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/color-property-editor.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/range-property-editor.test.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/range-property-editor.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/text-property-editor.test.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/text-property-editor.ts
- vaadin-dev-server/frontend/theme-editor/editor.test.ts
- vaadin-dev-server/frontend/theme-editor/icons.ts
- vaadin-dev-server/frontend/theme-editor/model.test.ts
- vaadin-dev-server/frontend/theme-editor/model.ts
- vaadin-dev-server/frontend/theme-editor/styles.ts
Adds a button to property editors that allows clearing customized property values. The button will only be shown if the property has been previously customized by the theme editor.
Note that until HMR for CSS is implemented, the component will still be styled with the modified value if it was present in the CSS file when the page was loaded.
> refactor: add clear property button

- flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
CP from https://github.com/vaadin/flow/pull/16367 to 23.3 branch.
Added more covering tests to ComponentTest.java for covering the getLocale() method.
It was needed because another external contributor PR is tackling a refactor/optimization of this method (as well), and this change, it will ensure the functionality, and execution branches are the same:
Fixes # (issue):
https://github.com/vaadin/flow/pull/16160
>  chore: added more covering tests to ComponentTest.java for covering getLocale() method (#16367) (CP: 23.3)

- vaadin-dev-server/pom.xml
Reverts vaadin/flow#16485
we need to match what poi uses
> Revert "chore(deps): bump javaparser-core from 3.24.10 to 3.25.2"

- flow-server/src/main/resources/vite.generated.ts
> fix: Make material styles work in hotdeploy dev mode

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/stateless/VaadinStatelessSecurityConfigurer.java
The stateless configuration is copied from https://docs.spring.io/spring-security/reference/5.8/migration/servlet/exploits.html#_i_am_using_angularjs_or_another_javascript_framework
Fixes #14923
> fix: Use default XOR CSRF token mechanism in Spring

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Fixes the sometimes constant output stream of 
```
[TypeScript] Found 0 errors. Watching for file changes.
```
The relevant fix in TypeScript is https://github.com/microsoft/TypeScript/pull/51626
> fix: Do not trigger extra TS checks

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Using PIPE instead of INHERIT prevents corrupted stream errors with maven
surefire and failsafe plugins.
> chore: use stream PIPE redirect for npm process executions

- flow-client/src/main/frontend/Flow.ts
- flow-client/src/test/frontend/FlowTests.ts
- flow-server/src/main/java/com/vaadin/flow/component/UI.java
- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
- flow-tests/test-eager-bootstrap/src/main/java/com/vaadin/flow/eagerbootstrap/ParameterView.java
- flow-tests/test-eager-bootstrap/src/test/java/com/vaadin/flow/eagerbootstrap/ParameterIT.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/scopes/AbstractUIScopedTest.java
Changes bootstrap for eager mode so that the index page contains the <flow-container-[appId]> div and the virtual child for this element is created eagerly on the server. This allows the initial render on the client side to put the content inside the flow-container instead of document body as happened before.
By using a convention on how the container div is created and id is set, we no longer need to communicate the element tag and id from the client.
Fixes #16046
Fixes #16496
> fix: Initialize the route only once when using eager server load

- vaadin-dev-server/frontend/theme-editor/detector.test.ts
- vaadin-dev-server/frontend/theme-editor/detector.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-checkbox-group.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-checkbox.ts
- vaadin-dev-server/frontend/theme-editor/metadata/model.ts
- vaadin-dev-server/frontend/theme-editor/tests/utils.ts
Adds metadata for Checkbox and CheckboxGroup to the theme editor. Also added a basic solution for styling component states to the metadata model and theme detector (checked state in this case).
Compared to Daniel's suggestions:
- Checkbox
- Left out `gap`, as that would need to be applied on an element that is not accessible with global CSS.
- Added properties for checkbox size, checkmark color, label font style
- For styling the label explicitly target the `label` child element
- Group
- Left out `gap` and `direction`, which can require setting `display: flex` first. Instead of exposing `display` and `flex-direction` properties, which are likely to confuse users unfamiliar with CSS, long term the editor should provide some convenient UI that does this under the hood somehow.
> refactor: add metadata for Checkbox, CheckboxGroup

- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-radio-group.ts
Adds metadata for RadioButtonGroup. Mostly just adapted from the metadata for Checkbox and CheckboxGroup.
This PR is based on the changes from https://github.com/vaadin/flow/pull/16462 and is currently set to merge against it.
> refactor: add RadioButtonGroup metadata

- vaadin-dev-server/frontend/theme-editor/editor.test.ts
- vaadin-dev-server/frontend/theme-editor/editor.ts
- vaadin-dev-server/frontend/theme-editor/model.ts
Shows a notice if a component is not supported by the theme editor. This should currently only affect Vaadin components that do not have metadata.
> refactor: show notice if styling component is not supported

- vaadin-dev-server/package.json
- vaadin-dev-server/pom.xml
Run dev tools frontend tests in Maven `verify` phase. The setup is adopted from the `flow-client` module.
> chore: run dev tools frontend tests with maven

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifier.java
While picking component that has inaccessible source files (like `<body>`) nasty exception has been thrown. Generic component inaccessible message is now presented to the user.
> refactor: fix for picking elements that have inaccessible source file

- vaadin-dev-server/frontend/theme-editor/components/editors/range-property-editor.ts
Hide prefix/suffix icons in range editor, as we currently don't have proper icons for each type of property. The icon rendering code is only commented out, so that it can be restored after proper icons have been configured.
> refactor: hide icons in range editor

- vaadin-dev-server/frontend/component-util.ts
- vaadin-dev-server/frontend/theme-editor/components/editors/color-picker.ts
- vaadin-dev-server/frontend/theme-editor/components/scope-selector.ts
- vaadin-dev-server/frontend/vaadin-dev-tools.ts
Prevents application overlays from closing when clicking within the dev tools. Also makes sure that overlays that have been opened from within the dev tools, such as the color picker in the theme editor, can still be closed.
Fixes https://github.com/vaadin/flow-components/issues/4901
- Bugfix
> fix: prevent dev tools interactions from closing application overlays

- vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Cherry-pick of https://github.com/vaadin/flow/pull/16545
Removed the special handling of overlays in the dev tools, as there are none in v24.0. There are also no type defs for overlays classes.
> fix: prevent dev tools interactions from closing application overlays (CP: 24.0)

- flow-server/src/main/resources/plugins/stats-plugin/stats-plugin.js
The StatsPlugin uses an hard-coded forwars slash charachter to split the file identifier in path segments.
This produces wrong results when running on Windows, as the identifier contains back slashes.
This change uses node 'path.sep' as split chars
Fixes #16234
> fix: use OS path separator in stats plugin

- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/EntryPointData.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerCssTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerThemeTest.java
Google finds a definition like "An endpoint is a remote computing device that communicates back and forth with a network to which it is connected." which is not what a @Route annotated class is, and even less what a service init listener is..
Endpoint is already used in Hilla for something close to what the definition describes
> refactor: Rename endpoint to entry point when scanning classes

- flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/AtmospherePushConnectionTest.java
If the AtmospherePushConnection.disconnect method is invoked concurrently by multiple threads, a deadlock may happen if the servlet container somehow locks HTTP session, as closing AtmosphereResource may cause accesses to the HTTP session.
For example, is a thread (A) is invalidating the HTTP session, thus closing Vaadin UIs and disconnecting push, and another thread (B) is also requesting a push disconnect, then B will be blocked when closing the atmosphere resource by the lock on the session held by A, but A is actually waiting to acquire the lock on AtmospherePushConnection held by B, causing the deadlock.
This change allows a single thread to perform the disconnect operation, to avoid potential deadlocks.
Fixes #16293
> fix: prevent deadlock on concurrent push disconnection (#16544) (CP: 2.9)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/EntryPointData.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerThemeTest.java
When splitting code into multiple chunks, there is no way to guarantee that some modules are globally loaded before others
> chore!: Remove the themeModule concept

- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassInfo.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/EntryPointData.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerTestComponents.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerThemeTest.java
This changes the class visitor so that we
1. Find all entry points
2. Scan through all classes reachable from any of the entry points and store metadata for that class
3. Collect the metadata for all classes reachable for each individual entry point
It should allow us to generate an import file separately for each entry point and then lazy load scripts and css for some of the entry points
> refactor: Collect reachable class info per entry point

- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
- vaadin-dev-server/frontend/theme-editor/api.ts
- vaadin-dev-server/frontend/theme-editor/editor.test.ts
- vaadin-dev-server/frontend/theme-editor/editor.ts
- vaadin-dev-server/frontend/theme-editor/model.test.ts
- vaadin-dev-server/frontend/theme-editor/model.ts
- vaadin-dev-server/frontend/theme-editor/preview.test.ts
- vaadin-dev-server/frontend/theme-editor/preview.ts
- vaadin-dev-server/frontend/vaadin-dev-tools.test.ts
- vaadin-dev-server/frontend/vaadin-dev-tools.ts
Integrates HMR into theme editor:
- Remove loading of the full theme editor CSS into preview stylesheet
- Instead do an optimistic update by adding CSS rules for single property updates to preview stylesheet
- Change CSS HMR to dispatch a DOM event after
- Vite has updated style modules (Vite hot deploy mode)
- Dev tools have updates styles (Dev bundle mode)
- Listen for that event in theme editor, and when it is triggered, remove optimistic style updates, and refresh property values shown in editor. This should ensure that the correct property values are shown in all cases (change property, clear property, change class name, undo, redo).
- Removes mechanism for preventing live reload from the dev tools
Covers both dev bundle mode and Vite hot deploy mode.
Based on the changes from …
> refactor: integrate CSS HMR into theme editor

- vaadin-spring/pom.xml
vulnerability report: https://nvd.nist.gov/vuln/detail/CVE-2023-20863
the matching spring-boot hasn't been released yet.
> fix: use spring-framework-bom 6.0.8 to resolve vulnerability

- flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleUtils.java
As UIInternals always tries to load the bundle info, we cannot warn as never exists in development mode
> chore: Do not output warning in development mode

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
pnpm 8 dropped node 14 support which has no impact on Flow. There are changes to the lockfile and local store format but pnpm should upgrade or redownload as needed.
> chore!: Bump pnpm version to a supported versions (8.3.1)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Avoids excessive logging on each startup:
```
c.v.f.s.frontend.TaskRunDevBundleBuild   : Checking if a development mode bundle build is needed
c.v.f.s.f.TaskRunDevBundleBuild$1        : Added 19 default dependencies to main package.json
c.v.f.s.frontend.TaskRunDevBundleBuild   : A development mode bundle build is not needed
c.v.f.s.f.TaskGeneratePackageJson        : Added 19 default dependencies to main package.json
c.v.f.s.frontend.TaskCopyFrontendFiles   : Copying frontend resources from jar files ...
c.v.f.s.frontend.TaskCopyFrontendFiles   : Visited 21 resources. Took 15 ms.
```
> chore: Change log level to debug

- flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java
`chromeOptions.setCapability("networkConnectionEnabled", true); `was deprecated, and now it was removed from Selenium, but we used it in our chromeOptions, which caused an exception now as we tried to update to the latest selenium version.
This was needed to be able to do a `setConnectionType()` in Chrome.
BUT:
I have checked and` setConnectionType() ` is not used anymore, so I am removing code parts that are not w3 compliant anymore, it was used in PWA-related IT tests back then, but not now. In that case, no point to block us from using the latest/safest selenium versions. Did we use it back then for AirPlane mode and other modes potentially? So we can delete the whole related code now, I hope.
More info:
- https://github.com/SeleniumHQ/selenium/issues/11923
MobileEmuliation seems is …
> fix, chore: Removing some dead code (now is the perfect time: selenium 4.9.0. is more strict on being w3c)

- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataProvider.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataChangeEvent.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataProvider.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataProviderWrapper.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataProviderTest.java
Adds new method `DataProvider#refreshItems(boolean)` as a replacement for `DataProvider#refreshAll()` to allow choosing to either clear or keep selection. 
`DataChangeEvent` has new method `isClearSelection()` that `DataProvider` change listeners can utilize.
Fixes #16532
> feat!: add DataProvider API for refreshing without clearing selection

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
The tasks should use finder for getting
resources instead of using a XYZ.class.getClassLoader() as 
that doesn't contain required content.
This fixes the issue that a production build in maven/gradle 
prints out `Unable to determine version information. No vaadin-core-versions.json found`
Fixes #16032
> fix: TaskUpdatePackages should use finder

- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/ProjectHelpers.java
Copying @Artur's idea. I saw some unused imports lately. (Reference PR: https://github.com/vaadin/flow/pull/16612)
So:
1. `find . -type f -name "*.java"|xargs java -jar google-java-format-1.16.0-all-deps.jar --fix-imports-only --skip-sorting-imports -rgit then add "**/*.java"s`
2. `git add "**/*.java"`
> Unused import cleanup

- flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
- flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
- flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/UIsCollectedWithBeaconAPIView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LocaleChangeIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/UIsCollectedWithBeaconAPIIT.java
- flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/routescope/PreserveOnRefreshIT.java
Notifies server about closed UIs using a beacon request on pagehide event.
At the same time unifies behaviour in certain edge cases, where Safari maintained the state when brought back from page cache. Previously Safari in some situations kept the state.
Tested manually with Safari, Chrome, Firefox and validated results using VisualVM.
Closes #6293
> feat: More eager cleanup for UIs using Beacon API

- pom.xml
maven-enforecer-plugin version is set in the pluginManagement section of the POM file, but for some reason the version is ignored when running the build with release profiles active.
This change pins the plugin version also in the plugin section.
> chore: pinned maven enforcer plugin version

- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
Tries up to 5 times with a delay of 5 seconds to better deal with network issues
> fix: Make node download more stable

- flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadAccess.java
JRebel detects `BrowserLiveReloadAccess` and uses it to trigger the browser reload
> fix: Restore JRebel support

- flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
- flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBuild.java
- flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
- flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/test/java/com/vaadin/flow/uitest/ui/theme/CssLoadingIT.java
- flow-tests/test-express-build/test-prod-bundle/pom.xml
Add a parameter that forces a
production bundle build even
when an applicable bundle exists.
Closes #16752
> feat: add parameter to force prod build

- flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
If the LoadDependenciesOnStartup
annotation is added a production
bunlde should always be built.
> fix: Require production bundle for LoadDependenciesOnStartup

- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataProvider.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataChangeEvent.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataProvider.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataProviderWrapper.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataProviderTest.java
Reverts recent DataProvider API changes, because it's not yet finally decided how the API should look like for setting components to erase or not the selection upon data refresh.
Also, we almost lost a train to include it to the Vaadin 24.1, so the suggestion is to make better API and use cases elaboration and target this feature to Vaadin 24.2.
Issue to follow up https://github.com/vaadin/platform/issues/3640.
This reverts commit 9d2b7b19a924f1dc580423e5f8ad340f2e71c3aa.
> Revert "feat!: add DataProvider API for refreshing without clearing selection (#16650)"

- flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
- flow-server/src/test/java/com/vaadin/flow/server/OSGiVaadinServletTest.java
This change ensures that Lookup is set in servlet context attributes when initializing VaadinServlet in OSGi environment.
Fixes: vaadin/base-starter-flow-osgi/issues/296
> fix: set Lookup attribute to servlet context from OSGi servlet context

- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
This ensures you can overwrite all parts of the index page in listeners
> fix: Run the IndexHtmlRequestListener after the whole page is complete

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
- flow-server/src/main/resources/vite.generated.ts
- flow-server/src/test/java/com/vaadin/tests/util/TestUtil.java
- flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/webapp/imported-by-vite-plugin.css
- flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/frontend/ViteImportedCSSIT.java
- flow-tests/test-express-build/test-dev-bundle-frontend-add-on/vite.config.ts
> fix: Store and reuse index.html modifications for dev bundles

- flow-server/src/main/resources/com/vaadin/flow/router/NoRoutesError_hilla.html
A single Maven goal/Gradle task is suggested for Hilla, as the framework used depends on the contents of `pom.xml`/`build.gradle`.
> fix: suggest single goal for scaffolding Hilla apps

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFiles.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFilesTest.java
When running a Hilla project
or a project containing a package.json
do not clean node_modules.
Fixes #16830
> fix: retain node_modules folder

- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
> fix: remove detach listener when javascript execution completes

- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
> fix: remove detach listener when javascript execution completes (#16836) (CP: 24.0)

- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
> fix: remove detach listener when javascript execution completes (#16836) (CP: 9.1)

- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
> fix: remove detach listener when javascript execution completes (#16836) (CP: 2.9)

- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
> fix: remove detach listener when javascript execution completes (#16836) (CP: 2.8)

- flow-tests/test-express-build/test-dev-bundle-frontend-add-on/pom.xml
Module `test-dev-bundle-frontend-add-on` contains a custom `vite.config.ts`, but if a `clean` is performed before executing the tests it is deleted and there are test failures
> test: do not delete custom vite.config.ts on clean

- flow-server/src/main/java/com/vaadin/flow/component/Text.java
- flow-server/src/test/java/com/vaadin/flow/component/TextTest.java
Make sure that calling methods inherited from HasStyles and that doesn't make sense in Text, throw a UnsupportedOperationException with a descritive message. The methods that got better error messages are those that could update a component:
- addClassName
- removeClassName
- setClassName
- addClassNames
- removeClassNames
Fixes #16646
> feat: Improve error messages in Text methods

- flow-server/src/main/java/com/vaadin/flow/server/LoadDependenciesOnStartup.java
VS Code refuses to understand that a View which extends a Component can be used with the annotation when it is `Class<? extends Component>`. VS Code is broken here but this is a workaround to make VS Code work.
> fix: Change from ? extends Component to ? for VS Code

- flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
Fixing this exception.
```
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.util.Optional
at com.vaadin.flow.component.html.HtmlComponentSmokeTest.testSetter(HtmlComponentSmokeTest.java:234)
at com.vaadin.flow.component.html.HtmlComponentSmokeTest.lambda$testSetters$3(HtmlComponentSmokeTest.java:138)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at …
```
> fix: HtmlComponentSmokeTest.testAllHtmlComponents() casting dynamically problem

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
The TaskRunNpmInstall should use ClassFinder
to load the vaadin-core-versions.json
Fixes #16032
> fix: npm install task should use ClassFinder

- .github/workflows/validation.yml
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
- flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
Add `vaadin.` prefix to `ci.build` and `force.production.build` properties added in 24.1 to satisfy naming rules.
Also see https://github.com/vaadin/docs/pull/2450
Fixes https://github.com/vaadin/flow/issues/16880
> chore!: Add vaadin. prefix to recently added properties

- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/stats/ProjectHelpersTest.java
ProjectHelpersTest tests sets user.home system property to a custom value, but they do not reset it after execution, causing other tests to potentially fail or behave incorrectly.
This change resets user.home at original value after each test
> test: restore user.home system property after test (#14273) (CP: 9.1)

- flow-server/src/main/resources/webpack.generated.js
Removed 'babel/plugin-proposal-object-rest-spread' from 'webpack.generated.config.js'. Edge version starting from 79 has support for 'Spread in object literals' and therefore this babel plugin is not needed anymore. 'babel/plugin-proposal-object-rest-spread' was renamed to 'plugin-transform-object-rest-spread' which caused build issues.
Fixes: #16905
> fix: removed babel/plugin-proposal-object-rest-spread

- flow-server/src/main/resources/META-INF/frontend/theme-util.js
Workaround for https://bugs.webkit.org/show_bug.cgi?id=254844
Fixes #16909
> fix: Use push/splice to avoid Safari 16.4 issue

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
- flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/CleanFrontendMojoTest.java
When running the clean-frontend target
remove also application dev bundle
from the project.
Part of #16888
> feat: clean app devBundle with clean-frontend

- pom.xml
2.15.1 is faulty version. as this reported issues. https://github.com/FasterXML/jackson-core/issues/1027
hilla is using this version as it was aligned from flow.
> chore: upgrade jackson.version to 2.15.2

- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
File found can be ignored if not
building bundle due to accepted bundle.
Fixes #16885
> fix: Accept css if not building bundle

- flow-plugins/flow-gradle-plugin/pom.xml
- flow-tests/test-express-build/frontend-add-on/pom.xml
- flow-tests/test-express-build/java-add-on/pom.xml
- flow-tests/test-express-build/test-dev-bundle/pom.xml
- flow-tests/test-express-build/test-prod-bundle/pom.xml
- pom.xml
Update available plugins
to not get validation issues.
This lessens some of them when
building flow.
partly to #16881
> fix: update plugins

- flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeUtils.java
Classloader always uses a / separated path
> fix: Find production bundle theme on Windows

- flow-server/src/main/resources/META-INF/frontend/theme-util.js
The polyfill does not support push or splice, see https://github.com/calebdwilliams/construct-style-sheets/issues/124
> fix: Theme injection in Safari with polyfill

- flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandler.java
Log error messages and throw more
generic exceptions.
> fix: log error messages

- flow-client/pom.xml
- flow-server/pom.xml
- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloader.java
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/ProjectHelpers.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/StatisticsSender.java
Less dependencies that might cause conflicts in user projects
Fixes #14538
> chore: use SDK http client instead of a separate http-client dependency

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Add check for known bad npm
version so that the user
knows to update if using that
exact version.
> chore: Add 9.2.0 as unsupported npm version

- flow-server/src/main/java/com/vaadin/flow/server/communication/LongPollingCacheFilter.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/LongPollingCacheFilterTest.java
Storing the header value in AtmosphereResource session should prevent issues with long polling and servlet container that recycles requests. This change stores in the resource session the value got from client during connection so that it will be available even if the underliyng request gets nullified.
Part of #16968
Part of #16775
> fix: store LastSeenServerSyncId in atmosphere resource session

- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
The addCssBlock function
should be added when ever
a cssimport with inclue is added
Fixes #16979
> fix: add addCssBlock function when needed

- flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/AbstractLiveReloadIT.java
While waiting for live reload, the searched element may become stale before being able to get its attributes.
Catching the exception allows the test to continue and succeed once the reload is completed.
> test: fix flakyness in FrontendLiveReloadIT

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/DevModeUsageStatistics.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/StatisticsConstants.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/stats/DevModeUsageStatisticsTest.java
Add machineId to the reported stats. This allows us to connect the data to license data. Related to MAU.
> feat: DevModeUsageStatistics: track MachineId as well

- flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/AbstractLiveReloadIT.java
While waiting for live reload, the searched element may become stale before being able to get its attributes.
Catching the exception allows the test to continue and succeed once the reload is completed.
> test: fix flakyness in FrontendLiveReloadIT (#17044) (CP: 9.1)

- flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/AbstractLiveReloadIT.java
While waiting for live reload, the searched element may become stale before being able to get its attributes.
Catching the exception allows the test to continue and succeed once the reload is completed.
> test: fix flakyness in FrontendLiveReloadIT (#17044) (CP: 24.0)

- flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/AbstractLiveReloadIT.java
While waiting for live reload, the searched element may become stale before being able to get its attributes.
Catching the exception allows the test to continue and succeed once the reload is completed.
> test: fix flakyness in FrontendLiveReloadIT (#17044) (CP: 23.3)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/StatisticsConstants.java
Remove and stop collecting data for sub-parts of the build process: startDevserverWebpack(_count/min/max/avg)
packageManagerInstall(_count/min/max/avg)
packageManagerCleanup(_count/min/max/avg)
packageManagerInstallnpm(_count/min/max/avg)
These measurements measure an unknown percentage of the total build time. We have not been able to use them for useful decision-making.
> chore: stop collecting stats for build process sub-parts

- flow-client/pom.xml
add flow-server sources as
a sources dependency instead
of a src resource.
Closes #17020
> fix: do not have server sources in client

- flow-data/src/main/java/com/vaadin/flow/data/binder/AbstractBeanPropertyDefinition.java
- flow-data/src/main/java/com/vaadin/flow/data/binder/BeanPropertySet.java
- flow-data/src/main/java/com/vaadin/flow/data/binder/PropertyDefinition.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BeanPropertySetTest.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderCustomPropertySetTest.java
BeanPropertySet fails to merge property definition when a class inherits and overrides a getter with a generic return type.
This change checks for return type equality only if both property definitions have not a generic return type.
When merging property definitions, the non-generic definition is taken.
Fixes #16838
> fix: fix property detection for generic return type

- flow-data/src/main/java/com/vaadin/flow/data/provider/HasLazyDataView.java
In HasLazyDataView.setItems the error message says:
"Trying to use exact size with a lazy loading component without either providing a count callback for the component to fetch the count of the items or a data provider that implements the size query. Provide the callback for fetching item count with
component.getLazyDataView().withDefinedSize(CallbackDataProvider.CountCallback);
or switch to undefined size with
component.getLazyDataView().withUndefinedSize();"
Since 2020 the API has changed. This PR teaches developers the current API.
Fixes #17062
> fix: Fix HasLazyDataView.setItems error message to be compliant with the current API

- flow-server/src/main/java/com/vaadin/flow/internal/UsageStatistics.java
Current code is thread-safe under JMM as guaranteed by the class initialization lock. However, semantically-wise, since the field won't change, it's safer to explicitly state the intent.
No associated issue.
> chore: Make UsageStatistics.entries final

- flow-server/src/main/java/com/vaadin/flow/shared/util/SharedUtil.java
- flow-server/src/test/java/com/vaadin/flow/shared/util/SharedUtilTests.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifier.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifierTest.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandlerTest.java
Changed suggested classname prefix from UpperCamelCase to lower-dash-case.
Fixes #16865
> fix: changed suggested classname to dash-case

- flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
The PR clarifies in JavaDoc that the new validation mechanism is disabled by default in Vaadin 14.
A follow-up to https://github.com/vaadin/flow/pull/17056
> docs: clarify that new validation mechanism is disabled by default

- flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/DefaultErrorHandlerTest.java
Flow default error handler logs all caught exceptions. However, there may be exceptions thrown by servlet container that are meant to be tracked only at debug level (e.g. Jetty QuietException implementors).
This change prevents logging of similar 'quiet' exception, unless the DefaultErrorHandler logger level is set to debug or higher.
By default, the following exceptions are ignored:
* java.net.SocketException
* java.net.SocketTimeoutException
* java.io.EOFException
* org.apache.catalina.connector.ClientAbortException
* org.eclipse.jetty.io.EofException
Closes #16311
> feat: prevent logging of ignored exceptions

- flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
To reduce the false positive warnings when the deprecated `Label` component is used by the `flow-components` with proper client-side logic to associate the field with the `Label`. The attribute `slot=label` is also added to the list of valid use-cases.
Related to https://github.com/vaadin/flow-components/issues/5171 and https://github.com/vaadin/flow/pull/16708#issuecomment-1600736263
> fix: add slot=label attribute as legit use-case for the deprecated Label

- vaadin-spring/src/main/java/com/vaadin/flow/spring/DevModeBrowserLauncher.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/DevModeBrowserLauncherHttpsProtoTest.java
Fixes #15496 vaadin.launch-browser=true and HTTPS 
This fix brings the behavior of the feature "opening browser" according to the application settings that can be used SSL in a development environment.
I can't check it locally because mvn verify is broken on my development host.
> Fix vaadin.launch-browser=true and HTTPS #15496

- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
Currently, the detach listener callback is added to pending javascript invocation on every call to dumpPendingJavaScriptInvocations. This change will apply the callback only once, when the pending invocation is seen for the first time.
Fixes #17082
> fix: add detach listener callback once for pending invocations

- flow-server/src/test/java/com/vaadin/flow/server/communication/AtmospherePushConnectionTest.java
To help identify the cause of concurrent disconnection test flakyness, the stacktrace of potentially raised exception is printed on logs.
> test: print stacktrace when concurrent push disconnection test fails

- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
UI dirty check currently takes into account also pending JS invocation for invisible node, that however will not be sent to the client. This change updates the check to only consider JS invocation that should be effectively sent to the browser.
> fix: ignore pending JS invocations for invisible node in UI dirty check

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksViteTest.java
Copy the package-lock.json from
the dev bundle in frontend
hotdeploy mode if no package-lock
is available.
> fix: copy package-lock from bundle in hotdeploy

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
The package list always includes all packages (from @NpmPackages). We need to check which js modules are actually used to know which components are used
> fix: Validate license only for used components

- vaadin-dev-server/frontend/vaadin-dev-tools.ts
Allow the browser to adapt any native controls (like scrollbars) to the dark color scheme.
Before:
After:
> fix: use dark color scheme for dev tools

- flow-server/src/main/java/com/vaadin/flow/component/page/History.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
- flow-server/src/test/java/com/vaadin/flow/component/page/HistoryTest.java
Dispatch a `popstate` event when using server-side navigation, which allows components like `vaadin-side-nav` to react to location changes. The event includes the state `{state: 'vaadin-router-ignore'}`, so that Vaadin router ignores the event.
This is similar to what Vaadin router does to notify about location changes:
https://github.com/vaadin/router/blob/f5f31e00acd542fe714ea472172d17a03ba04794/src/router.js#L733-L742
Closes https://github.com/vaadin/flow/issues/17138
- Feature
> feat: dispatch popstate event on server-side navigation

- flow-server/src/main/resources/vite.generated.ts
When running in dev mode, the service worker should be served from memory and not written to the filesystem, to avoid potential endless restarts when Spring dev tools are in use.
This change fixes a regression introduced when service worker compression was implemented, that causes sw.js to be written to the filesystem also in dev mode.
> fix: prevent writing service worker on filesystem in dev mode

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/RestartMonitorTest.java
If hot reload is enabled, e.g. with Spring Dev Tools, during Java server restart the check for active dev-server connection may temporarily fail because the dev-server is restarting.
This change finds and sets the currently active restart monitor before checking for dev-server connection, so that the check will wait for a potential restart to complete.
> fix: set restart monitor before checking for dev server connection

- flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServletServiceTest.java
When Java hot reload is enabled, it is possible that VaadinServlet will receive requests even if its destroy method has been invoked. When this happens, getting the PWA registry may fail with an NPE because of VaadinServlet optimizations for servlet initialization. This change prevents getting the PWA registry if the VaadinServlet is not initialized or has been destroyed
Fixes #17137
> fix: prevent PWA registry lookup when VaadinServlet is not initialized

- flow-server/src/main/resources/vite.generated.ts
When running in dev mode, the service worker should be served from memory and not written to the filesystem, to avoid potential endless restarts when Spring dev tools are in use.
This change fixes a regression introduced when service worker compression was implemented, that causes sw.js to be written to the filesystem also in dev mode.
> fix: prevent writing service worker on filesystem in dev mode (#17155) (CP: 24.0)

- flow-server/src/main/resources/vite.generated.ts
When running in dev mode, the service worker should be served from memory and not written to the filesystem, to avoid potential endless restarts when Spring dev tools are in use.
This change fixes a regression introduced when service worker compression was implemented, that causes sw.js to be written to the filesystem also in dev mode.
> fix: prevent writing service worker on filesystem in dev mode (#17155) (CP: 23.3)

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Replaces deprecated Spring Security APIs marked for removal in 7.0
Fixes #16872
> chore: replace deprecated Spring Security APIs usage

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
mkdirSync in Node has had recursive:true support since Node 10
> chore: Remove unnecessary mkdirp dependency

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
- flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BasicsIT.java
This version has a UI rewritten with Vue and always includes the custom overlay element in the DOM
> chore: Upgrade vite plugin checker to 0.6.1

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/main/resources/pnpmfile.js
The old chokidar version was used by webpack 4...
> fix: Do not force chokidar version

- flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java
- flow-tests/test-webpush/src/main/java/com/vaadin/flow/webpush/WebPushView.java
- flow-tests/test-webpush/src/test/java/com/vaadin/flow/webpush/WebPushIT.java
- flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
- flow-webpush/src/main/resources/META-INF/frontend/FlowWebPush.js
Webpush integration test was working fine locally, also using selenium hub, but failed on CI env.
This change fixes the test by waiting a bit longer for the subscription to complete and handling errors received a string instead of JSON objects.
> test: fix webpush integration test

- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/TestUtils.kt
- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPlugin.kt
Checks the gradle version when applying the plugin and fails fast if the current gradle version is unsupported.
Closes #16149
> feat: fail fast when plugin is used with an unsupported version of Gradle

- flow-server/src/main/java/com/vaadin/flow/server/communication/LongPollingCacheFilter.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/LongPollingCacheFilterTest.java
Fixes: https://github.com/vaadin/flow/issues/17237
> fix: Fix regression when sync id check is disabled

- flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/AtmospherePushConnectionTest.java
Prevents a deadlock that may happen when a servlet container holds a lock on HTTP session access and a push disconnection happens concurrently with a push operation requested when VaadinSession is unlocked after session destroyed listeners are invoked.
References #16293
Co-authored-by: Johannes Tuikkala @johannest
> fix: prevent deadlock when push is requested during disconnect (#17130) (CP: 24.0)

- flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/AtmospherePushConnectionTest.java
Prevents a deadlock that may happen when a servlet container holds a lock on HTTP session access and a push disconnection happens concurrently with a push operation requested when VaadinSession is unlocked after session destroyed listeners are invoked.
References #16293
Co-authored-by: Johannes Tuikkala @johannest
> fix: prevent deadlock when push is requested during disconnect (#17130) (CP: 23.3)

- flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/AtmospherePushConnectionTest.java
Prevents a deadlock that may happen when a servlet container holds a lock on HTTP session access and a push disconnection happens concurrently with a push operation requested when VaadinSession is unlocked after session destroyed listeners are invoked.
References #16293
Co-authored-by: Johannes Tuikkala @johannest
> fix: prevent deadlock when push is requested during disconnect  (#17130) (CP: 2.9)

- flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/AtmospherePushConnectionTest.java
Prevents a deadlock that may happen when a servlet container holds a lock on HTTP session access and a push disconnection happens concurrently with a push operation requested when VaadinSession is unlocked after session destroyed listeners are invoked.
References #16293
Co-authored-by: Johannes Tuikkala @johannest
> fix: prevent deadlock when push is requested during disconnect (#17130) (CP: 9.1)

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Spring security configurers accepting strings matcher may fail to detect if the parameter is a Spring MVC pattern or not. This change update VaadinWebSecurity to explictly use ant path request matchers.
> chore: explictly use ant path matchers in VaadinWebSecurity

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
Classloading errors may cause the frontend-build to fail, but without any useful information.
This change overrides the original class resolve method adding exception logging to help in troubleshooting build issues.
> chore: log classloading errors in reflections class finder

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/DevModeUsageStatistics.java
Handles potential failures due to JNA incompatibility when collecting statistic data, providing empty value as default.
Fixes vaadin/quarkus#136
> chore: prevent usage statistics failure when collecting info

- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
Pre compiles the regex pattern to improve build frontend performance during the bytecode scan and collection of reachable classes. Also adds some package exclusions for well knonw libraries that should not be visited.
Part of #17234
> fix: pre-compile visitable classes regex pattern

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Similar to an [issue](https://github.com/vaadin/flow/issues/14435) that was [fixed](https://github.com/vaadin/flow/pull/14647) before, there is a new [issue](https://github.com/vaadin/flow-components/issues/4674) regarding endless loops triggered under certain conditions. The issue was originally reported for  `ComboBox`. However, the behaviour can be reproduced with a `Grid` as well, since the underlying issue is with the `DataCommunicator`. Even if the example or the test is not considered best practice, the endless loop should still be avoided.
This PR replaces the flush request canceling approach using a "flush in progress" flag. While a registered flush is triggered, until it ends, no other flush requests will be registered. With this change, any edge cases regarding registering …
> fix: do not register requests while flush in progress

- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
Pre compiles the regex pattern to improve build frontend performance during the bytecode scan and collection of reachable classes. Also adds some package exclusions for well-known libraries that should not be visited.
Part of #17234
> fix: pre-compile visitable classes regex pattern (#17280) (CP: 24.0)

- flow-jandex/pom.xml
> fix: update jandex-maven-plugin for JDK 21

- vaadin-dev-server/frontend/theme-editor/editor.test.ts
- vaadin-dev-server/frontend/theme-editor/editor.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-accordion-heading.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-accordion-panel.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-board-row.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-board.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-date-picker.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-date-time-picker.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-details-summary.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-form-layout.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-list-box.ts
- vaadin-dev-server/frontend/theme-editor/metadata/model.ts
Added metadata for vaadin-board (also for vaadin-board-row) and vaadin-form-layout.
Added possibility to define additional information for specific components:
In case component is accessible:
And when component is not accessible:
> Feat/theme editor vaadin-board and vaadin-form-layout

- flow-html-components/src/test/java/com/vaadin/flow/component/html/ComponentTest.java
> test: ignore properties from mixin interfaces in component tests

- vaadin-dev-server/frontend/theme-editor/editor.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-accordion-heading.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-accordion-panel.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-accordion.ts
- vaadin-dev-server/frontend/theme-editor/model.ts
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeModifier.java
Fixed issue of string comparison while comparing CSS Selectors ('>' vs ' > '). Updates `vaadin-accordion` metadata.
> fix: fixed issue with using child selector, accordion metadata updates
