- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-tab.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-tabs.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-tabsheet.ts
1. There isn’t support for box-shadow as editor property, the divider on Tabs uses box-shadows
2. There isn’t a way to specify style properties for variants, the divider on Tabs uses box-shadows but vertical variant needs a different sets value to style the width and the horizontal variant also needs a different set of values.
3. There isn't a way to set the `width`, and `color` of the Tab divider because the values are defined together as a single CSS property - `box-shadow: inset 0 -1px 0 0 var(--lumo-contrast-10pct);`. It will need some method to expose only the `width` and `color` to user in the editor for styling while it adds the other values and assign it to the `box-shadow`.
4. There isn’t support for multiple css selectors. To style the selected tab indicator, you will need to …
> Add meta data for tab and tabsheet

- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-message-list.ts
1. It will be more helpful to be able to set `border-bottom` for the message item other that border around the entire message item. shapeProperties only have `border-width`, would be helpful to have `border-bottom-width`
2. The default style values for `vaadin-message`, `::part(name)`, `::part(title)` and `::part(message)` are empty until you update the style with a new value
3. Avatar component `vaadin-message > vaadin-avatar` cannot be styled as a child component and vaadin avatar cannot be selected to be styled individually since it’s a slot not a direct shadow child element to `vaadin-message`.
> Add meta data for message list

- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SerializeShortcutIT.java
On OSGi environments, deserialization requires custom class loading handling, so the tests fail with a ClassNotFoundException.
> test: disable deserialization test on OSGi

- flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-security-flow/pom.xml
Seldom the unpack goal selects the wrong test artifact, without the 'tests' classifier, causing the build to fail because of classes not found. A related issue happens on IntelliJ IDEA, where the super class in the hierarchy cannot be found.
This change adds the 'tests' classifier to the unpack configuration to identify the correct artifact.
> test: add tests classifier to test-jar unpack configuration

- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-map.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-spreadsheet.ts
Theme Editor metadata for Spreadsheet and Map, strange issue is present but it's not blocking use of Theme Editor:
While dynamically creating `vaadin-spreadsheet` element using `document.createElement('vaadin-spreadsheet')`  I end up with:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertRule')
at bT (spreadsheet-export.js:1478:33)
at HV (spreadsheet-export.js:2369:288)
at v_ (spreadsheet-export.js:377:18)
at GP (spreadsheet-export.js:2279:132)
at new d7 (spreadsheet-export.js:2053:124)
at VaadinSpreadsheet.updated (vaadin-spreadsheet.js:179:18)
at VaadinSpreadsheet._$didUpdate (reactive-element.js:868:1)
at VaadinSpreadsheet.performUpdate (reactive-element.js:834:1)
at VaadinSpreadsheet.scheduleUpdate (reactive-element.js:753:1)
at …
```
> feat: Spreadsheet and Map metadata

- flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java
- flow-server/src/test/java/com/vaadin/flow/component/ComponentEventBusTest.java
- flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
Currently, it is possible to add component event listeners pointing to a null reference. At runtime an NPE is thrown, but for an internal wrapper class, making difficult to spot where the null reference comes from. This change will throw immediately if null is given as a component event listener.
> fix: fail when adding null component event listener

- flow-jandex/pom.xml
This reverts commit bf2d96977071813ab13a96fbf023dfb1766dcc13.
The index produced by this plugin is not supported by Quarkus 2, that fails with errors similar to "Can't read index version 11; this IndexReader only supports index versions 2-3,6-10"
> revert: update jandex-maven-plugin for JDK 21 (#17291) (#17323)

- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-side-nav-item.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-side-nav.ts
1. There isn’t support for `border-width-right` or `border-width-left`, it will be more helpful to set the border style on just one side of the `vaadin-side-nav` or it's parent wrapper.
2. To ensure consistent styles for multiple `vaadin-side-nav` and `vaadin-side-nav-item` elements within a single wrapper, you need to apply global styles. This may not be very helpful when there are multiple side nav (as sub navigation).
3. To make styles consistent for all `vaadin-side-nav-item`, selectors have been moved to the parent component but styles applied on the `vaadin-side-nav-item` has flow specificity and can't override parent style.
4. Some style properties on `vaadin-side-nav-item` label ends up affecting suffix content if it’s a text, eg: badge gets `italic` style, and leading icon gets …
> Add meta data for side nav

- flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
- flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
- flow-server/src/test/java/com/vaadin/flow/router/QueryParametersTest.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterLinkTest.java
When an empty query parameters object is given to a RouterLink the computed href contains an empty query string.
This change prevents the addition of the query string to the href attribute when query parameters object is empty. It also fixes parsing to return an empty query parameters object for blank string.
Fixes #17287
> fix: prevent adding query string for empty parameters in router link href

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Tested with Node.js 18 (V24.2, 24.1, 24.0, 23.3) using spring skeleton starter.
Flow 9.1 and 2.10 need either
- upgrade to pnpm 7.33.5 and update supported Node version to 14,
- or upgrade to pnpm 8.6.11 and update supported Node version to 16,
because Node 12 is not compatible with pnpm >= 7, see https://pnpm.io/installation#compatibility.
> chore: Upgrade pnpm to latest 8.6.11

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Cherry pick from main + update patch version for Node.js to be aligned with main.
> chore: Upgrade pnpm to latest (CP: 23.3)

- flow-data/src/main/java/com/vaadin/flow/data/validator/EmailValidator.java
- flow-data/src/test/java/com/vaadin/flow/data/validator/EmailValidatorTest.java
As indicated in issue #17333, this PR changes the validation pattern of an email address by invalidating the dot-dot in the domain name.
The pattern is now public in order to reference it in EmaiField and remove duplicate code (see https://github.com/vaadin/flow-components/pull/5320)
Fixes #17333
> fix: reject emails with double dot between domain and tld

- vaadin-dev-server/frontend/component-picker.ts
- vaadin-dev-server/frontend/component-util.ts
- vaadin-dev-server/frontend/theme-editor/components/component-resolver.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/defaults.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-big-decimal-field.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-button.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-confirm-dialog.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-cookie-consent.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-dialog.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-email-field.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-integer-field.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-login-form.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-login-overlay.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-notification.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-number-field.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-password-field.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-text-area.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-text-field.ts
- vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-upload.ts
There are components that cannot be picked directly due to being rendered in overlay:
- `vaadin-cookie-consent`
- `vaadin-login-overlay`
- `vaadin-dialog`
- `vaadin-confirm-dialog`
- `vaadin-notification`
After moving mouse over such components, they not present in node tree and are not recognized by picker. 
Resolver has been introduced to match and resolve proper Vaadin components that are present in node tree and can be styled.
In addition to above highlighting of overlay elements is also used using highlight resolver as highlighted element is different than hovered.
https://github.com/vaadin/flow/assets/106965834/2741e0b1-753b-4efa-b0ec-73f2091d7a53
> feat: overlay resolver, metadata for overlay components

- flow-tests/test-npm-only-features/test-npm-no-buildmojo/pom.xml
- pom.xml
This fixes errors when running `flow-test-npm-no-buildmojo` locally:
- JNA version conflict, with the newer WDM the JNA version is the same as in the license-checker, so no conflicts,
- Removes the whole node_modules directory, otherwise it causes packages compilation errors within running `mvn verify`
> chore: Upgrade webdrivermanager and delete node modules properly

- flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/MyLitField.java
Fixes an issue with two versions of polymer library imported twice in the bundle
> test: downgrade vaadin-radio-button to 1.6.0

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendOutputProperties.kt
This removes the frontend folder from watch list of the `VaadinPrepareFrontendTask`, because it overlaps with frontend/generated folder, causing cache problems:
```
Caching disabled for task ':vaadinPrepareFrontend' because:
Gradle does not know how file 'frontend/styles' was created (output property 'taskOutputProperties.frontendDirectory'). Task output caching requires exclusive access to output paths to guarantee correctness (i.e. multiple tasks are not allowed to produce output in the same location).
```
Files in the frontend folder are project-specific and handled outside of prepare-frontend task.
> fix: Remove frontend directory from prepare frontend output list

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
This is a node security release
> chore: Upgrade Node to 18.17.1

- flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
This change makes UI#navigate, BeforeEvent#rerouteTo and BeforeEvent#forwardTo methods more consistent without changing the existing API:
- adds new methods in BeforeEvent that accepts route parameters.
- adds new methods in BeforeEvent that accepts query parameters.
- improves forwardTo and rerouteTo to accept route parameters being part of the location String (same way as UI#navigate does it already).
Fixes: https://github.com/vaadin/flow/issues/14553
> feat: Update navigation method signatures 

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendOutputProperties.kt
- flow-server/src/main/java/com/vaadin/flow/component/HasComponents.java
- flow-server/src/main/java/com/vaadin/flow/component/HasHelper.java
- flow-server/src/main/java/com/vaadin/flow/component/HasLabel.java
- flow-server/src/main/java/com/vaadin/flow/component/HasSize.java
- flow-server/src/main/java/com/vaadin/flow/component/HasStyle.java
- flow-server/src/main/java/com/vaadin/flow/component/HasText.java
- flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java
- flow-server/src/main/java/com/vaadin/flow/component/HasValidation.java
Improved documentation of Has* mixin interfaces. Added more details when to use some of the interfaces and when not.
Related-to: #10761
> docs: Update mixin interface JavaDoc

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
This is a node security release
> chore: Upgrade Node to 18.17.1 (#17411) (CP: 24.0)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
CSS from CssImport.themeFor should be eagerly loaded, otherwise the framework tries to apply them after the web-component is already registered, resulting in an error in the browser.
Although CssImport.themeFor is not recommended with Vaadin 24 it can still be used and in some cases it is required to work around some of the limitations mentioned in vaadin/docs#2552.
This change forces CSS from CssImport.themeFor to be loaded eagerly.
Fixes #17345
Fixes #17221
> fix: eager load css from CssImport.themeFor

- flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
- flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/StreamResourceView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java
If a path is already URL decoded but contains a percent char, the unsafe path check fails when it tries to decode it again.
The thrown IllegalArgumentException can be safely ignored, as it means that the input path is already decoded and can be checked as is.
Fixes #16561
Co-authored-by: Tatu Lund @TatuLund
> fix: fix unsafe path check for URL decoded path (#17312) (CP: 24.1)

- scripts/cherryPick.js
we have found issue with branch `cherry-pick-17312-to-24.1-1690808382065`, where there is only a branch but no PR.  this try/catch is trying to prevent that. https://vaadin.slack.com/archives/C6X43FE8M/p1692165275795269?thread_ts=1692109040.675989&cid=C6X43FE8M
> chore: add try/catch to PR creation in cherry pick script

- vaadin-dev-server/frontend/vaadin-dev-tools-info.ts
- vaadin-dev-server/frontend/vaadin-dev-tools-log.ts
- vaadin-dev-server/frontend/vaadin-dev-tools.ts
- vaadin-dev-server/tsconfig.json
Render using function (for backwards compatibility) or tag (for future plugins). 
Always render all tabs so they can handle communication in the future
The log and info tabs are split out in this commit
> refactor: Eagerly render all dev tools tabs

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
- flow-tests/test-express-build/test-embedding-express-build/src/main/java/com/vaadin/flow/webcomponent/MyView.java
- flow-tests/test-express-build/test-embedding-express-build/src/test/java/com/vaadin/flow/webcomponent/MyViewIT.java
When having a project with
application and WebComponents
the served bootstrap should be
served by the correct bootstrap
handler and not by what is available.
Fixes #17346
> fix: Serve correct bootstrap

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
- flow-tests/test-express-build/test-embedding-express-build/src/main/java/com/vaadin/flow/webcomponent/MyView.java
- flow-tests/test-express-build/test-embedding-express-build/src/test/java/com/vaadin/flow/webcomponent/MyViewIT.java
When having a project with
application and WebComponents
the served bootstrap should be
served by the correct bootstrap
handler and not by what is available.
Fixes #17346
> fix: Serve correct bootstrap (#17478)

- vaadin-dev-server/frontend/theme-editor/editor.ts
Support undo/redo shortcuts for a Theme Editor.
Fixes #17402
> feat: Theme Editor undo/redo shortcuts

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeModifier.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/ApplicationThemeNotAccessibleException.java
Removes creation of theme-editor.css on application startup.
Fixes #17462
> fix: do not create theme-editor.css on application startup

- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/README.MD
- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/java/com/vaadin/flow/spring/test/CodeGeneratorMojo.java
- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/java/com/vaadin/flow/spring/test/CssImportContext.java
- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/java/com/vaadin/flow/spring/test/JavaRouteContext.java
- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/java/com/vaadin/flow/spring/test/JsModuleContext.java
- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/resources/css-import.mustache
- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/resources/js-module.mustache
- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/resources/route-java.mustache
- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/java/com/vaadin/flow/spring/test/ApplicationServiceInitListener.java
- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/java/com/vaadin/flow/spring/test/SpringDevToolsReloadUtils.java
- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/java/com/vaadin/flow/spring/test/store/CatalogLayout.java
- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/java/com/vaadin/flow/spring/test/store/ProductView.java
- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/test/java/org/vaadin/example/SpringDevToolsReloadViewIT.java
- flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/main/java/com/vaadin/flow/spring/test/SpringDevToolsReloadUtils.java
- flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/test/java/org/vaadin/example/SpringDevToolsReloadViewIT.java
Adds three new system properties for `test-spring-boot-multimodule-reload-time`:
- `vaadin.test.codegen.maven.plugin.cssimports.per.route`
- `vaadin.test.codegen.maven.plugin.jsmodules.per.route`
- `route.hierarchy.enabled`
Updated README.MD to describe each property.
Updates each reload time test to run five times and report average result for the TeamCity.
> test: Add more measurements in reload time tests

- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ChunkInfo.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithByteCodeScannerTest.java
Checks if a chunk has already been considered for a given list of imported modules and scripts. If so, it doesn't generate a new file, but only updates the the import file, linking all the route class hashes with the same chunk file.
Also adds dependencyTriggers and eager fields to the ChunkInfo hashCode and equals, as ChunkInfo is used widely in maps.
Adds extra debug logging to AbstractUpdateImports to understand better what takes most of the time in large projects.
Related-to #17234
(cherry picked from commit 74196a047647f39f764470516d513d4314d564b9)
> fix: Not generate chunks with the same content (#17511)(CP: 24.1)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/CssBundler.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/CssBundlerTest.java
Add the fourth url group to
be checked when going through
url strings.
Fixes #17314
> fix: CssBundler should check all groups

- flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
- flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java
For errors in beforeClientResponse
handle cases where any part to the
errorHandler is null
Fixes #17352
> fix: Check for null when handling exception

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
Ensure that the binder does not hide / swallow the exception when something goes wrong while fields are already unregistered.
> fix: Binder throws NPE and eats a relevant exception

- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
The shouldVisit list in frontend
dependencies should match the
packages exactly and not as
a starts with.
e.g. com.vaadiner is not a match for com.vaadin
Found investigating https://github.com/vaadin/flow/issues/17490
> fix: shouldVisit should match package exactly

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Node 20 will become the LTS on 2023-10-24 and 24.2 is targeted for 2023-10-18
> chore: Upgrade default Node to 20.6.0

- flow-server/src/main/java/com/vaadin/flow/server/Constants.java
- pom.xml
Downgrade to atmosphere version
2.4.30.slf4jvaadin2 for osgi
compatibility.
> fix: Use earlier atmospehere version

- flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
For dependencies without custom versions in `package.json` (when `dependencies` and `vaadin.dependencies` agree), currently a pinned version from `versions.json` is not applied if it is for some reason older than the one specified in `package.json`. This effectively prevents downgrading npm package versions by changing the platform dependency version.
This change removes the downgrade prevention check.
Context: to speed up the upcoming release, Hilla platform 2.2 reverted to using stable React and Vaadin components 24.1.x before the beta1 release after using 24.2.0.alphaX during alpha releases. At the moment upgrading a Hilla application from 2.2.0.alpha10 to beta1 does not downgrade the component dependencies back to 24.1, while this is expected.
> fix: support downgrading dependencies based on versions.json

- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleUtils.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithByteCodeScannerTest.java
Chunk JavaScript lines shouldn't be sorted in place.
Sorting is only needed for repeatable hash calculations.
Fixes https://github.com/vaadin/flow/issues/17573
> fix: Not sort chunk lines in place

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
Do not fail if a managed version is linked to a local copy and thus the version cannot be parsed
> fix: Allow platform dependencies to be linked

- flow-plugins/flow-gradle-plugin/build.gradle
Set the kotlin language version
to be the same as java.
Fixes #17574
> fix: set kotlin language version

- flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/main/resources/application.properties
- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/resources/application.properties
- flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/main/resources/application.properties
Reduced `spring.devtools.restart.poll-interval` to 100ms and `spring.devtools.restart.quiet-period` to 50ms to reduce time it takes for `FileSystemWatcher` to react to file touch in tests. This stabilizes reload time measuring results and makes reloading faster in general.
> test: adjust spring.devtools.restart properties for reload time tests

- flow-server/bnd.bnd
- flow-server/src/main/java/com/vaadin/flow/server/Constants.java
- pom.xml
The modified atmosphere-runtime:2.7.3.slf4jvaadin5 exports packages with version 2.7.3 (i.e., not 2.7.3.slf4jvaadin5).
Depend on bundle version instead of the package version.
> chore: update atmosphere version

- pom.xml
this version of plugin doesn't allow deployAtEnd
> chore: remove not needed deploy.plugin version

- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
This change uses precompiled regex for string replacements and searches, to improve performance when expressions are used inside loops.
Part of #17234
> chore: use pre-compiled regex when possible

- vaadin-dev-server/frontend/vaadin-dev-tools.ts
If there are many tabs, they should be shown. If we still run out of space, allow scrolling
> fix: Allow dev tools window to grow

- flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringLookupInitializer.java
Cache `RoutePathProvider` in `SpringLookup` for faster lookup time especially for `RouteUtil#resolve` method, but also for all default (and subclasses of default) implementations of services defined in `LookupInitializer.getDefaultImplementations()`.
> perf: optimize SpringLookup lookup time by caching

- flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/AbstractBaseIT.java
- flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/CssLoadingIT.java
- flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
- flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeWebpackIT.java
The CSS loadin test is using a development mode servlet instead of the production mode.
This change fixes the url provided to the web driver in order to use the expected Vaadin servlet.
> test: fix open url to use correct servlet

- flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/pom.xml
Wrong version came from automatically merged cherry-picked PR https://github.com/vaadin/flow/pull/17648.
> test: fixed test module parent version number

- pom.xml
in order to publish to the vaadin-prereleases
> chore: update vaadin-parent for flow 2.10 [skip ci]

- vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringLookupInitializer.java
To avoid possibility to get ConcurrentModificationException.
Related to: https://github.com/vaadin/flow/pull/17604
> fix: synchronize cache maps in SpringLookupInitializer

- vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringLookupInitializer.java
For better non-blocking read-performance for lookups with SpringLookup.
Reload to: https://github.com/vaadin/flow/pull/17668
> chore: change synchronizedMap to ConcurrentHashMap

- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
In a production build, for every chunk the JS files are parsed to extract the imported paths. There are checks to ensure that a module is visited only once, but this works on a chunk level.
This change caches the JS imports extraction results, so that a single JS file is visited only once during the build.
Part of #17234
> chore: cache JS imported paths during chunk generation

- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Forward and reroute should run even when targeting same target but with different query parameters.
Fixes #17639
> fix: forward/reroute when query parameters changed

- flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/AbstractThemeEditorIT.java
- flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/ThemeEditorIT.java
The idea is:
1. before updating a property, get a timestamp
2. update the property
3. wait until the 'lastModifiedDate' attribute of the style sheet file is changed to a value after the timestamp
This way we make sure the vaadin dev server has written the properties to the file before we try to read them.
- [ X ] Bugfix
- [ X ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ X ] I have added a description following the guideline.
- [ X ] New and existing tests are passing locally with my change.
- [ X ] I have performed self-review and corrected misspellings.
> Fixes the flaky theme editor tests

- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/test/java/org/vaadin/example/SpringDevToolsReloadViewIT.java
- flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/test/java/org/vaadin/example/SpringDevToolsReloadViewIT.java
Adds `vaadin.test.reload-time-assert-threshold` system property for Vaadin reload time tests. When value is set, tests will fail if reload time result goes outside the threshold.
> test: add optional assert with reload time threshold

- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternalUpdater.java
- flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java
- flow-server/src/main/java/com/vaadin/flow/dom/Element.java
- flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
- flow-server/src/main/java/com/vaadin/flow/internal/change/NodeDetachChange.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
- flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java
Do not clean the node id or
hasAttached state too early as
then we do not send the detach
event for the node.
Fixes #17653
> fix: detach should be sent for node

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/Version.java
- flow-server/src/main/resources/com/vaadin/flow/server/version.properties
(cherry picked from commit 90245eee2280e43b2092fdfc503f326bcc4bc45d)
> fix: Use build timestamp for Push script request (#17706) (CP: 2.10)

- flow-tests/test-theme-editor/pom.xml
- flow-tests/test-theme-editor/src/main/java/com/vaadin/flow/uitest/ui/ThemeEditorView.java
- flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/ThemeEditorIT.java
- flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/testbench/DevToolsComponentPickerElement.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/CssRule.java
Adds a test for the editing of vaadin-accordion in theme-editor.
It is not possible to directly select the vaadin-accordion component directly by clicking on it, so the test is using the ComponentPicker component to navigate to the vaadin-accordion by using the keyboard.
This commit also contains:
-  a fix for a flakyness when a test tries to retrieve the CssRule related with a CssSelector
- normalization of the CssRule content inside the CssRule.equals(...) method.
- [ X ] Feature
- [ X ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ X ] I have added a description following the guideline.
- [ X ] I have added tests to ensure my change is effective and works as intended.
- [ X ] New and existing tests are passing locally with my …
> In theme-editor, adds a test for vaadin-accordion component

- flow-server/src/main/resources/vite.generated.ts
If you create a `src/main/resources/static/public` folder with static files, you will see a lot of
```
files in the public directory are served at the root path.
Instead of /public/images/logo.jpg, use /images/logo.jpg.
```
when trying to access the files. This is because the default "publcDir" of Vite is "public" and the Vite server is queried for resources before loading from the class loader
> fix: Disable the Vite public directory to not interfere with a folder named 'public'

- flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java
ServletDeployer performs several checks on servlet registrations to determine if the Vaadin Servlet must be registered automatically. However, as of servlet 3.0, <servlet-class> is optional in <servlet> declaration in web.xml, and in this case ServletDeployer fails with a NPE. With this change ServletDeployer ignores servlet registration without a servlet-class definition.
Fixes #17748
> fix: ignore servlet registrations without server-class definition

- flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/BundleLitParser.java
- flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/BundleLitParserTest.java
Changes regex in LitTemplateParser to find correct template content in case when lit template code contains "return html`" template also after the render function.
Fixes: #17721
> fix: improve LitTemplateParser to find correct content

- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
On windows at least the added
class can come in the format
com/example/application/Hello
in which case the cache throws a
IndexOutOfBounds exception for
the range [0, -1]
> fix: added class can be with /

- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/AdminView.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/RolePrefixedAdminView.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/AuthenticationUtil.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringViewAccessChecker.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinRolePrefixHolder.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Added `AuthenticationUtil#getSecurityHolderRoleChecker(String rolePrefix)` method that works now in same way as `SecurityContextHolderAwareRequestWrapper#isGranted(String role)`. Role prefix is set and read in `VaadinRolePrefixHolder` bean by `SpringViewAccessChecker#getRolesChecker(VaadinRequest)`.
Fixes: https://github.com/vaadin/flow/issues/17629
> fix: update role checkers to work in same way

- flow-tests/test-express-build/test-prod-bundle/src/main/java/com/vaadin/prodbundle/FakeAppConf.java
The test production bundle is using an older npm package version that may produce failure during Vite build.
This change updates the production bundle to use the correct version of vaadin npm package for testing.
> test: fix horizontal-layout npm package version

- flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/ComponentProperty.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/ComponentTest.java
Anchors in Vaadin are simply broken if the url happens to be relative. With this API that can be fixed.
Fixes #17617
> feature: provide an API to make router ignore an anchor

- flow-server/src/main/java/com/vaadin/flow/router/AfterNavigationEvent.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Adds a getter for `RouteParameters` in `AfterNavigationEvent`.
Fixes: #9993
> feat: add RouteParameters to AfterNavigationEvent

- flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/frontend/BrowserLoggingView.java
- flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/BrowserLoggingIT.java
- flow-tests/test-misc/frontend/consoleLoggingProxy.js
- flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/ExceptionLoggingIT.java
Could not find a way to hook into methods of `com.vaadin.client.Console` without exporting them to JS  which we do not want. So only debug, info and error level output is checked via known log messages.
> test: Add tests for dev mode client-side logging; Clarify prod mode test

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/editor/Editor.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/editor/AddComponentTest.java
- vaadin-dev-server/src/test/resources/com/vaadin/base/devserver/editor/inputs/EmptyViewWithSwitch.java
Fixes #17834  (issue)
Add the parser configuration in the Editor class to allow the switch expression to be parsed
> Fix the support for Java 17 (Theme editor)

- flow-server/src/main/java/com/vaadin/flow/dom/Node.java
- flow-server/src/main/java/com/vaadin/flow/dom/impl/AbstractNodeStateProvider.java
- flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Fixes the case where a component is readded
to the same parent and at the same time
in a detachListener removes components from
the parent.
Fixes #16741
> fix: readding component that on detach removes components

- flow-server/src/main/java/com/vaadin/flow/component/UI.java
Adds new public API for already existing features in `UIInternals`. `UI#getActiveViewLocation()` is shortcut to `UIInternals#getActiveViewLocation()` and `UI#getActiveRouterTargetsChain()` is shortcut to `UIInternals#getActiveRouterTargetsChain()`.
Fixes: #1894
> feat: add getActiveViewLocation and getActiveRouterTargetsChain to UI

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
This fixes the following bad formatted message (notice %n after globally):
```
======================================================================================================
Your installed 'npm' version (9.2.0) is known to have problems.
Please update to a new one either:
- by following the https://nodejs.org/en/download/ guide to install it globally%n  - or by updating your global npm installation with `npm install -g npm@latest`
- or by running the frontend-maven-plugin goal to install it in this project:
$ mvn com.github.eirslett:frontend-maven-plugin:1.10.0:install-node-and-npm -DnodeVersion="v20.8.0"
You can disable the version check using -Dvaadin.ignoreVersionChecks=true
====================================================================================================== …
```
> chore: fix typo when appending new line

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Allows to check whether specific binding has been changed. So far there is only a generic Binder#hasChanges, which checks all bindings. The new method allows to check whether a specific binding has changes.
Fixes #17395
> feat: Use binding object to check for Binder#hasChanges

- flow-server/src/main/java/com/vaadin/flow/router/internal/ConfiguredRoutes.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/ConfiguredRoutesTest.java
Specifically check Route annotation route 
first for match when going through templates.
Fixes #9969
> fix: RouteAlias hides Route value

- flow-client/pom.xml
- flow-data/pom.xml
- flow-dnd/pom.xml
- flow-html-components-testbench/pom.xml
- flow-html-components/pom.xml
- flow-lit-template/pom.xml
- flow-polymer-template/pom.xml
- flow-polymer2lit/pom.xml
- flow-push/pom.xml
- flow-server/pom.xml
- flow-test-generic/pom.xml
- flow-test-util/pom.xml
- flow-webpush/pom.xml
- vaadin-dev-server/pom.xml
The expression ${name} is deprecated. Please use ${project.name} instead
> chore: Fix Maven deprecation warning

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
@rollup/plugin-replace to 5.0.4
@rollup/pluginutils to 5.0.5
@vitejs/plugin-react to 4.1.0
vite to 4.5.0
vite-plugin-checker to 0.6.2
> chore: Bump npm dependencies

- flow-data/src/main/java/com/vaadin/flow/data/provider/Query.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Fix the query page and pageSize for
cases where the offset is not
equally divisible with the limit/pageSize.
Fixes #17750
> fix: page calculation when not equally divisible

- flow-data/src/main/java/com/vaadin/flow/data/provider/Query.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Fix the query page and pageSize for
cases where the offset is not
equally divisible with the limit/pageSize.
Fixes #17750
> fix: page calculation when not equally divisible (#17920)

- vaadin-dev-server/frontend/theme-editor/editor.ts
- vaadin-dev-server/frontend/vaadin-dev-tools.ts
Fixed ThemeEditor tracking to send markAsUsed only when user first time opens Theme Editor tab.
Fixed issues related to calling activate and deactivate methods on dev-tools plugins.
Fixes #17934
> fix: send markAsUsed only when Theme Editor is opened first time

- flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
Throw a WebPushException when
sending of notification fails.
Fixes #17942
> fix: throw WebPushException for sendNotification

- flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
- vaadin-dev-server/frontend/connection.ts
* Enable Atmosphere heartbeat and ignore it in devserver
* Set default WS idle timeout to 5 minutes
---------
> cp: Enable Atmosphere heartbeat (#17845) (24.2)

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendInputProperties.kt
To check if the prepare frontend task is up-to-date, the Flow gradle plugin also tracks the pnpm executable paths. However, getting the paths triggers the installation of pnpm, even if the tool is not enabled in configuaration.
This change only tracks pnpm paths if the tool is explicitly enabled.
Fixes #17967
> fix: prevent installing pnpm if not required

- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/TestUtils.kt
- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
Historically we have used the `vaadin { pnpmEnable = true }` stanza to test that the `vaadin{}` block works properly in the gradle build. However, the `pnpmEnable = true` may have unintended side-effects and may even fail the build, which is definitely not what the original purpose of the test was.
Therefore we have switched the property to `nodeAutoUpdate = true` which has little-to-no side-effect, and we have added an accompanied remark, clearly explaining the intended purpose of the test.
Also the unused `Path.deleteRecursively()` function is removed.
Doesn't fix any particular issue, it's just a chore.
> chore: gradle plugin test cleanup

- flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeValidationUtil.java
Fix the path when using
windows so that it matches
the stats file path.
Fixes #17998
> fix: path difference on windows

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
When not compressing the devBundle
skip writing of readme.md as folder
doesn't exist.
> fix: Do not try to write readme if no compression

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
- flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBuild.java
- flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Adds possibility to install the npm packages using npm ci instead of npm install (or for pnpm: pnpm install --frozen-lockfile) to install the exact versions in the lock file. Can be enabled with ci.build parameter when executing a production mode frontend build.
Fixes #15579
(cherry picked from commit 5607864ceefe46080aa2889078ee3081f2910979)
> feat: Enable running npm ci mode (CP: 23.4)

- flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
- flow-server/src/main/java/com/vaadin/flow/dom/Element.java
- flow-server/src/main/java/com/vaadin/flow/dom/ElementUtil.java
- flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
- flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
- flow-server/src/test/java/com/vaadin/flow/dom/ElementUtilTest.java
Improve error message when a component is moved from one UI to another.
Fixes #9376
> fix: improve error message when a component is moved from one UI to another.

- flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
StreamReceiverHandler understands `accept` property of the target element to block unwanted mime types. `accept` property takes comma separated list of mime types like 'text/plain, text/html'.
> fix: support accept property in StreamReceiverHandler

- flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Prevents unexpected situation in ComponentTest caused by the ComponenTracker.productionMode flag being initialized to true by some other tests.
In particular, cannotMoveComponentsToOtherUI test may fail because the exception message is different in development and production modes.
> test: reset ComponentTracker.productionMode static field

- pom.xml
the older version uses a wrong vaadin-prerelease target.
> chore: update vaadin-parent to 2.2.1

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
- flow-server/src/main/resources/plugins/rollup-plugin-postcss-lit-custom/rollup-plugin-postcss-lit.js
Vite 5 is based on Rollup v4. The major breaking change there is dropping support for Node < 18 which does not affect Flow. There might be other potential plugin issues though.
Vite 5 also drops support for accidentally importing styles twice, i.e.
```ts
import styles from 'hello.css'
```
To import styles and apply globally, you should do
```ts
import 'hello.css'
```
and to import styles as a string you need to do
```ts
import styles from 'hello.css?inline';
```
> chore!: Upgrade to Vite 5

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java
This should prevent issues when a Spring Boot application is restarted almost immediately after startup. Previously roughly this happened:
1. Start app
2. Start npm install
3. Restart app
4. Clean node_modules while npm install is still running
5. Fail
Now it should be
1. Start app
2. Start npm install
3. Restart app
4. Wait for npm install to finish
5. npm install finishes but might log some exception as the app was restarted
6. run node tasks including npm install from the restarted app
7. It should work
> fix: Do not run NodeTasks in parallel

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
In some cases, at least the `package.json` file is overwritten with the same content it already had. This causes the timestamp to be updated, which in some environments causes file fingerprint to differ. 
Fixes https://github.com/vaadin/flow/issues/17941
> Do not touch package.json files unless content has changed

- flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java
Prevents PWA test failures with Chrome 119 because of 'invalid argument: Empty userAgent invalid with userAgentMetadata provided'
> test: replace chrome mobile profile with custom settings

- flow-server/src/main/java/com/vaadin/flow/component/ClickNotifier.java
- flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShadowRootShortcutsWithValueChangeModeView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShortcutsView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShortcutsWithValueChangeModeView.java
Removes a call `setResetFocusOnActiveElement(true)` in `addClickShortcut` method in `ClickNotifier` to revert default behavior changes from https://github.com/vaadin/flow/pull/17826.
> fix: revert addClickShortcut to not reset focus by default

- flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
- flow-server/src/main/java/com/vaadin/flow/dom/Element.java
- flow-server/src/main/java/com/vaadin/flow/dom/ElementUtil.java
- flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
- flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
- flow-server/src/test/java/com/vaadin/flow/dom/ElementUtilTest.java
* feat: Add ElementUtil.from(StateNode) which returns Optional<Element>
Sister function for Element.get(StateNode), but returns an empty Optional instead of throwing an exception
* fix: improve error message when a component is moved from one UI to another.
Fixes #9376
* chore: mention both createLocation and attachLocation in the exception message
* chore: mention both createLocation and attachLocation in the exception message
* chore: minor fixes in messages
> fix: improve error message when a component is moved from one UI to another. (#18019) (CP: 24.1)

- flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/PwaHandlerTest.java
An IOException when writing a PWA icon on the HTTP response can neither be fixed nor handled and causes a lot of log spamming. This change catches the error and logs it at debug level.
Fixes #17643
> fix: prevent propagating IO errors when serving PWA icons

- flow-server/src/main/java/com/vaadin/flow/router/RouteAccessDeniedError.java
This makes `AccessDeniedException`'s default error page to work by default just like in the previous versions before `AccessDeniedException` even when `NotFoundException` is customized.
Fixes: #18082
> fix: reroute to NotFoundException from default RouteAccessDeniedError

- flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
- flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
- flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
- flow-server/src/test/java/com/vaadin/flow/server/ErrorHandlerUtilTest.java
Based on DX feedback, the default for https://github.com/vaadin/flow/pull/17791 is swapped to true.
> fix: Redirect to error view by default for errors in RPC-handling

- flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
- flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java
This reverts commit c73bbacd3b77eaa19b924ca113186877c2784352.
Reverted, because it leads to various regressions in components, e.g. for cases when `ComboBox` gets detached and re-attached and then contains no items (see `DataProviderIT::loadData_toggleAttached_correctItemsDisplayed` in flow components).
> Revert "fix: postpone commands scheduled with runWhenAttached for detached nodes (#18078)

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
It is faster and more correct.
Did not remove the old plugin as it is used in all existing projects and Flow would uninstall it if removed from here
> chore: install also react-plugin-swc

- flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
- flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
- flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/UIsCollectedWithBeaconAPIView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LocaleChangeIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/UIsCollectedWithBeaconAPIIT.java
- flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/routescope/PreserveOnRefreshIT.java
Notifies server about closed UIs using a beacon request on pagehide event.
At the same time unifies behaviour in certain edge cases, where Safari maintained the state when brought back from page cache. Previously Safari in some situations kept the state.
Tested manually with Safari, Chrome, Firefox and validated results using VisualVM.
Back ported from 24 to 23.4.
Closes #6293
> feat: More eager cleanup for UIs using Beacon API (#16657)

- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/resources/application.properties
- flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/main/resources/application.properties
Fixes slower reload times when run in CI due to connection errors with blocked host.
Related-To: vaadin/flow/pull/18079
> chore: allow all hosts for devmode performance tests

- flow-tests/test-live-reload-multimodule/ui/src/test/java/com/vaadin/flow/uitest/multimodule/ui/FrontendLiveReloadIT.java
FrontendLiveReloadIT.modifyThemeFile test updates a theme resource as a preliminary operation to have the expected initial setup. It then updates the same resource for testing purpose; however, if the two updates happens too fast, only one event is triggers by Vite reload, thus failing the test.
This change performs the initial write only if the actual content is not the expected one (may happen only on local tests, not on CI where there's ailway a fresh project clone).
Fixes #18053
> test: prevent write theme resource if content is not changed

- flow-server/src/main/java/com/vaadin/flow/component/ClickNotifier.java
- flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
- flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShadowRootShortcutsWithValueChangeModeView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShortcutsView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShortcutsWithValueChangeModeView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShadowRootShortcutsWithValueChangeModeIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShortcutsIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShortcutsWithValueChangeModeIT.java
Adds `setResetFocusOnActiveElement`, `resetFocusOnActiveElement` and `isResetFocusOnActiveElement` to `ShortcutRegistration` class to optionally reset focus on active element (focused element in browser). Resetting means calling `blur()` and `focus()` on the active element to ensure that input fields with `ValueChangeMode` `ON_CHANGE` will fire value change event before shortcut handler is run.
Back ported from Flow 24 for 23.4.
Fixes: https://github.com/vaadin/flow/issues/5959
> feat: reset focus on active element in ShortcutRegistration

- flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java
- flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
- flow-tests/test-frontend/vite-pwa-custom-offline-path/src/main/java/com/vaadin/viteapp/AppShell.java
- flow-tests/test-frontend/vite-pwa-custom-offline-path/src/main/java/com/vaadin/viteapp/MainView.java
- flow-tests/test-frontend/vite-pwa-disabled-offline/src/main/java/com/vaadin/viteapp/AppShell.java
- flow-tests/test-frontend/vite-pwa-disabled-offline/src/main/java/com/vaadin/viteapp/MainView.java
- flow-tests/test-frontend/vite-pwa-production/src/main/java/com/vaadin/viteapp/AppShell.java
- flow-tests/test-frontend/vite-pwa-production/src/main/java/com/vaadin/viteapp/MainView.java
- flow-tests/test-frontend/vite-pwa/src/main/java/com/vaadin/viteapp/AppShell.java
- flow-tests/test-frontend/vite-pwa/src/main/java/com/vaadin/viteapp/MainView.java
- flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/AppShell.java
- flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/FrontendLiveReloadView.java
- flow-tests/test-pwa-disabled-offline/src/main/java/com/vaadin/flow/pwatest/AppShell.java
- flow-tests/test-pwa-disabled-offline/src/main/java/com/vaadin/flow/pwatest/MainView.java
- flow-tests/test-pwa/src/main/java/com/vaadin/flow/pwatest/ui/AppShell.java
- flow-tests/test-pwa/src/main/java/com/vaadin/flow/pwatest/ui/ParentLayout.java
- flow-tests/test-pwa/src/main/java/com/vaadin/flow/pwatest/ui/PwaTestView.java
- flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
AppShellRegistry now rejects app shell class which extends Component.
Fixes #18012
> feat!: reject AppShell classes which extend Component

- flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
- flow-server/src/main/java/com/vaadin/flow/server/LockCheckStrategy.java
- flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/SessionLockCheckStrategy.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
- flow-server/src/test/java/com/vaadin/flow/server/AbstractDeploymentConfigurationTest.java
- flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
- flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/MockDeploymentConfiguration.java
Fixes for https://github.com/vaadin/flow/pull/18129 that was unfortunately merged too hastily.
Couple of changes:
* The LockCheckStrategy.DEFAULT was misleading since there are two defaults, one for production mode (assert), the other for development mode (throw).
* Renamed LockCheckStrategy to SessionLockCheckStrategy, to explicitly scope the lock to VaadinSession
* The init parameter got renamed to "productionSessionLockCheckStrategy", to explicitly mention that this is meant for a session lock which is only taken into account in production mode. However, this is a bit mouthful, perhaps sessionLockCheckStrategy would suffice? @mcollovati
> chore: improve session lock strategy

- flow-server/src/main/java/com/vaadin/flow/server/SessionLockCheckStrategy.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/MockLogger.java
Building on the https://github.com/vaadin/flow/pull/18175 PR, to my horror I realized that the stack trace is not logged by the SessionLockCheckStrategy.LOG strategy, which was the whole purpose of the original PR. Sorry about that; this PR makes sure the stacktrace is logged properly.
> refactoring: make SessionLockCheckStrategy.LOG log stack trace as well

- flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
- flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java
When detach listeners are called, the node still has a parent set, causing commands scheduled with runWhenAttached to be executed immediately. This change make runWhenAttached postpone the command by registering an attach listener, if called durint node detach.
Fixes vaadin/flow-components#1434
Fixes #18020
> fix: postpone commands scheduled with runWhenAttached for detached nodes

- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/AbstractDevServerRunnerTest.java
AbstractDevServerRunner serves dev mode request only when the waitFor task completes. The asynchronous completion of the internal devServerStartFuture may result in the test proceeding before the future is fulfilled, potentially causing failure due to the false return of 'serveDevModeRequest.'
This change waits for the future to complete, before proceeding with the test.
Fixes #18159
> test: wait for dev server start future completion

- flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleUtils.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleUtilsTest.java
BundleUtil computes import paths for component theme variants from npm packages, but it does not consider variants from JAR add-ons.
This change applies the same import rules for both variants from npm packages and JAR unpacked in the fronted generated folder.
Fixes #18245
> fix: consider theme variants from JAR in bundleImports

- CONTRIBUTING.md
Minor fix to docs to correct broken link
> docs: fix broken contributing link

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Update to v0.0.19, which supports Lit 3.
> chore: update @vaadin/common-frontend

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Update to v0.0.19, which supports Lit 3.
Co-authored-by: Zhe Sun <31067185+ZheSun88@users.noreply.github.com>
(cherry picked from commit 505b7973b766ed1ba57cac9d4cdd9b9d0b0d59d1)
> chore: update @vaadin/common-frontend (#18273)(CP: 24.3)

- flow-server/src/main/resources/vite.generated.ts
Running Vite currently results in the following warnings being logged:
```
2023-12-13T15:07:59.034+01:00  INFO 69460 --- [onPool-worker-3] c.v.b.devserver.AbstractDevServerRunner  : Running Vite to compile frontend resources. This may take a moment, please stand by...
2023-12-13T15:07:59.837+01:00  INFO 69460 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : plugin 'vaadin:force-remove-html-middleware' uses deprecated 'enforce' option. Use 'order' option instead.
2023-12-13T15:07:59.837+01:00  INFO 69460 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : plugin 'vaadin:force-remove-html-middleware' uses deprecated 'transform' option. Use 'handler' option instead.
2023-12-13T15:07:59.837+01:00  INFO 69460 --- [v-server-output] …
```
> chore: replace deprecated Vite config options

- flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReload.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/FragmentedMessageHolder.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/FragmentedMessageTest.java
- vaadin-dev-server/frontend/websocket-connection.ts
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
Without this, a message larger than 16KB will cause the connection to close instead of the message being delivered
> fix: Support fragmented messages in debug window

- .gitignore
Not sure if something is wrong with the tests they leave these I have at least
flow-tests/test-eager-bootstrap/.flow-node-tasks.lock
flow-tests/test-live-reload-multimodule/ui/.flow-node-tasks.lock
flow-tests/test-npm-only-features/test-npm-performance-regression/.flow-node-tasks.lock
flow-tests/test-redeployment-no-cache/.flow-node-tasks.lock
flow-tests/test-redeployment/.flow-node-tasks.lock
flow-tests/test-router-custom-context/.flow-node-tasks.lock
flow-tests/test-servlet/.flow-node-tasks.lock
flow-tests/test-themes/.flow-node-tasks.lock
> test: Ignore leftover lock files

- vaadin-dev-server/frontend/vaadin-dev-tools.ts
This seems to happen when from time to time, maybe because of dev tools being loaded on offline pages or something similar
> chore: Be more tolerant to dev tools conf not being available

- vaadin-dev-server/package.json
Breaking change between 5.0 and 4.0
The default origin is set to *, if you want to keep the 4.0 behavior, you can set the origin handler like this:
app.use(cors({
origin(ctx) {
return ctx.get('Origin') || '*';
},
}));
> chore: Upgrade @koa/cors

- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractLazyDataView.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataProviderWrapper.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java
Adds in `AbstractDataView` a better support for wrapper data providers that implements `DataProviderWrapper`. `AbstractDataView` won't throw exception anymore if wrapped data container is supported by the data view implementation. Adds public `getWrappedDataProvider` method in `DataProviderWrapper`.
Related-to: #18088
> feat: support DataProviderWrapper better in AbstractDataView

- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerViteTest.java
- flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractTestBenchTest.java
- flow-tests/test-express-build/test-embedding-express-build/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
- flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
- flow-tests/test-multi-war/deployment/src/test/java/com/vaadin/flow/multiwar/deployment/TwoAppsIT.java
When a Flow component is embedded as a web-component, the bootstrap process may fail if the dev-bundle is still under creation, because an HTML page is returned instead of the javascript initialization code. This change waits for dev-bundle to be ready before loading the web-components bootstrap script.
Fixes #18283
> fix: delay web-component bootstrap during dev-bundle creation

- flow-tests/test-frontend/vite-embedded-webcomponent-resync/pom.xml
- flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
If the button is not available on the page, the test immediately fails and stops the embedded server.
This change waits for the element to be available before clicking on it.
It also adds the websocket dependency to prevent PUSH initialization errors at startup
> test: prevent test flakyness by waiting for element

- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
Moved `getItemIndex(Object)` and `getItemIndex(Object, Stream)` methods from `AbstractListDataView` to `AbstractDataView`.
> chore: move getItemIndex to AbstractDataView

- flow-server/src/main/java/com/vaadin/flow/component/UI.java
- flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptNavigationStateRenderer.java
- flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
- flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
- flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
- flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
- flow-tests/pom.xml
- flow-tests/test-react-router/pom.xml
- flow-tests/test-react-router/src/main/java/com/vaadin/flow/StateView.java
- flow-tests/test-react-router/src/main/resources/vaadin-featureflags.properties
- flow-tests/test-react-router/src/test/java/com/vaadin/flow/StateIT.java
Only one request sent to the
server for flow navigation
so that the request contains
removals and adds in the same
query.
> fix: Single request navigation

- flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
- flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/TestEndpointGeneratorTaskFactory.java
- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/TestUtil.java
- flow-server/src/main/java/com/vaadin/flow/internal/hilla/EndpointRequestUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/Platform.java
- flow-server/src/test/java/com/vaadin/flow/server/PlatformTest.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeEndpointTest.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/TestEndpointGeneratorTaskFactory.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTest.java
- vaadin-dev-server/src/test/resources/java/MyEndpoint.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Hilla is undergoing a package renaming that affects some files in Flow. This PR makes the necessary changes.
Part of https://github.com/vaadin/hilla/issues/1904
> feat: rename `dev.hilla` to `com.vaadin.hilla`

- flow-server/src/main/java/com/vaadin/flow/component/ClickNotifier.java
Adds paragraph about `resetFocusOnActiveElement()` feature in `addClickShortcut` method.
Related-to: #5959
> docs: update ClickNotifier addClickShortcut JavaDoc

- pom.xml
This reverts commit 4d1b6f6b9655970392e7d79a155eb81fb2623ed0.
jackson-core 2.16.1 is a multiversion JAR with classes for Java 21. Unfortunately, this breaks builds with gradle less than 8.4, and the Flow declared minimum supported version for gradle is 7.6.
> revert: Revert "chore(deps): bump jackson.version from 2.16.0 to 2.16.1 (#18360)"

- flow-server/src/main/resources/vite.generated.ts
Includes `WebComponentExporter`'s generated web components under `frontend/generated/flow/web-components` in `frontendHashes` in `stats.json`, to make them properly detected for changes when building bundles.
Fixes: #18076
> fix: update stats.json for WebComponentExporter resources

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/types.d.ts.v1
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitionsTest.java
- flow-tests/test-ccdm/frontend/css-importing-test.ts
- flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/typescript/hello-world-view.ts
- flow-tests/test-themes/frontend/typescript/hello-world-view.ts
When importing styles in typescript sources, the import should contains the inline parameter (e.g. import styles from './some.css?inline'). The current module definition in types.d.ts does not handle the parameter, so TypeScript errors happen during build.
This change updates the definition in Flow default types.d.ts file and handles upgrade of existing files.
Fixes #18330
> fix: fix css module definition in typescript declaration file

- flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
- flow-server/src/test/java/com/vaadin/flow/ComponentTrackerLocationTest.java
ComponentTracker location fails to determine the source file for inner classes. This change tries to identify the enclosing class before matching with location filename.
Fixes #18216
> fix: handle inner classes in component tracker

- flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
- flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
- flow-server/src/test/java/com/vaadin/flow/ComponentTrackerTest.java
- flow-server/src/test/java/com/vaadin/flow/DisableComponentTrackerTest.java
- flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Adds a configuration parameter that allows developers to disable component tracking.
Fixes #18130
> feat: allow disable component tracker

- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Prevents JavaScript errors caused by dev-tools plug-ins attempting to register themselves when the development tools are disabled.
Fixes #18350
> fix: ignore plugins registration when dev-tools are disabled

- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
Test was failing because the devsoap plugin was not compatible with Gradle 7.6. Bump it to latest beta and adding a configuration workaround makes the test pass.
Fixes vaadin/multiplatform-runtime#117
> test: re-enable gradle MPR test

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
First line with import can be copy-pasted as is.
Feedback from DX test.
> chore: Easier copy-paste for no import message

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TypeScriptBootstrapModifier.java
This is needed to be able to import the correct version of components in an addon, e.g. if the application uses Material you will break the app if you import the Lumo version of vaadin-button
> feat: Pass theme definition to bootstrap modifiers

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorDataTest.java
Limits the number of requested items from backend to a given threshold of ten pages. Exactly the same as #12003, but applied to HierarchicalDataCommunicator.
Fixes #18403
> fix: limit the requested items to a given threshold

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorDataTest.java
Limits the number of requested items from backend to a given threshold of ten pages. Exactly the same as #12003, but applied to HierarchicalDataCommunicator.
Fixes #18403
> fix: limit the requested items to a given threshold (#18417)

- flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java
- flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
- flow-tests/vaadin-spring-tests/test-mvc-without-endpoints/src/main/resources/application.properties
- flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/src/main/resources/application.properties
- flow-tests/vaadin-spring-tests/test-spring-white-list/src/main/resources/application.properties
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Mark the existing methods as deprecated and introduce methods with new names. Fall back to the old configuration properties if the new ones aren't used.
Fixes vaadin/spring#645
> fix: replace 'blacklist' and 'whitelist' with 'blocked' and 'allowed' (#18405) (CP: 23.4)

- flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java
- flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
- flow-tests/vaadin-spring-tests/test-mvc-without-endpoints/src/main/resources/application.properties
- flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/src/main/resources/application.properties
- flow-tests/vaadin-spring-tests/test-spring-white-list/src/main/resources/application.properties
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Mark the existing methods as deprecated and introduce methods with new names. Fall back to the old configuration properties if the new ones aren't used.
Fixes vaadin/spring#645
> fix: replace 'blacklist' and 'whitelist' with 'blocked' and 'allowed' (#18405) (CP: 23.3)

- vaadin-dev-server/frontend/websocket-connection.ts
PushHandler expects that dev-tools connection to always use websocket transport. However, in case of client reconnection, atmosphere after a couple of attempts downgrades the transport to 'streaming', causing PushHandler to treat the connection as a Flow UI Push connection.
This change set 'websocket' also as atmospehere fallback transport, so all reconnection attempts will use the expected transport.
Fixes #18398
> fix: prevent dev-tools connection to downgrade to streaming transport

- flow-server/src/main/java/com/vaadin/flow/component/dependency/HtmlImport.java
- flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
Deprecates `@HtmlImport` and compatibility mode / bower mode
> Deprecate HtmlImport and Compatibility Mode

- flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
This change makes getSessionLockCheckStrategy a default method, returning ASSERT as the default lock strategy.
It prevents potential compilation issues in internal modules implementing DeploymentConfiguration for testing purposes that may run against different versions of Flow (e.g. MPR)
> chore: provide default session lock strategy

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
https://github.com/advisories/GHSA-c24v-8rfc-w8vw
> chore: upgrade to Vite 4.5.2 (24.2)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
https://github.com/advisories/GHSA-c24v-8rfc-w8vw
> chore: upgrade to vite 2.9.17 (9.2)

- flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
With Jetty 12, static resources retrieved via servlet context's `getResource(String)` may return non-null URL for non-existing resource. Jetty 11 returns null for non-existing resource. This change adds a double check for the static resource retrieved with the `getResource`, and returns null if it doesn't exist, to keep other parts work the same way as with Jetty 11.
This PR is tested manually. IT for executable JAR will be created in another task/PR.
Fixes: #18410
> fix: fix static resource retrieval with Jetty 12

- vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringSecurityAutoConfigurationTest.java
For parameters with Lazy annotation, Spring generates a not-serializable proxy. Since some security beans are used inside Flow listeners, they should be fully serializable (or defined transient, if possible).
This change removes the unnecessary Lazy annotaions, moving the lazy evaluation to VaadinWebSecurity.
Fixes #18458
> fix: remove Lazy annotation from Flow security beans

- flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Currently, when eagerServerLoad is active only parameters from query string are propagated to the route Location. If the Flow view is accessed through a multipart form POST request thg form values are suppressed.
With this change all request parameters are propagated to the view location object.
Fixes #17972
> fix: propagate all request parameter to location in eagerServerLoad mode

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
This should fix the TS compilation error in Hilla test module, saying
```
frontend/generated/flow/Flow.tsx(264,39): error TS2345: Argument of type 'readonly ViewRouteObject[]' is not assignable to parameter of type 'ViewRouteObject[]'. The type 'readonly ViewRouteObject[]' is 'readonly' and cannot be assigned to the mutable type 'ViewRouteObject[]'.
```
by converting an immutable routes array into mutable copy.
Related-to https://github.com/vaadin/hilla/pull/1990
> fix: Pass a mutable copy of routes array into React function

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Changes:
1. Once `Binder.handleFieldValueChange` runs for a binding when `readBean` was used, the whole binder will be silently validated also. `BinderValidationStatusHandler` is called like before (only contains status from changed binding), but `StatusChangeEvent` is now fired considering all bindings and if possible bean validators as well.
2. Once `Binder.handleFieldValueChange` runs for a binding when `setBean` was used, `doWriteIfValid` will validate all bindings, not only the changed ones. This prevents writing an invalid bean in cases where one or more of the initial values are in invalid state (but not marked as such since `setBean` resets validation status), but they have not been changed from their initial value(s).
3. Calling `setAsRequiredEnabled` with a changed value no …
> Validation fixes

- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
Add options object that can be
used to controll what is removed/cleaned
in the clean-frontend goal.
By deault everything is done.
> feat: make it possible to controll clean-frontend

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
Do not check for the
serverSideRoutes in
routes.tsx in react mode
if no `@Route` annotated
Flow routes found.
Fixes #18539
> fix: no serverSideRoutes check if no Routes

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java
If react is enabled for
add react-components to
package.json from
vaadin-versions.json and
vaadin-core-versions.json
else skip adding react npm packages.
Fixes #18506
> feat: add react components to package.json

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
Provides means to skip default validators of bound fields. Skipping can be done either for the Binder instance (skips all), or per-binding via BindingBuilder.
Fixes https://github.com/vaadin/flow/issues/17178
> Adds skipDefaultValidator API

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Add the loadComponentScript method
to Flow.tsx to be used when
WebComponents are loaded for
Hilla views.
part of #18401
> Feat: add loadComponentScript method

- flow-html-components/src/main/java/com/vaadin/flow/component/html/IFrame.java
- flow-html-components/src/main/java/com/vaadin/flow/component/html/Section.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/IFrameTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/SectionTest.java
> feat: Section and IFrame implements HasAriaLabel

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
This patch fixes a regression in Binder introduced by adding skipDefaultValidator API (https://github.com/vaadin/flow/pull/18549). This issue was missed since it seems to be impossible/difficult to trigger via unit testing using the mock field components in Flow project.
Affected flow-components tests:
[UpdateEditorComponentIT](https://github.com/vaadin/flow-components/blob/main/vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/UpdateEditorComponentIT.java#L34)
[DynamicEditorKBNavigationIT](https://github.com/vaadin/flow-components/blob/main/vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DynamicEditorKBNavigationIT.java#L37) …
> Fix regression NPE in binder

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
- flow-server/src/test/resources/com/vaadin/flow/server/frontend/dependencies/hilla/components/no-deps/package.json
If a package.json template cannot be found for any reason, Flow catches it and logs an error message.
> fix: Catch exceptions when package.json template doesn't exist

- vaadin-spring/src/main/java/com/vaadin/flow/spring/annotation/SpringComponent.java
Fixed Spring Boot's deprecation warning affecting SpringComponent. Relevant information about the motivation to deprecate convention-based naming: https://github.com/spring-projects/spring-framework/issues/31093
Fixes # ([18632](https://github.com/vaadin/flow/issues/18632))
> fix: Spring Boot's deprecation warning

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Rename default validator toggling API. Also fixes methods in binding to set/return `Boolean` instead of `boolean`.
> fix!: rename default validator api

- flow-server/src/main/resources/com/vaadin/flow/server/webcomponent/webcomponent-script-template.js
Delay the first poller call
for registerElement as if
we have already a live
client and the required method
react won't be fast enough
to set the attributes before
they are read.
Fixes #18645
> fix: delay initial poller call

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/types.d.ts
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitionsTest.java
Without this, it seems some linters/formatters will go and change types.d.ts to `import type` and then Flow will refuse to start
> chore: Use type Import in types.d.ts

- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/ConvertPolymerMojo.java
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FrontendDanceMojo.java
- flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
- flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/CleanFrontendMojoTest.java
Adds warnings when running clean-frontend, dance and convert-polymer goals if Hilla is used. Also skip cleanFrontendFiles for build-frontend goal if Hilla is used.
Related-to: #18567
> chore: update flow-maven-plugin goals for unified platform

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
- flow-data/src/test/java/com/vaadin/flow/tests/data/bean/Person.java
> feat: Add method to write only the changed properties to the bean

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
There is no value in seeing a lot of messages about denied connections if you e.g. leave browser tabs open. The warning is logged in the browser so you can understand why the connection is not working
> fix: Log debug connection issues as debug

- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateMavenBOMMojo.java
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojo.java
- flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- Change the lifecycle phase of sbom generator maven goals from `generate-resources` to `prepare-resources` so that it matches the `prepare-frontend` maven goal.
- Flip a boolean expression so that the `package.json` file is created if it doesn't exist when running the `prepare-frontend` maven goal.
> fix: change SBOM maven goals lifecycle phase

- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPlugin.kt
Close https://github.com/vaadin/platform/issues/5027.
Related to https://github.com/vaadin/flow/issues/18367.
> chore: upgrade minimum supported Gradle version to 8.4

- pom.xml
This is proposed to be applied to Vaadin 24.4 and we should update minimal requirement for Gradle from 7 to 8, see https://github.com/vaadin/flow/pull/18683.
> chore!: bump jackson.version from 2.16.0 to 2.16.1

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
When getting outside package json
files we should not log errors for
them if they are missing as they may
or may not be availabe.
Fixes vaadin/platform#5023
> fix: Possibly missing packages should not show error

- flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
Default production and development bundles are packaged with react router only. With this change, bundle is always rebuild if React is disabled and default bundle would be used otherwise. Rebuilding ensures that Vaadin router is used instead of the React router.
Fixes: #18656
> chore: rebuild bundle if React is disabled

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
If flow-react module is not
available do not add react-components
into package.json
Fixes #18676
> feat: Only add react-components with flow-react

- flow-data/src/main/java/com/vaadin/flow/data/provider/CallbackDataProvider.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/ConfigurableFilterDataProviderWrapper.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataProviderWrapper.java
When DataCommunicator flushes data and IndexOutOfBound exception can happen if data provider callbacks are not implemented properly. This change adds a log message that should help the user in debugging the cause of the error.
References #18541
> chore: log message when requested range does not match fetched items

- flow-tests/test-redeployment/pom.xml
- flow-tests/test-redeployment/src/test/java/com/vaadin/flow/uitest/ui/DevModeClassCacheIT.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Restores known root paths from cache after an application reload to correctly validate new resources.
Fixes #18730
> fix: fix cache resource validation on application reload

- .github/workflows/validation.yml
based on the changes in `upload-artifact@v4`, the artifacts are not mutable any more. 
so we took the way they have recommended in [docs](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#merging-multiple-artifacts) that 
- create and upload the artifacts separately with different names
- `test-output-it/unit-x`
- the separated artifacts will 
- download all artifacts to a temporary directory and reupload them as a single artifact `test-outputs` 
test result can be found https://github.com/vaadin/flow/actions/runs/7976167633?pr=18762
> chore: test new upload/download test result artifacts.

- flow-server/src/main/resources/vite.generated.ts
Vite's esbuild JSX output in production has some incompatibility with the Preact Signals library. As a workaround, this change applies JSX transformation provided by `@vitejs/plugin-react` in production mode.
Required by: https://github.com/vaadin/hilla/pull/2043
> fix: use Vite @vitejs/plugin-react also in production

- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Fixes and adds tests to ensure we don't get a regression like https://github.com/vaadin/flow/issues/18735.
Note to reviewer, if running these tests without [this patch](https://github.com/vaadin/flow/commit/76b862a8f6f962cdfbb370864a0c5a655693cd69), the following test failures should happen:
```
[ERROR]   BinderTest.two_asRequired_fields_without_initial_values_setBean:1582 Age field should not be in error, since it was not modified.
[ERROR]   BinderTest.validated_and_asRequired_fields_without_initial_values_setBean:1644 Last name field should not be in error, since it was not modified.
```
> test: Add/fix tests for binding cross-validation

- flow-server/src/main/resources/vite.generated.ts
- flow-tests/test-frontend/vite-basics/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
- flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BasicsIT.java
- flow-tests/test-frontend/vite-production/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
- flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/ProductionBasicsIT.java
- flow-tests/test-frontend/vite-test-assets/src/main/resources/META-INF/frontend/toplevelawait-main.js
- flow-tests/test-frontend/vite-test-assets/src/main/resources/META-INF/frontend/toplevelawait-other.js
> feat: Support top-level await

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
Both imports
- `import { serverSideRoutes } from "Frontend/generated/flow/Flow";`
- `import { serverSideRoutes } from "Frontend/generated/flow/Flow.js";`
are considered valid imports.
> fix: Add optional .js extension for Flow import

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/types.d.ts.hilla
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitionsTest.java
If types.d.ts contains content compatible with a common Hilla project then Flow will update it silently.
Fixes #18724
> fix: silently update types.d.ts in Hilla projects

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Doesn't use `this` reference directly to store a list of event listeners, but uses closures.
Calls the original `addEventListener` functions via `.call(this, arguments)` to avoid explosions due to `this` being `undefined`.
Fixes https://github.com/vaadin/flow/issues/18793
> fix: Use closures to store listeners and fallback to window

- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderConverterValidatorTest.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Currently some tests only check error message. Adds checks for expected validity state as well.
> test: check field validity in addition to errormsg

- pom.xml
- vaadin-spring/pom.xml
default spring-framework version coming with sb 2.7 is 5.3.31.  currently, we cannot find the date when next sb 2.7 will come. so let us use it this to resolve the cve
https://www.cve.org/CVERecord?id=CVE-2024-22243
> chore: upgrade spring framework to 5.3.32 (23.4)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/ExclusionFilter.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java
vaadin-*versions.json has "exclusions" array of npm dependencies that Flow will not add in the package.json if dependencies would be otherwise added via versions.json or NpmPackage annotations.
Fixes: #18684
> feat: support exclusions property in versions.json

- flow-tests/test-redeployment/src/test/java/com/vaadin/flow/uitest/ui/DevModeClassCacheIT.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/ReloadEvent.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Do Route scanning on packages of changed files also. Depending on the package/class structure, it some cases such change was not correctly scanned earlier.
Fixes #18794
> fix: also scan changed files for routes

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
When a field is bound multiple times, the previous bindings are removed from the Binder internal collection, but they are not unboud, leaving listeners attached to the field.
This change unbounds previous bindings when the field is bound again.
Fixes #18826
Fixes #18702
> fix: unbind previous binding for the same field

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FileIOUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
When reactEnable=false, TaskGenerateReactFiles removes routes.tsx. If routes.tsx doesn't match the default generated content, then a backup file is created.
Fixes: #18810
> fix: remove routes.tsx when React is disabled

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
If Flow doesn't it, these files leave in the generated folder and prevent a project to compile.
Have to be done automatically.
Related-to https://github.com/vaadin/flow/issues/18810
> fix: Remove also Flow.tsx and ReactAdapter.tsx on react=false

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
When a field is bound multiple times, the previous bindings are removed from the Binder internal collection, but they are not unboud, leaving listeners attached to the field.
This change unbounds previous bindings when the field is bound again.
Fixes #18826
Fixes #18702
> fix: unbind previous binding for the same field (#18833) (CP: 24.2)

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendOutputProperties.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPrepareFrontendTask.kt
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
> fix: Gradle frontend folder handling

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Check if the frontend folder
is absolute or not so that we
do not end up with a path like:
`C:\Users\user\example\C:\Users\user\example\.\frontend\generated/`
> fix: fix path depending on frontent folder

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
- flow-server/src/main/resources/vite.generated.ts
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateViteTest.java
- flow-server/src/test/resources/com/vaadin/flow/server/frontend/dependencies/hilla/components/react/package.json
Adds vitePluginFileSystemRouter to Vite plugins by default when React and Hilla is in use.
Fixes: #18832
> feat: add file system router plugin for vite

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/main/java/com/vaadin/flow/data/binder/BinderValidationStatus.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Fixes https://github.com/vaadin/flow/issues/18869
Adds missing test to confirm that setBean works as before.
> fix: fix setBean single binding write and add tests

- flow-react/src/main/resources/com/vaadin/flow/server/frontend/ReactAdapter.tsx
Fixes https://github.com/vaadin/flow/issues/18808 (partially)
> fix: move readonly keywords for better autocomplete

- flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeUtils.java
- flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/AbstractDevModeTest.java
Fixes frontend folder check
so that it is correctly gotten
from configuration even when no
buildInfo is available.
Fixs #18894
> fix: Frontend folder is always correctly checked

- flow-webpush/pom.xml
bump original dependency to latest version
> chore: remove jose4j workaround

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Update loadComponentScrip to use
a promise for the script onload
and onerror for better handling.
Update createWebComponent to take
onerror callback for script loading.
part of #18816
> feat: loadComponentScript returns promise

- flow-server/src/main/resources/com/vaadin/flow/router/NoRoutesError_dev.html
Update the message to present the options in a consistent way: in [language] with [framework(s)]
> Adjust message with no routes

- flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
> fix: revert path separator handling in StreamRequestHandler

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
Fix the plugin to use the
frontend folder instead of
frontendGenerated as the
actual files are not generated.
Fixes vaadin/hilla#2210
> fix: Gradle file system checks

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/index-react.tsx
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
Generate default routes.tsx in Frontend/generated folder instead of Frontend/. Imports to routes.js are now dynamic in Flow.ts and index-react.ts.
Fixes: #18871
> feat: generate routes.tsx in Frontend/generated

- flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
- flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
- flow-server/src/test/java/com/vaadin/flow/server/PropertyDeploymentConfigurationTest.java
Plugin mojo and task changes aren't covered as for some reason static mocking of endpoint utils doesn't work.
> test: Add tests for legacy frontend folder detection in app configuration

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Adds a feature flag for the new Hilla I18n API, which is considered experimental for v24.4.
> chore: add Hilla I18n API feature flag

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfigTest.java
- flow-server/src/test/resources/tsconfig-reference.json
Set the frontend path to tsconfig correctly for
the project depending on where it is found.
Fixes #18973
> fix: Generate tsconfig frontend path as in project.

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Fixes runtime issues when using pnpm >=8 and <= 8.6.12 for frontend build.
Fixes #18978
> chore: pin preset-react version

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfigTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitionsTest.java
Instead of updating and throwing
exception for 'tsconfig.json'.
Generate .bak file,
update file and log info if the
file is updated.
Fixes #18984
> Fix: update tsconfig and log message

- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
- flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksHillaTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksViteTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFilesTest.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
The prepare-frontend task run by build tool plugins and DevModeInitializer should produce the same output for dev-server settings.
Also deprecates and replaces methods whose name references webpack.
Part of #18907
> fix: make prepare-frontend and DevModeInitializer work consistently

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateSettingsFile.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateSettingsFileTest.java
Currently, TaskUpdateSettingsFile produces a json with different content depending if the task is executed by DevModeInitializer or by the build tool plugin (prepare-frontend).
With DevModeInitializer path are prepended with the project path, whereas with prepare-frontend they are not.
This change makes the tasks behave the same regardless of who is the caller.
Part of #18907
> fix: prepend npm folder to vaadin-dev-server setting paths

- flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
- flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java
> fix: prevent runWhenAttached command to execute immediately by detach listeners

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
Prevent writes on flow-build-info.json if there are no changes.
Part of #18907
> fix: prevent unecessary writes on flow-build-info.json

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/stateless/JwtSecurityContextRepository.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/stateless/SerializedJwtSplitCookieRepository.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/stateless/VaadinStatelessSecurityConfigurer.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/security/stateless/JwtStatelessAuthenticationTest.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/security/stateless/SerializedJwtSplitCookieRepositoryTest.java
Fixes stateless authentication, by updating the JWT cookies at every request, preventing the browser to remove the cookie after initial max-age time is expired.
Fixes https://github.com/vaadin/flow/issues/18895
> fix: update JWT cookie at every request

- flow-client/src/main/frontend/Flow.ts
- flow-server/src/main/java/com/vaadin/flow/component/UI.java
- flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptNavigationStateRenderer.java
- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
- flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
- flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
- flow-tests/test-react-router/src/main/frontend/ReactView.tsx
- flow-tests/test-react-router/src/main/frontend/routes.tsx
- flow-tests/test-react-router/src/main/java/com/vaadin/flow/NavigationView.java
- flow-tests/test-react-router/src/test/java/com/vaadin/flow/NavigationIT.java
Going back to Hilla view from
Flow view should not override
history so that forward button
also works to get "back" to Flow view.
Fixes #19003
> fix: forward/back navigation in hybrid app

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/OpenInCurrentIdeTest.java
Fix decision on file separator
character according to string
instead of OS.
Fix ide test to use same format
for file path.
Fixes #19046
> fix: path separator in vfs

- flow-server/src/main/java/com/vaadin/flow/router/AbstractRouteNotFoundError.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/ClientRoutesProvider.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/src/main/java/com/vaadin/flow/spring/test/TestServletInitializer.java
- flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/HillaRoutesRegisteredIT.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinApplicationConfiguration.java
Adds client views in the list of available routes when viewing "Route not found" page in development mode. Adds ClientRoutesProvider interface to get available client routes. Client routes means mainly Hilla views, but not limited to.
Fixes: #18857
> fix: show available client routes

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Return an empty list if no
listeners for type exist.
Fixes #19073
> fix: return empty list

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
Normalizes and replaces line separators potentially present in the process command line before writing the lock file, so that it will contain only two lines. Same normalization is applied when getting the command line for the process identified by the pid in the lock file before comparing it with the value stored in the lock file.
Fixes #19091
> fix: normalize and replace line separator in node task lock file

- flow-server/src/main/java/com/vaadin/flow/component/UI.java
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
- flow-tests/test-react-router/src/main/java/com/vaadin/flow/NavigationView.java
- flow-tests/test-react-router/src/test/java/com/vaadin/flow/NavigationIT.java
Fix mistaken add of query
parameters into the route
breaking route resolution
when navigating thrhough link.
fixes #19080
> fix: Query in path

- flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
- flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
HandlerHelper is currently not considering Flow PUSH requests (/VAADIN/push) as internal, preventing VaadinWebSecurity to ignore CSRF checks.
The issues happen only for ping requests; the connection request is not affected because it is a GET request.
Fixes #19075
> fix: detect Flow PUSH requests as internal framework requests

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/RequestUtil.java
During a hot reload, there may be requests incoming before VaadinService completes its intialization. In this situation, a NPE is thrown when trying to create WebIconsRequestMatcher.
This change postpones the instantiation until VaadinService is available.
Fixes #18965
> fix: postpone creation of WebIconsRequestMatcher

- flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Extend the test so that we test using
react-components-pro from the
vaadin-versions.json file.
Remove unused parameter.
part of vaadin/platform#5204
> test: Extend test to use vaadinVersions

- .github/ISSUE_TEMPLATE/bug_report.yaml
The discord chat is discontinued in favor of the new/old Vaadin forum, this change reflects that in the bug report template.
> Chore: Replace discord link with forum link in bug-report template

- flow-webpush/pom.xml
upgrade the dependency to resolve CVE: CVE-2024-29857, CVE-2024-30172, CVE-2024-30171
PR has been created to the original vulnerable dependency project.
```
-  dev.blanke.webpush.jwt:webpush-jwt-jose4j:jar:6.1.2:compile
|     +- dev.blanke.webpush:webpush:jar:6.1.1:compile
|     |  \- org.bouncycastle:bcprov-jdk18on:jar:1.76:compile
```
> fix: upgrade vulnerable dependency

- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/TranslationView.java
Resets the poll interval in the UI.access block so that the change is immediately pushed to the client and polling is stopped. Otherwise, the client will continue to poll until a UIDL request is sent the server.
> test: reset UI poll interval in UI.access block

- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Filter "com/vaadin/hilla" and "com/vaadin/copilot" packages by default from the class scanner in `VaadinServletContextInitializer` and include only what is really needed: `com.vaadin.copilot.startup` and `com.vaadin.hilla.startup`. This speeds up mostly reload time and also startup time a bit.
Related-to: #19112
> fix: filter hilla and copilot packages better

- flow-server/src/main/java/com/vaadin/flow/di/Instantiator.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/test/java/com/vaadin/flow/di/DefaultInstantiatorTest.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
- flow-tests/vaadin-spring-tests/test-spring-boot/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/test/TestServletInitializer.java
- flow-tests/vaadin-spring-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/test/ProxiedNavigationTarget.java
- flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/RouteBasicIT.java
- flow-tests/vaadin-spring-tests/test-spring/pom.xml
- vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/instantiator/SpringInstantiatorTest.java
AbstractNavigationStateRenderer.getRouteTarget filters the active router targets chain, comparing collection items class with the route target type. The filter may fail if routes instances are proxy objects created by frameworks like spring, since the class will not match the required one. This change ensures that synthetic and proxy classes are discarded, allowing for more accurate comparison when filtering objects based on their real application class.
Fixes #19100
> fix: unwrap router target class in getRouteTarget

- flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
Updates PushHandler to catch and log debug message of IllegalStateException from BrowserLiveReloadAccessor when it's thrown from already closed Spring context.
Fixes: #18835
> fix: handle exception from BrowserLiveReloadAccessor

- flow-server/src/main/java/com/vaadin/flow/router/Menu.java
Menu annotation has information like title, order and icon for automatically populated menu. Matches with ViewConfig menu API in Hilla.
Related-To: #19109
> feat: add Menu annotation

- flow-server/src/main/java/com/vaadin/flow/component/Component.java
Some Flow Components override `onAttach` or `onDetach` methods defined in `Component.java` for various purposes. Since the (inherited) Javadoc states that the default implementation does nothing, one might assume they can safely omit the call to `super.onAttach` / `super.onDetach` upon overriding the method in a component extension.
This PR modifies the Javadoc to remove the mention of default behavior and advises users to call the super method when overriding.
> [!NOTE] 
> Refactoring the components to use `addAttachListener` may not be feasible without causing a breaking change so we opted for updating the documentation instead.
Fixes https://github.com/vaadin/flow-components/issues/6189
Documentation
> docs: make onAttach docs advise a call to super method

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Update supported node version to 18.12, because pnpm 9.0.0-rc0 updated node requirement to 18.12.
Updates minimal supported pnpm version to 7 as older are semi-supported:
> chore: Upgrade minimal supported Node.js to v18.12

- flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
- flow-server/src/test/java/com/vaadin/flow/i18n/I18NUtilTest.java
OpenLiberty provides URL with a 'wsjar' protocol; Wildfly offers JBoss VFS URLs.
Fixes #19159
> fix: support OpenLiberty and Wildfly URL when listing translation files

- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/FrontendStubs.java
Fixes the failed test in https://github.com/vaadin/flow/pull/19188
> test: Update Node.js stub version

- flow-server/src/main/resources/vite.generated.ts
Only minify in production mode.
For development and devBundle builds
do not minify sources.
Fixes #19180
> fix: Only minify in production

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Makes it possible for Copilot to detect it without importing the file. Importing the file triggers the esbuild import order bug
> chore: Add type to FlowContainer

- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrowserWindowResizeIT.java
With latest chrome version, a small delay is needed before checking the resize listener effects.
> test: wait before checking size

- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrapTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
- flow-tests/test-embedding/test-embedding-application-theme/src/main/webapp/index.html
- flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
When using an exported a themed Flow web-component, Lumo style may leak the embedding document, causing invalid CSS rules to be applied. This change prevents applying Lumo global imports when the theme is applied to a web-component.
Fixes #12704
> fix: prevent embedded styles to leak main document (#19221) (CP: 23.5)

- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateSettingsFileTest.java
Wrap path string to get
same folder pathSeparator
as the system uses for the
temporary folder.
Fixes windows execution of test.
> test: Fix test path validation

- flow-data/src/test/java/com/vaadin/flow/data/binder/BeanPropertySetTest.java
- flow-server/src/main/java/com/vaadin/flow/internal/BeanUtil.java
Related to https://github.com/vaadin/flow/issues/16879
> feat: record support in beanpropertyset

- flow-server/src/main/java/com/vaadin/flow/internal/hilla/FileRouterRequestUtil.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/RequestUtil.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
This PR adds a check for Hilla routes so that developers (and our Start) do not have to do themselves.
As the check happens in a Spring bean, nothing changes if Hilla is not on the classpath, as the implementation will be added in Hilla.
> feat: add check for Hilla routes in VaadinWebSecurity

- flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/BrowserLauncher.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java
As we can not know if a tab
for the application is open
we add a file that is checked
for modification time and after
default 30 min we open a new tab on
server restart.
If server is restarted again before
timeout file timestamp is updated.
Clearing build folder will also
cause new tab to open on next restart.
Closes #18393
> feat: Open tab in dev mode less often

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
file-routes.ts is only generated by Hilla, thus routes.tsx should import it without extension.
> chore: Import file routes from ts file

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Navigation inside flow doesn't
happen when side-nav is used
as the link is marked as defaultPrevented
To have server update the site
allow link handling even if
default prevented for side-nav-item
Fixes #19272
> fix: Side-nav navigation ignored

- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrowserWindowResizeIT.java
With latest chrome version, a small delay is needed before checking the resize listener effects.
Forward port of #19243
> test: wait before checking size (#19243) (CP: 24.3)

- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/AbstractPropertyMap.java
- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
- flow-server/src/test/java/com/vaadin/flow/component/AbstractSinglePropertyFieldTest.java
- flow-server/src/test/java/com/vaadin/flow/component/PropertyDescriptorsTest.java
- flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMapTest.java
Removing element property by calling `com.vaadin.flow.internal.nodefeature.AbstractPropertyMap#removeProperty` does not trigger property change listener because of `com.vaadin.flow.internal.nodefeature.ElementPropertyMap#remove` method is skipped due to `AbstractPropertyMap#removeProperty` method calls super:
```
public void removeProperty(String name) {
super.remove(name);
}
```
Fixes #3994
> fix: make property change listener trigger on removeProperty

- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrap.java
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrapTest.java
When using an exported a themed Flow web-component, Lumo style may leak the embedding document, causing invalid CSS rules to be applied. This change prevents applying Lumo global imports when the theme is applied to a web-component.
Fixes #12704
Fixes #19265
> fix: prevent embedded styles to leak main document (#19274) (CP: 24.3)

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeStartupListener.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/DevModeHandlerStopTest.java
During the destruction of the web applicationi context, the DevModeStartupListener's context destroy listener is invoked. This listener attempts to locate the DevModeHandlerManager to halt the Vaadin dev-server. However, this process could trigger an exception if the dependency injection container behind the Lookup mechanism has already been stopped.
This commit addresses the issue by capturing a reference to the handler during web context start, eliminating the need for a lookup during destruction, thus preventing potential exceptions.
Fixes #19183
> fix: prevent exception getting DevModeHandlerManager on application shutdown

- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/AbstractPropertyMap.java
- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
- flow-server/src/test/java/com/vaadin/flow/component/AbstractSinglePropertyFieldTest.java
- flow-server/src/test/java/com/vaadin/flow/component/PropertyDescriptorsTest.java
- flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMapTest.java
This reverts commit 63e6dfd9b188ba35f895a259582a37ae071757b5.
The original fix for the property change event is correct per se, but, unfortunately, we faced an odd side effect in the RadioButtonGroup component that blocks our development process and would be a breaking change for RadioButtonGroup's users.
Here are some details: 
The `getValue()` method of the `RadioButtonGroup` (and probably other similar components, like `Select` and `CheckboxGroup`) returned an item that was set in `setValue()` before, even if it was an invalid item, e.g. it's key/id wasn't in the list of items for this component.
With this change, the `PropertyChangeEvent` is triggered, that causes `handlePropertyChange` and `hasValidValue` method to be called. `hasValidValue` doesn't properly check if the item is in …
> Revert "fix: make property change listener trigger on removeProperty (#19196)"

- flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeButtonElement.java
- pom.xml
Elements having their labels in their text (such as buttons) must implement a new, method-less interface `HasLabelAsText` in their element tester (such as `NativeButtonElement` for the `NativeButton` component and `ButtonElement` for the `Button` component) in order for the `withCaption[Containing]` selectors to work for them.
Related Flow change for https://github.com/vaadin/testbench/issues/1183
> feat: Add HasLabelAsText interface to NativeButtonElement

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketProxy.java
Sending multiple messages at the same time resulted in
```
java.lang.IllegalStateException: The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method
```
which originates in calling `browserSession.getAsyncRemote().sendText` a second time before the complete callback for the first call has been called.
Now the getBasicRemote() method is used instead which blocks until the message has been sent.
> fix: Fix failure when Vite sends many messages in sequence

- flow-client/src/main/frontend/FlowBootstrap.js
Reset and reload flow when a
template hrm reload happens.
Fixes #19291
> fix: reload flow after hmr reload in dev mode

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
- flow-server/src/test/java/com/vaadin/experimental/FeatureFlagsTest.java
A copy of https://github.com/vaadin/flow/pull/19049 patch, but with proper formatting.
Thanks @schastlivcev for contribution!
There was no indication if you were using non-existent or unsupported feature flags at startup. This change brings log warnings about existence of such feature flags.
Fixes #18672
> fix: add warnings for unsupported feature flags

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Rename the createWebComponent function
as the create gives the impression that
the function is heavy.
> fix!: rename createWebComponent method

- flow-server/src/main/java/com/vaadin/flow/router/Menu.java
- flow-server/src/main/java/com/vaadin/flow/router/MenuData.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/src/main/java/com/vaadin/flow/spring/flowsecurity/views/AdminView.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PrivateView.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PrivateView.java
Changing `Menu#order` type double and `MenuData#order` type to Double to match it with Hilla's `ViewConfig` type `number`.
Fixes: #19320
> fix: change type of Menu order to double

- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
`UIInternals#setTitle(String)` sets page title via JavaScript to `document.title` and optionally `window.Vaadin.documentTitleSignal.value` where documentTitleSignal is expected but not limited to be Signal<string> type with a value field. This allows Hilla main layout, when used, being kept in sync with the Flow page title even when set via PageTitle annotation or HasDynamicTitle interface.
Fixes: #19200
> fix: set page title to documentTitleSignal

- flow-tests/vaadin-spring-tests/pom.xml
Bumps `component.version` from 24.3.11 to 24.3.12.
Bump nimbus-jose-jwt to 9.37.3 to remove vulnerability
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
> chore(deps): bump component.version from 24.3.11 to 24.3.12 (#19364)

- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/ActiveUIsView.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/CustomServlet.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/PreserveOnRefreshView.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/UITrackerListener.java
- flow-tests/test-misc/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
- flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/PreserveOnRefreshCloseUIsIT.java
> fix: clear preseved chain cache for inactive UI

- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/ActiveUIsView.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/CustomServlet.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/PreserveOnRefreshView.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/UITrackerListener.java
- flow-tests/test-misc/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
- flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/PreserveOnRefreshCloseUIsIT.java
> fix: clear preseved chain cache for inactive UI (#19360) (CP: 24.3)

- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
- flow-tests/test-misc/pom.xml
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/ActiveUIsView.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/CustomServlet.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/PreserveOnRefreshView.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/UITrackerListener.java
- flow-tests/test-misc/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
- flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/PreserveOnRefreshCloseUIsIT.java
> fix: clear preseved chain cache for inactive UI (#19360) (CP: 23.5)

- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
- flow-tests/test-misc/pom.xml
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/ActiveUIsView.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/CustomServlet.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/PreserveOnRefreshView.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/UITrackerListener.java
- flow-tests/test-misc/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
- flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/PreserveOnRefreshCloseUIsIT.java
> fix: clear preseved chain cache for inactive UI (#19360) (CP: 23.4)

- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
- flow-tests/test-misc/pom.xml
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/ActiveUIsView.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/CustomServlet.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/PreserveOnRefreshView.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/UITrackerListener.java
- flow-tests/test-misc/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
- flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/PreserveOnRefreshCloseUIsIT.java
> fix: clear preseved chain cache for inactive UI (#19360) (CP: 23.3)

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Cherry-pick from #19380 to 24.4 to enable using the feature flag in Copilot.
> chore: add feature flag for Copilot I18n plugin (#19380)

- vaadin-dev-server/pom.xml
Adds the Dependencies manifest entry to the vaadin-dev-server artifact to prevent runtime errors raised by FileWatcher when application is deployed in Wildfly.
Fixes #17159
Fixes vaadin/skeleton-starter-flow-cdi#636
> fix: add explicit dependency to JDK classes in vaadin-dev-server

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketProxy.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnectionTest.java
It may happen that the thread that is createing ViteWebsocketConnection gets blocked when trying to create the internal websocket client, because a message from Vite server may be received and forwarded to the browser websocket before the websocket client creation future is completed, leaving the browser request thread pending indefinitely.
This change creates the websocket client asynchronously, but immediately closing the browser connection if the client connection cannote be established.
Fixes #19397
> fix: avoid blocking thread on ViteWebsocketConnection creation

- flow-jandex/pom.xml
This reverts commit 0b914395da091ee7302baaefc4dd1bd4338165e7.
Jandex 3.2.0 will be supported in Quarkus 3.12.
> Revert "chore(deps): bump io.smallrye:jandex-maven-plugin from 3.1.8 to 3.2.0 (#19407)"

- pom.xml
This reverts commit e8ee22a43d0c9ed62c395db7117ae99262534eae.
jakarta.validation-api is part of Jakarta EE 11, should not be bumped right now
> Revert "chore(deps): bump jakarta.validation:jakarta.validation-api from 3.0.2 to 3.1.0 (#19426)

- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
If the project does not define the frontendHotdeploy property, the Flow maven plugins try to detect the correct value by analysing project files and looking for Hilla presence by checking for its classes in classpath. However, when FrontendUtils.isHillaUsed() method is called from the maven mojo it can return a wrong value, since Class.forName check is performed using the plugin classloader that does not contain Hilla artifacts.
This change makes the mojo isFrontendHotdeploy() method using the project classpath to check for Hilla presence.
> fix: use maven project classpath to detect Hilla presence

- flow-server/src/main/java/com/vaadin/flow/i18n/I18NProvider.java
- flow-server/src/main/java/com/vaadin/flow/internal/LocaleUtil.java
- flow-server/src/test/java/com/vaadin/flow/i18n/DefaultInstantiatorI18NTest.java
- flow-server/src/test/java/com/vaadin/flow/server/I18NProviderTest.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/TranslationView.java
- flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/TranslationIT.java
Adds static `I18NProvider#translate` methods for alternative way to get translation. Compares to calling getTranslation via `VaadinService.getCurrent().getInstantiator().getI18NProvider()`. `translate` methods throws IllegalStateException without active VaadinService.
Fixes: #19333
> feat: add alternative translate methods to I18NProvider

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/main/java/com/vaadin/flow/data/binder/RequiredFieldConfiguratorUtil.java
- flow-data/src/main/java/com/vaadin/flow/data/binder/ValueContext.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/ValueContextTest.java
original authors: @archiecobbs and @mstahv
Minor fixes to contribution PR: https://github.com/vaadin/flow/pull/19131
> feat: add ValueContext.getBinder()

- flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
Workaround for MPR & resynchronization being broken. If MPR is detected, a full page reload will be forced when resynchronization is requested.
Fixes https://github.com/vaadin/multiplatform-runtime/issues/133
> fix: force page reload on re-sync with MPR

- flow-server/src/main/java/com/vaadin/flow/component/UI.java
- flow-server/src/main/java/com/vaadin/flow/component/page/History.java
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes-flow.tsx
- flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
- flow-server/src/test/java/com/vaadin/flow/component/page/HistoryTest.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/HistoryView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PopStateHandlerView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/HistoryIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PopStateHandlerIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PostponeUpdateIT.java
When pushing or replacing history
send a custom event 'vaadin-navigate'
instead of popstate event.
Fixes #19513
> fix: do not use popstate event

- flow-react/src/main/resources/com/vaadin/flow/server/frontend/ReactAdapter.template
this was removed in https://github.com/vaadin/flow/pull/19434 (maybe accidentally? )
> fix: Add usage stats for react adapter

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
- flow-tests/test-react-router/src/main/java/com/vaadin/flow/NavigationView.java
- flow-tests/test-react-router/src/main/java/com/vaadin/flow/ServerView.java
- flow-tests/test-react-router/src/test/java/com/vaadin/flow/NavigationIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/HistoryIT.java
> fix: preserve navigated.current value

- flow-tests/vaadin-spring-tests/pom.xml
Bumps `component.version` from 24.3.13 to 24.4.2.
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
> chore(deps): bump component.version from 24.3.13 to 24.4.2 (#19581)

- flow-server/src/main/resources/vite.generated.ts
Related-to https://github.com/vaadin/platform/issues/6488
> fix: Preserve usage stats for hot deploy mode as well

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Add the navigationEventHandler
to window to be able to handle
link clicks into dialogs that
are outside of the container element.
Fixes #19630
> fix: handle clicks outside container

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
- flow-server/src/main/resources/plugins/react-function-location-plugin/react-function-location-plugin.js
- flow-server/src/main/resources/vite.generated.ts
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
This is to be able to remove usage of installAutoSignalTracking in Hilla, which will not work with React 19, as stated in https://github.com/preactjs/signals/issues/576
> fix: Use @preact/signals-react-transform

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes-flow.tsx
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/vaadin-react.tsx
Instead of importing `routes.js/routes.ts/routes.tsx` from the project into `Flow.tsx` and creating a circular dependency, this moves importing of `routes.js` to a new file that is always included when react is used `vaadin-react.tsx`. This file publishes the routes as `window.Vaadin.routesConfig` so that `Flow.tsx` can read them from there without directly depending on `routes.js`
Fixes #19658
> fix: Pass route data through window.Vaadin.routesConfig instead of an import

- flow-tests/test-pwa/pom.xml
Fixes nightly test using chrome 123.
Change should be removed once CI environments upgrades to chrome 124 or
newer.
> test: fix pwa nightly test

- flow-data/src/main/java/com/vaadin/flow/data/binder/ValueContext.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractComponentDataGenerator.java
- flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java
- flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
- flow-server/src/main/java/com/vaadin/flow/component/UI.java
Component.getUI() is potentially expensive operation, especially in complex UIs with deep component tree, since it traverses up to the root component. (Identified by profiling large application).
Do not unnecessarily invoke it multiple times like getUI().isPresent() + getUI().get(), but rather use local variable to avoid repeated component tree traversals.
> refactor: Avoid duplicate invocations of Component:getUI

- flow-server/src/test/java/com/vaadin/flow/i18n/DefaultInstantiatorI18NTest.java
- flow-server/src/test/java/com/vaadin/flow/i18n/TranslationFileRequestHandlerTest.java
Mockito recommend against mocking static methods of classes in the standard library. In several builds static mocking on Locale.getDefault() causes a stack overflow during test execution, that seems to happen depending on the tests execution order. This change removes the usage of static mock, replacing it with simple calls to Locale.setDefault to change and restore the default locale.
> test: remove static mock for Locale class

- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshNavigationView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshNavigationIT.java
Programmatic self navigation with query parameters on view with preserve on refresh do not update the URL in the browser.
This change fixes the regression introduced by #15331, updating push history also for navigation events with trigger REFRESH.
Fixes #19701
> fix: update browser URL on preserve on refresh navigation

- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
Wraps the annotation finder function to log potential errors during class scanning and the class that originates the failure.
References #19616
> chore: log class causing failure in frontend dependency scan

- flow-server/src/main/java/com/vaadin/flow/component/UI.java
- flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
- flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReload.java
- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementListenerMap.java
- flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
- vaadin-dev-server/src/main/frontend/live-reload-connection.ts
- vaadin-dev-server/src/main/frontend/vaadin-dev-tools.ts
- vaadin-dev-server/src/main/frontend/websocket-connection.ts
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
Uses the dev-tools web socket connection to refresh the UI when PUSH is not available, instead of forcing a page reload.
> feat: refresh browser using dev-tools connection

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/NavigationEventsView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/NavigationEventsIT.java
Lets navigation cause server round-trip, when navigation is triggered by clicking a link.
Fixes https://github.com/vaadin/flow/issues/19635
> fix: do not block navigation to current url

- flow-tests/test-pwa/pom-production.xml
Fixes nightly test using chrome 123.
Change should be removed once CI environments upgrades to chrome 124 or newer.
Same as in #19674
> test: fix pwa production nightly test

- flow-server/src/main/java/com/vaadin/flow/router/AbstractRouteNotFoundError.java
Make the client route string
on the error page in dev mode
not start with / so it is the
same as for server-side routes.
Fixes #19182
> fix: Unify client route to match server route format

- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
- flow-server/src/main/resources/META-INF/frontend/theme-util.js
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithByteCodeScannerTest.java
- flow-tests/test-embedding/test-embedding-application-theme/frontend/css-import-component.css
- flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/embedded-theme/theme.json
- flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/CssImportComponent.java
- flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/ThemedComponent.java
- flow-tests/test-embedding/test-embedding-application-theme/src/main/webapp/index.html
- flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
CssImport annotation with just a value attribute can be injected automatically to shadow root of all exported web components (embedded applications) using Constructable StyleSheets. WebComponentExporter should have a theme to make automation work properly in theme-generator.js. Theme property "autoInjectGlobalCssImports": true in theme.json enable auto injection. Disabled by default.
Fixes: #19700
> fix: apply CssImport to exported webcomponent (#19740) (CP: 24.3)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
Always generate the routes.tsx
into frontend/generated. Even
when routes.tsx is defined in
frontend by the developer so
that it can be used as an example.
Fixes #19179
> fix: always generate routes.tsx

- .gitignore
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
Rename the flow-node-tasks
lock file to vaadin-node-tasks
so it doesn't confuse application
state when running a non flow
build.
Closes #19187
> fix: rename lock file

- flow-server/src/main/java/com/vaadin/flow/component/page/History.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
- flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
- flow-server/src/test/java/com/vaadin/flow/component/page/HistoryTest.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/HistoryIT.java
Add feature to support replace and
push without getting a callback
to the server for the change.
fixes #19613
> feat: push and replace without navigation callback

- flow-server/src/main/java/com/vaadin/flow/server/dau/DAUUtils.java
- flow-server/src/test/java/com/vaadin/flow/server/dau/DAUUtilsTest.java
Needed for integrating DAU tracking with HTTP Servlet Request outside of normal VaadinService request handling context, like Hilla endpoint controller.
> chore: add utility method for DAU tracking

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/utils/LookupImpl.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/utils/ResourceProviderImpl.java
- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
Fixes vaadin/hilla#2637
ResourceProvider ignored the actual project's resources when using the default ClassLoader. This resulted in loading `vaadin-featureflags.properties` from the vaadin-dev-bundle jar, even though there is a file in the project.
> fix: use URLClassLoader with ResourceProvider in Maven plugins

- flow-data/src/main/java/com/vaadin/flow/data/binder/BeanPropertySet.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BeanPropertySetTest.java
Until now, bean properties have not been ordered by Flow. Instead they have been ordered by components using the property set, e.g. Grid. Now that we support records, we'd like to maintain original definition ordering for record props, but do sorting for bean props (since for beans you can't get the definition order).
This PR makes `BeanPropertySet` differentiate the two cases and return an ordered stream of properties for beans only.
> fix: preserve record prop order, sort for beans

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/utils/LookupImpl.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/utils/ResourceProviderImpl.java
- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
Fixes vaadin/hilla#2637
ResourceProvider ignored the actual project's resources when using the default ClassLoader. This resulted in loading `vaadin-featureflags.properties` from the vaadin-dev-bundle jar, even though there is a file in the project.
> fix: use URLClassLoader with ResourceProvider in Maven plugins (#19781)

- flow-server/src/main/java/com/vaadin/flow/server/dau/DAUUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/dau/DAUVaadinRequestInterceptor.java
- flow-server/src/main/java/com/vaadin/flow/server/dau/FlowDauIntegration.java
- flow-server/src/test/java/com/vaadin/flow/server/dau/DAUVaadinRequestInterceptorTest.java
Blocks new requests immediately, if:
- DAU tracking is enabled,
- enforcement is ON,
- remaining limit is <=0
Depends on https://github.com/vaadin/flow/pull/19820
> fix: block new users immediately when enforcement=ON

- flow-html-components/src/main/java/com/vaadin/flow/component/html/FieldSet.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/FieldSetTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
Java API to create a <fieldset> and <legend> html tag without using a custom Java class to group fields.
Fixes #18213
> Create Fieldset - Legend Java API

- vaadin-spring/src/main/java/com/vaadin/flow/spring/DevModeBrowserLauncher.java
> fix: Use 8080 as the default launch port for opening the browser

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
Do not add the outlet
file if react is not
enabled as the required
react node files are not
available.
Fixes #19842
Fixes vaadin/start#3159
> fix: React file not added when reactEnabled false

- flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
The reactEnable flag should be
automatically corrected to
false if vaadin router is used
instead of react router.
> Options should correct the reactEnable flag

- flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
- flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
ServletConfig might contain init parameter with null values. This is however not supported by java Properties class.
This change adds a null check and logs offending keys for debugging purpose.
Fixes #19855
> fix: prevent NPE when creating init parameters

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Follow up from https://github.com/vaadin/copilot-internal/pull/2972. Feature flag won't be needed in V24.5.
> chore: remove Copilot I18n feature flag

- flow-tests/pom.xml
Temporarily pin selenium devtools to a version compatible with chrome
128. This workaround should be removed after TB 9.2.8 is released.
> test: pin selenium devtools version compatible with chrome 128 (24.3)

- flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
- flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
- flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/routescope/PreserveOnRefreshIT.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
ServletConfig might contain init parameter with null values. This is however not supported by java Properties class.
This change adds a null check and logs offending keys for debugging purpose.
Fixes #19855
> fix: prevent NPE when creating init parameters (#19856) (CP: 23.5)

- flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
- flow-server/src/test/java/com/vaadin/flow/server/menu/MenuRegistryTest.java
`MenuRegistry.filterClientViews` removes inaccessible routes and their child routes from the menu items. When iterating the list of all routes, a NPE can occur if a child route has already been removed together with its parent route. This adds a check that prevents the NPE.
> fix: safely handle nested removal of menu routes

- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullScannerPwaTest.java
Remove reactOutlet module
if we are not running react,
but are using Vaadin Router
inferred from index.ts
Fixes #19870
> fix: No react module for Vaadin Router

- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
Prevents Flow navigation actions for cases where a client route exists and is navigated to, but there is also a Flow route with a parameter that could potentially match the target URL.
Fixes https://github.com/vaadin/flow/issues/19831
> fix: prevent Flow navigation for Hilla route

- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrowserWindowResizeIT.java
Waits for the browser resize event listener to update the UI before asserting on the window width.
> test: assert after browser resize event listener completes (2.11)

- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
Using instantiator instead of directly calling Lookup allows CDI and Quarkus projects to expose the implementation as a bean instead of registering it as a ServiceLoder component.
> fix: use instantiator to lookup DAUCustomizer implementation

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyLocalFrontendFiles.java
Allows to skip setting the writable flag on copied files, by providing the vaadin.frontend.disableWritableFlagCheckOnCopy system property.
This may improve performance in certain scenarios with Windows OS.
Fixes #19866
> feat: Add option to not modify readonly files during copy, add logging of time

- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
NodeInstall.getVersion currently does not block waiting for STDOUT and STDERR to be read completely. This causes random failure during node installation because of forcing an empty version.
This change waits for future to complete before parsing the version value.
> fix: wait for output reading to complete before parsing version

- flow-jandex/pom.xml
Makes all flow-jandex dependencies provided scoped to prevent optional adding transitive dependencies on the user project. Also removes optional dependencies that might not be automatically added by Vaadin (e.g. polymer templates) or excluded by the user project (e.g. vaadin-dev-server).
Part of vaadin/quarkus#158
> chore: prevent jandex artifact to import transitive dependencies

- flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactoryTest.java
This adds missing codes into app configuration factory that propagates the PREMIUM_FEATURES flag value from token file to app config. This value can be retrieved from deployment configuration in runtime.
Related-to https://github.com/vaadin/flow/pull/19846
> fix: Propagate Premium Features flag value to configuration

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeStartupListener.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeClassFinderTest.java
Genrate a layout.json for
Hilla to automatically
enable server layouts
part of vaadin/hilla#2709
> feat: generate layout.json

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
For deciding what action to
take we should evaluate where
we are going and not the current
active path.
Fixes vaadin/hilla#2726
> fix: Evaluate target not active

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
The pre-compiled production bundle comes with true value of this flag always, because Vaadin CI server has a sub that enables it. Thus, Flow need to reset this flag before it calls the license server.
> fix: Reset the Premium Features flag before license checking

- flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
- flow-server/src/test/java/com/vaadin/flow/server/menu/MenuRegistryTest.java
> feat: add collectMenuItemsList() to MenuRegistry

- flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java
- flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java
- flow-tests/test-react-router/src/main/java/com/vaadin/flow/ForwardTargetView.java
- flow-tests/test-react-router/src/main/java/com/vaadin/flow/ForwardTargetWithParametersView.java
- flow-tests/test-react-router/src/main/java/com/vaadin/flow/ForwardingToParametersView.java
- flow-tests/test-react-router/src/main/java/com/vaadin/flow/ForwardingView.java
- flow-tests/test-react-router/src/test/java/com/vaadin/flow/ForwardTargetIT.java
Fixes https://github.com/vaadin/flow/issues/19794
Fixes https://github.com/vaadin/flow/issues/19822
Also fixes https://github.com/vaadin/flow/issues/19813 in a more coherent way. Relevant test is `com.vaadin.flow.uitest.ui.PreserveOnRefreshForwardingIT`
> fix: forward with optional callback

- flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializerTest.java
Currently, if a view defines `@Route` and `@RouteAlias` with the same path, the alias is rejected at startup, but there is no evidence of the error.
However, when hot swap is enabled and the view class is reloaded, an exception is thrown.
This change adds an explicit check for duplicate paths, preventing the application from starting if the configuration is invalid.
Fixes #19972
> fix: fail fast if view defines same path for route and route alias

- flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
- flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
VaadinSession references are registered in Hotswapper in a session init listener. However, the listener might not always been invoked, for example if the HTTP session is serialized and deserialized on server restart. This change registers a UI init listener to make sure VaadinSession reference is also registered for existing sessions.
Fixes #19973
> fix: ensure session is registered with Hotswapper

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Close the overlay drawer
even when clicking on
same link and no actual
navigation happens.
Fixes #19823
> fix: close overlay drawer on click

- flow-server/src/test/java/com/vaadin/flow/ComponentTrackerTest.java
On CI systems the test randomly fails because the GC seems not to clean up ComponentLocator memory within the 5 milliseconds. However, running the test in isolation works fine. This change increases the delay between the GC requests to try to make the test more reliable.
> test: increase sleep time to allow GC to perform cleanup

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Node 22 will become LTS well before the 24.6 release
> chore: Node 22.9.0

- flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
Make log more detailed for
ignored invocation handle.
> chore: More detailed logging for ignored handling

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/controlcenter/starter/actuate/endpoint/VaadinActuatorEndpoint.java
- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
Changes production build info to validate Control Center feature only when VaadinActuatorEndpoint is in the class path. Class will be included with `control-center-starter` Vaadin platform dependency.
Fixes: #20013
> fix: Validate Control Center feature when used

- flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBuild.java
In a DAU build, checks if license-checker will be present at runtime and prints a warning message with instructions to fix the configuration if the dependency is missing.
> chore: show warning when LC is missing in a DAU build

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Ensures that root output element added for React router in Flow.tsx doesn't accidentally change the main layout with CSS rules targeting it.
Fixes: #19871
> fix: hide root output element

- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PageIT.java
Update the page title after
navigation has ended to
not have the wrong title in
history.
Fixes #19868
> fix: update title after navigation

- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
Layout annotated classes should be
collected as entrypoints for
production builds.
Fixes #20074
> fix: Layout should be collected as entyrpoint

- flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandlerManager.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerManagerImpl.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/DevModeHandlerStopTest.java
Sync file watcher should be closed on context shut down so adding watchers to dev tools logical since it handles that 
> chore: Add possibility to register shutdown commands for development mode

- vaadin-spring/src/main/java/com/vaadin/flow/spring/ReloadCache.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Store layout packages
in development mode reload
cache as layouts may not be
in same packages as routes.
Fixes #20066
> fix: Store layout packages

- flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
- flow-server/src/test/java/com/vaadin/flow/ComponentTrackerLocationTest.java
Checks if Java file is de facto Kotlin file and uses proper source directory
Fixes https://github.com/vaadin/copilot/issues/30
> feat: ComponentTracker file location of Kotlin files

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendInputProperties.kt
Prior to this fix, the settings declared in Gradle were not being passed to the plugin. For example, changing the nodeVersion in build.gradle did not update the actual nodeVersion used.
Fixes [# (issue)](https://github.com/vaadin/flow/issues/20058)
There are no existed tests for this part of code. You can review code execution flow for review this changes.
> fix: add nodeVersion in gradle plugin settings

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/UidlRedirectStrategy.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSimpleUrlLogoutSuccessHandler.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/security/AuthenticationContextTest.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinWebSecurityTest.java
Don't throw NullPointerException in case of null VaadinServletResponse in AuthenticationContext#logout.
Fixes: #20017
> fix: allow null response in logout

- flow-plugins/flow-gradle-plugin/README.md
- flow-plugins/flow-gradle-plugin/build.gradle
- flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/TestUtils.kt
- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPlugin.kt
Jackson 2.18 is incompatible with Gradle 8.4 because it contains classes compiled with Java 22.
This change bumps Gradle minimum supported version to 8.7 that supports Java 22.
> chore!: upgrade minimum supported Gradle version to 8.7

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/UidlRedirectStrategy.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSimpleUrlLogoutSuccessHandler.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/security/AuthenticationContextTest.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinWebSecurityTest.java
Don't throw NullPointerException in case of null VaadinServletResponse in AuthenticationContext#logout. Tolerate null response better in case when running with @Push(transport = Transport.WEBSOCKET), or when response is null for some other reason. Makes logout also work in WEBSOCKET mode by automatically switching to WEBSOCKET_XHR for one additional request that executes logout.
Fixes: #20017
> fix: allow null response in logout (#20057) (CP: 24.3)

- flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializerTest.java
> fix: consider layout prefixes when checkin for route and alias paths

- flow-server/src/main/java/com/vaadin/flow/component/UI.java
- flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptNavigationStateRenderer.java
- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/main/java/com/vaadin/flow/component/page/History.java
- flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
- flow-server/src/test/java/com/vaadin/flow/component/page/HistoryTest.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
- flow-tests/test-react-router/src/main/java/com/vaadin/flow/StateView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PopStateHandlerView.java
`reactEnabled` value might have been stored in session store so we can't trust that - this patch makes Flow always fetch it from `VaadinService`
Most likely fixes https://github.com/vaadin/flow/issues/20077
> fix: always fetch reactEnabled from service

- flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DragSource.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DnDView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DnDIT.java
Postpone moment when virtual child element is created and added to allow setting non-attached drag source itself as a drag image.
RelatedTo: #6793
> chore: append drag image on attach

- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
- flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
- flow-server/src/test/java/com/vaadin/flow/server/menu/MenuRegistryTest.java
Create always MenuData in `AvailableViewInfo.menu` to avoid need for extra null checking in automatic menu in Hilla. This change affects only code that reads available client routes from Hilla generated json file.
Fixes: #20109
> fix: always create AvailableViewInfo.menu

- flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/RouteRegistryHotswapper.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
- flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/RouteRegistryHotswapperTest.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/RouteUtilTest.java
When a [At]Layout annotated class is modified, the changes are not propagated to the route registry after hotswap happens. This change updates Route registry layouts configuration and re-registers routes potentially impacted by the change to apply the new settings. It also checks the route target chain for active UIs in order to trigger a page refresh if the layout changes should be applied.
Fixes #20111
> fix: reload route configuration upon layout changes

- flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
- flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReload.java
- vaadin-dev-server/package.json
- vaadin-dev-server/src/main/frontend/vaadin-dev-tools.ts
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
- vaadin-dev-server/vite.config.js
Clears resource bundle cache on translation resource redeployment
Fires a HMR event to the browser when translations are reloaded
Limitation: Only supports DefaultI18NHandler where the paths are known. If you have a custom I18N handler, you might need a custom HMR supporting HotswapListener.
For #20118
Requires https://github.com/vaadin/hilla/pull/2795 to fully fix the issue
> feat: HMR for translation files

- flow-server/src/main/java/com/vaadin/flow/server/dau/FlowDauIntegration.java
- flow-server/src/test/java/com/vaadin/flow/server/dau/FlowDauIntegrationTest.java
Set the DAU cookie as secure, if the http request is secure. Same as for JWT cookie.
> chore: Set DAU cookie secure if the request is secure

- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
Creates ClassFinder once per mojo execution, preventing eccessive and useless scans.
Fixes #19874
> fix: cache ClassFinder for reuse in mojo execution

- flow-server/src/main/java/com/vaadin/flow/server/menu/MenuConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/menu/MenuEntry.java
- flow-server/src/test/java/com/vaadin/flow/server/menu/MenuConfigurationTest.java
`MenuEntry#exclude` is always false with `MenuConfiguration`.
> chore: remove exclude from MenuEntry

- flow-plugins/flow-gradle-plugin/build.gradle
- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
Currently, running gradle plugin tests with a JDK greater than 17, and not having 17 installed on the system, fails because kotlin is configured to use a JDK 17 toolchain. This change replaces the toolchain setting for kotlin, pinning insted the jvmTarget compiler configuration to 17.
This is an alternative way to fix #17574.
> chore: allow running gradle plugin tests with JDK greater that 17

- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/ConvertPolymerMojo.java
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
Reintroduces static methods used by Hilla in FlowModeAbstractMojo, preserving the ClassFinder creation improvements for Flow mojos.
> fix: reintroduce static methods used by Hilla

- eclipse/VaadinJavaConventions.xml
- flow-data/src/test/java/com/vaadin/flow/tests/data/bean/Country.java
- flow-html-components/src/main/java/com/vaadin/flow/component/html/IFrame.java
- flow-server/src/main/java/com/vaadin/flow/dom/Style.java
- flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/Mode.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
If some projects use the formatting file directly from https://github.com/vaadin/flow/blob/main/eclipse/VaadinJavaConventions.xml then the formatting of those projects will change slightly
> chore: Wrap each enum on a separate line when there are many of them

- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
Updates document title for client view with flow layout based on `ViewConfig.title` and when not overridden by server's `HasDynamicTitle`.
RelatedTo: #20107
> fix: update document title for client route

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
- flow-tests/test-react-router/src/main/java/com/vaadin/flow/RouterLinkForwardingToParametersView.java
- flow-tests/test-react-router/src/test/java/com/vaadin/flow/ForwardTargetIT.java
In the case of server-side forward, even if the server callback is not required, the client-side navigation is completed when the React router blocker is still blocked, causing an unwanted roundtrip when location then changes to the desired state.
This change prevents server roundtrip if the blocker is in a blocked state.
Fixes #19822
> fix: perform server navigation roundtrip only when client side navigation is completed

- flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
Firefox has a bug/feature that it don't send the beacon in pagehide event.
Fixes #19305
> Sends beacon request in beforeunload event in Firefox

- flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
- flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
Prevents NPE during hotswap when checking if changed classes are layouts for current active target.
> fix: check parent layouts only if path has a layout

- flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SetParameterRerouteToView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SetParameterForwardToIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SetParameterRerouteToIT.java
> fix: resolve route parameters when rerouting and forwarding with query parameters

- flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
This reverts commit e554b456891e6cdc112fda9e02872b4d6de639a9.
> Revert "Sends beacon request in beforeunload event in Firefox (#20198)"

- flow-server/src/main/java/com/vaadin/flow/server/menu/MenuConfiguration.java
- flow-server/src/test/java/com/vaadin/flow/server/menu/MenuConfigurationTest.java
Fix the menu page header to
check the actual full path for the
view and not the view path.
For client entries the
AvailableViewInfo.path is only
the "route" for the file and
not the whole path from parents.
> fix: menu page header path check

- flow-server/src/main/java/com/vaadin/flow/server/menu/MenuConfiguration.java
> fix: add usage stats for dynamic menu entries

- flow-server/src/main/java/com/vaadin/flow/internal/menu/MenuRegistry.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/menu/MenuConfigurationTest.java
- flow-server/src/test/java/com/vaadin/flow/server/menu/MenuRegistryTest.java
Adds a new util method that detects layout entries in `file-routes.json`.
Related-to https://github.com/vaadin/hilla/issues/2825
> fix: Add util method for detecting Hilla auto layout

- flow-server/src/main/resources/com/vaadin/flow/server/webcomponent/webcomponent-script-template.js
This fixes the following error which sometimes occurs when switching between docs pages with Java examples:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'disconnected')
at ContextMenuPresentationWc.disconnectedCallback (:8000/vaadin/VAADIN/generated/flow/web-components/context-menu-presentation-wc.js:131:18)
at removeChild (chunk-UXDD7MME.js:8456:26)
```
I'm not sure how to test this but it makes sense to check for object being defined before calling its methods anyway.
- Bugfix
> fix: prevent possible error on embedded component disconnect

- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
Commands enqueued by `VaadinSession.access()` in general have nothing to do with each other. The only thing they have in common is they share the same `VaadinSession` (and, by implication, `VaadinService`).
Therefore, if command №1 invoked `UI.setCurrent()` and command №2 invokes `UI.getCurrent()`, command №2 should read `null`, not the random `UI` from command №1 that it has nothing to do with.
Fixes #6349
- Except `JarContentsManagerTest.copyFilesFromJar_doNotUpdateFileIfContentIsTheSame` which has nothing to do with this change.
> Fix flow issue #6349

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Update default npm version
to match the version used
by node 22.10.0
> fix: Update default npm version

- flow-server/src/main/java/com/vaadin/flow/internal/menu/MenuRegistry.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/ClientTarget.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/DefaultRouteResolver.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/RouteTarget.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/menu/MenuConfiguration.java
- flow-server/src/test/java/com/vaadin/flow/router/DefaultRouteResolverTest.java
- flow-server/src/test/java/com/vaadin/flow/server/menu/MenuConfigurationTest.java
- flow-server/src/test/java/com/vaadin/flow/server/menu/MenuRegistryTest.java
Improves navigation path matching with client route templates. Adds support for matching with route parameters to find automatic Flow main layout for client routes.
Fixes: #20268
> fix: support client route parameters in auto layout path matching

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
Java records are immutable, so they do not provide setters for their properties. However, Flow Binder fully supports writing records by creating new instances on demand.
This change prevents Binder from logging a useless 'missing setter' log message for records.
> chore: don't log missing setter message for records

- flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/RouteUtilTest.java
- flow-server/src/test/java/com/vaadin/flow/server/menu/MenuRegistryTest.java
Fix the client server route
collision to not take into
account client layouts as
they are not route targets.
For instance
```
{
"route": "flow",
"params": {},
"children": [
{
"route": "hello-hilla",
"menu": {
"title": "Hello React in Flow Layout"
},
"title": "Hilla in Flow",
"flowLayout": true,
"params": {}
}
]
},
``` 
Collision on `flow` is wrong as the actual existing route is only `flow/hello-hilla` and thus should not match against a server route `flow`
> fix: client route collisions

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
Adds a shortcut method that read the record and checks that it's not a bean.
> chore: Add a shortcut method for reading from record

- flow-server/src/main/java/com/vaadin/flow/internal/menu/MenuRegistry.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/test/java/com/vaadin/flow/component/InvalidUrlTest.java
- flow-server/src/test/java/com/vaadin/flow/component/UITest.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
- flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
- flow-server/src/test/java/com/vaadin/flow/server/menu/MenuConfigurationTest.java
- flow-server/src/test/java/com/vaadin/flow/server/menu/MenuRegistryTest.java
Fixes https://github.com/vaadin/flow/issues/20290
> fix: find file-routes.json in dev bundle

- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Optional is not serializable, so capturing it into a SerializablePredicate will prevent serialization to succeed.
> fix: prevent Optional capture in serializable predicate

- flow-server/src/main/java/com/vaadin/flow/server/frontend/CssBundler.java
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
- flow-tests/test-themes/src/main/frontend/themes/app-theme/theme.json
- flow-tests/test-themes/src/main/frontend/themes/parent-theme/theme.json
- flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
- flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Adds missing css imports for parent theme when given in parent theme.json with lumoImports property and running with dev bundle.
Fixes: #19567
> fix: import parent theme lumoImports in dev bundle mode

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
Clean the token file after
production build/execution
to not make ide app execution
run app in production mode.
Closes #20294
> fix: remove tokenFile after production build

- flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
Fix collection of theme assets
in windows. Fix componentTracker
patch check in windows.
> fix: Theme asset collection and ComponentTracker path check

- flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
Fixes https://github.com/vaadin/copilot/issues/48
> fix: Ignore CDI related classes when finding component location

- flow-server/src/main/java/com/vaadin/flow/component/Component.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
- flow-server/src/test/java/com/vaadin/tests/server/SerializationTest.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/scopes/BeanStore.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/scopes/VaadinRouteScope.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/scopes/VaadinSessionScope.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/scopes/VaadinUIScope.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/scopes/AbstractScopeTest.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/scopes/VaadinRouteScopeTest.java
Makes sure that VaadinSession and UI thread locals are available during both serialization and deserialization, to allow other libraries to perform inspection and injection of Vaadin scoped beans.
Also refactors VaadinRouteScope to be independent from VaadinService when fetching RouteScopeOwner annotation for the bean, and replaces VaadinSession.unlock() calls with direct access to the lock instance to prevent unwanted push during bean lookup.
Fixes #19967
Part of vaadin/kubernetes-kit#140
> fix: support serialization of Vaadin scoped beans

- flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendInputProperties.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojo.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
- flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/ExclusionFilter.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Adds new property `npm.excludeWebComponents` (or `npmExcludeWebComponents` in Maven configurations). By default, it's `false` and everything works as before. `true` will exclude all web component dependencies from `package.json` for development mode (Vite/dev bundle) and production bundle build. Excluded dependencies are all Vaadin core components (e.g. button, grid, login, etc.) and commercial components (e.g. charts, rich-text-editor, etc.), but not lumo/material themes.
RelatedTo: #19948
> feat: opt-out web components from package.json

- flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendInputProperties.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
- flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
- flow-server/src/main/resources/vite.generated.ts
- flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateViteTest.java
- flow-tests/test-express-build/test-dev-bundle-frontend-add-on/pom.xml
- flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/frontend/styles/my-sass.scss
- flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/java/com/vaadin/flow/frontend/DevBundleCssImportView.java
- flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/frontend/DevBundleCssImportIT.java
- flow-tests/test-frontend/vite-embedded-webcomponent-resync/pom.xml
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
> feat: Add support for customizable projectFileExtensions

- flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
- flow-client/src/main/java/com/vaadin/client/flow/nodefeature/MapProperty.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ClientSideValueChangeView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ClientSideValueChangeIT.java
Changes client side value binding logic so that if the user modifies the value during server round-trip, the value earlier sent to the server no longer overwrites user's changes once the round-trip finishes. Instead, user's changes are preserved.
Fixes https://github.com/vaadin/flow/issues/20365
> fix: flush logic

- flow-server/src/main/java/com/vaadin/flow/component/Component.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
- flow-server/src/test/java/com/vaadin/tests/server/SerializationTest.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/scopes/BeanStore.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/scopes/VaadinRouteScope.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/scopes/VaadinSessionScope.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/scopes/VaadinUIScope.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/scopes/AbstractScopeTest.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/scopes/VaadinRouteScopeTest.java
Makes sure that VaadinSession and UI thread locals are available during both serialization and deserialization, to allow other libraries to perform inspection and injection of Vaadin scoped beans.
Also refactors VaadinRouteScope to be independent from VaadinService when fetching RouteScopeOwner annotation for the bean, and replaces VaadinSession.unlock() calls with direct access to the lock instance to prevent unwanted push during bean lookup.
Fixes #19967
Part of vaadin/kubernetes-kit#140
> fix: support serialization of Vaadin scoped beans (#20394) (CP: 24.4)

- flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
- flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
- flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InternalErrorIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java
Attempts to fix the synchronization issue related to the usage of the Login reported in #12640. The Login component sends the UIDL request for the login event to the server and concurrently submits the form. If processing the form submission performs a session ID change and a request redirect, the UIDL requests might fail with a session expiration response. The Flow client then can cancel the first redirect because it reloads the page due to the session expiration. Lastly, the beacon request hits again a valid session, but a resynchronization is triggered because the previous UIDL request was rejected.
This change delays a bit the session expiration handling on Flow client, to allow a potential redirect to complete without being cancelled. However, the client application is immediately …
> fix: delay session expiration handling to prevent canceling ongoing navigation (#19983) (CP: 23.5)

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
- flow-tests/test-webpush/src/main/java/com/vaadin/flow/webpush/WebPushView.java
- flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
- flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPushKeys.java
- flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPushSubscription.java
- flow-webpush/src/main/resources/META-INF/frontend/FlowWebPush.js
Removes third-party `nl.martijndwars.webpush.Subscription` from Flow public API.
Removes the feature flag.
> feat!: WebPush Subscription Wrapper and feature flag removal

- flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/StreamReceiverHandlerTest.java
This change will set JakartaServletFileUpload's header charset to UTF-8 in StreamReceiverHandler when request character encoding is null. This ensures that system's default character encoding is not applied when parsing filename of the uploaded file, unless request's character encoding is set otherwise.
Only for setups without multipart config for servlet.
Fixes: https://github.com/vaadin/flow/issues/20417
> fix: fix ServletFileUpload header encoding (#20480) (CP: main)

- vaadin-dev-server/src/main/frontend/vaadin-dev-tools.ts
When the app is bootstrapping, it only contains
`initializing`, `isActive` and `productionMode`. We should not call `sendEventMessage` at this point or might cause `Uncaught TypeError: l.sendEventMessage is not a function`. 
This is unlikely to happen in many real world scenarios but happens in Copilot tests
> fix: Do not try to refresh app while it is initializing

- flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/StreamReceiverHandlerTest.java
This change will set JakartaServletFileUpload's header charset to UTF-8 in StreamReceiverHandler when request character encoding is null. This ensures that system's default character encoding is not applied when parsing filename of the uploaded file, unless request's character encoding is set otherwise.
Only for setups without multipart config for servlet.
Fixes: https://github.com/vaadin/flow/issues/20417
> fix: fix ServletFileUpload header encoding (#20480) (CP: 24.4)

- flow-server/src/main/java/com/vaadin/flow/router/internal/DefaultRouteResolver.java
- flow-server/src/test/java/com/vaadin/flow/router/DefaultRouteResolverTest.java
When having a client route for
server layout  the layout
parent routes should be collected.
Fixes #20505
> fix: Client route autolayout should have parent layouts chain

- flow-server/src/main/java/com/vaadin/flow/server/SynchronizedRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
Move blocking calls outside session lock (#19938)
> Fix: move blocking calls outside session lock (#20475) (CP:24.4)

- flow-server/src/main/java/com/vaadin/flow/server/Constants.java
- flow-server/src/main/java/com/vaadin/flow/server/PwaIcon.java
- flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePWAIcons.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/PwaHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGeneratePWAIconsTest.java
Generates PWA icons during the production build, preventing the need to use AWT APIs at runtime and making first requests to the application faster. Also prevents potential issues caused by loading AWT native library in native images.
If the base icon cannot be found at build time, Flow will attempt to generate the icons at runtime, exactly how it does before this change.
Fixes #19497
> feat: generate PWA icons at build time

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnectionTest.java
This change prevents ViteWebSocketConnection to waiting indefinitely on close, waiting at most 500 milliseconds for the client websocket close request to complete.
Fixes #20445
> fix: prevent blocking when closing ViteWebSocketConnection

- flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DragSource.java
- flow-dnd/src/main/resources/META-INF/resources/frontend/dndConnector.js
Attach elemnt to dom and move it
outside of the viewport to have it
visible as a drag image.
Image can be used without attaching
to dom. Hidden elements are also
not shown so throw exception
when using one as dragImage.
Fixes #20426
> fix: attach element when used in drag source

- flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java
Exclude vaadin/router when runing
in react mode.
Without exclusion vaadin/router
gets added from the vaadin-core.json
package in platform.
Fixes #20496
> fix: vaadin/router added with react-router

- flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java
Exclude vaadin/router when runing
in react mode.
Without exclusion vaadin/router
gets added from the vaadin-core.json
package in platform.
Fixes #20496
> fix: vaadin/router added with react-router (#20522) (CP: 24.5)

- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
If the client request contains
the previous id and exactly the
same message content respond with
the same payload as previously.
Closes #20506
> feat: resend payload of reoccuring client request

- flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
> fix: prevent hotswap failure if class is not found

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/index-react.tsx
Preparations for React Router v7, opts-in a new feature to avoid warnings in console.
Related-to https://github.com/vaadin/flow/issues/20527
> chore: Opt-in for v7_startTransition of React Router

- flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/Reflector.java
- flow-plugins/flow-maven-plugin/src/it/deps-with-classifier-dups-project/invoker.properties
- flow-plugins/flow-maven-plugin/src/it/deps-with-classifier-dups-project/pom.xml
- flow-plugins/flow-maven-plugin/src/it/deps-with-classifier-dups-project/src/main/java/com/vaadin/test/ProjectFlowExtension.java
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/Reflector.java
Computes a unique key for maven artifacts when collecting dependencies for the Flow maven plugin isolated classloader.
fixes #20555
> fix: compute unique key for artifact

- flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
- flow-server/src/test/java/com/vaadin/flow/ComponentTrackerTest.java
Some filtering was already earlier moved to Copilot and handling everything in the same place is easier
> fix: Include all component tracker locations

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketEndpoint.java
> fix: add vite-ping subprotocol to Vite websocket proxy

- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
- flow-server/src/main/java/com/vaadin/flow/router/NavigationTrigger.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RefreshCurrentRouteView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RefreshCurrentRouteIT.java
Modal components attached to the UI were not removed or replaced during self-navigation triggered by a route refresh.
This change updates navigation handler to ensure modal components are removed and adds a new navigation trigger for route refresh to differentiate programmatic navigations (e.g., forward actions).
It also modifies Hotswapper to require a full chain refresh when modal components are present.
Fixes #20473
> fix: remove modal component on route refresh

- flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
- flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/Reflector.java
- flow-plugins/flow-maven-plugin/src/it/offending-dependency-project/invoker.properties
- flow-plugins/flow-maven-plugin/src/it/offending-dependency-project/pom.xml
- flow-plugins/flow-maven-plugin/src/it/offending-dependency-project/src/main/java/com/vaadin/test/ProjectFlowExtension.java
- flow-plugins/flow-maven-plugin/src/it/offending-dependency-project/verify.bsh
- flow-plugins/flow-maven-plugin/src/it/plugin-pinned-deps-project/invoker.properties
- flow-plugins/flow-maven-plugin/src/it/plugin-pinned-deps-project/pom.xml
- flow-plugins/flow-maven-plugin/src/it/plugin-pinned-deps-project/src/main/java/com/vaadin/test/ProjectFlowExtension.java
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/Reflector.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
The Flow Maven Plugin uses a class loader that combines project and plugin dependencies to ensure class scanning happens on runtime artifacts. However, plugin execution may fail if the project defines dependency versions incompatible with those used by the plugin.
This change enforces the use of plugin-defined versions for certain dependencies not directly used by Flow at runtime. Additionally, it logs potential incompatibilities for other dependencies if the build fails.
Fixes vaadin/mpr-demo#23
> fix: enforce plugin-required dependencies and log incompatibilities

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketEndpoint.java
If you keep the browser debugger paused for longer than the timeout, the application will reload after you click resume
> fix: Remove timeout for browser websocket connection for Vite

- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
Related to https://github.com/vaadin/flow/issues/20577
> fix: service destroy listener exceptions

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes-flow.tsx
Adds missing future flags for a Flow only configuration.
Fixes https://github.com/vaadin/flow/issues/20527
> fix: Add React Router future flags for flow auto-generated routes file

- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
When session destroy is triggered,
wraps each UI close/detach to
catch exceptions, making sure
session destroy listeners are called.
Fixes https://github.com/vaadin/flow/issues/20293
> fix: wrap UI closing to catch exceptions

- flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
Log the correct expected id.
the expected and checked id
is the clientId not the syncId
> chore: Log the correct id

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
When navigating in quick succession
check that path starts with /
as else react will append to
current url.
Fixes #20671
> fix: appended path on fast navigate

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/FrontendStubs.java
Node 20 is the active LTS version for Node.
Node 18 will be end of life soon and new libraries like React 19 support Node 20+
> chore!: Change supported Node from 18 to 20

- flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
- flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
- flow-server/src/test/java/com/vaadin/flow/server/WebBrowserTest.java
- flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java
- flow-server/src/test/resources/common-desktop-useragents.json
- flow-server/src/test/resources/mobile-useragents.json
Added new opera userAgent string.
Better logging for failures.
Better matching for version string.
Fixed android mistaken check.
Part of #20610
> fix: browser parsing

- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
Makes sure that Vaadin thread locals are cleared even if something fails durung requestEnd execution. It also wraps Vaadin interceptors execution in a try/catch block to ensure all of them are invoked and that potential failures does not affect the continuation of requestEnd method.
> fix: ensure requestEnd clears Vaadin thread locals

- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
Makes sure that Vaadin thread locals are cleared even if something fails durung requestEnd execution. It also wraps Vaadin interceptors execution in a try/catch block to ensure all of them are invoked and that potential failures does not affect the continuation of requestEnd method.
> fix: ensure requestEnd clears Vaadin thread locals (#20687) (CP: 23.5)

- flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java
- flow-server/src/main/java/com/vaadin/flow/component/DetachNotifier.java
- flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Wraps detach listener calls and onDetach calls into try-catch blocks so all
possible exceptions are handled by session ErrorHandler, and they will not
interrupt running the remaining detach handlers.
Fixes https://github.com/vaadin/flow/issues/20577
> fix: catch exceptions from detach calls

- flow-bom/pom.xml
- flow-signals/bnd.bnd
- flow-signals/pom.xml
- flow/pom.xml
- pom.xml
- signals/bnd.bnd
- signals/pom.xml
Adds a new empty maven module for Full-Stack Signals common lib for Flow and Hilla
> chore: Add a new maven module for Full-Stack Signals common lib

- flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow-websocket/src/test/java/com/vaadin/flow/spring/flowsecuritywebsocket/AppViewIT.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/AdminView.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PublicView.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/SecurityUtil.java
When using PUSH with websocket transport, the atmosphere wrapped request can be a no-op implementation whose isUserInRole method alwasy returns false, causing, for example, wrong access checking during navigation. This change falls back to Spring Securty for role checking when PUSH transport is websocket.
It also fixes some tests in order to propagate the Spring Security context when starting Thread that perform UI operations.
References psi#123
Part of #11026
> fix: fix role checking when using websocket push

- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/MainView.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/UIAccessContextIT.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
Allows AuthenticationContext.logout feature to be used from a background thread,
handling the missing request by forcing the client to make an additional request.
Applies the same logic used to support logout when using PUSH with websocket
transport.
References #11026
> fix: handle logout from a background thread 

- flow-tests/pom.xml
Set the Jetty stop timeout to a value less than the Jetty plugin's stop wait time. This change prevents the ShutdownManager from being blocked while waiting for Jetty to stop, avoiding an inconsistent state when subsequent Maven modules are executed.
> test: set Jetty stop timeout (2.11)

- flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow-websocket/src/test/java/com/vaadin/flow/spring/flowsecuritywebsocket/AppViewIT.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/AdminView.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PublicView.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/SecurityUtil.java
When using PUSH with websocket transport, the atmosphere wrapped request can be a no-op implementation whose isUserInRole method alwasy returns false, causing, for example, wrong access checking during navigation. This change falls back to Spring Securty for role checking when PUSH transport is websocket.
It also fixes some tests in order to propagate the Spring Security context when starting Thread that perform UI operations.
References psi#123
Part of #11026
> fix: fix role checking when using websocket push (#20679) (CP: 24.5)

- flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow-websocket/src/test/java/com/vaadin/flow/spring/flowsecuritywebsocket/AppViewIT.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/AdminView.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PublicView.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/SpringNavigationAccessControl.java
When using PUSH with websocket transport, the atmosphere wrapped request can be a no-op implementation whose isUserInRole method alwasy returns false, causing, for example, wrong access checking during navigation. This change falls back to Spring Securty for role checking when PUSH transport is websocket.
It also fixes some tests in order to propagate the Spring Security context when starting Thread that perform UI operations.
References psi#123
Part of #11026
> fix: fix role checking when using websocket push (#20679) (CP: 24.4)

- flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow-websocket/src/test/java/com/vaadin/flow/spring/flowsecuritywebsocket/AppViewIT.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/AdminView.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PublicView.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/SecurityUtil.java
When using PUSH with websocket transport, the atmosphere wrapped request can be a no-op implementation whose isUserInRole method alwasy returns false, causing, for example, wrong access checking during navigation. This change falls back to Spring Securty for role checking when PUSH transport is websocket.
It also fixes some tests in order to propagate the Spring Security context when starting Thread that perform UI operations.
References psi#123
Part of #11026
> fix: fix role checking when using websocket push (#20679) (CP: 24.6)

- flow-tests/test-express-build/frontend-add-on/pom.xml
- flow-tests/test-express-build/java-add-on/pom.xml
Removed duplicate maven-jar and merged the configuration options
> Fix for duplicate maven-jar entries in POM.XML

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
Allows the HttpClient default executor to be properly shutdown when HttpClient is not referenced anymore.
> chore: makes HttpClient instance available for garbage collection

- flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
- flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
Prevent hotswapper to trigger a refresh when the classes are loaded for the first time. Refreshing a view should make sense only if a project class has been modified. The only exception is auto layout classes, that must be applied even if they are not directly references in the component tree.
Fixes #20680
Fixes #20681
> fix: trigger refresh on hotswap only for redefined classes

- flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/test/java/org/vaadin/example/SpringDevToolsReloadViewIT.java
- flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/test/java/org/vaadin/example/SpringDevToolsReloadViewIT.java
- flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/test/java/org/vaadin/example/SpringDevToolsReloadViewIT.java
Prevents remote Chrome ERR_INSUFFICIENT_RESOURCES failures for tests loading hundreds of resources concurrently (CSS or JS).
> test: disable shm usage for reload time test

- flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtEventHandlerTest.java
- flow-server/src/main/java/com/vaadin/flow/dom/ChildElementConsumer.java
- flow-server/src/main/java/com/vaadin/flow/dom/Node.java
- flow-server/src/main/java/com/vaadin/flow/internal/menu/MenuRegistry.java
- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
- flow-server/src/main/java/com/vaadin/flow/router/AbstractRouteNotFoundError.java
- flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
- flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/MapSyncRpcHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/dau/DAUVaadinRequestInterceptor.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePWAIcons.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
- flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
- flow-server/src/test/java/com/vaadin/flow/internal/JsonUtilsTest.java
Related-to https://github.com/vaadin/flow/issues/16668
> chore: Remove unused declarations in flow-server and flow-data

- flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerManagerImpl.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Vaadin dev-server executes long-running tasks (e.g. npm install) using the common ForkJoin pool. This can cause a slow startup or even timeouts when the pool size is small.
Using a dedicated executor for dev-server tasks should prevent the above issues.
Fixes #20793
> chore: use custom thread pool for vaadin-dev-server tasks

- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
Make the handle workflow
easier to read.
Add javadoc for clarification
of parts that are executed.
> chore: refactor navigation state renderer

- flow-react/src/main/resources/META-INF/resources/frontend/ReactRouterOutletElement.tsx
> fix: ReactRouterOutlet interferes with layout

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFiles.java
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/jsx-dev-transform/index.ts
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/jsx-dev-transform/jsx-dev-runtime.ts
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/jsx-dev-transform/jsx-runtime.ts
- flow-server/src/main/resources/vite.generated.ts
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
Needed for Copilot to get source information as React 19 drops _debugSource from fiber nodes
> chore: Use custom react transform in development mode

- flow-server/src/main/java/com/vaadin/flow/internal/MessageDigestUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/ProxyConfig.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/VerificationException.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Validate downloaded node
against the provided
sha256 hash.
Fixes #20661
> fix: validate downloaded node

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinWebSecurityTest.java
Improves setOAuth2LoginPage method to configure an OIDC logout success handler capable of handling redirection for UIDL requests. Post logout URL is by default the application root, but a method overload allows specifying a custom URL.
Related-to #11026
> feat: add support for OAuth2 logout configuration

- flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
- flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
- flow-client/src/main/java/com/vaadin/client/communication/RequestResponseTracker.java
- flow-client/src/test/frontend/FlowTests.ts
- flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
- flow-tests/pom.xml
- flow-tests/test-client-queue/pom.xml
- flow-tests/test-client-queue/src/main/java/com/vaadin/flow/misc/ui/CustomService.java
- flow-tests/test-client-queue/src/main/java/com/vaadin/flow/misc/ui/CustomServlet.java
- flow-tests/test-client-queue/src/main/java/com/vaadin/flow/misc/ui/CustomUidlRequestHandler.java
- flow-tests/test-client-queue/src/main/java/com/vaadin/flow/misc/ui/TestNoResponseView.java
- flow-tests/test-client-queue/src/test/java/com/vaadin/flow/misc/ui/NoResponseIT.java
Add sent payloads to message
queue and resend if no response
to message inside MaxMessageSuspendTimeout
fixes #20507
> feat: queue message payloads

- flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
- flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
Do not log the exception stack trace
when failing version parse.
Message contains alrready required
information and the result is -1
and the app stays running.
touches #20838
> chore: Update browser details parse log output

- flow-server/src/main/java/com/vaadin/flow/router/internal/RouteSegment.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinServletContextStartupInitializer.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/AbstractRouteRegistryTest.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/ConfigureRoutesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/SessionRouteRegistryTest.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
When route configuration errors happen, make sure to output the actual error message as the first output at `ERROR` level. When this is detected at startup, we can't prevent printing out the stack trace too since the container does that when initialization throws. Also checked all the messages for different route misconfiguration cases, and they seem to be fine.
Fixes https://github.com/vaadin/flow/issues/20589
> fix: make route config errors more prominent

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
When Binder is used with record, calling setReadonly method does not have any effect because the logic only considers bindings with a proper setter. This change fixes the setReadonly logic to take care of all bindings when Binder is using a record.
Fixes #20854
> fix: fix setReadonly when using binder with records

- vaadin-spring/src/main/java/com/vaadin/flow/spring/data/CountService.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/data/ListService.java
Using a default implementation does not put any extra burden on the interface implementor
> chore: Add convenience list and count without Filter

- flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
- flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShortcutsView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShortcutsIT.java
Adds `DisabledUpdateMode` support for `ShortcutRegistration`.
Fixes https://github.com/vaadin/flow/issues/20813
> feat: DisabledUpdateMode for ShortcutRegistration

- vaadin-spring/src/main/java/com/vaadin/flow/spring/data/CountService.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/data/ListService.java
Reverts vaadin/flow#20867
This causes problems with Hilla that does not support method overloading, as TS/JS does not support that
> Revert "chore: Add convenience list and count without Filter"

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Part of https://github.com/vaadin/web-components/issues/4585
> feat: add accessibleDisabledButtons feature flag

- flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
- flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
When PUSH is enabled, Flow Hotswapper uses it to refresh only the affected UIs. However, this can cause issues if Flow views contain code that relies on VaadinRequest thread local, since hotswap refresh start in a background thread. This change defines a client side event listener to trigger the refresh, and uses PUSH only to fires the event.
Fixes #20843
> fix: trigger refresh from client on hotswap with PUSH

- flow-server/src/main/resources/vite.generated.ts
- flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Updates the service worker plugin to use the Vite official API for building `sw.js`.
Fixes https://github.com/vaadin/flow/issues/20808
> refactor: use Vite official API for building sw.js

- pom.xml
Two tests in the codebase need to nullify the factory field of URL class by reflection. With Java 17 this requires java.net module to be opened to the unnamed module.
> test: fix URLStreamHandlerFactory reset for Java 17 (2.11)

- flow-server/src/main/resources/vite.generated.ts
https://github.com/vaadin/flow/pull/20894 reintroduced https://github.com/vaadin/flow/issues/13123 where the service worker build would cause a server restart in dev mode. This PR fixes this issue again.
> fix: build service worker without writing it to FS

- flow-server/src/main/resources/vite.generated.ts
- flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
* fix: fix service worker build
* fix PwaTestIT
* exclude sw.js from manifest
* generate service worker at closeBundle stage
* clean up service worker build config
* generate service worker at different stages depending on mode
* do not use lib mode to allow for minification in es format
* clean up plugin code
* add inlineDynamicImports: true option
* revert some changes to minimize diff
* add exports option for backward compatibility
---------
> refactor: use Vite official API for building sw.js (#20894) (CP: 24.5)

- flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
- flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
The  name used to register the event listener for hotswap refresh and the name used to fire the event are different. This change fixes the name in the listener.
Fixes #20843
> fix: fix UI refresh event name

- flow-server/src/main/java/com/vaadin/flow/component/HasSize.java
- flow-server/src/main/java/com/vaadin/flow/server/Constants.java
- flow-server/src/test/java/com/vaadin/flow/component/HasSizeTest.java
Adds data attributes to components that have been configured to use the full size in a layout, by either calling `setWidthFull`, `setHeightFull` or `setSizeFull`. Vaadin components such as `HorizontalLayout` and `VerticalLayout` will include additional styles targeting children with these data attributes, to effectively make these children take up the remaining space in a layout, rather than the full size.
For now, the respective styles will only be added by the Vaadin components if the `com.vaadin.experimental.layoutImprovements` feature flag is enabled (see https://github.com/vaadin/web-components/pull/8552).
Part of https://github.com/vaadin/flow-components/issues/6998
- Feature
> feat: mark full size components with data attribute

- flow-html-components/src/main/java/com/vaadin/flow/component/html/IFrame.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/IFrameView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/IFrameIT.java
Setting resource should happen via underlying element API to avoid timing issues. This convenience API is easier to find.
> feat: Add setSrc(AbstractStreamResource)

- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksHillaTest.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeEndpointTest.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTest.java
Execute Hilla tasks (`TaskGenerateOpenAPI` and `TaskGenerateEndpoint`) whenever Hilla is available on the classpath. These tasks should determine the required actions themselves, instead of Flow trying to do it.
Fixes https://github.com/vaadin/flow/issues/20289
Fixes https://github.com/vaadin/flow/issues/18800
> feat: execute Hilla tasks whenever Hilla is available

- .github/workflows/validation.yml
- flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
- flow-tests/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
- pom.xml
- Some actions are deprecated and prevent the workflow execution.
- bump TB version
- fix selenium import and remove not needed dependency 
- fix tests
> chore: make GHA work again on 23.5 branch

- flow-tests/test-frontend/pom.xml
If the dev and prod mode test modules are defined in the same folder, the production mode can fail if executed after development mode. This happens because the dev mode npm install background process may still be running when Maven executes the frontend build for prod mode, causing conflicts in the node_modules folder.
This change swaps the execution order of the modules to ensure that prod mode is executed before dev mode.
> test: run npm production tests before development mode (23.5)

- flow-server/src/main/java/com/vaadin/flow/internal/JacksonCodec.java
- flow-server/src/main/java/com/vaadin/flow/internal/JacksonUtils.java
- flow-server/src/test/java/com/vaadin/flow/internal/JacksonCodecTest.java
- flow-server/src/test/java/com/vaadin/flow/internal/JacksonUtilsTest.java
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Create jackson versions
of the JsonUtils and JsonCodec.
part of #20741
> feat: Add jackson utils and codec

- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
Ignores additional well-known packages when scanning classes to find frontend resources.
> chore: improve class scanning filter

- flow-server/src/main/java/com/vaadin/flow/internal/JacksonUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/test/java/com/vaadin/flow/internal/JacksonUtilsTest.java
This is compatible with the old elemental json version and with how browsers output indented json
> fix: Output file JSON without a leading space before colon

- flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/TestEndpointGeneratorTaskFactory.java
- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
- flow-server/src/main/java/com/vaadin/flow/internal/hilla/EndpointRequestUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/EndpointGeneratorTaskFactory.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksHillaTest.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeEndpointTest.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/TestEndpointGeneratorTaskFactory.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeClassFinderTest.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTest.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/VaadinServletContextInitializerTest.java
Fixes https://github.com/vaadin/flow/issues/20983
> feat: improved endpoint detection

- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlags.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrap.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentProviderTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlagsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrapTest.java
Activating a feature flag in the project does not work when a default bundle is used because the values of the flags sent to the client are hard-coded at bundle build time. Additionally, if a feature flag is active during bundle creation, it remains active on the client side even if the project does not activate it in the `vaadin-featureflags.properties` file.
This change ensures that feature flags in the frontend bundle are always disabled initially and are activated on page load based on the current project settings.
Fixes #20991
> fix: compute client-side feature flag values at runtime

- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlags.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrap.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentProviderTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlagsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrapTest.java
Activating a feature flag in the project does not work when a default bundle is used because the values of the flags sent to the client are hard-coded at bundle build time. Additionally, if a feature flag is active during bundle creation, it remains active on the client side even if the project does not activate it in the `vaadin-featureflags.properties` file.
This change ensures that feature flags in the frontend bundle are always disabled initially and are activated on page load based on the current project settings.
Fixes #20991
> fix: compute client-side feature flag values at runtime (#21066) (CP: 24.7)

- vaadin-spring/src/test/java/com/vaadin/flow/spring/instantiator/SpringInstantiatorTest.java
Some Spring tests flood the logs with 'IllegalStateException's raised when trying to initialize Atmosphere on a mocked Servlet environment. This change prevent Atmosphere to be initialized by providing a mock framework instance, that is anyway not used by tests.
> test: prevent Atmosphere IllegalStateException in Spring Tests

- flow-react/src/main/resources/META-INF/resources/frontend/ReactRouterOutletElement.tsx
Should fix compile errors like:
```
[ERROR] src/main/frontend/generated/jar-resources/ReactRouterOutletElement.tsx(6,3): error TS2416: Property 'connectedCallback' in type 'ReactRouterOutletElement' is not assignable to the same property in base type 'ReactAdapterElement'.
```
> chore: Preserve method signature to avoid compile errors

- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnectionTest.java
The JDK HttpServer uses the common Fork Join pool to fulfill callbacks connected to async operations, like the websocket connection handshake. On GH actions, sometimes the callbacks are executed with a delay of a couple of seconds, most likely caused by many tests running in parallel on the same JVM and concurrently submitting mid/long running tasks to the common pool. This change increases the ViteWebsocketConnection timeouts to take care of such delays.
> test: increase timeouts for ViteWebsocketConnection tests

- flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
- flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractBrowserConsoleTest.java
- flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTestWithProxy.java
- flow-test-util/src/main/java/com/vaadin/flow/testutil/net/SimpleProxy.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/faulttolerance/BeforeOutputStreamActionFilter.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/faulttolerance/NetworkInterruptionView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/faulttolerance/NetworkInterruptionIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/PushChromeBrowserTestWithProxy.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/ReconnectTest.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/SendMultibyteCharactersTest.java
Messages sent by the Flow client are queued until the server acknowledges their reception. However, if there's a network fault, the Flow client immediately attempts to resend the message, resulting in duplicates in the queue.
This change ensures that the same message is not added to the queue multiple times.
Fixes #21095
> fix: prevent duplicated messages in client queue

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/ComponentFlagsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsWithByteCodeScannerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsWithFullCPScannerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesWithByteCodeScannerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesWithFullCPCodeScannerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithByteCodeScannerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithFullCPScannerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendScannerPwaTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerThemeTest.java
Fixes https://github.com/vaadin/flow/issues/21016
> feat: use single scanner for plugin class scan

- flow-server/src/main/java/com/vaadin/flow/component/WebComponentExporter.java
- flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/internal/JacksonCodec.java
- flow-server/src/main/java/com/vaadin/flow/internal/JacksonUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentBinding.java
- flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
- flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentTest.java
- flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentBindingTest.java
Change more parts of webComponent
to use Jackson instead of elemental.
> feat: WebComponent more Jackson

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
The PR introduces a new feature flag, `defaultAutoResponsiveFormLayout`, which enables auto-responsive mode for all form layouts by default.
Part of https://github.com/vaadin/flow-components/issues/7164
> feat: add defaultAutoResponsiveFormLayout feature flag

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ExternalDependencyWatcher.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/FileWatcherTest.java
Watch resources from active project if active project defined in hotdeployDependencyFolders.
If hotdeployDependencyFolders is not set, add active project to watched set of directories.
Fixes https://github.com/vaadin/flow/issues/20992
> fix: watch active project resources

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
- flow-tests/test-express-build/test-embedding-express-build/src/main/frontend/themes/embedded-theme/theme.json
- flow-tests/test-express-build/test-embedding-express-build/src/main/frontend/themes/parent-theme/styles.css
- flow-tests/test-express-build/test-embedding-express-build/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
When using a development bundle, WebComponentBootstrapHandler adds a <link> tag to the embedding document that references document.css for all used themes (application and parents). However, the URL is relative to the embedding document instead of being an absolute URL to the CSS resource. Additionally, the <link> tag is added even if the theme does not provide a document.css file, potentially causing 404 errors at runtime.
This change ensures that the link URL is calculated based on the request and that it only adds tags for existing CSS files.
Fixes #21120
Fixes #19620
> fix: ensure exported WebComponent adds absolute links to document.css

- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/FileWatcherTest.java
Stops watchers after test execution and uses JUnit temporary folder rule to ensure temporary directories are deleted.
> test: refactor FileWatcherTest to clean up resources

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFiles.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFilesTest.java
> fix: Clean file-routes if hilla not in use (#21155)

- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFiles.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFilesTest.java
If the prepare-frontend task is invoked while the Vaadin application is running, it may happen that some generated files are mistakenly removed, causing the frontend compilation to fail and sometimes an infinite reload loop.
This happens, for example, in Hilla projects based on Gradle and IntelliJ IDEA: when the IDE compiles a class, it runs Gradle, and the vaadinPrepareFrontend task is executed. Some generated files are then deleted for two reasons:
1. Hilla is not detected because the check is done during the Gradle configuration phase, and it uses the plugin class loader, which does not have references to the project dependencies.
2. The TaskRemoveOldFrontendGeneratedFiles is executed, but it fails to compare non-normalized paths.
This change fixes the two issues by detecting Hilla …
> fix: prevent hot-reload failure caused by prepare-frontend task

- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFiles.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFilesTest.java
If the prepare-frontend task is invoked while the Vaadin application is running, it may happen that some generated files are mistakenly removed, causing the frontend compilation to fail and sometimes an infinite reload loop.
This happens, for example, in Hilla projects based on Gradle and IntelliJ IDEA: when the IDE compiles a class, it runs Gradle, and the vaadinPrepareFrontend task is executed. Some generated files are then deleted for two reasons:
Hilla is not detected because the check is done during the Gradle configuration phase, and it uses the plugin class loader, which does not have references to the project dependencies. The TaskRemoveOldFrontendGeneratedFiles is executed, but it fails to compare non-normalized paths. This change fixes the two issues by detecting Hilla from the …
> fix: prevent hot-reload failure caused by prepare-frontend task (#21174)(CP:24.6)

- flow-server/src/test/java/com/vaadin/flow/server/menu/MenuRegistryTest.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/FileWatcherTest.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnectionTest.java
Clear the menuregistry cache for
production mode execution as it
caches client routes.
Use the now static getMenuItems as
static without creating an instance.
> test: menu registry test in production mode

- flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
- flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
- flow-client/src/main/java/com/vaadin/client/communication/ReconnectionAttemptEvent.java
- flow-client/src/main/java/com/vaadin/client/communication/RequestResponseTracker.java
- flow-tests/test-client-queue/src/main/java/com/vaadin/flow/misc/ui/SlowResponseView.java
- flow-tests/test-client-queue/src/test/java/com/vaadin/flow/misc/ui/SlowResponseIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/faulttolerance/NetworkInterruptionIT.java
When a request takes longer to respond than the configured `maxMessageSuspendTimeout`, the Flow client still attempts to resend the last message to the server, causing inconsistencies with the connection state indicator in subsequent requests.
This change prevents messages from being resent while a request is in progress. It also updates the reconnection mechanism to properly attempt an HTTP request instead of merely re-adding the unsent message to the client queue.
Fixes #21188
> fix: prevent resending message when request is in progress

- flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
Fix 1s delay on init request
when reloading full page.
We now close the push channel
if open for beacon close request
before ui.close so we do not get a
pending empty message that blocks
push channel close.
Fixes #21158
> fix: extra delay on full page reload

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Adds a feature flag for the Master Detail Layout component.
Note that we want to release the component as a preview feature in 24.7, so that people can try it out sooner. So let's cherry-pick the flag to that branch as well.
- Feature
> feat: add feature flag for Master Detail Layout

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePWAIcons.java
Submitting multiple asynchronous jobs to generate PWA icons at build time can cause OutOfMemory errors with Gradle.
This change introduces a fixed thread pool executor so that fewer icon generations are processed concurrently, allowing the JVM to clean up memory for already generated images.
Fixes #20842
> fix: reduce concurrent PWA icons generation tasks

- flow-jandex/pom.xml
This reverts commit afecf4038e05f2d15ff82143f8a6020e675450ae.
Jandex index 3.3.0 is incompatible with Quarkus 3.15, currently used by vaadin-quarkus
> revert: chore(deps): bump io.smallrye:jandex-maven-plugin from 3.2.7 to 3.3.0 (#21247)

- flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
Adds toString to PushMessage, so the content of the message can be visible on Atmosphere TRACE logs for debugging purposes.
> chore: add toString method to PushMessage

- flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
- flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
When Hotswapper force page reload is active, trigger page reload only for redefined classes, not when they are loaded for the first time.
Fixes #21273
> fix: force page reload only for redefined classes

- flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/Reflector.java
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/Reflector.java
- flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/ReflectorTest.java
Adds the "provided" scope to the list of Maven dependency scopes considered during class scanning by the Flow maven plugin.
Fixes #21192
> feat: scan Maven "provided" scoped dependencies

- flow-server/src/main/java/com/vaadin/flow/component/Component.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
During serialization and deserialization of VaadinSession and UI,
CurrentInstances may be set but not present in the original instances map,
causing the added instance to leak outside the scope of the deserialization
hook method.
This fix ensures all instances set by the hooks are wiped out before
restoring the original instances.
> fix: prevent serialization to leak CurrentInstances

- signals/src/main/java/com/vaadin/signals/impl/StagedTransaction.java
- signals/src/test/java/com/vaadin/signals/impl/StagedTransactionTest.java
If a tree was only read but not written inside a transaction, then the transaction result was never published. This was because the result collector would wait for a result from the unchanged tree but that tree wasn't involved in the actual two-phase commit procedure and thus never published any result. This is fixed by creating the result collector based on the trees that participate in the two-phase commit.
> Exclude trees without changes from the result collector

- flow-server/src/main/resources/vite.generated.ts
Vite / Rollup defaults are old. While #21276 adjusted the target for the dependencies optimizer, this change applies the same target also for the `sw.js` entrypoint build.
> fix(flow-server): enable top-level await for service worker

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/FileWatcher.java
Calling watchAsync without any specific executor uses the common ForkJoinPool. This is bad as all the watchers will remain in a blocking state until there is a change and will thus always use up a large part of the ForkJoinPool. If other tasks try to use the common ForkJoinPool, it might run out of concurrent threads and will no longer start any tasks at all
> fix: Do not starve the common ForkJoinPool with blocking listener tasks

- flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/FileWatcher.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/NamedDaemonThreadFactory.java
FileWatcher was using an executor that creates non-daemon threads to watch for file changes. This caused a delay in JVM shutdown, as it would wait at least 60 seconds for all threads in the executor pool to be evicted.
This change provides a custom thread factory that creates daemon threads for the executor to prevent JVM shutdown delays.
> fix: prevent file watcher threads from slowing down JVM shutdown (#21365) (CP: 24.6)

- pom.xml
updated the flatten-maven-plugin to keep <scm> when publishing
> chore: upgrade vaadin-parent to 2.2.2

- .github/workflows/validation.yml
seems the environment variable is not working for concurrency group..
> chore: use github variable for concurrency group

- flow-server/src/main/java/com/vaadin/flow/server/TransferProgressListener.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/ClassDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/FileDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/ServletResourceDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressAwareHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/AbstractDownloadHandlerTest.java
This allows to type
```java
DownloadHandler.forFile(new File("image.png"))
.whenComplete(success -> {});
```
and get the proper type after you ask "Introduce local variable" in IDE:
```java
FileDownloadHandler fileDownloadHandler =
DownloadHandler.forFile(new File("image.png"))
.whenComplete(success -> {});
```
Without it, the IDE create a variable of type `TransferProgressAwareHandler` that you cannot pass to component.
Related-to https://github.com/vaadin/flow/pull/21343
> fix: Preserve handler type when chaining listener methods

- flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractFileUploadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/InMemoryUploadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/UploadEvent.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/UploadHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/UploadTransferProgressTest.java
Add unit tests for listeners of upload case.
Also changes how owner element is given to transfer context.
Fixes https://github.com/vaadin/flow/issues/21167.
> test: Add tests for TransferProgressListener in upload case

- flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressListener.java
Fix javadoc links after
file move.
> chore: fix javadoc links after refactor

- flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
- flow-html-components/src/main/java/com/vaadin/flow/component/html/HtmlObject.java
- flow-html-components/src/main/java/com/vaadin/flow/component/html/IFrame.java
- flow-html-components/src/main/java/com/vaadin/flow/component/html/Image.java
- flow-server/src/main/java/com/vaadin/flow/server/StreamReceiver.java
- flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java
- flow-server/src/main/java/com/vaadin/flow/server/StreamVariable.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressAwareHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressListener.java
Mark StreamResource api as deprecated
and point to Upload-/DownloadHandler
instead.
part of #21414
> chore: deprecate StreamResource api

- signals/src/main/java/com/vaadin/signals/impl/Transaction.java
- signals/src/test/java/com/vaadin/signals/impl/TransactionTest.java
The logic that determines whether a computed signal or effect should be run again is triggered from a change observer. If the value used by that change observer was already captured in the read transaction, then the old value would be used instead of the new one when the value is changed which would mean that the change remains undetected.
> Update read revision before applying changes

- flow-tests/pom.xml
Selenium and Testbench have been updated to a new version supported by CI. The workaround must be removed to prevent build failures.
> test: disable selenium-devtools workaround (24.6)

- flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressListener.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/AbstractDownloadHandlerTest.java
For common cases let's not lock the session for data transfer and assume that this locking can be done in a custom handler, if required.
> fix: Do not lock the session while transferring content

- .github/workflows/validation.yml
Updates the validation workflow to expand only one environment variable when computing the Concurrency Group
> chore: expand only one variable in Concurrency Group

- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
If a route component instance is proxied by a DI framework the PageTitle annotation from the concrete class might not be accessible because it is not inheritable. This change tries to read the annotation from the application-defined class instead of using the route instance class directly.
Fixes vaadin/quarkus#67
> fix: read PageTitle annotation from application-defined class

- flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractFileUploadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/ClassDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/ElementRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/FileDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/InMemoryUploadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/ServletResourceDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/UploadHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/UploadHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/AbstractDownloadHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/ClassDownloadHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/FileDownloadHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/InputStreamDownloadHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/ServletResourceDownloadHandlerTest.java
This adds the IOException to Download/Upload handlers signature to not require catching the exception in lambda.
> fix: Add IOException to handlers signature

- flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/ClassDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadEvent.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/FileDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/ServletResourceDownloadHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/AbstractDownloadHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/ClassDownloadHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/DownloadEventTest.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/FileDownloadHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/InputStreamDownloadHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/ServletResourceDownloadHandlerTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DownloadHandlerView.java
Refactors the `DownloadEvent` to be a normal class.
Removed the getters for file name, type and size and add setters instead that are basically helper methods for setting various attributes to a response.
Adds inline method so that you can call `DownloadHandler.forFile(new File("path/to/file")).inline()` and the download will be inlined onto page.
> fix!: Add setter helpers to DownloadEvent and new method for inline

- flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractFileUploadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/InMemoryUploadHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/UploadHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/UploadTransferProgressTest.java
Running successhandler callback from
access so that UI can be updated
directly based on the received data.
> fix: call successhandler from access block

- flow-html-components/src/main/java/com/vaadin/flow/component/html/HtmlObject.java
- flow-html-components/src/main/java/com/vaadin/flow/component/html/IFrame.java
- flow-html-components/src/main/java/com/vaadin/flow/component/html/Image.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlObjectTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/IFrameTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/ImageTest.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractDownloadHandler.java
Automatically sets pre-defined download handlers to inline in data html components.
> fix: Inline download in data html elements

- flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadEvent.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadResponse.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/TransferContext.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressAwareHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressListener.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/AbstractDownloadHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/DownloadEventTest.java
Better explains the methods in `DownloadEvent`, `TransferContext`, `fromInputStream` factory methods in download handler as well as explains -1 for unknown length and handles it accordingly.
> fix: Improve javadoc and handle unknown content length as -1

- flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/InputStreamDownloadHandlerTest.java
Remove the possibility to give
fileName/name to inputStreamDownloadHandler
as the atual downloaded name is
decided on transfer and will in many cases
not match or be confusing to match in 2 places.
> fix: remove name/fileName from inputStreamDownload

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
Makes it possible to write an application method like
```
public static Optional<User> getCurrentUser() {
return AuthenticationContext.getAuthenticatedUser(AppUserInfo.class).map(AppUserInfo::user);
}
```
instead of re-implementing everything from AuthenticationContext
> feat: Make current user available without an AuthenticationContext instance

- flow-server/pom.xml
- flow-server/src/main/java/com/vaadin/experimental/DisabledFeatureException.java
- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
- flow-server/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceSignalsInitializationTest.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServletServiceTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerViteTest.java
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
- signals/src/main/java/com/vaadin/signals/SignalEnvironment.java
Configures Signals environment when VaadinService is initialized, providing Vaadin defaults Executor and ObjectMapper.
Signals functionality is behind a feature flag; if the flag is not set, an exception is thrown at runtime if Signals are used.
Closes #21474
Closes #21475
> feat: initialize signals environment

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTest.java
Do not generate a 1 item
list for the default empty
string in dev mode init
for file extensions.
Fixes #21509
> fix: do not generate list for empty string

- flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
Makes sure that syncId is not updated when resending a queued message.
Perhaps related to #21493
> chore: prevent sync id to be updated on queued messages

- pom.xml
Downgrade the byte-buddy version to prevent class scanning issues caused by Java 24 classes present in the latest multi version artifact.
> chore: downgrade byte-buddy to 1.12.23 (23.6)

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Eliminate the Hilla I18n API feature from the FeatureFlags class.
Part of https://github.com/vaadin/hilla/issues/3502.
> chore(i18n): remove references to Hilla I18n Feature Flag

- vaadin-spring/src/main/java/com/vaadin/flow/spring/scopes/VaadinRouteScope.java
Update the beanstore currentUI
instance if it is changed due
to a reload or bookmark navigation
where the window name stays the same.
Fixes #21417
> fix: Update beanstore ui if changed

- flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
Add methods for checking if
anchor is a download and
setting the download status.
> feat: add method for `download`

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Since version 0.7.0, vite-plugin-checker is an ES Module, and its import in vite.generated.ts fails with ERR_REQUIRE_ESM error. This change downgrades the plugin to a version compatible with Node 20/ Vite 3
> chore: downgrade vite-plugin-checker to support node 20 (23.6)

- signals/src/main/java/com/vaadin/signals/impl/SignalTree.java
- signals/src/test/java/com/vaadin/signals/impl/EffectTest.java
- signals/src/test/java/com/vaadin/signals/impl/SynchronousSignalTreeTest.java
> fix: Allow observing other nodes from an observer

- flow-tests/vaadin-spring-tests/test-spring-boot-contextpath/src/main/resources/application.properties
- flow-tests/vaadin-spring-tests/test-spring-boot-jar/src/main/resources/application.properties
- flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/src/main/resources/application.properties
- flow-tests/vaadin-spring-tests/test-spring-boot-reverseproxy/src/main/resources/application.properties
- flow-tests/vaadin-spring-tests/test-spring-boot-scan/src/main/resources/application.properties
- flow-tests/vaadin-spring-tests/test-spring-boot/src/main/resources/application.properties
- flow-tests/vaadin-spring-tests/test-spring-war/src/main/resources/application.properties
- vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletConfiguration.java
For instance Swagger uses ResourceHandlerRegistry to register a handler for /swagger-ui/index.html and this is now called without excluding any url from Vaadin
> fix: Use handlers registered using ResourceHandlerRegistry

- flow-data/src/test/java/com/vaadin/flow/data/binder/Jsr303Test.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/NotEmptyTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/ComponentTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/InputTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/NativeTableTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/RangeInputTest.java
- flow-server/src/main/java/com/vaadin/flow/internal/JsonSerializer.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ThemeWrapper.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
- flow-tests/test-frontend/test-bun/src/main/java/com/vaadin/flow/mixedtest/ui/MissingDependenciesView.java
- flow-tests/test-frontend/test-npm/src/main/java/com/vaadin/flow/mixedtest/ui/MissingDependenciesView.java
- flow-tests/test-frontend/test-pnpm/src/main/java/com/vaadin/flow/mixedtest/ui/MissingDependenciesView.java
- flow-tests/test-frontend/vite-test-assets/src/main/java/com/vaadin/viteapp/views/template/TemplateView.java
- flow-tests/test-npm-only-features/test-npm-bytecode-scanning/src/main/java/com/vaadin/flow/testnpmonlyfeatures/bytecodescanning/ByteCodeScanningView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/ui/SerializationTest.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/ui/ToStringTest.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerClassLoaderTest.java
Use getDeclaredConstructor().newInstance()
instead of using the deprecated
class.newInstance()
Closes #9331
> chore: use constructor.newinstance

- signals/src/main/java/com/vaadin/signals/Signal.java
- signals/src/main/java/com/vaadin/signals/impl/UsageTracker.java
- signals/src/test/java/com/vaadin/signals/ValueSignalTest.java
The change value cannot be extracted if there's no data node in the tree. Check for this both when creating the usage instance and when later evaluating whether it has changes.
Note that removing a node is not seen as changing the node itself but only as a change to the node's parent.
> fix: Avoid NPE when tracking usage for removed nodes

- signals/src/main/java/com/vaadin/signals/ValueSignal.java
- signals/src/test/java/com/vaadin/signals/ValueSignalTest.java
For some unknown reason, the `update` operation was wrapped in `runWithoutTransaction` which as a side effect meant that updates could be triggered from inside a readonly transaction. I don't see any reason for why `update` would be different from all the other operations, and there's also no previous test that would show why it's necessary.
> Disallow update operation in readonly transactions

- signals/src/main/java/com/vaadin/signals/Signal.java
- signals/src/test/java/com/vaadin/signals/impl/EffectTest.java
A null value in the node caused the usage change value to be an empty optional which was interpreted as a removed node and thus no changes rather than comparing with the original value.
Fixes #21778
> fix: Distinguish between missing node and node with null value

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/CleanFrontendUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
For pnpm usage write the overrides
section under the pnpm object
instead of the root of the package.json
Fixes #21724
Fixes #21682
add all component versions to overrides.
Will use $NAME for existing dependencies
and devDpendencies.
For other components in vaadin-versions
and vaadin-core-versions version value
will be added to overrides.
Keep existing overrides content from othe system if any
Keep the existing overrides when
moving from npm to pnpm and vice versa
Refactor test to use Jackson
> fix: when using pnpm write overrides under pnpm (CP: 24.7)

- vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Removes the AuthenticationContext bean definition from VaadinWebSecurity so there's a single overridable bean in SpringSecurityAutoConfiguration.
Fixes #21835
> fix: fix AuthenticationContext bean duplicated definition

- vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Removes the AuthenticationContext bean definition from VaadinWebSecurity so there's a single overridable bean in SpringSecurityAutoConfiguration.
Fixes #21835
> fix: fix AuthenticationContext bean duplicated definition (#21845)

- vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
This reverts commit f771039b8eda03a929ff97b99606fd82e7eca212.
> Revert "fix: fix AuthenticationContext bean duplicated definition (#21845) (#21846) (#21847)" (24.8)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassInfo.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithByteCodeScannerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
Maintains a predictable ordering of classes found during class scanning to ensure that iteration over collected elements is consistent with the order of visited classes. This fixes potential test inconsistencies in tests like UpdateImportsWithByteCodeScannerTest where order-dependent assertions rely on stable output.
> chore: ensure consistent order of scanned classes

- flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTest.java
The PR adds `--disable-backgrounding-occluded-windows` to Headless Chrome options to ensure `requestAnimationFrame` callbacks aren't skipped when running integration tests locally on macOS.
Although https://github.com/teamcapybara/capybara/issues/2796#issuecomment-2678172710 suggests that the issue only occurs when running tests in parallel, I'm actually facing it when running a single test using `-Dfailsafe.forkCount=1` on my local machine in https://github.com/vaadin/flow-components/pull/7681:
```
mvn verify -f vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests -Dit.test=TreeGridMultiSelectionIT -Dfailsafe.forkCount=1
```
Adding the mentioned flag makes this test – and many others like ItemCountCallbackComboBoxIT, MenuBarPageIT – pass.
> test: disable backgrounding occluded windows in headless chrome

- flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapper.java
Deprecates `HierarchyMapper` with plans to remove it in Vaadin 25.
Part of #21873
> refactor: deprecate HierarchyMapper

- pom.xml
Do not rely on transitive dependency to use jcip annotations
> chore: bump license-checker to 1.13.5 (#21904) (CP: 2.12)

- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataProvider.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataChangeEvent.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataProvider.java
Deprecates `refreshItem(T item, boolean refreshChildren)` in favor of `refreshAll`. It cannot be implemented for flat data providers and is already working inconsistently for current data providers. The method will be removed in Vaadin 25. 
Part of https://github.com/vaadin/flow/issues/21873
> refactor: deprecate refreshItem(item, refreshChildren)

- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataProvider.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataChangeEvent.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataProvider.java
It was decided to keep the `refreshItem(T item, boolean refreshChildren)` method available for non-flat data providers in the new version of  `HierarchicalDataCommunicator`. It doesn't fix scroll issues in every case, but it is known to help avoid them in some situations – for example when the refreshed item doesn't contain _expanded_ children. Since moving to flat data providers can be not straightforward, keeping this method around is the safer option, at least until Vaadin 26.
The PR also improves the JavaDoc of this method to warn about possible content shifts when it's called on items with more than one level of nesting.
Part of #21873
> refactor: undeprecate refreshItem, improve its JavaDoc

- flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/InputStreamDownloadHandlerTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DownloadHandlerView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/TransferProgressListenerView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DownloadHandlerIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/TransferProgressListenerIT.java
When a callback provided to DownloadHandler.fromInputStream throws an IOException the transfer progress listeners are not notified about the error. This change caught IOException potentially thrown by the callback and notifies the registered listeners.
Part of #21931
> fix: notify listeners when InputStream download handler callback fails

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorAsyncTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorDataTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorTest.java
The PR deprecates `setRequestedRange` and `computeRequestedRange` in favor of `setViewportRange` and `computeViewportRange`. The deprecated methods will be removed in Vaadin 26.
Fixes https://github.com/vaadin/flow/issues/21875
> refactor: deprecate setRequestedRange in favor of setViewportRange

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSecurityConfigurer.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/stateless/VaadinStatelessSecurityConfigurer.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinSecurityConfigurerTest.java
See https://github.com/vaadin/hilla/pull/3807, where the issue currently manifests.
VaadinSavedRequestAwareAuthenticationSuccessHandler isn't actually saved request aware unless RequestCache is correctly shared with it in the configuration, which VaadinSecurityConfigurer was failing to do due to order of events: authentication is configured before customizing request cache. This change makes sure that VaadinDefaultRequestCache instance is set for VaadinSavedRequestAwareAuthenticationSuccessHandler during configuration.
> fix(vaadin-spring): enable client-side redirects for TypeScript login (#21980) (CP: 24.8)

- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSecurityConfigurer.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/stateless/VaadinStatelessSecurityConfigurer.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinSecurityConfigurerTest.java
See https://github.com/vaadin/hilla/pull/3807, where the issue currently manifests.
VaadinSavedRequestAwareAuthenticationSuccessHandler isn't actually saved request aware unless RequestCache is correctly shared with it in the configuration, which VaadinSecurityConfigurer was failing to do due to order of events: authentication is configured before customizing request cache. This change makes sure that VaadinDefaultRequestCache instance is set for VaadinSavedRequestAwareAuthenticationSuccessHandler during configuration.
> fix(vaadin-spring): enable client-side redirects for TypeScript login (#21980) (CP: 24.9)

- flow-server/pom.xml
- pom.xml
https://nvd.nist.gov/vuln/detail/CVE-2025-48976
https://nvd.nist.gov/vuln/detail/CVE-2025-48924
> chore: upgrade commons dependencies to resolve vulnerability (23.6)

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataChangeEvent.java
The `isRefreshChildren` method was forgotten to be undeprecated.
Follow-up to #21953
> refactor: undeprecate isRefreshChildren method

- flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapper.java
The PR deprecates the protected `setFilter` method in `HierarchicalDataCommunicator` and also improves deprecation texts for other deprecated methods.
Part of #21873
> refactor: deprecate setFilter, improve deprecation texts

- flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/ClassDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadEvent.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadResponse.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/FileDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/ServletResourceDownloadHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/streams/TransferContext.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/AbstractDownloadHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/ClassDownloadHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/FileDownloadHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/InputStreamDownloadHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/streams/ServletResourceDownloadHandlerTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DownloadHandlerView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DownloadHandlerIT.java
Adds `DownloadResponse#exception` and `TransferContext#exception` of type `java.lang.Exception`. Updates DownloadHandlers to fill exception automatically in case of `IOException` (or `RuntimeException`, or error in `DownloadResponse` for `InputStreamDownloadHandler`).
Fixes: #21930
> feat: add Exception to DownloadResponse and TransferContext

- flow-server/src/main/java/com/vaadin/flow/server/communication/PushAtmosphereHandler.java
Fixes #21782
Changes the log level from ERROR to DEBUG for the specific IOException that occurs when a client connection dies during push communication. This reduces noise in logs, especially during integration tests.
This is similar to https://github.com/vaadin/flow/blob/c80f04ca11951e72672840c4c90123e5d4adbe04/flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java#L90
> fix: log "Connection remotely closed" IOException at debug level

- flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/AbstractHierarchicalDataCommunicatorTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorDataRefreshTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorFlatHierarchyTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorIndexPathResolutionTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorViewportTest.java
The PR reduces HierarchicalDataCommunicator's network usage. Instead of sending the entire viewport on every flush, it now sends `$connector.set` calls with just the new / changed items when possible. A full viewport is still sent when an action changes the flat size.
Depends on 
- https://github.com/vaadin/flow-components/pull/7905
Part of #21989
> refactor: Reduce HierarchicalDataCommunicator's network usage

- flow-client/src/main/java/com/vaadin/client/Console.java
Allow dynamic control of browser console logging in production mode by checking localStorage for "vaadin.browserLog" flag. Developers can now enable client-side logging in production using:
localStorage.setItem('vaadin.browserLog', 'true')
This helps with debugging production issues without requiring JAR modifications or rebuilds.
Fixes #17935
> feat: enable client-side logging in production via localStorage flag

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DebugWindowConnectionLicenseCheckTest.java
When a Vaadin user wants to Log in or Sing Up in vaadin.com he can click on the corresponding button on the Pre-trial splash screen.
Vaadin then re-validates the Pre-Trial status and sometimes it passes it (trial not started) and sometimes throws (trial expired). 
Vaadin should not re-validate the status once again when Log in is clicked. This just removes the Pre-Trial capability from the  Log in/Sign Up handler.
> fix: Skip pre-trial validation when clicking on Log in or Sign up

- signals/src/main/java/com/vaadin/signals/impl/AsynchronousSignalTree.java
The need was discovered when explaining the algorithm to others
> Add clarifying comments to async signal confirmation

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImportTest.java
Log the component styles that
are not applied with missing flag.
```
WARN com.vaadin.flow.server.frontend.TaskUpdateThemeImport - Theme 'app-theme' contains component styles, but the 'themeComponentStyles' feature flag is not set, so component styles will not be applied for 
vaadin-radio-button.css
vaadin-text-field.css
```
> fix: Log available component styles

- flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java
Fix the javadoc for
acceptNullValues that
mistakenly says that
true throws an exception.
Fixes #22186
> fix: Fix faulty javadoc for acceptNullValues

- flow-server/src/main/java/com/vaadin/flow/dom/Element.java
- flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
Not depending on what type array
is given to Serializable... the
copied array should be of type
Serializable[] to enable
adding Element to it.
> fix: Array type should be serializable

- flow-server/src/main/java/com/vaadin/flow/component/ModalityMode.java
Introduce ModalityMode with three modes: STRICT, VISUAL and MODELESS.
Part of: #22279
This PR just adds the new enum available for all components without any functionality.
> feat: add ModalityMode enum

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react19/package.json
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
- flow-tests/test-themes/pom-devbundle.xml
Left out
```
typescript  5.8.3  →  5.9.2
react-router  7.6.3  →  7.9.1
```
React router could maybe be included?
> chore: Bump frontend dependencies (24.9)

- flow-server/src/main/resources/plugins/plugins.json
- flow-server/src/main/resources/plugins/vite-plugin-vaadin-bundles/index.ts
- flow-server/src/main/resources/plugins/vite-plugin-vaadin-bundles/package.json
- flow-server/src/main/resources/vite.generated.ts
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskInstallFrontendBuildPluginsTest.java
The PR extracts the vaadin bundles plugin into an individual internal package, `@vaadin/vite-plugin-vaadin-bundles`, to reduce the clutter in `vite.generated.ts`.
> refactor: extract vaadin bundles plugin into internal package

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
The async dependency was originally added in PR #13547 to fix a Prototype Pollution security vulnerability. This is no longer needed as the vulnerability has been resolved in newer versions and there are no direct dependencies requiring async.
- Removed async@3.2.6 from default/package.json devDependencies
- Updated test to reflect the removal
Fixes #21507
> fix: remove pinned async dev dependency from default package.json

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
The feature flags import in dev mode with the hot reload disabled ends up after the custom elements definition. This is problematic for cases, like the `layoutComponentsImprovements`, where the feature flag value is checked at the definition time to decide whether some CSS styles should be added or not.
This change moves the appending of the feature flags import to the end of the method, and adds it at the start of the file.
Fixes vaadin/web-components#9571
- Bugfix
> fix: ensure to add feature-flags import at the start of bundle

- flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/AbstractHierarchicalDataCommunicatorTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorBasicTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorDataGenerationTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorKeyGenerationTest.java
This PR updates HierarchicalDataCommunicator to clean up no longer visible items, their client keys and generated data in `confirmUpdate` instead of `flush`.  Removing client keys from `keyMapper` in `flush` is too early, since there may be new pending client requests (for example, item selection) that were made while the current request was in progress and they might still rely on those keys.
Fixes https://github.com/vaadin/flow-components/issues/8040
> fix: Clean up client keys only after viewport update is confirmed

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
If a legacy frontend folder is found,
log a warning instead of throwing.
Related to https://github.com/vaadin/flow/issues/22126
> fix: instead of throwing, warn if legace frontend folder is used

- flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/main/java/com/vaadin/flow/component/page/ExtendedClientDetails.java
- flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
- flow-server/src/main/java/com/vaadin/flow/dom/Element.java
- flow-server/src/main/java/com/vaadin/flow/internal/JacksonCodec.java
- flow-server/src/main/java/com/vaadin/flow/internal/JsonCodec.java
- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/AbstractServerHandlers.java
- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ClientCallableHandlers.java
- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/PolymerServerEventHandlers.java
- flow-server/src/main/java/com/vaadin/flow/shared/JsonConstants.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
- flow-server/src/test/java/com/vaadin/flow/component/page/HistoryTest.java
- flow-server/src/test/java/com/vaadin/flow/component/page/PageTest.java
- flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentTest.java
- flow-server/src/test/java/com/vaadin/flow/dom/ElementJacksonTest.java
- flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
- flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
- flow-server/src/test/java/com/vaadin/flow/internal/JacksonCodecTest.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExecJavaScriptView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExecJavaScriptIT.java
Implements bean-only serialization using Jackson.
Beans are serialized on server and handled as standard JS objects on client.
> feat: Add bean serialization support

- flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
- flow-server/src/main/java/com/vaadin/flow/component/page/PendingJavaScriptResult.java
- flow-server/src/main/java/com/vaadin/flow/dom/Element.java
- flow-server/src/main/java/com/vaadin/flow/internal/JacksonCodec.java
- flow-server/src/main/java/com/vaadin/flow/internal/JsonCodec.java
- flow-server/src/test/java/com/vaadin/flow/internal/JacksonCodecTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExecJavaScriptView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExecJavaScriptIT.java
- Extend JacksonCodec.decodeAs() to deserialize JSON objects into Java beans using Jackson
- Extend JsonCodec.decodeAs() with similar bean deserialization support for consistency
- Add comprehensive unit tests for simple beans, nested beans, null handling, and error cases
- Add default constructors to test bean classes for Jackson compatibility
- Add integration tests with new buttons for testing bean return values from client
- Add ExecJavaScriptIT tests to verify complete client-to-server bean deserialization flow
- Maintain full backward compatibility for existing primitive type decoding
- Support both simple and complex nested bean structures returned from JavaScript
This enables JavaScript code to return complex objects that are automatically
deserialized into typed Java beans on the …
> feat: Add bean deserialization support for executeJs return values

- flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/pom.xml
- flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/src/main/java/com/vaadin/hilla/EndpointController.java
- flow-tests/vaadin-spring-tests/test-spring-security-flow-standalone-routepathaccesschecker/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/RequestUtil.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/SpringAccessPathChecker.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSecurityConfigurer.java
- vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/security/UserPrincipalRequestMatcherSpringAccessPathCheckerTest.java
- vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinSecurityConfigurerTest.java
When Spring Security request matchers are executed within SpringPathAccessChecker the request object is a stub instance that throw UnsupportedOperationException for many methods. This can cause failure when the path access checker is used in combination with request matchers that, for example, try to access the request user principal. An example is the pre-configured 'isAllowedHillaView' matcher.
This change wraps the request matchers configured by Vaadin so that the request principal is taken from the Spring Security context, if not available on the request.
In addition provides documentation and helper to set a global HttpServletRequestTransformer to augment all requests handled by WebInvocationPrivilegeEvaluator with the proper getUserPrincipal method override.
Fixes #22284
> fix: make sure request principal is available (#22368) (CP: 24.9)

- flow-polymer-template/src/test/java/com/vaadin/flow/server/communication/rpc/PolymerPublishedServerEventHandlerRpcHandlerTest.java
- flow-server/src/main/java/com/vaadin/flow/internal/JacksonUtils.java
- flow-server/src/test/java/com/vaadin/flow/component/ComponentEventBusTest.java
- flow-server/src/test/java/com/vaadin/flow/internal/JacksonCodecTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandlerTest.java
Decoding null to primitive should
not fail as dom event data
may be missing parts sent from the client.
> fix: Null for primitive should not fail decode

- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
avoids flooding log output with warnings
> fix: check legacy frontend folder from prepare step

- pom.xml
> chore: update ASM to 9.9 to work with Java 26

- .github/workflows/formatter.yml
- CLAUDE.md
- flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
- flow-client/src/main/java/com/vaadin/client/PolymerUtils.java
- flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
- flow-client/src/main/java/com/vaadin/client/flow/binding/ServerEventObject.java
- flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
- pom.xml
Replace maven formatter plugin with spotless plugin (v2.46.1) for code formatting.
Configuration includes:
- Java formatting using Eclipse formatter (VaadinJavaConventions.xml)
Usage:
- mvn spotless:check - validate formatting
- mvn spotless:apply - apply formatting
> chore: migrate from formatter plugin to spotless
