pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2563)

Use stable js interop version.

---

flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java
flow-components-parent/flow-components/src/test/java/com/vaadin/ui/grid/GridTest.java

Fixes #2579
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2582)

Select only if not already selected

---

flow-spring-addon/pom.xml
pom.xml

Fixes #1967
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2587)

Make a new submodule for Spring add-on

---

flow-tests/pom.xml
flow-tests/test-spring-boot/pom.xml
flow-tests/test-spring-boot/src/main/frontend/empty.txt
flow-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/boot/TestServletInitializer.java
flow-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/boot/TestSpringServlet.java
flow-tests/test-spring-boot/src/main/webapp/empty.txt
flow-tests/test-spring-war/pom.xml
flow-tests/test-spring-war/src/main/frontend/empty.txt
flow-tests/test-spring-war/src/main/java/com/vaadin/flow/spring/war/TestServletInitializer.java
flow-tests/test-spring-war/src/main/java/com/vaadin/flow/spring/war/TestSpringServlet.java
flow-tests/test-spring-war/src/main/webapp/empty.txt

Two modules: tests for web app as a Spring boot app and as a deployable
WAR
Fixes #457
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2588)

Add integration test modules for Spring

---

flow-server/src/main/java/com/vaadin/router/Router.java
flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java
flow-server/src/test/java/com/vaadin/router/RouterTest.java
flow-server/src/test/java/com/vaadin/server/startup/RouteRegistryInitializerTest.java

Now generated routes never start or end with '/'
Closes #2562
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2589)

Fix route string generation.

---

flow-server/src/main/java/com/vaadin/router/Router.java
flow-server/src/test/java/com/vaadin/router/RouterTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2658)

When navigating break if already navigated to url.

---

flow-client/pom.xml
flow-components-parent/demo-flow-components/pom.xml
flow-components-parent/flow-code-generator-api/pom.xml
flow-components-parent/flow-code-generator-api/src/main/resources/version.prop
flow-components-parent/flow-code-generator/pom.xml
flow-components-parent/flow-components-test/pom.xml
flow-components-parent/flow-components/pom.xml
flow-components-parent/flow-generated-components/pom.xml
flow-components-parent/pom.xml
flow-data/pom.xml
flow-html-components/pom.xml
flow-server/pom.xml
flow-spring-addon/pom.xml
flow-test-util/pom.xml
flow-tests/pom.xml
flow-tests/test-root-context/pom.xml
flow-tests/test-scalability/pom.xml
flow-tests/test-servlet/pom.xml
flow-tests/test-spring-boot/pom.xml
flow-tests/test-spring-common/pom.xml
flow-tests/test-spring-war/pom.xml
flow-tests/test-subcontext/pom.xml
flow/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2662)

Use project version for Flow dependencies

---

flow-server/pom.xml

Fix for #2551
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2663)

Update byte buddy version to 1.7.5 version.

---

flow-client/src/main/java/com/vaadin/client/ExecuteJavaScriptElementUtils.java
flow-client/src/test-gwt/java/com/vaadin/client/GwtExecuteJavaScriptElementUtilsTest.java
flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/ChildTemplate.java
flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/TemplateInjectsTemplate.java
flow-tests/test-spring-common/src/main/resources/META-INF/resources/components/ChildTemplate.html
flow-tests/test-spring-common/src/main/resources/META-INF/resources/components/ParentTemplate.html
flow-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/ParentTemplateIT.java

Fix for #2653
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2661)

Consider not yet defined custom elements on element attach

---

flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java
flow-server/src/main/java/com/vaadin/router/NotFoundException.java
flow-server/src/test/java/com/vaadin/router/RouterTest.java

Now rerouting works also from the
setParameter method for HasUrlParameter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2665)

Fix rerouting from HasUrlParameter::setParameter

---

build-tools/src/test/java/com/vaadin/LicenseCheckTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2673)

Whitelist another MIT license name.

---

flow-client/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2675)

Avoid unncessary dependency on asm in all projects

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2679)

Clean error screenshots.

---

.gitignore
flow-components-parent/flow-components-test/src/main/java/com/vaadin/flow/components/it/grid/GridView.java
flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridViewIT.java
flow-components-parent/flow-components/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2686)

Unignore Grid test for changing DataProviders. Update grid version.

---

flow-server/src/main/java/com/vaadin/router/Router.java
flow-server/src/main/java/com/vaadin/ui/UIInternals.java
flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractParallelTestBenchTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/servlet/RouterTestServlet.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2687)

Same location navigation should be UI dependent.

---

flow-tests/pom.xml
flow-tests/test-spring/pom.xml
flow-tests/test-spring/src/main/java/com/vaadin/flow/spring/TestConfiguration.java
flow-tests/test-spring/src/main/java/com/vaadin/flow/spring/mvc/TestWebAppInitializer.java

Fix for #2600
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2691)

Add Spring MVC test module (no Spring Boot)

---

flow-spring-addon/src/main/java/com/vaadin/spring/VaadinMVCWebAppInitializer.java
flow-spring-addon/src/main/java/com/vaadin/spring/annotation/EnableVaadin.java
flow-spring-addon/src/main/java/com/vaadin/spring/annotation/SpringComponent.java
flow-tests/test-spring/src/main/java/com/vaadin/flow/spring/TestConfiguration.java
flow-tests/test-spring/src/main/java/com/vaadin/flow/spring/mvc/TestWebAppInitializer.java

Fix for #2628
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2694)

Add the abstract web initializer class for Spring Web MVC application

---

flow-server/src/main/java/com/vaadin/server/webjar/SemanticVersion.java
flow-server/src/test/java/com/vaadin/server/webjar/SemanticVersionTest.java
flow-server/src/test/java/com/vaadin/server/webjar/WebJarBowerDependencyTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2701)

Fix semantic versioning resolutions.

---

flow-server/src/main/java/com/vaadin/flow/nodefeature/PushConfigurationMap.java
flow-server/src/main/java/com/vaadin/shared/ui/Transport.java
flow-server/src/main/java/com/vaadin/ui/Push.java
flow-server/src/main/java/com/vaadin/ui/PushConfiguration.java
flow-server/src/main/java/com/vaadin/util/AnnotationReader.java
flow-server/src/test/java/com/vaadin/flow/nodefeature/PushConfigurationMapTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/push/BasicPushLongPollingUI.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/push/BasicPushWebsocketUI.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/push/BasicPushWebsocketXhrUI.java

Fixes #2651.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2716)

Move Transport class to com.vaadin.shared.ui

---

flow-html-components/src/main/java/com/vaadin/ui/html/Anchor.java
flow-html-components/src/test/java/com/vaadin/ui/html/AnchorTest.java
flow-html-components/src/test/java/com/vaadin/ui/html/ComponentProperty.java
flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java

Should fix #2704. I didn't find where tests for basic HTML elements are, but I'll commit those if someone point me in the right direction!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2718)

Do not remove href attribute when empty

---

flow-html-components/src/main/java/com/vaadin/ui/html/DescriptionList.java
flow-html-components/src/main/java/com/vaadin/ui/html/ListItem.java
flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java
flow-html-components/src/main/java/com/vaadin/ui/html/Paragraph.java
flow-html-components/src/main/java/com/vaadin/ui/html/UnorderedList.java
flow-html-components/src/test/java/com/vaadin/ui/html/ComponentProperty.java
flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java
flow-html-components/src/test/java/com/vaadin/ui/html/DescriptionListTest.java
flow-html-components/src/test/java/com/vaadin/ui/html/HtmlComponentSmokeTest.java
flow-html-components/src/test/java/com/vaadin/ui/html/ListItemTest.java
flow-html-components/src/test/java/com/vaadin/ui/html/OrderedListTest.java
flow-html-components/src/test/java/com/vaadin/ui/html/ParagraphTest.java
flow-html-components/src/test/java/com/vaadin/ui/html/UnorderedListTest.java
flow-server/src/main/java/com/vaadin/ui/Tag.java

Fixes #2535 adding `<p>` elements and also `<li>`, `<ul>`, `<ol>`, `<dl>`, `<dt>` and `<dd>`.
Tests are coming.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2719)

Add missing base HTML elements

---

flow-server/src/main/java/com/vaadin/router/InternalServerError.java
flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java
flow-server/src/main/java/com/vaadin/router/RouteNotFoundError.java
flow-server/src/test/java/com/vaadin/router/RouterTest.java

Error location when redirectingToError should
be the same as the one redirected from.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2725)

Location should stay for error redirect.

---

flow-server/pom.xml

The old one was moved: https://mvnrepository.com/artifact/org.hibernate/hibernate-validator
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2729)

Use correct hibernate validator.

---

flow-spring-boot-starter/pom.xml
flow-spring-boot-starter/src/main/resources/META-INF/spring.provides
flow-tests/test-spring-boot/pom.xml
pom.xml

Fix for #2586
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2723)

Create spring boot starter module

---

flow-server/src/main/java/com/vaadin/flow/template/angular/parser/TemplateParser.java

Please check if the way I am converting the InputStream to a String is valid. I may missed a helper class that is doing that already.
It also forced me to change the exception handling a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2734)

#2730: configures JSoup to keep case of tags

---

flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc

it is quite confusing about the `${project.version}` and `${flow.version}`
as we just changed everything to `${flow.version}`, let us keep it in this way
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2738)

update a misleading part in tutorial

---

flow-spring-addon/src/main/java/com/vaadin/spring/VaadinConfigurationProperties.java

Fix for #2748
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2751)

Add setters for VaadinConfigurationProperties class

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2760)

Update to new gwt.

---

flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java
flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js
flow-components-parent/flow-components/src/main/resources/META-INF/resources/vaadin-grid-flow-selection-column.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2759)

Rename dynamically added methods in gridConnector

---

flow-server/src/main/java/com/vaadin/server/communication/StreamReceiverHandler.java

The used getFieldName is the name of the Field
and will always return 'file'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2788)

Use getName to get FileName.

---

flow-components-parent/flow-components-test/pom.xml

Fix for #2523
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2789)

Exclude SQ from components test

---

webjars-bom/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2804)

Add vaadin upload to webjars-bom

---

flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/SourceContentResolver.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2809)

Check that resource actually is found.

---

flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/CheckboxIT.java
flow-components-parent/flow-components-test/src/main/java/com/vaadin/flow/components/it/textfield/TextFieldView.java
flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/textfield/TextFieldViewIT.java
flow-server/src/main/java/com/vaadin/ui/ComponentMetaData.java
flow-server/src/main/java/com/vaadin/ui/ComponentUtil.java
flow-server/src/test/java/com/vaadin/ui/ComponentMetaDataTest.java

Fix for vaadin-text-field-flow/issues/4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2811)

Scan Synchronized annotation for all superclasses and superinterfaces

---

flow-components-parent/flow-generated-components/json_metadata/paper-dialog.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-button.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-checkbox.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-text-field.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-upload-file.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-upload.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/button/GeneratedVaadinButton.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/checkbox/GeneratedVaadinCheckbox.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/combobox/GeneratedVaadinComboBoxDropdownWrapper.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/datepicker/GeneratedVaadinInfiniteScroller.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/dialog/GeneratedVaadinDialog.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/paper/dialog/GeneratedPaperDialog.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextField.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/upload/GeneratedVaadinUpload.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/upload/GeneratedVaadinUploadFile.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2824)

Generated Upload element java wrapper

---

flow-components-parent/flow-component/.gitignore
flow-components-parent/flow-component/pom.xml

so we dont need to push driver.xml file to each component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2821)

modify the configuration for selenium

---

flow-components-parent/flow-components-test/src/main/java/com/vaadin/flow/components/it/combobox/ComboBoxView.java
flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/combobox/ComboBoxViewIT.java
flow-components-parent/flow-generated-components/json_metadata/vaadin-combo-box-dropdown-wrapper.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-combo-box-dropdown.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-combo-box-item.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-combo-box-light.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-combo-box.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/combobox/GeneratedVaadinComboBox.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/combobox/GeneratedVaadinComboBoxDropdown.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/combobox/GeneratedVaadinComboBoxDropdownWrapper.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/combobox/GeneratedVaadinComboBoxItem.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/combobox/GeneratedVaadinComboBoxLight.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/datepicker/GeneratedVaadinInfiniteScroller.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json
flow-components-parent/flow-webcomponent-api-analyzer/pom.xml
webjars-bom/pom.xml

Added a test for the specific case..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2827)

Update combobox webcomponent version to 3.0.1. Regenerate flow component and update bom.

---

flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoTest.java

overwrite the getTestPath method, so that we don't need to 
overwrite it every time for individual component test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2829)

modify component demo test class

---

webjars-bom/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2837)

Add progress-bar dependency to bom

---

flow-server/src/main/java/com/vaadin/router/InternalServerError.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/servlet/RouterTestServlet.java

Fixes #2724
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2836)

Log stacktrace in the default error view

---

flow-tests/test-spring-boot/pom.xml
flow-tests/test-spring-war/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2841)

WIP Do Not Merge- Try to override selenium version

---

flow-components-parent/flow-component-demo-helpers/pom.xml
webjars-bom/pom.xml

solve the long error when runs the demoServer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2840)

Add websocket-server dependency

---

flow-client/src/main/java/com/vaadin/client/communication/ServerRpcQueue.java

Fix for #2337
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2834)

Skip scheduled flush if clear() is called

---

flow-components-parent/flow-generated-components/json_metadata/vaadin-progress-bar.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/progressbar/GeneratedVaadinProgressBar.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json
webjars-bom/pom.xml

Also upgrade valo-theme dependency version to 2.0.0-alpha4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2848)

 Upgrade vaadin-progress-bar to 1.0.0-alpha6

---

flow-components-parent/flow-component/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2854)

Add jetty-maven-plugin for component CI build

---

flow-components-parent/flow-generated-components/json_metadata/vaadin-tab.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-tabs.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/tabs/GeneratedVaadinTab.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/tabs/GeneratedVaadinTabs.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json
webjars-bom/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2852)

Generated Tabs element Java wrapper

---

flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoTest.java
flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridMultiSelectionModel.java
flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridSingleSelectionModel.java
flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java
flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/GridNoneSelectionModel.java
flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/GridSelectionModel.java
flow-data/src/main/java/com/vaadin/data/provider/DataCommunicator.java
flow-data/src/main/java/com/vaadin/data/provider/DataGenerator.java

Refactors grid selection models and columns to use data generators.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2850)

Introduce DataGenerators

---

flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2859)

Correct cache update

---

flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js
webjars-bom/pom.xml

Update gridConnector to work with the new cache structure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2866)

Update Grid to 4.1.0.alpha2.

---

flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java
flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/GridViewIT.java
flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java
flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2865)

Add server side toggling of row details

---

flow-server/src/main/java/com/vaadin/server/communication/rpc/StringToNumberDecoder.java
flow-server/src/test/java/com/vaadin/server/communication/rpc/StringToNumberDecoderTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2860)

Correct abstract Number handling in RPC decoder

---

flow-server/src/main/java/com/vaadin/ui/common/HasStyle.java
flow-server/src/test/java/com/vaadin/ui/HasStyleTest.java

Fix for #2308
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2898)

Use live ClassList for HasStyle interface instead of a copy

---

flow-components-parent/demo-flow-components/pom.xml

Due to https://github.com/vaadin/flow/commit/a9effafc96e650dd8b6a7ecdb38fa2c6322c16bf
there is no Servlet.java to exclude.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2899)

Remove exclusion that excludes nothing.

---

drivers.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2911)

Update Chrome drivers.

---

flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java
flow-server/src/test/java/com/vaadin/server/BootstrapHandlerTest.java

Fix for #2477
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2893)

Add UA compatible meta tag in bootstrap handler

---

flow-server/src/main/java/com/vaadin/server/communication/PushHandler.java

Port change added in Fw 8.1.0.alpha5
Original commit: https://github.com/vaadin/framework/commit/60a6e0282e8e013acb56821f30573c65f1a6c36d
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2937)

Check for NullPointer to remove exception spam

---

flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java
flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/metadata/ComponentPropertyBaseData.java
flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java
flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/registry/PropertyNameRemapRegistryTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2934)

Correct component generator code

---

flow-documentation/get-started.asciidoc
flow-documentation/src/main/java/com/vaadin/flow/tutorial/getstarted/MainView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2940)

Fix documentation for new api.

---

flow-client/src/main/java/com/vaadin/client/Profiler.java

Port changes from Fw 8.1.0.alpha6
Original PR:
https://github.com/vaadin/framework/pull/9033
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2951)

Ignore all external events in the Profiler

---

flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/server/VaadinSession.java
flow-server/src/main/java/com/vaadin/server/communication/PushHandler.java
flow-server/src/main/java/com/vaadin/shared/ApplicationConstants.java

Port changes from Fw 8.1.0.alpha5
Original commits:
* https://github.com/vaadin/framework/commit/a4a4d9e064f06ad4cdc2801db75955872a3acf45
* https://github.com/vaadin/framework/commit/fa9bdbef6601f66bd2d14d07595bfa7e3e609997
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2949)

Use separate identifier for push connections

---

flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/server/communication/StreamReceiverHandler.java
flow-server/src/main/java/com/vaadin/shared/ApplicationConstants.java

Port change from Fw 8.1.0.alpha7
Original PR:
* https://github.com/vaadin/framework/pull/9123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2954)

Include charset in text/html responses

---

pom.xml
settings.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2958)

Change snapshot repository

---

flow-server/src/main/java/com/vaadin/ui/common/HasStyle.java
flow-server/src/test/java/com/vaadin/ui/HasStyleTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2960)

Add multiple class names handling to HasStyle (#2955)

---

flow-components-parent/flow-components/src/main/java/com/vaadin/ui/passwordfield/PasswordField.java
flow-components-parent/flow-components/src/main/java/com/vaadin/ui/textfield/TextField.java
flow-components-parent/flow-components/src/test/java/com/vaadin/data/BinderTest.java
flow-components-parent/flow-components/src/test/java/com/vaadin/data/BinderValidationStatusTest.java
flow-components-parent/flow-generated-components/json_metadata/vaadin-password-field.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-text-area.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-text-field.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinPasswordField.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextArea.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextField.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json
webjars-bom/pom.xml

Fix for vaadin/vaadin-text-field#20
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2948)

Generate TextArea and metadata for it

---

flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java

Port only Javadoc changes in PR from Fw 8.1.0.alpha7
Original PR:
https://github.com/vaadin/framework/pull/9164
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2962)

Add Javadoc to BootstrapHandler

---

flow-server/src/main/java/com/vaadin/server/VaadinService.java

Port change from Fw 8.1.0.beta1
Original PR:
https://github.com/vaadin/framework/pull/9285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2964)

Make VaadinService#isUIActive() public

---

flow-server/src/main/java/com/vaadin/server/communication/AtmospherePushConnection.java

Port change from Fw 8.1.0.rc2
Original PR:
https://github.com/vaadin/framework/pull/9622
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2965)

Change sendMessage access modifier to protected

---

flow-client/src/main/java/com/vaadin/client/BrowserInfo.java
flow-client/src/main/java/com/vaadin/client/ResourceLoader.java
flow-server/src/main/java/com/vaadin/server/WebBrowser.java
flow-server/src/main/java/com/vaadin/shared/BrowserDetails.java

Port change from Fw 8.1.0.alpha7
Original PR:
https://github.com/vaadin/framework/pull/9138
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2957)

Detect Chrome on iOS as Chrome + Webkit

---

flow-server/src/main/java/com/vaadin/server/VaadinRequest.java
flow-server/src/main/java/com/vaadin/server/VaadinResponse.java
flow-server/src/main/java/com/vaadin/server/VaadinService.java
flow-server/src/main/java/com/vaadin/server/VaadinServletRequest.java
flow-server/src/main/java/com/vaadin/server/VaadinServletResponse.java
flow-server/src/main/java/com/vaadin/server/VaadinServletService.java

Port change from Fw 8.1.0.rc2
Original PR:
https://github.com/vaadin/framework/pull/9642
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2967)

Provide current request/response through VaadinRequest/VaadinResponse

---

.gitignore
flow-components-parent/flow-generated-components/json_metadata/vaadin-radio-button.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-radio-group.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/radiobutton/GeneratedVaadinRadioButton.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/radiobutton/GeneratedVaadinRadioGroup.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json
webjars-bom/pom.xml

Part of the fix for vaadin-radio-button-flow#7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2970)

Add radio button metadata, web-jar dependency and generate classes

---

flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ExclusionRegistry.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/radiobutton/GeneratedVaadinRadioButton.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2971)

Exclude value property generation for radio button group

---

flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ExclusionRegistry.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/radiobutton/GeneratedVaadinRadioButton.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/radiobutton/GeneratedVaadinRadioGroup.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2974)

Exclude value property for radio button group, not radio button

---

flow-documentation/data-provider/tutorial-flow-data-provider.asciidoc
flow-documentation/src/main/java/com/vaadin/flow/tutorial/dataproviders/DataProviders.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2953)

Improve DataProvider tutorial

---

flow-data/src/test/java/com/vaadin/data/provider/AbstractDataProviderTest.java
flow-data/src/test/java/com/vaadin/data/provider/BackendDataProviderTest.java
flow-data/src/test/java/com/vaadin/data/provider/ConfigurableFilterDataProviderWrapperTest.java
flow-data/src/test/java/com/vaadin/data/provider/DataProviderTestBase.java
flow-data/src/test/java/com/vaadin/data/provider/ListDataProviderTest.java
flow-data/src/test/java/com/vaadin/data/provider/ReplaceListDataProvider.java
flow-data/src/test/java/com/vaadin/data/provider/ReplaceListDataProviderTest.java
flow-data/src/test/java/com/vaadin/data/provider/StrBean.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2917)

Migrate missing DataProvider tests from FW

---

flow-documentation/flow-components/tutorial-flow-grid.asciidoc
flow-documentation/src/main/java/com/vaadin/flow/tutorial/binder/Person.java
flow-documentation/src/main/java/com/vaadin/flow/tutorial/component/GridBasic.java

Also fix for some code formatting problems between the test code and the tutorial.

Add a tutorial for grid sorting

---

flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridMultiSelectionModel.java
flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridSingleSelectionModel.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/button/GeneratedVaadinButton.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/checkbox/GeneratedVaadinCheckbox.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/combobox/GeneratedVaadinComboBoxLight.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/datepicker/GeneratedVaadinDatePickerLight.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/paper/button/GeneratedPaperButton.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/paper/input/GeneratedPaperInput.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/paper/input/GeneratedPaperTextarea.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/paper/progress/GeneratedPaperProgress.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/radiobutton/GeneratedVaadinRadioButton.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextArea.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextField.java
flow-data/src/main/java/com/vaadin/data/event/ListenerMethod.java
flow-data/src/main/java/com/vaadin/data/provider/KeyMapper.java
flow-data/src/main/java/com/vaadin/data/provider/SortDirection.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/AbstractNodeStateProvider.java
flow-server/src/main/java/com/vaadin/server/CustomizedSystemMessages.java
flow-server/src/main/java/com/vaadin/server/ErrorHandlingCommand.java
flow-server/src/main/java/com/vaadin/server/communication/PushRequestHandler.java
flow-server/src/main/java/com/vaadin/ui/Component.java
flow-server/src/main/java/com/vaadin/ui/UI.java
flow-server/src/main/java/com/vaadin/ui/common/HasValue.java
flow-server/src/test/java/com/vaadin/router/RouterTest.java
flow-server/src/test/java/com/vaadin/server/startup/RouteRegistryInitializerTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LoadingIndicatorView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PageTitleView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/temp/NPETargetView.java
flow-tests/test-subcontext/src/main/java/com/vaadin/flow/contexttest/ui/DependencyUI.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2983)

Remove redundant declaration of super interfaces

---

flow-documentation/flow-components/tutorial-flow-grid.asciidoc
flow-documentation/src/main/java/com/vaadin/flow/tutorial/component/GridBasic.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2986)

Rewrite the tutorial about sorting

---

flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridMultiSelectionModel.java
flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridSingleSelectionModel.java
flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/ColumnGroup.java
flow-server/src/main/java/com/vaadin/ui/ComponentMetaData.java
flow-server/src/test/java/com/vaadin/ui/HasStyleTest.java
flow-spring-addon/src/main/java/com/vaadin/spring/scopes/BeanStore.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2990)

Remove redundant type arguments.

---

flow-server/src/main/java/com/vaadin/server/WebBrowser.java
flow-server/src/main/java/com/vaadin/shared/BrowserDetails.java
flow-server/src/test/java/com/vaadin/shared/BrowserDetailsTest.java

Port change from Fw 8.1.1
Original PR:
https://github.com/vaadin/framework/pull/9698
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2980)

Add support for detecting ChromeOS operating system

---

flow-documentation/get-started.asciidoc
flow-documentation/src/main/java/com/vaadin/flow/tutorial/getstarted/Customer.java
flow-documentation/src/main/java/com/vaadin/flow/tutorial/getstarted/CustomerForm.java
flow-documentation/src/main/java/com/vaadin/flow/tutorial/getstarted/CustomerService.java
flow-documentation/src/main/java/com/vaadin/flow/tutorial/getstarted/MainView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2993)

Use spaces instead of tab.

---

flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/DemoView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2997)

Add the prim.css file, fixing the code syntax highlighting

---

flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridDelegatesToSelectionModelTest.java
flow-data/src/main/java/com/vaadin/data/ValueContext.java
flow-server/src/main/java/com/vaadin/flow/dom/ShadowRoot.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/AbstractNodeStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicTextElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/TemplateElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/TemplateTextElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/model/ModelDescriptor.java
flow-server/src/main/java/com/vaadin/flow/template/angular/model/ModelDescriptor.java
flow-server/src/main/java/com/vaadin/server/startup/RouteRegistryInitializer.java
flow-server/src/test/java/com/vaadin/flow/nodefeature/PolymerServerEventHandlersTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2998)

Remove unnecessary SuppressWarnings

---

flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java
flow-components-parent/flow-code-generator/src/main/java/com/vaadin/generator/ComponentGeneratorPlugin.java
flow-server/src/main/java/com/vaadin/router/Location.java
flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/server/VaadinService.java
flow-server/src/main/java/com/vaadin/server/communication/StreamReceiverHandler.java
flow-server/src/main/java/com/vaadin/server/communication/UidlRequestHandler.java
flow-server/src/main/java/com/vaadin/ui/Html.java
flow-test-util/src/main/java/com/vaadin/flow/testutil/ViewOrUITest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3013)

Use StandardCharsets.UTF_8 constant

---

flow-server/src/main/java/com/vaadin/ui/renderers/TextRenderer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3005)

Add TextRenderer implementation of ComponentRenderer

---

flow-documentation/src/main/java/com/vaadin/flow/tutorial/getstarted/CustomerService.java
flow-documentation/src/main/java/com/vaadin/flow/tutorial/polymer/PolymerTemplateModelWithBean.java
flow-server/src/main/java/com/vaadin/flow/nodefeature/AbstractPropertyMap.java
flow-server/src/main/java/com/vaadin/flow/nodefeature/ModelMap.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/2999)

Remove unneeded cast

---

flow-server/src/main/java/com/vaadin/ui/renderers/IconRenderer.java

Partial fix for #11.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3014)

Implement IconRenderer

---

flow-server/src/main/java/com/vaadin/function/DeploymentConfiguration.java
flow-server/src/test/java/com/vaadin/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/server/DefaultDeploymentConfigurationTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/servlet/Es6UrlViewTestServlet.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3020)

Use `vaadin.frontend.url.dev` when in development mode.

---

flow-data/src/main/java/com/vaadin/data/Binder.java
flow-tests/test-components/pom.xml
flow-tests/test-components/src/test/java/com/vaadin/data/BinderTest.java

Port the following changes from Fw 8.2.alpha1-2:
* Add methods to remove Bindings from Binder
https://github.com/vaadin/framework/pull/9932
* Fix removeBinding logic
https://github.com/vaadin/framework/pull/10002
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3026)

Add methods to remove Bindings from Binder

---

flow-server/src/main/java/com/vaadin/server/VaadinService.java
flow-server/src/main/java/com/vaadin/server/VaadinServlet.java
flow-server/src/main/java/com/vaadin/server/VaadinServletService.java

Port change from Fw 8.2.alpha2
Original PR:
https://github.com/vaadin/framework/pull/9658
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3031)

Make Servlet related classes more welcoming to DI

---

flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/FunctionParameterVariantCombinator.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/button/GeneratedVaadinButton.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/checkbox/GeneratedVaadinCheckbox.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/combobox/GeneratedVaadinComboBoxDropdownWrapper.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/combobox/GeneratedVaadinComboBoxItem.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/combobox/GeneratedVaadinComboBoxLight.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/datepicker/GeneratedVaadinDatePickerLight.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/datepicker/GeneratedVaadinInfiniteScroller.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/paper/button/GeneratedPaperButton.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/paper/input/GeneratedPaperInput.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/paper/input/GeneratedPaperTextarea.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/paper/progress/GeneratedPaperProgress.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/paper/tabs/GeneratedPaperTabs.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/radiobutton/GeneratedVaadinRadioButton.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextArea.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextField.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3039)

ComponentGenerator to have consistent order of overloaded methods.

---

flow-documentation/Overview.asciidoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3038)

Add link to the I18N tutorial to overview page.

---

flow-data/src/main/java/com/vaadin/data/Binder.java
flow-data/src/main/java/com/vaadin/data/BinderValidationStatus.java
flow-tests/test-components/src/test/java/com/vaadin/data/BinderTest.java

Port change from Fw 8.2.alpha2
Original PR:
https://github.com/vaadin/framework/pull/9966
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3035)

Add API for running BindingValidationStatusHandlers

---

flow-server/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3044)

Update webjars locator.

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3045)

Changed the repository url to use the prerelease one.

---

flow-server/src/main/java/com/vaadin/flow/dom/Node.java
flow-server/src/main/java/com/vaadin/router/DefaultRouteResolver.java
flow-server/src/main/java/com/vaadin/server/VaadinServlet.java
flow-server/src/main/java/com/vaadin/shared/util/SharedUtil.java
flow-server/src/main/java/com/vaadin/ui/UIInternals.java
flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3050)

Use enhanced for loop.

---

flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java
flow-server/src/test/java/com/vaadin/server/BootstrapHandlerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3053)

Add inital UI language to html.

---

flow-data/src/main/java/com/vaadin/data/Binder.java
flow-tests/test-components/src/test/java/com/vaadin/data/BinderInstanceFieldTest.java
flow-tests/test-components/src/test/java/com/vaadin/data/BinderTest.java

Port change from Fw 8.2.0.alpha2
Original PR:
https://github.com/vaadin/framework/pull/9988
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3048)

Improve Binder value change handling with bean validation

---

flow-server/src/main/java/com/vaadin/router/HasUrlParameter.java
flow-server/src/main/java/com/vaadin/router/Router.java
flow-server/src/main/java/com/vaadin/util/ReflectTools.java
flow-server/src/test/java/com/vaadin/router/RouterTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3052)

Fix some generics warnings

---

flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java
flow-server/src/test/java/com/vaadin/server/BootstrapHandlerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3064)

Remove es5 adapter for ES5 mode.

---

flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoTest.java
flow-test-util/pom.xml
flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractValidationTest.java
flow-test-util/src/main/java/com/vaadin/flow/testutil/ValidationTestView.java

the component IT tests will be moved to its own repo and the
flow-component-test module will be abandoned finally, some common files
are moving to test util. necessary dependencies have been added inside
pom file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3063)

move component it to test util

---

flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRendererUtil.java

GridTemplateRendererUtil will be refactored after this PR is merged in Flow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3065)

Extract logic from GridTemplateRendererUtil to make it reusable for other components - namely IronList.

---

flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
flow-client/src/main/java/com/vaadin/client/flow/TreeChangeProcessor.java
flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
flow-data/src/main/java/com/vaadin/data/Binder.java
flow-data/src/main/java/com/vaadin/data/HasValidator.java
flow-data/src/main/java/com/vaadin/data/event/ListenerMethod.java
flow-data/src/main/java/com/vaadin/data/selection/SelectionModel.java
flow-html-components/src/main/java/com/vaadin/ui/html/Input.java
flow-server/src/main/java/com/vaadin/flow/dom/Element.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/TemplateElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/nodefeature/OverrideElementData.java
flow-server/src/main/java/com/vaadin/flow/router/View.java
flow-server/src/main/java/com/vaadin/function/DeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/function/SerializableBiFunction.java
flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/server/CustomizedSystemMessages.java
flow-server/src/main/java/com/vaadin/server/StreamVariable.java
flow-server/src/main/java/com/vaadin/server/VaadinRequest.java
flow-server/src/main/java/com/vaadin/server/WebBrowser.java
flow-server/src/main/java/com/vaadin/shared/ApplicationConstants.java
flow-server/src/main/java/com/vaadin/ui/UIInternals.java
flow-server/src/main/java/com/vaadin/ui/common/HasStyle.java
flow-server/src/main/java/com/vaadin/ui/common/PropertyDescriptors.java
flow-server/src/main/java/com/vaadin/ui/renderers/IconRenderer.java
flow-server/src/main/java/com/vaadin/util/BeanUtil.java
flow-server/src/main/java/com/vaadin/util/Range.java
flow-server/src/test/java/com/vaadin/flow/router/ViewRendererTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/EventHandlerView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3067)

 Fix typos (Fixes #3017)

---

flow-client/src/main/java/com/vaadin/client/Profiler.java
flow-client/src/main/java/com/vaadin/client/Registry.java
flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
flow-client/src/main/java/com/vaadin/client/UILifecycle.java
flow-client/src/main/java/com/vaadin/client/WidgetUtil.java
flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
flow-client/src/main/java/com/vaadin/client/flow/ConstantPool.java
flow-client/src/main/java/com/vaadin/client/flow/ExecuteJavaScriptProcessor.java
flow-client/src/main/java/com/vaadin/client/flow/binding/BinderContext.java
flow-client/src/main/java/com/vaadin/client/flow/collection/JsCollections.java
flow-client/src/main/java/com/vaadin/client/flow/collection/jre/JreJsArray.java
flow-client/src/main/java/com/vaadin/client/flow/util/NativeFunction.java
flow-client/src/main/java/com/vaadin/client/gwt/com/google/web/bindery/event/shared/SimpleEventBus.java
flow-client/src/main/java/com/vaadin/client/gwt/elemental/js/util/Xhr.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3079)

Fix JavaDoc warnings

---

flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoTest.java
flow-test-util/pom.xml
flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractComponentIT.java
flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractValidationTest.java
flow-test-util/src/main/java/com/vaadin/flow/testutil/ValidationTestView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3075)

move common component test file to test Util

---

flow-client/src/main/java/com/vaadin/client/communication/DefaultReconnectDialog.java
flow-client/src/main/java/com/vaadin/client/communication/XhrConnection.java
flow-client/src/main/java/com/vaadin/client/gwt/com/google/web/bindery/event/shared/SimpleEventBus.java
flow-client/src/test/java/com/vaadin/client/flow/StateTreeTest.java
flow-client/src/test/java/com/vaadin/client/flow/nodefeature/MapPropertyTest.java
flow-client/src/test/java/com/vaadin/client/flow/nodefeature/NodeListTest.java
flow-client/src/test/java/com/vaadin/client/flow/nodefeature/NodeMapTest.java
flow-client/src/test/java/com/vaadin/client/flow/reactive/ComputationTest.java
flow-server/src/main/java/com/vaadin/server/VaadinService.java
flow-server/src/main/java/com/vaadin/server/communication/PushHandler.java
flow-server/src/main/java/com/vaadin/server/communication/PushRequestHandler.java
flow-server/src/main/java/com/vaadin/ui/event/ComponentEventBus.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
flow-server/src/test/java/com/vaadin/server/VaadinSessionTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3054)

Use lambda expressions

---

flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
flow-client/src/main/java/com/vaadin/client/flow/ExecuteJavaScriptProcessor.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/JsApiGetByIdView.java
flow-tests/test-root-context/src/main/webapp/frontend/js-get-by-id.js
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/JsApiGetByIdIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3078)

Add JS API to get DOM Node by the server-side node id.

---

flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java
flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGeneratorUtils.java
flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java
flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorUtilsTest.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/combobox/GeneratedVaadinComboBoxLight.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/datepicker/GeneratedVaadinDatePickerLight.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/paper/input/GeneratedPaperInput.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/paper/input/GeneratedPaperTextarea.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/paper/tabs/GeneratedPaperTabs.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextArea.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextField.java

Unit Test added;
new generated component files added;
fix by Gilberto, tests by Zhe
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3074)

Fix has value Null Check on component generator

---

flow-documentation/spring/tutorial-spring-basic.asciidoc
flow-spring-addon/pom.xml
flow-spring-addon/src/main/java/com/vaadin/spring/SpringBootAutoConfiguration.java
flow-spring-boot-starter/pom.xml
flow-test-util/pom.xml
flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
flow-tests/pom.xml
flow-tests/test-spring-boot/pom.xml
flow-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/TestServletInitializer.java
flow-tests/test-spring-common/pom.xml
flow-tests/test-spring-war/pom.xml
flow-tests/test-spring-war/src/main/java/com/vaadin/flow/spring/TestServletInitializer.java
flow-tests/test-spring/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3084)

Update Spring-boot to 2.0.0.M7

---

flow-server/src/main/java/com/vaadin/flow/template/angular/model/BeanModelType.java
flow-server/src/main/java/com/vaadin/flow/template/angular/parser/DefaultElementBuilderFactory.java
flow-server/src/main/java/com/vaadin/ui/UIInternals.java
flow-server/src/test/java/com/vaadin/tests/VaadinClasses.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3090)

Remove redundant .toString() in string concatenation

---

flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java
flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGeneratorUtils.java
flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java
flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorUtilsTest.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/combobox/GeneratedVaadinComboBoxLight.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/datepicker/GeneratedVaadinDatePickerLight.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/paper/input/GeneratedPaperInput.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/paper/input/GeneratedPaperTextarea.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextArea.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextField.java
flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java

To store the returned value of `getElement().getProperty()` instead of
calling it twice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3089)

Generated value getter enhancement

---

flow-components-parent/flow-generated-components/json_metadata/vaadin-tab.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-tabs.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/tabs/GeneratedVaadinTab.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/tabs/GeneratedVaadinTabs.java
flow-components-parent/flow-webcomponent-api-analyzer/package-lock.json
flow-components-parent/flow-webcomponent-api-analyzer/package.json

Also regenerate components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3087)

Update ejs dependency of webcomponent analyzer

---

flow-client/pom.xml
flow-client/src/main/java/com/vaadin/client/DependencyLoader.java
flow-client/src/main/java/com/vaadin/client/Profiler.java
flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
flow-client/src/main/java/com/vaadin/flow/linker/ClientEngineLinker.java
flow-client/src/test/java/com/vaadin/client/CodeTest.java

As hinted in #2981
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3009)

 Enforce GWT client code to use implementation type declaration

---

flow-server/src/main/java/com/vaadin/router/util/RouterUtil.java
flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java
flow-server/src/test/java/com/vaadin/router/util/RouterUtilTest.java

There was a problem with route resolving when using
@RoutePrefix in parent layouts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3094)

Fix the resolving of @Route or @RouteAlias in RouterUtil

---

flow-client/src/main/java/com/vaadin/client/ExecuteJavaScriptElementUtils.java
flow-client/src/main/java/com/vaadin/client/PolymerUtils.java
flow-client/src/main/java/com/vaadin/client/Registry.java
flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
flow-client/src/main/java/com/vaadin/client/flow/collection/JsCollections.java
flow-client/src/main/java/com/vaadin/client/flow/collection/JsMap.java
flow-client/src/main/java/com/vaadin/client/flow/collection/JsSet.java
flow-client/src/main/java/com/vaadin/client/flow/collection/jre/JreJsMap.java
flow-client/src/main/java/com/vaadin/client/flow/collection/jre/JreJsSet.java
flow-client/src/main/java/com/vaadin/client/gwt/com/google/web/bindery/event/shared/SimpleEventBus.java
flow-client/src/main/java/com/vaadin/client/gwt/elemental/js/util/Xhr.java
flow-client/src/test-gwt/java/com/vaadin/client/flow/collection/GwtJsMapTest.java
flow-client/src/test-gwt/java/com/vaadin/client/flow/collection/GwtJsSetTest.java
flow-client/src/test/java/com/vaadin/client/flow/collection/JreMapTest.java
flow-client/src/test/java/com/vaadin/client/flow/collection/JreSetTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3076)

 Move helper methods from JsCollections to JsMap/JsSet (Fixes #135)

---

webjars-bom/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3100)

Update Valo theme.

---

flow-server/src/main/java/com/vaadin/function/DeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/server/Constants.java
flow-server/src/test/java/com/vaadin/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/server/DefaultDeploymentConfigurationTest.java
flow-spring-addon/src/main/java/com/vaadin/spring/SpringServlet.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3106)

Restrict changing frontend prefix in development mode via environment variable.

---

flow-components-parent/flow-webcomponent-api-analyzer/bin/flow-webcomponent-api-analyzer.js
flow-components-parent/flow-webcomponent-api-analyzer/gulpfile.js
flow-components-parent/flow-webcomponent-api-analyzer/lib/js/analyzer-transform.js
flow-components-parent/flow-webcomponent-api-analyzer/lib/js/element-filter.js
flow-components-parent/flow-webcomponent-api-analyzer/lib/js/global-variables.js
flow-components-parent/flow-webcomponent-api-analyzer/lib/js/mixin-collector.js
flow-components-parent/flow-webcomponent-api-analyzer/lib/js/version-transform.js
flow-components-parent/flow-webcomponent-api-analyzer/package-lock.json
flow-components-parent/flow-webcomponent-api-analyzer/package.json
flow-components-parent/flow-webcomponent-api-analyzer/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3109)

Remove redundant packages, copying and code.

---

flow-documentation/application-structure/tutorial-bootstrap.asciidoc
flow-documentation/src/main/java/com/vaadin/flow/tutorial/BootstrapPage.java
flow-server/src/main/java/com/vaadin/router/event/AfterNavigationEvent.java
flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java
flow-server/src/main/java/com/vaadin/server/InitialPageSettings.java
flow-server/src/main/java/com/vaadin/server/PageConfigurator.java
flow-server/src/main/java/com/vaadin/server/startup/AbstractRouteRegistryInitializer.java
flow-server/src/test/java/com/vaadin/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/server/startup/RouteRegistryInitializerTest.java
flow-server/src/test/resources/inline.css
flow-server/src/test/resources/inline.html
flow-server/src/test/resources/inline.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3101)

Enable initial page configuration using PageConfigurator.

---

flow-spring-addon/src/main/java/com/vaadin/spring/SpringBootAutoConfiguration.java
flow-tests/test-spring-boot/pom.xml

Use Dispatcher servlet available as a Spring bean instead of direct
instantiation.
Fix for #2871
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3115)

Use Spring managed Dispatcher servlet instance

---

flow-server/src/main/java/com/vaadin/server/startup/RouteTarget.java
flow-server/src/test/java/com/vaadin/server/startup/RouteTargetTest.java

Tests for RouteTarget functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3118)

Fix RouteTarget exception parameters.

---

flow-server/src/main/java/com/vaadin/ui/common/ItemLabelGenerator.java
flow-server/src/main/java/com/vaadin/ui/renderers/ComponentRenderer.java
flow-server/src/main/java/com/vaadin/ui/renderers/IconRenderer.java
flow-server/src/main/java/com/vaadin/ui/renderers/TextRenderer.java
flow-server/src/test/java/com/vaadin/ui/renderers/IconRendererTest.java
flow-server/src/test/java/com/vaadin/ui/renderers/TextRendererTest.java

Fix for #2996
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3125)

Throw an exception if the generator return value is null

---

flow-documentation/flow-components/tutorial-flow-webjars.asciidoc

added newline to fix listing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3128)

added newline to fix listing in tutorial-flow-webjars.asciidoc

---

flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc

added newline to fix listing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3129)

added newline to fix listing in tutorial-how-to-use-webjars.asciidoc

---

flow-data/src/main/java/com/vaadin/data/Binder.java
flow-tests/test-components/src/test/java/com/vaadin/data/BinderTest.java

Port change from FW 8.2.0.alpha2
original PR: vaadin/framework#10004
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3130)

Fix BindingBuilder to always use the same instance

---

flow-server/src/main/java/com/vaadin/flow/dom/ElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/Node.java
flow-server/src/main/java/com/vaadin/flow/dom/NodeVisitor.java
flow-server/src/main/java/com/vaadin/flow/dom/ShadowRoot.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/AbstractNodeStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/AbstractTextElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/ShadowRootStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/TemplateElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/TemplateTextElementStateProvider.java
flow-server/src/main/java/com/vaadin/router/event/EventUtil.java
flow-server/src/test/java/com/vaadin/flow/dom/BasicElementStateProviderTest.java
flow-server/src/test/java/com/vaadin/flow/dom/ShadowRootTest.java
flow-server/src/test/java/com/vaadin/flow/dom/TestNodeVisitor.java
flow-server/src/test/java/com/vaadin/flow/router/event/EventUtilTest.java
flow-server/src/test/java/com/vaadin/ui/UITest.java

Fix for #2855
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3127)

Inspect all descendants of the element to find observers

---

flow-data/src/main/java/com/vaadin/data/Binder.java
flow-tests/test-components/src/test/java/com/vaadin/data/BinderConverterValidatorTest.java
flow-tests/test-components/src/test/java/com/vaadin/data/BinderTest.java

Port change from FW 8.2.0.alpha3
original PR: vaadin/framework#10162
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3132)

Fix Binder bean writing to only validate and write given bindings

---

flow-documentation/application-structure/tutorial-bootstrap.asciidoc
flow-documentation/src/main/java/com/vaadin/flow/tutorial/BootstrapPage.java
flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java
flow-server/src/main/java/com/vaadin/server/InitialPageSettings.java
flow-server/src/main/java/com/vaadin/server/InlineTargets.java
flow-server/src/main/java/com/vaadin/server/startup/AbstractRouteRegistryInitializer.java
flow-server/src/main/java/com/vaadin/ui/Inline.java
flow-server/src/test/java/com/vaadin/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/server/startup/RouteRegistryInitializerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3135)

@Inline annotation for Bootstrap page

---

flow-data/src/main/java/com/vaadin/data/Binder.java
flow-tests/test-components/src/test/java/com/vaadin/data/BinderTest.java

Port change from FW 8.2.0.alpha3 to Flow
original PR: vaadin/framework#10316
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3138)

Add API to read Binding value from bean

---

flow-data/src/main/java/com/vaadin/data/Binder.java

Port Change from FW8.2.0.alpha3 to flow
original PR:vaadin/framework#9873
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3141)

Added utility method Binder#asRequired()

---

flow-data/src/main/java/com/vaadin/data/Binder.java
flow-tests/pom.xml
flow-tests/test-components/pom.xml
flow-tests/test-components/src/test/java/com/vaadin/data/BinderCustomPropertySetTest.java
flow-tests/test-components/src/test/java/com/vaadin/data/BinderTest.java

This module is mainly for binder tests.
Needed flow components have been released as SNAPSHOT version. So we can
enable this module now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3133)

Enable tests components module

---

flow-tests/test-components/src/test/java/com/vaadin/data/BinderConverterValidatorTest.java
flow-tests/test-components/src/test/java/com/vaadin/data/BinderTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3153)

Fix master compilation.

---

flow-server/src/main/java/com/vaadin/ui/polymertemplate/TemplateInitializer.java
flow-server/src/test/java/com/vaadin/ui/polymertemplate/PolymerTemplateTest.java

Fix for #3131
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3156)

Use @Id way to address subtemplate whenever it's possible

---

flow-server/src/main/java/com/vaadin/server/DefaultDeploymentConfiguration.java
flow-server/src/test/java/com/vaadin/server/DefaultDeploymentConfigurationTest.java

Closes #3142
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3155)

Do not visit repeated paths twice

---

flow-server/src/main/java/com/vaadin/ui/renderers/ButtonRenderer.java
flow-server/src/main/java/com/vaadin/ui/renderers/ClickableRenderer.java
flow-server/src/main/java/com/vaadin/ui/renderers/LocalDateRenderer.java
flow-server/src/main/java/com/vaadin/ui/renderers/LocalDateTimeRenderer.java
flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java
flow-server/src/main/java/com/vaadin/ui/renderers/SimpleValueTemplateRenderer.java

A demo with all the renderers will be pushed to `vaadin-grid-flow`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3144)

Add basic template renderers.

---

flow-test-util/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3170)

Use button snapshot, update TB to 5.1.1

---

webjars-bom/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3173)

Use non-corrupt layout.

---

flow-server/src/main/java/com/vaadin/flow/router/internal/ErrorStateRenderer.java
flow-server/src/main/java/com/vaadin/flow/router/internal/RouterUtil.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
flow-server/src/test/java/com/vaadin/flow/router/internal/RouterUtilTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3184)

Enable ParentLayout for error targets.

---

flow-documentation/flow-components/tutorial-flow-grid.asciidoc
flow-documentation/src/main/java/com/vaadin/flow/tutorial/component/GridRenderers.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3164)

Add a tutorial for basic renderers.

---

flow-data/src/main/java/com/vaadin/flow/data/provider/ComponentDataGenerator.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3200)

Change KeyMapper to DataKeyMapper in the ComponentDataGenerator.

---

flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java
flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtMultipleBindingTest.java
flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtPolymerModelTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/VisibilityView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VisibilityIT.java

Fix for #3146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3202)

Hide/unhide DOM element based on visibility feature

---

flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java
flow-server/src/main/java/com/vaadin/flow/router/RouteData.java
flow-server/src/main/java/com/vaadin/flow/router/Router.java
flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java
flow-server/src/test/java/com/vaadin/flow/internal/ReflectToolsTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java

All router registered routes can be gotten as a List<RouteData>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3205)

Registered routes can now be requested.

---

flow-documentation/Overview.asciidoc
flow-documentation/routing/tutorial-routing-get-registered-routes.asciidoc
flow-documentation/src/main/java/com/vaadin/flow/tutorial/routing/RountingGettingRoutes.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3223)

Add a tutorial for Router::getRoutes

---

webjars-bom/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3226)

update notification webjars version

---

webjars-bom/pom.xml

This webjar is needed by the new structured webcomponent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3231)

Add-needed-webjars

---

flow-server/src/main/java/com/vaadin/flow/dom/impl/AbstractNodeStateProvider.java
flow-server/src/main/java/com/vaadin/flow/renderer/TemplateRendererUtil.java

Fix for #2901
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3224)

Use beforeClientResponse() inside runWhenAttached() to execute JS

---

flow-documentation/flow-components/tutorial-flow-grid.asciidoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3238)

Add docs about Grid.setDetailsVisibleOnClick()

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinServiceInitListener.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3245)

Fix VaadinServiceInitListener javadoc

---

flow-documentation/application-structure/tutorial-bootstrap.asciidoc
flow-documentation/src/main/java/com/vaadin/flow/tutorial/BootstrapPage.java
flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3247)

Add shorthands for addLink and addFavIcon

---

webjars-bom/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3253)

update ordered-layout webjars

---

flow-server/src/main/java/com/vaadin/flow/router/Router.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3255)

For null parameter use getUrl(Class)

---

flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/Image.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java

Fixes #3243.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3250)

Add StreamResource shorthands to Anchor and Image

---

flow-documentation/Overview.asciidoc
flow-documentation/flow-components/tutorial-component-basic-features.asciidoc
flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc
flow-documentation/flow-components/tutorial-flow-grid.asciidoc
flow-documentation/flow-components/tutorial-flow-icon.asciidoc
flow-documentation/flow-components/tutorial-flow-webjars.asciidoc
flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc
flow-documentation/src/main/java/com/vaadin/flow/tutorial/component/ComponentBasicFeatures.java
flow-server/src/main/java/com/vaadin/flow/component/Component.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3257)

Add a tutorial and improve javadoc about Component::setVisible

---

pom.xml
webjars-bom/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3267)

Staging build changes

---

flow-server/pom.xml
flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
flow-server/src/test/java/com/vaadin/flow/router/InternalServerErrorTest.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceIT.java

Fix for #3216
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3266)

Show the stacktrace on the web page and a warning in case of SLF4J binding absence

---

flow-server/src/test/java/com/vaadin/flow/router/InternalServerErrorTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3268)

Fix used event as BeforeNavigationEvent is deleted

---

flow-server/src/main/java/com/vaadin/flow/renderer/TemplateRendererUtil.java

This change is needed for event handlers to work with TemplateRenderers inside ComboBox.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3271)

Add a safety check for the model object when receiving events from templated elements

---

flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/ModelDescriptorTest.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/TemplateModelTest.java

Fix for #2636
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3275)

Disallow final accessors in the template model

---

webjars-bom/pom.xml

Also update the version of `<vaadin-item>`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3278)

Add <vaadin-list-box> to webjars-bom

---

flow-client/src/main/java/com/vaadin/client/PolymerUtils.java
flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java

Fix for #3276
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3280)

Provide a way to listen polymer element readiness 

---

flow-client/src/main/java/com/vaadin/client/PolymerUtils.java
flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java

Fix for #3264, #3282
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3283)

Use "ready" listener instead of "whenDefined"

---

flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
flow-client/src/main/java/com/vaadin/client/Profiler.java
flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html
flow-server/src/main/resources/com/vaadin/flow/server/BootstrapHandler.js
flow-test-util/pom.xml
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExportedJSFunctionView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/TimingInfoReportedView.java
flow-tests/test-root-context/src/main/webapp/frontend/js-get-by-id.js
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/frontend/FrontendProtocolIT.java

Closes #3119 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3284)

Use window.Vaadin.Flow namespace for client api

---

flow-server/src/main/java/com/vaadin/flow/server/AbstractTheme.java
flow-server/src/test/java/com/vaadin/flow/server/AbstractThemeTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3287)

Create AbstractTheme class as base for theme handling.

---

flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
flow-spring-addon/src/main/java/com/vaadin/flow/spring/VaadinMVCWebAppInitializer.java
flow-spring-addon/src/main/java/com/vaadin/flow/spring/VaadinServletConfiguration.java
flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/test/StreamResourceView.java
flow-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/StreamResourceIT.java

Fix for #3244
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3291)

Don't use special mappings for Vaadin servlet

---

flow-server/src/main/java/com/vaadin/flow/renderer/TemplateRendererUtil.java

this cause the IT test failure on `vaadin-combo-box-flow`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3297)

correct usage on executeJavascript

---

flow-server/src/main/java/com/vaadin/flow/dom/Element.java
flow-server/src/main/java/com/vaadin/flow/dom/ThemeList.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/ThemeListImpl.java
flow-server/src/test/java/com/vaadin/flow/dom/impl/ThemeListImplTest.java

flow-server api for https://github.com/vaadin/vaadin-ordered-layout-flow/issues/1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3300)

Add ThemeList low level api to Element.

---

flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PageView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PageIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3299)

Add Page.reload for reloading the page

---

flow-server/src/main/java/com/vaadin/flow/component/page/Page.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3302)

Remove unused import

---

flow-documentation/Overview.asciidoc
flow-documentation/application-structure/tutorial-bootstrap.asciidoc
flow-documentation/src/main/java/com/vaadin/flow/tutorial/theme/ComponentTheme.java
flow-documentation/theme/tutorial-built-in-themes.asciidoc
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
flow-server/src/main/java/com/vaadin/flow/server/AbstractTheme.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
flow-server/src/main/java/com/vaadin/flow/server/InvalidApplicationConfigurationException.java
flow-server/src/main/java/com/vaadin/flow/server/Theme.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java
flow-server/src/main/java/com/vaadin/flow/server/startup/AnnotationValidator.java
flow-server/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer
flow-server/src/test/java/com/vaadin/flow/server/AbstractThemeTest.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/AnnotationValidatorTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/theme/MyComponent.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/theme/MyComponentView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/theme/MyTheme.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/theme/MyThemeComponentView.java
flow-tests/test-root-context/src/main/webapp/frontend/bower_components/my-component/src/my-component.html
flow-tests/test-root-context/src/main/webapp/frontend/bower_components/my-component/theme/myTheme/my-component.html
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/theme/MyThemeIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3295)

Add @Theme annotation

---

flow-documentation/polymer-templates/tutorial-template-model-bean.asciidoc
flow-documentation/src/main/java/com/vaadin/flow/tutorial/polymer/PolymerTemplateModelWithBean.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3304)

Add an example that highlights proxy model usage.

---

flow-documentation/application-structure/tutorial-bootstrap.asciidoc
flow-documentation/polymer-templates/tutorial-template-basic.asciidoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3306)

Fix tutorial notes to use the correct annotation names.

---

CONTRIBUTING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3307)

Fix gitter link in CONTRIBUTING.md

---

flow-documentation/components/tutorial-flow-icon.asciidoc
flow-documentation/src/main/java/com/vaadin/flow/tutorial/components/IconBasic.java
flow-documentation/theme/tutorial-built-in-themes.asciidoc

From valo to lumo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3342)

Fix a link in docs

---

flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3341)

Logg warn information for missing @Theme

---

flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java
flow-server/src/test/java/com/vaadin/flow/router/RouterLayoutTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3309)

Fix logic and NPE in RouterLayout

---

flow-documentation/Overview.asciidoc
flow-documentation/advanced/tutorial-application-lifecycle.asciidoc
flow-documentation/advanced/tutorial-bootstrap.asciidoc
flow-documentation/advanced/tutorial-dependency-filter.asciidoc
flow-documentation/advanced/tutorial-dynamic-content.asciidoc
flow-documentation/advanced/tutorial-execute-javascript.asciidoc
flow-documentation/advanced/tutorial-flow-runtime-configuration.asciidoc
flow-documentation/advanced/tutorial-history-api.asciidoc
flow-documentation/advanced/tutorial-i18n-localization.asciidoc
flow-documentation/advanced/tutorial-loading-indicator.asciidoc
flow-documentation/advanced/tutorial-service-init-listener.asciidoc
flow-documentation/advanced/tutorial-stream-resources.asciidoc
flow-documentation/spring/tutorial-spring-scopes.asciidoc
flow-documentation/src/main/java/com/vaadin/flow/tutorial/advanced/Lifecycle.java

Fix for #3177
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3345)

Add Vaadin application lifecycle tutorial

---

flow-documentation/spring/tutorial-spring-scopes.asciidoc

Fix for #3336.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3349)

Add links to the application lifecycle tutorial from Spring scopes decs

---

flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java
flow-spring-addon/src/test/java/com/vaadin/flow/spring/i18n/I18NProviderInstantiationTest.java
flow-spring-addon/src/test/java/com/vaadin/flow/spring/instantiator/SpringInstantiatorTest.java
flow-spring-addon/src/test/java/com/vaadin/flow/spring/scopes/VaadinSessionScopeTest.java
flow-spring-addon/src/test/java/com/vaadin/flow/spring/scopes/VaadinUIScopeTest.java

Fix  for #2928
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3353)

Use Spring bean if available for I18NProvider

---

flow-documentation/advanced/tutorial-application-lifecycle.asciidoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3354)

Correct the tutorial title

---

flow-documentation/routing/tutorial-routing-exception-handling.asciidoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3352)

Fix incorrect page title

---

flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3358)

Remove double space in error message

---

flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractAnnotationValidator.java
flow-server/src/main/java/com/vaadin/flow/server/startup/AnnotationValidator.java
flow-spring-addon/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java

Fix for #3303
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3355)

Extract common validation logic and implement ServletContextListener

---

flow-documentation/advanced/tutorial-i18n-localization.asciidoc

Fix for #3180
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3362)

Extend I18N tutorial with registering a provider in the Spring way

---

flow-documentation/web-components/tutorial-flow-maven-plugin.asciidoc
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FrontendToolsManager.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/common/BundleConfigurationReaderTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3361)

Support fragment names.

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FrontendDataProvider.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FrontendToolsManager.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/TranspileProductionFilesMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/production/TranspilationStep.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/common/FrontendDataProviderTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/production/TranspilationStepTest.java

Will also allow to deal with styling in new class only, FrontendDataProvider.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3372)

Refactoring: move away logic from mojos and FrontendToolsManager.

---

flow-test-util/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3373)

Update TestBench to 6.0.0.alpha5

---

flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java

Based on https://vaadin.slack.com/archives/C6RAXJATF/p1516628074000447
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3375)

Less verbose theming logging.

---

flow-test-util/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3376)

Update to TestBench 6.0.0.alpha6

---

flow-server/src/main/java/com/vaadin/flow/component/ChangeEvent.java
flow-server/src/main/java/com/vaadin/flow/component/ClickEvent.java
flow-server/src/main/java/com/vaadin/flow/component/CompositionEndEvent.java
flow-server/src/main/java/com/vaadin/flow/component/CompositionStartEvent.java
flow-server/src/main/java/com/vaadin/flow/component/CompositionUpdateEvent.java
flow-server/src/main/java/com/vaadin/flow/component/InputEvent.java
flow-server/src/main/java/com/vaadin/flow/component/InputNotifier.java
flow-server/src/main/java/com/vaadin/flow/component/KeyDownEvent.java
flow-server/src/main/java/com/vaadin/flow/component/KeyEventListener.java
flow-server/src/main/java/com/vaadin/flow/component/KeyPressEvent.java
flow-server/src/main/java/com/vaadin/flow/component/KeyUpEvent.java
flow-server/src/main/java/com/vaadin/flow/component/KeyboardEvent.java
flow-server/src/main/java/com/vaadin/flow/component/internal/CompositionEvent.java
flow-server/src/main/java/com/vaadin/flow/component/internal/KeyboardEvent.java

Fixes #3378
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3379)

Change generic type of Keyboard/Composistion events to Component

---

flow-documentation/introduction/introduction-overview.asciidoc

Need to start first what Flow is and how it relates to Vaadin platform.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3380)

Added some info what Flow is.

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
flow-server/src/main/java/com/vaadin/flow/server/startup/ServletVerifier.java
flow-server/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer
flow-spring-addon/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3381)

Check the servlet version as soon as possible.

---

flow-components-parent/flow-webcomponent-api-analyzer/lib/js/element-filter.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3389)

Add small convertion to make the analyzer work on windows machines

---

flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/ModelDescriptor.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/TemplateModelListProxyTest.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/TemplateModelProxyHandlerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3396)

Remove redundant constructors

---

flow-maven-plugin/pom.xml
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FrontendToolsManager.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/production/ProductionModeCopyStep.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3401)

Add logging to flow-maven-plugin.

---

flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/CompositeView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/CompositeIT.java

Fixes #2454
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3403)

Load HTML/JS/CSS dependencies of Composite contents

---

flow-test-util/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3407)

Update to TestBench 6.0.0.alpha7

---

flow-documentation/components/tutorial-flow-grid.asciidoc
flow-documentation/src/main/java/com/vaadin/flow/tutorial/components/GridBasic.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3412)

Fix tutorials after https://github.com/vaadin/vaadin-grid-flow/pull/72

---

flow-test-util/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3417)

Remove unnecessary dependency

---

flow-documentation/theme/tutorial-built-in-themes.asciidoc
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
flow-server/src/main/java/com/vaadin/flow/theme/NoTheme.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3406)

NoTheme annotation for classes never implementing a Theme themselves.

---

flow-components-parent/flow-components-test/src/main/java/com/vaadin/flow/components/it/binder/BinderComponentsValidationView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3429)

Fix binder test.

---

flow-documentation/web-components/tutorial-flow-maven-plugin.asciidoc
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageForProductionMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageFormProductionMojo.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3428)

Rename plugin goal.

---

flow-documentation/Overview.asciidoc
flow-documentation/components/tutorial-component-basic-features.asciidoc
flow-documentation/components/tutorial-flow-components-setup.asciidoc
flow-documentation/introduction/introduction-overview.asciidoc
flow-documentation/src/main/html/Introduction.html
flow-documentation/src/main/java/com/vaadin/flow/tutorial/introduction/Introduction.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3340)

Improve introduction and vaadin components docs

---

flow-maven-plugin/src/main/resources/gulpfile.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3432)

Add more logging to plugin.

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
flow-server/src/main/java/com/vaadin/flow/theme/AbstractTheme.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3446)

Use @HtmlImport for importing the theme files and making bundling automatically supporting it.

---

flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/AttachExistingElementFeature.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java

Some fixes based on scalability testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3445)

Reduce memory consumption by doing lazy initialization

---

flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
flow-server/src/main/java/com/vaadin/flow/server/webjar/WebJarServer.java
flow-server/src/main/java/com/vaadin/flow/theme/AbstractTheme.java
flow-server/src/test/java/com/vaadin/flow/theme/AbstractThemeTest.java
flow-server/src/test/java/com/vaadin/flow/theme/ThemeUrlResolverTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3442)

Resolve url translations on the fly.

---

flow-server/src/main/java/com/vaadin/flow/router/BeforeEnterEvent.java
flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java

Fixes #3447
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3448)

Provide a UI reference to BeforeEnter and BeforeLeave

---

flow-maven-plugin/pom.xml
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/production/ProductionModeCopyStep.java

Fixes #3451
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3452)

Use elemental json instead of org.json

---

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateInitializer.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementAttributeMap.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeMap.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/AllowClientUpdates.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/ClientUpdateMode.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/ConvertedModelType.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/PropertyMapBuilder.java
flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/TemplateInitializerTest.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMapTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/MapSyncRpcHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/Bean.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/BeanContainingBeans.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/BeanModelTypeTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/BeanInListingView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/ClientUpdateModeView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/webcomponent/PaperSlider.java
flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/ClientUpdateMode.html

Fixes #1331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3449)

Restrict how model property updates are sent to the server

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/ThemedURLTranslator.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3454)

Reduce log spam

---

README.md
flow-server-production-mode/pom.xml
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3455)

Update documentation links after move

---

webjars-bom/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3459)

Use development detector which works in IE11

---

webjars-bom/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3461)

Fix WebJars' versions.

---

flow-components-parent/flow-component-demo-helpers/pom.xml
flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/DemoView.java
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractAnnotationValidator.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/AnnotationValidatorTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3465)

Enable bootstrap annotations to be set on a abstract superclass.

---

flow-client/src/main/java/com/vaadin/client/flow/StateNode.java
flow-client/src/test-gwt/java/com/vaadin/client/GwtSuite.java
flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtStateNodeTest.java
flow-client/src/test/java/com/vaadin/client/flow/StateNodeTest.java

Part of the fix for #3425
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3475)

Add a generic way to store data inside StateNode

---

flow-maven-plugin/src/main/resources/gulpfile.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3480)

Configure transpilation like in polymer-cli

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/ThemedURLTranslator.java
flow-maven-plugin/src/main/resources/gulpfile.js
flow-maven-plugin/src/main/resources/package.json
flow-maven-plugin/src/main/resources/yarn.lock

Remove unused method.
Throw more meaninful excecption if the method required is not found.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3477)

Update plugin frontend dependencies.

---

webjars-bom/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3488)

correct version on vaadin-element-mixin

---

flow-html-components-testbench/pom.xml
flow-test-util/pom.xml
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3478)

Update to TestBench 6.0.0.alpha9

---

flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java

Fixes #3486
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3492)

Store pending executions in the node itself

---

flow-server/src/main/java/com/vaadin/flow/templatemodel/AllowClientUpdates.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/Bean.java

The idea is that you can do the most common operation, i.e. allowing updates, simply by adding the annotation without any extra boilerplate.
Inspired by #3495.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3497)

Add default value for @AllowClientUpdates

---

flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtStateNodeTest.java
flow-client/src/test/java/com/vaadin/client/flow/StateNodeTest.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/AllowClientUpdates.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/PropertyMapBuilder.java
flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/Bean.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/BeanContainingBeans.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/BeanModelTypeTest.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/TemplateModelTest.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/TemplateModelWithConvertersTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/BeanInListingView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/ConvertToBeanView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/EmptyListsView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/Message.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/OneWayPolymerBindingView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/collections/ClearListView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/collections/ListBindingView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/collections/ListInsideListBindingView.java

Preliminary patch for #3425
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3494)

Check whether client-side update settings allow to have a getter

---

flow-server/pom.xml
flow-tests/pom.xml
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceIT.java
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3436)

Enable logging for testing servers

---

flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtPolymerModelTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3505)

Allow property being undefined from the server side except interim subrops

---

flow-server/src/main/java/com/vaadin/flow/router/Router.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java

Added getUrlBase to receive a url without the parameter
even if the parameter is required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3523)

Get url throws for a required parameter.

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3535)

Use TestBench 6.0.0.alpha11

---

flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationStateRenderer.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
flow-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/CoExistingSpringEndpointsIT.java
flow-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/NPEHandlerIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3528)

Return 404 when not able to parse url parameter.

---

flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtPolymerModelTest.java

This reverts commit 436fe70881838296a65a0b4fba5ab87a9bafc802.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3543)

Revert "Take care about several property change executions (#3521)"

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/ArtifactData.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CopyProductionFilesMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/production/ProductionModeCopyStep.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/production/WebJarPackage.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/common/ArtifactDataTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/production/ProductionModeCopyStepTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/production/WebJarPackageTest.java

Move the artifact-related logic from MOJO to plugin class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3550)

Skip directories and non-existing files for project artifacts.

---

flow-components-parent/flow-generated-components/json_metadata/vaadin-tab.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-tabs.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBoxLight.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3559)

Update vaadin-tabs, regenerate the components.

---

flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractParallelTestBenchTest.java
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3561)

Update to TestBench 6.0.0.alpha12

---

flow-tests/test-root-context/pom.xml
flow-tests/test-spring-common/pom.xml
webjars-bom/pom.xml

These are resolved automatically during build
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3534)

Remove unnecessary transitive dependency versions

---

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java

Empty does not intersect with empty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3570)

Do not resend all if both previous and effective is empty.

---

flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java
flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3571)

Handle special URI for HTML import dependencies

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3575)

Update to TestBench 6.0.0.alpha13

---

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/DefaultTemplateParser.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateInitializer.java
flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/DefaultTemplateParserTest.java
flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/TemplateInitializerTest.java

Fixes #3573
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3576)

Refactor template initialization logic related to the parsing to make it threadsafe

---

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateInitializer.java

Do not mix template analyzation logic with initialization logic to avoid using implicit contexts available in the initializer.
Fixes #3587
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3589)

Extract template data analyzation to the separate class

---

flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3593)

Logger uses {} not %s

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
flow-server/src/test/java/com/vaadin/flow/theme/ThemeUrlResolverTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3583)

servlet path should not be considered when resolving files.

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3599)

Update to latest TB alpha

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3601)

Update to TestBench 6.0.0.alpha15 (Selenium 3.9.1)

---

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java
flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java

Some code corrections and unit test for template initializer with production mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3607)

Add template initializer test

---

flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ExclusionRegistry.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/listbox/GeneratedVaadinListBox.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3615)

Regenerate List-box without the unneeded items sync

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/router/NavigationTrigger.java
flow-server/src/main/java/com/vaadin/flow/router/RouterInterface.java
flow-server/src/test/java/com/vaadin/flow/component/LocationObserverTest.java
flow-server/src/test/java/com/vaadin/flow/component/UITest.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/servlet/ViewTestLayout.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/NavigationTriggerView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RerouteView.java

Fixes #2918
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3610)

Rename UI::navigateTo methods and update javadocs

---

flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3611)

Improve lazy initialization in production mode.

---

flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/DemoView.java

This affects all component demos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3623)

Fix NPE when navigating to an unknown URL

---

flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java
flow-client/src/main/java/com/vaadin/client/Registry.java
flow-client/src/main/java/com/vaadin/client/communication/Poller.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExportedJSFunctionView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExportedJSFunctionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3626)

Publish a JS method for polling the server for changes

---

flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationStateRenderer.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java

Fixes #3614
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3629)

Don't traverse parent layouts for enter navigation event

---

flow-server/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3634)

Depend on only one version of commons-io

---

flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationStateRenderer.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java

Fixes #3605
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3636)

Don't traverse parent layout's hierarchy for after navigation event

---

flow-data/src/main/java/com/vaadin/flow/data/provider/ArrayUpdater.java
flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java

Needed for fixing vaadin/vaadin-grid-flow#109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3635)

Inform array updaters about client size initialization

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3639)

Use TestBench beta1

---

flow-spring-addon/pom.xml
flow-spring-boot-starter/pom.xml
flow-tests/pom.xml
flow-tests/test-spring-war/pom.xml
flow-tests/test-spring/pom.xml

Fixes #3308
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3641)

Update to Spring Boot 2 release

---

flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationStateRenderer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3645)

Remove redundant synchronization

---

flow-data/src/main/java/com/vaadin/flow/data/provider/ArrayUpdater.java
flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3637)

Mark DataCommunicator as Serializable

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringServlet.java

Fixes #2820
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3653)

Remove broken Shady DOM forcing feature

---

flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringServlet.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3655)

Add new SERVLET_PARAMETER_REQUEST_TIMING to spring servlet

---

drivers.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3669)

Use Chromdriver 2.36

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java

Port Change from framework. 
Original PR is vaadin/framework#10574
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3667)

Fix removeUI assertions to work with proxy UIs

---

flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java

Port change from framework.
Original commit is vaadin/framework#10629
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3673)

Add Content-Type with charset to notifications sent via Push

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FrontendDataProvider.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FrontendToolsManager.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageForProductionMojo.java
flow-maven-plugin/src/main/resources/gulpfile.js
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/common/FrontendDataProviderTest.java

With this patch it's possible to disable the minification of resources when using the `flow-maven-plugin`.
This is specially useful when debugging production code (such as transpiled code for IE11).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3681)

Add an option to disable minification.

---

flow-data/src/main/java/com/vaadin/flow/data/binder/BeanPropertySet.java
flow-data/src/main/java/com/vaadin/flow/data/binder/BeanValidationBinder.java
flow-data/src/main/java/com/vaadin/flow/data/binder/PropertyDefinition.java
flow-data/src/test/java/com/vaadin/flow/data/binder/BeanPropertySetTest.java

Port change from framework 8.3.0.alpha1
original commit vaadin/framework#10271
the test with grid will be move to grid repo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3659)

Fix nested bean property name

---

flow-server/src/main/java/com/vaadin/flow/server/SystemMessages.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3665)

Change session expired default to reload page

---

flow-data/src/main/java/com/vaadin/flow/data/binder/PropertyDefinition.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3690)

Remove unnecessary method on PropertyDefinition interface.

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/UIInitEvent.java
flow-server/src/main/java/com/vaadin/flow/server/UIInitListener.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServiceInitListener.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java

Support UIListeners in VaadinService.
The listeners get called every time a new UI is being created.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3691)

Possibility to add ui init listeners.

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3696)

Use TestBench beta2

---

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/Id.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3711)

Remove javadoc reference to deprecated stuff

---

flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3715)

Avoid and prevent modifying the globally shared route list

---

flow-data/src/main/java/com/vaadin/flow/data/selection/MultiSelectionEvent.java
flow-data/src/main/java/com/vaadin/flow/data/selection/SelectionEvent.java
flow-data/src/main/java/com/vaadin/flow/data/selection/SelectionListener.java
flow-data/src/main/java/com/vaadin/flow/data/selection/SelectionModel.java
flow-data/src/main/java/com/vaadin/flow/data/selection/SingleSelectionEvent.java

Fixes #3404 and #3707
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3718)

Add getSource() and isFromClient() methods to SelectionEvent iface

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/test/java/com/vaadin/flow/component/UITest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/BodyScrollView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BodyScrollIT.java

Fixes #3701
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3717)

Don't add scroll attribute for a UI instance.

---

flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3724)

Disable multi logger of springBeans for I18N

---

flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java

Fixes #3624
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3723)

Unit tests in RouterTest are rewritten

---

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/DefaultTemplateParser.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateParser.java
flow-server/src/test/java/com/vaadin/flow/component/CompositeTest.java
flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/DefaultTemplateParserTest.java
flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/TemplateInitializerTest.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/PolymerServerEventHandlersTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/CustomElementRegistryInitializerTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/CustomElementsTest.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/TemplateModelTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/dependencies/FrontendInlineApiView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/LazyLoadingTemplateView.java

Fixes #3265
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3719)

Rework template parser to return template URI and use it in logger

---

flow-push/pom.xml
flow-server/src/main/java/com/vaadin/flow/server/Constants.java

Fixes #3732
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3734)

Upgrade to new Atmosphere

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/router/Router.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3704)

Navigate should handle reentrant navigation.

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3742)

Use TestBench beta3

---

flow-server/src/main/java/com/vaadin/flow/dom/ElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/Node.java
flow-server/src/main/java/com/vaadin/flow/dom/NodeVisitor.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/AbstractNodeStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/AbstractTextElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/ShadowRootStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/TemplateElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/TemplateTextElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/router/EventUtil.java
flow-server/src/test/java/com/vaadin/flow/component/UITest.java
flow-server/src/test/java/com/vaadin/flow/dom/BasicElementStateProviderTest.java
flow-server/src/test/java/com/vaadin/flow/dom/ShadowRootTest.java
flow-server/src/test/java/com/vaadin/flow/dom/TestNodeVisitor.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3744)

Refactor NodeVisitor to have control over recursion

---

flow-server/src/main/java/com/vaadin/flow/component/EventData.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3746)

Describe how @EventData expressions are evaluated

---

flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/PushConfigurationMap.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
flow-server/src/test/java/com/vaadin/flow/server/AbstractDeploymentConfigurationTest.java
flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java

Also fixes the problem that a defined push URL was never used
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3740)

Allow configuring push URL through deployment configuration

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3751)

Use latest testbench version

---

flow-components-parent/flow-generated-components/json_metadata/vaadin-checkbox.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-combo-box-light.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-combo-box.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-date-picker-light.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-date-picker.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-infinite-scroller.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-password-field.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-radio-button.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-radio-group.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-text-area.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-text-field.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-upload.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/checkbox/GeneratedVaadinCheckbox.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBoxLight.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinDatePicker.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinDatePickerLight.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinInfiniteScroller.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioButton.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinPasswordField.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextField.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUpload.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json

including: vaadin-checkbox, vaadin-combo-box, vaadin-date-picker,vaadin-radio-button, vaadin-text-field, vaadin-upload
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3761)

Update Generated components

---

flow-server/src/main/java/com/vaadin/flow/component/Component.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/Id.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java

Fixes #3714
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3745)

Improve javadocs considering @Id limitations.

---

flow-components-parent/flow-generated-components/json_metadata/vaadin-list-box.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-tab.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-tabs.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/listbox/GeneratedVaadinListBox.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTab.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/tabs/GeneratedVaadinTabs.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3768)

Update generated code based on webcomponents

---

webjars-bom/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3769)

Fix list-mixin version

---

flow-server/src/main/java/com/vaadin/flow/dom/Element.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/ClearNodeChildrenView.java
flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/ClearNodeChildren.html
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ClearNodeChildrenIT.java

Add specific tests for the setText feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3762)

Change setText behavior to always clear the client side first.

---

flow-spring-addon/src/main/java/com/vaadin/flow/spring/VaadinWebsocketEndpointExporter.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3782)

Avoid IllegalStateException because of ServerContainer absence

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3786)

Update testbench version to beta5

---

webjars-bom/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3776)

Update vaadin-lumo-styles and vaadin-item versions

---

flow-server/src/main/java/com/vaadin/flow/router/EventUtil.java
flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
flow-server/src/test/java/com/vaadin/flow/router/EventUtilTest.java

As defined in #3649
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3775)

Redefine navigation event firing

---

flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
flow-client/src/main/java/com/vaadin/client/flow/nodefeature/NodeList.java
flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java
flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/ChangeInjectedComponentTextView.java
flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/ChangeInjectedComponentTextView.html
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ChangeInjectedComponentTextIT.java

Fixes #43
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3771)

Correct removeAllChildren() behavior when node is just attached and IT test for setText() 

---

flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java

Also adds a shorthand for registering navigation targets
Closes #3687
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3793)

Test that highlights are updated for router links in a router layout

---

flow-components-parent/flow-generated-components/json_metadata/vaadin-progress-bar.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/progressbar/GeneratedVaadinProgressBar.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3799)

Update progress bar web component version

---

flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
flow-server/src/test/java/com/vaadin/flow/router/RouterLinkTest.java

Fixes #3720.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3721)

Add support for query parameters to RouterLink

---

flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
flow-client/src/main/java/com/vaadin/client/communication/PushConnectionFactory.java
flow-client/src/main/resources/com/vaadin/ClientEngineXSI.gwt.xml

As in Vaadin 8 let PushConnection be customizable via GWT `replace-with`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3788)

Allow custom PushConnection implementations on client side (#3752)

---

flow-tests/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3792)

Disable test-spring-war module because of issue with websockets

---

flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/dependencies/DependenciesLoadingPageApiView.java
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3823)

Update jetty from 9.3.7 to 9.4.9

---

flow-components-parent/flow-component-demo-helpers/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3828)

Downgrade jetty for components.

---

flow-spring-addon/src/main/java/com/vaadin/flow/spring/VaadinWebsocketEndpointExporter.java
flow-tests/pom.xml
flow-tests/test-spring-boot-undertow/pom.xml
flow-tests/test-spring-boot-undertow/src/main/java/com/vaadin/flow/spring/test/TestServletInitializer.java
flow-tests/test-spring-boot-undertow/src/main/resources/application.properties

This reverts commit c69acafd395705f1c2924d7c01ab472c01e80a8f.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3832)

Fix websockets issue and enable test-spring-war module

---

drivers.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3845)

Update chromedriver to version 2.37.

---

flow-server/src/main/java/com/vaadin/flow/component/Focusable.java
flow-server/src/main/java/com/vaadin/flow/component/HasComponents.java
flow-server/src/main/java/com/vaadin/flow/component/HasEnabled.java
flow-server/src/main/java/com/vaadin/flow/component/HasValue.java
flow-server/src/test/java/com/vaadin/flow/component/HasEnabledTest.java
flow-server/src/test/java/com/vaadin/flow/component/HasValueTest.java

Fix for #3816
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3848)

Add HasEnabled mixin and apply it for a number of existing mix-ins

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java

Update javaDoc to be clearer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3850)

Make it clearer in javaDoc what getUrlTranslation actually does.

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/test/TemplatePushView.java
flow-tests/test-spring-common/src/main/resources/META-INF/resources/frontend/TemplatePushView.html
flow-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/TemplatePushIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3811)

Make sure executeJavascript calls are pushed

---

flow-components-parent/flow-generated-components/json_metadata/vaadin-split-layout.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3856)

Update generated SplitLayout to 4.0.0

---

flow-client/src/main/java/com/vaadin/client/Console.java
flow-client/src/main/java/com/vaadin/client/flow/ExecuteJavaScriptProcessor.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ClientSideExceptionHandlingView.java
flow-tests/test-root-context/src/main/webapp/frontend/externalErrorTrigger.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3858)

Log the actual cause of errors from execJavaScript

---

flow-data/src/main/java/com/vaadin/flow/data/renderer/BasicRenderer.java
flow-data/src/main/java/com/vaadin/flow/data/renderer/NativeButtonRenderer.java
flow-data/src/test/java/com/vaadin/flow/data/renderer/NativeButtonRendererTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3863)

Add support for disabled buttons on NativeButtonRenderer

---

flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java

Part of #3802
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3855)

Use UTF-8 to read resources and do not replace new lines

---

flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBusUtil.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3869)

Minor javadoc update for ComponentEventBusUtil.

---

flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringServlet.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3873)

Remove dead code

---

flow-components-parent/flow-generated-components/json_metadata/vaadin-checkbox.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-password-field.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-text-area.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-text-field.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/checkbox/GeneratedVaadinCheckbox.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinPasswordField.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextField.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3874)

Update generated files

---

webjars-bom/pom.xml

update vaadin-lumo-styles to 1.0.0;
update vaadin-item to 2.0.0;
update vaadin-list-mixin to 2.0.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3883)

Update webjars versions in the webjars-bom

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3895)

Delete random call to getDeploymentConfiguration()

---

flow-server/src/main/java/com/vaadin/flow/component/PropertyDescriptor.java
flow-server/src/main/java/com/vaadin/flow/component/PropertyDescriptors.java
flow-server/src/test/java/com/vaadin/flow/component/PropertyDescriptorsTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3899)

Provide a getter for the property name in a PropertyDescriptor

---

flow-server/src/test/java/com/vaadin/flow/server/webjar/WebJarServerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3880)

Change WebJarServerTest to test WebJarServer

---

flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
flow-server/src/test/java/com/vaadin/flow/server/CustomUIClassLoaderTest.java
flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3864)

Make StaticFileServer use servlet instead of service

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/test/java/com/vaadin/flow/component/UITest.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java

Fixes #3802
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3909)

Store appId instead of calculating it on demand

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/startup/RouteTarget.java
flow-server/src/main/java/com/vaadin/flow/theme/AbstractTheme.java
flow-server/src/main/java/com/vaadin/flow/theme/Theme.java
flow-server/src/main/java/com/vaadin/flow/theme/ThemeDefinition.java
flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java

Update Lumo class to support LIGHT and DARK variants. Update Flow internals to properly propagate the variant choice across route targets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3922)

Add support for Theme variants

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3887)

Use VaadinService methods in BundleFilter

---

flow-server/src/main/java/com/vaadin/flow/theme/AbstractTheme.java
flow-server/src/test/java/com/vaadin/flow/theme/AbstractThemeTest.java

Only the last match for the base part should
be replaced with the theme part.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3930)

Only the last instance of the base path should be changed.

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3928)

Use VaadinService resolve methods in BootstrapHandler

---

flow-server/pom.xml

Fixes #3780
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3926)

Update style parser dependency version

---

flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java
flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java
flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
flow-server/src/test/java/com/vaadin/flow/shared/VaadinUriResolverTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3916)

Properly normalize Vaadin URIs when parsing HTML imports 

---

flow-server/src/main/java/com/vaadin/flow/component/Component.java
flow-server/src/main/java/com/vaadin/flow/dom/Node.java
flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateMappingDetectorView.java
flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/TemplateMappingDetector.html
flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/TemplateMappingDetectorParent.html
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateMappingDetectorIT.java

Both methods are relevant to identify whether a component was attached as part of a template or if it a standalone component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3927)

Add isTemplateMapped to Component and isVirtualChild for Node

---

flow-server-production-mode/src/main/resources/META-INF/web-fragment.xml

Fixes #3924
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3940)

Use web fragment id compatible with WebLogic

---

flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/temp/NPEHandler.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3911)

Print the stacktrace for NPEs in testing views

---

flow-server/src/main/java/com/vaadin/flow/server/startup/BundleDependencyFilter.java
flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/startup/BundleDependencyFilterTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java

Reworked the way Flow checks for fragments during the initialization.
Fixes:
* Main bundle is now searched by prefix, not the full name match
* Moved main bundle presence validation into `BundleFilterInitializer`
* The order dependencies are returned when filtered by `BundleDependencyFilter`  - fragments should be  returned before imports that are not from any fragment, otherwise we might get errors
* Corresponding tests added and fixed. 
* Check exception messages in tests, since some tests failed to check the things they declared because they've got different exception with same type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3947)

Rework Flow bundle filter initialization

---

flow-server/src/main/java/com/vaadin/flow/dom/Element.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3950)

Don't remove attribute from unsupported providers.

---

flow-server/src/main/java/com/vaadin/flow/server/communication/JSR356WebsocketInitializer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3952)

Add some debug logging to make it easier to analyze push init problems

---

flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeButton.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3942)

Add missing interface to NativeButton

---

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
flow-server/src/main/java/com/vaadin/flow/internal/UsageStatistics.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-tests/test-root-context/pom.xml
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/frontend/UsageStatisticsView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3944)

Report select Flow features in the same way as Vaadin components

---

flow-server/src/main/java/com/vaadin/flow/component/Text.java

Fixes #3606
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3948)

Make Text implement HasText

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3951)

Wait for 2 seconds instead of 2000 seconds in test

---

flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentMetaData.java
flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerPushConfigurationTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3945)

Use VaadinService resolve methods in HtmlDependencyParser

---

flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3957)

Move bundle initialization checks from inner loop.

---

flow-client/src/main/java/com/vaadin/client/BrowserInfo.java
flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java

fixes #2844
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3953)

Remove `v-` classes from body

---

flow-components-parent/flow-generated-components/json_metadata/vaadin-password-field.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-text-area.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-text-field.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinPasswordField.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextField.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3955)

Update vaadin-text-field to 2.0.1

---

flow-server/src/main/java/com/vaadin/flow/internal/ReflectionCache.java
flow-server/src/test/java/com/vaadin/flow/internal/ReflectionCacheTest.java

Contributes to #3186
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3968)

Make it possible to clear all reflection caches

---

flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
flow-server/src/main/java/com/vaadin/flow/router/ErrorParameter.java
flow-server/src/main/java/com/vaadin/flow/router/Router.java
flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java
flow-server/src/test/java/com/vaadin/flow/router/ErrorParameterTest.java
flow-server/src/test/java/com/vaadin/flow/router/InternalServerErrorTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/temp/NPEHandler.java

Fixes #3902
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3954)

Distinguish between error parameter and the caught exception

---

flow-server/src/main/java/com/vaadin/flow/component/Component.java
flow-server/src/main/java/com/vaadin/flow/i18n/I18NProvider.java
flow-server/src/test/java/com/vaadin/flow/server/TestProvider.java

Fixes #2919
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3970)

Distinguish I18NProvider API and SPI.

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/TemplateInitializerTest.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinServletServiceTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java

Add `mocks.cleanup()` to tests using
`MockServletServiceSessionSetup`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3971)

Fix themedPath exists check.

---

flow-data/pom.xml
flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataProvider.java
flow-data/src/test/java/com/vaadin/flow/data/provider/ListDataProviderTest.java

Fixes #3961
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3962)

Make it possible to serialize data providers

---

flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java

Fixes #3935
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3937)

Detect IE11 as IE11 when in compatibility mode (#3935)

---

flow-server/src/main/java/com/vaadin/flow/component/PushConfiguration.java
flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
flow-server/src/main/java/com/vaadin/flow/router/Router.java
flow-server/src/main/java/com/vaadin/flow/server/StreamResourceRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
flow-server/src/test/java/com/vaadin/flow/component/LocationObserverTest.java
flow-server/src/test/java/com/vaadin/flow/component/UITest.java
flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
flow-server/src/test/java/com/vaadin/flow/internal/JsonCodecTest.java
flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java
flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ClientDelegteHandlersTest.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeMapTest.java
flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java

Fixes #3790
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3797)

Make lock checking more strict

---

flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/DefaultTemplateParser.java
flow-server/src/main/java/com/vaadin/flow/server/DependencyFilter.java
flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
flow-server/src/main/java/com/vaadin/flow/server/startup/BundleDependencyFilter.java
flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java
flow-server/src/main/java/com/vaadin/flow/server/startup/FakeBrowser.java
flow-server/src/test/java/com/vaadin/flow/server/startup/BundleDependencyFilterTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java

Fixes: #3974
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3976)

Handle ES5 hash names

---

flow-server/src/main/java/com/vaadin/flow/router/Router.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java

Fixes #3988 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3992)

Exception view event should have the original trigger.

---

flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java
flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ExclusionRegistry.java
flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java
flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/registry/ExclusionRegistryTest.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java

Add and fix tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3995)

Make generator to remove HasStyle from dialog and notification

---

flow-server/src/test/java/com/vaadin/flow/component/UITest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4002)

Fix UITests so that we have the session object.

---

flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java
flow-data/src/main/java/com/vaadin/flow/data/value/ValueChangeMode.java
flow-data/src/test/java/com/vaadin/flow/data/value/ValueChangeModeTest.java
flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java
flow-server/src/test/java/com/vaadin/flow/component/AbstractFieldTest.java
flow-server/src/test/java/com/vaadin/flow/component/AbstractSinglePropertyFieldTest.java
flow-server/src/test/java/com/vaadin/flow/component/ValueChangeMonitor.java
flow-server/src/test/java/com/vaadin/tests/PublicApiAnalyzer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3997)

Add AbstractSinglePropertyField

---

flow-tests/test-root-context/pom.xml
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/webcomponent/PaperInputIT.java
flow-tests/test-root-ui-context/pom.xml
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4001)

Remove bintray url. Replace components' versions with the ones present on Maven Central.

---

flow-server/src/main/java/com/vaadin/flow/component/AbstractField.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4004)

Rename and clarify docs for default value parameter

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/test/java/com/vaadin/flow/component/UITest.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ServiceInitListenersView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ServiceInitListenersIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/3996)

Add beforeEnterListeners before navigating to the target.

---

flow-server/src/main/java/com/vaadin/flow/dom/DebouncePhase.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4008)

Add missing period at the end of DebouncePhase javadocs

---

flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4010)

Show no routes instead of NPE on 404 page if duplicate routes were set

---

flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4011)

Clarify acceptNullValues parameter description

---

flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java
flow-server/src/main/java/com/vaadin/flow/component/internal/AbstractFieldSupport.java
flow-server/src/test/java/com/vaadin/flow/component/AbstractCompositeFieldTest.java
flow-server/src/test/java/com/vaadin/flow/component/AbstractSinglePropertyFieldTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4009)

Add AbstractCompositeField

---

flow-html-components/src/main/java/com/vaadin/flow/component/html/Input.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java

Fixes #3984
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4007)

Make Input implement HasValue and Focusable

---

flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java
flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBoxLight.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinDatePicker.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinDatePickerLight.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinInfiniteScroller.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinPasswordField.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextField.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4019)

Expose abstract ctor

---

flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java
flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/PropertyNameRemapRegistry.java
flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ValuePropertyRegistry.java
flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/checkbox/GeneratedVaadinCheckbox.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinInfiniteScroller.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4023)

Remap value prop

---

flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java
flow-server/src/test/java/com/vaadin/flow/component/AbstractSinglePropertyFieldTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4026)

Allow passing the component instance to the converters

---

flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java
flow-server/src/test/java/com/vaadin/flow/component/AbstractSinglePropertyFieldTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4029)

Add support for JsonValue properties

---

drivers.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4032)

Use latest chromedriver

---

flow-server/src/main/java/com/vaadin/flow/templatemodel/BasicComplexModelType.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/BasicModelType.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/ConvertedModelType.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/ListModelType.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/ModelType.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4028)

Remove angular templates leftovers

---

flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java
flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/BehaviorRegistry.java
flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ExclusionRegistry.java
flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ValuePropertyRegistry.java
flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/checkbox/GeneratedVaadinCheckbox.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBoxLight.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinDatePicker.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinDatePickerLight.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinInfiniteScroller.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinPasswordField.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextField.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4033)

Update generator to support the new SerializableBiFunction constructor

---

flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBoxLight.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4043)

Update ComboBox to 4.0.1

---

flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementAttributeMap.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeMap.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMapTest.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeMapTest.java

Fixes #3994
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4037)

Fire an event on removeProperty

---

flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java
flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/registry/PropertyNameRemapRegistryTest.java
flow-components-parent/flow-generated-components/json_metadata/vaadin-combo-box-light.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-combo-box.json
flow-data/src/main/java/com/vaadin/flow/data/value/ValueChangeMode.java
flow-server/src/main/java/com/vaadin/flow/component/HasValue.java

Fixes #3846
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4053)

Remove getClientValuePropertyName and getClientPropertyChangeEventName

---

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
flow-data/src/main/java/com/vaadin/flow/data/provider/QueryTrace.java
flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java

Fixes vaadin/vaadin-grid-flow#171
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4036)

Keep an eye on following the data provider contract

---

flow-server/src/main/java/com/vaadin/flow/component/page/Viewport.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4066)

Add a mobile friendly default viewport tag

---

flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java
flow-server/src/main/java/com/vaadin/flow/component/AbstractField.java
flow-server/src/test/java/com/vaadin/flow/component/AbstractCompositeFieldTest.java
flow-server/src/test/java/com/vaadin/flow/component/AbstractFieldTest.java

Fixes #4067
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4069)

Make isEmpty() use valueEquals()

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java

Fixes #2926
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4038)

Update locale for all UIs in the session

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4052)

Use latest testbench

---

flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4083)

Remove unused constants.

---

flow-components-parent/flow-component-demo-helpers/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4088)

Remove test-util dep (moved to component base)

---

flow-components-parent/flow-component-demo-helpers/pom.xml
pom.xml

This reverts commit 352855779ec4ce3da48b9f1bb0a70551feb89d14.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4098)

Revert "Update jetty version (#4094)"

---

flow-server/src/main/java/com/vaadin/flow/component/ComponentEvent.java
flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java
flow-server/src/test/java/com/vaadin/flow/component/ComponentEventBusTest.java

Fixes #2044
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4073)

Allow unregistering an event listener inside the listener itself

---

flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementListenersTest.java

Related to #4105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4120)

Explicitly test that ElementListenerMap can be serialized

---

flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/ConvertedModelType.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/TemplateModelWithEncodersTest.java

Fixes #4092
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4125)

Make primitive types and their boxed types compatible in encoders

---

flow-maven-plugin/src/main/resources/gulpfile.js
flow-maven-plugin/src/main/resources/package.json
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java

Fix issue #3959 
Update flow-maven-plugin dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4099)

Provide es5 adapter for the detected browsers running on IOS 10

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4128)

Update testbench to beta10

---

flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java

Fixes #4116
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4131)

Properly detect embedded iOS browsers as supporting ES6

---

flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/checkbox/GeneratedVaadinCheckbox.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinDatePicker.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/datepicker/GeneratedVaadinDatePickerLight.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json

vaadin-checkbox 2.1.0
vaadin-date-picker 3.0.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4133)

Regenerate components

---

flow-server/src/main/java/com/vaadin/flow/templatemodel/AbstractBasicModelType.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/BasicComplexModelType.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/BasicModelType.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/BeanModelTypeTest.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/ModelDescriptorTest.java

Fixes #4126
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4137)

Support client-originated integers in models

---

flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4144)

Use es5 adapter also for desktop Safari 10

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FrontendToolsManager.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageForProductionMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/production/TranspilationStep.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/production/TranspilationStepTest.java

Fixes #4122
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4135)

Provide an option to specify network concurrency arg for yarn

---

flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java
flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtPolymerModelTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/CustomCustomElementView.java
flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/CustomCustomElement.js
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/CustomCustomElementIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4147)

Only do hookUpPolymerElement for Polymer elements

---

flow-server/src/main/java/com/vaadin/flow/component/HasValue.java

Fix for #4077
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4149)

Clarify javadocs for setRequiredIndoctor method

---

flow-data/src/test/java/com/vaadin/flow/data/binder/BeanBinderTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4156)

Remove test for invalid case rejected by the bean validator lib

---

flow-data/pom.xml
flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
flow-data/src/test/java/com/vaadin/flow/tests/data/DataSerializableTest.java

Related to vaadin/platform#173
Related to #4105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4163)

Make Binder serializable, add test

---

flow-server/src/test/java/com/vaadin/tests/server/component/FlowClassesSerializableTest.java

Related to https://github.com/vaadin/platform/issues/173
Related to #4105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4162)

Add serialization test for HtmlComponent and HtmlContainer

---

flow-server/src/main/java/com/vaadin/flow/dom/Element.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementAttributeMap.java
flow-server/src/test/java/com/vaadin/tests/server/component/FlowClassesSerializableTest.java

Fixes https://github.com/vaadin/vaadin-upload-flow/issues/48
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4173)

Jvm bug workaround

---

flow-components-parent/flow-generated-components/json_metadata/vaadin-checkbox.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-form-item.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-form-layout.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/checkbox/GeneratedVaadinCheckbox.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormItem.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormLayout.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json

Regenerate the vaadin-form-layout based on version 2.0.1
Regenerate the vaadin-checkbox based on version 2.1.1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4182)

Regenerate webcomponents

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4185)

Update to testbench beta11

---

flow-server/src/main/java/com/vaadin/flow/component/ComponentEvent.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4179)

Hide implementation detail from public API

---

flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/collections/ListBindingView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/collections/Message.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/collections/TwoWayListBindingView.java
flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/collections/TwoWayListBinding.html
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/collections/TwoWayListBindingIT.java

Fixes #4091
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4160)

Make two way data binding work with beans in list

---

flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4192)

Add a check for shadow root presence before querying dom-repeats

---

flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/test/java/com/vaadin/flow/component/UITest.java

Fixes #4178
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4183)

Detach UI children when detaching the UI

---

flow-data/src/main/java/com/vaadin/flow/data/binder/BeanPropertySet.java
flow-data/src/test/java/com/vaadin/flow/data/binder/BeanPropertySetTest.java

Port Change from framework, original PR vaadin/framework#10635
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4204)

Always return a fresh copy of BeanPropertySet from cache

---

flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java

Port Change from framework 8.4.0.alpha1
Original PR is vaadin/framework#10745
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4205)

Fix ValueChangeListener order changes with Binder

---

flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractTestBenchTest.java
flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4210)

Add option to run IE11 tests in BrowserStack

---

flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java

Port change from framework 8.4.0.alpha1
Original PR is vaadin/framework#10724
Test class will be ported to the component repository
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4207)

Added method asRequired with a custom required validator

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4211)

Update to testbench rc1

---

flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java
flow-server/src/test/java/com/vaadin/flow/internal/ReflectToolsTest.java

Fixes #2631
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4215)

Filter out synthetic methods for setters/getters

---

flow-server/src/main/java/com/vaadin/flow/router/Router.java

fix PARAMETER_PATTREN -> PARAMETER_PATTERN
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4233)

fix typo PATTREN -> PATTERN

---

flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/ThemeListImpl.java
flow-server/src/test/java/com/vaadin/flow/component/HasThemeTest.java

- For better api to edit theme(s) of component(s)
for example:
Button button = new Button("Important");
button.addThemeName("primary");
- Needs to be implemented (directly, or indirectly) to components that support theme-attribute
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4187)

Added HasTheme interface

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CopyProductionFilesMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageForProductionMojo.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4236)

Add javadocs for maven plugin configuration parameters.

---

flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java

Debug window no longer exists
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4243)

remove reference to ?debug URL parameter

---

flow-server/src/main/java/com/vaadin/flow/component/AbstractField.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4242)

Fix setPresentationValue javadoc typo

---

flow-tests/servlet-containers/tomcat85/pom.xml
flow-tests/test-root-context/pom.xml

Fixes #4248
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4250)

Use UI classes as a test dependency in integration tests

---

flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html

Fix for grid#122
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4244)

Listen clicks on renderer component and forwards to the children

---

flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html

Fixes #4109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4246)

Replaces the first child node (not element)

---

flow-tests/servlet-containers/tomcat85/pom.xml
flow-tests/servlet-containers/tomcat9/pom.xml

Fixes #4251
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4252)

Specify es5 frontend folder (same as es6) for production tests

---

flow-components-parent/flow-component-demo-helpers/pom.xml
pom.xml

Remove the override in flow-component-demo-helper
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4255)

Update flow jetty-version to 9.4.11

---

pom.xml

Related to #4164
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4249)

Java 10 partial compatibility (tests still need to be fixed)

---

flow-tests/servlet-containers/tomcat9/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4256)

Add ui jar file as a test dependency for tomcat9

---

flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4259)

Improve click handling in flow-component-renderer

---

pom.xml

Remove settings and dependency about nexus-staging-maven-plugin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4281)

Use vaadin-parent pom

---

flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DomEventFilterView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AttachExistingElementIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BodyScrollIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ClientSideExceptionHandlingIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LoadingIndicatorIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShadowRootIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyIT.java
flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/RPCLoggerIT.java

Fixes most tests in package `com.vaadin.flow.uitest.ui`
More comprehensive explanations in the commit messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4278)

Fix a bunch of individual test failures on IE11

---

flow-components-parent/pom.xml
flow-html-components-testbench/pom.xml
flow-tests/pom.xml
flow/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4286)

Make empty flow module pom instead of jar

---

flow-test-util/src/main/java/com/vaadin/flow/testcategory/IgnoreIE11.java
flow-test-util/src/main/java/com/vaadin/flow/testcategory/ScreenshotTests.java
flow-test-util/src/main/java/com/vaadin/flow/testcategory/TestCategory.java

to make sure that the test categories are Serializable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4291)

Add TestCategory marker interface

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/InjectScriptTagView.java
flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/InjectScriptTagTemplate.html
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/InjectScriptTagIT.java

Fix #4285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4292)

Remove open tags (<) from the UIDL when a comment is present

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/AbstractScrollIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/MultipleAnchorsIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/ScrollIT.java

Fix for #4263
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4294)

Introduce a delta to verify the scroll position

---

flow-tests/test-common/pom.xml
flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/ui/dependencies/DependenciesLoadingBaseView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4296)

Disable javadocs for test-common

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/PolymerDefaultPropertyValueIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/PolymerModelPropertiesIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/PolymerPropertiesIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/PolymerPropertyChangeEventIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/PolymerPropertyMutationInObserverIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/PropertiesUpdatedBeforeChangeEventsIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/RestoreViewWithAttachedByIdIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/SubPropertyModelIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4301)

Use TB Query method instead of find/getInShadowRoot methods

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ElementInitOrderIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/AttachExistingDomElementByIdIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateHasInjectedSubTemplateIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateInTemplateIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateInTemplateWithIdIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplatesVisibilityIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TwoWayPolymerBindingIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/UpdatableModelPropertiesIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/UpgradeElementIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/collections/ClearListIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/collections/ListBindingIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/collections/ListInsideListBindingIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/imports/LazyWidgetIT.java
flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/template/RouterLinksIT.java

Use TB query methods instead of shadow root methods
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4305)

Remaining part for #4265

---

flow-tests/pom.xml

settings are for the `nexus-staging-maven-plugin`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4307)

Skip the deployment for test modules

---

flow-theme-integrations/lumo/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4308)

Use fixed iron-flex-layout version in the lumo dependency

---

flow-theme-integrations/lumo/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4310)

Exclude iron-flex-layout from lumo

---

flow-components-parent/flow-generated-components/pom.xml
flow-tests/test-root-context/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4314)

Exclude iron-flex-layout dependency and skip module from deployment

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4315)

Update TestBench to final

---

flow-theme-integrations/material/pom.xml

Fix the snapshot fail on find theme integration 1.0-SNAPSHOT

Update parent version to 1.1-snapshot

---

flow-theme-integrations/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4295)

Make flow-server provided in flow-theme-integrations

---

flow-server-production-mode/src/main/resources/META-INF/web-fragment.xml

Fix production mode fragment.

---

flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/TemplateModelTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/collections/ToggleNullListView.java
flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/collections/ServerModelNullList.html
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/collections/ToggleNullListIT.java

Repopulate empty model lists on detach.

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/production/ProductionModeCopyStep.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/production/TranspilationStep.java

Remove confusing javadocs.

---

flow-server/src/main/java/com/vaadin/flow/router/RouteData.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java

Print current routes of the application on start.

---

flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/StreamResourceView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4425)

Stream resource test (targeted for OSGi).

---

pom.xml

Fix for #4419
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4430)

Add API diff via profile in the vaadin-parent project

---

pom.xml

* Add API diff via profile in the vaadin-parent project
Fix for #4419
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4433)

Add API diff via profile in the vaadin-parent project (#4430)

---

drivers.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4447)

Update ChromeDriver version

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CopyProductionFilesMojo.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4455)

Process jars only in flow-maven-plugin.

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/production/WebJarPackage.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/production/WebJarPackageTest.java

Closes #4415
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4462)

When multiple same bower.json files are present in the same package, use the topmost one.

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FrontendDataProvider.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/common/FrontendDataProviderTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4470)

Do not process absolute imports. Log, if not processing the import.

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FrontendDataProvider.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/production/ProductionModeCopyStep.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4475)

Show more detailed exception when an import is not found.

---

flow-components-parent/flow-webcomponent-api-analyzer/gulpfile.js
flow-components-parent/flow-webcomponent-api-analyzer/lib/js/variants-transform.js

Adjust the regex to match windows machines
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4476)

 Fix the path used in the gulpfile 

---

flow-server/src/main/java/com/vaadin/flow/server/UnsupportedBrowserHandler.java

Fixes #3803
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4484)

Update UnsupportedBrowserHandler with removing Chrome Frame

---

flow-server/src/main/java/com/vaadin/flow/server/UnsupportedBrowserHandler.java

Fixes #3803
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4485)

Update UnsupportedBrowserHandler with removing Chrome Frame (#4484)

---

flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

Exclude all classes in 'test-classes' from the serialization test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4486)

Exclude all classes in 'test-classes' from the serialization test 

---

flow-html-components/src/main/java/com/vaadin/flow/component/html/Article.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/Aside.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/DescriptionList.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/Div.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/Emphasis.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/Footer.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/H1.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/H2.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/H3.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/H4.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/H5.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/H6.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/Header.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/ListItem.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/Main.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/Nav.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/OrderedList.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/Paragraph.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/Section.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/Span.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/UnorderedList.java

Fixes #4500
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4505)

Use a component type in ClickNotifier generic for HTML components

---

flow-data/src/main/java/com/vaadin/flow/data/provider/HasDataGenerators.java

Inspired by #4401
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4502)

Deprecate removeDataGenerator (#4494)

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java

Fixes #4426
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4501)

Use FaviconHandler only for servlets (#4495)

---

flow-server/src/main/java/com/vaadin/flow/server/startup/ErrorNavigationTargetInitializer.java

Fixes #4511
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4512)

Fix init problem on Liberty 18

---

flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java

* Added missing servlet context attribute saving.
* Fixed naming like in route registry + added docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4509)

Performance issue fixed: pwa registry got re-calculated on each call.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4517)

 Remove branch reference from the readme

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4516)

Update Readme about no V11

---

flow-server/src/main/java/com/vaadin/flow/server/communication/JSR356WebsocketInitializer.java
flow-server/src/main/java/com/vaadin/flow/server/startup/ServletContextListeners.java
flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

Fixes #3923
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4520)

Ensure listeners deploy a servlet before adding JSR-356 support to it

---

flow-server/src/main/java/com/vaadin/flow/server/communication/JSR356WebsocketInitializer.java
flow-server/src/main/java/com/vaadin/flow/server/startup/ServletContextListeners.java
flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

Fixes #3923
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4533)

Ensure listeners deploy a servlet before adding JSR-356 support to it  (#4520)

---

flow-server/src/main/java/com/vaadin/flow/shared/VaadinUriResolver.java

Fixes #4467
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4540)

Correct @value expression to get its correct value

---

flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/DependencyIT.java

* Unify system error messages
Fixes #3777
* Remove duplicate logging call
* Fix a test by finding only direct children of body with class 'message'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4546)

Unify system error messages (#4542)

---

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java

Fixes #4434
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4541)

Throw an exception if VaadinService instance is null

---

flow-components-parent/flow-webcomponent-api-analyzer/bin/flow-webcomponent-api-analyzer.js
flow-components-parent/flow-webcomponent-api-analyzer/gulpfile.js
flow-components-parent/flow-webcomponent-api-analyzer/package-lock.json
flow-components-parent/flow-webcomponent-api-analyzer/package.json

Closes #4572 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4573)

Fix github vulnerability message.

---

flow-server/src/main/java/com/vaadin/flow/internal/UsageStatistics.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4576)

Include Java version in usage stats

---

flow-client/pom.xml
flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java

This reverts commit cb60a6cdac4e627d3019102482fc84e2f951c9c0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4582)

Revert "Serve ClientEngine as Brotli compressed if possible (#4556)"

---

flow-server/src/main/java/com/vaadin/flow/server/Constants.java
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4545)

Upgrade Atmosphere

---

flow-data/bnd.bnd

Fix #4570
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4587)

Correct the export-package for OSGi setting

---

flow-server/pom.xml

Fixes #4598
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4604)

Use updated gwt-elemental library version

---

flow-server/src/main/java/com/vaadin/flow/component/HasComponents.java
flow-server/src/test/java/com/vaadin/flow/component/HasComponentsTest.java

Part of the fix for #4600
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4605)

Make addComponentAtIndex logic FW8 compatible

---

flow-tests/pom.xml
flow-tests/test-router-custom-context/pom.xml
flow-tests/test-router-custom-context/src/main/java/com/vaadin/flow/contexttest/ui/DependencyLayout.java
flow-tests/test-router-custom-context/src/main/java/com/vaadin/flow/contexttest/ui/PathUI.java
flow-tests/test-router-custom-context/src/main/java/com/vaadin/flow/contexttest/ui/RootUI.java
flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/AbstractContextIT.java
flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/RootContextIT.java
flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/RoutedContextIT.java
flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/RoutedSubContextIT.java
flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/RoutedSubContextSubPathIT.java
flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/SubContextIT.java
flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/SubContextNoEndingSlashIT.java
flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/SubContextSubPathIT.java
flow-tests/test-subcontext/src/main/java/com/vaadin/flow/contexttest/ui/DependencyUI.java

Resolves #4621
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4627)

Add tests for Router for non-root servlet contexts

---

flow-theme-integrations/lumo/pom.xml
flow-theme-integrations/material/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4635)

Update theme dependencies.

---

flow-server/src/main/java/com/vaadin/flow/router/Location.java
flow-server/src/main/java/com/vaadin/flow/router/Router.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinRequest.java
flow-server/src/test/java/com/vaadin/flow/component/InvalidUrlTest.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/FaultyLocationIT.java

Fixes #4206
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4645)

Fix failing on internal error for routes starting with %3f

---

flow-server/src/main/java/com/vaadin/flow/component/page/BrowserWindowResizeEvent.java
flow-server/src/main/java/com/vaadin/flow/component/page/BrowserWindowResizeListener.java
flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
flow-server/src/main/resources/com/vaadin/flow/component/page/windowResizeListener.js
flow-server/src/test/java/com/vaadin/flow/component/page/PageTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/BrowserWindowResizeView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrowserWindowResizeIT.java

Fix for #4312
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4651)

Browser window resize event listener

---

flow-server/src/test/java/com/vaadin/flow/internal/HasCurrentService.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4656)

Cleanup the service before the test

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/RunnerManager.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageForProductionMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/production/RunnerManagerTest.java

Please review and accept my pull request.
Background:
- our environment does not allow internet connection for downloading the npm modules used in production mode. We have a Nexus server for this package management, and we need the npmRegistryURL available for customization (directly from flow-maven-plugin)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4639)

Customizable npm registry parameter

---

pom.xml

Also parametrize the repo names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4657)

Switch pom repo names to existing ones

---

flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicationController.java
flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/TreeData.java
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/AttachExistingElementFeature.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4632)

Remove unnecessary stream overhead

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/NoRouterUI.java
flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/NoRouterIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4661)

Take into account that UI.getRouter can return null

---

flow-components-parent/flow-code-generator/pom.xml
flow-maven-plugin/pom.xml
flow-server/pom.xml

Fix for #3700
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4666)

Update byte buddy version

---

flow-components-parent/flow-component-demo-helpers/pom.xml
flow-tests/test-root-context/pom.xml
flow-theme-integrations/pom.xml
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4670)

Use platform version of polymer dependencies

---

flow-components-parent/flow-code-generator-api/pom.xml
flow-components-parent/flow-generated-components/pom.xml
flow-components-parent/pom.xml
flow-maven-plugin/pom.xml
pom.xml

Update plugins and add dependencies so that Flow can
be compiled using JDK11 but with Java 8 language features.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4678)

JDK11 with 1.8 as target build.

---

flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/test/java/com/vaadin/flow/component/UITest.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java

Fixes #4690
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4699)

Don't empty the entire UI when attaching the router root

---

flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java

Fixes #4700
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4704)

Use route classes for validatePwaClass method

---

flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4717)

Exclude OSGi related classes from serializable test

---

flow-data/src/main/java/com/vaadin/flow/data/selection/MultiSelect.java

Fix for https://github.com/vaadin/flow/issues/4588.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4716)

Extension of MultiSelect by methods select/deselect, that accept Iterable as parameter.

---

flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java

Make `ComponentUtil#addListener(Component, Class, ComponentEventListener, Consumer)` static
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4718)

Make overloaded ComponentUtil addListener static

---

flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java
flow-components-parent/flow-generated-components/json_metadata/vaadin-checkbox-group.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroupVariant.java
flow-components-parent/flow-webcomponent-api-analyzer/lib/js/variants-transform.js
flow-components-parent/flow-webcomponent-api-analyzer/package-lock.json

Fixes #4677
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4720)

Sort variants by the theme name to produce deterministic

---

flow-data/src/main/java/com/vaadin/flow/data/selection/MultiSelect.java
flow-data/src/test/java/com/vaadin/flow/data/selection/MultiSelectTest.java

Add tests related to https://github.com/vaadin/flow/pull/4716
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4725)

Add unit tests for the MultiSelect interface

---

flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java

Fixes #4711
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4724)

Correct javadocs and add removeHref method

---

flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java

Fixes #4711
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4726)

Correct javadocs and add removeHref method (#4724)

---

flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java

Fixes starter#114
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4738)

Enable headless mode for AWT image transforms

---

flow-data/src/main/java/com/vaadin/flow/data/renderer/RendererUtil.java
flow-data/src/test/java/com/vaadin/flow/data/renderer/RendererUtilTest.java

Fixes #4054
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4732)

Execute renderer related JS on every attach

---

flow-data/src/main/java/com/vaadin/flow/data/renderer/RendererUtil.java
flow-data/src/test/java/com/vaadin/flow/data/renderer/RendererUtilTest.java

Correction for fix for #4054
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4743)

Execute attach listener right away if the node is already attached

---

drivers.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4735)

Update chromedriver to 2.43

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/EmptyListsIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4745)

Disregard HTML Imports deprecation warning

---

flow-data/src/main/java/com/vaadin/flow/data/renderer/RendererUtil.java
flow-data/src/test/java/com/vaadin/flow/data/renderer/RendererUtilTest.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/EmptyListsIT.java

Fix for #373
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4741)

Execute renderer related JS on every attach 

---

flow-server/src/main/java/com/vaadin/flow/server/webjar/WebJarServer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4753)

Do not use path info if it is null.

---

flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
flow-data/src/test/java/com/vaadin/flow/data/binder/UnbindTest.java

(cherry picked from commit 40eb2f81727e99b86d2fb1c1a11fd14fe73a3330)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4759)

Fixing NPE when unbind is called during readBean (#4752)

---

flow-tests/test-root-context/pom.xml
flow-theme-integrations/lumo/pom.xml

See https://github.com/vaadin/flow-component-base/pull/101 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4764)

Remove iron-flex-layout exclusions

---

flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMapTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/MapSyncRpcHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/templatemodel/BeanModelTypeTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/collections/TwoWayListBindingView.java
flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/MapSyncRpcHandlerTestServlet.java
flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/NotSyncedPropertyUpdate.java
flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/NotSyncedPropertyUpdateIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4779)

Return back preventing disallowed property update (#4774)

---

flow-server/src/test/java/com/vaadin/tests/server/component/FlowClassesSerializableTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4781)

Fix the NPE in the streamResource test.

---

flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ExclusionRegistry.java
flow-components-parent/flow-generated-components/json_metadata/vaadin-password-field.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-text-area.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-text-field.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinPasswordField.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextField.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/TextAreaVariant.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/TextFieldVariant.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json

Connected to https://github.com/vaadin/vaadin-text-field-flow/issues/118
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4786)

Update config and generated class for text-field

---

flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RouterLinkView.java

#4775
Implement new constructor to the Anchor class.
Write unit test for the new constructor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4789)

Anchor: add constructor that accepts a list of components (#4775)

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerPushConfigurationTest.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java

Fixes #4797
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4801)

Read client engine file only when it's needed first time

---

flow-data/pom.xml
flow-data/src/main/java/com/vaadin/flow/data/osgi/FlowComponentRendererResource.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

Fixes #4807
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4810)

Register flow-component-renderer.html web resource for OSGi

---

flow-theme-integrations/lumo/bnd.bnd
flow-theme-integrations/lumo/pom.xml
flow-theme-integrations/material/bnd.bnd
flow-theme-integrations/material/pom.xml

Fixes #4809
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4813)

Make theme modules OSGi compatible

---

flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java

Fixes #4808
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4819)

Avoid set navigation targets if they are not yet available

---

flow-server/src/main/java/com/vaadin/flow/component/HasSize.java
flow-server/src/main/java/com/vaadin/flow/dom/ElementConstants.java
flow-server/src/test/java/com/vaadin/flow/component/HasSizeTest.java

setMin(Max)Width(Height) are very useful for responsive designs.
setWidth(Height)Full are better than calling setWidth(Height)("100%") all the time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4811)

added more helper methods for HasSize

---

flow-server/src/main/java/com/vaadin/flow/component/HasEnabled.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4823)

Clarify documentation for implementers of HasEnabled

---

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
flow-server/src/main/java/com/vaadin/flow/component/HasEnabled.java

#4830 
#4823
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4831)

Pick/from master to 1.2

---

flow-server/pom.xml

Fixes #4737
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4835)

Update ByteBuddy version

---

flow-client/pom.xml
flow-data/pom.xml
flow-osgi/pom.xml
flow-server/pom.xml
flow-tests/servlet-containers/felix-jetty/pom.xml
flow-tests/test-root-context/pom.xml
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4834)

Clean up OSGi tests and use property for osgi versions

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4845)

Fixing a typo in UI Javadoc

---

flow-data/src/main/java/com/vaadin/flow/data/provider/DataProvider.java
flow-data/src/main/java/com/vaadin/flow/data/provider/FilterUtils.java
flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/AbstractHierarchicalDataProvider.java
flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalConfigurableFilterDataProvider.java
flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataProvider.java
flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalFilterUtils.java
flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/TreeDataProvider.java
flow-data/src/test/java/com/vaadin/flow/data/provider/DataProviderTestBase.java
flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/TreeDataProviderTest.java

Fixes #4839
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4846)

Make filter related methods work properly for hierarchical DP

---

flow-server/src/main/java/com/vaadin/flow/component/page/Viewport.java

Provide String constants for common @Viewport settings #3597
Maybe it would be necessary to change the name of some fields.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4873)

Viewport fixes

---

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java

Part of #3830 
Specific tests for the components that use DataProviders/DataCommunicators will need to be done separately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4889)

Make the DataCommunicator ask for new sizes when the DataProvider return less items than expected 

---

flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4905)

Fix compilation problem due to out of sync branch.

---

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4896)

Make the DataCommunicator ask for new sizes when the DataProvider return less items than expected  (#4889)

---

flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java

#4878 was originally merged without any tests since nobody had any idea
for how to test the functionality without lots of overhead. A test is
added now when a decent approach was pointed out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4908)

Add unit test for dependency filter order

---

flow-server/src/main/java/com/vaadin/flow/component/WebComponent.java
flow-server/src/main/java/com/vaadin/flow/component/WebComponentProperty.java

Fixes #4916
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4935)

Create annotations for WebComponent

---

drivers.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4936)

Update ChromeDriver to 2.45

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/router/RouteConfiguration.java
flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
flow-server/src/main/java/com/vaadin/flow/theme/ThemeUtil.java
flow-server/src/test/java/com/vaadin/flow/router/internal/RouteUtilTest.java
flow-server/src/test/java/com/vaadin/flow/theme/ThemeUtilTest.java

Fixes #4892
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4957)

RouteUtil "refactoring"

---

flow-html-components/src/main/java/com/vaadin/flow/component/html/Image.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ImageClickView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ImageClickIT.java

Fixes #4915
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4963)

Add ClickListener support to Image (#4915)

---

flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ExclusionRegistry.java
flow-components-parent/flow-generated-components/json_metadata/vaadin-select-overlay.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-select-text-field.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-select.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/select/GeneratedVaadinSelect.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/select/GeneratedVaadinSelectOverlay.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json

Version is compatible with V12.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4900)

Generate Component for vaadin-select

---

flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/BehaviorRegistry.java
flow-components-parent/flow-generated-components/json_metadata/vaadin-email-field.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-number-field.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-password-field.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-text-area.json
flow-components-parent/flow-generated-components/json_metadata/vaadin-text-field.json
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinEmailField.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinNumberField.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextArea.java
flow-components-parent/flow-generated-components/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextField.java
flow-components-parent/flow-webcomponent-api-analyzer/bower.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4983)

Update generated text field to 2.3.0-alpha7

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/theme/ThemeUtil.java
flow-tests/pom.xml
flow-tests/test-lumo-theme/pom.xml
flow-tests/test-lumo-theme/src/main/java/com/vaadin/flow/uitest/ui/lumo/ExplicitLumoTemplateView.java
flow-tests/test-lumo-theme/src/main/java/com/vaadin/flow/uitest/ui/lumo/ImplicitLumoTemplateView.java
flow-tests/test-lumo-theme/src/main/webapp/frontend/bower_components/themed-template/src/ImplicitLumoThemedTemplate.html
flow-tests/test-lumo-theme/src/main/webapp/frontend/bower_components/themed-template/src/LumoThemedTemplate.html
flow-tests/test-lumo-theme/src/main/webapp/frontend/bower_components/themed-template/theme/lumo/ImplicitLumoThemedTemplate.html
flow-tests/test-lumo-theme/src/main/webapp/frontend/bower_components/themed-template/theme/lumo/LumoThemedTemplate.html
flow-tests/test-lumo-theme/src/test/java/com/vaadin/flow/uitest/ui/lumo/AbstractThemedTemplateIT.java
flow-tests/test-lumo-theme/src/test/java/com/vaadin/flow/uitest/ui/lumo/ExplicitLumoTemplateIT.java
flow-tests/test-lumo-theme/src/test/java/com/vaadin/flow/uitest/ui/lumo/ImplicitLumoTemplateIT.java
flow-tests/test-material-theme/pom.xml
flow-tests/test-material-theme/src/main/java/com/vaadin/flow/uitest/ui/material/MaterialThemedTemplateView.java
flow-tests/test-material-theme/src/main/java/com/vaadin/flow/uitest/ui/material/NotThemedTemplateView.java
flow-tests/test-material-theme/src/main/webapp/frontend/bower_components/themed-template/src/MaterialThemedTemplate.html
flow-tests/test-material-theme/src/main/webapp/frontend/bower_components/themed-template/src/NotThemedTemplate.html
flow-tests/test-material-theme/src/main/webapp/frontend/bower_components/themed-template/theme/material/MaterialThemedTemplate.html
flow-tests/test-material-theme/src/test/java/com/vaadin/flow/uitest/ui/material/MaterialThemedTemplateIT.java
flow-tests/test-material-theme/src/test/java/com/vaadin/flow/uitest/ui/material/NotThemedTemplateIT.java
flow-theme-integrations/lumo/pom.xml
flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/LumoThemeDefinition.java

Fixes #4847
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4972)

Check Lumo theme in OSGi via services mechanism

---

flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4991)

Fix serializationTest when instantiating outside of VaadinSession.

---

flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiAccess.java
flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
flow-server/src/main/java/com/vaadin/flow/server/startup/ServletContextListeners.java
flow-server/src/test/java/com/vaadin/flow/router/SessionRouteRegistryTest.java
flow-server/src/test/java/com/vaadin/flow/router/internal/AbstractRouteRegistryTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/ApplicationRouteRegistryTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/OSGiInitApplicationRouteRegistryTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryTestBase.java
flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4939)

Dynamically register and unregister routes in OSGi

---

flow-tests/test-root-context/pom.xml

Testing to see if test fails
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4990)

Update usage statistics version

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5003)

Update browser version

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
flow-tests/test-web-components/pom.xml

Merged out of sync with master version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5012)

Fix version to be 1.4-SNAPSHOT instead of 1.3-SNAPSHOT

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5013)

Update chrome version

---

flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5016)

Fix custom root element for IE11 and Edge in production mode.

---

flow-server/src/main/java/com/vaadin/flow/router/RouteConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
flow-server/src/test/java/com/vaadin/flow/server/MockServletContext.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DynamicallyRegisteredRoute.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DynamicallyRegisteredRouteIT.java

Fix RouteRegistry access during ServiceInitListener (#5018)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5022)

Cherry-pick #5018

---

flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java
flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrap.java
flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java
flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
flow-server/src/main/resources/com/vaadin/flow/server/webcomponent/webcomponent-template.html
flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentProviderTest.java
flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentGeneratorTest.java
flow-tests/test-web-components/src/main/java/com/vaadin/flow/webcomponent/ClientSelect.java
flow-tests/test-web-components/src/main/java/com/vaadin/flow/webcomponent/PlainServlet.java
flow-tests/test-web-components/src/main/java/com/vaadin/flow/webcomponent/WebComponentVaadinServlet.java
flow-tests/test-web-components/src/main/webapp/frontend/Dependency.html
flow-tests/test-web-components/src/test/java/com/vaadin/flow/webcomponent/EmbeddedWebComponentIT.java

Fixes #5027, #5044
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5031)

Send service URL to the client side for Web Components UI

---

flow-data/pom.xml
flow-data/src/main/java/com/vaadin/flow/data/renderer/BasicRenderer.java
flow-data/src/main/java/com/vaadin/flow/data/renderer/NativeButtonRenderer.java
flow-data/src/test/java/com/vaadin/flow/data/binder/BinderConverterValidatorTest.java
flow-data/src/test/java/com/vaadin/flow/data/binder/BinderValidationStatusTest.java
flow-data/src/test/java/com/vaadin/flow/data/binder/ReadOnlyHasValueTest.java
flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/TestLabel.java
flow-data/src/test/java/com/vaadin/flow/data/renderer/ComponentRendererTest.java
flow-data/src/test/java/com/vaadin/flow/data/selection/MultiSelectTest.java
flow-data/src/test/java/com/vaadin/flow/data/validator/ValidatorTestBase.java

Fixes #5015
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5050)

Remove dependency from data to html-components

---

flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4981)

Clarify StreamResource JavaDoc

---

flow-data/src/main/resources/META-INF/resources/frontend/.gitignore
flow-data/src/main/resources/META-INF/resources/frontend/CONVERT-P3.txt
flow-data/src/main/resources/META-INF/resources/frontend/bower.json
flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js
flow-data/src/main/resources/META-INF/resources/frontend/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5038)

Adding flow-component-renderer for P3. Fixes #5036

---

flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
flow-server/src/test/java/com/vaadin/flow/server/AbstractDeploymentConfigurationTest.java
flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java

Fixes #5042
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5062)

Add bowerMode property

---

flow-server/src/main/java/com/vaadin/flow/router/Route.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5063)

Make the java doc return say the correct thing.

---

flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html
flow-server/src/main/java/com/vaadin/flow/router/Route.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5066)

Cherry-pick fixes for 1.4

---

flow-server/src/main/java/com/vaadin/flow/component/ClickNotifier.java
flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShortcutsView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShortcutsIT.java
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5065)

Shortcuts: change click shortcut's default behavior (#5058)

---

flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html
flow-server/src/main/java/com/vaadin/flow/component/Component.java
flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java
flow-tests/test-root-context/pom.xml
flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5067)

Cherry picks to 1.2

---

flow-client/src/main/java/com/vaadin/client/DependencyLoader.java
flow-client/src/main/java/com/vaadin/client/ResourceLoader.java
flow-client/src/test-gwt/java/com/vaadin/client/GwtDependencyLoaderTest.java
flow-client/src/test/java/com/vaadin/client/DependencyLoaderTest.java
flow-server/src/main/java/com/vaadin/flow/component/dependency/JsModule.java
flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentMetaData.java
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
flow-server/src/main/java/com/vaadin/flow/internal/AnnotationReader.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java
flow-server/src/main/java/com/vaadin/flow/shared/util/SharedUtil.java
flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
flow-tests/pom.xml

Fixes #5045
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5057)

Add JsModule annotation

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeServer.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java

Fixes #5046
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5069)

Add a frontend server proxying to webpack

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinServletConfiguration.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5052)

Deprecate @VaadinServletConfiguration

---

drivers.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5020)

Update chrome driver version

---

flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html
flow-server/src/main/java/com/vaadin/flow/component/Component.java
flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java

Picks:
- Fix javadocs for getId() and setId() (#4960)
- Clarify StreamResource JavaDoc (#4981)
- Fix flow-component-renderer for Chrome 72 (#5060)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5084)

1.0.9 cherry picks

---

drivers.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5083)

Fix version id in drivers

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
flow-server/src/main/java/com/vaadin/flow/theme/AbstractTheme.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java
flow-theme-integrations/material/src/main/java/com/vaadin/flow/theme/material/Material.java

Fixes #4765
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5019)

Deprecate getBodyAttributes and replace it with getHtmlAttributes

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5087)

Add m2e lifecycle mapping for maven-antrun-plugin

---

flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/AbstractErrorHandlerView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ErrorHandlingView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExceptionDuringMapSyncView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/ExceptionsDuringPropertyUpdatesView.java
flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/ExceptionsDuringPropertyUpdates.html
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AbstractErrorIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ErrorHandlingIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionDuringMapSyncIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ExceptionsDuringPropertyUpdatesIT.java

Fixes #4979
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5077)

Catch Throwable during maps sync handling

---

flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentMetaData.java
flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
flow-server/src/test/java/com/vaadin/flow/component/HtmlImportJsModuleTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
flow-server/src/test/java/com/vaadin/tests/util/MockUI.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5085)

Replace HtmlImport with JsModule.

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java

Fixes #5046
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5091)

do not run webpack twice

---

flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShortcutsView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShortcutsIT.java

Fixes #5100 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5099)

Shortcuts no longer work, when element is disabled

---

drivers.xml
flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/TreeDataProvider.java
flow-server/pom.xml
flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServletConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
flow-server/src/main/java/com/vaadin/flow/theme/AbstractTheme.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/AbstractErrorHandlerView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ErrorHandlingView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExceptionDuringMapSyncView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShortcutsView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/ExceptionsDuringPropertyUpdatesView.java
flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/ExceptionsDuringPropertyUpdates.html
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AbstractErrorIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ErrorHandlingIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionDuringMapSyncIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShortcutsIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ExceptionsDuringPropertyUpdatesIT.java
flow-tests/test-web-components/src/main/java/com/vaadin/flow/webcomponent/PushWebComponentServlet.java
flow-tests/test-web-components/src/main/java/com/vaadin/flow/webcomponent/UpdateServerSideWebComponent.java
flow-tests/test-web-components/src/main/webapp/push.html
flow-tests/test-web-components/src/test/java/com/vaadin/flow/webcomponent/UpdateServerSideWebComponentIT.java
flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java
flow-theme-integrations/material/src/main/java/com/vaadin/flow/theme/material/Material.java
pom.xml

Keep 2.0 branch up to date with master branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5115)

Cherrypicks from master

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5127)

make devmode handler wait until webpack available. Fixes #5096

---

flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5132)

Fix invalid null check
