flow-server/src/main/java/com/vaadin/flow/component/HasComponents.java

Document the fact that a component with a parent will be added to a new parent and removed from the previous one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5137)

Javadoc - Add a component already added to a parent.

---

flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java

Cherry pick from master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5138)

Fix invalid null check (#5132)

---

flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html
flow-server/src/main/java/com/vaadin/flow/component/HasComponents.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShortcutsIT.java
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5147)

Bring in changes from master to 2.0

---

flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5171)

Avoid for..of loop in renderer

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java

- Compute the correct project dir when running in maven multi modules
- Use a free port for webpack server instead of reusing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5167)

Some fixes in DevModeHandler to prevent issues in tests

---

flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html
flow-server/src/main/java/com/vaadin/flow/component/HasComponents.java
flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShortcutsIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5175)

Cherry picks from master

---

flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5181)

Avoid for..of loop in renderer (#5171)

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageJsonMojo.java
flow-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
flow-server/src/main/java/com/vaadin/flow/component/dependency/NpmPackage.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5159)

NpmPackage annotation

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/UpdateNpmDependenciesMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/UpdateNpmDependenciesMojoTest.java
flow-server/src/test/java/com/vaadin/flow/component/NpmPackageTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5178)

NpmPackage maven goal annotation test

---

flow-tests/pom.xml
flow-tests/test-npm/.gitignore
flow-tests/test-npm/package.json
flow-tests/test-npm/pom.xml
flow-tests/test-npm/src/main/java/com/vaadin/flow/npmtest/ui/IdTestView.java
flow-tests/test-npm/src/main/webapp/frontend/main.js
flow-tests/test-npm/src/main/webapp/frontend/my-component.html
flow-tests/test-npm/src/main/webapp/frontend/my-component.js
flow-tests/test-npm/src/test/java/com/vaadin/flow/npmtest/ui/IdTestIT.java
flow-tests/test-npm/webpack.config.js

Fixes #5075
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5117)

Add tests for `@Id` in npm mode

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/AnnotationValuesExtractor.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/Fragment.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/UpdateImportsMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/UpdateNpmDependenciesMojo.java
flow-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/TestComponents.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/UpdateImportsMojoTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/UpdateNpmDependenciesMojoTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5182)

Add maven goal for updating imports. Fixes #5120

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/UpdateImportsMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/UpdateNpmDependenciesMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/UpdateImportsMojoTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/UpdateNpmDependenciesMojoTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5189)

Do not update dependencies or imports if already done

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java

Fixes #5187
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5190)

Start the dev server through node.

---

flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DomListenerOnAttachView.java
flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/DomListenerOnAttach.html
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DomListenerOnAttachIT.java

Fixes #5152
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5200)

Add DOM listeners before attaching the element (#5195)

---

flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/AbstractErrorHandlerView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ErrorHandlingView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExceptionDuringMapSyncView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/ExceptionsDuringPropertyUpdatesView.java
flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/ExceptionsDuringPropertyUpdates.html
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AbstractErrorIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ErrorHandlingIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionDuringMapSyncIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ExceptionsDuringPropertyUpdatesIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5196)

Catch Throwable during maps sync handling (#5077)

---

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/UnsupportedBrowserHandler.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/UnsupportedBrowserHandlerTest.java
flow-tests/test-npm/webpack.config.js

Connected to https://github.com/vaadin/beverage-starter-flow/issues/286
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5202)

Add webcomponent polyfill to bootstrap host page

---

flow-tests/test-npm/src/test/java/com/vaadin/flow/npmtest/ui/IdTestIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5209)

Try to wait for polymer init

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/UpdateImportsMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/UpdateImportsMojoTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5212)

Append imports to js file instead of replacing whole file.

---

flow-client/src/main/java/com/vaadin/client/communication/ServerConnector.java
flow-client/src/main/java/com/vaadin/client/flow/util/ClientJsonCodec.java
flow-client/src/test-gwt/java/com/vaadin/client/GwtExecuteJavaScriptElementUtilsTest.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicTextElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/ShadowRootStateProvider.java
flow-server/src/main/java/com/vaadin/flow/internal/JsonCodec.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeFeatureRegistry.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeFeatures.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ReturnChannelMap.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ReturnChannelRegistration.java
flow-server/src/main/java/com/vaadin/flow/server/communication/ReturnChannelHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
flow-server/src/main/java/com/vaadin/flow/shared/JsonConstants.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeFeatureTest.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ReturnChannelMapTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/ReturnChannelHandlerTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ReturnChannelView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ReturnChannelIT.java

This is an enabler for #1724 and #4925.
Fixes #4927
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5093)

Add a generic mechanism for passing values back to the server

---

flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/AmbiguousRouteConfigurationException.java
flow-server/src/main/java/com/vaadin/flow/server/InvalidRouteConfigurationException.java
flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
flow-server/src/main/java/com/vaadin/flow/server/startup/RouteTarget.java
flow-server/src/test/java/com/vaadin/flow/router/RouteConfigurationTest.java
flow-server/src/test/java/com/vaadin/flow/router/SessionRouteRegistryTest.java
flow-server/src/test/java/com/vaadin/flow/router/internal/AbstractRouteRegistryTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/ApplicationRouteRegistryTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java

Fixes #5114
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5218)

Register superclass in case of route target collision

---

flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java
flow-data/src/main/java/com/vaadin/flow/data/value/ValueChangeMode.java
flow-data/src/test/java/com/vaadin/flow/data/value/ValueChangeModeTest.java
flow-html-components/pom.xml
flow-html-components/src/main/java/com/vaadin/flow/component/html/Input.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/ComponentTest.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/InputTest.java
flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java
flow-server/src/main/java/com/vaadin/flow/dom/DomListenerRegistration.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementListenerMap.java
flow-server/src/test/java/com/vaadin/flow/component/AbstractSinglePropertyFieldTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/AbstractDebounceSynchronizeView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DebounceSynchronizePropertyView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RerouteView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ValueChangeModeView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AbstractDebounceSynchronizeIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DebounceSynchronizePropertyIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ValueChangeModeIT.java
flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/RPCLoggerIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/4945)

Introduce ValueChangeMode#LAZY, and #TIMEOUT

---

flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html

Fixes #5206
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5208)

Check the function presence before calling it

---

flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/AmbiguousRouteConfigurationException.java
flow-server/src/main/java/com/vaadin/flow/server/InvalidRouteConfigurationException.java
flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
flow-server/src/main/java/com/vaadin/flow/server/startup/RouteTarget.java
flow-server/src/test/java/com/vaadin/flow/router/RouteConfigurationTest.java
flow-server/src/test/java/com/vaadin/flow/router/SessionRouteRegistryTest.java
flow-server/src/test/java/com/vaadin/flow/router/internal/AbstractRouteRegistryTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/ApplicationRouteRegistryTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java

Fixes #5114
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5232)

Register superclass in case of route target collision (#5218)

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/ClassPathIntrospector.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/UpdateImportsMojo.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5251)

Fix the theme instantation context

---

flow-server/src/main/java/com/vaadin/flow/dom/DomEvent.java

Fixes #5211
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5215)

Correct javadocs for DomEvent

---

pom.xml

Fixes #4127
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5253)

Update jsoup version

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/UpdateNpmDependenciesMojo.java
flow-maven-plugin/src/main/resources/webpack.config.js
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/UpdateNpmDependenciesMojoTest.java
flow-tests/test-npm/src/main/webapp/frontend/main.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5262)

Create webpack.config.js. Fixes #5203

---

flow-server/src/main/java/com/vaadin/flow/dom/DomEvent.java

Fixes #5211
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5266)

Correct javadocs for DomEvent (#5215)

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/UpdateNpmDependenciesMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/UpdateNpmDependenciesMojoTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5269)

Fix --save-dev

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/AnnotationValuesExtractor.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5271)

fix javadoc

---

flow-client/pom.xml
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/UpdateNpmDependenciesMojo.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5276)

Fix CI builds because process might not be finished

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5287)

Add source maps when in dev-mode. Fixes #290

---

flow-data/src/test/java/com/vaadin/flow/data/binder/BeanBinderTest.java

Set locale explicitly in the tests.
Fixes #3500
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5283)

Avoid indeterministic behavior in tests.

---

flow-tests/pom.xml
flow-tests/test-npm/src/test/java/com/vaadin/flow/npmtest/ui/IdTestIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5289)

Ignore failing test

---

flow-server/src/main/java/com/vaadin/flow/component/Html.java
flow-server/src/test/java/com/vaadin/flow/component/HTMLTest.java

Fixes #5220
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5255)

Handle empty attribute values properly in HTML element

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5295)

Update chrome version in tests

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/UpdateNpmDependenciesMojo.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5298)

Fix npm execution on windows.

---

flow-server/src/main/java/com/vaadin/flow/component/Html.java
flow-server/src/test/java/com/vaadin/flow/component/HTMLTest.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

Fixes #5220
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5299)

Handle empty attribute values properly in HTML element (#5255)

---

flow-tests/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5301)

Enable IT test again.

---

flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PageView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PageIT.java

Fixes #4869 
Implement new method to Page.class:
```
open(String url, String windowName)
open(String url, String windowName, int width, int height)
setLocation(String uri)
setLocation(URI uri)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5166)

Implement open and setLocation method to Page. (#4869)

---

flow-server/src/main/java/com/vaadin/flow/router/Location.java
flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java

Fixed #5113
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5291)

Fix navigate back to main view don't work in FF and Safari . (#5113)

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/AbstractNpmMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageForProductionMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/UpdateImportsMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/UpdateNpmDependenciesMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/UpdateImportsMojoTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/UpdateNpmDependenciesMojoTest.java
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java

Additionally, create a mock Flow npm module with the frontend resources from the jar dependencies.
Prefer those resources when generating webpack imports.
Closes #5204
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5319)

Add JavaScript modules to WebPack

---

flow-server/src/main/java/com/vaadin/flow/component/page/Page.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5344)

Correctly restore binary compatibility

---

flow-server/src/main/java/com/vaadin/flow/component/ClickNotifier.java
flow-server/src/main/java/com/vaadin/flow/component/Focusable.java
flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
flow-server/src/main/java/com/vaadin/flow/component/Shortcuts.java
flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializer.java
flow-server/src/main/java/com/vaadin/flow/server/webcomponent/PropertyBinding.java
flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentBindingImpl.java
flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentConfigurationImpl.java
flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentImpl.java
flow-server/src/test/java/com/vaadin/flow/server/webcomponent/PropertyBindingTest.java
flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentImplTest.java

Fixes #5351 
This cannot be cherry-picked to Flow 1.4, as our contract slightly changes in places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5358)

Use IllegalArgumentException in place of InvalidParameterException (no cherry-pick)

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeUpdateAbstractMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeUpdateImportsMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeUpdatePackagesMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/UpdateImportsMojoTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/UpdateNpmDependenciesMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdatePackages.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

Closes #5231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5359)

Validate js imports in the project file structure

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
flow-server/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer

This is the first step, we need DevMode in a servlet contatiner initializer so as we have the list of annotated classes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5366)

Move DevMode initialisation to a ServletContainerInitializer

---

flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/UpdateImportsMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdateImports.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5367)

install flow-frontend modules before make import validations

---

flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5374)

Make exported web components work on hosts where https is proxied to http

---

flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/JavaScriptReturnValueView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/JavaScriptReturnValueIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5373)

Use message as the JS return value when catching an error

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeUpdateAbstractMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeUpdateImportsMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeUpdatePackagesMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageForProductionMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/common/AnnotationValuesExtractorTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/common/ThemedURLTranslatorTest.java
flow-server/pom.xml
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/AnnotationValuesExtractor.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/ClassPathIntrospector.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdatePackages.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5375)

Remove org.reflections dependency 

---

flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
flow-server/src/main/java/com/vaadin/flow/shared/JsonConstants.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5387)

Remove unused constants

---

flow-server/src/main/java/com/vaadin/flow/di/DefaultInstantiator.java
flow-server/src/main/java/com/vaadin/flow/di/Instantiator.java
flow-server/src/test/java/com/vaadin/flow/di/DefaultInstantiatorTest.java
flow-server/src/test/java/com/vaadin/flow/server/MockInstantiator.java

Fixes #4634
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5379)

Use "create" semantic for the createComponent method

---

flow-server/src/main/java/com/vaadin/flow/di/DefaultInstantiator.java
flow-server/src/main/java/com/vaadin/flow/di/Instantiator.java
flow-server/src/test/java/com/vaadin/flow/di/DefaultInstantiatorTest.java
flow-server/src/test/java/com/vaadin/flow/server/MockInstantiator.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5392)

Cherry pick for #4634 

---

flow-server/src/main/java/com/vaadin/flow/di/DefaultInstantiator.java
flow-server/src/main/java/com/vaadin/flow/di/Instantiator.java
flow-server/src/test/java/com/vaadin/flow/di/DefaultInstantiatorTest.java
flow-server/src/test/java/com/vaadin/flow/server/MockInstantiator.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5393)

Cherry pick for #4634

---

flow-tests/test-npm/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5399)

Clean node_modules for npm tests

---

flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java
flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java
flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
flow-server/src/main/resources/com/vaadin/flow/server/webcomponent/webcomponent-template.html
flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentGeneratorTest.java

Fixes #5382
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5391)

Avoid "web context" in web component module generation

---

flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentConfigurationFactory.java
flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentConfigurationRegistry.java

Fixes #5402
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5403)

Extract web component config factory

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeUpdateImportsMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/UpdateImportsMojoTest.java
flow-tests/test-npm/pom.xml

Closes #5236 
Production mode IT tests re already present:
* for bower, in `test-frontend-production-custom-context` module
* for npm, in `test-npm` module
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5409)

Run webpack programmatically from the plugin

---

flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5417)

Fix compilation after merging

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdatePackages.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5415)

Simplify process launch code

---

flow-server/src/main/resources/com/vaadin/flow/server/webcomponent/webcomponent-template.html

Part of #5420
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5421)

Correct generated template to work properly in production mode

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java

Also updates an inconsistency in null checking between UI and session
when setting a locale.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5412)

Clarify Javadocs for UI and session locale settings

---

flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
flow-server/src/main/java/com/vaadin/flow/dom/Element.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5436)

Mention JsonValue as a supported parameter for executeJs

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/RunnerManager.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeUpdateImportsMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/common/RunnerManagerTest.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsLocator.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdatePackages.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsLocatorTest.java

Closes #5432
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5450)

Add node and npm detection

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CopyFrontendFilesMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CopyProductionFilesMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeUpdateAbstractMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageForProductionMojo.java
flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdatePackages.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/I18NProviderTest.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinServletConfigurationTest.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5448)

Detect when running in a legacy bower project

---

flow-server/pom.xml

Closes #5426
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5460)

Use closure compiler with no extra dependencies bundled in it

---

flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java

Set full Locale, and restore default locale after each test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5459)

Use UI locale in BinderTest

---

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsLocator.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java

Closes #5398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5468)

Start in the development mode in a servlet container without errors

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeValidateMojo.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdatePackages.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5472)

validate goal for the flow-maven plugin

---

flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponent.java
flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentTest.java

fixes #5475
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5476)

Fixed: WebComponent is unable to write boolean properties

---

flow-data/src/main/java/com/vaadin/flow/data/binder/ValueContext.java
flow-data/src/test/java/com/vaadin/flow/data/binder/ValueContextTest.java
flow-data/src/test/java/com/vaadin/flow/data/provider/BackendDataProviderTest.java

Fixes #5469
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5481)

Retrieve locale from the UI of component if possible

---

flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java

Fixes #4901
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5484)

Avoid NPE in validation methods

---

flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
flow-tests/test-web-components/src/main/java/com/vaadin/flow/webcomponent/PushWebComponentServlet.java

Fixes #5061
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5478)

Derive relative pushUrl from the service URL

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java

Executables on windows is .exe or .cmd versions.
Fixes #5488
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5497)

Fix executables for windows environment

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeUpdateAbstractMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeUpdateImportsMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeUpdatePackagesMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/UpdateImportsMojoTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/UpdateNpmDependenciesMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdatePackages.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/resources/webpack.config.js
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
flow-tests/test-npm/.gitignore

Closes #5423
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5502)

Move main.js generation into target directory

---

flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-tests/pom.xml
flow-tests/test-web-components-production/pom.xml
flow-tests/test-web-components-theme-variant/pom.xml
flow-tests/test-web-components-theme-variant/src/main/java/com/vaadin/flow/webcomponent/ThemedVariantComponent.java
flow-tests/test-web-components-theme-variant/src/main/java/com/vaadin/flow/webcomponent/ThemedVariantComponentExporter.java
flow-tests/test-web-components-theme-variant/src/main/webapp/index.html
flow-tests/test-web-components-theme-variant/src/test/java/com/vaadin/flow/webcomponent/ThemedVariantComponentIT.java

Fixes #5372
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5482)

Add theme variant attributes to the embedded element

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouteNotFoundIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5519)

Test for xss attack in RouteNotFound

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouteNotFoundIT.java

Test for #5498
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5520)

Cherry-pick: Test for xss attack (#5519)

---

flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeUpdateFrontendMojoTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/TestComponents.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5532)

Properly handle `frontend://` in `@JsModule`

---

flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
flow-server/src/main/java/com/vaadin/flow/dom/Element.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5526)

Cherry-pick: Mention JsonValue as a supported parameter for executeJs (#5436)

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojoTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/TestComponents.java
flow-server/src/main/java/com/vaadin/flow/component/dependency/NpmPackage.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/ClassFinder.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendAnnotatedClassVisitor.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendClassVisitor.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendDependencies.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeNpmInstall.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdatePackages.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/component/NpmPackageTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTestComponents.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeExecutorTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
flow-tests/test-npm/src/main/java/com/vaadin/flow/npmtest/ui/IdTestView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5506)

Consider versions in NpmPackage and save them to package.json

---

flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5523)

Cherry-pick: Use UI locale in BinderTest (#5459)

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5540)

Add log level for dev server output.

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FlowPluginFrontendUtils.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CopyProductionFilesMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeValidateMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageForProductionMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/common/AnnotationValuesExtractorTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/common/ThemedURLTranslatorTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/common/WebComponentModulesGeneratorTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5543)

Remove abstract frontend goal class.

---

flow-server/pom.xml

Related to https://github.com/vaadin/flow/issues/5554
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5555)

Exclude all transitive dependencies from the closure-compiler

---

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendDependencies.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5556)

Clarify message when webpack is not running and production mode not set

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeNpmInstall.java

Fixes local node install problem from #5397
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5562)

Set local node path variable for windows execution.

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java

Fixes cdi#288
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5546)

Instantiator methods should be run with VaadinService available

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojo.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5563)

Improve javadoc

---

flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
flow-server/src/main/java/com/vaadin/flow/dom/Element.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5561)

Explicitly mention that execJs by default ignores the return value

---

flow-server/src/main/java/com/vaadin/flow/component/dependency/NpmPackage.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5559)

clarify jdoc about package version

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeValidateMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-tests/test-npm/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5558)

Move the copy resources task to the validate goal

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5542)

Add log level for dev server output. (#5540)

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5574)

Increase chrome version to fix TC builds

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5571)

when webpack fails, show the error in browser

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojo.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/WebpackUpdater.java
flow-server/src/main/resources/webpack.config.js
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesTest.java

Closes #5579
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5581)

Get rid of absolute paths in the webpack.config.js

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeValidateMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojoTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeValidateMojoTest.java

Closes #5577
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5584)

Copy project frontend resourses

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeNpmInstall.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdatePackages.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5585)

Run npm even when no package.json files is updated

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendAnnotatedClassVisitor.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendClassVisitor.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5593)

downgrade ASM api level, to avoid collision with testbench

---

flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5592)

update renderer for P3 with last changes

---

flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java

ServletContext resources need to start with a /
else nothing will be found.
Also lock into the default value for frontend-es6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5595)

Fix the isBowerLegacyProdMode resource path.

---

drivers.xml
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5599)

Cherry picks/from master

---

flow-server/src/main/java/com/vaadin/flow/router/AfterNavigationObserver.java
flow-server/src/main/java/com/vaadin/flow/router/BeforeEnterObserver.java
flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveObserver.java

Reworded to not imply that the component is only notified at the point
in time when it gets attached.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5614)

Clarify navigation observer javadocs

---

flow-tests/test-npm/src/main/java/com/vaadin/flow/npmtest/NpmEnabledVaadinServlet.java
flow-tests/test-npm/src/main/java/com/vaadin/flow/npmtest/ui/IdTestView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5547)

Extract servlet to be able to add more tests

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java

Fixes #5620
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5625)

Always load bundle files from the context root

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinServletServiceTest.java

Fixes #5634
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5637)

Make getAttribute return the attribute value

---

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdCollector.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateParser.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5548)

Extract Id collection to a separate class

---

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdMapper.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateInitializer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5550)

Extract @Id mapping to a separate class

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendClassVisitor.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTestComponents.java

Fixes #5619
It covers cases like:
add(Icon(VaadinIcon.CALENDAR));
Notification.show("Hello");
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5649)

Scanner visitor should visit classes whose methods are used in the UI

---

flow-server/pom.xml
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
flow-server/src/test/resources/build/stats.json

Use pattern matching to parse the template instead
of relying on the closure compiler dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5644)

Drop closure and parse the template by pattern

---

flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java
flow-theme-integrations/material/src/main/java/com/vaadin/flow/theme/material/Material.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5652)

Add JsModule annotations to themes

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FlowPluginFrontendUtils.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CopyProductionFilesMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeValidateMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageForProductionMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojoTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeValidateMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5650)

Move creation of npm config files to the `validate` goal

---

flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java
flow-theme-integrations/material/src/main/java/com/vaadin/flow/theme/material/Material.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5660)

Fix dependency in lumo

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
flow-server/src/main/resources/webpack.config.js
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java

Fixes #5654
Fixes #5580 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5656)

Update webpack with latest maven configuration changes

---

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/AbstractTemplate.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5549)

Move model handling to AbstractTemplate

---

flow-server/src/main/java/com/vaadin/flow/component/WebComponentExporter.java
flow-server/src/main/java/com/vaadin/flow/router/Location.java
flow-server/src/main/java/com/vaadin/flow/router/Router.java
flow-server/src/test/java/com/vaadin/flow/component/WebComponentExporterTest.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java

Fixes #5514
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5663)

Throw an exception if addProperty is called inside configureInstance

---

flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentMetaData.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendDependencies.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
flow-tests/test-npm/src/main/java/com/vaadin/flow/npmtest/ui/MissingDependenciesView.java

Fixes #5624
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5639)

Log a warning for unvisited dependency annotations

---

flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SetParameterForwardToView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SetParameterForwardToIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5667)

Add parameters to Location object after forwarding using forwardTo (#5174)

---

flow-dnd/bnd.bnd
flow-dnd/pom.xml
flow-dnd/src/main/java/com/vaadin/flow/component/dnd/osgi/DndConnectorResource.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5690)

Fix OSGi tests: first configure properly DND module

---

flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesTest.java

Fixes #5535
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5678)

Don't detect component versions based on vaadin-core-shrinkwrap

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojo.java

Update javaDoc for phase clarity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5694)

Revert change of lifecyclePhase

---

flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojoTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeValidateMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendDependencies.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTestComponents.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java

- Support any syntax in NpmPackage version field.
- Split package.json in main one and app one
- User can pin versions by editing main package.json or with annotation
- Remove packages dependency when not used anymore
- Allow multiple version, but warn about it
- Add name and version fields to generate files to avoid warnings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5681)

Improve version resolution

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5697)

Collect information about Bower and npm usage

---

flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java

Fixes #5714
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5718)

Use full URL for loading scripts

---

flow-tests/test-root-context/pom.xml
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5724)

Update testbench-core version

---

flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5719)

Fix java 11 build

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5720)

Use a command which works regardless of installed versions

---

flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java

Fixes #5642
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5730)

Do not clear theme if set again

---

flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java

Fixes https://github.com/vaadin/flow/issues/5700
Needs https://github.com/vaadin/platform/pull/662
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5723)

Remove hardcoded shrinkwrap dependency in favor of vaadin.jar annotation

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java

Fixes #5737
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5738)

Fix exception always logged for every resource request

---

flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5746)

Remove obsolete checks after using the flow-build-info.json

---

flow-components-parent/flow-code-generator-api/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5753)

Update dependency to solve the  security vulnerability

---

flow-server/src/main/resources/webpack.config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5767)

Update outdated maven plugin goal

---

flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentMetaData.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinContext.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServletContext.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
flow-server/src/test/java/com/vaadin/flow/component/HtmlImportJsModuleTest.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinServletContextTest.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinServletServiceTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5756)

5751: VaadinContext and VaadinServletContext ready

---

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/resources/webpack.config.js
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/resources/build/stats.json

Fixes #5456 
Fixes #5631
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5776)

Add a hash and a cache fragment to the build file name to avoid cache issues

---

flow-server/src/main/java/com/vaadin/flow/component/dependency/NpmPackage.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendAnnotatedClassVisitor.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendDependencies.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTestComponents.java

There are cases where the classlist doesn't contain
super classes and those might be the one containing
the annotation and should also be visited.
Make NpmPackage Inherited.
Fixes #5780
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5786)

Visit also super classes

---

flow-tests/servlet-containers/pom.xml

This should fix the Tomcat and Felix ITs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5796)

Add html-components-testbench artifact for containers.

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendClassVisitor.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendDependencies.java
flow-server/src/main/java/com/vaadin/flow/theme/NoTheme.java
flow-server/src/main/java/com/vaadin/flow/theme/Theme.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTestComponents.java

Fixes: #5762
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5788)

Change Theme algorithm in order not to break V13.

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java

Fixes #5615 
Fixes #5797
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5804)

Do not show warning when frontend:// in JavaScript annotations

---

flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5811)

Use correct logger class

---

flow-tests/pom.xml

Fixes #5809
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5814)

Enable dev mode tests

---

flow-server/src/main/java/com/vaadin/flow/theme/NoTheme.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5819)

Fix JavaDoc error in NoTheme interface

---

flow-server/src/main/resources/webpack.config.js

Fixes #5760
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5821)

Use non-deprecated API

---

flow-server/src/main/java/com/vaadin/flow/server/Constants.java
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5818)

Use Atmosphere with SLF4J instead of java.util.logging

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java

Fixes #5809
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5827)

Stop dev mode if all servlet contexts are destroyed.

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5782)

Update to TB stable

---

flow-tests/test-no-theme/pom.xml
flow-tests/test-no-theme/src/main/java/com/vaadin/flow/uitest/ui/notheme/NoThemeComponentView.java
flow-tests/test-no-theme/src/main/java/com/vaadin/flow/uitest/ui/servlets/WorkaroundServlet.java
flow-tests/test-no-theme/src/test/java/com/vaadin/flow/uitest/ui/notheme/NoThemeComponentIT.java

Fixes #5777
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5810)

Add test for @NoTheme

---

flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/main/java/com/vaadin/flow/server/startup/ServletContextListeners.java
flow-server/src/main/java/com/vaadin/flow/server/startup/StopDevMode.java

Fixes #5834 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5837)

Make servlet context listener be called from @WebListener

---

flow-tests/test-root-context/frontend/MixinInjectsElement.js
flow-tests/test-root-context/frontend/com/vaadin/flow/uitest/ui/dependencies/lazy.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5828)

Correct the JS module code

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendAnnotatedClassVisitor.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendClassVisitor.java

Fixes #5785
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5840)

Update used ASM api version to support Java 11

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

Fixes #5841
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5842)

Add version field to generated package.json to support older npm versions

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5850)

Update testbench to version with latest byte buddy

---

flow-data/src/main/java/com/vaadin/flow/data/binder/ReadOnlyHasValue.java

Binder#bind() needs to have a setter as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5846)

Fix wrong code example in the Java Doc

---

flow-server/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5847)

Use latest Byte Buddy

---

drivers.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5851)

Update chromedriver version to 75.0.3770.8

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShortcutsIT.java

Fix the javadoc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5853)

Remove non thrown exception.

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShortcutsIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5863)

Fixed ShortcutsIT

---

flow-server/src/main/resources/com/vaadin/flow/server/BootstrapHandler.js

This allows loading the bundle with components adding to window.Vaadin.Flow.* before
loading the bootstrap, which adds to other parts of window.Vaadin.Flow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5868)

Use window.vaadin.Flow.clients to check for executed bootstrap

---

flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java
flow-server/src/test/java/com/vaadin/flow/component/internal/ServiceDependencyParserTest.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinServletServiceTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java

Fixes #5871
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5872)

Fix resource resolution in npm.

---

flow-tests/test-root-context/pom-npm.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5877)

Exclude missed ValueChangeModeIT test (in NPM mode).

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinContext.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServletContext.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/DevModePort.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/WebpackDevServerPort.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5852)

Get rid of webpack port system property.

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5873)

Check node and npm versions before using them

---

flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5893)

Fail build for known broken npm/node versions, warn for unsupported versions

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendDependencies.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTestComponents.java
flow-tests/pom.xml
flow-tests/test-npm-only-features/pom.xml
flow-tests/test-npm-only-features/test-default-theme/pom.xml
flow-tests/test-npm-only-features/test-default-theme/src/main/java/com/vaadin/flow/testonlynpmfeatures/defaulttheme/DefaultThemeView.java
flow-tests/test-npm-only-features/test-default-theme/src/test/java/com/vaadin/flow/testonlynpmfeatures/defaulttheme/DefaultThemeIT.java

Fixes #5812
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5885)

Fix default theme for routes with only html components

---

flow-tests/test-web-components/src/main/java/com/vaadin/flow/webcomponent/WebComponentVaadinServlet.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5890)

Add missing servlet property

---

flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java
flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java
flow-client/src/main/java/com/vaadin/client/LoadingIndicator.java
flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java
flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
flow-client/src/main/java/com/vaadin/client/communication/DefaultReconnectDialog.java
flow-client/src/test-gwt/java/com/vaadin/client/communication/GwtDefaultReconnectDialogTest.java
flow-client/src/test/java/com/vaadin/client/communication/LoadingIndicatorConfiguratorTest.java
flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java
flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
flow-server/src/main/resources/com/vaadin/flow/server/webcomponent/webcomponent-script-template.js
flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentProviderTest.java

This reverts commit 56350c134811dc948675ce61f98e56a2503b5f10.
The given patch has no tests, no use cases and nothing else.
If there are cases for this, the feature can be added back later accompanied
with the required parts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5898)

Revert "Support another element than body for UI. (#5000)"

---

flow-tests/servlet-containers/felix-jetty/pom.xml
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5886)

Use https URLs

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageForProductionMojo.java
flow-maven-plugin/src/main/resources/yarn.lock

Fixes #5892, #4888, #5028
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5891)

Download a supported version of Node and make production build work with new Node versions

---

flow-server/src/main/java/com/vaadin/flow/component/WebComponentExporter.java

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5858)

Make WebComponentExporter.configureInstance protected

---

flow-server/src/main/java/com/vaadin/flow/component/WebComponentExporter.java
flow-server/src/test/java/com/vaadin/flow/component/TemplateComponentTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5904)

'final static' should be 'static final'

---

flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/AbstractBackEndHierarchicalDataProvider.java
flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/BackEndHierarchicalDataProvider.java
flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HasHierarchicalDataProvider.java
flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicationController.java
flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalQuery.java
flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapper.java
flow-server/src/main/java/com/vaadin/flow/server/startup/ServletContextListeners.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5905)

Fix license headers

---

flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicationController.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5907)

Fix sonarQube header complains

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5928)

Ensure target/frontend/node_modules/* are not considered generated files

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendDependencies.java

related with #5803
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5933)

Increase scanning black-list.

---

flow-tests/pom.xml
flow-tests/test-multi-war/deployment/pom.xml
flow-tests/test-multi-war/deployment/src/main/webapp/index.html
flow-tests/test-multi-war/deployment/src/test/java/com/vaadin/flow/multiwar/deployment/TwoAppsIT.java
flow-tests/test-multi-war/pom.xml
flow-tests/test-multi-war/test-war1/pom.xml
flow-tests/test-multi-war/test-war1/src/main/java/com/vaadin/flow/multiwar/war1/HelloComponent.java
flow-tests/test-multi-war/test-war1/src/main/java/com/vaadin/flow/multiwar/war1/MainView.java
flow-tests/test-multi-war/test-war2/pom.xml
flow-tests/test-multi-war/test-war2/src/main/java/com/vaadin/flow/multiwar/war2/HelloComponent.java
flow-tests/test-multi-war/test-war2/src/main/java/com/vaadin/flow/multiwar/war2/MainView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5923)

Test for multiple wars deployed to the same server

---

flow-server/src/main/java/com/vaadin/flow/router/Location.java
flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java

Fixes #4736
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5935)

Root with query params should be handled

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java

Related to #5931
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5944)

Show a better error message if the webpack stats file is not found

---

flow-tests/test-root-context/pom.xml

Fixes tomcat IT tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5948)

Build jar with ui classifier for test-root-context regardless of web-jar repackaging.

---

flow-tests/test-root-context/pom.xml

classes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5957)

Fix maven config so that ui classifier jar contains compiled java

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java

Fixes #5939
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5950)

Don't use special characters.

---

flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java

* Applied changes to enhance the message when there is an @OptionalParameter.
* Modified to show the messages as a link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5914)

debug helping text for optional URL parameter misleading

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5926)

Update to latest tesbtench

---

flow-tests/test-mixed/src/test/java/com/vaadin/flow/mixedtest/ui/IdTestIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5963)

Avoid using getInShadowRoot() methods.

---

flow-client/src/test/resources/simplelogger.properties
flow-server/src/test/resources/simplelogger.properties
flow-tests/test-common/src/main/resources/simplelogger.properties
flow-tests/test-multi-war/deployment/src/main/resources/simplelogger.properties
flow-tests/test-multi-war/test-war1/src/main/resources/simplelogger.properties
flow-tests/test-multi-war/test-war2/src/main/resources/simplelogger.properties
flow-tests/test-resources/src/main/resources/simplelogger.properties

Reduces build log from 11.6MB to 8.3MB
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5937)

Stop the Atmosphere log spam

---

flow-tests/pom.xml
flow-tests/test-mixed/src/test/java/com/vaadin/flow/mixedtest/ui/IdTestIT.java

Will create a ticket to investigate the test failure and enable it back.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5969)

Disable unstable test

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/resources/webpack.generated.js
flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java

Fixes #5947
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5970)

Make webpack-dev-server dynamically serve stats.json file

---

flow-server/src/main/java/com/vaadin/flow/router/EventUtil.java
flow-server/src/test/java/com/vaadin/flow/router/EventUtilTest.java

Fixes #5817
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5968)

Detect composite components and use their underlying component

---

flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java
flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriter.java
flow-server/src/test/java/com/vaadin/flow/internal/ReflectToolsTest.java

Fixes https://github.com/vaadin/skeleton-starter-flow-spring/issues/176
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5972)

More lenient WebComponentModulesWriter classloader comparison

---

flow-server/src/main/java/com/vaadin/flow/router/EventUtil.java
flow-server/src/main/java/com/vaadin/flow/router/Location.java
flow-server/src/test/java/com/vaadin/flow/router/EventUtilTest.java
flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5980)

Cherry picks 1.4 - Don't squash !

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5977)

Remove copyProjectFrontendResources from prepare-frontend

---

flow-maven-plugin/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5978)

Maven 3.3.9 compatibility fix

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java

Fixes #5992
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5998)

Use ADBLOCK when running npm install

---

flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6002)

Fix test that is not clearing port on tear down

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java

Fixes #5988
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5997)

Fix npm version detection in Eclipse

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6003)

Removed custom join(...) implementations

---

flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java

Fixes #5843
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6005)

Reset everything on clear change event handling

---

flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
flow-server/src/test/java/com/vaadin/flow/component/internal/PageTest.java
flow-server/src/test/java/com/vaadin/flow/component/page/PageTest.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/DependencyListTest.java
flow-server/src/test/java/com/vaadin/tests/util/MockUI.java

Fixes #5692
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6021)

Handling addHtmlImport in npm mode

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendClassVisitor.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTestComponents.java

Fixes #6017
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6025)

Fix theme variant

---

flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
flow-server/src/main/resources/webpack.generated.js
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerStopTest.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
flow-tests/test-mixed/pom.xml

Fixes #5990
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6008)

Add a flag to stop the server on exit

---

flow-components-parent/flow-webcomponent-api-analyzer/package-lock.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6052)

Fix lodash.merge version

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
flow-tests/pom.xml
flow-tests/test-misc/frontend/theme/my-theme/my-component-themed.js
flow-tests/test-misc/pom-bower.xml
flow-tests/test-misc/pom.xml
flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/MiscelaneousView.java
flow-tests/test-misc/src/main/webapp/frontend/theme/my-theme/my-component-themed.html
flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/MiscelaneousIT.java

Fixes #5964
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6013)

Look for custom themed files for components in /frontend

---

flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerStopTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6048)

Disable test which freezes validation and snapshot builds.

---

flow-maven-plugin/src/main/resources/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6055)

Fix security alert

---

flow-server/src/main/java/com/vaadin/flow/component/KeyUpEvent.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java
flow-server/src/main/java/com/vaadin/flow/router/Location.java
flow-server/src/main/java/com/vaadin/flow/server/FrontendVaadinServlet.java
flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java
flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java
flow-server/src/test/java/com/vaadin/flow/server/FrontendVaadinServletTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/KeyboardEventView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/HistoryIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/KeyboardEventIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6058)

Cherry picks from master to 1.4

---

flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentMetaData.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java

Fixes #6050
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6059)

Update Javadocs in ComponentMetaData and refactor dependency check

---

flow-server/src/main/java/com/vaadin/flow/component/dependency/CssImport.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java

Fixes: https://github.com/vaadin/flow/issues/6063 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6062)

include attribute must work with css modules

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFiles.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java

Fixes #6074
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6075)

We need to take classpath from classloader when copying resources

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/ImportExtractor.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/ImportExtractorTest.java

Fixes #6061
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6078)

Consider imports only until something else is found

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CopyProductionFilesMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageForProductionMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/ExecutionFailedException.java
flow-server/src/main/java/com/vaadin/flow/server/FallibleCommand.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFiles.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyLocalFrontendFiles.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java

Fixes #5953
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6085)

Use command interface which may throw an exception to indicate failure

---

flow-maven-plugin/src/main/resources/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6068)

Require the latest lodash version

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java

Fixes #6023
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6089)

Run npm install if node_modules dir is empty

---

flow-html-components/pom.xml
flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSerializableTest.java
flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

Fixes #5973
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6101)

Check serializability of components added into a container

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/MigrateMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/migration/CopyMigratedResourcesStep.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/migration/CopyMigratedResourcesStepTest.java

Fixes #6102
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6106)

Filter out files and folders which were not initially in the source

---

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/BundleParserTest.java
flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
flow-server/src/test/resources/META-INF/VAADIN/config/stats.json

Fix the name recognition so that we can
have an add-on with a local polymer template
Fixes #6069
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6091)

Fix bundle parser

---

flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
flow-server/src/test/java/com/vaadin/flow/component/UITest.java
flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java

Fixes #4197
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6112)

Allow to set parent to null for root node (UI element).

---

flow-server/src/main/java/com/vaadin/flow/dom/Element.java

Fixes #6117
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6118)

Fix typo in error message

---

flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/StreamReceiverHandlerTest.java

Fixes https://github.com/vaadin/vaadin-upload-flow/issues/142
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6121)

Use Part.getSubmittedFileName instead of Part.getName

---

flow-client/src/main/resources/com/vaadin/flow/linker/ClientEngineSingleScriptTemplate.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6124)

Make generated client-script be compatible with JS strict mode

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/MigrateMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/migration/CopyResourcesStep.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/migration/CopyResourcesStepTest.java

Fixes #6115
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6119)

Removes comments from HTML template files during copying

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/MigrateMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/migration/CopyResourcesStep.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/migration/RewriteLegacyAnnotationsStep.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/migration/RewriteLegacyAnnotationsStepTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/migration/samplecode/ShouldNotBeRewritten.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/migration/samplecode/StyledComponent.java

Fixes #6114
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6120)

Add logic to rewrite StyleSheet annotations and improve replacement logic

---

flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java
flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
flow-client/src/main/java/com/vaadin/client/PopStateHandler.java
flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java
flow-client/src/test-gwt/java/com/vaadin/client/GwtApplicationConnectionTest.java
flow-client/src/test-gwt/java/com/vaadin/client/GwtSuite.java
flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java

Fixes https://github.com/vaadin/flow/issues/6108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6111)

Do not listen to routing events when the app is run as a WC

---

flow-server/src/main/java/com/vaadin/flow/component/dependency/CssImport.java
flow-server/src/main/java/com/vaadin/flow/component/dependency/JsModule.java

Fixes #6086
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6154)

Fix javadocs for annotations to highlight where the files should be located

---

drivers.xml
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6168)

Chromedriver 76 update

---

flow-components-parent/flow-code-generator-api/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6157)

Update dependency to fix the security alert

---

flow-server-compatibility-mode/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6176)

CCDM: Set parent version of the flow-server-compatibility-mode module

---

flow-server/pom.xml
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/MyUIInitListener.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/RouteComponent.java
flow-tests/test-npm-only-features/test-npm-general/frontend/init-listener-component.js
flow-tests/test-npm-only-features/test-npm-general/src/main/java/com/vaadin/flow/testnpmonlyfeatures/general/ComponentAddedViaInitListener.java
flow-tests/test-npm-only-features/test-npm-general/src/main/java/com/vaadin/flow/testnpmonlyfeatures/general/ComponentAddedViaInitListenerView.java
flow-tests/test-npm-only-features/test-npm-general/src/main/java/com/vaadin/flow/testnpmonlyfeatures/general/TestingServiceInitListener.java
flow-tests/test-npm-only-features/test-npm-general/src/main/java/com/vaadin/flow/testnpmonlyfeatures/general/TestingUiUnitListener.java
flow-tests/test-npm-only-features/test-npm-general/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
flow-tests/test-npm-only-features/test-npm-general/src/test/java/com/vaadin/flow/testnpmonlyfeatures/general/ComponentAddedViaInitListenerIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

Fixes #5792
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6161)

Discover endpoints in UI init listener classes

---

drivers.xml
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6179)

Chromedriver 76 update (#6168)

---

flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/StreamReceiverHandlerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6178)

Apply fix for StreamReceiverHandler upload file name to 1.4 branch

---

flow-tests/pom.xml
flow-tests/test-mixed/pom-bower-devmode.xml
flow-tests/test-mixed/pom-bower-production.xml

Enable mixed modules to check how their test work on TC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6173)

Enable mixed modules

---

flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java

Concerns #6188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6190)

Inform Spring Boot users that 'vaadin.compatibilityMode' must be set separately in compatibility mode exception message

---

flow-tests/pom.xml
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6200)

Always have tests module, but skip tests if requested

---

flow-components-parent/flow-code-generator-api/pom.xml
flow-data/src/main/java/com/vaadin/flow/data/provider/Query.java
flow-server-production-mode/src/main/resources/META-INF/web-fragment.xml
flow-server/src/main/java/com/vaadin/flow/component/Focusable.java
flow-server/src/main/java/com/vaadin/flow/dom/Element.java
flow-server/src/test/java/com/vaadin/flow/component/FocusableTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6211)

Picks from master to 1.4

---

flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/migration/CopyResourcesStepTest.java
flow-server/pom.xml
flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/MyUIInitListener.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/RouteComponent.java
flow-tests/pom.xml
flow-tests/test-mixed/pom-bower-devmode.xml
flow-tests/test-mixed/pom-bower-production.xml
flow-tests/test-npm-only-features/test-npm-general/frontend/init-listener-component.js
flow-tests/test-npm-only-features/test-npm-general/src/main/java/com/vaadin/flow/testnpmonlyfeatures/general/ComponentAddedViaInitListenerView.java
flow-tests/test-npm-only-features/test-npm-general/src/main/java/com/vaadin/flow/testnpmonlyfeatures/general/TestingServiceInitListener.java
flow-tests/test-npm-only-features/test-npm-general/src/main/java/com/vaadin/flow/testnpmonlyfeatures/general/TestingUiUnitListener.java
flow-tests/test-npm-only-features/test-npm-general/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
flow-tests/test-npm-only-features/test-npm-general/src/test/java/com/vaadin/flow/testnpmonlyfeatures/general/ComponentAddedViaInitListenerIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6234)

merge master to ccdm

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java

Part of #6024
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6171)

Correct error message to use frontendDirectory value instead of hardcoded

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java

Fixes #5646
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6164)

Fail the build via Maven or throw a servlet exception if tools are not found

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java

Fixes #6235
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6258)

Renamed "prepare-package" to "prepare-frontend"

---

flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/ClientIndexHandlerIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6237)

CCDM: fix tests after merge

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java

Related with #6142
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6252)

CCDM: adjust DevModeHandler request check to include VAADIN mapping

---

flow-migration/pom.xml

Required for #6095
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6267)

Migration tool: Additionally package a fat jar that can be downloaded and run with `java -jar ...`

---

flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
flow-client/src/test/frontend/FlowTests.ts
flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java

Fixes #6282
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6283)

CCDM: reuse client wrapper element for the Flow UI

---

flow-tests/test-npm-only-features/test-npm-custom-frontend-directory/pom.xml
flow-tests/test-npm-only-features/test-npm-general/pom.xml
flow-tests/test-npm-only-features/test-npm-no-buildmojo/pom.xml
flow-tests/test-root-context/pom.xml

As per @caalador's request:
Removed unnecessary `<version>`s and replaced some with `${project.version}`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6305)

Pom file version ref clean up

---

flow-components-parent/flow-code-generator-api/pom.xml
flow-data/src/main/java/com/vaadin/flow/data/binder/ReadOnlyHasValue.java
flow-server/src/main/java/com/vaadin/flow/router/AfterNavigationObserver.java
flow-server/src/main/java/com/vaadin/flow/router/BeforeEnterObserver.java
flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveObserver.java
flow-server/src/main/java/com/vaadin/flow/router/Router.java
pom.xml

After this, this: https://github.com/vaadin/flow/pull/5983
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6313)

Old 1.0 cherrypicks

---

flow-server/src/main/java/com/vaadin/flow/router/EventUtil.java
flow-server/src/main/java/com/vaadin/flow/router/Location.java
flow-server/src/test/java/com/vaadin/flow/router/EventUtilTest.java
flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/5983)

Cherry picks 1.0 0- Don't squash !

---

flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java

Open up some parts of
WebComponentBootstrapHandler and
WebComponentProvider so that they
can be overridden.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6323)

Make overridable.

---

flow-migration/src/main/java/com/vaadin/flow/migration/RewriteLegacyAnnotationsStep.java
flow-migration/src/test/java/com/vaadin/flow/migration/RewriteLegacyAnnotationsStepTest.java
flow-migration/src/test/java/com/vaadin/flow/migration/samplecode/NonVaadinComponent.java

Fixes #6208
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6325)

Add log message about non-Vaadin component and change the generated path

---

flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java

Fixes #4901
(cherry picked from commit 16afcbbb18eae0b448a9ce4a57e38e56ea691664)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6317)

Avoid NPE in validation methods (#5484)

---

flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveObserver.java

typo fix
(cherry picked from commit d063edf9190ceff34e7327a8be5605aa7b5bd5df)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6328)

Update BeforeLeaveObserver.java (#6316)

---

flow-components-parent/flow-webcomponent-api-analyzer/package-lock.json
flow-components-parent/flow-webcomponent-api-analyzer/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6356)

Fix GitHub vulnerability warning

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/JarContentsManager.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/JarContentsManagerTest.java

Fixes #6274
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6353)

Don't overwrite the file if it has the same content

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/EndPointData.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/JsOrderComponent.java

Fixes #6198
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6371)

Preserve JavaScript annotations order

---

flow-server/src/main/java/com/vaadin/flow/server/SessionRouteRegistry.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerPushConfigurationTest.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/SessionRouteRegistryTest.java

Fixes #6236
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6389)

Don't store parent registry in session route registry.

---

flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6407)

Use compatibility mode for OSGi servlets.

---

flow-server/src/main/java/com/vaadin/flow/server/SessionRouteRegistry.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerPushConfigurationTest.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/SessionRouteRegistryTest.java

Fixes #6236
(cherry picked from commit 3d934121aefbb7460db6f57c1d611f58ce877a05)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6409)

Cherry-pick from master: Don't store parent registry in session route registry. (#6389)

---

flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/TestComponents.java
flow-server/src/main/java/com/vaadin/flow/internal/UrlUtil.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-tests/test-npm-only-features/test-npm-general/src/main/java/com/vaadin/flow/testnpmonlyfeatures/general/ComponentWithExternalJsModule.java
flow-tests/test-npm-only-features/test-npm-general/src/main/java/com/vaadin/flow/testnpmonlyfeatures/general/ExternalJSModuleView.java
flow-tests/test-npm-only-features/test-npm-general/src/test/java/com/vaadin/flow/testnpmonlyfeatures/general/ExternalJSModuleIT.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExecJavaScriptView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/dependencies/ComponentWithExternalJavaScript.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/dependencies/ExternalJavaScriptView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/ExternalJavaScriptIT.java

Fixes #6298
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6324)

Interpret JavaScript URLs starting with "//" as external URLs

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

Helps debugging problems like: #6384
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6410)

Add log for failing path relativization.

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesTest.java

Fix getting shrinkwrap version from
package-lock.json
fixes #6151
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6433)

Fix getting shrinkwrap version

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsLocator.java

Fixes #6392
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6457)

Don't use error level if locate command fails

---

flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
flow-client/src/test/frontend/FlowTests.ts

Fixes #6475
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6476)

CCDM: assure that `onBeforeLeave` is always executed

---

flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java

Fixes #6494
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6495)

Don't stop read InputStream is zero bytes are read.

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShortcutsIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6497)

Replay shortcut test fix

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/DevServerWatchDog.java
flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriter.java
flow-server/src/main/resources/webpack.generated.js
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

Fixes #6291
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6487)

Add watchdog in webpack process config via connecting to a Java socket

---

flow-data/src/main/java/com/vaadin/flow/data/provider/FilterUtils.java
flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalFilterUtils.java
flow-server/src/main/java/com/vaadin/flow/component/ShortcutEvent.java
flow-server/src/main/java/com/vaadin/flow/component/ShortcutEventListener.java
flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
flow-server/src/main/java/com/vaadin/flow/component/Shortcuts.java
flow-server/src/main/java/com/vaadin/flow/dom/DomListenerRegistration.java
flow-server/src/main/java/com/vaadin/flow/dom/Element.java
flow-server/src/main/java/com/vaadin/flow/router/RouteAliasData.java
flow-server/src/main/java/com/vaadin/flow/router/RouteBaseData.java
flow-server/src/main/java/com/vaadin/flow/router/RouteConfiguration.java
flow-server/src/main/java/com/vaadin/flow/router/RoutesChangedEvent.java
flow-server/src/main/java/com/vaadin/flow/router/RoutesChangedListener.java
flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
flow-server/src/main/java/com/vaadin/flow/router/internal/ConfigureRoutes.java
flow-server/src/main/java/com/vaadin/flow/router/internal/ConfiguredRoutes.java
flow-server/src/main/java/com/vaadin/flow/router/internal/ErrorTargetEntry.java
flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
flow-server/src/main/java/com/vaadin/flow/server/RouteRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/SessionRouteRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/StaticFileHandler.java
flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterFactory.java
flow-server/src/main/java/com/vaadin/flow/theme/ThemeUtil.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6498)

Added 1.3 since tags

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/DevServerWatchDog.java
flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/resources/webpack.generated.js
flow-server/src/test/java/com/vaadin/flow/internal/ResponseWriterTest.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShortcutsView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShortcutsIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6499)

Picks from master to 2.0

---

flow-push/src/main/java/com/vaadin/flow/push/osgi/PushOsgiStaticResource.java
flow-server/src/main/java/com/vaadin/flow/server/AmbiguousRouteConfigurationException.java
flow-server/src/main/java/com/vaadin/flow/server/FrontendVaadinServlet.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LongPollingMultipleThreadsView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6503)

Added 1.4 since tags

---

drivers.xml
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6516)

Update version, zips, and hashes for chrome

---

drivers.xml
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6529)

Update version, zips, and hashes for chrome (#6516)

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsLocator.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/resources/webpack.generated.js

Should fix problem with webpack dying
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6526)

merge master

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/EndPointData.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerCssTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerTestComponents.java

Fixes #6523
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6534)

Css imports in predictable order, and not the one dictated by hashcode

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/AbstractDependenciesScanner.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ThemeData.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ThemeWrapper.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsWithByteCodeScannerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsWithFullCPScannerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesWithByteCodeScannerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesWithFullCPCodeScannerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeClassFinderTest.java

Fixes #6480
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6521)

Full classpath scanning for frontend resources

---

flow-server/src/main/java/com/vaadin/flow/component/dependency/CssImport.java
flow-server/src/main/java/com/vaadin/flow/component/dependency/JavaScript.java
flow-server/src/main/java/com/vaadin/flow/component/dependency/JsModule.java
flow-server/src/main/java/com/vaadin/flow/theme/NoTheme.java

Part of vaadin/spring#497
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6545)

Make frontend resource annotations inherited.

---

pom.xml

Fixes https://github.com/vaadin/flow/issues/6464
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6551)

Update to the latest JSoup version

---

flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6553)

Revert disabling safari 9

---

flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java

* Adds WildFly's vfs protocol support to DevModeInitializer
* Adds physical file of JBoss vfs jar to frontendFiles
* Create a temporary jar file from vfs files
* Add support for both jar and plain directory in vfs
(cherry picked from commit 39b5bcc93c843ec2a5984fcfbde3805dfffa4327)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6555)

Pick WildFly's vfs protocol support from master

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-push/src/main/resources/META-INF/resources/VAADIN/static/push/vaadinPush.js
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsLocator.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
pom.xml

Rebase
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6554)

2.0.14 cherry picks

---

pom.xml

This reverts commit b6594c4508aa795d4e04c41dad17a231bc5e75d2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6564)

Revert "Update to the latest JSoup version (#6551)"

---

flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentMetaData.java

Closes #6575
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6579)

Add CssImport collection to ComponentMetaData

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/main/resources/webpack.generated.js
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/EmptyByteScannerDataTestComponents.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/ExtraNodeTestComponents.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithByteCodeScannerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithFullCPScannerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6572)

Generate  fallback imports file and add fallback chunk info into token file

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/AbstractDependenciesScanner.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ThemeWrapper.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6569)

Add empty since tags

---

flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FallbackChunk.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
flow-tests/test-npm-only-features/test-npm-bytecode-scanning/src/main/java/com/vaadin/flow/testnpmonlyfeatures/bytecodescanning/ByteCodeScanningView.java
flow-tests/test-npm-only-features/test-npm-bytecode-scanning/src/test/java/com/vaadin/flow/testnpmonlyfeatures/bytecodescanning/ByteCodeScanningIT.java

Fixes #6576
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6581)

Make fallback chunk info available via VaadinContext

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FallbackChunk.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6589)

Fix javadocs for fallback chunk and add extra CTOR

---

flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
flow-client/src/test/frontend/FlowTests.ts
flow-tests/test-ccdm/frontend/client-router.js
flow-tests/test-ccdm/frontend/index.js

Connected to #6580
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6594)

CCDM: rename flow.route to flow.serverSideRoutes

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java

When ever we add something to the
main package.json we should force
npm install.
Fixes #6514
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6592)

 package.json updates force npm i

---

flow-data/src/main/java/com/vaadin/flow/data/converter/Converter.java

Fixes #6571
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6613)

Correct Javadoc lines

---

flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java

Fixes #6578
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6611)

CCDM: generate a TS definition file for generated-flow-imports.js

---

flow-data/src/main/java/com/vaadin/flow/data/converter/StringToUuidConverter.java

This PR will add a new Converter for java.util.UUIDs. As mentioned in the issue #4400 this was solved for vaadin/framework (Vaadin8) by @basil-bourque . I used his code and added an aligned version for vaadin/flow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6614)

add StringToUuidConverter (#4400)

---

flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentBinding.java
flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentBindingTest.java

Fixes #6566
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6639)

Fix JsonValues for Embedding

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java

Fixes #6599
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6647)

Lumo theme as default for exporters

---

flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
flow-client/src/test/frontend/FlowTests.ts
flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
flow-tests/test-ccdm/pom-production.xml
flow-tests/test-ccdm/pom.xml
flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java

Fixes #6609
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6638)

CCDM: consider servlet context when server navigation

---

flow-server/src/main/java/com/vaadin/flow/server/startup/NavigationTargetFilter.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6649)

Fix wrong path to service file in javadocs

---

flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java

Do not load flow-build-info from a jar.
Fixes #6616
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6636)

Do not load jar build-info

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/resources/webpack.generated.js
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
flow-server/src/test/resources/InvalidStats.json
flow-server/src/test/resources/MissFormatStats.json
flow-server/src/test/resources/ValidStats.json

Fixes #6650, #6635 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6648)

For bootstrap only read until assetsByChunkName

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java

Fixed few typos and lines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6658)

Improved exception readability in FullDependenciesScanner

---

flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java

Fixes #6651
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6660)

Use compatibility mode for Frontend servlet.

---

flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6664)

Avoid asking classloader on servlet context.

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java

Fixes #6667
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6668)

Remove duplicate import entries from generated-flow-imports.js

---

flow-server/pom.xml
flow-tests/servlet-containers/felix-jetty/pom.xml
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6681)

Pin byte buddy version

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java

Fixes #6471
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6676)

Use setStatus for non error response code

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/RouteComponentWithMethodReference.java

Fix #6524
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6686)

Visit method references in byte code traversal

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/JsModuleComponent.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/RouteInterface.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/RouteInterfaceComponent.java
flow-tests/test-npm-only-features/test-npm-bytecode-scanning/pom-devmode.xml

Fixes https://github.com/vaadin/flow/issues/6424
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6684)

Visit implemented interfaces when preparing frontend.

---

flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
flow-data/src/main/java/com/vaadin/flow/data/renderer/RendererUtil.java
flow-data/src/test/java/com/vaadin/flow/data/renderer/RendererUtilTest.java
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/main/resources/com/vaadin/flow/server/webcomponent/webcomponent-script-template.js
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/frontend/FrontendProtocolView.java
flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/FrontendProtocolIT.java

Fixes #5252
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6702)

Use application id to call client side app context methods

---

flow-server/src/main/java/com/vaadin/flow/component/EventData.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6710)

List supported types in @EventData javadocs

---

flow-server/pom.xml

Connected to https://github.com/vaadin/flow/issues/6701
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6704)

CCDM: mark spring dependencies as provided

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/JsModuleComponent.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/RouteInterface.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/RouteInterfaceComponent.java

* Visit implemented interfaces.
* Fix comments. Test css imports annotations.
(cherry picked from commit d90d8aa441844a85e1c0ee280cc658331fbb7fdc)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6713)

Cherry-pick: Visit implemented interfaces when preparing frontend. (#6684)

---

flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java

Fix #6160
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6705)

Enhancing DEBUG mode startup warning message

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/WebComponentModulesGenerator.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/common/WebComponentModulesGeneratorTest.java
flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializer.java
flow-tests/test-embedding/embedding-test-assets/src/main/java/com/vaadin/flow/webcomponent/InterfaceBasedExporter.java
flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/InterfaceBasedIT.java
flow-tests/test-embedding/webapp/compatibility-dev/interfaceBased.html
flow-tests/test-embedding/webapp/compatibility-prod/interfaceBased.html
flow-tests/test-embedding/webapp/npm/interfaceBased.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6692)

ExportsWebComponent: IT + fix for compatibility/prod mode

---

flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
flow-client/src/main/java/com/vaadin/client/ScrollPositionHandler.java
flow-data/src/main/java/com/vaadin/flow/data/renderer/RendererUtil.java
flow-data/src/test/java/com/vaadin/flow/data/renderer/RendererUtilTest.java
flow-server/src/main/java/com/vaadin/flow/component/EventData.java
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
flow-server/src/main/resources/com/vaadin/flow/server/webcomponent/webcomponent-script-template.js
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/JsModuleComponent.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/RouteInterface.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/RouteInterfaceComponent.java
flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/frontend/FrontendProtocolView.java
flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/FrontendProtocolIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6721)

Merge master to 2.1

---

flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/StreamResourceHandlerTest.java

Fixes #6076
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6726)

Set internal server error status on stream resource exception

---

flow-server/src/main/java/com/vaadin/flow/component/UI.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6728)

Fix app id in UI.

---

flow-server/src/main/java/com/vaadin/flow/server/startup/ConnectServicesValidator.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer
flow-server/src/test/java/com/vaadin/flow/server/startup/ConnectServicesValidatorTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeClassFinderTest.java

Fixes #6701
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6719)

CCDM: throw when using VaadinService in non Spring projects

---

flow-tests/test-ccdm/frontend/client-router.js
flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/ViewWithServerViewButton.java
flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java

Fixes #6665
Depends on #6700
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6708)

CCDM: Test ui.navigate updates URL when using client-side routing

---

flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java

Be more strict with the resource filter.
Accept production mode build file in
production mode build, this enables
production mode in fat- and uber-jars.
Fixes #6679
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6685)

Enable fat-/uber-jar production mode

---

flow-dnd/pom.xml
flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DragSource.java
flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DropTarget.java
flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java
flow-dnd/src/main/resources/META-INF/resources/frontend/dndConnector.js
flow-dnd/src/test/java/com/vaadin/flow/component/dnd/AbstractDnDUnitTest.java

It works but has an issue with scrolling while dragging #6696.
Part of #3978
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6697)

Generic DnD: enable dnd polyfill for iOS

---

flow-dnd/pom.xml
flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DragSource.java
flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DropTarget.java
flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java
flow-dnd/src/main/resources/META-INF/resources/frontend/dndConnector.js
flow-dnd/src/test/java/com/vaadin/flow/component/dnd/AbstractDnDUnitTest.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6742)

Cherry-pick: dnd polyfill for iOS (#6697)

---

flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6741)

Exclude DnDConnectorResource from SerializableTest

---

flow-server/src/main/resources/webpack.generated.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6729)

Remove spam from watchdog

---

flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java

Part of https://github.com/vaadin/portlet-support/issues/45
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6740)

WebComponentProvider: added protected method for clearing tag -> bootstrap cache

---

flow-server/src/main/java/com/vaadin/flow/server/startup/ConnectServicesValidator.java
flow-server/src/test/java/com/vaadin/flow/server/startup/ConnectServicesValidatorTest.java

This fixes builds in  [CDI projects](https://bender.vaadin.com/viewLog.html?buildId=98098&buildTypeId=VaadinPlatform_VaadinStarterTestingNightly_SkeletonStarterFlowCdi_SkeletonSta&tab=buildLog)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6747)

CCDM: skip spring check when in a CDI environment

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexJs.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateIndexJsTest.java

Fixes #6688
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6744)

CCDM: ensure generated index js is valid for Windows

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java

Update version handling to be
more readable and robust.
Fixes #6743
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6750)

Fail if npm of known faulty version (#6745)

---

flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
flow-server/pom.xml
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateConnect.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/connect/generator/openapi/OpenApiSpecBasedTests.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateOpenApiTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeClassFinderTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

Fixes #6222 #6643
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6755)

CCDM: run TS generators in dev-mode

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6758)

CCDM: move connect goals from prepare to build goal

---

drivers.xml
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6761)

Update browser version to 78 from 77

---

flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/PreElement.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/Pre.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/PreTest.java

solved like described in #5010
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6725)

Add Java API for pre element (#5010)

---

drivers.xml
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

Update chrome driver
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6765)

Update browser version to 78 from 77 (#6761)

---

flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/PreElement.java
flow-html-components/src/main/java/com/vaadin/flow/component/html/Pre.java
flow-html-components/src/test/java/com/vaadin/flow/component/html/PreTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6767)

Add Java API for pre element (#5010) (#6725)

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6780)

Remove from release profile removed module

---

flow-server/src/main/resources/com/vaadin/flow/server/BootstrapHandler.js

Connected to https://github.com/vaadin/components-team-tasks/issues/479
Needed for the Components to be used in connectors (i.e. here: https://github.com/vaadin/vaadin-time-picker-flow/pull/51)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6783)

Add tryCatchWrapper

---

flow-server/pom.xml
flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectClientGenerator.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateConnectTest.java
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/expected-connect-client-default.ts
flow-tests/test-ccdm-connect/src/main/java/com/vaadin/flow/connect/VaadinView.java
flow-tests/test-ccdm-connect/src/main/resources/application.properties
flow-tests/test-ccdm-connect/src/test/java/com/vaadin/flow/connect/VaadinViewIT.java
flow-tests/test-ccdm-connect/tsconfig.json

Fixes #6777
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6794)

CCDM: use default relative connect endpoint

---

flow-server/src/main/resources/com/vaadin/flow/server/BootstrapHandler.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6800)

Add tryCatchWrapper (#6783)

---

flow-client/intern.json
flow-client/package.json
flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
flow-client/src/test/frontend/ConnectTests.ts
flow-client/src/test/frontend/FlowTests.ts
flow-client/src/test/frontend/utils.js
flow-client/webpack.tests.config.js
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/main/resources/connect-client.default.ts.template
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateConnectTest.java
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/expected-connect-client-custom.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/expected-connect-client-default.ts

Fixes #6770
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6814)

CCDM: package connect-client in flow-client.jar

---

flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
flow-server/src/main/java/com/vaadin/flow/dom/Element.java

Fixes #6791
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6815)

Clarify executeJs JavaDocs for return values

---

flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java

Fixes #2210
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6833)

Handle client-initiated resync request

---

flow-server/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
flow-server/src/test/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessCheckerTest.java

Fixes #6771
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6839)

CCDM: check user roles when accessing to services

---

flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java

* Support client-initiated resync request
* Reverted debugging aids
* Signal resync need by custom exception, improved log message
* Removed disused field UIInternals.clientResync
* Log, minor JavaDoc changes
* NOSONAR
* Merge branch 'master'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6847)

Handle client-initiated resync request (#6833)

---

flow-bom/pom.xml
flow-client/src/main/java/com/vaadin/client/ResourceLoader.java
flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/component/dependency/CssImport.java
flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
flow-server/src/main/java/com/vaadin/flow/dom/Element.java
flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
flow-server/src/main/resources/webpack.generated.js
flow-server/src/test/java/com/vaadin/flow/router/RouterLinkTest.java
flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/dependencies/DynamicDependencyView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/DynamicDependencyIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6863)

2.1 cherry picks for rc2

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ClassFinderTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/ErrorComponent.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeClassFinderTest.java

Fixes #5659
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6864)

Add HasErrorParameter classes to the endpoints

---

flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java

Part of #6763
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6865)

Clarify isCloseIdleSession method javadocs

---

flow-bom/pom.xml
flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/component/dependency/CssImport.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6866)

Cherry picks for 2.0.18

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ClassFinderTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/ErrorComponent.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeClassFinderTest.java

Fixes #5659
(cherry picked from commit 3d68811eb0713f66b9ba7717eb436f0166fef682)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6871)

Add HasErrorParameter classes to the endpoints (#6864)

---

flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java

Part of #6763
(cherry picked from commit 406057a08abb28b66b40d508aa0fe7474eae9b2a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6875)

Clarify isCloseIdleSession method javadocs (#6865)

---

flow-server/src/main/resources/com/vaadin/flow/server/frontend/index.html
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

Use the same styles as in V14 apps.
Closes #6877
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6878)

fix: change the default body styles in V15 apps

---

flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java

Change new method from protected to private to keep API comp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6900)

Fix cherry-picked API

---

flow-server/src/main/java/com/vaadin/flow/component/HasComponents.java
flow-server/src/main/java/com/vaadin/flow/component/Text.java
flow-server/src/main/java/com/vaadin/flow/dom/Element.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicTextElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/TextNodeMap.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6905)

Add "not null" javadocs to a chain of text node methods

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PageIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6925)

Fix IT in snapshot

---

flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java

Enable using a stats.json file from
external service.
Fixes #6923
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6928)

Enable using external stats.json

---

flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerPushConfigurationTest.java

Fixes #4337
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6943)

Enable push unit tests for Java 10

---

flow-client/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6957)

Disable dev mode for GWT unit tests to speed up them

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

Fixes #6960
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6963)

Upgrade webpack-babel-multi-target-plugin dependency

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

Fixes #6489
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6956)

Make DevModeHandler non serializable

---

flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java

Fixes #5630
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6962)

Filters out meta and style tags from head element

---

flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java
flow-client/src/main/java/com/vaadin/client/ScrollPositionHandler.java

Fixes vaadin/portlet-support#133
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6982)

Don't use scroll position handler in embedded web components app

---

flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6979)

Deprecate isIPad due to changes in detection.

---

flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java

Part of #6802 
Cherry pick to 2.0 and 2.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6981)

Add deprecation messages for isIPad

---

flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6988)

Add deprecation messages for isIPad (#6981)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6986)

Pin @vaadin/vaadin-element-mixin to 2.1.5

---

flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java

(cherry picked from commit 90d4411e126928e75c75ec060e36622d174571bb)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6992)

Cherry-pick (#6931)

---

flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
flow-server/src/main/java/com/vaadin/flow/server/communication/MetadataWriter.java
flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
flow-server/src/main/java/com/vaadin/flow/shared/JsonConstants.java
flow-server/src/test/java/com/vaadin/flow/server/communication/CommunicationUtil.java
flow-server/src/test/java/com/vaadin/flow/server/communication/MetadataWriterTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/PushAtmosphereHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/RouterTestServlet.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SessionCloseLogoutView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SessionCloseLogoutIT.java

Fixes #4071 for Flow 2.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7006)

Send sessionExpired as early as possible. (#6798)

---

flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7004)

Improve InitialPageSettings::addInlineWithContents Javadoc

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java

Fix #6737
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7011)

Prevent VaadinSession.setErrorHandler from accepting null

---

flow-tests/README.md
flow-tests/test-dev-mode/pom.xml

Add a readme for test modules
that tries to explain what a test module
is testing/used for and in which modes.
Cloases #6732
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/6995)

Add test module readme

---

flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java

(cherry picked from commit d321dcf9a256391420176d85b0839a5fdd8f827b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7023)

Improve InitialPageSettings::addInlineWithContents Javadoc (#7004)

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java

Fixes #6973
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7013)

Do not add defer attribute to JS module element

---

flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java

Fix a problem in spring initialization.
See the problem in this build:
https://teamcity.vaadin.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=55788&_focus=1762
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7024)

CCDM: prevent infinite-loop when controller mapping is registered

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7025)

update to latest testbench

---

flow-client/src/main/java/com/vaadin/client/flow/reactive/Reactive.java
flow-client/src/test/java/com/vaadin/client/flow/reactive/ReactiveTest.java
flow-tests/test-root-context/frontend/template-scalability-panel.js
flow-tests/test-root-context/frontend/template-scalability-view.js
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityPanel.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityView.java
flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/template-scalability-panel.html
flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/template-scalability-view.html
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityIT.java

Fixes #5806
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7022)

Don't flush if flush underway.

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java

Move extra logs to debug and
give better information in info logs.
Part of #6784
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7014)

Improve logging

---

flow-client/src/main/java/com/vaadin/client/flow/reactive/Reactive.java
flow-client/src/test/java/com/vaadin/client/flow/reactive/ReactiveTest.java
flow-tests/test-root-context/frontend/template-scalability-panel.js
flow-tests/test-root-context/frontend/template-scalability-view.js
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityPanel.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityView.java
flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/template-scalability-panel.html
flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/template-scalability-view.html
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityIT.java

Fixes #5806
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7037)

Don't flush if flush underway. (#7022)

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdMapper.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateInitializer.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java

No squash as only cherry picks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7039)

Avoid shadow root and logging improvement

---

LICENSE

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7045)

Remove unnecessary part from LICENSE

---

flow-server/src/main/java/com/vaadin/flow/router/Route.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7053)

Simplify JavaDoc for @Route.absolute

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java

Fixes #7019
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7051)

Add a command to locate pnpm executable

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
flow-server/src/test/resources/META-INF/resources/VAADIN/static/client/compile.properties
flow-tests/test-embedding/embedding-test-assets/src/main/java/com/vaadin/flow/webcomponent/ClientSelectExporter.java
flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/EmbeddedWebComponentIT.java

Fixes #5315
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7049)

Ignore PWA registry in embedded bootstrapper and add tests

---

flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7062)

Update reference to ticket with details

---

flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/AppShell.java
flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java

connects #6938
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7065)

CCDM: adding a IT for AppShell -> @Meta

---

flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java

In case we have build info in a jar and
we can't determine a valid one,
accept at least a single one for use and
log the information that we are using a
non verified flow-build-info.json
This will make flattened Uber jars work
but they have other missmatch problems also
with files so the user probably knows how to handle
the situation.
Fixes #7060
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7072)

Accept a build-info #7066

---

flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/WhenDefinedManager.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7076)

Load dependencies for components pending attach

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/MigrateMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
flow-migration/src/main/java/com/vaadin/flow/migration/Migration.java
flow-migration/src/main/java/com/vaadin/flow/migration/MigrationConfiguration.java
flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
flow-tests/pom.xml
flow-tests/test-mixed/pom-npm-production.xml
flow-tests/test-mixed/pom-npm.xml
flow-tests/test-mixed/pom-pnpm-production.xml
flow-tests/test-mixed/pom.xml
flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java

Fixes #7020
Fixes #7021
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7059)

Install pnpm if it's not disabled explicitly

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java

Exception message now also instructs
to remove package-lock.json to fix the
node_modules dependencies.
Part of #7000
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7008)

Update exception message

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7096)

Fix tests now that pnpm is in use.

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java

Fixes #7083
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7095)

Avoid clean up if PNPM is used

---

flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java

Avoids ConcurrentModificationException if firing an event causes
listeners to be added or removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7103)

Iterate over a copy for UI internals listeners

---

flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java

Test run against a local installation of pnpm
test was expecting a global installation
to be used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7100)

Fix command expectations to expect a local install

---

LICENSE
flow-server/src/main/java/com/vaadin/flow/router/Route.java
flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7092)

Picks from master to 1.0

---

flow-dnd/src/main/resources/META-INF/resources/frontend/dndConnector.js

Fixes #7108, #7109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7110)

Fix drop target highlighting issues with child elements

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java

Part of #7113
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7117)

Remove old "flow-deps" dependency/package-lock if PNPM is used

---

flow-server/src/main/java/com/vaadin/flow/dom/Element.java
flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java

Fixes #7085
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7131)

Use Element API for traversing children to call the onEnabledStateChanged method

---

flow-server/src/main/java/com/vaadin/flow/component/page/ExtendedClientDetails.java
flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
flow-server/src/test/java/com/vaadin/flow/component/page/ExtendedClientDetailsTest.java

Fixes #6671
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7139)

Deprecate isIOS method and make it in ExtendedClientDetails

---

flow-data/src/main/java/com/vaadin/flow/data/binder/BeanValidationBinder.java

Cherry pick from: https://github.com/vaadin/framework/pull/11801
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7099)

Added missing constructor with scanNestedDefinitions option

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

Fixes #7121
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7122)

Upgrade webpack plugins to fix npm audit warnings

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7141)

Update compression plugin

---

flow-client/src/main/resources/META-INF/resources/frontend/FlowBootstrap.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7145)

CCDM: cherry pick changes in BootstrapHandler.js to FlowBootstrap.js

---

flow-data/src/main/java/com/vaadin/flow/data/binder/BeanValidationBinder.java
flow-dnd/src/main/resources/META-INF/resources/frontend/dndConnector.js
flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
flow-server/src/main/java/com/vaadin/flow/component/page/ExtendedClientDetails.java
flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
flow-server/src/main/java/com/vaadin/flow/dom/Element.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
flow-server/src/test/java/com/vaadin/flow/component/page/PageTest.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-tests/README.md
flow-tests/test-dev-mode/pom.xml
flow-tests/test-memory-leaks/src/test/java/com/vaadin/flow/memoryleaks/ui/RedeployLeakIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7151)

Cherry picks for 2.1 branch. Do not squash

---

flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java

Fixes #7126
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7140)

fix navigation loops

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java

If building sourcemaps for webpack
the assets array will contain an array
of bundles instead of a single string.
Fixes #7158
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7159)

Handle possible array

---

flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
flow-client/src/test/frontend/FlowTests.ts

Related with https://github.com/vaadin/vaadin-combo-box-flow/issues/316
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7153)

CCDM: prevent connector failures when they expect connected component

---

flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7155)

Make links focusable

---

flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java
flow-dnd/src/test/java/com/vaadin/flow/component/dnd/AbstractDnDUnitTest.java
flow-dnd/src/test/java/com/vaadin/flow/component/dnd/internal/DnDUtilHelper.java

Fixes #7123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7163)

Fix broken mobile dnd polyfill for ipad on iOS13

---

flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicTextElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/ShadowRootStateProvider.java
flow-server/src/test/java/com/vaadin/flow/dom/impl/ElementStateProviderDeserializationTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7192)

fixes #7190

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java

Fixes #7183
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7191)

Pin pnpm verion to 4.5 and remove workaround for 4.3.3

---

flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java

Fixes #7188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7189)

Pass query parameters to the new location

---

flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
flow-client/src/main/resources/META-INF/resources/frontend/FlowBootstrap.js
flow-client/src/test/frontend/FlowTests.ts

Fixes: https://github.com/vaadin/testbench/issues/1229
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7193)

CCDM: inform TestBench that Flow client navigation is in progress

---

drivers.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7181)

Update chromedriver to v79

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7201)

Assert chrome version 79

---

flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java

Fixes #7187
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7195)

CCDM: fix NPE when in prod there is no VaadinAppShell

---

drivers.xml
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7207)

Update chromedriver and test for version 79

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7203)

CCDM: bump router version

---

flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java

follow-up on https://github.com/vaadin/flow/pull/7209
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7213)

chore: remove unused method parameter

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java

Fixes #7182
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7216)

Error message for failing imports should be tool dependent

---

flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java

Fixes #7148
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7220)

Combine all constructors together

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java

This is useful when looking for the class with the incorrect annotation. For instance for the problem in https://github.com/vaadin/skeleton-starter-flow/pull/269 due to an incorrect annotation described in https://github.com/vaadin/vaadin-list-box-flow/issues/69
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7221)

log: debug the list of dependencies and imports found in classes

---

flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/selfreference/SelfReference.java
flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/selfreference/SelfReferenceService.java
flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/selfreference/SelfReferenceTest.java
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-media.Schema.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-model-model.ModelService.Account.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/selfreference/expected-SelfReferenceService.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/selfreference/expected-model-selfreference.SelfReference.ts

Fixes #7210
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7214)

Remove self imports from generated TS files

---

flow-server/pom.xml

Fixes #7204
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7222)

Remove test-jar artifact from flow-server

---

flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlResponse.java
flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
flow-tests/test-ccdm/pnpm-lock.yaml

Dp/ccdm/add optional ui getter into index html request listener
fixes #6940
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7223)

add UI getter into IndexHtmlRequestListener

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java

Fixes #7198
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7236)

CCDM: serve all assets from webpack dev server

---

flow-server/src/test/java/com/vaadin/flow/component/internal/PageTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7237)

Remove unused method from PageTest

---

flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7241)

fix: warn about PageConfigurator also in Spring apps

---

flow-migration/src/main/java/com/vaadin/flow/migration/Migration.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java

Closes #7219 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7233)

If globally installed pnpm is too old, install newer version locally

---

flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7249)

rename VaadinAppShell also in error messages

---

flow-client/tsconfig.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7253)

Add skipLibCheck to tsconfig.json

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7197)

Make node.js install prompt more friendly

---

drivers.xml
flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
flow-client/src/main/java/com/vaadin/client/flow/nodefeature/MapProperty.java
flow-data/src/main/java/com/vaadin/flow/data/renderer/LocalDateRenderer.java
flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java
flow-dnd/src/test/java/com/vaadin/flow/component/dnd/AbstractDnDUnitTest.java
flow-dnd/src/test/java/com/vaadin/flow/component/dnd/internal/DnDUtilHelper.java
flow-server/pom.xml
flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentWrapper.java
flow-server/src/main/java/com/vaadin/flow/dom/Element.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicTextElementStateProvider.java
flow-server/src/main/java/com/vaadin/flow/dom/impl/ShadowRootStateProvider.java
flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
flow-server/src/main/resources/com/vaadin/flow/server/safari-10-1-script-nomodule.js
flow-server/src/main/resources/webpack.generated.js
flow-server/src/test/java/com/vaadin/flow/dom/impl/ElementStateProviderDeserializationTest.java
flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/ApplicationRouteRegistryTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryTestBase.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ElementInnerHtmlView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ElementInnerHtmlIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7258)

Picks from master to 2.1

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java

Fixes #7260
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7261)

Fix logging information for dependency updates.

---

flow-server/src/main/resources/com/vaadin/flow/server/default-pwa-prompt.html

Fixes #7170
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7271)

CCDM: make pwa-UI work before flow client has been initialized

---

flow-client/src/test/frontend/FlowTests.ts
flow-client/src/test/frontend/stubVaadinPush.js
flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7275)

CCDM: test loading pushScript in Flow.ts

---

flow-tests/pom.xml
flow-tests/test-pwa/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7278)

Enable PWA IT

---

flow-tests/pom.xml

Part of #7242
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7280)

Reenable scalability and memory-leak ITs

---

flow-migration/src/main/java/com/vaadin/flow/migration/Migration.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java

Fixes #7227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7292)

Disable pnpm update-notifier

---

flow-server/src/main/java/com/vaadin/flow/component/internal/DeadlockDetectingCompletableFuture.java
flow-server/src/main/java/com/vaadin/flow/component/page/PendingJavaScriptResult.java
flow-server/src/test/java/com/vaadin/flow/component/internal/PendingJavaScriptInvocationTest.java
flow-server/src/test/java/com/vaadin/flow/server/MockVaadinSession.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7218)

Throw if blocking on JS result would deadlock

---

flow-tests/pom.xml

Part of #7242
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7295)

Enable npm-only ITs

---

flow-tests/pom.xml

Part of #7242
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7298)

Enable mixed production mode ITs.

---

flow-tests/pom.xml

Part of #7242
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7297)

Enable misc ITs

---

flow-tests/pom.xml

Part of #7242
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7293)

Enable CCDM module: dev moe and production

---

flow-tests/pom.xml
flow-tests/test-servlet/pom.xml

Part of #7242
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7290)

Enable servlet it

---

flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java
flow-tests/pom.xml

Part of #7242
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7296)

Enable test-embedding ITs

---

flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/Card.java
flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/DemoView.java
flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/SourceContent.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7314)

Fix component demo helpers

---

flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java

Part of #6856
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7316)

Support Safari 13 upwards

---

flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/TreeDataProvider.java
flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithDataTest.java
flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/TreeDataProviderTest.java

Fixes https://github.com/vaadin/vaadin-grid-flow/issues/819
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7317)

TreeDataProvider: Apply filters to children

---

flow-client/package.json
flow-client/scripts/client.js

Fixes #7283
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7324)

Extract FlowClient.js build script from package.json

---

flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java

..and ?closeApplication. Instead move them to proper place.
Part of #6510
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7335)

Revert removal of ?restartApplication

---

flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/TreeDataProvider.java
flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithDataTest.java
flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/TreeDataProviderTest.java

Fixes https://github.com/vaadin/vaadin-grid-flow/issues/819
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7327)

TreeDataProvider: Apply filters to children (2.1) (#7317)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java

Create temp package.json and
package-lock.json to get less
confusing output.
Log that a global install of pnpm
is suggested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7332)

Cleaner ouput for pnpm i

---

flow-client/.eslintrc.js
flow-client/scripts/client.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7341)

Disable linebreak-style eslint rule in flow-client

---

flow-data/src/main/java/com/vaadin/flow/data/selection/MultiSelectionEvent.java

Fixes #6756
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7346)

Deprecate getNewSelection method

---

flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7357)

Use headless chrome always, except on local debug

---

flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
flow-client/src/test/frontend/ConnectTests.ts
flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
flow-server/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
flow-server/src/test/java/com/vaadin/flow/component/UITest.java
flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
flow-server/src/test/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessCheckerTest.java

Use double cookie to prevent csrf attack
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7331)

Use double cookie to prevent csrf

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7362)

chore: remove unused constant

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7363)

chore: remove unused var, repace `var` with const/let

---

flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
flow-client/src/test/frontend/ConnectTests.ts
flow-client/src/test/frontend/FlowTests.ts
flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java

Fixes #7372
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7374)

CCDM: do not pollute Vaadin.Flow when setting csrfToken

---

flow-server/src/test/java/com/vaadin/flow/component/page/PageTest.java
flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java

Test that each deprecated method delegates to the appropriate regular
method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7359)

Add tests for deprecated execJs shorthands

---

flow-server/src/main/java/com/vaadin/flow/component/Direction.java
flow-server/src/main/java/com/vaadin/flow/component/internal/DeadlockDetectingCompletableFuture.java
flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7380)

Add @since version to new classes.

---

flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/AppShellSettings.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java

Fixes #7268
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7366)

CCDM: restore app-shell title in untitled server routes

---

flow-client/pom.xml
flow-data/src/main/java/com/vaadin/flow/data/selection/MultiSelectionEvent.java
flow-server/src/main/java/com/vaadin/flow/component/Direction.java
flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/main/java/com/vaadin/flow/component/internal/DeadlockDetectingCompletableFuture.java
flow-server/src/main/java/com/vaadin/flow/component/page/PendingJavaScriptResult.java
flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/ImportExtractor.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
flow-server/src/main/resources/webpack.generated.js
flow-server/src/test/java/com/vaadin/flow/component/UITest.java
flow-server/src/test/java/com/vaadin/flow/component/internal/PendingJavaScriptInvocationTest.java
flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/BundleParserTest.java
flow-server/src/test/java/com/vaadin/flow/internal/StringUtilTest.java
flow-server/src/test/java/com/vaadin/flow/server/MockVaadinSession.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
flow-server/src/test/java/com/vaadin/tests/util/MockUI.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7370)

[DO NOT SQUASH] Cherry picks to 2.1 branch from master

---

flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java

Fixes #7144
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7355)

Switch off audit for npm

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/InvisibleDefaultPropertyValueIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7358)

Update test ignore message with ticket number

---

flow-client/package.json
flow-client/pom.xml
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/ServiceInitEvent.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlResponse.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
flow-tests/pom.xml
flow-tests/test-ccdm/pom-production.xml
flow-tests/test-ccdm/pom.xml
flow-tests/test-dev-mode/pom.xml
flow-tests/test-npm-only-features/test-npm-no-buildmojo/pom.xml
flow-tests/test-router-custom-context/pom.xml

Fixes: 7336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7390)

CCDM: rename flag clientSideMode to useDeprecatedV14Bootstrapping

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java

Fixes vaadin/90min-dx-tasks#59
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7400)

Clarify that webpack may take a moment

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java

* Clarify that webpack may take a moment
Fixes vaadin/90min-dx-tasks#59
(cherry picked from commit 409a1d8b6bc6d4a450b52c56174a571568b34d65)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7404)

Clarify that webpack may take a moment (#7400) cherry-pick to 2.1

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java

* Clarify that webpack may take a moment
Fixes vaadin/90min-dx-tasks#59
(cherry picked from commit 409a1d8b6bc6d4a450b52c56174a571568b34d65)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7403)

Clarify that webpack may take a moment (#7400)  cherry-pick to 2.2

---

flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
flow-client/src/test/frontend/FlowTests.ts

Fixes #7394
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7402)

CCDM: fix isActive flag in flow client

---

flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/MigrateMojo.java
flow-migration/src/main/java/com/vaadin/flow/migration/Migration.java
flow-migration/src/main/java/com/vaadin/flow/migration/MigrationConfiguration.java
flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
flow-tests/test-mixed/pom-npm-production.xml
flow-tests/test-mixed/pom-npm.xml
flow-tests/test-mixed/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7411)

[Do not squash] Cherry picks to 2.2

---

flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7418)

Use true as the default value for pnpm.enable in dev mode

---

flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7421)

Use true as the default value for pnpm.enable in dev mode (#7418)

---

flow-server/src/test/java/com/vaadin/flow/component/internal/PendingJavaScriptInvocationTest.java

Fixes PendingJavaScriptInvocationTest which fails randomly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7415)

Fix a random fail test for 2.1 branch

---

flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/TestUtils.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/main/resources/com/vaadin/flow/server/frontend/index.html
flow-server/src/main/resources/webpack.generated.js
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
flow-tests/test-resources/src/main/resources/META-INF/resources/frontend/test-files/js/module1.js
flow-tests/test-resources/src/main/resources/META-INF/resources/frontend/test-files/js/module2.js
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/WebComponentsIT.java

remove webcomponents polyfill by default
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7416)

remove webcomponents polyfill by default

---

flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java

Fixes #7424
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7439)

Report Edge 18 and older as unsupported

---

flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/PushIT.java

Connected to #7347
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7449)

test: replace sleep by condition to avoid random failures in slow systems

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java

This fixes the UpdateThemedImportsTest that fails in windows
Connected to #7347
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7452)

Windows path needs to be normalized before comparing with theme url.

---

flow-server/src/main/java/com/vaadin/flow/component/ClickNotifier.java
flow-server/src/main/java/com/vaadin/flow/component/Focusable.java
flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
flow-server/src/main/java/com/vaadin/flow/component/Shortcuts.java
flow-server/src/main/java/com/vaadin/flow/component/UI.java
flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

Fix #6570
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7339)

Add varargs parameter to ShortcutRegistration.listenOn().

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7464)

upgrade ts version to 3.7.3

---

flow-client/pom.xml

Fixex #7468
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7470)

use npm when building flow-client

---

flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java

remove webpack-babel-multi-target-plugin
fixes #7409
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7475)

remove webpack-babel-multi-target-plugin

---

flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7476)

Rename user stat entry @vaadin/flow-frontend/Connect to endpoint

---

flow-server/src/main/java/com/vaadin/flow/router/internal/ConfiguredRoutes.java

Methods already exist in the class that do what this code is doing. Instead of repeating code, we should use existing methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7478)

Use existing methods instead of repeating code

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java

Make bootstrap exception note what mode
we are in when making the message.
Fixes #7384
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7480)

Do not try to handle empty stream

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java

Make bootstrap exception note what mode
we are in when making the message.
Fixes #7384
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7486)

Do not try to handle empty stream 2.1 (#7480)

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java

Make bootstrap exception note what mode
we are in when making the message.
Fixes #7384
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7485)

Do not try to handle empty stream 2.2 (#7480)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/test/java/com/vaadin/flow/server/connect/generator/TestUtils.java
flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGenerationTest.java
flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/json/JsonTestEndpointGeneratedTest.java
flow-server/src/test/java/com/vaadin/flow/server/connect/generator/openapi/OpenApiSpecBasedTests.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java

Connected to #7347
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7455)

test: fix ccdm tests in windows because of character issues

---

flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java

Fixes #3809
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7492)

Ignore duplicate message with a log, do not throw

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java

Fixes #7503
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7504)

Use npmVersion if it exists instead of jsVersion.

---

flow-server/pom.xml

Update jackson version to get security fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7487)

Update jackson version

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java

Fixes #7495
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7509)

Inform users that `prepare-frontend` may need to be run in the case of missing frontend files and no token file

---

flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
flow-client/src/test/frontend/ConnectTests.ts
flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
flow-server/src/main/java/com/vaadin/flow/server/connect/exception/EndpointException.java
flow-server/src/main/java/com/vaadin/flow/server/connect/exception/EndpointValidationException.java
flow-server/src/main/java/com/vaadin/flow/server/connect/exception/VaadinConnectValidationException.java
flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7471)

CCDM: rename VaadinConnectException -> EndpointException

---

flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/TypeScriptApiTemplate.mustache
flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/reservedwordmethod/ReservedWordMethodEndpointGenerationTest.java
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/collectionendpoint/expected-CollectionEndpoint.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/complexhierarchyendpoint/expected-ComplexHierarchyEndpoint.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/datetime/expected-DateTimeEndpoint.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/denyall/expected-DenyAllEndpoint.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/inheritedmodel/expected-InheritedModelEndpoint.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-GeneratorAnonymousAllowedTestClass.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-JsonTestEndpoint.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/model/expected-ComplexReturnTypeEndpoint.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/model/expected-ComplexTypeParamsEndpoint.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/model/expected-ModelEndpoint.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/modelpackage/expected-ModelPackageEndpoint.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/modelpackage/expected-SubModelPackageEndpoint.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/nullable/expected-NullableEndpoint.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/reservedwordmethod/expected-ReservedWordMethodEndpoint.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/sameclassname/expected-SameClassNameEndpoint.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/selfreference/expected-SelfReferenceEndpoint.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-FooBarEndpoint.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-default-class-no-tag.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-first-class-multiple-tags.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-multiple-lines-description.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-no-tsdoc.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-partly-tsdoc.ts
flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-second-class-multiple-tags.ts

Fixes #7460
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7518)

Allow using JS reserved words as endpoint method names

---

flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java

Fixes #7488
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7522)

CCDM: VaadinRequest is available in Endpoints

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java

Fixes ##7461
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7543)

Remove pnpm-lock.yaml file if npm is used

---

flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/ExportedJSFunctionView.java
flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/ExportedJSFunctionIT.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/TimingInfoReportedView.java

Fixes #7514
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7537)

CCDM: do not consider TypeScript client object in tests

---

flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
flow-server/src/main/java/com/vaadin/flow/router/Router.java
flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
flow-tests/test-dev-mode/pom.xml

implementation feature `InternalServerError` component in v15 handlers
fixes #7515
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7544)

implementation feature `InternalServerError` component in v15 handlers

---

flow-dnd/src/main/resources/META-INF/resources/frontend/dndConnector.js
flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
flow-test-util/src/main/resources/dnd-simulation.js
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DnDDisabledView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DnDView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DnDIT.java

(cherry picked from commit 73d1bd662e4ab39182c53c0f29f1c9a3eb7ae867)
Please don't merge this. I'm gonna test cherry-pick bot on it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7545)

Cheery-pick: Change UI behaviour of disabled DnD elems

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7554)

Update branches info

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java

Fixes #7561
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7568)

Make a method to access {user_home}/.vaadin directory.

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java

Fixes https://github.com/vaadin/flow/issues/7573
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7577)

Fix log info string format mismatch error

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java

Fixes #7560
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7569)

Use .vaadin folder from home folder to search node/npm binaries.

---

flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7597)

Remove usage of com.google.common.base.Supplier

---

drivers.xml
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7602)

test: update chromedriver and test to test: update chromedriver and test to 80.0.3987.106

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

Fixes #7593
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7604)

Don't remove pnpm-lock on node and npm validation

---

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

Fixes #7555
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7601)

Avoid calling mx bean to get a file name unique for JVM

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java

Fixes #7528
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7609)

Delete node_modules if it's structure doesn't match the current tool.

---

flow-server/src/main/java/com/vaadin/flow/internal/ReflectionCache.java
flow-server/src/test/java/com/vaadin/flow/internal/ReflectionCacheTest.java

Fixes #7549
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7613)

Keep a hard reference to ReflectionCache clear action

---

flow-server/src/main/resources/webpack.generated.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7615)

chore: not need to use the spread operator since array is filtered

---

drivers.xml
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7617)

Update chromedriver and test to 80.0.3987.106 (2.2) (#7602)

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java

Fixes #7563
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7605)

Force using node from vaadin  home folder

---

flow-server/pom.xml
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/ArchiveExtractionException.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/ArchiveExtractor.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DefaultArchiveExtractor.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloader.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DownloadException.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/FileDownloader.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/InstallationException.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/Platform.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/ProxyConfig.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/DefaultArchiveExtractorTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloaderTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
flow-server/src/test/java/com/vaadin/tests/server/component/FlowClassesSerializableTest.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

Add features fron eirslett plugin to
download and install node+npm
to the system to a target directory.
Fixes #7562
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7618)

Node and npm download and installation 2.2 (#7571)

---

flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementAttributeMap.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/StreamResourceView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AbstractStreamResourceIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java

* Fix the bug 
* Add IT tests for re-attaching a stream resource
Fixes #6478
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7627)

Update attribute value on attach

---

flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7629)

Disable failing on CI test and improve expected exception checks

---

flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java

Windows node executable is node.exe
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7630)

Fix test on windows.

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/ProxyConfig.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java

Fixes #7567
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7625)

Read proxy config from .npmrc file

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
flow-server/src/main/java/com/vaadin/flow/internal/ReflectionCache.java
flow-server/src/main/java/com/vaadin/flow/server/Constants.java
flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/ProxyConfig.java
flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/test/java/com/vaadin/flow/internal/ReflectionCacheTest.java
flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java

Don't squash
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7639)

Cherry picks for 2.2

---

flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/TestUtils.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/template/AttachExistingElementByIdView.java
flow-tests/test-lumo-theme/src/main/java/com/vaadin/flow/uitest/ui/lumo/ExplicitLumoTemplateView.java
flow-tests/test-material-theme/src/main/java/com/vaadin/flow/uitest/ui/material/MaterialThemedTemplateView.java
flow-tests/test-material-theme/src/main/java/com/vaadin/flow/uitest/ui/material/NotThemedTemplateView.java
flow-tests/test-mixed/src/main/java/com/vaadin/flow/mixedtest/ui/IdTestView.java
flow-tests/test-npm-only-features/test-npm-bytecode-scanning/src/main/java/com/vaadin/flow/testnpmonlyfeatures/bytecodescanning/MyButton.java
flow-tests/test-npm-only-features/test-npm-general/src/main/java/com/vaadin/flow/testnpmonlyfeatures/general/ComponentAddedViaInitListenerView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/InjectedElementInsideMixinBehaviorView.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityPanel.java
flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/template/RouterLinksTemplate.java
flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/NpmThemedComponentView.java

This reverts commit d6b7b41022a815e00afb3b8afe7b0d4b81cea098.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7640)

Revert "Remove polymer from default dependencies (#7558)"

---

flow-client/intern.json
flow-client/scripts/client.js

Fixes #7643
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7645)

Update chrome version for intern test in flow-client module

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7642)

Remove unused imports from BuildFrontendMojo

---

flow-server/src/main/java/com/vaadin/flow/server/Version.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7641)

Clarify that the version number if for Flow and not Vaadin

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java

Add logging for when we are
automatically installing node
and where it is installed.
Part of #6249
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7635)

Add logging for node install

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java

Add logging for when we are
automatically installing node
and where it is installed.
Part of #6249
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7654)

Add logging for node install 2.2 (#7635)

---

flow-server/pom.xml
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7657)

Removed org.apache.commons.text dependency 2.2 (#7599)

---

flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7659)

Ignore a test (which is ignored on master)

---

flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java

Fixes #7664
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7667)

Fix unit test

---

drivers.xml
flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7674)

Update chromedriver and test to 80.0.3987.106 (#7602)

---

flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7682)

Increase threshold for performance test

---

flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7692)

fix typo in var name during re-refactor that causes misfunction and IOOBE

---

flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
flow-client/src/test/frontend/FlowTests.ts
flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java

handle forward onBeforeEnter from java view in flow client api, not support onBeforeLeave
fixes #6490
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7672)

handle forward from java view in flow client api

---

flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
flow-client/src/main/java/com/vaadin/client/flow/StateTree.java
flow-client/src/main/java/com/vaadin/client/flow/TreeChangeProcessor.java
flow-client/src/main/java/com/vaadin/client/flow/binding/ServerEventObject.java
flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtStateTreeTest.java
flow-client/src/test/java/com/vaadin/client/flow/StateTreeTest.java
flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ResynchronizationView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ResynchronizationIT.java

Adapted for Flow 3.0 with different DOM structure (outlet as root).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7662)

Implement resynchronization of the client and server

---

flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShortcutsView.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShortcutsIT.java

* Fix problem with multiple listenOns of ShortcutRegisteration
* Add exceptions for duplicate and null components in listenOn components
(cherry picked from commit 1d92ac34740ff94747e4a7df162ba9fa4591a402)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7687)

Fix problem with multiple listenOns of ShortcutRegisteration (#7638)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java

Fix for #7620
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7690)

Search for versions file using class finder instead of using classloader

---

flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
flow-data/src/main/java/com/vaadin/flow/data/binder/ReadOnlyHasValue.java
flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataProvider.java
flow-data/src/main/java/com/vaadin/flow/data/renderer/NativeButtonRenderer.java
flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
flow-server/src/main/java/com/vaadin/flow/internal/ReflectionCache.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
flow-server/src/main/java/com/vaadin/flow/shared/GwtIncompatible.java
flow-server/src/main/java/com/vaadin/flow/shared/Registration.java
flow-server/src/test/java/com/vaadin/flow/shared/RegistrationTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7383)

Add registration creation shorthands

---

flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
flow-tests/test-lumo-theme/src/main/java/com/vaadin/flow/uitest/ui/lumo/ExplicitLumoTemplateView.java
flow-tests/test-lumo-theme/src/test/java/com/vaadin/flow/uitest/ui/lumo/AbstractThemedTemplateIT.java
flow-tests/test-lumo-theme/src/test/java/com/vaadin/flow/uitest/ui/lumo/ExplicitLumoTemplateIT.java

Fixes #7588
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7675)

Set theme variant and theme html attributes to the HTML tag instead of body

---

flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
flow-data/src/main/java/com/vaadin/flow/data/binder/ReadOnlyHasValue.java
flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataProvider.java
flow-data/src/main/java/com/vaadin/flow/data/renderer/NativeButtonRenderer.java
flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
flow-server/src/main/java/com/vaadin/flow/internal/ReflectionCache.java
flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
flow-server/src/main/java/com/vaadin/flow/shared/GwtIncompatible.java
flow-server/src/main/java/com/vaadin/flow/shared/Registration.java
flow-server/src/test/java/com/vaadin/flow/shared/RegistrationTest.java

(cherry picked from commit 7f803f9)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7698)

Add registration creation shorthands (#7383)

---

flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterIT.java

Fixes #7583
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7704)

fix navigation when route ends with slash

---

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java

Fixes #7626
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7666)

Use token file to write parameters for dev mode from maven config

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7710)

Create vaadin json with defaults. (#7697)

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java

Fix for #7620
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7712)

Search for versions file using class finder instead of using classloader (#7690)

---

.gitignore
flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java

Fixes #7581
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7707)

delay location.reload when session expires

---

flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java

Fixes #7623
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7691)

fix: add router-ignore attribute to Anchor with StreamResource

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InternalErrorIT.java

Fixes #7624
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7699)

Make session expired test stable

---

flow-server/src/main/resources/webpack.generated.js

- do not run watchdog if devMode is not set
- skip defining watchdog function if no port provided
- configure connect handlers before connecting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7720)

chore: re-factor webpack watchdog code.

---

flow-server/src/main/resources/webpack.generated.js

* chore: re-factor webpack watchdog code.
- do not run watchdog if devMode is not set
- skip defining watchdog function if no port provided
- configure connect handlers before connecting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7733)

Cheery pick 7720

---

.gitignore
flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java

Fixes #7581
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7731)

delay location.reload when session expires (#7707)

---

flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7732)

7673, 7692, 7693 3.0 cherry pick

---

flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java

fix: add router-ignore attribute to Anchor with StreamResource (#7691)
Fixes #7623
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7730)

7691 3.0 cherry pick

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7688)

Update branches in Readme

---

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InternalErrorIT.java

Fixes #7624
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7726)

Reset system message provider before running any test

---

flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java

Fix #7542
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7709)

Fix the dependency of DevModeInitializer on ServletRegistration

---

flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ForwardToIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SetParameterForwardToIT.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/PushRouteNotFoundIT.java

fixes #7578
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7719)

handle forward between server-side views and also update url

---

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
flow-server/src/main/resources/webpack.generated.js
flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
flow-server/src/test/resources/InvalidStats.json
flow-server/src/test/resources/META-INF/VAADIN/config/stats.json
flow-server/src/test/resources/MissFormatStats.json
flow-server/src/test/resources/ValidStats.json
flow-tests/test-embedding/pom.xml
flow-tests/test-multi-war/pom.xml

Fixes #7550
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7748)

7614 3.0 cherry-pick

---

flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InternalErrorIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7749)

7739 3.0 cherry-pick

---

flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java

This should fix MPR validation builds
-  https://bender.vaadin.com/viewType.html?buildTypeId=Flow_MultiplaformRuntime_Mpr&branch_Flow_MultiplaformRuntime=366&tab=buildTypeStatusDiv
- https://bender.vaadin.com/viewType.html?buildTypeId=Flow_MultiplaformRuntime_MprSnapshots_Mpr20Snapshot 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7747)

be more specific when modifying the hash fragment rpc

---

flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java

* be more specific when modifying v7 uidl hash fragment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7750)

7747 3.0 cherry-pick

---

flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
flow-tests/test-lumo-theme/src/main/java/com/vaadin/flow/uitest/ui/lumo/ExplicitLumoTemplateView.java
flow-tests/test-lumo-theme/src/test/java/com/vaadin/flow/uitest/ui/lumo/ExplicitLumoTemplateIT.java

Fixes #7588
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7715)

Set theme variant and theme html attributes to the HTML tag instead of

---

pom.xml

Update the formatter plugin to
a version that can handle multi
module projects and format
all sub modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7695)

Update formatter plugin

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java

This reverts commit 7f8a00f52dbc667af7571ceef227c5de49e8ba78.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7734)

Revert "Remove FrontendUtils.getBowerExecutable()  (#7701)"

---

flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
flow-server/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
flow-server/src/test/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessCheckerTest.java
flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/BaseTypeConversionIT.java
flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java

Fixes #7525
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7737)

Do not run endpoints csrf check when disable-xsrf-protection flag is set

---

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7777)

Update dev dependency versions.

---

flow-test-util/src/main/java/com/vaadin/flow/testcategory/PushTests.java
flow-tests/pom.xml

Part of #7775
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7778)

Move push tests category to test util module, exclude Push tests
