vaadin/flow

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Fixes #7768
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7779)
=> Update dev dependency versions. (#7777)

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
Fixes #7768
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7781)
=> Update web-pack version

.gitignore, flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java
This reverts commit 5e30ca403c44f33085f1deaef8f646d1186851eb.
The mentioned commit results in an endless loop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7795)
=> Revert "delay location.reload when session expires (#7707) (#7731)"

flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PushWithPreserveOnRefreshView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PushWithPreserveOnRefreshIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7796)
=> Correct push with preserve on refresh test.

flow-server/src/main/java/com/vaadin/flow/component/page/BodySize.java, flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java, flow-server/src/main/resources/com/vaadin/flow/server/frontend/index.html, flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Fixes #7611
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7788)
=> Change default 100vw to 100% body size settings.

flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Fixes #7510
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7803)
=> Backport disable audit for npm

flow-server/src/main/java/com/vaadin/flow/component/page/BodySize.java, flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java, flow-server/src/main/resources/com/vaadin/flow/server/frontend/index.html, flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Fixes #7611
Co-authored-by: Haijian Wang <30408303+haijian-vaadin@users.noreply.github.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7807)
=> Change default 100vw to 100% body size settings. (#7788)

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
Fixes #7800
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7815)
=> Accept only major version String in FrontendVersion CTOR

flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/push/PushWithRequireJSUI.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7812)
=> Use absolute URI for require JS

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Fixes #7768
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7780)
=> Cherry pick for dev dep versions update (#7768)

flow-data/src/main/java/com/vaadin/flow/data/binder/HasDataProvider.java, flow-data/src/main/java/com/vaadin/flow/data/binder/HasFilterableDataProvider.java, flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataProvider.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataProviderTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/HasDataProviderTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/HasFilterableDataProviderTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/WildcardDataProvider.java, flow-data/src/test/java/com/vaadin/flow/tests/data/DataSerializableTest.java
Implementation of #6617
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7652)
=> Accept setting DataProvider of subclasses (#6617)

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
Fixes #7800
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7816)
=> Accept only major version String in FrontendVersion CTOR (#7815)

flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java, flow-server/src/test/java/com/vaadin/flow/router/internal/RouteUtilTest.java
Related to #7794 #7792. Extracted this functionality into internal package for reuse.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7809)
=> Added internal methods for updating routes when classes are added / modified / deleted

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java, flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java, flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java, flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
Fixes #7773
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7824)
=> Don't store optimize bundle in dev mode in the token file.

flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7842)
=> Removed dead code (pre 3)

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7853)
=> Upgrade the Jetty Maven Plugin version

flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateOpenApiTest.java, flow-server/src/test/resources/java/CustomEndpoint.java, flow-server/src/test/resources/java/EndpointNoValue.java
fixes #7671
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7765)
=> let TS generator detect custom endpoint name

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java, flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java, flow-server/src/main/java/com/vaadin/flow/server/Constants.java, flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java, flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Fixes #7771
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7849)
=> Extract frontend executable functionality to a separate contextual class.

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7857)
=> Don't catch Exception

flow-server/src/test/java/com/vaadin/flow/component/UITest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7828)
=> Add a unit test for #5411

flow-test-util/src/main/java/com/vaadin/flow/testutil/ViewOrUITest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7839)
=> Do not spam console with misleading test exceptions

flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java, flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
7827-3.0-cherry-pick
cherry-pick #7827 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7865)
=> 7827-3.0-cherry-pick

flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateOpenApiTest.java, flow-server/src/test/resources/java/CustomEndpoint.java, flow-server/src/test/resources/java/EndpointNoValue.java
7765-3.0-cherry-pick
cherry-pick #7765
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7866)
=> 7765-3.0-cherry-pick

flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/push/ReconnectLongPollingIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7879)
=> Disable failing test because of #7878.

flow-server/src/main/java/com/vaadin/flow/server/frontend/JarContentsManager.java
Fixes #7855
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7880)
=> Clean up temp file if not used.

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java, flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java, flow-migration/src/main/java/com/vaadin/flow/migration/Migration.java, flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java, flow-server/src/main/java/com/vaadin/flow/server/Constants.java, flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java, flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
class. (#7849)
Fixes #7771
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7881)
=> Extract frontend executable functionality to a separate contextual

flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java, flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java, flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java
Prints clear indication to the user that the application can be opened
in the browser.
Cleans up output from DefaultDeploymentConfiguration and tweaks when/how
user is warned when necessary.
Fixes #7762
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7872)
=> Let user know when application is deployed

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/resources/webpack.generated.js, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Fixes https://github.com/vaadin/flow/issues/7841
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7873)
=> Fix regression in progress plugin after upgrading webpack version

flow-server/src/main/java/com/vaadin/flow/server/frontend/JarContentsManager.java
Fixes #7855
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7889)
=> Clean up temp file if not used. 3.0 (#7880)

flow-server/src/main/java/com/vaadin/flow/server/frontend/JarContentsManager.java
Fixes #7855
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7890)
=> Clean up temp file if not used. 2.2 (#7880)

flow-server/src/main/java/com/vaadin/flow/server/frontend/JarContentsManager.java
Fixes #7855
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7891)
=> Clean up temp file if not used. 2.1 (#7880)

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/resources/webpack.generated.js
Fix regression in progress plugin after upgrading webpack version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7895)
=> 7873 3.0 cherry-pick

flow-jrebel-plugin/src/main/java/com/vaadin/flow/server/jrebel/JRebelClassEventListener.java, flow-jrebel-plugin/src/main/java/com/vaadin/flow/server/jrebel/JRebelInitializer.java, flow-jrebel-plugin/src/test/java/com/vaadin/flow/server/jrebel/JRebelInitializerTest.java
Fixes #7875
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7887)
=> Do not crash if JRebel is not on classpath

flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java, flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java, flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java, flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java
Prints clear indication to the user that the application can be opened
in the browser.
Cleans up output from DefaultDeploymentConfiguration and tweaks when/how
user is warned when necessary.
Fixes #7762
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7898)
=> Let user know when application is deployed (#7872)

flow-client/src/main/java/com/vaadin/client/LiveReload.java, flow-client/src/main/java/com/vaadin/client/StorageUtil.java, flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadIT.java
Closes #7834.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7886)
=> Added toggle for live-reload on a per-window basis

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Fixes #7684
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7894)
=> Install pnpm into vaadin home folder (#7863)

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
Collect lines from error until
a empty line or i (information) line marker.
Fixes #7833
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7882)
=> Collect all error lines

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7905)
=> CP: Update vaadin-parent-2.0.2 (#7843)

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
Collect lines from error until
a empty line or i (information) line marker.
Fixes #7833
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7912)
=> Collect all error lines 2.1 (#7882)

flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RedirectToPushView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/routing/PushRouteNotFoundView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RedirectToPushIT.java
Fixes #5759
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7838)
=> Apply push setting after navigation

flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java, flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java, flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7917)
=> Add stats for pnpm usage

flow-data/src/main/java/com/vaadin/flow/data/binder/HasDataProvider.java, flow-data/src/main/java/com/vaadin/flow/data/binder/HasFilterableDataProvider.java, flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataProvider.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataProviderTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/HasDataProviderTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/HasFilterableDataProviderTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/WildcardDataProvider.java, flow-data/src/test/java/com/vaadin/flow/tests/data/DataSerializableTest.java
Fixes #6617
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7825)
=> CP: Accept setting DataProvider of subclasses (#6617) (#7652)

flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java, flow-server/src/test/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
Fixes #3865
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7870)
=> Validate Route and ParentLayout annotations presence at the same time

flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java, flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7921)
=> Disable live reload on the client side temporary

flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java, flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java, flow-client/src/main/java/com/vaadin/client/LiveReload.java, flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java, flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java, flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReload.java, flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadAccess.java, flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, flow-server/src/main/java/com/vaadin/flow/server/Constants.java, flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java, flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java, flow-server/src/test/java/com/vaadin/flow/internal/BrowserLiveReloadAccessTest.java, flow-server/src/test/java/com/vaadin/flow/server/AbstractDeploymentConfigurationTest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java, flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java, flow-tests/pom.xml, flow-tests/test-dev-mode/pom.xml, flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadIT.java, flow-tests/test-root-context/pom.xml, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DevModeConfigView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/EmptyPageView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DevModeConfigIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/EmptyPageIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/EmptyListsIT.java, pom.xml
Fix #7874
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7884)
=> Add liveReload.enabled config parameter to enable/disable Live Reload

flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/startup/AnnotationValidator.java, flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/startup/ErrorNavigationTargetInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/startup/FixedServletContainerInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/startup/ServletVerifier.java, flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentExporterAwareValidator.java, flow-server/src/test/java/com/vaadin/flow/server/startup/AnnotationValidatorTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java, flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/ServletContainerInitializerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/WebComponentExporterAwareValidatorTest.java, flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassFinder.java, flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Fixes #7805
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7904)
=> Make a workaround for skinnywar/Wildfly

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7951)
=> Lock terser version to 4.6.7

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7956)
=> Lock terser version to 4.6.7 (#7951)

flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7954)
=> Cherry picks for 2.1.7

.gitignore, flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java
This reverts commit 94098e337acbec700d3a9dd9e9b0d4b5af03fea0.
Fixes https://github.com/vaadin/flow/issues/7581
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7910)
=> Revert: "Revert 'delay location.reload (#7707)' (#7789)"

flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java, flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java, flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
Fixes #7851
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7946)
=> link to documentation when PWA annotation is misplaced

pom.xml
Fixes #7918
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7949)
=> Upgrade byte buddy dependency

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java, flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java, flow-server/src/main/java/com/vaadin/flow/server/Constants.java, flow-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7945)
=> Switch pnpm to be default for 3.1

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java, flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java, flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java, flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java, flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
fixes #7926
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7950)
=> remove flowResourcesFolder parameter in FlowModeAbstractMojo

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java, flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java, flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7953)
=> Remove extra code

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java, flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Fixes #7764
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7980)
=> CP: Output commands using logger with debug level only (#7852)

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
Cherry pick PR do not squash!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7986)
=> 2.1 cherry pick PR

.gitmodules
Adds the combo-box dataprovider
feature branch as a submodule.
part of #7966
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7992)
=> Add combo-box submodule

flow-server/pom.xml, flow-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7997)
=> Temporary disable ITs to speed up client developing

flow-client/src/main/java/com/vaadin/client/LoadingIndicator.java, flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts, flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts, flow-client/src/test/frontend/ConnectTests.ts, flow-client/src/test/frontend/FlowTests.ts
Fixes #7505
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7975)
=> Show flow loading indicator when requesting server routes and endpoints

flow-server/src/main/java/com/vaadin/flow/server/startup/AnnotationValidator.java, flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/startup/ConnectEndpointsValidator.java, flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/startup/ErrorNavigationTargetInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/startup/ServletVerifier.java, flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentExporterAwareValidator.java, flow-server/src/test/java/com/vaadin/flow/server/startup/AnnotationValidatorTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/ConnectEndpointsValidatorTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java, flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/ServletContainerInitializerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/WebComponentExporterAwareValidatorTest.java, flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassFinder.java, flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Fixes #7805
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7952)
=> Make a workaround for skinnywar/Wildfly (#7904)

flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8003)
=> Fix compile error in DevModeInitializerTest

flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java, flow-theme-integrations/material/src/main/java/com/vaadin/flow/theme/material/Material.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8002)
=> Update lumo and material styles for v16

flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js, flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadView.java, flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadIT.java
Fixes  #8004.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8005)
=> Close websocket connection when disabling live reload

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Added cleanup for vaadinAppPackageHash
which is not used anymore.
Closes #8007
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8011)
=> Add tests for package cleaning

flow-maven-plugin/src/main/resources/yarn.lock, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java, pom.xml
Do not squash,
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7987)
=> 2.2 cherrypick pr.

flow-client/src/main/java/com/vaadin/client/LoadingIndicator.java, flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts, flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts, flow-client/src/test/frontend/ConnectTests.ts, flow-client/src/test/frontend/FlowTests.ts, flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java, flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java, flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfigurationTest.java, flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8023)
=> 7975 8016 3.0 cherry-pick

flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts, flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.d.ts, flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js, flow-jrebel-plugin/pom.xml, flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReload.java, flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadAccess.java, flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadImpl.java, flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, flow-server/src/test/java/com/vaadin/flow/internal/BrowserLiveReloadImplTest.java, flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
Fixes #7845.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8015)
=> Identify live reload backend technology on the server and show in browser

flow-server/src/main/java/com/vaadin/flow/component/Direction.java, flow-server/src/main/java/com/vaadin/flow/component/UI.java, flow-server/src/main/java/com/vaadin/flow/i18n/LocaleChangeEvent.java, flow-server/src/test/java/com/vaadin/flow/component/LocationObserverTest.java, flow-server/src/test/java/com/vaadin/flow/component/UITest.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DirectionChangeView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DirectionChangeIT.java
Fixes #8021
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8024)
=> Add UI.setDirection API

flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8042)
=> Increase Chrome version

flow-server/src/main/resources/com/vaadin/flow/server/dev-mode-not-ready.html
Fixes #7962
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8057)
=> Style dev mode waiting page

flow-server/src/main/resources/webpack.generated.js
Add chunks also to production stats.
Fixes #8053
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8056)
=> Add more data to stats.json

flow-server/src/main/resources/com/vaadin/flow/server/dev-mode-not-ready.html, flow-server/src/main/resources/webpack.generated.js
merge not squash!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8058)
=> 3.1 cherry picks

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java, flow-server/src/main/resources/webpack.generated.js, flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java, pom.xml
Merge not squash!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8059)
=> 3.0 cherry picks

flow-tests/test-root-context/pom.xml, flow-tests/test-root-context/src/test/java/com/vaadin/flow/StatsContentTest.java
Validate that all parts wanted
for stats.json are found.
Fixes #8061
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8069)
=> Add stats.json content validation

flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8080)
=> Devmode gizmo: Do not use href target "#" to avoid topscroll and redirect

flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java, flow-server-compatibility-mode/pom.xml, flow-server/src/main/resources/webpack.generated.js, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java, flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/FrontendProtocolIT.java, flow-tests/test-embedding/embedding-test-assets/src/main/java/com/vaadin/flow/webcomponent/servlets/AbstractPlainServlet.java, flow-tests/test-embedding/test-embedding-theme-variant-compatibility/src/test/java/com/vaadin/flow/webcomponent/ThemedVariantComponentIT.java, flow-tests/test-misc/pom-bower.xml, flow-tests/test-root-context/pom.xml, flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/AbstractFrontendInlineIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/AnnotatedFrontendInlineIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/DependenciesLoadingAnnotationsIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/FrontendInlineApiIT.java, flow-theme-integrations/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8082)
=> Cp/test 2.2

flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts, flow-server/src/main/java/com/vaadin/flow/router/Location.java, flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java, flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RequestParametersHistoryView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RequestParametersHistoryIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RequestParametersIT.java
fixed #7589
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7994)
=> query parameters should be decoded in server

flow-server-compatibility-mode/pom.xml, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java, flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/FrontendProtocolIT.java, flow-tests/test-embedding/embedding-test-assets/src/main/java/com/vaadin/flow/webcomponent/servlets/AbstractPlainServlet.java, flow-tests/test-embedding/test-embedding-theme-variant-compatibility/src/test/java/com/vaadin/flow/webcomponent/ThemedVariantComponentIT.java, flow-tests/test-misc/pom-bower.xml, flow-tests/test-root-context/pom.xml, flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/AbstractFrontendInlineIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/AnnotatedFrontendInlineIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/DependenciesLoadingAnnotationsIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/FrontendInlineApiIT.java, flow-theme-integrations/pom.xml, pom.xml
Fix java 14 compatibility.
Fix htmlImport problems.
No squash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8103)
=> 2.1 cherry picks

flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Fix #8088
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8099)
=> Explicitly set the direction of the devmode gizmo to LTR

flow-client/.eslintrc.js, flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js, flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java, flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadIT.java, flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/PreserveOnRefreshLiveReloadIT.java
Integrated theme update from @juuso-vaadin and link to documentation. Added support for multiple persistently dismissable notifications.
Fixes #8077.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8116)
=> Live reload: Theme update and improved notification system

flow-client/src/main/resources/META-INF/resources/frontend/Binder.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8124)
=> Remove Constraint in favor of Validator

flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiAccess.java, flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
Fixes #8109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8128)
=> Return back code which has been accidentally removed.

flow-client/package.json, flow-client/src/main/resources/META-INF/resources/frontend/FormValidator.ts, flow-client/src/test/frontend/FormValidatorTests.ts, flow-client/webpack.tests.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8008)
=> Adding FormValidator library for client forms

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PushRouteNotFoundIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8134)
=> Disable new Push tests in OSGI

flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Animate notifications when dismissed / timed out.
Changed text of button from "Dismiss" to "Don't show again" to correctly describe behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8143)
=> Tuned live-reload gizmo (from @juuso-vaadin)

flow-client/src/main/resources/META-INF/resources/frontend/Binder.ts, flow-client/src/test/frontend/FormValidatorTests.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8152)
=> Export Required class

flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java, flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8154)
=> AnyModel does not exist, use ObjectModel instead

flow-client/src/main/resources/META-INF/resources/frontend/Binder.ts, flow-client/src/main/resources/META-INF/resources/frontend/FormValidator.ts, flow-client/src/test/frontend/FormValidatorTests.ts, flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java, flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache, flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java, flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8159)
=> Generate Validations for Models

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java, flow-server/src/main/resources/pnpmfile.js, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java, flow-server/src/test/resources/versions/no_vaadin_package.json, flow-server/src/test/resources/versions/package.json, flow-server/src/test/resources/versions/user_package.json, flow-server/src/test/resources/versions/user_versions.json, flow-server/src/test/resources/versions/versions.json
If package.json version
has been set to newer than
versions.json says then we
should not touch the file.
Fixes #8108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8160)
=> Accept user versions

flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java, flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java, flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java, flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java, flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts, flow-client/src/test/frontend/FlowTests.ts, flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
Fixes #8107
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8180)
=> Adding a separated flag for client-routing

flow-client/src/main/resources/META-INF/resources/frontend/FormValidator.ts, flow-client/src/test/frontend/FormValidatorTests.ts, flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache
fixes #8208
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8211)
=> fix ts compilation because of unused imports

flow-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
Remove mistakenly added goal target
Fixes #8033
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8207)
=> Remove duplicate plugin execution

flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8216)
=> fix ts error when there is nothing used in an import

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8225)
=> pin @vaadin/router to a specific version

flow-client/src/main/resources/META-INF/resources/frontend/Binder.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8229)
=> Fix required constrain and return the saved item

pom.xml, settings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8165)
=> Enable vaadin-prerelease for snapshot

flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Fixes #8174.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8215)
=> Added "Vaadin Development Mode" to development gizmo header to clarify it's not a production mode feature

flow-dev-deps/pom.xml, flow-dev-deps/src/test/java/com/vaadin/flow/devdeps/DevDepsFileTest.java, flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/LockDepDepVersionsMojo.java, flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/LockDevDepVersionsMojo.java, flow-server/pom.xml, flow-server/src/main/java/com/vaadin/flow/internal/BuildUtil.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java, flow-server/src/main/resources/build.properties, flow-server/src/main/resources/pnpmfile.js, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java, flow-server/src/test/resources/versions/no_vaadin_package.json, flow-server/src/test/resources/versions/package.json, flow-server/src/test/resources/versions/user_package.json, flow-server/src/test/resources/versions/user_versions.json, flow-server/src/test/resources/versions/versions.json, flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java, flow-tests/pom.xml, flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java, flow-tests/test-mixed/pom-pnpm-production.xml, pom.xml
Fixes #7958
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8197)
=> Lock dev dependencies via new module with generated versions file

flow-client/src/test/frontend/BinderTests.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8232)
=> test: add tests for validator api

flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
Fixes #8149
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8233)
=> Don't throw an exception if servlet class can't be loaded

flow-client/README.md, flow-client/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8250)
=> run webpack in watch mode and in background when debugging intern tests

flow-client/src/main/resources/META-INF/resources/frontend/Binder.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8239)
=> run field validation on blur

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8252)
=> pin vaadin router to a specific version (#8225)

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
Fixes #8231 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8253)
=> fix: clean up connect tokens in build info for production

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java, flow-server/src/main/java/com/vaadin/flow/server/PWA.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java, flow-server/src/main/resources/pnpmfile.js, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java, flow-server/src/test/resources/versions/no_vaadin_package.json, flow-server/src/test/resources/versions/package.json, flow-server/src/test/resources/versions/user_package.json, flow-server/src/test/resources/versions/user_versions.json, flow-server/src/test/resources/versions/versions.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8244)
=> Cherry-picks for 2.2.0.rc1

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexHtml.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8230)
=> Use current class to get resource instead getClass

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BackButtonServerRoundTripIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FragmentLinkIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/MultipleAnchorsIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/ScrollIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8257)
=> Update router version and related tests

flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java, flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java, flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java, flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java, flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts, flow-client/src/test/frontend/FlowTests.ts, flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8263)
=> 8180 3.0 cherry-pick

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java, flow-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java, flow-server/src/main/resources/pnpmfile.js, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java, flow-server/src/test/resources/versions/no_vaadin_package.json, flow-server/src/test/resources/versions/package.json, flow-server/src/test/resources/versions/user_package.json, flow-server/src/test/resources/versions/user_versions.json, flow-server/src/test/resources/versions/versions.json, flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BackButtonServerRoundTripIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FragmentLinkIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/MultipleAnchorsIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/ScrollIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8266)
=> 3.0 cherry pick

pom.xml, settings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8260)
=> Enable vaadin-prerelease for snapshot (#8165)

flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
It was accidentally merged via #8125.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8273)
=> Remove invalid test from RouterTest

flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Fixes #8234
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8284)
=> Live-reload: slider disabled mode styling

flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java, flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java, flow-dev-deps/pom.xml, flow-dev-deps/src/test/java/com/vaadin/flow/devdeps/DevDepsFileTest.java, flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/LockDevDepVersionsMojo.java, flow-server/pom.xml, flow-server/src/main/java/com/vaadin/flow/internal/BuildUtil.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java, flow-server/src/main/resources/build.properties, flow-server/src/main/resources/pnpmfile.js, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java, flow-server/src/test/resources/versions/no_vaadin_package.json, flow-server/src/test/resources/versions/package.json, flow-server/src/test/resources/versions/user_package.json, flow-server/src/test/resources/versions/user_versions.json, flow-server/src/test/resources/versions/versions.json, flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java, flow-tests/pom.xml, flow-tests/test-mixed/pom-pnpm-production.xml, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DirectionChangeView.java, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8281)
=> Cherry picks 2.3

flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java, flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java, flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java, flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java, flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts, flow-client/src/test/frontend/FlowTests.ts, flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java, flow-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java, flow-server/src/main/resources/webpack.generated.js, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java, flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BackButtonServerRoundTripIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FragmentLinkIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/MultipleAnchorsIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/ScrollIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8265)
=> 3.1 cherry pick

flow-client/src/main/resources/META-INF/resources/frontend/Binder.ts, flow-client/src/test/frontend/BinderModels.ts, flow-client/src/test/frontend/BinderTests.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8277)
=> run validators on submit

flow-server/src/main/java/com/vaadin/flow/component/internal/DeadlockDetectingCompletableFuture.java
Fixes #8302
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8312)
=> Clarify message about blocking with the session locked

flow-client/src/main/resources/META-INF/resources/frontend/Binder.ts, flow-client/src/test/frontend/BinderModels.ts, flow-client/src/test/frontend/BinderTests.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8288)
=> run validations in parallel, return error objects

flow-client/src/main/resources/META-INF/resources/frontend/Binder.ts, flow-client/src/test/frontend/BinderModels.ts, flow-client/src/test/frontend/BinderTests.ts, flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java, flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java, flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java, flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java, flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8317)
=> fix required in generator, and skip validations if not required

flow-dev-deps/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8306)
=> Correct project version

flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java, flow-server/src/test/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerTest.java
Fixes #8238
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8316)
=> fix: check for TypeVariable in the ExplicitNullableTypeChecker

flow-client/src/main/resources/META-INF/resources/frontend/Binder.ts, flow-client/src/test/frontend/BinderTests.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8326)
=> translate server validation errors to client validation form errors

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshIT.java
Fixes https://bender.vaadin.com/viewType.html?buildTypeId=Flow_Flow22_Flow22Snapshot
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8327)
=> Wait for intermediate page to load completely in @PreserveOnRefresh IT

flow-client/src/test/frontend/BinderModels.ts, flow-client/src/test/frontend/BinderTests.ts
fixes #7933
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8331)
=> adding more tests for adding validators to models

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8264)
=> Cherry pick to 2.2.0

flow-client/src/main/resources/META-INF/resources/frontend/Binder.ts, flow-client/src/test/frontend/BinderTests.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8343)
=> validationErrorData is not one error but an array of errors

flow-client/pom.xml, flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java, flow-client/src/main/java/com/vaadin/client/ExecuteJavaScriptElementUtils.java, flow-client/src/main/java/com/vaadin/client/ScrollPositionHandler.java, flow-client/src/main/java/com/vaadin/client/flow/ExecuteJavaScriptProcessor.java, flow-client/src/main/java/com/vaadin/client/flow/RouterLinkHandler.java, flow-server/src/main/java/com/vaadin/flow/component/UI.java, flow-server/src/main/java/com/vaadin/flow/router/ErrorNavigationEvent.java, flow-server/src/main/java/com/vaadin/flow/router/NavigationEvent.java, flow-server/src/main/java/com/vaadin/flow/router/NavigationTrigger.java, flow-server/src/main/java/com/vaadin/flow/router/Router.java, flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java, flow-server/src/main/java/com/vaadin/flow/router/internal/InternalRedirectHandler.java, flow-server/src/test/java/com/vaadin/flow/component/UITest.java, flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java, flow-server/src/test/java/com/vaadin/flow/router/internal/ErrorStateRendererTest.java, flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/NavigationTriggerView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PostponeProceedView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RouterLinkView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/NavigationTriggerIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PostponeProceedIT.java, flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8342)
=> Cherry pick from 2.1 to 2.2

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
Minor refactoring away of an unnecessary intermediate private method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8357)
=> Remove unnecessary intermediate private method in BootstrapHandler

flow-client/src/main/resources/META-INF/resources/frontend/form/Form.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/Validation.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/index.ts, flow-client/src/test/frontend/BinderModels.ts, flow-client/src/test/frontend/BinderTests.ts, flow-client/src/test/frontend/FormValidatorTests.ts, flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java, flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache, flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Fix regression introduced in https://github.com/vaadin/flow/pull/8347 because moustache template were not updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8362)
=> fix forms package import in generated models 

flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java, flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java, flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8363)
=> fix boolean types in model generator, and fix broken test

flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts, flow-client/src/test/frontend/BinderTests.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8360)
=> feat: add binder.clear() method

flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts, flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java, flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java, flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8372)
=> Fix primitive model names (string|number|boolean) for arrays

flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts, flow-client/src/test/frontend/BinderTests.ts
Fixes #8291 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8367)
=> add default onchange listener & BinderConfig

flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java, flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java, flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java, flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshReAddView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshReAddIT.java
Fixes #8286
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8365)
=> Close UI after refreshing the page in PreserveOnRefresh case and mark it

flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
AbstractListDataView unit test added for [141](https://github.com/vaadin/vaadin-checkbox-flow/issues/141)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8374)
=> Take DataView concept into use for CheckboxGroup #141

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8369)
=> Grid support methods

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Added to ListDataView the possibility
to addItem(T) and removeItem(T)
Fixes #8382
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8394)
=> Add list modification methods

flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
Fixes #8320
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8392)
=> Correct Javadocs for adding JS and Stylesheets programatically.

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Part of #8351
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8406)
=> Remove lit-element from default dev dependencies (#8351)

flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java, flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshShortcutView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshShortcutIT.java
Fixes #8247
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8391)
=> Listen detach events on "listenOn" components in shortcut registration

flow-client/package.json, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Part of #8351
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8414)
=> Remove lit-element from flow-client (#8351)

flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8417)
=> Update chrome version to 83

.gitmodules, flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Move some reusable code to abstract class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8422)
=> Add select submodule

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Added method to add
item before or after another item.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8429)
=> New add item methods

flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8441)
=> Update chrome version to 83 (#8417)

flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java, flow-client/src/test-gwt/java/com/vaadin/client/GwtSuite.java, flow-client/src/test-gwt/java/com/vaadin/client/communication/GwtAtmoshperePushConnectionTest.java
Related to #8177
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8330)
=> Fix issue with Push unsubscribe URL.

flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java, flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/PushView.java, flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RedirectToPushIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8444)
=> 8435 3.1 cherry-pick

flow-server/src/main/java/com/vaadin/flow/router/ParameterDeserializer.java, flow-server/src/test/java/com/vaadin/flow/router/ParameterDeserializerTest.java
Fixes #8371
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8431)
=> Workaround a bug in the external reflection library.

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Fixes #8434.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8452)
=> Force pnpm version >=4.4.0, <4.6.0

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Fixes #8434
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8455)
=> Force pnpm version >=4.4.0, <4.6.0 (#8452)

flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java, flow-server/src/main/java/com/vaadin/flow/server/Constants.java, flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java, flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java, flow-tests/pom.xml
Fixes #8447
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8449)
=> Throw immediately on finding AppShell annotation on non AppShell classes

flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Fixes #8460
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8470)
=> Set z-index to all direct children of vaadin-devmode-gizmo's shadow DOM root

flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts, flow-client/src/test/frontend/form/FieldTests.ts
Fixes #8389
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8459)
=> Allow that user can override strategies in binder

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/resources/pnpmfile.js
Fixes #8432
Fixes #8411
Fixes #8278
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8473)
=> Force chokidar version to ^3.4.0 (#8432) (#8451)

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Added the addFilter and clearFilters
methods.
Fixes #8313
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8479)
=> Add methods for filtering

drivers.xml, flow-client/intern.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8407)
=> Update chrome driver to 83.0.4103.39

flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8484)
=> Updated doclink for live-reload

flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java, flow-server/src/test/java/com/vaadin/flow/function/DeploymentConfigurationTest.java, flow-tests/test-mixed/src/main/java/com/vaadin/flow/mixedtest/ui/NavigateToStyled.java, flow-tests/test-mixed/src/main/java/com/vaadin/flow/mixedtest/ui/StyledDiv.java, flow-tests/test-mixed/src/main/webapp/frontend/css/styles.css, flow-tests/test-mixed/src/test/java/com/vaadin/flow/mixedtest/ui/NavigateToStyledIT.java
Fixes #8292
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8465)
=> Do not use compatibility mode production frontend prefixes without compat mode

flow-client/src/main/java/com/vaadin/client/flow/ExecuteJavaScriptProcessor.java, flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java, flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java, flow-server/src/main/java/com/vaadin/flow/component/page/Page.java, flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java, flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java, flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/main/java/com/vaadin/flow/server/startup/NavigationTargetFilter.java, flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java, flow-server/src/test/java/com/vaadin/flow/component/page/PageTest.java, flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java, flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java, flow-server/src/test/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java, flow-tests/test-root-context/frontend/HiddenTemplate.js, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshReAddView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshShortcutView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RemoveAddVisibilityView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/HiddenTemplateView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshReAddIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshShortcutIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RemoveAddVisibilityIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/HiddenTemplateIT.java
no squash.
fixes chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8439)
=> Cherry picks 3.0

flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java, flow-server/src/test/java/com/vaadin/flow/router/RouterLinkTest.java
Fixes #7634
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8472)
=> Throw IAE if navigation target is not registered via Router

flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/Validation.ts, flow-client/src/test/frontend/form/BinderTests.ts, flow-client/src/test/frontend/form/FieldTests.ts, flow-client/src/test/frontend/form/ModelTests.ts, flow-client/src/test/frontend/form/TestModels.ts, flow-client/src/test/frontend/form/ValidationTests.ts
There was a leftover commit in the previous merge.
=> Merge form feature branch to master

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Enable add and remove for
collection.
part of #8497
=> New methods for collections

flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
* Usability and visual design improvements for devmode gizmo
* Re-enable selecting the notification text
* FIx whitespace characters
=> Usability and visual design improvements for devmode gizmo and notifications (#8505)

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewListenerTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Rename methods name, update javadoc, add extra filtering and sorting methods
Part of #8497
=> Address DX feedback for data views #8497

flow-server/src/main/resources/webpack.generated.js
Also take into account that
chunk modules may have
submodules.
Fixes #8493
=> Chunk module submodules

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Fixes https://github.com/vaadin/platform/issues/1251
=> remove terser plugin from the default dependencies

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InternalErrorIT.java
=> Fix a couple of tests that were failing randomly. (#7739)

flow-server/src/main/java/com/vaadin/flow/component/Text.java, flow-server/src/test/java/com/vaadin/flow/component/TextTest.java
Fixes #7686
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8480)
=> Throw a meaningfull exception on change property/attribute of Text

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/tests/data/bean/Item.java
=> Add updateItem to DataView #8499

flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
=> Don't redirect in case of error in web component mode

flow-data/src/main/java/com/vaadin/flow/data/provider/HasListDataView.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewListenerTest.java
=> Use setDataSource for setting data.

flow-data/src/main/java/com/vaadin/flow/data/provider/HasDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/HasListDataView.java
Added the HasDataView interface
so that for cases that are not
handled by ListDataView or LazyDataView
there can still be a return type of DataView.
part of #8189
=> Add HasDataView interface

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, flow-data/src/main/java/com/vaadin/flow/data/provider/HasLazyDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/LazyDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/Query.java, flow-data/src/main/java/com/vaadin/flow/data/provider/SizeEstimateCallback.java, flow-data/src/main/java/com/vaadin/flow/data/provider/SizeEstimateQuery.java
Part of vaadin/vaadin-grid-flow#966
Grid part in https://github.com/vaadin/vaadin-grid-flow/pull/1022
=> Support undefined size for DataCommunicator

flow-server/src/main/java/com/vaadin/flow/component/dependency/JavaScript.java, flow-server/src/test/java/com/vaadin/flow/internal/UrlUtilTest.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PlainScriptViaJavaScriptView.java, flow-tests/test-root-context/src/main/webapp/plain-script.js, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PlainScriptViaJavaScriptIT.java
=> Treat URLs with "context" and "base" schemas as external 

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
=> Protect add- methods in ListDataView from adding the duplicated items #8538

flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
=> Prevent NPE in Pwa handler

flow-server/src/main/java/com/vaadin/flow/component/Composite.java, flow-server/src/test/java/com/vaadin/flow/component/CompositeTest.java
=> Prevent StackOverflowError in Composite.

flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
=> Prevent NPE in Pwa handler (#8561)

flow-server/pom.xml, pom.xml
Base on the report by `dependency-check-maven` plugin and vulnerability report
>https://teamcity.vaadin.com/repository/download/VaadinPlatform_VaadinPlatformPrValidation/64220:id/vaadin-core/target/dependency-check-report.html/dependency-check-report.html
>https://snyk.io/vuln/maven:org.slf4j%3Aslf4j-ext
=> Update slf4j version to resolve vulnerabilities

flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java, flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
=> Clear thread local instances on connection lost in push handler

flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java, flow-data/src/main/java/com/vaadin/flow/data/renderer/RendererUtil.java, flow-data/src/test/java/com/vaadin/flow/data/renderer/RendererUtilTest.java, flow-server/src/main/java/com/vaadin/flow/component/Composite.java, flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java, flow-server/src/main/resources/webpack.generated.js, flow-server/src/test/java/com/vaadin/flow/component/CompositeTest.java, flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/StreamResourceRegistryTest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/StreamRequestHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java, flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/StreamResourceView.java, flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/StreamResourceView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java, pom.xml
=> Cherry picks 2.2

flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java, flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache, flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java, flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
=> Enable generating self-referencing arrays in TypeScript models

flow-server/src/main/java/com/vaadin/flow/component/HasLabel.java, flow-server/src/main/java/com/vaadin/flow/dom/ElementConstants.java, flow-server/src/test/java/com/vaadin/flow/component/HasLabelTest.java
Add new HasLabel interface to be used by components that supports label
definitions
Fixes #3241
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8424)
=> Create new mixin interface HasLabel(#3241)

flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
Part of vaadin/multiplatform-runtime#72
=> Add client side API for listening DOM Node set for StateNode

flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
=> Remove async from client-side binder addValidator method

flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
Part of vaadin/multiplatform-runtime#72
=> Add client side API for listening DOM Node set for StateNode (#8590)

flow-bom/pom.xml
This module is no longer included.
=> Remove flow-jrebel-plugin from flow-bom

flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/Validation.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts, flow-client/src/test/frontend/form/ValidationTests.ts, flow-client/src/test/frontend/form/ValidatorsTests.ts
=> Add impliesRequired Validator flag

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/ScrollIT.java
=> Check the issue after open the browser window.

flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java, flow-server/src/test/java/com/vaadin/flow/server/WebBrowserTest.java
=> Avoid NPEs in WebBrowser

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
=> Rework AbstractListDataView::updateItem #8608

flow-server/src/main/java/com/vaadin/flow/router/ErrorNavigationEvent.java, flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkIT.java
=> Push history when navigating to route-not-found view (#8630)

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
=> Destroy external frontend resources install process on JVM exit

flow-client/src/main/java/com/vaadin/client/flow/ExecuteJavaScriptProcessor.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
=> Check whether the lifecycle state is already terminated before terminate

flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java, flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
=> Make Registration for Component::addListener idempotent

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
=> Don't handle dynamic resources by the DevModeHandler

flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataViewTest.java
Components have a similar unit tests for generic data view classes, so those common tests are moved to Flow to avoid duplicated code.
=> Abstract unit test for generic component-specific data views

flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementAttributeMap.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AbstractStreamResourceIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java
* Fix the bug
* Add IT tests for re-attaching a stream resource
Fixes #6478
=> Update attribute value on attach (#7627)

flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java, flow-server/src/main/java/com/vaadin/flow/server/connect/generator/SchemaResolver.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateConnect.java, flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityTemplate.mustache, flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGenerationTest.java, flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/enumtype/EnumEndpoint.java, flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/enumtype/EnumEndpointTest.java, flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/json/JsonTestEndpoint.java, flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/enumtype/expected-EnumEndpoint.ts, flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/enumtype/expected-model-enumtype.EnumEndpoint.MyEnum.ts, flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-model-json.JsonTestEndpoint.Permissions.ts, flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-model-json.JsonTestEndpoint.Role.ts, flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-openapi-custom-application-properties.json, flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-openapi.json
The OpenAPI JSON output for enums is based on "Reusable enums" description at https://swagger.io/docs/specification/data-models/enums/
Fixes #8144 
```java
public enum MyEnum {
ENUM1(1), ENUM2(2);
private final int value;
MyEnum(int value) {
this.value = value;
}
public int getValue() {
return value;
}
}
```
Generated OpenAPI json:
```json
...
"components" : {
"schemas" : {
"com.vaadin.flow.server.connect.generator.endpoints.enumtype.EnumEndpoint.MyEnum" : {
"type" : "string",
"enum" : [ "ENUM1", "ENUM2" ],
"x-vaadin-file-path" : "/home/haprog/repos/Work/flow/flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/enumtype/EnumEndpoint.java"
}
},
"securitySchemes" : { ... }
}
```
In the json where the enum type has been used in the API it will show under `properties` …
=> Add support for enums in endpoints

flow-data/src/main/java/com/vaadin/flow/data/binder/HasItems.java, flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/HasDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/HasLazyDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/HasListDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/LazyDataView.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewListenerTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/HasLazyDataViewTest.java
Only remaining parts referring to "data source" in comments will be touched by upcoming refactoring tickets.
Fixes #8632
=> Use setItems instead of setDataSource

flow-client/src/main/java/com/vaadin/client/flow/ExecuteJavaScriptProcessor.java, flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java, flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementAttributeMap.java, flow-server/src/main/java/com/vaadin/flow/router/ErrorNavigationEvent.java, flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java, flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java, flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java, flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java, flow-server/src/test/java/com/vaadin/flow/server/WebBrowserTest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AbstractStreamResourceIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java
=> Merge 2.2 to 2.3

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractLazyDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/HasLazyDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/ItemCountChangeEvent.java, flow-data/src/main/java/com/vaadin/flow/data/provider/ItemCountChangeListener.java, flow-data/src/main/java/com/vaadin/flow/data/provider/LazyDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewListenerTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/HasLazyDataViewTest.java
=> Use ItemCount instead of size and RowCount #8651

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/HasDataView.java
=> Rename the API for generic data view #8618

flow-client/package.json, flow-client/pom.xml, flow-client/scripts/version.js, flow-client/src/main/resources/META-INF/resources/frontend/form/index.ts, flow-client/src/main/resources/version.txt, flow-client/src/test/frontend/form/IndexTests.ts, flow-client/webpack.tests.config.js
=> Add registration for @vaadin/form package

flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts, flow-client/src/test/frontend/form/BinderTests.ts, flow-client/src/test/frontend/form/FieldTests.ts, flow-client/src/test/frontend/form/ValidationTests.ts
=> Clear client-side validation and visits on .reset() and .clear()

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractLazyDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
=> Move contains(T item) to ListDataView

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractLazyDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HasHierarchicalDataProviderTest.java
=> Add getItem(int index) to DataView #8652

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HasHierarchicalDataProviderTest.java
=> Rename and move updateItem #8653

flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts, flow-client/src/test/frontend/form/ValidationTests.ts
=> fix: render server errors and submitting state

flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
=> Fall back to user.dir / cwd as frontend build base directory only if it is a project directory

flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkIT.java
=> Store scroll position in state when entering route not found view

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, flow-data/src/main/java/com/vaadin/flow/data/provider/Query.java, flow-data/src/main/java/com/vaadin/flow/data/provider/QueryTrace.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
=> Make it easier to use to paged repositories for data provider data #8557

flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshReAddIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshShortcutIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PushWithPreserveOnRefreshIT.java
=> When moving from one UI to another, move elements contained in body rather than those contained in wrapper

flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
Documentation enhancement for #8716
=> Added more docs for the mutation methods.

flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts
Fixes https://github.com/vaadin/flow/issues/8719
=> chore: add in-code documentation for ts form

flow-server/src/main/java/com/vaadin/flow/server/connect/BeanValueTypeCheckHelper.java, flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java, flow-server/src/test/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerTest.java
Fixes https://github.com/vaadin/flow/issues/8025
=> fix: circular ref results in stackoverflow

flow-server/src/main/java/com/vaadin/flow/server/Constants.java, flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
=> Add forgotten properties to InitParameters from Constants in 2.3

flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExceptionInStreamResourceView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionInStreamResourceIT.java
=> Avoid try-resource construction with catch for status code set

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Fixes #8762
Thanks @mstahv for this fix! I've just added a regression tests and created a new branch.
=> ListDataView: addItemAfter doesn't work with filter

flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts, flow-client/src/test/frontend/FlowTests.ts
=> fix: relax Flow client content-type check

flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExceptionInStreamResourceView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionInStreamResourceIT.java
=> Avoid try-resource construction with catch for status code set (#8793)

flow-server/src/main/java/com/vaadin/flow/component/HasComponents.java, flow-server/src/test/java/com/vaadin/flow/component/HasComponentsTest.java
=> Don't remove children immediately: make checks and then remove

flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
=> Avoid findIndex JS Array function.

flow-server/src/main/java/com/vaadin/flow/server/UnsupportedBrowserHandler.java, flow-server/src/test/java/com/vaadin/flow/server/UnsupportedBrowserHandlerTest.java
=> Set content type in UnsupportedBrowserHandler

flow-data/src/main/java/com/vaadin/flow/data/validator/EmailValidator.java, flow-data/src/test/java/com/vaadin/flow/data/validator/EmailValidatorTest.java
=> Overload EmailValidator to accept an empty value

flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
=> Use var instead of let to avoid magical JS error

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
=> Improve log message for skipping (p)npm install

flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Fix for #8729 has been reverted in `2.3`. Let's do the same for master.
=> Revert fix for #8729

.gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8350)
=> chore: Add more files into .gitignore

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
=> Fix integer overflow in Data Provider page number formula

flow-client/src/main/java/com/vaadin/client/WidgetUtil.java, flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtEventHandlerTest.java, flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtMultipleBindingTest.java, flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtPropertyElementBinderTest.java, flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementAttributeMap.java, flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeProperties.java, flow-tests/test-embedding/embedding-test-assets/src/main/java/com/vaadin/flow/webcomponent/ClientSelectComponent.java, flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/WebComponentIT.java
=> Add transmission semantic for URI attribute values

flow-server/src/main/java/com/vaadin/flow/component/Component.java, flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
=> #7911 Implement Component.isAttached().

flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java, flow-server/src/main/java/com/vaadin/flow/server/connect/generator/SchemaGenerator.java, flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java, flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java, flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-openapi-custom-application-properties.json, flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-openapi.json, flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
=> fix(TypeScript): Ensure model validators are generated for fields of bean type

flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataViewTest.java
Fixing the abstract test on Flow side so as to update this PR https://github.com/vaadin/vaadin-grid-flow/pull/1055
=> Fix custom data provider impl in AbstractComponentDataViewTest

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
=> Backend is requested for pages that don't exist

.gitignore, flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java
=> fix: Revert delay location.reload when session expires(#7707)

flow-server/src/main/java/com/vaadin/flow/component/Key.java
Some trivial improvement in Key interface:
* make its keys unmodifiable
* produce less garbage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8416)
=> Improve Key interface

flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
=> Cherry pick for 3.1

flow-server/src/main/java/com/vaadin/flow/component/Key.java, flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java, flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
=> Cherry picks for 4.0

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
=> Update compression plugin (#8879)

flow-server/src/main/java/com/vaadin/flow/component/HasHelper.java, flow-server/src/test/java/com/vaadin/flow/component/HasHelperTest.java
* Add HasHelper interface (#8532)
=> Add HasHelper interface (#8922)

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsLocator.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java, flow-server/src/main/resources/com/vaadin/flow/server/dev-mode-not-ready.html, flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerStopTest.java, flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java, flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractTestBenchTest.java, flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java, flow-tests/test-multi-war/deployment/src/test/java/com/vaadin/flow/multiwar/deployment/TwoAppsIT.java, flow-tests/test-npm-only-features/test-npm-performance-regression/src/main/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformance.java, flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BackButtonServerRoundTripIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BaseHrefIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DynamicallyRegisteredRouteIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouteNotFoundDevModeIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouteNotFoundProdModeIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SetParameterForwardToIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ViewTitleIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/PushRouteNotFoundIT.java, flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/PushIT.java
=> Cherry picks for starting web pack dev server and (p)npm install command in the separate thread

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/resources/webpack.generated.js, flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
=> Remove progress plugin from web-pack config

flow-data/src/test/java/com/vaadin/flow/data/provider/CustomInMemoryDataProvider.java
=> Make the CustomInMemoryDataProvider implement listeners handling (#8961)

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloaderTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
=> Cherry picks to 4.0

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java, flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloaderTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java, flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
=> Cherry picks for 2.3

flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java, flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java, flow-server/src/main/java/com/vaadin/flow/internal/HtmlUtils.java, flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java, flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/PropertyChangeDeniedException.java, flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java, flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/MapSyncRpcHandler.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java, flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMapTest.java, flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/MapSyncRpcHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloaderTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java, flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java, flow-tests/pom.xml, pom.xml
There are conflicts due to new changes in 2.4 so cherry-picking was more simple than merge.
=> Merge, do not squash: cherry-picks from 2.3 to 2.4

flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java, flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java, flow-tests/test-root-context/frontend/SetInitialText.js, flow-tests/test-root-context/frontend/lit/SetInitialText.js, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/SetInitialTextLitView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/SetInitialTextView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/SetInitialTextLitIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/SetInitialTextIT.java
=> Send clear event if no other changes done on attach

flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Tests https://github.com/vaadin/flow/issues/5173
Fix was done in https://github.com/vaadin/flow/pull/8170
=> Add test for forwardTo from setParameter without BeforeEnterObserver.

flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java, flow-server/src/test/java/com/vaadin/flow/component/AbstractSinglePropertyFieldTest.java
=> Be aware of property value in the Element

flow-server/src/main/java/com/vaadin/flow/internal/BootstrapHandlerHelper.java, flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/routing/PushRouteWildcardParameterView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/PushRouteWildcardParameterIT.java
=> JavaScriptBootstrapHandler: Do not compute push url from service and request url on the server side

flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
=> 4.0 cherry pick

flow-server/src/main/java/com/vaadin/flow/server/AppShellSettings.java, flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
=> Remove faux Serializable from AppShellSettings

flow-server/src/main/java/com/vaadin/flow/router/internal/ConfigureRoutes.java, flow-server/src/main/java/com/vaadin/flow/router/internal/RouteModel.java, flow-server/src/test/java/com/vaadin/flow/router/internal/ConfigureRoutesTest.java
Fixes https://github.com/vaadin/flow/issues/8433
=> Clear routes.

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/AbstractDependenciesScanner.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java, flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/AbstractScannerPwaTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendScannerPwaTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullScannerPwaTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/pwa/AnotherAppShellWithPwa.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/pwa/AppShellWithPwa.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/pwa/AppShellWithoutPwa.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/pwa/NonAppShellWithPwa.java, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeClassFinderTest.java, flow-tests/test-embedding/embedding-test-assets/src/main/java/com/vaadin/flow/webcomponent/ClientSelectExporter.java, flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/MiscelaneousView.java, flow-tests/test-pwa/src/main/java/com/vaadin/flow/pwatest/ui/ParentLayout.java
=> feat(offline): read @PWA to configure webpack build

flow-server/src/main/java/com/vaadin/flow/component/page/PendingJavaScriptResult.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
=> Cherry picks for 2.3.6

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
=> Restructure dev mode handler logic to avoid starting webpack twice

flow-client/src/main/java/com/vaadin/client/PolymerUtils.java, flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java, flow-server/src/main/java/com/vaadin/flow/component/page/PendingJavaScriptResult.java, flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java, flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeProperties.java, flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java, flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java, flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java, flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java, flow-tests/test-root-context/frontend/SetInitialText.js, flow-tests/test-root-context/frontend/template-inner.js, flow-tests/test-root-context/frontend/template-outer.js, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/InnerTemplateVisibilityView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/SetInitialTextView.java, flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/SetInitialText.html, flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/template-inner.html, flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/template-outer.html, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/InnerTemplateVisibilityIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/SetInitialTextIT.java
=> Cherry-picks for 2.4

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java, flow-server/src/main/java/com/vaadin/flow/component/page/PendingJavaScriptResult.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java, flow-tests/pom.xml, pom.xml
=> Cherry-pick from master to 4.0

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java, flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
=> Skip data provider verification in AbstractDataView if default one is used

flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java, flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
=> fix: Rewrite fix for clearing Current instances

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java, flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
=> Use a default page size for DataCommunicator

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Part of https://github.com/vaadin/vaadin-combo-box-flow/issues/355
=> fix: Rename method name to avoid double negation

flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts, flow-client/src/test/frontend/ConnectTests.ts
=> feat(offline): expose isDeferred flag on MiddlewareContext

flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java, flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
It should return all components added to the UI, like Dialog and Notification.
Related to #7799
Fixes #9069
=> fix: Fix JavaScriptBootstrapUI::getChildren

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
=> Do more accurate check for error messages in IT

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
=> Do more accurate check for error messages in IT (#9086)

flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/LitTemplateTest.java, flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java, flow-server/src/main/java/com/vaadin/flow/component/Component.java, flow-tests/test-root-context/frontend/DisabledPolymerTemplateElement.js, flow-tests/test-root-context/frontend/lit/DisabledLitTemplateElement.js, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/DisabledLitTemplateElementView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/DisabledPolymerTemplateElementView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/DisabledLitTemplateElementIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/AbstractDisabledTemplateElementIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/DisabledPolymerTemplateElementIT.java
=> fix: Set disabled status for component mapped to an Element

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Part of https://github.com/vaadin/vaadin-combo-box/issues/914
=> refactor: allow components to fire a count change event

flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts, flow-client/src/test/frontend/ConnectTests.ts
=> feat(offline): add processDeferredCalls / onDeferredCall API to ConnectClient

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Part of https://github.com/vaadin/vaadin-combo-box/issues/914
=> refactor: revert 'allow components to fire a count change event'

flow-tests/pom.xml, flow-tests/test-ccdm-flow-navigation/frontend/index.html, flow-tests/test-ccdm-flow-navigation/frontend/index.ts, flow-tests/test-ccdm-flow-navigation/frontend/views/about/about-view.ts, flow-tests/test-ccdm-flow-navigation/pom.xml, flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/HelloWorldView.java, flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java
Test navigating from clinet view to server-side
view and server to client.
Closes #9134
=> test: Navigation test between modes

flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java, flow-server/src/test/java/com/vaadin/flow/internal/ResponseWriterTest.java
A Range header can specify either a single byte range, e.g. `Range: bytes=0-99`, or multiple ranges,
e.g. `Range: bytes=0-99, 200-299`. The ranges do not need to be sequential and can have overlap;
e.g. `Range: bytes=200-299, 0-219` is valid; such requests will open a new stream reading from the
beginning of the file for each out-of-order range. The motivation for this feature is to support video
playback on Safari.
Fixes #9083
=> feat: add support for Range header to StaticFileServer

flow-server/pom.xml
=> chore!: bump httpclient to 4.5.13

flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateParser.java, flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateParserImpl.java, flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java, flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/LitClassesSerializableTest.java, flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImplTest.java
=> Make LitTemplateParserImpl public. Fixes #9169

flow-server/src/main/resources/com/vaadin/flow/server/frontend/types.d.ts, flow-tests/test-ccdm/frontend/css-importing-test.ts, flow-tests/test-ccdm/frontend/empty.css
=> fix: include import CSSResult in generated types.d.ts

flow-server/src/main/java/com/vaadin/flow/component/Composite.java
Using a regular instance field instead of a non-static ThreadLocal has
no functional difference except in the hypothetical case when
getContent() would be called concurrently on a different thread. That
case is not supposed to happen since the session lock should be used to
prevent concurrent access. Furthermore, concurrent invocation would
still not work properly since use of the `content` field is not
synchronized.
A simple boolean communicates the intent more clearly, thus making the
purpose of the implementation easier to understand. The simpler approach
also has a minimal positive impact on CPU usage and memory allocation.
Fixes #9160
=> Simplify check for recursive getContent() in Composite

flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/BundleLitParser.java, flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java, flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImplTest.java, flow-lit-template/src/test/resources/META-INF/VAADIN/config/stats.json, flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java, flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java, flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/BundleParserTest.java, flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java, flow-polymer-template/src/test/resources/META-INF/VAADIN/config/stats.json
Add support for parsing sources for
TypeScript modules.
Fixes #9165
=> fix: Support .ts files in parsers

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Extends the `DataCommunicator` API to set the permanent/disposable flag to the component's filter object and discards this filter after the next request to data provider, if disposable. This is needed to ignore the client filter of `ComboBox` in data view retrieve methods (`getItems` for instance) and to not fire the item count change event in case of client filtering.
Overloaded version of `setRequestedRange` has also added in order to avoid a doubled `flush` invocations in `ComboBox`, when the client filter has changed.
Part of https://github.com/vaadin/vaadin-flow-components/issues/210
=> feat: disposable filter setup API in data communicator

flow-server/src/main/resources/sw.ts
=> fix: implement navigation fallback

README.md, drivers.xml, flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
=> Cherry picks to 2.4

README.md, drivers.xml, flow-client/intern.json, flow-maven-plugin/README.md, flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
=> Merge master into offline

flow-server/src/main/resources/webpack.generated.js, flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
=> fix: use relative path reference to index.html (`.` instead of `/`)

flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java, flow-tests/test-ccdm-flow-navigation/frontend/index.ts, flow-tests/test-ccdm-flow-navigation/frontend/views/another/another-view.ts, flow-tests/test-ccdm-flow-navigation/frontend/views/main/main-view.ts, flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/AppShell.java, flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java, flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/OfflineServerViewIT.java, flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
=> Add test for navigation fallback

flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloader.java
Do not depend on transitive generic libraries in flow-server.
=> chore: do not depend on commons.lang3

flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java, flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
=> refactoring: App classpath resources should be access via ResourceProvider

flow-server/README.md, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java, flow-server/src/main/resources/plugins/stats-plugin/package.json, flow-server/src/main/resources/plugins/stats-plugin/stats-plugin.js, flow-server/src/main/resources/plugins/webpack-plugins.json, flow-server/src/main/resources/webpack.generated.js, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPluginsTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java, flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Moved stats file handling to a custom plugin.
Added feature for copying custom Flow plugins
for use with webpack.
Fixes #9283
=> feat: Create Flow plugins for webpack

flow-client/src/main/resources/META-INF/resources/frontend/form/index.ts, flow-server/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java, flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/SessionView.java, flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/SessionViewIT.java
=> test(TypeScript): ensure CSRF token is updated when session is invalidated

flow-server/src/main/java/com/vaadin/flow/component/Composite.java, flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java, flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java, flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java, flow-server/src/test/java/com/vaadin/flow/internal/ResponseWriterTest.java, flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java, flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/UrlValidationIT.java, flow-tests/test-npm-only-features/test-npm-general/src/test/java/com/vaadin/flow/testnpmonlyfeatures/general/UrlValidationIT.java
=> Cherry Picks for 2.4

flow-server/bnd.bnd, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FragmentLinkIT.java
=> Fix push osgi

flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
=> fix: check whether class implements an interface first directly

flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java, flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/test/java/com/vaadin/flow/internal/ResponseWriterTest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
=> 5.0 cherry pick

drivers.xml, flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/test/java/com/vaadin/flow/internal/ResponseWriterTest.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
=> 2.4 cherry pick

README.md, drivers.xml, flow-server/src/main/java/com/vaadin/flow/component/Composite.java, flow-server/src/main/java/com/vaadin/flow/internal/CustomElementNameValidator.java, flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java, flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java, flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java, flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java, flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java, flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/test/java/com/vaadin/flow/internal/CustomElementNameValidatorTest.java, flow-server/src/test/java/com/vaadin/flow/internal/ResponseWriterTest.java, flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java, flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/UrlValidationIT.java, flow-tests/test-npm-only-features/test-npm-general/src/test/java/com/vaadin/flow/testnpmonlyfeatures/general/UrlValidationIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
=> Cherry Picks for 2.5

flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java, flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
=> test: add unit test for clear all in the servlet init method

flow-tests/test-root-context/pom.xml, flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PlainScriptViaJavaScriptIT.java
=> fix: enable PlainScriptViaJavaScriptIT in OSGi

flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts, flow-client/src/test/frontend/ConnectTests.ts, flow-client/src/test/frontend/FlowTests.ts
=> fix: add vaadin-connection-indicator in Connect ctor

flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/routing/PushRouteWildcardParameterView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/PushRouteWildcardParameterIT.java
=> fix: enable PushRouteWildcardParameterIT in OSGi

flow-server/README.md
Added information on log levels
with webpack loaders and plugins.
=> chore: Add information on logging in webpack

flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/ViewTestServlet.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
=> test: fix test class and register view servlet with a context in OSGi

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/MultipleAnchorsIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/ScrollIT.java
=> chore: removed `hasClientIssue("8236")` guard as ITs now pass

flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/BundleLitParser.java, flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/BundleLitParserTest.java
Now the pattern will not fail with a StackOverflowException
as we will search from the start character accepting
any characters until we reach the caught start character with ;
=> Fix: Update Lit bundle parser regex.

flow-server/src/main/resources/webpack.generated.js, flow-tests/test-themes/frontend/index.html, flow-tests/test-themes/frontend/index.ts, flow-tests/test-themes/frontend/typescript/hello-world-view.css, flow-tests/test-themes/frontend/typescript/hello-world-view.ts, flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
=> fix: Enable lit css importing

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
=> fix: use provided executor for frontend tools

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
=> fix: use provided executor for frontend tools (#9553)

flow-server/src/main/java/com/vaadin/flow/di/Lookup.java, flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java, flow-server/src/test/java/com/vaadin/flow/di/LookupTest.java, flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerStopTest.java, flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/LookupInitializerTest.java, flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
=> refactor: get Executor service from Lookup instead init params

flow-client/scripts/version.js, flow-client/src/main/resources/META-INF/resources/frontend/DeferrableEndpoint.ts, flow-client/src/test/frontend/DeferrableEndpointTest.ts, flow-client/webpack.tests.config.js, flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/TypeScriptApiTemplate.mustache, flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-SingleMethodDeferrableEndpoint.ts, flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-WholeClassDeferrableEndpoint.ts, flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/expected-PersonEndpoint.ts
=> feat: add entry for @Deferrable to Vaadin usage statistics

flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImplTest.java, flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java, flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java, flow-server/src/main/java/com/vaadin/flow/di/ResourceProvider.java, flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java, flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java, flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java, flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java, flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java, flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/LookupInitializerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/testdata/TestResourceProvider.java
=> refactor: simplify ResourceProvider

flow-server/bnd.bnd, flow-server/src/main/java/com/vaadin/flow/internal/ApplicationClassLoaderAccess.java, flow-server/src/main/java/com/vaadin/flow/internal/VaadinContextInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java, flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java, flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
related to #9601 : needed to restore OSGi resource provider
=> chore: add internal classes to access classloader and init context

.gitignore, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java, flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js, flow-server/src/main/resources/plugins/application-theme-plugin/package.json
my-theme.js is now generated as my-theme.generated.js
Fixes #9595
=> Fix: Generated theme.js is now named theme.generated.js

flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js, flow-server/src/main/resources/plugins/application-theme-plugin/package.json, flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js, flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js, flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/ThemedComponentExporter.java, flow-tests/test-themes/README.md
Check that we have named npm resources
available or throw an exception informing
the user to intall it using a NpmPackage
annotation or manually with (p)npm i
Fixes #9615
=> Feat: Check that npm resources are available

flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts, flow-client/src/test/frontend/AuthenticationTests.ts, flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java, flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
=> fix(offline): do not cache CSRF token and clear on offline logout

flow-client/src/test/frontend/FlowTests.ts, flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java, flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ConnectionIndicatorIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
This PR fixes three four IT issues:
1. A race condition in `ConnectionIndicatorIT`  
2. `DevToolsActivePort file doesn't exist` spurious error when running in headful mode.
3. `LogoutIT` `"Session Expired"` console error exclusion format relaxed
4. Timing issues in `FlowTests.ts`
=> chore: improve IT stability

flow-data/src/main/java/com/vaadin/flow/data/provider/CompositeDataGenerator.java, flow-data/src/test/java/com/vaadin/flow/data/provider/CompositeDataGeneratorTest.java
Fixes https://github.com/vaadin/flow/issues/9656
=> fix: use LinkedHashSet (not HashSet) for deterministic CompositeDataGenerator 

drivers.xml, flow-client/intern.json
=> chore: update ChromeDriver to 87.0.4280.88

flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/Validation.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts, flow-client/src/test/frontend/form/FieldTests.ts, flow-client/src/test/frontend/form/ModelTests.ts, flow-client/src/test/frontend/form/ValidationTests.ts, flow-client/src/test/frontend/form/ValidatorsTests.ts
=> cherry-pick 5.0

flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/Validation.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts, flow-client/src/test/frontend/form/FieldTests.ts, flow-client/src/test/frontend/form/ModelTests.ts, flow-client/src/test/frontend/form/ValidationTests.ts, flow-client/src/test/frontend/form/ValidatorsTests.ts
=> cherry-pick 4.0

flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts, flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts, flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts, flow-tests/test-ccdm-flow-navigation/frontend/index.ts
=> refactor!: expose connectionIndicator as constant instead of via getter

flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java, flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java
=> fix: avoid BeforeClient executions for nodes with different StateTree

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
=> fix: use proper logging for installing pnpm and its directory

flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts, flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts, flow-client/src/test/frontend/ConnectTests.ts
=> fix: offline indicator visibility

flow-tests/test-themes/frontend/themes/app-theme/components/background-color.css, flow-tests/test-themes/frontend/themes/app-theme/components/vaadin-radio-button.css, flow-tests/test-themes/frontend/themes/app-theme/components/vaadin-text-field.css
Add test for using css `@import` for component
specific theme files.
Closes #9736
=> Use CSS import in component theming

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerDependenciesTest.java, flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java, flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
Loading from classpath resource should
not start with '/'
=> Fix: resource loading string

flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
=> fix: wrong this binding in loadingStarted/Finished

flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js, flow-server/src/main/resources/plugins/theme-loader/theme-loader.js
Make plugins less noisy with normal log
by moving info level logs to log level.
Clean up log messages so they match.
=> chore: update log for level for plugins

flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/startup/fusion/DevModeInitializerEndpointTest.java
Picked applicable changes from these commits on master: df7a5f80b8c77f5d1505ecd6aea7e1adf70141bf,  9e8a0618dbc7ffec22b8fff49a520b846f7f2c49, 86efdc6a54196914982bcad2a72e8649fe4338d2
=> chore: pick flaky test fixes from master

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
Fixes: https://github.com/vaadin/vaadin-grid/issues/1837
=> fix: Add empty list handling to DataCommunicator#collectKeysToFlush

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImportTest.java
Remove the theme.[js|d.ts] files if no
theme is defined.
Fixes #9832
=> fix: Clean theme file if no theme defined

flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
Fixes: https://github.com/vaadin/flow/issues/9838
=> test: Revert user.dir system property after test

flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java, flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
=> fix: properly initialize and destroy Vaadin Servlet

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Includes https://github.com/calebdwilliams/construct-style-sheets/pull/46 which seems relevant for many cases
=> Use newest constructed stylesheet polyfill

flow-server/pom.xml
=> fix: bump jackson library version

scripts/cherryPick.js
pick the older commits first,
show the error when cherry pick failed.
=> chore: fix cherry pick script

fusion-endpoint/pom.xml
Related to https://github.com/vaadin/flow/issues/8588
=> fix: remove problematic dependencies

flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfigTest.java, flow-tests/test-ccdm-flow-navigation/frontend/views/main/main-view.ts, flow-tests/test-ccdm/frontend/index.js
=> feat(TypeScript): add Frontend path alias

flow-tests/servlet-containers/pom.xml, flow-tests/servlet-containers/tomcat85/pom.xml, flow-tests/servlet-containers/tomcat9/pom.xml
=> fix: use maven3 cargo plugin

flow-tests/servlet-containers/pom.xml, flow-tests/servlet-containers/tomcat85/pom.xml, flow-tests/servlet-containers/tomcat9/pom.xml
=> fix: fix tomcat ITs 

flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java, flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java, flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java, flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
Prepare for 1.0.14 maintenance release.
https://github.com/vaadin/flow/issues/9907
=> Cherry pick to 1.0

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Clean away also old devDependencies
on Package update.
Fixes #9720
=> fix: Remove old devDependencies

fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/enumtype/EnumEndpoint.java, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/enumtype/expected-model-enumtype.EnumEndpoint.MyEnum.ts
=> Use the same enum name in TS as in Java

flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
=> chore: fix flaky test

flow-server/src/main/resources/webpack.generated.js
=> fix: ensure app shell is always in offline manifest

flow-client/src/test/frontend/FlowTests.ts
Don't test css properties in loading indicator using short timeout,
as this is flaky (the test `should initialize a flow loading indicator`)
already checks loading indicator style transitions with a longer
and hence stabler timeout. Use sinon.spy to check that the 
right methods are called and added another test for isActive
flag.
Fixes #9980.
=> test: sinon.spy instead of timer for stabler test

fusion-endpoint/src/main/resources/com/vaadin/flow/server/connect/generator/TypeScriptApiTemplate.mustache, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/collectionendpoint/expected-CollectionEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/complexhierarchyendpoint/expected-ComplexHierarchyEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/datetime/expected-DateTimeEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/denyall/expected-DenyAllEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/enumtype/expected-EnumEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/inheritedmodel/expected-InheritedModelEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-GeneratorAnonymousAllowedTestClass.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-JsonTestEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/model/expected-ComplexReturnTypeEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/model/expected-ComplexTypeParamsEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/model/expected-ModelEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/modelpackage/expected-ModelPackageEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/modelpackage/expected-SubModelPackageEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/nullable/expected-NullableEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/reservedwordmethod/expected-ReservedWordMethodEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/sameclassname/expected-SameClassNameEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/selfreference/expected-SelfReferenceEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/expected-PersonEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-FooBarEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-default-class-no-tag.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-first-class-multiple-tags.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-multiple-lines-description.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-no-tsdoc.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-partly-tsdoc.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-second-class-multiple-tags.ts
=> feat(TypeScript): add endpoint wrapper class-like exports

scripts/cherryPick.js
if the cherry pick cannot be done by the script, there will be a comment to remind the author to do the cherry pick manually. 
the comment is provided based on target branch.
=> chore: post a comment if cherry pick failed

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/main/resources/webpack.generated.js, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
This is compatible with Webpack 5
=> Cleanup: Use env instead of custom parameter to webpack

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
=> fix: Use latest webpack 4 to fix using npm v7

flow-server/README.md, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java, flow-server/src/main/resources/plugins/stats-plugin/package.json, flow-server/src/main/resources/plugins/stats-plugin/stats-plugin.js, flow-server/src/main/resources/plugins/webpack-plugins.json, flow-server/src/main/resources/webpack.generated.js, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPluginsTest.java, flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Moved stats file handling to a custom plugin.
Added feature for copying custom Flow plugins
for use with webpack.
Fixes #9283
Part of #9983
=> feat: Create Flow plugins for webpack (#9295)

flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
=> chore: remove broken code

flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts, flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts, flow-client/src/test/frontend/form/ValidatorsTests.ts
=> fix: NumberValidator accepts undefined for optional fields

flow-server/src/main/java/com/vaadin/flow/router/RoutesChangedEvent.java, flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java, flow-server/src/main/java/com/vaadin/flow/router/internal/HasUrlParameterFormat.java, flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java, flow-server/src/test/java/com/vaadin/flow/router/internal/HasUrlParameterFormatTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/ApplicationRouteRegistryTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryTestBase.java
Fixes https://github.com/vaadin/flow/issues/9973
=> fix: Skip adding url parameter template if already present

flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
=> chore: Increase application startup time threshold

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Workbox 6 is compatible both with Webpack 4 and 5
=> Upgrade to Workbox 6

flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
To be fixed https://github.com/vaadin/flow/issues/10065
=> chore: Ignore flaky test

flow-server/src/main/java/com/vaadin/flow/component/HasSize.java, flow-server/src/main/java/com/vaadin/flow/component/Unit.java, flow-server/src/test/java/com/vaadin/flow/component/HasSizeUnitTest.java
Add legacy style setting of size by using Unit to HasSize.
This will simplify migration of Vaadin 8 projects.
=> feat: support Unit in similar fashion to Vaadin 8 (#8533)

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
=> Update adopted stylesheet polyfill

flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
=> chore: remove broken code (#10019)

flow-client/package.json, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-tests/test-ccdm-flow-navigation/frontend/views/about/about-view.global.css, flow-tests/test-ccdm-flow-navigation/frontend/views/about/about-view.ts, flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/CssLoaderIT.java
Fixes https://github.com/vaadin/flow/issues/10080
Also removed the unnecessary `idb` dependency.
=> fix: add style-loader dependency

flow-server/src/main/resources/com/vaadin/flow/server/frontend/types.d.ts, flow-server/src/main/resources/webpack.generated.js
This reverts commit 27d6e534e2dad985ff0a83858a3d67375b7d92b4.
=> Revert "feat: global CSS loader (#10036) (#10060)"

flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Don't start third devServer in middle.
Fixes #10018
=> chore: Fix initalizing to devServers

flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java, flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java, flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java, flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java, flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java, flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java, flow-server/src/main/java/com/vaadin/flow/server/startup/AppShellPredicate.java, flow-server/src/main/java/com/vaadin/flow/server/startup/LookupServletContainerInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java, flow-server/src/test/java/com/vaadin/flow/di/AppShellPredicateImplTest.java, flow-server/src/test/java/com/vaadin/flow/di/LookupIntializerTest.java, flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/PwaHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentProviderTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java, flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
=> chore: enable PWA in OSGi

flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
=> Do not emit errors for unused variables/imports/parameters

flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java, flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
=> chore: security helper with list of should-be-public urls

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js, flow-server/src/main/resources/plugins/application-theme-plugin/package.json, flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js, flow-server/src/main/resources/plugins/theme-loader/package.json, flow-server/src/main/resources/plugins/theme-loader/theme-loader.js, flow-server/src/main/resources/webpack.generated.js, flow-tests/test-themes/frontend/theme/app-theme/theme.json, flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java, flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Bring in assets and file loader features.
Part of #9983
=> Assets and file loader

flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java
=> chore: make LookupInitializer::instantiate method protected

flow-client/src/main/java/com/vaadin/client/ElementUtil.java, flow-tests/test-root-context/frontend/lit/simple-lit-template-shadow-root.js, flow-tests/test-root-context/frontend/template-without-shadow-root-view.js, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateNoShadowRootView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateShadowRootView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/PolymerTemplateWithoutShadowRootView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateShadowRootIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/PolymerTemplateWithoutShadowRootIT.java
=> Do not return array methods from body.$ when looking for elements

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkIT.java
=> test: add wait before fetching the scroll position

flow-server/src/main/java/com/vaadin/flow/theme/ThemeUtil.java, flow-server/src/test/java/com/vaadin/flow/theme/ThemeUtilTest.java
Throw exception if improved theme support is
used in compatibility mode.
Part of #9983
=> feat: Improved theme support not allowed in compatibility mode

flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts, flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/OfflineWithCustomContextIT.java, flow-tests/test-router-custom-context/src/main/java/com/vaadin/flow/contexttest/ui/AppShell.java, flow-tests/test-router-custom-context/src/main/webapp/offline.html, flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/AbstractContextIT.java, flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/PwaTestIT.java
Fixes https://github.com/vaadin/flow/issues/10177
=> fix: offline path should be relative to current path not root

flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
Related-to: https://github.com/vaadin/flow/issues/9647
=> chore: Activate LogoutWithNotificationServlet for OSGi environment

flow-lit-template/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java, flow-polymer-template/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java, flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java, flow-server/src/main/java/com/vaadin/flow/server/StaticFileHandlerFactory.java, flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java, flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java, flow-server/src/main/java/com/vaadin/flow/server/startup/LookupServletContainerInitializer.java, flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java, flow-server/src/test/java/com/vaadin/flow/di/LookupInitializerTest.java, flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java, flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java, flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java, flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java, flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
=> refactor: use StaticFileHandler as a service (#10229)

fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/SchemaResolver.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/SchemaResolverTest.java
=> fix: do not interpret a bean implementing Iterable as a collection

flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java, flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/EnableOSGiRunner.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ServletContextResourceIT.java
=> fix: avoid exposing ServletContext resources via StaticFileServer

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java, flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js, flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
=> Write generated theme file to the generated folder

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutIT.java
=> test: disable flaky test

flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiAccess.java, flow-server/src/test/java/com/vaadin/flow/server/startup/EnableOSGiRunner.java
Make OSGi check more correct otherwise the code works incorrectly if
FrameworkUtil is present in the classpath
=> chore: FrameworkUtil class presence doesn't mean OSGi

flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiAccess.java, flow-server/src/test/java/com/vaadin/flow/server/startup/EnableOSGiRunner.java
Make OSGi check more correct otherwise the code works incorrectly if
FrameworkUtil is present in the classpath
=> fix: FrameworkUtil class presence doesn't mean OSGi (#10285)

flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
=> test: Disable DevModeHandlerTest flaky test

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
=> test: Disable LogoutIT flaky test

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
=> perf: Cache stats.json loaded from class path

fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/stalefiles/NewEndpoint.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/stalefiles/StaleFilesTest.java
=> fix: keep theme generated files from removing by endpoints generator

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
=> fix: close InputStream properly in FrontendUtils

flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
=> chore: disable flaky test

flow-server/src/main/java/com/vaadin/flow/component/HasStyle.java, flow-server/src/test/java/com/vaadin/flow/component/HasStyleTest.java
=> feat: Allow spaces in addClassNames arguments array

flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/OSGiMarker.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/OSGiMarkerImpl.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/routing/PushLayout.java
=> chore: fix ITs behavior inside OSGi

flow-client/src/main/java/com/vaadin/client/ElementUtil.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-tests/test-npm-only-features/test-npm-general/frontend/lit/simple-lit-template-shadow-root.js, flow-tests/test-npm-only-features/test-npm-general/src/main/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateNoShadowRootView.java, flow-tests/test-npm-only-features/test-npm-general/src/main/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateShadowRootView.java, flow-tests/test-npm-only-features/test-npm-general/src/test/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateShadowRootIT.java, flow-tests/test-root-context/frontend/template-without-shadow-root-view.js, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/PolymerTemplateWithoutShadowRootView.java, flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/template-without-shadow-root-view.html, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/PolymerTemplateWithoutShadowRootIT.java
=> CP: missing template fixes to 2.5

flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
Add input filtering so we only handle
class files from the classpath in
ReflectionsClassFinder
Closes #10304
=> fix: Add reflections input filter

flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DialogShortcutView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DialogShortcutIT.java
Refactors the code a bit to make it easier to understand why are dialog
shortcut ITs flaky in the CI. Only for master branch now.
Related to #10302, #10284
=> chore: refactor flaky test

flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java, flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutWithNotificationServlet.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutWithNotificationIT.java
Fixes #9647
This reverts commit 33113c36be5caa511445bf713a1b3ddacc9f9564.
=> Execute error handling as a last action in message handler"

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrowserWindowResizeIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/DynamicDependencyIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/webcomponent/PaperSliderIT.java
Remove hasUnknownClientIssue() guards for ITs that now pass. Related to #10327.
=> chore: removed some hasUnknownClientIssue() guard

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DialogShortcutIT.java
=> chore: fix DialogShortcutIT initialization

flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
=> Add explicit return type

flow-client/pom.xml, flow-data/pom.xml, flow-dnd/pom.xml, flow-html-components/pom.xml, flow-lit-template/pom.xml, flow-plugins/flow-maven-plugin/pom.xml, flow-polymer-template/pom.xml, flow-push/pom.xml, flow-server/pom.xml, fusion-endpoint/pom.xml, pom.xml
skip tests from server and client
!Revert this commit!
=> Keep modules light

flow-plugins/flow-gradle-plugin/pom.xml
Build jar using gradle and skip maven jar build
deploy using default maven deploy
=> fix: Jar package, gradle build

flow-plugins/flow-gradle-plugin/pom.xml
Seems wagon is missing, probably due to pom packaging?
remove jar override.
=> Add wagon extension

flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java, flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutWithNotificationServlet.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutWithNotificationIT.java
This reverts commit 33113c36be5caa511445bf713a1b3ddacc9f9564.
(cherry picked from commit 2e35fe71f54f18e83a70aab3e2eb85fcb236fe9f)
=> Execute error handling as a last action in message handler (#10390) (CP: 2.5)

flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java, flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutWithNotificationServlet.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutWithNotificationIT.java
This reverts commit 33113c36be5caa511445bf713a1b3ddacc9f9564.
(cherry picked from commit 2e35fe71f54f18e83a70aab3e2eb85fcb236fe9f)
=> Execute error handling as a last action in message handler (#10390) (CP: 2.6)

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterLinkIT.java
=> test: replace hasClientIssue with @Ignore for test which fails in fusion

flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
=> fix: do lazy initialization in a thread-safe way (#10456)

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/PushRouteNotFoundIT.java
=> test: enable PushRouteNotFoundIT

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FragmentLinkIT.java
=> test: ignore FragmentLinkIT instead of using hasClientIssue

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RefreshCloseConnectionIT.java
=> test: enable RefreshCloseConnectionIT

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java
=> test: ignore RouterSessionExpirationIT instead of using hasClientIssue

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/HistoryIT.java
=> test: disable HistoryIT because of fusion issue 82113

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/CountUIsIT.java
=> test: remove hasClientUnknownIssue call and enable CountUIsIT

flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
These are application specific and not related to Vaadin
=> fix: Remove images and icons from public URL list

fusion-endpoint/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
=> Add file link to generated model

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PopStateHandlerIT.java
=> test: refactor test to extract failing parts and disable them

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/CountUIsIT.java
=> test: disable flaky CountUIsIT

flow-server/src/main/java/com/vaadin/flow/component/Text.java, flow-server/src/main/java/com/vaadin/flow/dom/Element.java, flow-server/src/test/java/com/vaadin/flow/component/TextTest.java, flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
=> feat: allow creation of Text and Element from nullable text content

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/CustomScrollCallbacksIT.java
=> test: disable CustomScrollCallbacksIT failing with fusion

flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/JavaScriptReturnValueView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/JavaScriptReturnValueIT.java
=> test: remove hasUnknownClientIssue and enable JavaScriptReturnValueIT

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PageIT.java
=> test: disable page its because of fusion issue instead hasClientIssue

flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentExporterUtils.java
=> fix: use warn instead of trace for WC exporters discovering

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/NavigationTriggerIT.java
=> test: disable failing part in NavigationTriggerIT instead hasClientIssue

flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
=> fix: avoid NPE in WebBrowser methods

flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractTestBenchTest.java
=> test: remove hasClientIssue and hasUnknownClientIssue TB methods

flow-server/src/main/java/com/vaadin/flow/server/VaadinRequest.java, flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java, flow-server/src/test/java/com/vaadin/flow/server/VaadinRequestTest.java, flow-server/src/test/java/com/vaadin/flow/server/VaadinServletRequestTest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/StreamReceiverHandlerTest.java
=> fix: use getContentLengthLong instead getContentLength 

fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessCheckerTest.java
=> feat!: endpoint access is denied by default

flow-server/src/main/java/com/vaadin/flow/router/internal/RouteSegment.java, flow-server/src/test/java/com/vaadin/flow/server/SessionRouteRegistryTest.java
=> fix: consider first added route as main route and always return it first

flow-server/src/main/java/com/vaadin/flow/router/Location.java, flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java
Also allow locations containing "?" (#3f)
This simplifies location handling and helps with #10449
=> Allow passing null and paths starting with "/" to Location

flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java, flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
This allows creating form based logins using the token
=> Include Spring CSRF parameter name also

flow-server/src/main/java/com/vaadin/flow/server/VaadinContext.java
=> chore: clarify VaadinContext::getAttribute semantic

flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
=> chore: clarify javadocs for VaadinSession::close

fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/EndpointRegistry.java, fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java, fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerMockBuilder.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
=> refactor: separate endpoint registry out from connect controller

scripts/cherryPick.js
when collecting the commits, skip the closed without merged PRs.
=> chore: skip closed but no merged PRs for cherry pick

flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java, flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
=> fix: avoid extra events on route reinitialization

flow-server/src/main/java/com/vaadin/flow/component/dependency/JavaScript.java
=> chore: explain JavaScript annotation behavior

flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
=> chore: mention query parameters in reroute and forward methods

flow-server/src/main/java/com/vaadin/flow/server/frontend/JarContentsManager.java
Compare jar file content and existing
target file content before writing to disk.
=> fix: Compare file content from stream

flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
=> chore: mention query parameters in reroute and forward methods (#10687)

flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
=> chore: mention query parameters in reroute and forward methods (#10687) 

flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts, flow-client/src/test/frontend/AuthenticationTests.ts
Partly fixes #10681
Partly fixes #10682
Connected to https://github.com/vaadin/spring/pull/770
=> Assume a non-redirect response for login requests

flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/BundleLitParserTest.java, flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java, flow-server/src/test/java/com/vaadin/flow/internal/StringUtilTest.java
* fix: properly remove block comments from templates
fixes #10673
=> fix: properly remove block comments from templates (#10701)

fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessCheckerTest.java
=> refactor: delete unnecessary separate case for anonymous users

flow-server/src/main/java/com/vaadin/flow/router/RouteParameters.java, flow-server/src/test/java/com/vaadin/flow/router/RouteParametersTest.java
=> fix: report the parameter name in the exception message

flow-server/src/main/java/com/vaadin/flow/router/HighlightConditions.java, flow-server/src/test/java/com/vaadin/flow/router/HighlightConditionsTest.java
=> fix: improve locationPrefix impl

flow-server/src/main/java/com/vaadin/flow/shared/Registration.java
=> chore: Clarify idempotence of Registrations

flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractTaskClientGenerator.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java, fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
=> chore: reduce amount of info log messages during startup

flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractTaskClientGenerator.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java, fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
=> chore: reduce amount of info log messages during startup (#10738)

flow-server/src/main/java/com/vaadin/flow/theme/Theme.java
Update the javadoc to have the annotation
placement earlier and more visible.
=> chore: update theme javadoc

flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
=> fix: use global node and tools if they are available first

flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java, flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
=> fix: don't update bean property which is read-only bound

flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java, flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
=> fix: don't update bean property which is read-only bound (#10768)

flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractComponentDataGenerator.java, flow-data/src/main/java/com/vaadin/flow/data/provider/ComponentDataGenerator.java, flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataGeneratorTest.java
=> chore: improve component renderer mistakes detection

flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java, flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
=> fix: avoid ConcurrentModificationException in Binder

flow-client/src/main/frontend/Authentication.ts, flow-client/src/test/frontend/AuthenticationTests.ts
This fixes a problem introduced in #10697
=> fix: update CSRF tokens with the ones returned in the login call

flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java, flow-server/src/main/java/com/vaadin/flow/component/WebComponentExporterFactory.java, flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriter.java, flow-server/src/test/java/com/vaadin/flow/component/DefaultWebComponentExporterFactoryTest.java
=> chore: improve exceptions handling in WC exporter handling

flow-server/src/main/java/com/vaadin/flow/component/template/Id.java
=> chore: clarify attribute/property value behavior in templates

flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java, flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Fixes https://github.com/vaadin/flow/issues/10792
=> fix: update attribute name for fetching spring csrf token

flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java
Currently it scares non-frontend developers who scare to touch anything that says .html
=> Improved Java docs for AppShellConfigurator

flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java, flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
=> fix: preserve internal JS UI state properly

flow-server/src/main/resources/plugins/theme-live-reload-plugin/package.json, flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
=> fix: Adapt warning message to 2.6

flow-server/src/main/resources/webpack.generated.js
Fix some lines in webpack.generated
that have duplicated or are used strangely
possibly due to merge resolution.
=> chore: fix probable merge failures

flow-server/src/main/java/com/vaadin/flow/server/auth/AccessAnnotationChecker.java, flow-server/src/test/java/com/vaadin/flow/server/auth/AccessAnnotationCheckerTest.java, fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/EndpointUtil.java, fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
=> feat: Add helpers for using current request and simplify naming

flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
Add missing cleanup of current instances
to tests.
=> chore: add missing cleanup to tests

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
=> fix: upgrade to LitElement 2.5.0 and lit-html 1.4.0 (#10874) (CP: 6.0)

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
=> fix: upgrade to LitElement 2.5.0 and lit-html 1.4.0 (#10874) (CP: 2.6)

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
=> fix: upgrade to LitElement 2.5.0 and lit-html 1.4.0 (#10874) (CP: 2.5)

flow-client/src/main/frontend/Flow.ts, flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java, flow-server/src/main/java/com/vaadin/flow/component/page/History.java, flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RouterLinkView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/HistoryIT.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PopStateHandlerIT.java
=> test: unignore tests in PopStateHandlerIT

flow-migration/src/main/java/com/vaadin/flow/migration/CopyMigratedResourcesStep.java, flow-migration/src/test/java/com/vaadin/flow/migration/CopyMigratedResourcesStepTest.java
=> fix: use trimmed line in imports rewrite

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/NavigationTriggerIT.java
=> test: enable ignored cases in NavigationTriggerIT

flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java
same fixes has been applied to master branch #9763
=> chore: update vaadin-lumo-styles to 1.6.1

flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
=> Always update webpack.generated.js

flow-client/tsconfig.json, flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json, flow-server/src/main/resources/tsconfig.json
Upgrades the TypeScript target to es 2019.
Fixes #10824
=> feat: Upgrade from es2017 to es2019

flow-client/src/main/frontend/form/BinderNode.ts, flow-client/src/test/frontend/form/BinderTests.ts
=> fix(Fusion): binding nullable fields with combo-box throws when clearing

flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/RepeatedAnnotationVisitor.java
Update used ClassVisitor ASM version
from 7 to 8 to support Java16 record
Fixes #10870
=> fix: update the used Opcode from 7 to 8

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
=> Change construct-style-sheets-polyfill to be a runtime dependency

flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
Add fix for flaky test `testNodeDownload`.
=> chore: add fix for download test

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java
=> fix: filter vaadin-core from versions pinning

flow-server/src/main/java/com/vaadin/flow/component/page/Page.java, flow-server/src/test/java/com/vaadin/flow/component/page/PageTest.java
workaround for vaadin/multiplatform-runtime-internal#473
=> fix: don't update cached extended details inside callback

flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java, flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
Fixes https://github.com/vaadin/spring/issues/802
=> Permit access to /themes/**

flow-server/src/main/java/com/vaadin/flow/router/Router.java, flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java, flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationRouteTarget.java, flow-server/src/main/java/com/vaadin/flow/server/ErrorRouteRegistry.java, flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java, flow-server/src/test/java/com/vaadin/flow/router/internal/TestAbstractRouteRegistry.java, flow-tests/pom.xml, flow-tests/test-custom-route-registry/pom.xml, flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomErrorHandler.java, flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomInitListener.java, flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomNotFoundView.java, flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomRoute.java, flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomRouteRegistry.java, flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomServlet.java, flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomServletService.java, flow-tests/test-custom-route-registry/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener, flow-tests/test-custom-route-registry/src/test/java/com/vaadin/flow/custom/CustomRouteIT.java
Make it possible to create a custom RouteRegistry and add test module for it.
Fixes #11022
=> fix: Using a custom RouteRegistry (#11033)

fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/EndpointUtil.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/EndpointUtilTest.java
Fixes https://github.com/vaadin/fusion/issues/10
=> fix: Correctly resolve paths when using a context path

flow-dnd/src/test/java/com/vaadin/flow/component/dnd/AbstractDnDUnitTest.java, flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImplTest.java, flow-polymer-template/src/test/java/com/vaadin/flow/component/AbstractTemplateTest.java, flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/BundleParserTest.java, flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java, flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentTest.java, flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java, flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java, flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/StreamRequestHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java, flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java, flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/startup/fusion/DevModeInitializerEndpointTest.java, pom.xml
related to https://github.com/vaadin/flow-components/issues/997 
related to https://github.com/vaadin/flow-components/pull/998
=> test: fix mockito errors accessing protected API in JDK16

vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeInitializerEndpointTest.java
Fixes https://github.com/vaadin/fusion/issues/15
=> test: mock npm and webpack for endpoint tests

flow-server/src/main/java/com/vaadin/flow/router/Location.java, flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java
=> fix: avoid NPE in Location parsing

fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/IndentationUtils.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/TestUtils.java
Fixes vaadin/fusion#25.
Unfortunately, #11096 didn't fix the CI build, so this is the second attempt. According to the [test build](https://bender.vaadin.com/buildConfiguration/Flow_Flow80_Nightly_ValidateFlowMasterWithWindows/233581?buildTab=overview) it passes correctly.
=> chore: fix CI indentation issue

scripts/cherryPick.js
when CP failed, we ping the `author` and `merging` person together inside the error comment. 
assignee is not a reliable parameter here to use, PRs are not having this field usually. 
fixes https://github.com/vaadin/releases-team-tasks/issues/56
=> chore: ping merged_by when CP failed [skip ci]

fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java, fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java, fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/SchemaGenerator.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGenerationTest.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/nonnullable/NonNullableEndpoint.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/complexhierarchyendpoint/expected-model-complexhierarchymodel.GrandParentModel.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/inheritedmodel/expected-model-core.Version.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-JsonTestEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-model-core.Version.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-openapi-custom-application-properties.json, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-openapi.json, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/nonnullable/expected-model-nonnullable.NonNullableEndpoint.NonNullableModel.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/expected-PersonEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
=> fix: make primitive types non-nullable by default in generated TS file

flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java, flow-server/src/test/java/com/vaadin/flow/router/RouteNotFoundErrorTest.java
=> fix: set routes first into the template

flow-plugins/flow-gradle-plugin/build.gradle, flow-plugins/flow-gradle-plugin/pom.xml
=> chore: Add javadoc creation for gradle plugin [skip ci]

flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt, flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/TestUtils.kt
=> test: fix Gradle plugin MiscSingleModuleTest::testNodeDownload test

flow-plugins/flow-gradle-plugin/build.gradle, flow-plugins/flow-gradle-plugin/pom.xml
Generate javadoc jar for the gradle plugin.
=> chore: Add javadoc creation for gradle plugin

flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java, flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
Fixes issue with multiple concurrent
requests to jar resource.
Fixes #11144
=> fix: Handle concurrent file requests

flow-migration/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
Add input filtering so we only handle
class files from the classpath in
ReflectionsClassFinder
Closes #10304
=> fix: Add reflections input filter (#10333)

flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java, flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
=> fix: remove href attribute for disabled Anchor

flow-client/package.json, flow-client/src/main/frontend/form/Validators.ts, flow-client/src/test/frontend/form/ValidatorsTests.ts, flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java, flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
=> fix: keep package.json ordered

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
=> fix: keep package.json ordered (#11179)

flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/routing/NavigationException.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/routing/NavigationExceptionHandler.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/routing/NavigationExceptionLayout.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/routing/NavigationExceptionTargetView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/InfiniteRerouteLoopIT.java
=> fix: don't use ISE to test infinite loop for HasErrorParameter

flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java, flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
=> fix: remove href attribute for disabled Anchor (#11121)

flow-server/src/main/java/com/vaadin/flow/server/startup/LookupServletContainerInitializer.java, flow-server/src/test/java/com/vaadin/flow/server/startup/LookupServletContainerInitializerTest.java
=> fix: avoid NPE in LookupServletContainerInitializer

.github/ISSUE_TEMPLATE.md
Kudos to @felix-seifert for the heads up.
Fixes #11222
=> chore: update issue template link to SO [skip-ci]

fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGenerationTest.java, fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/model/ComplexTypeParamsEndpoint.java, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/collectionendpoint/expected-CollectionEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/datetime/expected-DateTimeEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/enumtype/expected-EnumEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/inheritedmodel/expected-InheritedModelEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-JsonTestEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-openapi-custom-application-properties.json, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-openapi.json, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/model/expected-ComplexTypeParamsEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/model/expected-ModelEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/modelpackage/expected-ModelPackageEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/modelpackage/expected-SubModelPackageEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/nonnullable/expected-NonNullableEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/sameclassname/expected-SameClassNameEndpoint.ts, fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/expected-PersonEndpoint.ts
=> fix: use nullable but required arguments for endpoint functions

flow-client/src/main/java/com/vaadin/client/WidgetUtil.java, flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java, flow-tests/test-root-context/frontend/lit-templates/InjectedTemplate.js, flow-tests/test-root-context/frontend/lit-templates/InjectingTemplate.js, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/InjectedTemplateView.java, flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/InjectingTemplateView.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/InjectingTemplateIT.java
=> fix: Use JS equals to check whether property value is changed

flow-client/pom.xml
(cherry picked from commit d17359acea9f0ef42c2f0d751bb92028ae047d0d)
=> chore: Pin org.eclipse.equinox.common version (#11247)

pom.xml
Add the module to the correct modules
listing.
=> chore: add the jandex module

scripts/cherryPick.js
=> chore: fixing the missing $ identifier in CP script [skip ci]

scripts/cherryPick.js
get the merged_by.login info from the commit url, while those info are not present in the collection.
=> chore: get the merged_by.login from commit url [skip ci]

fusion-endpoint/src/main/java/com/vaadin/fusion/VaadinConnectControllerConfiguration.java, fusion-endpoint/src/main/resources/META-INF/spring.factories
use the full class name of VaadinConnectController for Spring to discover.
=> chore: fix for Spring

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
=> fix: order only dependencies inside package.json

flow-lit-template/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java, flow-polymer-template/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java, flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java, flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java, flow-server/src/test/java/com/vaadin/flow/server/VaadinServletServiceTest.java
=> fix: use ServletContext classloader as a default classloader for service

flow-server/src/main/java/com/vaadin/flow/router/RouteConfiguration.java, flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
=> fix: provide info about navigation target in NotFoundException

flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html, flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js
=> fix: don't propogate clieck even in the component renderer

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
=> fix: order only dependencies inside package.json (#11318)

flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
=> chore: add excludepattern

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
=> fix: don't create a new UI instance for service worker resource

flow-data/src/main/java/com/vaadin/flow/data/renderer/NumberRenderer.java, flow-data/src/test/java/com/vaadin/flow/data/renderer/NumberRendererTest.java
=> fix: format numbers in NumberRenderer using Locale if it's provided

flow-server/src/main/java/com/vaadin/flow/router/InvalidLocationException.java, flow-server/src/main/java/com/vaadin/flow/router/Location.java, flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java, flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java, flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
=> fix: use dedicated exception for Location validation

flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/TemplateModelProxyHandler.java
=> fix: use proper classloader for template model

flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
=> fix: don't create a new UI instance for service worker resource (#11372)

pom.xml
=> fix: upgrade bytebuddy version for Java 18

flow-server/src/main/java/com/vaadin/flow/router/InvalidLocationException.java, flow-server/src/main/java/com/vaadin/flow/router/Location.java, flow-server/src/main/java/com/vaadin/flow/router/Router.java, flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java, flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java, flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java, flow-server/src/test/java/com/vaadin/flow/server/BootstrapContextTest.java
=> fix: use dedicated exception for Location validation (#11367)

flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java, flow-data/src/main/java/com/vaadin/flow/data/binder/BinderValidationErrorHandler.java, flow-data/src/main/java/com/vaadin/flow/data/binder/DefaultBinderValidationErrorHandler.java, flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java, flow-data/src/test/java/com/vaadin/flow/data/binder/DefaultBinderValidationErrorHandlerTest.java
part of #10598, replacement for #10683
=> feat: extract validation error handler from Binder

flow-server/src/main/java/com/vaadin/flow/component/dependency/Uses.java
=> fix: undeprecate Uses

flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
=> fix: use dedicated namespace for fallback style imports

flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
fixes slow tests build failure
=> fix: correct unit test for serializing VaadinSession

flow-data/src/main/java/com/vaadin/flow/data/binder/BeanPropertySet.java, flow-data/src/test/java/com/vaadin/flow/data/binder/BeanPropertySetTest.java
=> fix: avoid merge conflicts during properties collection

flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
=> fix: don't check logger in frontend version validation test

flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
=> fix: don't check logger in frontend version validation test (#11463)

flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/MockLogger.java
Update the log check to not use
a file as it will most likely bring in
problems in concurrent execution
=> fix: update mock logging

flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/MockLogger.java
Update the log check to not use
a file as it will most likely bring in
problems in concurrent execution
=> fix: update mock logging (#11464)

flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InvalidateHttpSessionIT.java
=> fix: remove extra assertion

flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
=> fix: use package json file in unit tests

flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
=> test: use package json file in unit tests (#11491)

flow-server/src/main/java/com/vaadin/flow/dom/ElementUtil.java, flow-server/src/test/java/com/vaadin/flow/internal/UsageStatisticsExporterTest.java, flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java, pom.xml
=> feat!: update jsoup version

drivers.xml, flow-client/intern.json
=> chore: update ChromeDriver to 92

flow-server/pom.xml
=> fix: add JSR305 to the generated Karaf feature

drivers.xml
=> chore: update chrome driver to 92 (2.6)

drivers.xml
=> chore: update chromedriver to 92 (2.7)

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
=> fix: update workbox version to prevent webpack failure

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
=> fix: update workbox version to prevent webpack failure (#11527)

flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Fixes: https://github.com/vaadin/flow-components/issues/1914
=> fix: clean up the old listeners of data provider

flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
Clean up default dependencies and
devDependencies if they have changed.
Fixes #11561
=> fix: clean up managed default versions

flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java, flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
Clean up default dependencies and devDependencies if they have changed.
Fixes #11561
=> fix: clean up managed default versions (#11563)

flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
Related-to #9544
(cherry picked from commit 61a7fd9a2f8eee5634827dfed3a99dfe2ab64760)
=> feat(TypeScript): add Frontend path alias (#9898) (CP: 2.7)

flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java, flow-server/src/test/java/com/vaadin/tests/server/SerializationTest.java
=> fix: set the lock field to a fake lock for unbound session

pom.xml
Latest version improves handling of weird HTML and XML along with some smaller fixes
=> Update to JSoup 1.14.2

fusion-endpoint/src/main/java/com/vaadin/fusion/generator/SchemaGenerator.java, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/collectionendpoint/expected-model-collectionendpoint.CollectionEndpoint.Collection.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-core.Version.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-inheritedmodel.InheritedModelEndpoint.ChildModel.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-media.ArraySchema.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-media.Discriminator.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-media.Schema.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-media.XML.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-models.ExternalDocumentation.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/json/expected-model-core.Version.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/json/expected-model-json.JsonTestEndpoint.Role.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/json/expected-model-json.JsonTestEndpoint.User.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/json/expected-openapi-custom-application-properties.json, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/json/expected-openapi.json, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/model/expected-model-model.ModelEndpoint.Account.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/model/expected-model-model.ModelEndpoint.Group.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/model/expected-model-subpackage.ModelFromDifferentPackage.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/modelpackage/expected-model-modelpackage.ModelPackageEndpoint.Account.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/modelpackage/expected-model-subpackage.Account.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/nonnullable/expected-model-nonnullable.NonNullableEndpoint.NonNullableModel.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/sameclassname/expected-model-subpackage.SameClassNameModel.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/selfreference/expected-model-selfreference.SelfReference.ts, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/tsmodel/expected-TsFormEndpoint.ts
=> fix: generate model fields in the same order as in Java

flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Add new versions to the NPM blacklist.
Update information on that to do about
having an blacklisted version.
Touches #11584
=> fix: blacklist npm versions

client/lerna.json, client/package.json, client/packages/client-common/package.json, client/packages/client-fusion/package.json
- Use `npm` as a client for `lerna`.
- Update dependencies to the latest version.
- Update packages versions to the latest platform version
=> chore(client): fix CI issues

flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java, flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java
Fixes #11025
Co-authored-by: Pekka Hyvönen <pekka@vaadin.com>
=> fix: filter vaadin-core from versions pinning (CP: #11027) (#11037)

flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
See RouteConfiguration#getUrl for reference
see: https://github.com/vaadin/flow/issues/11502
=> documentation: Add missing throws in JavaDocs [skip ci]

flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java, flow-server/src/test/java/com/vaadin/flow/server/auth/AccessAnnotationCheckerTest.java
=> Always allow the client placeholder view to be loaded

flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
Fixes regression caused by #11635
Fixes #11666
(cherry picked from commit 9cc240b2e7737336f8a45c810571099518fefb1e)
=> fix: not fail for missing window.Vaadin.Flow (CP: 7.0)

flow-server/src/main/resources/plugins/application-theme-plugin/package.json, flow-server/src/main/resources/plugins/stats-plugin/package.json
=> fix: add mkdirp as default devDependency

flow-server/src/main/java/com/vaadin/flow/component/page/History.java, flow-server/src/main/java/com/vaadin/flow/router/Location.java, flow-server/src/main/java/com/vaadin/flow/router/LocationUtil.java, flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java, flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, flow-server/src/test/java/com/vaadin/flow/component/InvalidUrlTest.java, flow-server/src/test/java/com/vaadin/flow/component/page/HistoryTest.java, flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java, flow-server/src/test/java/com/vaadin/flow/router/QueryParametersTest.java, flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java, flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java, flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java, flow-tests/test-root-context/src/test/java/com/vaadin/flow/InvalidLocationIT.java
=> Cherry picking two changes to 2.7

README.md
=> chore: update 8.0 release info in readme [skip ci]

flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java, flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
=> fix: remove the sw referer filter when adding csrf token (#11767)

flow-jandex/pom.xml
=> Revert "chore(deps): bump jandex-maven-plugin from 1.1.0 to 1.2.0"

fusion-endpoint/pom.xml, fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-media.Schema.ts
=> fix: Downgrade to swagger-codegen-generators 1.0.20

pom.xml
=> chore: remove extra profile

flow-tests/pom.xml
=> chore: clean up test from extra profiles
