- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
We should install pnpm, but with a stubbed
npm no pnpm will be installed to .vaadin
and the test will fail trying to execute pnpm.
Fixes #7848
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7909)
> Don't stub npm as pnpm should be installed

- flow-server/src/main/resources/webpack.generated.js
In development mode we do not use
the build folder, but creating it on
runtime may make for instance Jetty
restart due to changes in scanned packages.
Fixes #7922
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7969)
> Do not create buildFolder in dev mode

- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
- flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
Jetty closes the WS connection after 5 minutes, other servers may have other similar timeouts. Added a 3 minute interval heartbeat to keep the live-reload connection alive.
Fixes #7959
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7976)
> Live-reload sends a heartbeat to keep the dedicated push channel alive

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
If npm install has failed in the middle of
extraction only a .staging folder will
exist  in node_modules and we should
execute npm install on application startup.
Fixes #7972
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7979)
> Run npm install if only .staging

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
Development mode gizmo and live-reload logic at the moment does not support the embedded webcomponent use-case, so disable it. Fixes #7991.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7993)
> Disable development mode gizmo for exported webcomponents

- flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
This modification introduces the "Dev Mode already started" flag and mainly addresses `WebLogic`+`Spring-boot` configuration (or any other configuration where `Spring-Boot` is started within a web server/servlet container), where two sequential Dev Mode runs lead to `webpack` compile failures and significant startup time increase.
Setting this flag in `DevModeInitializer` helps `DevModeServletContextListener` to identify either Dev Mode has been already started and just skip pnpm and webpack.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/7990)
> IllegalStateException when running a Vaadin Spring project on WebLogic server #502

- flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializerTest.java
Logs an error instead, which is not very visible but prevents breaking any existing apps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8013)
> Do not throw for @ParentLayout w/o RouterLayout

- flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
- flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfigurationTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
Fixes #8010
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8016)
> [Security Fix]Use Vaadin's own ObjectMapper instead of the one from Spring

- flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
- flow-tests/pom.xml
- flow-tests/test-dev-mode/pom.xml
- flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
- flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadIT.java
- pom.xml
Live reload is disabled from use
Also jrebel plugin will not be
released after this patch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8030)
> Disable live reload

- flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
To prevent it from being included to the compiled client JS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8045)
> Remove devmode widget inclusion from TS

- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
- flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadIT.java
Fixes #7835 
Applied new styling for Live Reload UI.
Additionally, Live Reload notifications now move to message tray 5s (5000ms) after reload.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8068)
> Style and beautify Live Reload (#7835)

- flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.d.ts
- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/frontend/PreserveOnRefreshLiveReloadView.java
- flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/PreserveOnRefreshLiveReloadIT.java
For `@PreserveOnRefresh`-annotated views, the live reload behavior is not be intuitive since the view instance is re-used on reload (for instance, modifications to the view's constructor are not reflected after live reload). 
Fixes #7819.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8070)
> Show alert when using @PreserveOnRefresh together with live reload

- flow-server/pom.xml
- flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/rest/BeanWithJacksonAnnotation.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/rest/EndpointWithRestControllerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/rest/VaadinConnectEndpoints.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/ArrayConversionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/BaseTypeConversionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/BeanConversionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/BooleanConversionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/ByteConversionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/CharacterConversionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/CollectionConversionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/DateTimeConversionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/DoubleConversionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/EnumConversionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/FloatConversionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/IntegerConversionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/LongConversionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/MapConversionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/ShortConversionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/StringConversionTest.java
1. Use `Jackson2ObjectMapperBuilder` from Spring application context to build a `Jackson2ObjectMapper`
2. Add `jackson-datatype-jsr310` to ensure data format
3. Enable ignored tests
4. Add test for LocalTime format
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8095)
> Fix endpoint serialization problems

- flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiAccess.java
This should have been fixed initially in `2.2` branch but `2.2` has no any OSGi support for different reason (see #8109). So it can't be tested there.
Fixes #8105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8110)
> Be aware of skinny war workaround in OSGi support

- flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Fixes the loadingFsResources_usesVfsProtocol_allFilesExist
on windows as Paths.get() uses wrong separator
that doesn't work with URLs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8117)
> Fix vfs resource test

- flow-bom/pom.xml
To be able to depend on `flow-jrebel-plugin` of correct version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8123)
> Manage flow-jrebel-plugin version under flow-bom

- flow-server/src/main/java/com/vaadin/flow/server/PWA.java
Deprecates PWA `enableInstallPrompt` method from Flow (#8038)
Add `@Deprecated` tag and `@deprecated` javadoc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8167)
> Deprecate enableInstallPrompt() method (#8038)

- flow-server/src/main/java/com/vaadin/flow/server/PWA.java
Part of #8038 
Change javadoc in order to call attention on the phase out of PWA Install Prompt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8179)
> Change PWA javadocs to reflect phase out of Install Prompt

- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
- flow-client/src/test/frontend/VaadinDevmodeGizmoTests.js
- flow-client/webpack.tests.config.js
gitpod.io maps URLs as https://port-hostname and all ports use the standard https port
Fixes #8009 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8190)
> Support live reload on gitpod.io

- flow-test-util/src/main/java/com/vaadin/flow/testcategory/PushTests.java
- flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
- flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/FrontendProtocolIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/AbstractFrontendInlineIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/AnnotatedFrontendInlineIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/DependenciesLoadingAnnotationsIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/FrontendInlineApiIT.java
Tests need changes as
chrome dropped HtmlImport support.
Fixes #8192
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8209)
> Update tests for polyfill

- flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
- flow-server/src/main/resources/webpack.generated.js
Produces around 2000 rows less output in the production build.
The progress output for a CI build is not relevant and is in the way
when looking for build problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8227)
> Do not print webpack progress output in a production build

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
- Enable / disable all validators on Binder level
- Enable / disable validators on Binding level
- add writeBeanAsDraft(bean,boolean) for writing draft bean with validators disabled
Fixes: #5030
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8094)
> Add methods to control validation

- flow-client/pom.xml
- flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java
- flow-client/src/main/java/com/vaadin/client/ExecuteJavaScriptElementUtils.java
- flow-client/src/main/java/com/vaadin/client/ScrollPositionHandler.java
- flow-client/src/main/java/com/vaadin/client/flow/ExecuteJavaScriptProcessor.java
- flow-client/src/main/java/com/vaadin/client/flow/RouterLinkHandler.java
- flow-server/src/main/java/com/vaadin/flow/component/UI.java
- flow-server/src/main/java/com/vaadin/flow/router/ErrorNavigationEvent.java
- flow-server/src/main/java/com/vaadin/flow/router/NavigationEvent.java
- flow-server/src/main/java/com/vaadin/flow/router/NavigationTrigger.java
- flow-server/src/main/java/com/vaadin/flow/router/Router.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/InternalRedirectHandler.java
- flow-server/src/test/java/com/vaadin/flow/component/UITest.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/NavigationTriggerView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PostponeProceedView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RouterLinkView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/NavigationTriggerIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PostponeProceedIT.java
- flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java
Part of #3619, fix items 1 and 2 from https://github.com/vaadin/flow/issues/3619#issuecomment-613389430
* Push browser history state after navigation is certain because in case
of `postpone` the URL in the address bar is changed too early and the 
navigation process might not proceed
* Remove adding to history state from `RouterLinkHandler` as the 
server-side does the same job at the correct time
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8125)
> Push browser history state after postponed navigation proceeds

- flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.d.ts
- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
- flow-client/src/test/frontend/VaadinDevmodeGizmoTests.js
- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
This handles non-default paths when establishing the WebSocket connection (e.g. Vaadin Spring expects `/vaadinServlet`). Fixes #8205.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8280)
> Live-reload: Accept push target parameter `liveReloadPath`

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
Generate a full hash to mainPackageJson
and store it after npm install to
node_modules/.vaadin
Fixes #8182
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8294)
> Store vaadin hash to node_modules 2.1

- flow-tests/README.md
- flow-tests/pom.xml
- flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
- flow-tests/test-live-reload/pom.xml
- flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/LiveReloadView.java
- flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshLiveReloadView.java
- flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
- flow-tests/test-live-reload/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
- flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/AbstractLiveReloadIT.java
- flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/LiveReloadIT.java
- flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshLiveReloadIT.java
Live reload tests must never execute in parallel with other tests since they will trigger a reload
in all open UIs, interfere with concurrently running tests. Having them in a separate test module
makes them more isolated. Also test with non-root context.
Fixes #8296 (and possibly #8310).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8324)
> Extract live reload ITs into separate test module

- flow-client/src/main/java/com/vaadin/client/flow/RouterLinkHandler.java
Fixes https://github.com/vaadin/flow/issues/8308
Using felix-jetty RouterSessionExpirationIT.navigationAfterSessionExpired fails due to session expired when using a router link.
https://bender.vaadin.com/viewLog.html?buildId=145588&buildTypeId=Flow_Nightly_FlowFelixJettyIntegrationTests21
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8354)
> Fix RouterSessionExpirationIT OSGi failure on 2.1

- flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/StreamResourceRegistryTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/StreamRequestHandlerTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/StreamResourceView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java
should fix #5360
see https://stackoverflow.com/a/31612226/1296333
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8271)
> Properly encoded URIs use %20

- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshIT.java
To prevent flaky test from appearing after #7587 is fixed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8340)
> Wait for intermediate page to load completely in @PreserveOnRefresh IT

- flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Presence or absence of a custom Connect client in `frontend/connect-client.ts` should not affect the URL mapping of the endpoint calls handler on the backend (the way to configure that mapping is to use the `vaadin.endpoint.prefix` application property). There is no need to parse the `connect-client.ts` and try to determine the URL mapping from there.
Earlier, when the support for a custom Connect client was added in https://github.com/vaadin/flow/pull/7944, the code that tried to determine the endpoint handler URL mapping from a custom `connect-client.ts` file had a bug that resulted in an incorrect URL mapping configuration.
This commit completely removes the link between a custom Connect client and the endpoint handler URL mapping config.
NOTE: an integration test is added to the …
> fix: custom connect client breaks endpoints mapping

- flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts
- flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts
- flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts
- flow-client/src/test/frontend/FormValidatorTests.ts
Fixes: https://github.com/vaadin/flow/issues/7940
- Do not use field-conversor in object models (fix check-group value arrays)
- Do not generate empty objects but null on createEmpty (fix clear time-picker)
- Adding strategies for checked and selected components
- Better stragegy selector for elements (checkbox, radio, listbox, rich-editor)
- fix NotEmpty validator so as it can check arrays (fix check-group arrays)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8378)
> vaadin elements strategies 

- flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
- flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
The Live Reload UI is not available in compatibility mode. Part of #8388.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8396)
> Disable Live Reload in compatibility mode

- flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
- flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java
- flow-tests/test-root-context/frontend/HiddenTemplate.js
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RemoveAddVisibilityView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/HiddenTemplateView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RemoveAddVisibilityIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/HiddenTemplateIT.java
Fixes #8100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8419)
> Don't override initial value of hidden HTML Element attribute.

- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
- flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/PushView.java
- flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RedirectToPushIT.java
Fixes #8283 
This is broken since https://github.com/vaadin/flow/pull/7838 
Problem is that in client-side routing, push mechanism only can be configured once, and it happens in the AppShell class, earlier to compute the server target route.
This fix needs to be cherry-picked in 3.1 series (v16)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8435)
> Fix regression in @Push when running in client bootstrapping

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/resources/pnpmfile.js
Fixes #8432 
Update pnpmfile.js to force all chokidar versions to ^3.4.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8451)
> Force chokidar version to ^3.4.0 (#8432)

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/SizeChangeEvent.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/SizeChangeListener.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorTest.java
DataCommunicator now fires size
change event for the component when
data size or dataprovider changes.
Fix DataCommunicator components for #8345
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8450)
> Add size event firing

- flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/NavigationTriggerIT.java
Fixes partially https://github.com/vaadin/flow/issues/8420
(check `UI_NAVIGATE is not used from JavaScriptBootstrapUI.navigate.` in partially fixed issue)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8463)
> Use UI_NAVIGATE when invoking routing from navigate.

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
If you use container (such as the latest Wilfdly) which forces to use significantly newer version of Jsoup than Vaadin depends to, this can cause a problem as deprecated method as been removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8325)
> Removing deprecated parameter from DataNode constructor

- flow-server/src/main/java/com/vaadin/flow/server/startup/NavigationTargetFilter.java
When mentioning `ServiceLoader` and the file to be used, there is a typo in the path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8467)
> Fix Javadoc typo in NavigationTargetFilter

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/resources/webpack.generated.js
Part of #8351 
Add lit-element as a default runtime dependency
Exclude VaadinDevmodeGizmo.js from production webpack bundle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8462)
> lit-element as a default runtime dependency (#8351)

- flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
Removes highlighting blocks, extra whitespace and changes output block
about application start up to a oneliner.
Fixes #8404, #8395
Related to #8104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8471)
> Quiet down logs for deployment

- flow-client/src/main/java/com/vaadin/client/ElementUtil.java
- flow-tests/test-root-context/frontend/template-without-shadow-root-view.js
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/PolymerTemplateWithoutShadowRootView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/PolymerTemplateWithoutShadowRootIT.java
This makes lookup work even if there are multiple elements with the same id defined globally
Fixes #8482
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8483)
> Always lookup DOM elements inside the given context and not globally

- flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
It was missed when removing the `VaadinDevmodeGizmo` module from the production bundle that it is indeed possible to run an app in dev mode using prebuilt bundles (although not recommended / supported). In this case the client side should not try to load the module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8489)
> Disable devmode gizmo if production bundles but no devserver

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateConnect.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateConnectTest.java
This commit fixes the TypeScript generator so that when a custom Connect client exists, it is imported into the generated TypeScript endpoint wrappers with a relative path (`../connect-client`) instead of an absolute path (`C:/Users/me/work/my-app/frontend/connect-client`).
Fixes: #8487
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8488)
> fix: import custom Connect client with a relative path

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateConnect.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateConnectTest.java
This commit fixes the TypeScript generator so that when a custom Connect client exists, it is imported into the generated TypeScript endpoint wrappers with a relative path (`../connect-client`) instead of an absolute path (`C:/Users/me/work/my-app/frontend/connect-client`).
(cherry picked from commit 8325a1fed04ab9f2855eba658dec33309671e19b / PR #8488)
> 8488 3.1 cherry-pick  (Import custom Connect client with a relative path)

- drivers.xml
- flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/DefaultValueInitializationIT.java
- flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/EmbeddedWebComponentIT.java
- flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/EmbeddingChromeBrowserTest.java
- flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/FactoryExporterIT.java
- flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/FireEventIT.java
- flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/NpmOnlyIndexIT.java
- flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/PreserveOnRefreshIT.java
- flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/PushAnnotationIT.java
- flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/UpdatePropertyIT.java
- flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/WebComponentIT.java
Fixes #8329. With Chrome dropping native HTML imports and the compatibility mode test for embedded webcomponents relying on polyfill, a race condition had appeared where the shadowroot was not yet attached during test run. Now waits for at least one shadowroot before commencing the test. 
Update: should squash when merging.
> Fix race condition in embedding tests

- flow-data/src/main/java/com/vaadin/flow/data/renderer/RendererUtil.java
- flow-data/src/test/java/com/vaadin/flow/data/renderer/RendererUtilTest.java
in case where the element is attached several times during the same roundtrip.
Fixes vaadin/vaadin-grid-flow#837
With these changes, the event listener is added synchronously instead of `beforeClientResponse`, so that it gets removed before the next attach.
Also, fixed a minor memory leak: The detach listeners were never removed, so re-attaching a component with template renderers was accumulating redundant listeners (see the third commit).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8428)
> Fix duplicate event listeners in TemplateRenderer

- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Partial redesign of the UI design. Wanted to clean up the visual hierarchy and improve the usability of the notifications (dismissing and the “don’t show again” feature).
As a disclaimer: I didn’t pay any attention to accessibility, as it looked like that wasn’t a concern previously either (color contrast, keyboard or screen reader usability). The gizmo is only usable with a mouse or a touch device, and by sighted people.
Apologies for the unnecessary white-space changes (my IDE does the formatting automatically). I didn’t bother leaving those out.
Not super happy about the code quality, but it does the job.
- Refined typographic styles (slightly smaller overall)
- Visually detached the gizmo and notifications from the edge of the browser
- Added a blue color for “information” messages
- …
> Usability and visual design improvements for devmode gizmo and notifications

- flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
Adding support for listening for shortcuts on multiple components #7339 broke binary compatibility.
This is problematic for any addon that would now need a new release on top of Flow 2.2.
Fixed the weirdly formulated javadocs.
Fixes vaadin/vaadin-button-flow#162
> Retain binary compatibility for listenOn method

- flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
Closes #8541. 
Note: Fix needs to be picked to master also, but will require some adaptation to the TS bootstrapping as the `flow-client` method for computing the URL with context root is not available there.
> Live reload: construct correct push URL when both service URL (and context path) and liveReloadPath are given

- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/PropertyChangeDeniedException.java
- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/PropertyChangeVetoException.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/MapSyncRpcHandler.java
- flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMapTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/MapSyncRpcHandlerTest.java
> Throw an exception which provides an info about vetoed property change

- flow-client/src/main/java/com/vaadin/client/LitUtils.java
- flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
- flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplate.java
- flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateDataAnalyzer.java
- flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateInitializer.java
- flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdCollector.java
- flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdMapper.java
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
- flow-tests/test-root-context/frontend/lit/simple-lit-template-no-shadow-root.js
- flow-tests/test-root-context/frontend/lit/simple-lit-template-shadow-root.js
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/LitPerson.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateNoShadowRootView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateShadowRootView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateNoShadowRootIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateShadowRootIT.java
Supports @Id mapping in the same way as PolymerTemplate
Contrary to PolymerTemplate, contains no special support for template in template, @Uses or a template model.
Properties of the template can be set on the server using the property API in `getElement()`
Limitations in this commit:
* The template is not parsed on the server so no attributes can be made available for mapped components
* All types of templates are allowed by default although we need to consider whether only static HTML should be accepted without an additional opt-in
Intentionally left out:
* Model support is intentionally left out as it causes problems when mixing with @Id mapping. The template should in most/all cases be used so that all UI logic is on the server (using @Id mapping) or all UI logic is in the browser …
> Basic LitTemplate support based on LitElement for Java UIs

- flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.d.ts
- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
- flow-client/src/test/frontend/VaadinDevmodeGizmoTests.js
- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
Same as #8542, but computes the live reload push URI in `Flow.ts` instead of GWT code.
> Adapt fix #8542 for #8541 to CCDM bootstrap (Flow.ts)

- flow-data/src/main/java/com/vaadin/flow/data/provider/HasDataView.java
Require components to implement
the getDataView() method that
returns at minimum the generic DataView
but if created a more specific DataView.
> Require getDataView()

- flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
Fixes #8446
Create a mechanism in VersionJsonFilter to force peer dependencies in pnpm if a specific version is written in the package.json project dependencies.
> Add peer dependency forcing mechanism to VersionsJsonFilter

- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractLazyDataView.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/HasLazyDataView.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/LazyDataView.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/HasLazyDataViewTest.java
Removes the public API for data communicator. Adds unit tests for undefined
size APIs for data communicator, except for default page increase since
that is likely to still change.
> Add an AbstractLazyDataView

- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
If item is moved from before
the target item the item index
was wrong as the old item was removed.
> Fix adding existing item

- flow-server/src/main/java/com/vaadin/flow/component/dependency/JavaScript.java
The `master` branch has no compatibility mode.
So it should not be mentioned.
This should be either taken with dramatic changes into `2.x` branches or should not be cherry-picked at all.
> Use correct javadocs for JavaScript annotation in the master btanch.

- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/IdentifierProvider.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/IdentityProvider.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
- flow-data/src/test/java/com/vaadin/flow/tests/data/bean/Item.java
Custom identity provider now could be set globally through DataView interface and this also will affect the components.
See components PRs:
- https://github.com/vaadin/vaadin-select-flow/pull/82
- https://github.com/vaadin/vaadin-checkbox-flow/pull/155
- https://github.com/vaadin/vaadin-grid-flow/pull/1044
> Configure identity provider for a components through the Data View

- flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts
- flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
- flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts
- flow-client/src/main/resources/META-INF/resources/frontend/form/Validation.ts
- flow-client/src/test/frontend/form/ValidationTests.ts
- flow-client/tsconfig.json
- `ValidationCallback` may now return a single `ValidationResult` or an array of `ValidationResult` objects which don't need to specify the `value` or `validator` properties which were needed previously when `ValueError` was used in the return type.
- `ValidationResult` may contain an optional `message` property for overriding the default error message (coming from validator) for a specific property.
- `ValueError` now also directly has a `message` property so it's slightly simpler to get the error messages when working with a list of errors.
- Update `flow-client` tsconfig to allow using `Array.flat()` etc.
- Add Binder as a parameter to `ValidationCallback`
Fixes #8552
> Simplify ValidationCallback return type

- flow-server/src/main/java/com/vaadin/flow/dom/Element.java
- flow-server/src/main/java/com/vaadin/flow/internal/JsonUtils.java
- flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
- flow-server/src/test/java/com/vaadin/flow/internal/JsonUtilsTest.java
> Support Element.setPropertyBean

- flow-server/src/main/java/com/vaadin/flow/dom/Element.java
- flow-server/src/main/java/com/vaadin/flow/internal/JsonUtils.java
- flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
- flow-server/src/test/java/com/vaadin/flow/internal/JsonUtilsTest.java
Fixes #7308
Based on #8584 to avoid unnecessary conflicts
> Support Element.setProperty for lists and maps

- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewListenerTest.java
Provide a modifiable collection to data provider in  `GridListDataViewTest.addSizeChangeListener_sizeChanged_listenersAreNotified`, since the test expects modifying the data source to get the size change events.
> Make the items collection modifiable for data view listener test

- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
setPreservedChain doesn't store Location in the cache but only a path.
This is logically correct for the router functionality since routing
considers only path and not parameters. But the same view (and same UI)
should not trigger preserve on refresh logic if they only differ with a
parameter.
Fixes #8605
> Don't use preserve on refresh logic in case of the same UI

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Currently FrontendTools nor NodeTasks.Builder
doesn't allow you to override the node.js download URL. However, in firewalled corporate
environments the node.js may be served from an intranet server.
Fixes #8603
The PR should be also merged into the 2.3 branch so that it will be present in Vaadin 14.3.
> Allow Vaadin plugins to configure node download URL and version

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
* Allow Vaadin plugins to configure node download URL and version
https://github.com/vaadin/flow/issues/8603 . Currently FrontendTools nor NodeTasks.Builder
doesn't allow you to override the node.js download URL. However, in firewalled corporate
environments the node.js may be served from an intranet server.
* #8603 initialize FrontendTools and TaskRunNpmInstall fields in ctor
* #8603 add test for FrontendTools.nodeVersion and nodeDownloadRoot
* #8603 fixed javadoc
Cherry-pick of https://github.com/vaadin/flow/pull/8611 into the 2.3 branch.
> Allow Vaadin plugins to configure node download URL and version (#8611)

- flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HasHierarchicalDataProvider.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HasHierarchicalDataProviderTest.java
HasHierarchicalDataProvider cannot extend HasDataProvider anymore.
Removes "flat data" API from HasHierarchicalDataProvider so it does not
cause compile errors for tree grid which extends grid and implements
HasHierarchicalDataProvider. This is a breaking change.
Grid part in https://github.com/vaadin/vaadin-grid-flow/pull/1057
Part of vaadin/vaadin-grid-flow#1027
> Fix hierarchy for HasHierarchicalDataProvider

- flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
- flow-client/tsconfig.json
Related to #8658. Avoids the issue for now, but the issue still needs a proper fix later so we can start using less conservative tsconfig options in Flow without breaking/affecting user projects.
> Avoid tsconfig issue #8658 for now

- flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts
- flow-client/src/test/frontend/form/ValidatorsTests.ts
- the default error messages in the built-in client-side validators are  interpolated in the same way as on the server-side
- custom error messages (e.g. `@Size(message = "my message {min} {max}")` are not interpolated
Fixes #8385
> fix: use default JSR-380 error messages in client-side validators

- flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- only import the validators that `@vaadin/form` really needs (instead of the entire `validators` module)
- declare the `@vaadin/form` module as having no side effects to let Webpack more aggressively remove unused code imported from `@vaadin/form`. See more details in https://webpack.js.org/guides/tree-shaking/
~Merge https://github.com/vaadin/flow/pull/8673 first.~
Before this PR using `@vaadin/form` would always add all validators (**13kB gzip**) to the app bundle.
After this PR using `@vaadin/form` would add only the actually used validators.
E.g. `@NotBlank`, `@Size` and `@Email` would add **2.12kB gzip**
```java
public class Employee {
@NotBlank
private String firstname;
@NotBlank
private String lastname;
private String title;
@Size(min = 1, max = 16)
@Email(message = "Please enter …
```
>  feat: enable effective tree shaking for @vaadin/form

- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/ItemCountChangeEvent.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataViewTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewListenerTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Adds isCountEstimated() to ItemCountChangeEvent.
If item count estimate allows the user to scroll way past the exact count,
DataCommunicator will now resolve the exact count immediately instead of
returning 0 items and new size to the client, which would have to keep
requesting items until the end was reached.
Fixes #8643
> Fix exact item count resolving if scrolled far

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
I assume the order of things on this method define the priority. As Proxy and ProxyConfig doesn't have any priority logic.
If/when that's the case the order is wrong. Project file should have higher priority than User file.
https://docs.npmjs.com/configuring-npm/npmrc.html
> Fix priority order of npmrc files

- flow-data/src/main/java/com/vaadin/flow/data/binder/HasItemComponents.java
- flow-data/src/main/java/com/vaadin/flow/data/binder/HasItemsAndComponents.java
`HasItems` in the `HasItemsAndComponents` does not allow some components (at least CheckboxGroup and Select) to support `HasXXXDataView` interfaces because of API methods name clashing. A new `HasItemComponents` has been introduced to be used in components instead.
> Exclude HasItems from HasItemsAndComponents so as to let the components support DataView

- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkIT.java
Closes #8693. Disabled ITs as scroll position handling requires a [separate fix](https://github.com/vaadin/vaadin-router/issues/43) for client-side router.
> Store scroll position in state when entering route not found view (#8698)

- flow-server/src/main/java/com/vaadin/flow/router/AfterNavigationEvent.java
This fixes #8669 by adding a method to retrieve the `LocationChangeEvent` from an `AfterNavigationEvent`.
> Fix for #8669 - add getLocationChangeEvent() to AfterNavigationEvent

- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkIT.java
Fixes problem with ITs failing local run because of client-side error when evaluating the `Assume` condition.
> Check for client-side router after loading page for disabling ITs

- flow-server/src/main/java/com/vaadin/flow/server/connect/generator/SchemaResolver.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGenerationTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/datetime/DateTimeEndpoint.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/DateTimeConversionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/VaadinConnectTypeConversionEndpoints.java
- flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/datetime/expected-DateTimeEndpoint.ts
- flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
LocalTime was an unkown type to Endpoint, which was translated to object type in TypeScript. This causes an issue when using `<vaadin-time-picker>` in a TypeScript form, as the value of `<vaadin-time-picker>` is a string.
> Add LocalTime type support in Endpoints

- flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts
- flow-client/src/test/frontend/form/BinderTests.ts
- flow-client/src/test/frontend/form/FieldTests.ts
Fixes https://github.com/vaadin/flow/issues/8638
> Rename binder.reset(value) to binder.read(value)

- flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
- flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts
- flow-client/src/test/frontend/form/ValidationTests.ts
Fixes https://github.com/vaadin/flow/issues/8688
Make The errors property of BinderNode return it's own validation errors + validation errors from its descendants.
> fix: BinderNode errors property

- flow-server/src/main/java/com/vaadin/flow/server/connect/generator/GeneratorUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/generator/GeneratorUtilsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/model/NonVaadinEndpoint.java
Fixes https://github.com/vaadin/flow/issues/8743
When checking if a class has an annotation, the underlying java parser lib has a bug that only considers the annotation's simple name. So a helper method is introduced in this PR to also check if it has the correct import.
> fix: consider import when checking has annotation

- flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
- flow-tests/pom.xml
- flow-tests/test-jetty-reload/pom.xml
- flow-tests/test-jetty-reload/src/main/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortView.java
- flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java
This allows reusing the running Webpack dev server when Jetty reloads the application context.
> Store webpack dev server port in tempfile named from JVM unique constant and project folder (#8739)

- flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache
- flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
This fixes the error in the previous PR https://github.com/vaadin/flow/pull/8754 that it forgot to apply the renaming to the model template.
> chore: apply symbol renaming in model template

- flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
This tries to fix https://github.com/vaadin/flow/issues/8699. 
There clearly is a logic error in the resync handling, under `if (isResynchronize(valueMap) && !isNextExpectedMessage(serverId))` condition. it will prepare for resync, thus remove all the nodes in the statetree, which will remove the 2 `@ClientCallable` methods in `JavaScriptBootStrapUI` (`connectClient` and `leaveNavigation`). 
But then if `boolean locked = !responseHandlingLocks.isEmpty();` is true, it will return, leaving `flowRoot.$server.connectClient` undefined in `Flow.ts`. Thus when user tries to navigate to any other view, which seems the reason to lead the error in #8699. 
But I don't know how to reliably reproduce the situation so couldn't come up with a test, even a unit test is hard to write.
> fix: don't clear node if cannot handle resync msg

- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Avoid reload() method whose usage may lead to showing a blank page
because server is not yet restarted. Instead use a fake iframe element
inside gizmo which refers to the same URL. Its window may be reloaded
safely and the result can be checked before applying it to the main
document. If reload was successful (page is initialized with Vaadin JS)
then replace the document content  with the content of iframe.
Fixes #8728
> Use fake iframe element to check reload result and replace on success.

- flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java
- flow-server/src/test/java/com/vaadin/flow/internal/StringUtilTest.java
> Sanitize string before removing comments from it.

- flow-server/src/main/java/com/vaadin/flow/component/Text.java
> Extend javadocs for Text and clarify not-supported API

- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Something is broken with the PR.
So it's completely removed.
> Revert fix for #8729

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/resources/webpack.generated.js
This modifies the default webpack loader configuration for all *.css files. Instead of the previous `raw-loader` only, this will use a loader chain of `['lit-css-loader', 'extract-loader', 'css-loader']`.
`lit-css-loader` gives us a nice DX of importing styles to TS views like this:
```ts
import styles from './list-view.css';
@customElement('list-view')
export class ListView extends LitElement {
static styles = [Lumo, styles];
```
`css-loader` gives the additional benefit of resolving CSS `@import "file.css";` syntax in CSS files. This is a new features that works both for TS views and also when using `@CssImport()` annotation in Java.
`extract-loader` is needed in the middle to convert the JS output of `css-loader` into a plain CSS string.
> Simpler CSS import for TS views and CSS @import support

- flow-server/src/main/java/com/vaadin/flow/component/HasStyle.java
- flow-server/src/test/java/com/vaadin/flow/component/HasStyleTest.java
> Fix setClassName to work as specified in javadoc

- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
I have experienced the same issue #8593 
This PR is to add file separator to the error message.
> fixing error message when fails to load content of index.html (#8593)

- flow-data/src/main/java/com/vaadin/flow/data/validator/EmailValidator.java
- flow-data/src/test/java/com/vaadin/flow/data/validator/EmailValidatorTest.java
Revert 'Overload EmailValidator to accept an empty value' feature from maintenance release because it's a new feature.
> Revert 'Overload EmailValidator to accept an empty value' feature

- flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
- flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/UnauthenticatedException.java
- flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/UnauthenticatedExceptionHandler.java
- flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/ViewThrowsException.java
- flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/ViewWithServerViewButton.java
- flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/ServerSideNavigationExceptionHandlingIT.java
Fixes #8430
Call `handleNavigationException()` inside `handleNavigation()` in `JavaScriptBootstrapUI`
> fix: handle nav exception inside handleNavigation

- flow-client/.eslintrc.js
- flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java
- flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
- flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java
- flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.d.ts
- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.ts
- flow-client/src/test/frontend/VaadinDevmodeGizmoTests.js
- flow-server/src/main/java/com/vaadin/flow/internal/BootstrapHandlerHelper.java
- flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReload.java
- flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadImpl.java
- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/Constants.java
- flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/DevServerWatchDog.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
- flow-server/src/main/resources/webpack.generated.js
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
- flow-tests/test-live-reload/frontend/styles.css
- flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/LiveReloadView.java
- flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/LiveReloadIT.java
When the webpack dev server finished recompilation, it will notify the Java server over
the watchdog connection. When the Java server notices the message, it in turn sends
the browser reload message over the dedicated live reload web socket connections.
Other changes in this commit:
- live reload now also works in V14 bootstrapping mode
- vaadin-devmode-gizmo is bundled separately
Addresses tickets #8852, #8721, #8001, #5617, #607 (and maybe others).
> Live reload on frontend changes

- flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
* Update VersionJsonFilter to use forced dependencies
* Update TaskRunPnpmInstallTest
Update tests to correctly test new expectations for PnpmInstall stage
* Update VersionJsonFilterTest
Change VersionJsonFilterTest in order to accomodate new behaviour when filtering versions
> Add peer dependency forcing mechanism to VersionsJsonFilter (#8545)

- flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
Remove the mode verification when populating
DeploymentConfiguration. The check is too early
when running the Application class and is not needed.
Fixes #8883
> Remove mode verification on configuration build

- flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Do not try to connect to the dev server
if it hasn't started yet or startup has failed.
Fixes #8858
> Only connect to devServer when it is started

- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataViewTest.java
`Void` type was erroneously set in `AbstractComponentDataViewTest`, which is not appropriate for components with an internal filter.
No changes in Grid, Select, CheckBox are needed, they just replace `?` with `Void`.
> Change the filter type from Void to wildcard in abstract data view test

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Update the webpack compression plugin to get a newer version of the serialize-javascript plugin.
Fixes #8857
> Update compression plugin

- flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
Fixes: https://github.com/vaadin/spring/issues/564
Instantiate AppShell with Instantiator, so that one can inject into AppShell.
Test is in the Spring Addon repo https://github.com/vaadin/spring/pull/652
> Instantiate AppShell with Instantiator

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
This fixes an issue which may cause webpack build failure with some CSS files. See https://github.com/bennypowers/lit-css-loader/issues/1
> fix(webpack): update lit-css-loader dependency

- flow-server/src/main/java/com/vaadin/flow/component/HasHelper.java
- flow-server/src/test/java/com/vaadin/flow/component/HasHelperTest.java
On this PR:
- Add HasHelper interface to be used for field components that have a "helper" feature (such as TextField)
- The interface contains getters and setters with default implementation for text and component APIs
- Tests for the methods
Fix #8871
> Add HasHelper interface

- flow-server/src/main/java/com/vaadin/flow/internal/HtmlUtils.java
Stop using the method that was deprecated in 1.11.1
Closes #8929
> Don't use the deprecated method

- flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
When redirecting to a HasUrlParameter class
with optional parameter call should be made with
empty parameter so that setParameter is called.
Fixes #8867
> Fix redirect/forward for Optional HasUrlParameter

- flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
The unit used when recording start (milliseconds) is not the same as the unit used when recording end (nanoseconds), yielding erroneous timing reports in the log. Record start also in nanoseconds.
> Fix log time units

- flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/CrudEndpoint.java
Fixes: #8931 
Use `GenericTypeReflector` to get the real type for generic typed parameters
> fix: fetch real type for generic typed parameter

- flow-server/src/main/java/com/vaadin/flow/internal/HtmlUtils.java
Last cherry-picks for 2.3 🤞 :
Stop using the method that was deprecated in 1.11.1
Closes #8929
> Cherry-picks for 2.3.5

- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.ts
- flow-server/src/main/java/com/vaadin/flow/internal/BootstrapHandlerHelper.java
- flow-server/src/main/java/com/vaadin/flow/server/DevServerWatchDog.java
- flow-server/src/main/resources/webpack.generated.js
Getting fixes for some issues that surfaced in the review of the cherry-pick to 2.4 (#8930) of original PR (#8875) back into master:
* Better ES5 compatibility in VaadinDevmodeGizmo (while not strictly necessary for V17+, including these also here makes backporting future changes to VaadinDevmodeGizmo simpler)
* Made BootstrapHandlerHelper a utility class (private ctor and final)
* Set encoding explicitly on webpack <-> server socket
> Fixes from backporting frontend live-reload into master

- flow-data/src/test/java/com/vaadin/flow/data/provider/CustomInMemoryDataProvider.java
This changes relevant to unit tests for data view in ComboBox.
I extended `AbstractDataProvider` in order to have a real implementation of listeners handling in ComboBox unit tests.
> Make the CustomInMemoryDataProvider implement listeners handling

- flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateDataAnalyzer.java
- flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdCollector.java
- flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdMapper.java
- flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java
- flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateInitializer.java
- flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
- flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
- flow-tests/test-root-context/frontend/AttributeTemplate.js
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateAttributeView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateAttributeIT.java
> Read attribute value from template

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
(cherry picked from commit 816a09474f2a3d105de00e4eb81960f7932dc0c3)
Fixes #8947
> Always consume the stdout stream from (p)npm and log at debug level (#7325)

- flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloaderTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
This PR:
1. Upgrade Node to latest LTS version (12.18.3)
2. ~Add `node-gyp` as a dev dependency (required for native compilation of `fsevents` 1 on macOS). Note that `fsevents` 1 is deprecated and is only required for `chokidar` 2 (also deprecated), which is a requirement of `webpack` 4 but is not used at runtime (`chokidar` 3 is included). Hence, fix 2 is only cosmetic: it prevents the unsightly [`spawn node-gyp EACCES`](https://github.com/vaadin/flow/issues/8741) errors, but on the flip side the native compilation increases the `npm install` time compared to the install script failing. All for no good reason.~
3. Add parameter `--scripts-prepend-node-artifact=true` to Node install [to ensure that the same node executable is used for running npm and package install …
> Upgrade auto-installed Node to latest LTS and suppress some `npm install` errors

- flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
- flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
- flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
- flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
- flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
- flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/StatsContentTest.java
Replace DEAULT_FLOW_RESOURCES_FOLDER with DEFAULT_FLOW_RESOURCES_FOLDER, but keep the old variable as deprecated.
> Fix typo in variable DEAULT_FLOW_RESOURCES_FOLDER

- flow-tests/pom.xml
- pom.xml
These introduced properties allows to disable the Windows failed tests in Bender build, and to fix them gradually.
> Support for disabling Win-specific tests in CI

- flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
- flow-server/src/main/java/com/vaadin/flow/server/connect/Deferrable.java
- flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
- flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/TypeScriptApiTemplate.mustache
- flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/deferrable/DeferrableEndpointTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/deferrable/SingleMethodDeferrableEndpoint.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/deferrable/WholeClassDeferrableEndpoint.java
- flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-SingleMethodDeferrableEndpoint.ts
- flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-WholeClassDeferrableEndpoint.ts
For #8951 
- When there is a `@Deferrable` in an Endpoint class or method, the generated function will return a `DeferrableResult` instead.
- If no `@Deferrable` is present, the generated code is the same as before.
Note this PR only has a class definition for the `DeferrableResult`, the detail implemented will be in a separate PR
> feat: Endpoint generation based on @Deferrable

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
> Do not force installation of compatible pnpm version when system property `vaadin.ignoreVersionChecks` is set

- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
This PR addresses two problems for the production mode:
- The `index.html` was read and parsed via Jsoup on every request in `IndexHtmlRequestHandler`
- The resulting page was pretty printed (default behaviour of `Jsoup.parse()`
> Cache original index.html Document in production mode

- flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
`checkLogsForErrors` checks if the message contains `404`, but it will match if the sequence is part of a number.
[This build for Grid](https://teamcity.vaadin.com/viewLog.html?buildId=66566&) is an example of such case.
> fix: surround 404 check with spaces

- flow-client/package.json
- flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
- flow-client/src/test/frontend/ConnectTests.ts
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/TypeScriptApiTemplate.mustache
- flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-SingleMethodDeferrableEndpoint.ts
- flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-WholeClassDeferrableEndpoint.ts
fixes #8950 
- Add client.deferrableCall() which allows caching the endpoint request when offline
- Generated endpoints will call `client.deferrableCall()` if a `@Deferrable` annotion is detected (#8951)
- Use a IndexedDB helper `"idb-keyval": "3.2.0"` for easier indexedDB manipulation
- Use an uuid helper `"uuid": "8.0.0"` for generating uuid
> feat: support deferrable endpoint request

- flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplate.java
- flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateDataAnalyzer.java
- flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateInitializer.java
- flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateParser.java
- flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateParserImpl.java
- flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
- flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdCollector.java
- flow-server/src/test/java/com/vaadin/flow/component/littemplate/LitTemplateParserImplTest.java
- flow-server/src/test/resources/META-INF/VAADIN/config/stats.json
- flow-server/src/test/resources/frontend/my-lit-element-view.js
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
> Implement lit template parser for limited template formats which extends LitTemplate element

- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
The problem is that the `ClassReader(InputStream)` constructor doesn't close the input stream itself, which is then left open hanging. This is especially troublesome for Gradle Plugin since the opened input stream is left hanging in the Gradle Daemon, which can stay around for hours. This could be a possible cause for https://github.com/vaadin/vaadin-gradle-plugin/issues/81
This PR needs to be cherry-picked to 4.0 and also 2.3 branches.
> Fixed: flow-server now closes resources properly when parsing java classes

- flow-server/src/main/java/com/vaadin/flow/component/template/internal/AbstractInjectableElementInitializer.java
- flow-server/src/main/java/com/vaadin/flow/component/template/internal/DisabledInitializationStrategy.java
- flow-server/src/test/java/com/vaadin/flow/component/littemplate/InjectableLitElementInitializerTest.java
- flow-server/src/test/java/com/vaadin/flow/component/littemplate/LitTemplateTest.java
- flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/InjectablePolymerElementInitializerTest.java
- flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
- flow-tests/test-root-context/frontend/AttributeTemplate.js
- flow-tests/test-root-context/frontend/lit/AttributeLitTemplate.js
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/LitTemplateAttributeView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateAttributeView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateAttributeIT.java
> Set enable state based on template element attribute

- flow-server/src/main/java/com/vaadin/flow/server/connect/BeanValueTypeCheckHelper.java
- flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
Fixes #9011 
Pass a `BeanValueTypeCheckHelper` instance in method calls instead of having it as a field instance. Benefits:
- It avoids memory leak, as keeping it as a field instance will make the referenced map keep growing.
- It becomes thread-safe, as each request will have its own instance of the `BeanValueTypeCheckHelper`.
The PR doesn't a unit test for the race condition, as the unit test won't be reliable.
> fix: don't reuse endpoint nullable checker state

- flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdCollector.java
- flow-server/src/main/java/com/vaadin/flow/component/template/internal/AbstractInjectableElementInitializer.java
- flow-server/src/main/java/com/vaadin/flow/component/template/internal/TextInitializationStrategy.java
- flow-server/src/test/java/com/vaadin/flow/component/littemplate/InjectableLitElementInitializerTest.java
- flow-server/src/test/java/com/vaadin/flow/component/littemplate/LitTemplateTest.java
- flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/InjectablePolymerElementInitializerTest.java
- flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
- flow-tests/test-root-context/frontend/AttributeTemplate.js
- flow-tests/test-root-context/frontend/lit/AttributeLitTemplate.js
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/LitTemplateAttributeView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/ChildOrderView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateAttributeView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ChildOrderIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateAttributeIT.java
> Read text for template element

- flow-server/src/main/java/com/vaadin/flow/component/UI.java
- flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java
- flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
- flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
- flow-server/src/test/java/com/vaadin/flow/component/InvalidUrlTest.java
- flow-server/src/test/java/com/vaadin/flow/component/LocationObserverTest.java
- flow-server/src/test/java/com/vaadin/flow/component/UITest.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterConfigurationUrlResolvingTest.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterLinkTest.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
- flow-server/src/test/java/com/vaadin/flow/router/RoutingTestBase.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/ErrorStateRendererTest.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
- flow-server/src/test/java/com/vaadin/flow/server/BootstrapContextTest.java
- flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerDependenciesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
- flow-server/src/test/java/com/vaadin/tests/util/MockUI.java
Fixes https://github.com/vaadin/flow/issues/8989
`Router.navigate` behaviour is now different than `UI.navigate` and won't update the browser history when used with `NavigationTrigger.PROGRAMMATIC`.
> Deprecate UI.getRouter() and use it only as internal

- flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
The test `VaadinConnectControllerTest.should_bePossibeToGetPrincipalInEndpoint` fails randomly in CI, the reason seems to be that the `MockVaadinServletService service` is garbage collected before the endpoint invocation. 
Change `MockVaadinServletService service` to be a field instance to prevent the garbage collection from happening.
> fix a flaky test in VaadinConnectControllerTest

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Since the `Range` is exclusive at the end, it may happen that the range end is the same as the assumed size. It that case the `flush()` would not be invoked, although it should. Requested range strategy generally speaking depends on web component and there may be the case when the component requests, for example [5700...5800] and the assumed size is already 5800. This situation reflects the case when the user scroll to the end and then he jumps to undefined size. Then it should force the size re-estimation. And thus this code change occurred.
> Force size re-estimate when requested range end equals assumed size

- flow-server/src/main/java/com/vaadin/flow/component/dependency/JavaScript.java
- flow-server/src/main/java/com/vaadin/flow/internal/UrlUtil.java
- flow-server/src/test/java/com/vaadin/flow/internal/UrlUtilTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PlainScriptViaJavaScriptView.java
- flow-tests/test-root-context/src/main/webapp/plain-script.js
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PlainScriptViaJavaScriptIT.java
* Consider context/base schemas as external URLs
Fixes #8290
> CP: Treat URLs with "context" and "base" schemas as external  (#8556)

- flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
- flow-server/src/main/java/com/vaadin/flow/router/LocationChangeEvent.java
Update javadoc of rerouteTo()/forwardTo() to clear out the difference between the two
> Update javadoc of rerouteTo()/forwardTo()

- flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/TypeScriptApiTemplate.mustache
- flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-SingleMethodDeferrableEndpoint.ts
- flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-WholeClassDeferrableEndpoint.ts
Add @ts-ignore to the DeferrableResult import in the generated ts files, as it might not be used.
> chore: add @ts-ignore to DeferrableResult import

- flow-server/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessCheckerTest.java
- use `request.getSesssion(false)` instead of `request.getSesssion()` so that it won't create a new session for access check.
- fix a bug that when there is no csrf token in the session (e.g. when session is expired), it's considered valid.
- allow empty csrf token in the request header when there is no session (e.g. using curl).
> fix: fail access check when no csrf token in session

- flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
This allows external code extending this class to reduce copy/pasting these and other private methods.
An example of where this would be beneficial is [here in Vertx Vaadin](https://github.com/mcollovati/vertx-vaadin/blob/master/vertx-vaadin-flow-parent/vertx-vaadin-flow/src/main/java/com/github/mcollovati/vertx/vaadin/communication/StreamReceiverHandler.java).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/flow/8468)
> Make handleFileUploadValidationAndData and sendUploadResponse protected

- flow-client/tsconfig.json
- flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
- flow-server/src/main/resources/sw.ts
- flow-server/src/main/resources/tsconfig.json
Revert adding lib section to tsconfig.json to avoid needing a manual upgrade step in projects.
Fixes #9144
> fix: declare webworker lib for sw.ts with TS triple-slash directive

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Update the copy-webpack-plugin and webpack-dev-server due to 
found vulnerabilities in dependencies.
Fixes #9189
> fix: update development plugins

- flow-server/src/main/java/com/vaadin/flow/internal/InternalConstants.java
- flow-server/src/main/java/com/vaadin/flow/server/Constants.java
- flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
- flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
Fixes https://github.com/vaadin/flow/issues/9005
For a non-boot Spring application or a Spring Boot application with auto-configuration disabled (e.g. when using `@EnableWebMvc`), Vaadin registers a request handler with mapping `/{endpoint}/{method}`. Note the connect prefix is not added in this case, since it relies on Spring Boot auto-configuraiton.
So it's better for users who are using endpoints, we don't register the endpoint request handler.
Test is in https://github.com/vaadin/spring/pull/672
> fix: only register endpoint request handler when endpoint presents

- flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
- flow-client/src/test/frontend/form/BinderTests.ts
- flow-client/src/test/frontend/form/TestModels.ts
> fix(TypeScript): client-side form binder validation errors because of value having unused deep optional fields

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataProvider.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Wrapped the result of `Arrays.asList(T... items)` by `java.util.ArrayList` to support further add/remove operations through the `DataView` API without getting an `UnsupportedOperationException`. 
Fix: #8761
> fix: Use ArrayList while creating ListDataProvider from items array

- flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
Fixes #9005 
Only register Vaadin Endpoint controller when there are beans with `@Endpoint` annotation.
> fix: register endpoint controller only when there are endpoints

- README.md
Updated `master` to reference version `5.0`. Added a few missing branches/versions. Updated to table format.
> Update README with branch versions

- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
Lock the registry when registering
dynamic route in serviceInit to not have
a race where 2 inits note that path not
registered and then register the route.
Fixes #9223
> test: Fix duplicate registration

- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
Lock the registry when registering
dynamic route in serviceInit to not have
a race where 2 inits note that path is not
registered and then try to register the route.
Fixes #9223
> test: Fix duplicate registration (#9233)

- flow-server/src/main/resources/com/vaadin/flow/server/webcomponent/webcomponent-script-template.js
8d012f755ccf8b00288959bfa7bc6dd7a3f51284 removed some log and converted others into debug
but log in disconnectedCallback was left.
> refactor: Remove log usage in embedded components

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
Exposes `DataCommunicator::getDataProviderSize` to the components, in order to get the items count taking into account the `countCallback`, if it has been set previously.
Related-to: https://github.com/vaadin/vaadin-flow-components/issues/282
> refactor: expose the items count API to components

- flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
- flow-client/src/main/resources/META-INF/resources/frontend/OfflineStub.ts
- flow-client/src/test/frontend/FlowTests.ts
- flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/OfflineServerViewIT.java
An information page, similar in style and content to the default `offline.html`, is rendered in 
when navigating to a server-side view in offline mode.
Fixes #9132.
> feat: offline stub for server-side views

- flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
If you enable Spring Security, the missing charset causes the page to either be downloaded or shown as plain text depending on the browser.
> fix: Add content type to dev-mode-not-ready response (#9095)

- flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Validates that the page is HTML and has correct `Content-Type`.
> chore: unit test for devmode-not-ready page contents and type

- flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiResourceProvider.java
- flow-server/src/main/java/com/vaadin/flow/server/osgi/ServletContainerInitializerExtender.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
OSGi `ResourceProvider`  impl should be available as a service at the moment when Vaadin WAB register a servlet.
It's not possible without extra unclear config to make sure that the service is registered if it's in the `flow-osgi` : the bundle may be activated at any moment regardless of servlet registration.
The issue doesn't appear if the service is registered at the `flow-bundle`  start phase.
> refactoring: move OSGi resource provider impl to flow-server

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
Fix typo in DataCommunicator::getDataProviderSize() javadoc.
> chore: fix typo

- flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapper.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithDataTest.java
HierarchicalDataCommunicator's expanded state were not being synchronized with client side and TreeGrid's expanded nodes were being collapsed after re-attaching.  
Fixes: #9175
> fix: Sync HierarchicalDataCommunicator's expand state with client side

- flow-tests/test-live-reload/frontend/code.js
- flow-tests/test-live-reload/frontend/custom-component.ts
- flow-tests/test-live-reload/pom.xml
- flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/AbstractLiveReloadView.java
- flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/FrontendLiveReloadView.java
- flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/JavaLiveReloadView.java
- flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/LiveReloadView.java
- flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshLiveReloadView.java
- flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
- flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/AbstractLiveReloadIT.java
- flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/FrontendLiveReloadIT.java
- flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/JavaLiveReloadIT.java
- flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/LiveReloadIT.java
- flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshLiveReloadIT.java
Improvements to frontend live reload IT:
- Add PWA annotation and wait for service worker installation
- `LiveReloadIt::liveReloadOnTouchedFrontendFile` now makes a TS file change and validates that it is applied after automatic reload
Part of #9182
> test: service-worker aware live reload IT

- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
- flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
Even though `WebBrowser` is updated only once via `com.vaadin.flow.server.VaadinService#createAndRegisterSession()`, it still has `public void updateRequestDetails()` method which may be called by the third party. `WebBrowser` instance is returned without defensive copy from `VaadinSession.getBrowser()`. This PR makes `WebBrowser` effectively immutable and removes `updateRequestDetails()` method.
> refactor: make web browser immutable

- flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
Check `navigator.onLine` value before calling server. Note that when he have the
new "single source of truth" (part of #9203) for the connection state that should 
be used instead.
Fixes #9326.
> fix: do not attempt to call `$server.leaveNavigation` in offline case

- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeClassFinderTest.java
AppShellConfigurator is now also considered when
scanning for annotations and deciding theme.
Fixes #9110
> fix: AppShellConfigurator is now considered for theme endpoint

- flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithDataTest.java
`HierarchicalDataProvider`'s `reset` method was called before recreating the `HierrarchyMapper` in `setDataProvider`. This was creating wrong updates for the client side. 
Fixes: #9328
> fix: TreeGrid updating wrong expanded items state after setDataProvider

- flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
- flow-server/src/main/java/com/vaadin/flow/theme/NoTheme.java
- flow-server/src/main/java/com/vaadin/flow/theme/Theme.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
If an AppShellConfigurator is available the `@Theme` annotation 
should be only defined there.
Fixes #9092
> feat: Theme annotation should be only on AppShellConfigurator

- flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
- flow-client/src/test/frontend/ConnectTests.ts
> fix: hide loading indicator when endpoint call fails

- flow-client/package.json
- flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts
- flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts
- flow-client/src/main/resources/META-INF/resources/frontend/form/index.ts
- flow-client/src/test/frontend/form/ValidationTests.ts
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Related to #9341 
- Update validator version
- Use tree-shakeable ES imports for TS form validators
- Add missing `return` in the `submit()` method
> fix: TS form validators import and missing return in submit()

- flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
- flow-server/src/test/java/com/vaadin/flow/internal/ResponseWriterTest.java
Supports headers of the type `Range: -123` and `Range: 123-`. This
format was accidentally omittted in the previous implementation and 
Firefox and Chromium now use it.
Fixes #9083.
> fix: support Range requests with either start or end byte index omitted

- flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/DemoView.java
Due to https://github.com/vaadin/flow/commit/c5f531937fe99ae7b49b2a7310abfccfdc5e5bcc Theme annotation should be removed from the module so as it can be used in vaadin-flow-components demos
> test: remove Theme annotation from demo helpers module

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Data communicator's filter removal, which has been introduced for components with internal filtering (like a ComboBox), may lead to filter loss during the items scrolling. This fix reverts the filter removal and the components should implement this feature on their side, if necessary.
Fixes: https://github.com/vaadin/vaadin-flow-components/issues/388
ComboBox side changes: https://github.com/vaadin/vaadin-flow-components/pull/393
> fix: preserve filter for not losing it between page requests

- flow-server/src/main/java/com/vaadin/flow/server/osgi/ServletContainerInitializerExtender.java
- flow-server/src/main/java/com/vaadin/flow/server/osgi/VaadinBundleTracker.java
Need to active the tracker from an servlet context initializer because @Activate doesn't work on CTOR with parameter
> fix: revert changes which broke route registration

- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InternalErrorIT.java
Tests on `flow-tests/test-root-context` it work on my setup only 3 of 10 times.
every other time failed with `enableSessionExpiredNotification_sessionExpired_notificationShown` :
That is not an OSGi or bnd problem.
```
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.48 s <<< FAILURE! - in com.vaadin.flow.uitest.ui.InternalErrorIT
[ERROR] enableSessionExpiredNotification_sessionExpired_notificationShown[ANY_Chrome_](com.vaadin.flow.uitest.ui.InternalErrorIT)  Time elapsed: 7.479 s  <<< FAILURE!
java.lang.AssertionError: After enabling the 'Session Expired' notification, the page should not be refreshed after killing the session
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at …
```
> fix race-condition in IT-Tests

- flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
- flow-client/src/main/java/com/vaadin/client/ConnectionState.java
- flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
- flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
- flow-client/src/main/java/com/vaadin/client/communication/RequestResponseTracker.java
- flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
- flow-client/src/test-gwt/java/com/vaadin/client/GwtSuite.java
- flow-client/src/test-gwt/java/com/vaadin/client/communication/GwtDefaultConnectionStateHandlerTest.java
Also pause heartbeats during `CONNECTION_LOST`.
Fixes #9424.
> feat: transition to RECONNECTING when receiving browser online event

- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
> fix: remove instance field from singleton IndexHtmlRequestHandler

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
As there is a conflict with the dependencies and prevent adding
the flow-dev-dependencies package to the platform (#9345), this will hide
the unavoidable error that was logged for Vaadin apps.
Fixes #9251
> Stop logging error when updating dev dependencies

- flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
- flow-server/src/test/java/com/vaadin/flow/internal/ResponseWriterTest.java
More efficient parsing of the Range: header value. Also, range count is capped at 16
(additional will be ignored) and overlapping ranges at 2 (request will be denied
if above).
> fix: optimize handling of requests containing Range header

- flow-server/src/main/java/com/vaadin/flow/internal/CustomElementNameValidator.java
- flow-server/src/test/java/com/vaadin/flow/internal/CustomElementNameValidatorTest.java
use find instead of matches as matches never matched.
Fixes #9494
> fix: Correct regexp to only match when digit first

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/resources/plugins/application-theme-plugin/package.json
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
Add the constructable stylesheets polyfill so
app theme also works with non chrome based browsers.
Fixes #9488
> fix: Add polyfill for constructable stylesheets

- flow-lit-template/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
- flow-polymer-template/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
- flow-server/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
* In WAR case init will be called as usual without any changes
* IN OSGi ServletContextListener::contextInitialized may be called after Servet::init is called and in this case info necessary for the servlet won't be available yet.
* ServletContextListener::contextInitialized  will call Servet::init one more time to complete initialization.
> fix: Initialize VaadinServlet after Lookup is available

- flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
- flow-client/src/main/java/com/vaadin/client/ConnectionIndicator.java
- flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java
- flow-client/src/main/java/com/vaadin/client/Registry.java
- flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
- flow-client/src/main/java/com/vaadin/client/communication/LoadingIndicatorConfigurator.java
- flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
- flow-client/src/main/java/com/vaadin/client/communication/ReconnectConfiguration.java
- flow-client/src/main/java/com/vaadin/client/communication/RequestResponseTracker.java
- flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts
- flow-client/src/test-gwt/java/com/vaadin/client/communication/GwtDefaultConnectionStateHandlerTest.java
- flow-client/src/test/frontend/ConnectionIndicatorTests.ts
- flow-client/src/test/java/com/vaadin/client/DomApiAbstractionUsageTest.java
- flow-client/src/test/java/com/vaadin/client/communication/ReconnectConfigurationTest.java
- flow-server/src/main/java/com/vaadin/flow/component/ReconnectDialogConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ReconnectDialogConfigurationMap.java
- flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ReconnectDialogConfigurationMapTest.java
- flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
- flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/ConnectionIndicatorView.java
- flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ConnectionIndicatorIT.java
The Java API for configuring the messages shown in the reconnect dialog (`ReconnectDialogConfiguration.setDialogText` and `ReconnectDialogConfiguration.getDialogTextGaveUp`) now carry over to the corresponding properties of the new `<vaadin-connection-indicator>` component (`reconnectingText` and `offlineText`, respectively). The `flow-client` class `ReconnectDialogConfiguration` has been renamed to `ReconnectConfiguration` to better capture that it manages the reconnect logic (connection attempts and interval), not the dialog visuals.
Two properties, which have no corrspondence in the new connection indicator (`ReconnectDialogConfiguration.setDialogGracePeriod` and `ReconnectDialogConfiguration.setDialogModal` are now no-ops and have been deprecated).
Fixes #9401.
> fix: reconnect dialog settings to vaadin-connection-indicator

- flow-server/src/main/resources/plugins/theme-loader/package.json
- flow-server/src/main/resources/plugins/theme-loader/theme-loader.js
The theme-loader recursion for themeFolder should stop
at the root level. Also if no theme folder found we should
not spend time on replacement.
> Fix: fix file system traversal of theme-loader to stop at root

- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BaseHrefIT.java
> fix: enable BaseHref IT for OSGi back

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
- flow-server/src/main/resources/plugins/application-theme-plugin/package.json
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
- flow-server/src/main/resources/plugins/theme-loader/package.json
- flow-server/src/main/resources/plugins/theme-loader/theme-loader.js
- flow-server/src/main/resources/webpack.generated.js
- flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Fixed the url handling so that theme resources
get prepended with theme/[themeName] while
having the correct absolute path. With this we can handle
these url resources with the css-loader which in turn
leads to file-loader gettign the files for copying.
External url are still not touched in any way.
part of #9410 and #9533
> feat: Resource handling to not need plugin copying

- flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
> fix: use provided executor for frontend tools (#9553)

- flow-server/src/main/resources/webpack.generated.js
Windows file path separator \ should not
be used as it will result in %0B when it should
be /
> fix: file-loader name for windows execution

- flow-data/src/test/java/com/vaadin/flow/data/validator/ValidatorTestBase.java
Fixed flaky test that caused by `com.vaadin.flow.component.UI` in class `ValidatorTestBase`. 
- **[Issue]** 
If only run `mvn -pl flow-data test -Dtest=BeanValidatorTest#testInvalidDecimalsFailsInFrench` command, the [`testInvalidDecimalsFailsInFrench`](https://github.com/vaadin/flow/blob/be4ddc785a22728b999e37551bb0d85bb3e4def6/flow-data/src/test/java/com/vaadin/flow/data/validator/BeanValidatorTest.java#L63) will failed because of the incorrect language setup 
- **error msg**: 
```
[ERROR] Failures: 
[ERROR] BeanValidatorTest.testInvalidDecimalsFailsInFrench:66->ValidatorTestBase.assertFails:59 expected:<[valeur numérique hors limite (<3 chiffres>.<2 chiffres> attendu])> but was:<[numeric value out of bounds (<3 digits>.<2 digits> expected])>
```
- **solution**: 
Added a `ui` variable …
> Fixed flaky tests caused by gc:ed variable ui in ValidatorTestBase.java

- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HasHierarchicalDataProviderTest.java
Adds the missed refresh all method to data view API.
Fixes: https://github.com/vaadin/flow/issues/9574
> fix: Add missing refreshAll method to data view

- flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
- flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HasHierarchicalDataProviderTest.java
Adds the missed refresh all method to data view API.
Fixes: #9574
(cherry picked from commit c60b51bd775a036982af580998e89097e165751c)
> Cherry pick to 5.0

- CONTRIBUTING.md
- README.md
The contribution guide was missing the project setup information.
There were outdated instructions in the readme, which was on the other hand not up to date and only had instructions for Eclipse.
> chore: Update contributing guide with setup info

- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Returning references to internal mutable members of a class can compromise an application's security, both by breaking encapsulation and by providing the opportunity to corrupt the internal state of the class (whether accidentally or maliciously). As a result, programs must not return references to private mutable classes.
Class: **`com.vaadin.flow.server.VaadinService`**
Scope: **singleton**
Field: **`private Iterable<DependencyFilter> VaadinService.dependencyFilters`**
Value: `(ArrayList<E>) []`
Value is read:
- **`public Iterable<DependencyFilter> VaadinService.getDependencyFilters()`**
Value is written:
- **`private void VaadinService.lambda$init$1(ServiceInitEvent, List<E>)`**
Value is returned:
- **`public Iterable<DependencyFilter> VaadinService.getDependencyFilters()`**
> Make VaadinService.dependencyFilters unmodifiable

- flow-server/src/main/resources/webpack.generated.js
- flow-tests/pom.xml
- flow-tests/test-ccdm-flow-navigation/pom-production.xml
- flow-tests/test-pwa/pom-production.xml
- flow-tests/test-pwa/pom.xml
- flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Also run offline test modules (`test-pwa` and `test-ccdm-flow-navigation`) in production mode.
Fixes #9457.
> fix: reorder manifest and compression plugins

- flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
- flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
- flow-client/src/test/frontend/ConnectTests.ts
Allows TestBench tests to assume that all initial endpoint requests have
completed before the test case is executed.
> fix: Vaadin.Flow.clients.TypeScript.isActive for endpoint requests

- flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
- flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
- flow-server/src/main/resources/plugins/application-theme-plugin/package.json
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
- flow-server/src/main/resources/webpack.generated.js
- flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
- flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
- flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Theme files are now copied undet theme/[theme-name]
and can be refernced by theme/them-name/path/file.ff
even though they are located at VAADIN/static
Fixes #9405 
Fixes #9535
> Fix: theme files can now be referenced as theme/theme-name

- flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
- flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
- flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
- flow-client/src/test/frontend/ConnectTests.ts
- flow-client/src/test/frontend/ConnectionStateTests.ts
This reverts part of 0d1a6a22ead081416846dc83fd323d1da14d861f, which made
Flow.isActive dependent on the global connection state. This caused flaky tests
and was incorrect use of global state which may be modified by other clients.
Rather each client must independently compute isActive.
Also renamed ConnectionState.loadingSucceeded to the more descriptive
loadingFinished.
> fix(offline): do not depend on global connection state for isActive

- flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
- fusion-endpoint/src/test/java/com/vaadin/flow/server/startup/fusion/DevModeInitializerEndpointTest.java
Move mock initialization to the setup method so that the tests depend on verify count won't affect each other.
> chore: fix flaky tests that depends on mock count

- flow-tests/pom.xml
Using the deepClean profile one can
clean up all the generated files and
node_modules folders from all test modules.
> chore: create deepClean profile

- flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/AbstractDeploymentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/AbstractPropertyConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
- flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationConfiguration.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationConfigurationFactory.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactory.java
- flow-server/src/test/java/com/vaadin/flow/server/AbstractDeploymentConfigurationTest.java
- flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
- flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java
> refactor: extract common config functionality and introduce add config

- flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts
- flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts
- flow-client/src/main/resources/META-INF/resources/frontend/form/Validation.ts
- flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts
- flow-client/src/test/frontend/form/FieldTests.ts
- flow-client/src/test/frontend/form/ModelTests.ts
- flow-client/src/test/frontend/form/ValidationTests.ts
- flow-client/src/test/frontend/form/ValidatorsTests.ts
> fix(TypeScript): binder should allow typing decimal numbers

- flow-client/src/test/frontend/FlowTests.ts
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
Contains two stabilising fixes:
- A [rare fluke](https://bender.vaadin.com/viewLog.html?buildId=204930&buildTypeId=Flow_Flow60_Flow60Snapshot&tab=buildLog&_focus=15958) (also in master) occurs in `FlowTests` when the `setTimeout` calls intended to simulate asynchronous server response in `stubServerRemoteFunction` complete after the unit test, when `afterEach` has already deleted `window.Vaadin`. This causing `Flow.loadingFinished` ran by `Flow.serverConnected` to crash between the tests. The fix cancels all timers between in `afterEach`.
- With the right heartbeat timing, the browser console in`LogoutIT` can [contain a session expiration message](https://bender.vaadin.com/viewLog.html?buildId=205169&buildTypeId=Flow_Misc_FlakyItInvestigationTestByJohannes&tab=buildLog&branch_Flow_Misc=mer …
> chore: improve stability of two tests

- flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Many `DevModeHandlerTest` unit tests start a separate thread that looks for a free port via `DevModeHandler::getFreePort`. This method is also used in the tests themselves, primarily via the private method `DevModeHandlerTest::prepareHttpServer`. Even though unit tests are run in sequence, a race conditions over ports between a thread started by a previous test and the setup code of the next test can occur fairly easily. For instance, in the recent builds of master there are two failures related to this:
- https://bender.vaadin.com/viewLog.html?buildId=205729&buildTypeId=Flow_Flow60_Flow60Snapshot
- https://bender.vaadin.com/viewLog.html?buildId=204456&buildTypeId=Flow_Flow60_Flow60Snapshot
This PR adds a `handler.join()` to a few unit tests that were missing it, to ensure that both port …
> fix: flaky unit test due to race for port numbers

- flow-server/pom.xml
- flow-server/src/main/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactory.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/ItApplicationConfigurationFactory.java
Use service.ranking property directly and avoid @ServiceRanking
annotation which for some reason is not handled by the bnd tools and no
rank is generated for the OSGI service descriptor.
> fix: @ServiceRanking is not handled by the osgi bundle generation tool

- flow-tests/test-application-theme/test-theme-live-reload/pom.xml
- flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
Marks ThemeLiveReloadIT as not thread safe, since it's tests modify server's state and are run in parallel by default on the CI.
> test: mark ThemeLiveReloadIT as not thread safe

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
Plugin installation can be skipped
by defining `"update": false,` in installed
package.json of plugin under node_modules
> Always install webpack plugins

- flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
- flow-client/src/test/frontend/FlowTests.ts
To avoid false positive due to service worker serving precached index.html.
Fixes #9688.
> fix: verify server live by HEAD to /sw.js instead of /

- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Fix the exception message and its test
to handle the file separator correctly.
If the base only contains / and the system
separator is \ we should add a / and not the
system separator.
Fixes 6.0 windows build failure.
> chore: fix exception message

- flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
Ignores ThemeLiveReloadIT temporary until https://github.com/vaadin/flow/issues/9746 is fixed.
> test: ignore ThemeLiveReloadIT

- flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloaderTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
Bumps the default installed version of Node.js to `v14.15.4` (last LTS).
> chore: Bump Node.js default version to last LTS

- flow-html-components/src/main/java/com/vaadin/flow/component/html/Article.java
- flow-html-components/src/main/java/com/vaadin/flow/component/html/Aside.java
- flow-html-components/src/main/java/com/vaadin/flow/component/html/Div.java
- flow-html-components/src/main/java/com/vaadin/flow/component/html/Footer.java
- flow-html-components/src/main/java/com/vaadin/flow/component/html/Header.java
- flow-html-components/src/main/java/com/vaadin/flow/component/html/Main.java
- flow-html-components/src/main/java/com/vaadin/flow/component/html/Nav.java
- flow-html-components/src/main/java/com/vaadin/flow/component/html/Section.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/ArticleTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/AsideTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/ComponentTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/DivTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/FooterTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/HeaderTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/MainTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/NavTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/SectionTest.java
closes #8188
This PR implements HasOrderedComponents for all common HTML layout elements: 
* Aside
* Article
* Div
* Footer
* Header
* Main
* Nav 
* Section
The test is created in the base test class to simplify the unit testing of all components. To make sure that the interface isn't removed by accident, every class implements the test explicitly and fails if the interface is removed.
> feat: implement HasOrderedComponents in HTML layout elements

- flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/HeartbeatHandler.java
relates to #9759 
forward port of https://github.com/vaadin/framework/pull/11859
Not sure about the `chore` label. 
Edit: I updated the issues to the full path for easier navigation.
> chore: framework#11859 Expired session: use 403 Forbidden instead of 410

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/resources/webpack.generated.js
- flow-tests/test-application-theme/test-theme-reusable/src/main/java/com/vaadin/flow/uitest/ui/theme/MyLitField.java
- flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/MyLitField.java
- flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/MyLitField.java
`awesome-typescript-loader` has not been updated in the last 2 years and does not guarantee compatibility with TypeScript 4+. `ts-loader` on the other hand is well maintained and tested with TypeScript 4+, and is the most popular Webpack loader for TypeScript files.
Related to #9714.
> feat: replace awesome-typescript-loader with ts-loader

- flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
Fixes #9774
The change makes the stub `webpack-dev-server.js` used in testing listen to
the specified port, so that `DevModeHandler` could connect to it. This resolves
connection errors that used to occur when running
`DevModeInitializerTest` tests, as well as fixes the test errors on
Windows caused by the OS timeout and retries for failed connection
attempts.
> fix(tests): add JSON HTTP server to stub webpackDevServer

- flow-server/src/main/java/com/vaadin/flow/server/startup/AnnotationValidator.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/DeferredServletContextInitializers.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/ErrorNavigationTargetInitializer.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/ServletVerifier.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinInitializerException.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinServletContextStartupInitializer.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializer.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentExporterAwareValidator.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializerTest.java
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
This is the successor to [this pull request](https://github.com/vaadin/flow/pull/8469) (which ran long and had too many updates).
Most Vaadin startup initializers don't actually need `ServletContext`. Thus, their methods should use VaaddinContext instead. This pull request attempts to fix. This allows non-servlet implementing HTTP frameworks (such as [VertxVaadin](https://github.com/mcollovati/vertx-vaadin)) to directly call the main initialization logic via `VaadinContextStartupInitializer#initialize(Set, VaadinConntext)}` instead of needing to create fake `ServletContext`s.
I also standardized parameter names of overriden methods and also deprecated (where it made sense) public methods that used `ServletContext` in favor of a new method which uses `VaadinContext`.
I believe this fixes …
> Refactor startup initializers to use VaadinContext

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/resources/webpack.generated.js
- flow-tests/test-application-theme/test-theme-reusable/src/main/java/com/vaadin/flow/uitest/ui/theme/MyLitField.java
- flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/MyLitField.java
- flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/MyLitField.java
This reverts commit be4d8728f82d47ec6cdf2a07d8d8ef8d5d9980a6.
be4d8728f82d47ec6cdf2a07d8d8ef8d5d9980a6 broke the CI, revert it first to make the CI green.
> Revert "feat: replace awesome-typescript-loader with ts-loader (#9721)"

- flow-server/src/main/resources/plugins/application-theme-plugin/package.json
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
When copying files for custom theme
only create directories that contain file
to be copied.
Generate directories with mkdirp instead
of fs.mkdir as it is more reliable.
> fix: Only create needed folders

- flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Connected to #9774
When port listening is not enabled in stub webpack server, there is a failed
connection in DevModeHandler. On Windows it needs at least
1.5s to fail (for 3 attempts with 500ms intervals).
This change makes the stub server to run long enough for failing connection
attempts on Windows, so that DevModeHandler startup could ensure it is
still running after that connection error.
> fix(tests): extend timeouts for stub webpack server connection attempts

- flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeDetailsElement.java
- flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/NativeDetailsElementIT.java
- flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/NativeDetailsView.java
- flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeDetails.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/NativeDetailsTest.java
- flow-server/src/main/java/com/vaadin/flow/component/Tag.java
Reasoning: Currently `<details>` is missing from the list of html components. This PR fixes this. 
`NativeDetails`  is based on `vaadin-details` except that the html property is called `open` instead of `opened` and the event is called `Toggle` like the html dom event. 
To reduce the API noise `NativeDetails` extends `HtmlComponent` instead of `HtmlContainer`. `HasText` and `HasComponents` would interfere with the already set `<summary>` inside the `<details>`.
> feat: implement NativeDetails as html component

- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
`((VaadinServletRequest) request).getRequestURL().toString()` is currently used in the `getServiceUrl` method. However, this code already exists as method `getRequestUrl`. Thus, we should use `getRequestUrl`.
> Use existing getRequestUrl method

- flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
- flow-tests/pom.xml
- flow-tests/test-application-theme/test-reusable-as-parent/pom.xml
- flow-tests/test-application-theme/test-theme-live-reload/pom.xml
- flow-tests/test-application-theme/test-theme-reusable/pom.xml
- flow-tests/test-embedding/test-embedding-application-theme/pom.xml
- flow-tests/test-misc/pom.xml
- flow-tests/test-root-ui-context/pom.xml
- flow-tests/test-router-custom-context/src/main/java/com/vaadin/flow/contexttest/ui/AppShell.java
- flow-tests/test-router-custom-context/src/main/java/com/vaadin/flow/contexttest/ui/DependencyLayout.java
- flow-tests/test-themes/pom.xml
Flow tests should not use app shell annotations
on wrong classes. Only exception is the push
test module.
Embedded exporters are allowed to have both
push and theme annotations as they are stand
alone applications.
Closes #9379
> chore: Update tests to not accept faulty annotations

- fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
Deleting the entire frontend/generated directory before
generating its contents again triggers webpack recompilation
in an invalid file state during live reload on Windows. Instead
don't delete frontend/generated/vaadin.ts but overwrite it later.
Fixes #9801.
> fix: delay deletion of frontend/generated/vaadin.ts

- .gitignore
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
- flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
- flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
- flow-server/src/main/resources/plugins/application-theme-plugin/package.json
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
- flow-server/src/main/resources/webpack.generated.js
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImportTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
- flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentGeneratorTest.java
Renames `theme-generated.js` to `theme.js` and moves it to `frontend/generated` folder.
Fixes: https://github.com/vaadin/flow/issues/9687
> refactor!: Move theme-generated.js to frontend/generated

- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java
The cache is only protected from multiple accesses at the same time by the same user. Many users can use it simultaneously
> Fix concurrency issue

- flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
- flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyLocalFrontendFiles.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePackageJson.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
- fusion-endpoint/src/test/java/com/vaadin/flow/server/startup/fusion/DevModeInitializerEndpointTest.java
Re-order some of the commands
so they don't by mistake fail due to
missing initializations.
Clean un-used code.
Add checks to not add commands
if missing required information.
Update old JavaDocs
Closes #9839
> chore: Make NodeTasks less failure prone

- .gitignore
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Even without platform versions we should
manage the used versions by using exactly
what is defined in the package.json
as if we had a platform versions file.
> fix: Lock versions to what is set in package.json

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
- flow-tests/test-application-theme/reusable-theme/src/main/resources/META-INF/resources/themes/reusable-theme/theme.json
- flow-tests/test-application-theme/test-theme-reusable/frontend/ts-component.ts
- flow-tests/test-application-theme/test-theme-reusable/src/main/java/com/vaadin/flow/uitest/ui/theme/TSView.java
- flow-tests/test-application-theme/test-theme-reusable/src/test/java/com/vaadin/flow/uitest/ui/theme/TSIT.java
Adds support for
"lumoImports": ["color", "typography", "badge", ... ]
to theme.json to override the default ["color", "typography"]
package.json is added to the test to be able to get only one version of @polymer/polymer
If you do not have an application theme specified, Lumo imports are injected by generated-flow-imports.js like before.
If you have an application theme, Lumo imports are injected as part of applying the theme.
In both cases, Lumo imports are added to the beginning of <head> so they are considered before any other styles, such as @CssImport:ed stylesheets. This allows overriding Lumo CSS rules no matter how you add the CSS.
Fixes #9765
> Inject Lumo CSS into shadow roots

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/resources/webpack.generated.js
- flow-tests/test-application-theme/test-theme-reusable/src/main/java/com/vaadin/flow/uitest/ui/theme/MyLitField.java
- flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/MyLitField.java
- flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/MyLitField.java
> fix: peer dependency errors in npm 7 install

- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
This hardens the framework against a theoretical timing attack based on
comparing how quickly a request with an invalid CSRF token is rejected.
> Use time-constant comparison for CSRF tokens

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/main/resources/pnpmfile.js
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
Remove pnpm-lock.yaml when package.json dependencies 
are updated to work around pnpm/pnpm#2587. Invoke pnpm
via `npx` instead of installing into `~/.vaadin/node_modules`.
Part of #9719
> feat: support current pnpm versions

- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
This is the same as #9875, but also applied for the upload security key
and the push id since both of those are also used to protect against
cross-site attacks. In addition, documentation for the push id is
clarified to point out its role.
> fix: use time-constant comparison for security tokens

- flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
- flow-server/src/main/java/com/vaadin/flow/component/UI.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
CSRF tokens in Vaadin follow the "synchronizer token pattern" rather
than the double submit cookie that some code comments refer to. Existing
comments are clarified to avoid confusion for anyone reviewing our
security practices.
> Clarify CSRF token comments

- flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
changes in #9553 is solved the problem of start-stop: 
https://github.com/vaadin/spring/issues/691, but resulted 
in occasional failures with ServiceException / 
TaskRejectedException: #9785.
Fixes: #9785
> fix: revert changes made for resolving start-stop issue

- flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
This private method is no longer used and can be removed.
> Remove unused private method

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/UnknownTaskException.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java
NodeTasks are now sorted before
execution so that they are always
executed in a predefined order.
Fixes #9893
> fix: Tasks are sorted for execution

- flow-server/src/main/java/com/vaadin/flow/internal/UsageStatistics.java
- flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
- pom.xml
Several changes which enable reusing forks during the surefire (unit tests) phase. As a result, a new jvm is not started for each unit test class and a 5 minute build time gain is experienced for the full build.
Fixes: #9885
> build: enable reuse of forks during unit tests

- flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
- flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/EventHandler.java
- flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/ModelItem.java
- flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
Add recommendation to use LitTemplate
instead of PolymerTemplate into polymer
JavaDocs.
Closes #8862
> chore: Recommend lit over polymer

- flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/UrlValidationIT.java
To not be in a loop we wait until
a view with a component can be opened
and then test the forbidden response.
> chore: Open a view before testing.

- flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/UrlValidationIT.java
To not be in a loop we wait until
a view with a component can be opened
and then test the forbidden response.
Closes #9981
> chore: Open a view before testing. (#9998)

- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.ts
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
TestBench wait logic is based the existence of Flow object
and in Fusion Only apps Flow object should not be initialized.
moving _vaadintheme_something and devModeGizmo to Vaadin 
namespace fixes the TB wait logic in Fusion Only apps.
Fixes: #9905
> fix: level up namespace of devModeGizmo and theming objects to Vaadin

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Fixes https://github.com/vaadin/flow/issues/9988
> fix: Resolve requested range properly after filtering the lazy backend

- flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html
- flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js
This change is to workaround a buggy behavior related with `flow-component-renderer` and `iron-list`.
For more info (https://github.com/vaadin/vaadin-flow-components/issues/437#issuecomment-757800924)
Fix /vaadin/vaadin-flow-components#437
> fix: make FCR try to attach child on appear

- flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
- flow-client/src/test/frontend/ConnectTests.ts
The `isFlowLoaded()` only checks if `$wnd.Vaadin.Flow` is defined. The `project-name.generated.js` file in a SVC project would also define Flow with
```
window.Vaadin = window.Vaadin || {};
window.Vaadin.Flow = window.Vaadin.Flow || {};
window.Vaadin.Flow['_vaadintheme_fusion-with-endpiont_globalCss'] = window.Vaadin.Flow['_vaadintheme_fusion-with-endpiont_globalCss'] || [];
```
So updated the check to see if `Flow.clients.TypeScript` is defined.
> fix: check if Flow is initiated for connection indicator

- flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
- flow-server/src/test/java/com/vaadin/flow/component/page/PageTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PageView.java
Page::fetchCurrentUrl can be used to asynchronously get the current url from the browser.
Closes https://github.com/vaadin/flow/issues/1897
> feat: enable fetching browser URL

- flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
Fixes #8149
(cherry picked from commit 00827e870dd1a5956d42c909655588b9df71523d)
> fix: Don't throw an exception if servlet class can't be loaded (#8233)

- flow-client/pom.xml
- flow-client/src/main/resources/com/vaadin/ClientEngineXSI.gwt.xml
- flow-client/src/test/java/com/vaadin/client/flow/ClientEngineSizeIT.java
Since 15 all goes through webpack tooling and gets compressed there.
Also fixes build on arm based macs, due the issues with abandoned jbrotly project
> fix: remove obsoleted client engine pre-compression

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/types.d.ts
- flow-server/src/main/resources/webpack.generated.js
This makes it so that you can import a CSS file into document scope with an import like:
```ts
import './about-view.global.css';
```
(using a `*.global.css` filename suffix)
instead of needing something like:
```ts
import '!style-loader!css-loader!./about-view.css';
```
It also makes it so that using a `CssResult` imported like:
```ts
import styles from './my-component.css';
```
will show a deprecation warning (based on an update to `types.d.ts`).
To avoid the deprecation and future proof your import you need to use a filename suffix `*.shadow.css` when you need to import a CSS file as a `CssResult` like this:
```ts
import styles from './my-component.shadow.css';
```
It's intended that in the next major version (after this has been released) the default behaviour for `*.css` will change …
> feat: global CSS loader

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/types.d.ts
- flow-server/src/main/resources/webpack.generated.js
* feat: global CSS loader
Closes #9970
* docs: add deprecation message description
(cherry picked from commit 70641dd61eb3295f5c66991111b4f4fa103207dc)
> [6.0] feat: global CSS loader (#10036)

- flow-tests/test-application-theme/test-reusable-as-parent/src/test/java/com/vaadin/flow/uitest/ui/theme/ParentThemeIT.java
- flow-tests/test-application-theme/test-theme-reusable/src/test/java/com/vaadin/flow/uitest/ui/theme/ReusableThemeIT.java
- flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
- flow-tests/test-embedding/test-embedding-reusable-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
- flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Update the way we get the text-field input
field as the original way has problems
when multiple fields exist on the page as the
id will depend on initialization order.
This was only apparent on the embedded test side.
Fxes #10065
> chore: Update how input field is gotten

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePackageJson.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Always write the package json after
updateDefaultDependencies as even if
the dependencies are not updated the
defaults may be updated.
Fixes #10032
> chore: write package json for default changes

- flow-server/src/main/java/com/vaadin/flow/component/HasSize.java
- flow-server/src/main/java/com/vaadin/flow/component/Unit.java
- flow-server/src/test/java/com/vaadin/flow/component/HasSizeTest.java
- flow-server/src/test/java/com/vaadin/flow/component/HasSizeUnitTest.java
- flow-server/src/test/java/com/vaadin/flow/component/UnitTest.java
Improves the addition to `HasSize` for `Unit`. 
* adds `getWidthUnit` and `getHeightUnit` for better discoverability
* Open Questions:
* Optional<Unit> vs. null vs. Unit.PIXELS as default?
*  Adding those APIs for Min/Max as well? This would increase the amount of methods quite a lot with less gain
* improve performance of `Unit`
* change streaming to simple for-each 
* change ordering of enum values, most used (% > px > others) 
* Open Questions:
* Should I replace the streaming API in `getSize` as well? 
* adds missing units `vw`, `vh`, `vmin` and `vmax`
> feat: add getters for used Unit to HasSize

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Always write the package json after
updateDefaultDependencies as even if
the dependencies are not updated the
defaults may be updated.
Fixes #10032
> chore: write package json for default changes (#10081)

- flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
- flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
- flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
- flow-client/src/test/frontend/ConnectTests.ts
- flow-client/src/test/frontend/ConnectionStateTests.ts
- flow-client/src/test/frontend/FlowTests.ts
When transitioning back from `LOADING`, don't assume `CONNECTED`.
> fix: remember original state after LOADING

- fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
This hardens the framework against a theoretical timing attack based on
comparing how quickly a request with an invalid CSRF token is rejected.
No tests since this functionality is equivalent to the previous implementation aside from timing differences that would be very fragile to verify in an automated test.
Related to https://github.com/vaadin/flow/pull/9875
> Use time-constant comparison for CSRF tokens in endpoint

- flow-server/src/main/resources/webpack.generated.js
Earlier was always created because of a version.json file in the folder
Fixes #10155
> Actually create 'export' bundle only when there are exported web components

- flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java
- flow-server/src/main/java/com/vaadin/flow/di/OneTimeInitializerPredicate.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
- flow-server/src/test/java/com/vaadin/flow/di/LookupIntializerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
RouteRegsitry should not be cleaned up every time when new routes are
set: there may be interim registry modification which adds routes. Such
routes should not be removed but they should stay in the registry.
fixes #10109
> fix: don't clean registry on every new routes set (#10162)

- flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinServletRequest.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinServletResponse.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/FaviconHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/CustomVaadinServiceImplementationTest.java
- flow-server/src/test/java/com/vaadin/flow/server/OtherImplementationsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
I cases you are not using the `VaadinServletService` because you ship your own own (Servlet-based) `VaadinService`.
Then you are, at the moment, not able to use fundamental classes like `VaadinServlet`. This is because they use your VaadinServletService. But you are not using any methods of VaadinServletService because VaadinService is enough. So I suggest to use superclasses if possible.
`VaadinServletRequest`needs a `VaadinServletService`
```
@Override
public VaadinServletService getService() {
return vaadinService;
}
```
If you have your own VaadinService implementation you can't rely on VaadinServletRequest
ant an the moment you cant use a lot of classes like `VaadinServlet`, `PushRequestHandler`, `StreamResourceHandler`, `WebComponentBootstrapHandler`
> feat: use superclass of VadinServlet/Request if possible

- flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
- flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
- flow-server/src/main/resources/plugins/application-theme-plugin/package.json
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
- flow-server/src/main/resources/webpack.generated.js
- flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
- flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
- flow-tests/test-themes/frontend/theme/app-theme/theme.json
- flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
- flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
> Css from node_modules, theme resources

- flow-server/src/main/java/com/vaadin/flow/server/PWA.java
- flow-server/src/main/java/com/vaadin/flow/server/PwaConfiguration.java
- flow-server/src/test/java/com/vaadin/flow/server/PwaConfigurationTest.java
Fixes https://github.com/vaadin/flow/issues/10148
No ITs, since the install workflow is to be tested manually. One can follow [this article](https://support.google.com/chrome/answer/9658361?co=GENIE.Platform%3DDesktop&hl=en) to install an PWA app  to Chrome. Note the icon is a bit different compare to the article, instead of a + icon, it's a ![Screenshot 2021-03-04 at 15 33 31](https://user-images.githubusercontent.com/30408303/109971509-03f7ac80-7cff-11eb-8585-1e4766681907.png)
> fix: set default PWA start_url as "." instead of ""

- flow-client/.prettierrc.js
Prettier by default enforces Linux-style LF line endings. Modify the config to accept CRLF after checkout on Windows.
> chore: automatic end-of-line for prettier

- flow-lit-template/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
- flow-polymer-template/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
- flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java
- flow-server/src/main/java/com/vaadin/flow/server/StaticFileHandlerFactory.java
- flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/LookupServletContainerInitializer.java
- flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
- flow-server/src/test/java/com/vaadin/flow/di/LookupInitializerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
- flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
> refactor: use StaticFileHandler as a service

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Caches stats.json file loaded from class path and improves the performance by not being opening too many stats.json files under the load.
Fixes #10116
> perf: Cache stats.json loaded from class path

- flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeButtonElement.java
- flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
- flow-server/src/main/java/com/vaadin/flow/component/Shortcuts.java
- flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
- flow-server/src/test/java/com/vaadin/flow/component/ShortcutsTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DialogShortcutView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DialogShortcutIT.java
This makes it possible for a component to specify a client side only
element that should be used for listening keydown events on when the
component is setup as the listenOn target for a Shortcut. This is needed
for components like Vaadin Dialog which transport the dialog contents
inside an overlay that only exists on the client side and thus breaks
shortcut event handling.
Related to #7799, vaadin/vaadin-dialog#229
> fix: fix shortcuts when listenOn is a dialog

- flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
- flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/EnableOSGiRunner.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ServletContextResourceIT.java
fix: avoid exposing ServletContext resources via StaticFileServer 
fixes #10260
> fix: avoid exposing ServletContext resources via StaticFileServer (#10261)

- flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
- flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/EnableOSGiRunner.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ServletContextResourceIT.java
(#10261)
* fix: avoid exposing ServletContext resources via StaticFileServer in
OSGi
fixes #10260
> fix: avoid exposing ServletContext resources via StaticFileServer

- flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeButtonElement.java
- flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
- flow-server/src/main/java/com/vaadin/flow/component/Shortcuts.java
- flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
- flow-server/src/test/java/com/vaadin/flow/component/ShortcutsTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DialogShortcutView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DialogShortcutIT.java
This makes it possible for a component to specify a client side only
element that should be used for listening keydown events on when the
component is setup as the listenOn target for a Shortcut. This is needed
for components like Vaadin Dialog which transport the dialog contents
inside an overlay that only exists on the client side and thus breaks
shortcut event handling.
Related to #7799, vaadin/vaadin-dialog#229
> fix: fix shortcuts when listenOn is a dialog (#10264)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
fixes #9366
Instead of wrapping only the return, I wrapped the whole method to make sure random exception are closing the stream as well. 
Reasoning behind the change:
>  Wherever possible, the methods in this class do not flush or close the stream. This is to avoid making non-portable assumptions about the streams' origin and further use. Thus the caller is still responsible for closing streams after use. 
Source: http://commons.apache.org/proper/commons-io/javadocs/api-release/org/apache/commons/io/IOUtils.html
> fix: close InputStream in FrontendUtils

- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
When troubleshooting TaskRunNpmInstall tests, having debug output logged
is very useful. Mocking the logger in the tests used to eat up all the
log.
This change makes use of spy instead of mock as a test logger to enable
logging the tested task output.
> test: enable logging for TaskRunNpmInstall tests

- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
- flow-server/src/test/resources/META-INF/VAADIN/config/stats_no_export.json
Makes it possible to reconfigure webpack to put exported wcs elsewhere
> fix: only use the export chunk for exported web components if it is found

- flow-plugins/flow-maven-plugin/pom.xml
- flow-plugins/flow-plugin-base/pom.xml
Move the fusion-endpoint dependency from
maven-plugin to plugin-base as it is needed
in other plugins also.
Fixes #10312
> fix: move fusion-endpoint dependency

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Caches stats.json file loaded from class path and improves the performance by not being opening too many stats.json files under the load.
Fixes #10116
> perf: Cache stats.json loaded from class path (#10303)

- flow-server/src/main/resources/webpack.generated.js
- flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Reduce frontend build time for non-PWA applications by not running the service worker Webpack plugin.
> chore: skip service worker plugin for non PWAs

- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FragmentLinkIT.java
Remove hasClientIssue(8236) guards for ITs that now pass. Related to #10327.
> chore: removed hasClientIssue(8236) guard

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
Forward port vaadin/framework#12230
> fix: Prevent NPE when writing field value to bean

- flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
- flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DialogShortcutView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DialogShortcutIT.java
Only passes the delegated event forward when it maps to the shortcut key.
For the shortcut key, preventDefault() is the default behavior and default
can be allowed with allowBrowserDefault() in the ShortcutRegistration.
Fixes #10362
> fix: Make shortcuts not break writing on inputs

- flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Removes DevModeHandlerTest::start_twoInstances_secondInstanceUsesAnotherPort because it relies on web pack startup time: if it starts fast enough, then the second handler instance may see that it occupies the port and just reuse that port, test will fail then. If webpack is starting slowly, the second handler sees that the port is not used by webpack and starts another instance of webpack. Then the tests passes.
Fixes #10101
Related-to #9061
> test: Remove the test because it relies on Webpack startup time

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
- flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
If offline and the file requested is in the precache manifest, then serve it as is.
Fixes #10031
> fix: do not serve appshell/offline page for cached resource

- flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
- flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
- flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
- flow-client/src/test/frontend/ConnectTests.ts
- flow-client/src/test/frontend/ConnectionStateTests.ts
- flow-client/src/test/frontend/FlowTests.ts
Added method loadingFailed transitioning to CONNECTION_LOST if it
is the last active loading. Also removed the exposed
Vaadin.Flow.clients.TypeScript.loadingStarted / loadingFinished pair, as
blocking TB is anyway not working for multiple ongoing backend calls
(and it would be better handled by register ConnectionState as a Flow
client with isActive flag).
> fix: remember original state after LOADING (#10099)

- flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java
Temporary solution for https://github.com/vaadin/flow/issues/10429
> chore: Disable flaky test in MigrationTest

- flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
> fix: do lazy initialization in a thread-safe way

- flow-tests/test-embedding/test-embedding-reusable-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Disables the flaky test in ApplicationThemeComponentIT of test-embedding-reusable-theme module.
Temporary solution for #10331
> chore: disable flaky theme component test

- flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
- flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/BundleParserTest.java
> fix: allow spaces between html function call and back tick

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Adds a package file name to exception message in case of JsonException in order to provide clean explanation where to look into.
Fixes #10323
> fix: Provide info on file name when Json parsing fails

- flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/WebComponentIT.java
Waits for the elements in 'show-message' web component shadow-dom to be appear before testing them.
Fixes https://github.com/vaadin/flow/issues/10364
> test: Fix flaky tests in WebComponentIT

- flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/StreamReceiverHandlerTest.java
> fix: don't use ErrorHandler for IOExceptions in StreamReceiverHandler

- flow-plugins/flow-gradle-plugin/build.gradle
As build.gradle script is just a build-related
file, it does not need a license header.
> chore: remove license header from build.gradle

- flow-server/src/main/java/com/vaadin/flow/router/Location.java
- flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
- flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java
- flow-server/src/test/java/com/vaadin/flow/router/QueryParametersTest.java
- fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java
This is a prerequisite for #10431 split out to a separate PR for easier review
> Add support for parsing query string in QueryParameters

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/InlineTargets.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
This is what is mostly needed for all implementations and getting it through
the request is more a workaround. The request is typically not needed at all
and relying on the internals of the request is problematic if we change how the
request is done, as is being done in e.g. #10431
> Add getService() to BootstrapContext

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Adds the package file name to exception message in case of JsonException in order to provide clean explanation where to look into.
Fixes #10323
(cherry picked from commit 1ea4ceffefc8f364261abea7f3d925c9f31e94a6)
> fix: Provide info on file name when Json parsing fails (#10423) (CP 2.5)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Adds the package file name to exception message in case of JsonException in order to provide clean explanation where to look into.
Fixes #10323
(cherry picked from commit 1ea4ceffefc8f364261abea7f3d925c9f31e94a6)
> fix: Provide info on file name when Json parsing fails (#10423)

- flow-client/pom.xml
ResourceCompressor plugin requires jbrotli which is not available
anymore. So the plugin which doesn't apply brotli compression via
jbrotli should be used.
> chore: use another compression plugin which uses only gzip (not brotli)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
pnpm >= 6.0.0 requires at least Node.js v12.17. This requirement may not be satisfied as framework current accepts Node.js 10.
pnpm 6.0 can be used with newer Node.js versions if the versions check is disabled with `vaadin.ignoreVersionChecks=true`. But in pnpm 6 the pnpmfile.js is renamed to .pnpmfile.cjs and thus the Flow generated pnpmfile.js will not be used by pnpm - meaning that versions are not locked.
Fixes #10571
> fix: force pnpm version <= 5

- flow-plugins/flow-gradle-plugin/pom.xml
As there is some problem with running
the functional tests in the CI
we will skip them for the time being
> Chore: skip functionalTests for gradle

- flow-server/src/main/resources/plugins/theme-live-reload-plugin/package.json
- flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
Switching the theme name in `@Theme` annotation triggered/created a new [other-theme].generated.js file, which is being watched by webpack and trigger another live-reload in turn. 
Thus, the endless loop took place. 
This fix skips the live reload for all generated theme files, no matter which name it has.
Related-to #10451
> fix: Skip any generated files in theme live reload plugin

- flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
- flow-client/src/test/frontend/AuthenticationTests.ts
- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
> 6.0 cherry pick 

- flow-server/pom.xml
It seemingly serves no purpose and breaks linking to source files in VS Code in some cases (VS Code links to the file in the target folder instead)
> Do not include test sources in 'target'

- scripts/cherryPick.js
cherrypick-bot failed silently when we close a PR without merging with `target/*` label.
this fix will let the bot comment before failing the build, so we can fix the PR manually
> chore: push comment before following steps when cherrypicking

- flow-server/src/main/resources/plugins/theme-live-reload-plugin/package.json
- flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
- flow-server/src/main/resources/webpack.generated.js
Extracts the custom theme name from frontend generated folder and skips theme handling when the theme generated file is being created/updated.
Related-to #10451, #10544
IT test to cover component styles live reload is being worked in a separate PR https://github.com/vaadin/flow/pull/10584, it is flaky still.
IT test to cover themes switch is under work still.
> fix: Extract theme name from proper folder and skip generated files

- flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
> chore: make thread-safe access to NpmTemplateParser internal state

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsLocator.java
> fix: avoid log an error if frontend tool can't be found

- flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
Log as error any output from webpack when
webpack exits prematurely.
Closes #7472
> fix: Log webpack output on failure

- fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java
- fusion-endpoint/src/test/java/com/vaadin/flow/server/startup/fusion/DevModeInitializerEndpointTest.java
Fixes #10545 
The `TsFormTest` was ignored in the Window build steps, now reenabled.
> test: ignore the file path comparison in comment of generated ts model

- flow-server/src/main/resources/webpack.generated.js
Watch the components folder for component styles update.
Other folders or CSS files except 'styles.css' should be referenced from `styles.css` anyway, so no need to watch them.
Related-to #10544
> fix: Watch for a new CSS only in components folder

- flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
- flow-client/src/test/frontend/AuthenticationTests.ts
- scripts/cherryPick.js
The [Vaadin security helper](https://github.com/vaadin/spring/blob/master/vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java) now has a request cache by default, which means that if a user tries to access an authentication protected view, the request will be saved and has it as a `redirectUrl` in the response. 
The logic in the `login()` helper didn't take this request cache into account.
Part of #10357, which fixes the bug.
> fix: cannot login to authentication protected view

- pom.xml
Update the directory-maven-plugin to not
fail the build on windows when the CWD
drive letter is lower case.
Closes #8959
> fix: windows drive can be upper or lower case

- flow-server/src/main/resources/webpack.generated.js
Removes overlooked unused themeName parameter for theme live reload plugin.
Related-to: https://github.com/vaadin/flow/issues/10451
> fix: Exclude theme name from plugin parameters

- flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Fixes a race condition which manifested as stale webpack-dev-server instances
on the CI.
Part of #10615.
> test: wait for dev-mode-server in test

- flow-server/src/main/resources/webpack.generated.js
Add the devMode plugin property that
is missing from the themeOptions
Closes #10621
> fix: add missing plugin property

- flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
- flow-client/src/test/frontend/AuthenticationTests.ts
It includes the `redirectUrl` in the return value of the `login()` helper. So that if the user has defined a request cache or a defaultSuccessUrl in the Spring Security configuration, user can use the `redirectUrl` in `LoginResult` to redirect instead of maintaining a `returnUrl` manually as in the current doc, which also doesn't work when a request cache or a defaultSuccessUrl is configured. 
Part of https://github.com/vaadin/flow/issues/10357
> fix: include redirectUrl in the return value of login()

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
- flow-server/src/test/resources/versions/package.json
- flow-server/src/test/resources/versions/versions.json
Any framework managed version that is newer
than the version in platform versions should be
left as is as the version probably is from an updated
annotation.
Fixes #9793
> fix: Accept newer framework managed versions

- flow-plugins/flow-maven-plugin/pom.xml
- flow-plugins/flow-plugin-base/pom.xml
the fusion-endpoint module is only needed for test the plugin module
> chore: mark fusion-endpoint as test dependency for flow maven plugin

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/resources/webpack.generated.js
> fix: allow TypeScript in V14 server bootstrapping mode

- flow-test-util/src/main/java/com/vaadin/flow/testcategory/ThemeLiveReloadTests.java
- flow-tests/pom.xml
- flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
- flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
Adds a new category for theme live reload tests and skips them by default.
Creates a new profile for running only those tests separately.
> chore: Move theme live reload tests to it's own profile

- flow-server/src/main/resources/plugins/theme-loader/theme-loader.js
- flow-tests/test-themes/frontend/themes/app-theme/styles.css
- flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
- flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
If a resource is not found in themes folder
check also any assets that are copied for
the theme.
fixes #10426
> fix: Check assets for url handling

- flow-test-util/src/main/java/com/vaadin/flow/testcategory/ThemeLiveReloadTests.java
- flow-tests/pom.xml
- flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
- flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
- pom.xml
Reverts adding overcomplicated test categories approach, because test reordering can be done easily in `run-tests` profile.
`run-tests` was changed here https://github.com/vaadin/flow/pull/10629
> chore: Revert test categories

- flow-server/src/main/java/com/vaadin/flow/dom/ElementUtil.java
- flow-server/src/test/java/com/vaadin/flow/dom/ElementUtilTest.java
> fix: extend and clarify valid tag names

- build-tools/pom.xml
We need this artefact in other projects that follow flow formatting rules like in flow-components
> chore: deploy flow-buildtools in order to be used in other projects

- flow-client/package.json
The build was broken on Windows due to using single quotes instead of double quotes to wrap a path in an npm script. The problem was introduced by #10765.
> fix: flow-client build on Windows

- flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
- flow-tests/test-application-theme/test-theme-component-live-reload/frontend/themes/app-theme/components/empty
- flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
Workaround for #9948. Warn devs to delete component CSS file along with theme generated file in one run to avoid webpack compilation errors and application restart.
Related-to: #9948
(cherry picked from commit e33ec10fd591251fae6c26fcd05b358a1da053e4)
> fix: Warn to delete component CSS with theme generated in one run

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
- flow-tests/test-application-theme/reusable-theme/src/main/resources/META-INF/resources/themes/reusable-theme/theme.json
- flow-tests/test-application-theme/test-theme-reusable/src/main/java/com/vaadin/flow/uitest/ui/theme/ReusableThemeView.java
- flow-tests/test-application-theme/test-theme-reusable/src/test/java/com/vaadin/flow/uitest/ui/theme/ReusableThemeIT.java
Adds support for
"lumoImports": ["color", "typography", "badge", ... ]
to theme.json to override the default ["color", "typography"]
If you do not have an application theme specified, Lumo imports are injected by generated-flow-imports.js like before.
If you have an application theme, Lumo imports are injected as part of applying the theme.
In both cases, Lumo imports are added to the beginning of <head> so they are considered before any other styles, such as @CssImport:ed stylesheets. This allows overriding Lumo CSS rules no matter how you add the CSS.
Related-to #9767 #9983
> feat: Backport 'Inject Lumo CSS also into shadow roots' to 2.6

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Upgrades to LitElement 2.5 which is forward compatible with LitElement 3 aka Lit 2
Fixes #10826
> Upgrade to LitElement 2.5.0 and lit-html 1.4.0

- pom.xml
Updates maven surefire and failsafe plugins versions to 2.22.2 which has a fix for `Corrupted STDOUT by directly writing to native stream in forked JVM 1`, which occasionally thrown in the pull request validation builds.
See https://issues.apache.org/jira/browse/SUREFIRE-1614
> chore: Update maven plugins versions

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
> Auto-install Node 16

- flow-bom/pom.xml
> fix: include flow-dnd module to flow-bom

- flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
If there are more than one theme available in
themes folder, user can switch between them in
development mode by changing the name of the
theme in `@Theme`. As having a watch for adding
new styles in component folder is 'static' and could
not be changed to another theme folder dynamically, 
at least a log about this limitation can help the users.
Fixes #10680 
This PR does not change any existing behavior, just adds some logs that can help users to find out when a restart is needed to see the effect of their changes in the available themes.
> fix: log limitation of adding new styles while switching themes

- flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/PathUtil.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterConfigurationUrlResolvingTest.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/PathUtilTest.java
Allow having empty segment as first segment
for parameters.
fixes #10729
> fix: allow empty segments at start

- flow-server/src/main/java/com/vaadin/flow/router/internal/PathUtil.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterConfigurationUrlResolvingTest.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/PathUtilTest.java
Fixes a regression with HasUrlParameter by allowing to have an empty segment as first segment for parameters.
Fixes #10729
> fix: allow empty segments at start (#10921)

- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
The `withConverter_writeBackValue` test was passing on systems where `Locale.getDefault()` is the same as `Locale.getDefault(Locale.Category.FORMAT)`, and failing on systems where these locales differ (e.g. Corretto 11 on Windows with country Finland and language English).
> chore: fix a locale-dependent Binder unit test

- flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
- flow-html-components/src/main/java/com/vaadin/flow/component/html/AnchorTarget.java
- flow-html-components/src/main/java/com/vaadin/flow/component/html/AnchorTargetValue.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTargetValueTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
Cherry-picks #8397
Fixes #8346
Co-authored-by: Denis Anisimov <denis@vaadin.com>
> feat: Add target enums for Anchor (#8346) (#8397)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
- flow-server/src/test/resources/specialCharacterValue.json
Use IOUtils toString and toInputStream
to not change any characters in the file content.
Using streamToString adds new lines for each usage,
but this can not be done for a json file that contains
in the string content new lines.
fixes #10893
> fix: Use IOUtils toStream and toString

- flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalFilterUtils.java
This is not an actual bug, but the attribute name should be consistent with others.
Other methods in the same file use "query" as an attribute name.
> Fix an inconsistency about the attribute name in HierarchicalFilterUtils.java

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> fix: Change construct-style-sheets-polyfill to be a runtime dependency (#10991)

- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
- flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/RouterLayoutCustomScopeServlet.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RemoveRoutersLayoutContentIT.java
Recursively removes content of the all nested router layouts of the given old content when the navigation occurs. 
This is needed to let Dependency Injection frameworks (Spring and CDI add-ons) to re-create managed components with no duplicates/leftovers.
Consider the following router target chain before navigation:
```
MainRouterLayout
|__SubRouterLayout
|__MyRouteView
```
And after navigation the whole chain can be replaced:
```
AnotherRouterLayout
|__AnotherRouteView
```
Or some part of it:
```
MainRouterLayout
|__AnotherRouteView
```
Route target `MyRouteView` will be removed before navigation in order to let DI framework to insert it by itself with no leftovers, depending on the scope of `MyRouteView`. It might be a new instance of `MyRouteView` or a preserved one.
Fixes …
> fix: Remove old router layouts content before navigation

- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
- flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/RouterLayoutCustomScopeServlet.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RemoveRoutersLayoutContentIT.java
Recursively removes content of the all nested router layouts of the given old content when the navigation occurs.
This is needed to let Dependency Injection frameworks (Spring and CDI add-ons) to re-create managed components with no duplicates/leftovers.
Fixes vaadin/cdi#345
Co-authored-by: @roeltje25
(cherry picked from commit 5f5fdcd1754bd283ba3f787d3d4dee0ca57955de)
> fix: Remove old router layouts content before navigation (#10973)(CP: 2.6)

- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
- flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/RouterLayoutCustomScopeServlet.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RemoveRoutersLayoutContentIT.java
Recursively removes content of the all nested router layouts of the given old content when the navigation occurs.
This is needed to let Dependency Injection frameworks (Spring and CDI add-ons) to re-create managed components with no duplicates/leftovers.
Fixes vaadin/cdi#345
Co-authored-by: @roeltje25
(cherry picked from commit 5f5fdcd1754bd283ba3f787d3d4dee0ca57955de)
> fix: Remove old router layouts content before navigation (#10973)(CP: 2.7)

- flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
Explicitly registers RouterLayoutCustomScopeServlet in OSGi.
Related-to https://github.com/vaadin/flow/pull/10973
> test: Explicitly register test servlet in OSGi

- flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
Explicitly registers RouterLayoutCustomScopeServlet in OSGi.
Related-to #10973
(cherry picked from commit 4a8dc42a874c62a5ed6a0b8729286f4550b1f61c)
> test: Explicitly register test servlet in OSGi (#11018)(CP: 2.7)

- flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
Explicitly registers RouterLayoutCustomScopeServlet in OSGi.
Related-to #10973
(cherry picked from commit 4a8dc42a874c62a5ed6a0b8729286f4550b1f61c)
> test: Explicitly register test servlet in OSGi (#11018)(CP: 2.6)

- flow-server/src/main/java/com/vaadin/flow/router/Router.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationRouteTarget.java
- flow-server/src/main/java/com/vaadin/flow/server/ErrorRouteRegistry.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
- flow-server/src/test/java/com/vaadin/flow/router/internal/TestAbstractRouteRegistry.java
- flow-tests/pom.xml
- flow-tests/test-custom-route-registry/pom.xml
- flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomErrorHandler.java
- flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomInitListener.java
- flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomNotFoundView.java
- flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomRoute.java
- flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomRouteRegistry.java
- flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomServlet.java
- flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomServletService.java
- flow-tests/test-custom-route-registry/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
- flow-tests/test-custom-route-registry/src/test/java/com/vaadin/flow/custom/CustomRouteIT.java
Make it possible to create a custom
RouteRegistry and add test module for it.
Fixes #11022
> fix: Using a custom RouteRegistry

- flow-client/src/main/frontend/Authentication.ts
Fixes https://github.com/vaadin/flow/issues/10997
> fix: use relative path for default login/logout processing url

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/resources/webpack.generated.js
This change updates the import for CSS files processed with `lit-css-loader` to get rid of the warning:
```
"The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.""
```
See https://github.com/vaadin/flow-components/pull/928#issuecomment-833478933
> feat: bump lit-css-loader for Lit 2

- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/Platform.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
Use the x64 package for mac if the installed
node version is < 16.0.0 as ARM package
is not available before this.
Fixes #11060
> fix: x64 version for mac if node old

- flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
- flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/DefaultErrorHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Annotate default error handlers with
the new annotaton DefaultErrorHandler
so that we can also in add-ons have default
handlers that can be overridden by user
handlers.
Part of vaadin/spring#661
> fix: Annotate default error handlers.

- flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
- flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
- flow-server/src/main/java/com/vaadin/flow/router/internal/DefaultErrorHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
- flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Annotate default error handlers with
the new annotaton DefaultErrorHandler
so that we can also in add-ons have default
handlers that can be overridden by user
handlers.
Part of vaadin/spring#661
> fix: Annotate default error handlers. (#11063)

- flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerImpl.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeHandlerImplTest.java
The webpack dev-server does not escape " character, as it is not valid
URL. This limitation was not checked when passing request to it via
DevModeHandlerImpl.
> fix: prevent passing bad character to dev-server

- flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
- flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
The webpack dev-server does not escape " character, as it is not valid
URL. This limitation was not checked when passing request to it via
DevModeHandlerImpl.
> fix: prevent passing bad character to wp (#11099)

- flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
Gives a clue in case the vaadin-dev-server module is accidentally excluded in dev mode.
> chore: warn about missing DevModeHandlerManager

- flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
- flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
Add check to the resource to see
if it is a directory and do not serve
if this is the case.
Fixe #11047
> fix: don't serve directories as static files (#11072)

- flow-server/src/test/java/com/vaadin/flow/server/CustomUIClassLoaderTest.java
- flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
Running tests in JDK16 fails if appConfig.getBuildFolder returns null, because a new assertion introduced in UnixFileSystem.getPath
> test: UnixFileSystem.getPath introduces null assertion in new JDKs

- flow-plugins/flow-gradle-plugin/build.gradle
- flow-plugins/flow-gradle-plugin/pom.xml
- flow-plugins/flow-gradle-plugin/src/main/java/com/vaadin/ClassToGenerateJavadocs.java
Not to be squashed as this reverts the previous failed attempt to generate those.
> create javadocs for gradle plugin [skip-ci]

- flow-plugins/pom.xml
Running gradle plugin with JDK17 EA does not work see https://github.com/gradle/gradle/issues/16857
> chore: skip gradle plugin when compiling in jdk17 early access

- flow-plugins/flow-gradle-plugin/build.gradle
Applied the same fix than in 
https://github.com/vaadin/vaadin-gradle-plugin/commit/aee343d58383c82859b0983f02f6e79fc73c8c8b from @mvysny
This fix avoid having to revert https://github.com/vaadin/flow/pull/11119
> test: fix gradle tests so as they can be run with gradle-7.0 and jdk16

- flow-server/src/main/java/com/vaadin/flow/server/auth/AccessAnnotationChecker.java
- flow-server/src/test/java/com/vaadin/flow/server/auth/AccessControlTestClasses.java
- flow-server/src/test/java/com/vaadin/flow/server/auth/ViewAccessCheckerTest.java
This allows leaving child views unannotated 
(without any of the access annotations) and the 
access annotations to be defined on any of the 
view's superclasses. 
Fixes #10705
> feat: allow defining access control annotations on view super classes

- flow-plugins/flow-gradle-plugin/pom.xml
Remove the skipTests profile as
by default we run the gradle tests in
another build.
> chore: Remove skipTests profile [skip ci] 

- flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
> fix: add javadocs warning to avoid using ResponseWriter for dirs

- flow-plugins/flow-gradle-plugin/gradle.properties
- flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
Updates gradle wrapper version to latest in order to fix issues in Flow CI like 
`java.lang.IllegalArgumentException: Supplied javaHome must be a valid directory.`
Related-to https://github.com/vaadin/platform/issues/2170
Fixes: https://github.com/vaadin/flow/issues/11159
> chore: bump gradle wrapper and disable gradle daemon

- drivers.xml
- flow-client/intern.json
Update chromedriver version so the browser tests will be run with latest Chrome (91 instead of 89).
> chore: update cromium drivers

- flow-client/src/main/frontend/form/Models.ts
- flow-client/src/test/frontend/form/FieldTests.ts
- flow-client/src/test/frontend/form/ModelTests.ts
NumberModel should read empty string as undefined so that the NumberValidator can pass the validation for an option number field when the input value is an empty string.
Fixes https://github.com/vaadin/fusion/issues/13
> fix: NumberModel should read empty string as undefined

- flow-client/package.json
Pins the ESLint plugin version because the newer one causes the build errors.
Fixes https://github.com/vaadin/flow/issues/11176
> chore: Pin ESLint plugin Lit version

- flow-client/src/main/frontend/form/Validators.ts
- flow-client/src/test/frontend/form/ValidatorsTests.ts
This change makes the TypeScript email validator accept undefined values. It fixes the runtime error when validating an empty email field on the UI, since the field is now undefined by default.
Added IT tests in https://github.com/vaadin/spring/pull/799
> fix: make ts email validator accept undefined value

- flow-client/scripts/client.js
fixes: #11149
Note, I couldn't reproduce this in my local, but happens quite often in the build platform does for JDKs tests.
I added there an extra step for patching the file with this approach and couldn't see the failure any more.
There is no way for actually test this with an IT, or at least I do not see  any.
> chore: fix random failure on copying files when building flow-client

- flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/FrontendLiveReloadIT.java
- flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Temp solution for https://github.com/vaadin/flow/issues/11201 https://github.com/vaadin/flow/issues/11210
> chore: Disable failed PWA and FrontendLiveReloadIT tests

- flow-client/src/main/frontend/form/BinderNode.ts
- flow-client/src/test/frontend/form/BinderTests.ts
Fixes a bug that Fusion form throws exceptions when reading the value of a nested property from an optional parent.
Fixes https://github.com/vaadin/fusion/issues/43.
> fix: error reading value of nested property from optional parent

- flow-client/src/main/frontend/Connect.ts
- flow-client/src/test/frontend/ConnectTests.ts
Null value in and endpoint response should be transformed to undefined in TypeScript.
Fixes https://github.com/vaadin/fusion/issues/44
> fix: transform null value in endpoint response to undefined

- flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
- flow-server/src/test/java/com/vaadin/flow/WarURLStreamHandlerFactory.java
- flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
Don't open a filesystem for unknown schemes
that are probably custom for container and
have no FileSystem Provider implementation added.
Fixes #11230
> fix: do not open FileSystem for unknown schemes

- flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
- flow-server/src/test/java/com/vaadin/flow/WarURLStreamHandlerFactory.java
- flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
Don't open a filesystem for unknown schemes
that are probably custom for container and
have no FileSystem Provider implementation added.
Fixes #11230
> fix: do not open FileSystem for unknown schemes (#11235)

- flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationConfiguration.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/ApplicationConfigurationTest.java
> fix: report Lookup instance absence with ISE and meaningful message

- flow-jandex/pom.xml
- pom.xml
Generate a jandex index for Flow
to use with quarkus.
part of vaadin/quarkus#1
Flow support for #9862 when no platform in use
> feat: generate jandex index for Flow

- flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/FrontendLiveReloadIT.java
> fix: use JS to get DOM element value instead Selenium getAttribute

- flow-client/src/main/frontend/form/Validators.ts
- flow-client/src/test/frontend/form/ValidatorsTests.ts
Fixes the bug that TypeScript form validators throw exceptions when validating null values. This could happen when loading an empty value from the backend. Related to https://github.com/vaadin/fusion/issues/44
> fix: make TS validators accept null values

- flow-plugins/flow-plugin-base/pom.xml
The goal is to remove as much external dependencies as Possible.
**org.reflections**
When updating from:
https://mvnrepository.com/artifact/org.reflections/reflections/0.9.11
To:
https://mvnrepository.com/artifact/org.reflections/reflections/0.9.12
we can get rid of com.google.guava dependency.
**commons-io**
is not used in this project directly. So we can remove it
Fixes #11226
> chore: Exclude commons-io and update org.reflections dependency

- README.md
New issues related to Fusion should be created in https://github.com/vaadin/fusion instead.
> Update the README file to mention the Fusion repo

- flow-server/src/main/java/com/vaadin/flow/dom/impl/ClassAttributeHandler.java
- flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
> fix: trim class names value before splitting

- flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/BundleLitParser.java
- flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImplTest.java
- flow-lit-template/src/test/resources/META-INF/VAADIN/config/stats.json
- flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
- flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/BundleParserTest.java
- flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
Add on templates didn't resolve correclty on windows
due to an issue in the path to flow-frontend getting
`\` instead of `/`.
Fixes #11220
Fixes #11325
> fix: Always use  unix convention for the path

- flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/BundleLitParser.java
- flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImplTest.java
- flow-lit-template/src/test/resources/META-INF/VAADIN/config/stats.json
- flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
- flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/BundleParserTest.java
- flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
Fixes a regression in Vaadin 20 with templates (.js, .ts) from add-ons which didn't resolve correclty on Windows due to an issue in the path to flow-frontend getting `\` instead of `/`.
Fixes #11220
Fixes #11325
> fix: Always use  unix convention for the path (#11326)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
Fix buildIdentifier comparison so
values compare correctly.
fixes #11352
> fix: Update buildIdentifier comparison

- flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
- flow-client/src/test-gwt/java/com/vaadin/client/GwtSuite.java
- flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtErrotHandlerTest.java
> fix: use textContent instead of innerHTML for error elements

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
Fix buildIdentifier comparison so values compare correctly.
The problem caused e.g. alphas greater than 10 to be considered older than 2-9.
fixes #11352
> fix: fixes comparison of prerelease versions FE deps (#11353)

- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
> fix: reset HTTP session on CLOSED state, not immidiately

- .gitignore
- drivers.xml
- flow-server/README.md
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
- flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
- flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
- flow-server/src/main/resources/plugins/application-theme-plugin/package.json
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
- flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
- flow-server/src/main/resources/webpack.generated.js
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImportTest.java
- flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentGeneratorTest.java
- flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
Any theme file that is generated is
now generated into `frontend/generated`
Fixes #11180
> fix: Move generated theme files to frontend/generated

- flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
- flow-client/src/test-gwt/java/com/vaadin/client/GwtSuite.java
- flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtErrotHandlerTest.java
> fix: use textContent instead of innerHTML for error elements (#11354)

- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
> fix: reset HTTP session on CLOSED state, not immidiately (#11377)

- flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
- flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
When getting a for Flow new FileSystem
there is the possibility that a filesystem
has been created elsewhere. Reuse the
existing FileSystem if it exists.
Fixes #11378
> fix: Reuse existing filesystem

- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/InvalidateHttpSessionView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InvalidateHttpSessionIT.java
> fix: reset session field only when HTTP session is invalidated

- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerCssTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerThemeTest.java
Do not revisit visited classes as
visited childer will not be rechecked
and possibly overwriten.
Always visit UI once as else we get
UI JsModule in fallback.
Fixes #9861
> fix: Don't revisit visited classes.

- flow-client/src/main/frontend/VaadinDevmodeGizmo.ts
If a persistent message is open
do not open a new permanent message
for the same persistentId.
Closes #11074
> fix: Show only single permanent notification

- flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.ts
If a persistent message is open
do not open a new permanent message
for the same persistentId.
Closes #11074
> fix: Show only single permanent notification (#11450)

- pom.xml
Align dependency management of slf4j with the latest version coming with spring boot 2.5.3 (https://github.com/vaadin/spring/pull/862)
See: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.5.3/spring-boot-dependencies-2.5.3.pom
> chore: update slf4j to 1.7.32

- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/InvalidateHttpSessionView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InvalidateHttpSessionIT.java
> fix: reset session field only when HTTP session is invalidated (#11416)

- flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
- flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
flow-server was overriding parameters set in web.xml/annotations with those found in *any flow-build-info.json* on the classpath. Now it only overrides parameters which weren't already set. Fixes #11479.
> fix: don't override web.xml, annotation config with classpath flow-build-info.json settings

- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
It is possible findOrCreateVaadinSession leaves session locked if HTTP session is invalidated in an another thread between lockSession and unlockSession calls. This PR changes the implementation so that this can no longer happen.
This is a cherry pick from: https://github.com/vaadin/framework/pull/12355
See details: https://github.com/vaadin/framework/issues/12352
TODO: Update framework version in the comments when target release is known.
> fix: Prevent deadlock in findOrCreateVaadinSession

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
This is made to avoid excessive memory usage when managing the data
fixes: #11515
> fix: Use byte[] instead of String to store stats.json

- flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java
- flow-server/src/main/java/com/vaadin/flow/server/PageConfigurator.java
> chore!: deperecate PageConfigurator since it has broken design

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/FrontendStubs.java
Checks that the npm version accepts whitespaces in user home path and explains how to fix that otherwise.
Fixes https://github.com/vaadin/flow/issues/10084
> fix: Fail-fast if the path to npm cache contains whitespaces

- flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
> fix: set Vaadin session attribute using lock

- flow-server/src/main/resources/webpack.generated.js
When copygin the webcomponentsjs
polyfill do not copy in package.json
or the md files.
closes #11560
> fix: only copy javascript files.

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Checks that the npm version accepts whitespaces in user home path and explains how to fix that otherwise.
Fixes https://github.com/vaadin/flow/issues/10084
> fix: Fail-fast if the path to npm cache contains whitespaces (CP: 2.7)

- flow-server/src/main/java/com/vaadin/flow/router/Location.java
- flow-server/src/main/java/com/vaadin/flow/router/LocationUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/test/java/com/vaadin/flow/component/InvalidUrlTest.java
- flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java
- flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
Fixes #9443 for legacy bootstrapping mode.
IT and fix for Flow 3+ bootstrapping will come next. This commit can be picked to Flow 2.x with the IT from the other PR.
> fix: do not serve UI for invalid location

- flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
- flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
> fix: don't fire shortcut event if ancestor of component is not visible

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
Uses the same vaadin_versions.json file based pinning as with pnpm.
In case the application has @NpmPackage annotation with a certain version,
then that is used over the platform pinned version. When that is older,
a warning is logged (like with pnpm).
In case a dependency has been pinned directly in package.json, then that
is used over the platform pinned version. When that is older, a warning
is logged (like with pnpm).
Fixes #10572
> fix: pin platform trans. deps with npm CP: #10864

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Re-applied after adding a fix on components side - https://github.com/vaadin/flow-components/pull/2005.
Fixes: https://github.com/vaadin/flow-components/issues/1914
Note: to be merged to master only for now, to make sure it doesn't break the components again.
> fix: Remove old data provider listener on component attach

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Add `babel-loader` to devDependencies
to fix issue happening after npm 7.20.3
where the loader gets only installed into
a sub node_modules folder and not to root.
Closes #11584
> fix: fix build issue with npm 7.20.3+

- flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java
- flow-server/src/main/java/com/vaadin/flow/server/PageConfigurator.java
The previous deprecation message was totally lacking any details to the
users.
> fix: explain deprecation of PageConfigurator [skip-ci]

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Re-applied after adding a fix on components side - https://github.com/vaadin/flow-components/pull/2005.
TO BE MERGED AFTER https://github.com/vaadin/flow-components/pull/2012.
Fixes: https://github.com/vaadin/flow-components/issues/1914
> fix: Remove old data provider listener on component attach (CP: 8.0)

- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
- flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/InvalidLocationIT.java
Based on #11552 and to be rebased on top of it.
Fixes #9443 for Flow 3+ bootstrapping.
> fix: don't bootstrap UI for invalid location

- flow-server/src/main/java/com/vaadin/flow/component/Component.java
- flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
> feat: Implement Component.isAttached(). (#8810)

- flow-server/src/main/java/com/vaadin/flow/dom/ElementUtil.java
Removes usage of the deprecated TextNode constructor (String, String) in favour of the (String) constructor available in 1.11.x and 1.14.x allowing projects to upgrade the transitive jsoup depenency without waiting for an official release of vaadin at the user's own risk.
Relates #11609 
Targets 2.7 -> Should be ported to 2.6, 1.0(?), 7(?), 8(?)
> chore: change usage of deprecated TextNote constructor

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
The `3.0.0` version of the [construct-style-sheets-polyfill](https://github.com/calebdwilliams/construct-style-sheets) package is released as `latest` recently. This PR bumps the dependency version accordingly.
> refactor(flow-server): bump construct-style-sheets-polyfill version

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerImpl.java
The transfer encoding used between Vaadin and the webpack dev server might be different than the encoding used between the user and Vaadin. The latter is determined by the server.
When the encoding is included, loading chunks in dev mode with webpack 5 fails with ERR_INVALID_CHUNKED_ENCODING
> Do not copy transfer encoding from the webpack dev server

- flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
> fix: return ServletConfig during servlet destroy invocation

- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
- flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Fixes #9905 again. It was re-introduced in #11669
> fix: Do not use Flow namespace for information not related to Flow

- flow-client/package.json
It turns out that esbuild-loader supports webpack 4.40.0 and later which is an issue with strict peer dependencies mechanism in Node 16.
Fixes #11668
- Bugfix
> fix: bump webpack version in client package.json

- flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
> fix: return ServletConfig during serbvlet destroy invocation (#11625)

- flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
> fix: return ServletConfig during servlet destroy invocation (#11625)

- flow-server/pom.xml
- fusion-endpoint/pom.xml
- fusion-endpoint/src/test/java/com/vaadin/fusion/typeconversion/DateTimeConversionTest.java
- pom.xml
This fix rearranges version properties in `pom.xml` files: common versions are moved from `flow-server` and `fusion-endpoint` up to the root `pom.xml`; unused properties are cleared
> Organize dependency versions and update vulnerable jackson-databind version for fusion-endpoint

- flow-plugins/flow-maven-plugin/pom.xml
This overrides outdated and vulnerable `jackson-databind` and `httpclient` with a more recent yet compatible versions
> chore(deps): override frontend-plugin-core dependencies

- flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
The service worker referer filter for adding `CSRF` token to the index HTML page causes a problem that Endpoint doesn't work for Safari on refresh, since Safari never gets a CSRF token as it fetches the index page through the service worker once it has been installed.
https://github.com/vaadin/fusion/issues/84
> fix: remove the sw referer filter when adding csrf token

- fusion-endpoint/pom.xml
This overrides the following transitive dependencies of `swagger-codegen` with known vulnerabilities:
1. `slf4j-ext` 1.24.0 -> 1.32.0
2. `snakeyaml` 1.25.0 -> 1.26.0 (via `jackson-dataformat-yaml`)
This will silence SCA complaining about CVE-2017-18640 and CVE-2018-8088
> chore(deps): Override vulnerable dependencies

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
- flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Stops css/fonts from being loaded multiple times to the document with embedded applications.
Closes #11608
Contains fix #11669
> fix: keep track of css injected to document (#11635)

- flow-server/pom.xml
This reverts commit be77bbee86b94d343f8f028dac4902a8a737a50a.
This reverts version bump of `commons-fileupload` 1.3.3 -> 1.4
> Revert "chore(deps): bump commons-fileupload from 1.3.3 to 1.4 (#11742)"

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
This reverts commit a345446cd524b1122c6d780eebcf084078878b05 because it breaks icon usage in Start in Safari, see https://github.com/vaadin/flow/pull/11634.
> Revert "refactor(flow-server): bump construct-style-sheets-polyfill version (#11634)"

- pom.xml
Bumps commons-io to a newer version where this bug has been fixed https://issues.apache.org/jira/browse/IO-692.
Fixes #11794
> fix: bump commons-io from 2.8.0 to 2.11.0 (#11739)

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
- flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Stops css/fonts from being loaded multiple times to the document with embedded applications.
Fixes #11608
> fix: keep track of css injected to document (#11635) (#11673)

- flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/ClientSideExceptionHandlingIT.java
Windows receives a different error string
so we need to check the target os when
running the test.
Fixes #11777
> test: Fix expectation on windows

- flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/ClientSideExceptionHandlingIT.java
It would seem like chrome changed
the exception after last update making
it the same as was gotten on the
windows agent.
> chore: Update exception pattern

- flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
- flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java
> fix: make IPhone version above 14.7 browsers allowed for Vaadin

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Flag update of vaadin version as an addition
also and only write the package.json if
thee was an actual change in content.
Fixes #11259
> fix: Only write package.json if something actually changed

- flow-client/pom.xml
Some transitive packages that were
in a defined range got released built
on JDK11 instead of JDK8
> fix: Use jdk8 compatible package.

- flow-server/src/main/java/com/vaadin/flow/server/AppShellSettings.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
There are some methods on `AppShellSettings` that only work with legacy bootstrapping, marked those as deprecated, and throw unsupported exceptions to not confuse users.
Fixes https://github.com/vaadin/fusion/issues/60
> chore!: deprecate methods in AppShellSettings that require UI

- flow-client/pom.xml
Some transitive packages that were
in a defined range got released built
on JDK11 instead of JDK8
> fix: Use jdk8 compatible package. (#11855)

- flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/StreamResourceTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/StreamResourceHandlerTest.java
> fix: add possibility to set header values for StreamResource

- flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
- flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java
2.x branch should still support old edge versions also.
Fixes #11882
> fix: revert mistaken edge requirement for 2.x

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/resources/plugins/build-status-plugin/build-status-plugin.js
- flow-server/src/main/resources/plugins/build-status-plugin/package.json
- flow-server/src/main/resources/plugins/webpack-plugins.json
- flow-server/src/main/resources/webpack.generated.js
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPluginsTest.java
- flow-tests/test-mixed/pom.xml
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerImpl.java
Flow/Fusion currently uses webpack-dev-server 3.11.0, which depends on chokidar 2.x. According to sources, chokidar 2.x breaks/doesn't work properly on node 14+. Besides, this version of chokidar brings glob-parent with known vulnerability (https://nvd.nist.gov/vuln/detail/CVE-2020-28469), which is getting reported by Software Composition Analysis tools.
Fixes #11762
> chore: Upgrade webpack-dev-server to 4.0.0+

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
When running the application in
devMode and the vaadin-dev-server
dependency is missing, instead of an
assert when getting stats from dev derver
throw exception on missing dependency.
> fix: Throw exception in dev mode if dependency missing

- flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java
- flow-server/src/test/java/com/vaadin/flow/server/auth/ViewAccessCheckerTest.java
Makes default constructor of ViewAccessChecker enable security check by default.
Ands one more constructor to create a ViewAccessChecker with disabled security check.
Note that this is a breaking change, since `ViewAccessChecker()` CTOR changes it's semantics and brakes Spring based applications which use older versions of Spring add-on - even if Vaadin security helpers are not activated by extending the `VaadinWebSecurityConfigurerAdapter`, the access checker will be enabled anyway and the view access will be denied.
Latest Spring add-on version has a corresponding change. Consider review this change also https://github.com/vaadin/spring/pull/902.
Fixes #11231
> feat!: Add an option to enable access checker by default

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
Do not mark pin if no version is actually
added or changed.
With this npm install will not always be
executed on reload.
Fixes #11888
> fix: pinned dependency only adds when modified

- flow-client/pom.xml
- flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/ClientSideExceptionHandlingIT.java
Some transitive packages that were
in a defined range got released built
on JDK11 instead of JDK8
> fix: Use jdk8 compatible package (CP:1.0)

- flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
Adds the waiting loop to the ComponentThemeLiveReloadIT to ensure the tested component is rendered.
> test: Wait for the themed component to be present

- flow-tests/pom.xml
Moves theme-no-polymer test to the end of list, so it would be executed last.
Checks whether it impacts the theme live reload tests.
> test: Move theme no polymer test to the end of list

- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerImpl.java
https://github.com/vaadin/flow/pull/11783 introduced a bug that webpack is NOT running in development by default, which results in the `index.html` and `manifest.json` not emitted, which is the root cause of https://github.com/vaadin/fusion/issues/117.
This PR is not marked as a fix, since it's a continuation of https://github.com/vaadin/flow/pull/11783 which is not released yet.
Fixes https://github.com/vaadin/fusion/issues/117
> chore: run webpack in dev mode by default

- flow-server/src/main/java/com/vaadin/flow/server/Constants.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PushLongPollingWithPreserveOnRefreshIT.java
- pom.xml
> fix: Upgrade to Atmosphere 2.7.2 and Atmosphere JS 3.1.2

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinUtils.kt
- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
- flow-server/src/main/java/com/vaadin/flow/server/Constants.java
- flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsSettings.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerImpl.java
Enable automatic update of the node version
installed by the framework. Auto update is opt in,
but for a version that is older than what should
work it is updated automatically.
Closes #9864
> feat: Automatic update of node version

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/GlobalThemeView.java
- flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/GlobalThemeIT.java
Initialize document theme if initTheme
is true. Do not check for theme annotation
on the pageConfigurationHolder.
Fixes #11896
> fix: initialize theme without checking page configuration holder

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> fix: Deprecate old FrontendTools constructors

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
To enable copying of the exception
only clicking on `Close` closes the popup
Fixes #8964
> fix: Close only for click on Close

- flow-polymer-template/src/test/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandlerTest.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandler.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandlerTest.java
> feat: allow to use null from clients side with primitives

- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
To enable copying of the exception
only clicking on `Close` closes the popup
Fixes #8964
> fix: Close only for click on Close (#11955)

- flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
- flow-server/src/main/java/com/vaadin/flow/component/HasText.java
- flow-server/src/test/java/com/vaadin/flow/component/HasTextTest.java
- flow-server/src/test/java/com/vaadin/flow/component/WhiteSpaceTest.java
> feat: add WhiteSpace setter and getter methods

- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
> fix: return immidiately if VaadinSession is not initialized

- flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
- flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
> fix: return immidiately if VaadinSession is not initialized (#11974)

- pom.xml
This allows using `-Dbnd.skip=true` and save time during testing
> chore: Update bnd to latest in 3.x series

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
The original fix https://github.com/vaadin/flow/pull/4205 removed the temporary removal of the value change listener. Thus the comment is no longer valid and assert is no longer needed.
> chore: Remove obsolete comment and assert in Binder

- flow-tests/test-frontend/vite-basics/pom.xml
containerIncludeJarPattern is "A pattern to match against the urls of the jars on the container path to select those that should be examined for things like META-INF fragments, resources, tlds and class inheritance hierarchy" but the container path is not the class path but also includes all Maven dependencies like
org.apache.maven:maven-core:jar:3.8.2:compile
com.google.inject:guice:jar:no_aop:4.2.2:compile
com.google.guava:guava:jar:25.1-android:compile
> test: Fix most 'scanned from multiple locations' warnings

- flow-server/src/main/resources/vite.generated.ts
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/AbstractDevModeTest.java
Add watchdog to stop vite
when java handler exits or crashes.
Fixes #12060
> feat: add vite watchdog

- flow-server/src/main/java/com/vaadin/flow/internal/UrlUtil.java
- flow-server/src/test/java/com/vaadin/flow/internal/UrlUtilTest.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/AbstractDevServerRunnerTest.java
Allows project folders with spaces to work
Fixes #12221
> fix: Use encoded path for dev server

- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/WebpackHandlerTest.java
Tests currently fail randomly with something like
java.lang.IllegalArgumentException: Tried to create a server on port 46159 but it was already in use
at com.vaadin.base.devserver.WebpackHandlerTest.createStubWebpackTcpListener(WebpackHandlerTest.java:742)
at com.vaadin.base.devserver.WebpackHandlerTest.prepareHttpServer(WebpackHandlerTest.java:725)
at com.vaadin.base.devserver.WebpackHandlerTest.shouldNot_Handle_IndexHtmlInManifestPaths(WebpackHandlerTest.java:326)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
Caused by: java.net.BindException: Address already in use
at sun.nio.ch.Net.bind0(Native …
> test: try to make test more stable by letting the server choose the port

- pom.xml
Reverts vaadin/flow#12244
The plugin is no longer Java 8 compatible since 2.17.0. See https://github.com/revelc/formatter-maven-plugin/pull/533
> Revert "chore(deps): bump formatter-maven-plugin from 2.16.0 to 2.17.0"

- flow-tests/test-application-theme/test-reusable-as-parent/src/test/java/com/vaadin/flow/uitest/ui/theme/ParentThemeIT.java
- flow-tests/test-application-theme/test-theme-reusable/src/test/java/com/vaadin/flow/uitest/ui/theme/ReusableThemeIT.java
- flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/ServerSideForwardView.java
- flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/ServerSidePostponeView.java
- flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
- flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/ViewTestLayout.java
- flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
- flow-tests/test-embedding/embedding-test-assets/src/main/java/com/vaadin/flow/webcomponent/PreserveOnRefreshExporter.java
- flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/WebComponentIT.java
- flow-tests/test-embedding/test-embedding-theme-variant/src/test/java/com/vaadin/flow/webcomponent/ThemedVariantComponentIT.java
- flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/ProductionBasicsIT.java
- flow-tests/test-jetty-reload/src/main/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortView.java
- flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/MiscelaneousView.java
- flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/NpmThemedComponentIT.java
- flow-tests/test-multi-war/test-war1/src/main/java/com/vaadin/flow/multiwar/war1/MainView.java
- flow-tests/test-multi-war/test-war2/src/main/java/com/vaadin/flow/multiwar/war2/MainView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RouterLinkView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateNoShadowRootView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateShadowRootView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DirectionChangeIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/IFrameIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/NavigationTriggerIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PopStateHandlerIT.java
- flow-tests/test-router-custom-context/src/main/java/com/vaadin/flow/contexttest/ui/DependencyLayout.java
- flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Using `find . -name "*.java"|xargs java -jar google-java-format-1.12.0-all-deps.jar --fix-imports-only --skip-sorting-imports  -r`
> chore: Remove unused imports

- flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
- flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/StylePriorityView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StylePriorityIT.java
> fix: set style property priority using proper API method

- flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/common/AnnotationValuesExtractorTest.java
- flow-migration/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendWebComponentGenerator.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
This reverts commit 929b7207.
Reverted because this change causes class loading errors for Flow 2.7 Portlet integration.
> Revert "refactor: Use maven vaadin plugin classloader as a parent for URLClassloader in ClassFinder (#12050)  (#12171)"

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Auto-updates Node version when the Node is forced to be located in only alternative directory.
Fixes https://github.com/vaadin/flow/issues/12264
> fix: Auto-update Node for alternative directory

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Limits the number of requested items from backend to a given threshold of 1000 items.
(cherry picked from commit 0ec90bf144c596214d34a2ef82ca9cf7bc8aa28b)
> fix: Limit the requested pages to a given threshold (#12003)(CP: 2.7)

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Limits the number of requested items from backend to a given threshold of ten pages.
(cherry picked from commit 0ec90bf144c596214d34a2ef82ca9cf7bc8aa28b)
> fix: Limit the requested pages to a given threshold (#12238)(CP: 1.0)

- pom.xml
Certain Java 17 bytecode is not compatible with the version of ASM that byte-buddy brings in. That needs to be updated.
fixes #12136
> chrore: Update byte-buddy for better Java 17 compatibility

- flow-server/src/main/java/com/vaadin/flow/server/StaticFileHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
- flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
- flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
- flow-tests/test-application-theme/test-theme-reusable/src/test/java/com/vaadin/flow/uitest/ui/theme/ReusableThemeIT.java
- flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/UrlValidationIT.java
- flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/InvalidLocationIT.java
- flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
This simplifies static file handling so the same logic is not duplicate in two places. It also makes it possible to always query the dev server for files instead of knowing upfront what the dev server can serve.
The method is removed instead of retained as there are two ways it could have been used:
1. Called to check if a given request is a static resource request
2. Overridden in a custom StaticFileHandler
To keep the method we would need to do the following for the cases:
1. Make isStaticResourceRequest return serveStaticResource() != null
2. Make serveStaticResource() call isStaticResourceRequest() as the first thing
We cannot do both so it is safer to remove the method to force code to be updated
> refactor!: Remove StaticFileHandler.isStaticResourceRequest

- flow-client/src/main/frontend/Flow.ts
- flow-client/src/test/frontend/FlowTests.ts
- flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/HelloWorldView.java
- flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java
Fixes #12080
The client-side Vaadin Router does not attach components until the `onBeforeEnter` callback is run. However, when the Flow client initializes a server-side view, it assumes its container and the UI root are connected to the document. This concerns constructor timing as well as `AttachEvent` listeners.
This fixes the issue by pre-attaching the hidden container element created in the `Flow.ts` (the adapter for the client-side router) to the body.
> fix: ensure Flow client container is pre-attached on navigation

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
Without this you get
```
(!) outDir /.../project/target/classes/META-INF/VAADIN/webapp is not inside project root and will not be emptied.
Use --emptyOutDir to override.
```
> fix: Clean Vite production output folder on build

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
JavaDoc of hasChanges says
"Check whether any of the bound fields' have uncommitted changes since last explicit call to {@link #readBean(Object)}, {@link #removeBean()}, * {@link #writeBean(Object)} or {@link #writeBeanIfValid(Object)}."
If readBean has converters, they will be run and field values updated accordingly. Furthermore if fields have value change listeners that will produce further changes in values, this should be considered according to above as part of readBean producedure and thus hasChanges still should return false.
Cherry pick from: https://github.com/vaadin/framework/pull/12455
> fix: Clear changed bindings after initing field values

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
Reverts vaadin/flow#12304
This causes #12312
Should be added back after that is fixed but preferrably in the `vite.generated.js` instead
> Revert "fix: Clean Vite production output folder on build"

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
JavaDoc of hasChanges says:
"Check whether any of the bound fields' have uncommitted changes
since last explicit call to readBean(Object), removeBean(), writeBean(Object)}
or writeBeanIfValid(Object)."
If readBean has converters, they will be run and field values updated accordingly.
Furthermore if fields have value change listeners that will produce further
changes in values, this should be considered according to above as part of
readBean procedure and thus hasChanges still should return false.
Cherry pick from: vaadin/framework#12455
(cherry picked from commit 4e36fd979ec4d592d08e8d1328eeb4149c8fa3ef)
> fix: Ensure that side effects of readBean do not set hasChanges true (#12181)(CP: 2.7)

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
JavaDoc of hasChanges says:
"Check whether any of the bound fields' have uncommitted changes
since last explicit call to readBean(Object), removeBean(), writeBean(Object)}
or writeBeanIfValid(Object)."
If readBean has converters, they will be run and field values updated accordingly.
Furthermore if fields have value change listeners that will produce further
changes in values, this should be considered according to above as part of
readBean procedure and thus hasChanges still should return false.
Cherry pick from: vaadin/framework#12455
(cherry picked from commit 4e36fd979ec4d592d08e8d1328eeb4149c8fa3ef)
> fix: Ensure that side effects of readBean do not set hasChanges true (#12181)(CP: 8.0)

- flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevServerOutputTracker.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
> fix: Log dev server output using standard logger

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/resources/vite.generated.ts
- flow-tests/test-frontend/vite-production/pom.xml
- flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/CompressionIT.java
As Brotli is disabled by default, you need to enable it to use this feature.
https://github.com/vaadin/flow/issues/4740 will enable Brotli by default once server issues are sorted out
Fixes #12055
> feat: Compress Vite output by default in production

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
- flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Support vite build in the v14 bootstrap
to have exported webcomponents working.
Closes #12057
> feat: support vite in v14 bootstrap

- pom.xml
2.0.4 uses maven-enforcer-plugin 3.0.0 aligned with flow project after `restrict-imports-enforcer-rule` updates.
> chore: upgrade vaadin-parent version to 2.0.4 [skip ci]

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
This is both a optimization by skipping duplicate validation round and avoids ConcurrentModificationExpectation being thrown certain corner cases.
Cherry pick from: vaadin/framework#12360
> fix: Avoid processing value change event due writing back of converted value

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
It does not delete them from `target` as this will go away with the next clean.
Fixes #12335
> fix: Remove disused plugins from package.json

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
cherry pick: https://github.com/vaadin/flow/pull/12183
> fix: Avoid processing value change event due writing back of converted value (#12183) (CP: 2.7)

- flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
- flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Cherry pick of https://github.com/vaadin/flow/pull/12183
> fix: Avoid processing value change event due writing back of converted value (#12183) (CP: 8.0)

- fusion-endpoint/src/main/java/com/vaadin/fusion/FusionController.java
- fusion-endpoint/src/main/java/com/vaadin/fusion/FusionControllerConfiguration.java
- fusion-endpoint/src/main/java/com/vaadin/fusion/auth/CsrfChecker.java
- fusion-endpoint/src/main/java/com/vaadin/fusion/auth/FusionAccessChecker.java
- fusion-endpoint/src/test/java/com/vaadin/fusion/EndpointUtilTest.java
- fusion-endpoint/src/test/java/com/vaadin/fusion/FusionControllerConfigurationTest.java
- fusion-endpoint/src/test/java/com/vaadin/fusion/FusionControllerMockBuilder.java
- fusion-endpoint/src/test/java/com/vaadin/fusion/FusionControllerTest.java
- fusion-endpoint/src/test/java/com/vaadin/fusion/ServletContextTestSetup.java
- fusion-endpoint/src/test/java/com/vaadin/fusion/auth/CsrfCheckerTest.java
- fusion-endpoint/src/test/java/com/vaadin/fusion/auth/FusionAccessCheckerTest.java
- fusion-endpoint/src/test/java/com/vaadin/fusion/generator/endpoints/AbstractEndpointGenerationTest.java
CSRF checking is related to the HTTP request and not at all related to the access checker. If you use the access checker in another context such as a websocket message, you cannot do the same CSRF check nor do you need any CSRF check.
> refactor: Move CSRF checking from AccessChecker to FusionController

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerImpl.java
Disallows usage of Node 17.0.
Fixes #12246, #12285
> fix: Make webpack work with Node 17.1+

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
- flow-server/src/main/resources/vite.generated.ts
Enable https://github.com/fi3ework/vite-plugin-checker
Closes #12114
> feat: Add typescript checker plugin

- flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java
Testing a state tree with depth of 5000 seems excessive and has caused stackoverflow in the CI randomly.
> test: Make more stable on CI

- flow-client/src/main/java/com/vaadin/client/flow/StateTree.java
- flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
- flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java
- flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBusUtil.java
- flow-server/src/main/java/com/vaadin/flow/dom/DomEvent.java
- flow-server/src/main/java/com/vaadin/flow/dom/DomListenerRegistration.java
- flow-server/src/main/java/com/vaadin/flow/shared/JsonConstants.java
- flow-server/src/test/java/com/vaadin/flow/component/ComponentEventBusTest.java
- flow-server/src/test/java/com/vaadin/flow/component/MappedDomEventWithComponentData.java
- flow-server/src/test/java/com/vaadin/flow/component/MappedDomEventWithRouterLinkData.java
- flow-server/src/test/java/com/vaadin/flow/component/MappedToDomEventWithElementData.java
- flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementListenersTest.java
- flow-tests/test-root-context/pom.xml
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/AbstractEventDataView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ComponentEventDataView.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/EventTargetView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AbstractEventDataIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ComponentEventDataIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/EventTargetIT.java
Makes it possible to use event data expressions that map to any Component / Element from server side state tree.
For example it will be possible to use:
- `@EventData("event.target") Component eventTarget` for `@DomEvent`
- `@EventData("event.target") Element eventTarget` for `@DomEvent`
- `DomEventRegistration::addEventDataElement(String expression)` to get any element mapped,
- and fetch it with `DomEvent::getEventDataElement(String expression)`
Follow up for #11992, #3356
> feat: add support for @EventData of type Component

- flow-server/src/main/java/com/vaadin/flow/component/HeartbeatEvent.java
- flow-server/src/main/java/com/vaadin/flow/component/HeartbeatListener.java
- flow-server/src/main/java/com/vaadin/flow/component/UI.java
- flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
- flow-server/src/test/java/com/vaadin/flow/component/UITest.java
- flow-server/src/test/java/com/vaadin/flow/server/communication/HeartbeatHandlerTest.java
Moves `HeartbeatEvent` and `HeartbeatListener` from the internal package into the public packages.  
Creates a new method `UI::addHeartbeatListener` as public API to use instead of the internal API from `UIInternal`.
Fixes #12295 
- [ x I have performed self-review and corrected misspellings.
> feat: add HeartbeatListener to UI

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
While this might break some pnpm case, it will still help more to have consistent behavior across npm versions. Also the cases it might break are already broken for many users (npm 7+)
Fixes #11963
> fix: Do not use --ignore-existing which is only available in npm 6

- flow-server/src/main/resources/com/vaadin/flow/server/frontend/vite-devmode.ts
> fix: Prevent Vite from reloading if live reload has been turned off

- flow-server/src/main/resources/vite.generated.ts
Fixes the PWA section in the vite config file
> chore: reflect that builderFolder was renamed frontendBundleFolder in PWA config

- flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
Fixes #12442
Firefox 78 brings support for unicode property escapes, which
are used in Vaadin 22 and later since vaadin/web-components#2815.
> fix: Require Firefox 78 or later

- flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
- flow-tests/test-embedding/test-embedding-reusable-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
No flakiness seen in 9 executions.
Re-enable tests for 2.8 and 2.7
Closes #10331
> chore: enable ignored tests

- fusion-endpoint/src/main/java/com/vaadin/fusion/FusionControllerConfiguration.java
Fixes compatibility with Spring Boot 2.6, which uses PathPattern matching.
> fix(Fusion): support PathPattern parsed mapping for endpoint prefix

- flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
The current behavior renders an additional error page below the current error page if an error occurs when navigating from the error page (which happens if you click on a view you do not have access to)
> fix: Render only one error page when trying to go to a view without access

- flow-server/src/main/java/com/vaadin/flow/router/EventUtil.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshNestedBeforeEnterCounter.java
- flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshNestedBeforeEnterView.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshNestedBeforeEnterIT.java
Fixes a bug where the stream of `BeforeEnterObserver`s could contain duplicates, causing extraneous calls to `BeforeEnterObserver::beforeEnter` for non-root components.
Fixes #12356
> fix: remove duplicates when collecting BeforeEnterObservers

- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
The info file isnow cleaned
after the build as else we
miss all the information for the
build settings
> fix: clean info after build

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Remove duplicate install locally string
and use the one from FrontendTools that
has the version as DEFAULT_NODE_VERSION
> chore: fix install locally string

- flow-plugins/flow-maven-plugin/pom.xml
Set all org.apache.maven  artifacts to
provided scope.
Fixes #12499
> fix: add scope to dependencies

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/utils/LookupImpl.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendWebComponentGenerator.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
- flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriter.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullScannerPwaTest.java
- flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriterTest.java
Do not squash!
This reverts commit 51837be415104765231ae072e725a024f1ea658d and fd22ee99cba158ba8e261e33f8e8f554904706c2  due to Maven plugin classloader throwing ClassNotFoundException for Spring classes during class scanning.
> Revert use maven plugin classloader as parent

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
#Remove duplicate install locally string
and use the one from FrontendTools that
has the version as DEFAULT_NODE_VERSION
> chore: fix install locally string (#12505)

- flow-plugins/flow-gradle-plugin/pom.xml
This should fix problems when running the build in docker containers in windows.
> chore: replace exec-maven-plugin with gradle-maven-plugin

- pom.xml
Should remove the warning
The POM for com.sun.xml.bind:jaxb-core:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
> chore: Upgrade jaxb

- flow-client/pom.xml
Reverts vaadin/flow#12540
Needs [bump of java](https://github.com/vaadin/flow/pull/12440) previous to this .
> Revert "chore(deps-dev): bump org.eclipse.core.contenttype from 3.7.1000 to 3.8.100"

- flow-server/src/main/java/com/vaadin/flow/component/UI.java
- flow-server/src/test/java/com/vaadin/flow/component/UITest.java
> fix: Do not throw NPE for UI.access called when session has expired (#12531)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
This should ease debugging of problems like "UnknownVersionException: Unable to detect version of pnpm"
> fix: output version string when version parsing fails

- .github/workflows/validation.yml
- scripts/computeMatrix.js
This build implementation:
- introduces a script which makes easier configure slices of modules and tests
- improve performance by reducing times in 30-60 secs
- latest job is red when any of the parallel jobs fails, which makes easier configure branch checks for PRs
> test: add script for better control of module/test splitting 

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
- flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexHtml.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateServiceWorker.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateViteDevMode.java
- flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
> chore: close streams

- flow-client/package.json
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
A customer has been using `this.shadowRoot?.elementFromPoint` method which got broken in TS 4.4 (Vaadin 21) due to lib DOM type definition changes. In V22 with TS 4.4 it requires additional casting workaround to be able to call that method. This should be resolved by upgrading to TS 4.5 ([change in TS](https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1123)). Related: https://github.com/WICG/webcomponents/issues/661#issuecomment-992262771
> Bump TypeScript to 4.5.3

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
While this might break some pnpm case, it will still help more to have consistent behavior across npm versions. Also the cases it might break are already broken for many users (npm 7+)
Fixes #11963
> fix: Do not use --ignore-existing which is only available in npm 6 (#12406)

- flow-tests/pom.xml
- flow-tests/test-application-theme/test-theme-component-live-reload/pom.xml
- flow-tests/test-application-theme/test-theme-live-reload/pom.xml
- flow-tests/test-application-theme/test-theme-switch-live-reload/pom.xml
- flow-tests/test-ccdm-flow-navigation/pom-production.xml
- flow-tests/test-ccdm-flow-navigation/pom.xml
- flow-tests/test-ccdm/pom-production.xml
- flow-tests/test-ccdm/pom.xml
- flow-tests/test-embedding/test-embedding-reusable-theme/pom.xml
- flow-tests/test-frontend/vite-basics/pom.xml
- flow-tests/test-fusion-csrf-context/pom.xml
- flow-tests/test-fusion-csrf/pom.xml
- flow-tests/test-jetty-reload/pom.xml
- flow-tests/test-live-reload/pom.xml
- flow-tests/test-mixed/pom-npm.xml
- flow-tests/test-mixed/pom.xml
- flow-tests/test-npm-only-features/pom.xml
- flow-tests/test-root-context/pom.xml
- flow-tests/test-root-ui-context/pom.xml
Sets reuseDevServer to false for all modules to ensure that webpack is killed when jetty is stopped
> test: fix memory leak in tests during build

- flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
- flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
Disabling and enabling component using the Java API now works as expected. href is always saved in the component implementation, but not stored in element if disabled.
Fixes #10924
> fix: Proper handling of href when the anchor is disabled/enabled

- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/AbstractGradleTest.kt
- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
Gradlel tests should by default use
local maven cache repo to get packages.
> test: Gradle tests must use local repo

- .github/workflows/validation.yml
- flow-tests/pom.xml
- flow-tests/test-application-theme/pom.xml
- flow-tests/test-embedding/pom.xml
- flow-tests/test-frontend/pom.xml
- flow-tests/test-fusion-csrf/pom.xml
- flow-tests/test-multi-war/test-war2/pom.xml
- flow-tests/test-root-context/pom.xml
- scripts/computeMatrix.js
- Fix script for visiting modules recursively
- Adjust weight and position parameters to optimise build
- Group tests that use shared modules for better timings
- Cache maven repositories
- Configure correctly action events
- Introduce profiles for installing shared modules, so as they can be
used when running verify in other modules independently
- Add check_run_annotations parameter to test reports
This PR increases the number or IT modules run from 36 to 78, now validation lasts ~11-13 mins instead of ~8-10
> test: run tests in sub-sub-modules

- scripts/computeMatrix.js
There are modules that are run twice because the recursive visit returns duplicates in cases with profiles for shared modules.
> test: remove duplicates from the module list

- fusion-endpoint/src/main/java/com/vaadin/fusion/FusionControllerConfiguration.java
Fixes #12623
With Spring Boot 2.6, PathPattern matching is a default, however with
2.4 / 2.5 Spring MVC still uses string-based pattern matching for paths.
This fixes compatibility with string-based pattern mapping mode when
prepending the endpoint path prefix.
> fix(Fusion): Spring Boot 2.4 string patterns request mapping compatibility

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
npm 8.3 includes the package version override feature which allows us to deal with dependency conflicts in a better way
> chore: Upgrade to Node 17 + npm 8.3

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Update exception for failing to
remove node_modules folder.
Closes #12655
> fix: better exception for failing removal

- flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Check if `node -p 'crypto.createHash("md4")'` works. If not,
pass the `--openssl-legacy-provider` flag. Workaround for:
https://github.com/webpack/webpack/issues/14532
Fixes #12649
> fix: check if --openssl-legacy-provider required for Node (#12675)

- flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
Since isAttached is trivially tail-recursive, use a loop instead of recursion.
Reduces memory consumption in tests that construct deep trees.
> refactor: make isAttached iterative

- flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
Get the push suspend timout
parameter from the configuration
as atmosphere doesn't read it
from anywhere.
Fixes #12559
> fix: use configured push parameter

- flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
Works around connection issue with webpack-dev-server 3.11.0 and Node 17+.
Fixes #12546.
> fix: add wepack dev server parameter --host=127.0.0.1

- flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
- flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
- flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
- flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
- flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
- flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Use node version and url properties if defined.
Force home node also in plugin if set.
part of #12686
> fix: Always use defined node version

- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
- flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
Remove jcenter from all gradle tests
as the repository is shutting down for good.
> chore: remove usage of jcenter

- flow-server/src/main/java/com/vaadin/flow/internal/UsageStatistics.java
Related to https://github.com/vaadin/flow/pull/12718#discussion_r784755431. 
Tried to have a test of the setting system property to null, but then it throws NPE when calling `System.setProperty("xx", null);`
> chore: fix potential NPE in usagestatistics

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/AbstractDevServerRunnerTest.java
Need to pass --openssl-legacy-provider to make
Webpack 4 work with Node 17 in some cases. Now
also when invoked as part of `build-frontend`.
Fixes #12732
> fix: --openssl-legacy-provider also in build-frontend

- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyLocalFrontendFiles.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyLocalFrontendFilesTest.java
When copying the local frontend files
remove any read-only flags from the
copies.
fixes #12711
> fix: Remove read-only flag on copy

- flow-tests/test-frontend/test-npm/package-lock.json
Update package lock for test-npm
module to get newer versions.
Fixes github dependabot alerts
> chore: update test package-lock

- flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
If the version in vaadin or dependenices
is not a valid version, but a string like
next/latest compare string content to
determine if they equal.
> fix: handle non versions in isUserChanged

- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/stats/StatisticsSenderTest.java
When binding to all interfaces it seems that the http server can choose a port that is in use for localhost but free for other interfaces
> test: Bind to localhost to ensure the port is free

- flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
- flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
Need to pass --openssl-legacy-provider to make Webpack 4 work with Node 17 in some cases. Now also when invoked as part of build-frontend.
Fixes #12732
> fix: --openssl-legacy-provider also in build-frontend (#12726)

- fusion-endpoint/src/main/resources/META-INF/spring.factories
Related to https://github.com/vaadin/flow/pull/12741, the `FusionController` package name was unintentionally removed by the IDE during refactoring.
> chore: add controller package name to spring.factories

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
This fixes some random build issues where webpack exits with code 139
> fix: Force an older babel version

- flow-tests/test-npm-only-features/test-npm-no-buildmojo/pom.xml
Module `flow-test-npm-no-buildmojo` has a `maven-clean-plugin` execution configuration to delete `node_modules/@vaadin/*`, `node_modules/@polymer/*` and `target/package-lock.json`.  However, since `node_modules/.vaadin/vaadin.json` is not deleted, successive runs do not perform `npm install`, causing the build to fail due to missing modules.
This change replaces the `maven-clean-plugin` execution with `flow:clean-frontend`, that performs a more complete cleanup,
making multiple test runs complete successfully.
> test: replace maven-clean-plugin execution with flow:clean-frontend

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
- flow-test-generic/src/main/java/com/vaadin/flow/testutil/FrontendStubs.java
When project or global node version is detected but deemed incompatible with Vaadin, alternative node installation (~./vaadin/node) is used as fallback (and downloaded if not present).
Fixes #12494
> feat: Fallback to alternative node when preferred is unsupported

- flow-server/bnd.bnd
The customized `atmosphere-runtime:2.7.3.slf4jvaadin3` exports packages
with version `2.7.3` (i.e., not `2.7.3.slf4jvaadin3`). Depend on exporting bundle 
version instead of the package version.
> fix: use bundle-version instead of package version

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
This fixes some random build issues where webpack exits with code 139
> fix: Force an older babel version (#12781)

- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Reverts vaadin/flow#12781
This fix is no longer needed as `@babel/core` 7.6.11 is released with a fix.
> Revert "fix: Force an older babel version"

- flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
- flow-tests/test-application-theme/test-theme-switch-live-reload/pom.xml
- flow-tests/test-application-theme/test-theme-switch-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeSwitchLiveReloadIT.java
- flow-tests/test-embedding/test-embedding-reusable-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
- pom.xml
The builder was executed twice, most
likely due to a merge conflict.
> fix: remove duplicate builder execution

- vaadin-dev-server/src/test/java/com/vaadin/base/devserver/stats/AbstractStatisticsTest.java
When calling DevModeUsageStatistics.init, there is a check to see if stats should be sent immediately. If this is triggered, then there will be two post requests going out in a test, with the response of the real test request potentially being overwritten by the response to the automatic request.
> test: Do not send any data from tests automatically

- flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlags.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlagsTest.java
Adds a task for generating a `feature-flags.ts` file that defines globals for all feature flags. The globals can then be used by Vaadin web components, or application code, to check whether a feature was enabled in the Java app. The file is then imported from the bootstrap file.
This also adds a feature flag for the map component that is currently in development, which would be the first Vaadin component to make use of these globals. See PR here: https://github.com/vaadin/web-components/pull/3321
We want to move this flag into this repo in order to re-use the existing constructs around feature flags, provide a consistent experience for using them for our users, and to support toggling the flag using the debug tools in Flow and Hilla apps.
Part of …
> feat: add task for generating client-side feature flags file

- flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
There are some error messages that always mention Webpack as the trouble source even though they are also used for Vite. This PR fixes such messages so that they mention the frontend tool that is actually used.
Fixes #12767
> fix: don't mention Webpack in error messages when Vite is used

- flow-tests/test-embedding/test-embedding-production-mode/pom.xml
The `deploy-war` target no longer exists in Jetty 10
> test: Delete seemingly unnecessary war deployment

- flow-tests/test-memory-leaks/src/test/java/com/vaadin/flow/memoryleaks/ui/RedeployLeakIT.java
`org.eclipse.jetty.util.log.JavaUtilLog` is no longer available in Jetty 10
> test: Delete seemingly unnecessary properties

- flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
- fusion-endpoint/src/main/java/dev/hilla/EndpointController.java
- fusion-endpoint/src/main/resources/connect-client.default.template.ts
- fusion-endpoint/src/main/resources/dev/hilla/generator/EntityModelTemplate.mustache
- fusion-endpoint/src/test/java/dev/hilla/frontend/TaskGenerateEndpointTest.java
- fusion-endpoint/src/test/resources/dev/hilla/generator/expected-connect-client-custom.ts
- fusion-endpoint/src/test/resources/dev/hilla/generator/expected-connect-client-default.ts
- fusion-endpoint/src/test/resources/dev/hilla/generator/tsmodel/expected-TsFormEndpoint.ts
fusion npm packages are renamed to hilla, updating the code accordingly
Fixes https://github.com/vaadin/hilla/issues/188
Depends on https://github.com/vaadin/hilla/pull/191
> feat!: rename fusion npm packages to hilla

- flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
Code cleanup
fixes: https://github.com/vaadin/flow/issues/12807
Note, exception is thrown here: https://github.com/vaadin/flow/blob/2.8/flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java#L178
But earlier session.getService() did not throw https://github.com/vaadin/flow/blob/2.8/flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java#L157
Hence I assume using stored service reference will make code less prone to throw
> fix: Use service already assigned

- flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java
Instead of throwing an exception if the
client has closed the stream socket, log a
message in debug mode.
Closes #12646
> fix: Log exception for closed socket

- flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
- flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorAsyncTest.java
In async mode data fetching is wrapped in the future
This version is for Vaadin 14.8
fixes: #1066
fixes: #10709
fixes: #12342
> feat: Add async mode to flush operation and API to turn it on

- flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
The wait commands never finish but the test waited for a timeout to occur. 
The behavior is correct because just copying a new file to the theme folder should not cause any reloads to happen.
> test: speed up test significantly

- flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
- flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Do not set permissions nor follow symlinks when 
deleting node_modules.
Fixes #12810
> fix: reliable deletion of node_modules

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Even if there were seemingly undeletable
files we should at the end check if the
node_modules folder still exists before
throwing an exception.
> fix: Check if node_modules exists

- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ModalDialogIT.java
Sometimes `findElements(By.tagName("div"))` returns an empty list, maybe because server roundtrip has not yet completed.
This change adds wait condition to ensure the presence of the newly added element before doing assertions.
Fixes #12756
> test: ModalDialogIT Wait for child element presence before performing assertions

- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutIT.java
- flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DialogShortcutIT.java
Sometimes findElements(By.tagName("div")) returns an empty list, maybe because server roundtrip has not yet completed.
This change adds a wait condition to ensure the presence of the newly added element before doing assertions.
Fixes #10481
Fixes #10487
Fixes #10491
> test: DialogShortcutIT Wait for child element presence before performing assertions

- flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Even if there were seemingly undeletable
files we should at the end check if the
node_modules folder still exists before
throwing an exception.
> fix: Check if node_modules exists (#12843)

- flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/ImportExtractor.java
- flow-server/src/test/java/com/vaadin/flow/internal/StringUtilTest.java
Do not throw silently for incompatible
import paths. Fix comment removal
for JS files to accept ' as string.
fixes #12765
> fix: handle faulty imports

- flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
The test performs some check on vaadin-text-field internal elements,
but it seems it is not up to date with the current web component structure.
This change adapts search criteria used to find internal elements.
Fixes #11928
> test: Adapt ComponentThemeLiveReloadIT for changes in vaadin-text-field structure

- flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
- flow-server/src/main/java/com/vaadin/flow/server/frontend/ImportExtractor.java
- flow-server/src/test/java/com/vaadin/flow/internal/StringUtilTest.java
Do not throw silently for incompatible
import paths. Fix comment removal
for JS files to accept ' as string.
fixes #12765
> fix: handle faulty imports (#12793)

- flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
This should not be needed but we cannot have this blocking all builds until somebody figures out the reason
> test: Increase npm timeout

- flow-data/src/main/java/com/vaadin/flow/data/converter/StringToUuidConverter.java
No other converter logs a conversion error, which makes sense as you do not want to see all invalid input in your server logs
> fix: Do not log conversion error in StringToUuidConverter

- flow-data/src/main/java/com/vaadin/flow/data/converter/StringToUuidConverter.java
No other converter logs a conversion error, which makes sense as you do not want to see all invalid input in your server logs
> fix: Do not log conversion error in StringToUuidConverter (#12882) (CP: 2.7)

- flow-data/src/main/java/com/vaadin/flow/data/converter/StringToUuidConverter.java
No other converter logs a conversion error, which makes sense as you do not want to see all invalid input in your server logs
> fix: Do not log conversion error in StringToUuidConverter (#12882) (CP: 2.8)
